### ISSUE TITLE
"Other specific risk"-filter is missing

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10133]
### Bug Description

In the Event Directory the filter "Other specific risk" is not displayed. 

### Steps to Reproduce

1.
2.

### Expected Behavior

Filter with the values: Unknown, Political risk, Media risk is visible and can be used. 

### System Details

* Device: Laptop
* SORMAS version:  1.74.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/
* User Role: Admin National User, Community Officer

**Comment by MateStrysewske** [comment]
@KernB Are you sure that those values have been set up on that system? Because I also can't see them when editing an event, which makes me wonder whether they've been added to the database in the first place. Please note that "Other specific risk" is a customizable enum field, so if nobody has added values to the database, it's expected that the filter is not displayed.

**Comment by KernB** [comment]
With the ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/5940 the function was introduced. 
Further research has shown that this field is not used in Germany.
