### ISSUE TITLE
Synchronization of the mobile app is not successful  

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10231]
### Bug Description

When trying to synchronize the mobile app with the server, an error message is displayed stating that the synchronization was not successful.

The synchronization does not work when it is triggered manually from any directory, or from 'Settings' - 'Re-synchronize data' button.

Note: I have some user roles configured manually and users created based on those user roles.
Note2: there are entities created currently whose diseases have been disabled from the DB.

### Steps to Reproduce

1. Have both the vaadin-app (Admin+NatUser) and the android-app open (Surveillance Officer);
2. Do a synchronization of the mobile app to check that it is successful;
3. In the vaadin-app navigate to the 'Users' directory and create a new configurable user role (Surveillance Officer (default) with jurisdiction set to Nation);
4. Create a new user with the user role created at step 3;
5. Refresh the vaadin-app then trigger a synchronization with the server in the android-app.

GIF of the behavior and the steps to reproduce:
![SyncUser](https://user-images.githubusercontent.com/96909231/188391112-bc0b6afb-0162-4b61-8aa8-db224d5792b0.gif)

### Actual Behavior

An error message is displayed and the synchronization is not successful. 
![image](https://user-images.githubusercontent.com/96909231/187209947-a306a470-15f5-469d-b726-1e5a500ad6fc.png)

Logs from the local machine:
 
[sync mobile.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9444502/sync.mobile.txt)

### Expected Behavior

Synchronization with the server should be successful. 

### System Details

* Device:  Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.76.0-SNAPSHOT(ae4bf18)
* Android version/Browser: Chrome (vaadin-app); Android 11 (android-app)
* Server URL: local machine
* User Role: Admin+NatUser (vaadin-app); Surveillance Officer (android app)

### Additional Information

Tested the synchronization with both old, existing users, and newly created ones - the same error is displayed in the logs.

Also, no entities are displayed in any directory in the mobile app.

**Comment by JonasCir** [comment]
@adinaflorea9 can you check #10250 if this is the same?

**Comment by adinaflorea9** [comment]
@JonasCir from what I can see, comparing the logs that I attached to this ticket and what Zohaib attached to his, the error is not 100% the same, but both of them mention a reference to a null object:

This is from Zohaib:
![image](https://user-images.githubusercontent.com/96909231/187660949-3b2b1850-ecc9-4998-b18b-310c7b9ed22f.png)

And this is from my local machine:
![image](https://user-images.githubusercontent.com/96909231/187661163-5aa57b71-3383-4c80-9fc1-07dc79d93af7.png)

**Comment by roxanamlendea** [comment]
The synchronization is not working on my local server also. This is the error that I get.
![image](https://user-images.githubusercontent.com/89522688/187675332-b20ee450-b9bc-4ee8-8569-8197d0044d9d.png)

I attach the logs for this sync error. 
[logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9461368/logs.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (73ef5ba) from the development branch and in Android Studio connected to the local server.

**Comment by StefanKock** [comment]
Needs to be cherry-picked to hotfix-1.75.2

**Comment by zohaibhassan122** [comment]
I was testing 1.76.0 Version and I am still facing the failed sync. I have attached the video and error log, please fix it, otherwise, 1.76.0 cannot be approved as stable for sure. Further details are below:

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.76.0
* Android version: 1.76.0
* Android Version: 11
* User Role: Hospital Informant
*URL: https://release-international.sormas.netzlink.com/sormas-rest/


FYI: @MateStrysewske  @MartinWahnschaffe @bernardsilenou 

[sync_error_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9820752/sync_error_log.txt)

https://user-images.githubusercontent.com/8872102/196700709-9988162f-91c1-4409-abc1-df3791007d2e.mp4

**Comment by roxanamlendea** [comment]
If you install an older apk version (1.74.0) it means that you're testing on Sormas 1.74. The ticket #10231 was about the synchronization that was failing because the DB contains configured user roles. The problem was fixed in Sormas 1.75.2.

Also, I rechecked on https://release-international.sormas.netzlink.com/sormas-rest/ (Sormas 1.76) and I couldn't reproduce the issue.

**Comment by zohaibhassan122** [comment]
@roxanamlendea,
The use case is the following,

1. SORMAS 1.74.0 was running and the user has the mobile app for 1.74.0
2. Now we upgraded the server from 1.74.0 to 1.76.0.
3. Now when a mobile user opens the app and it asks for an update because the server has been updated.
4. Once the new apk is downloaded and installed, I cannot do any more sync. 

Did you install the first 1.64.0 or 1.74.0 and try to update it?

The problem is that we cannot ask our all users to uninstall the app and download 1.76.0 directly and then sync everything again because first, they will lose data that is already collected in-app and not synced and it will become big operation only because the mobile app update feature is not smooth. 

Let me know if you need any further explanation.

**Comment by zohaibhassan122** [comment]
Hi @roxanamlendea,

I have created a new issue #10698 .  You can always download all older versions apk from GitHub. Just select the version tag, download the SORMAS and you can have it.

**Comment by roxanamlendea** [comment]
@zohaibhassan122  Thank you :)
