### ISSUE TITLE
'A problem has occurred' message appears when a National Clinician attempts to edit data

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10232]
### Bug Description

An error message is displayed when a National Clinician attempts to save changes made on an immunization.

The National Clinician has the user roles:
![image](https://user-images.githubusercontent.com/96909231/187213057-7ffb0bf3-2cdb-4883-be0d-e5a87757fa72.png)

### Steps to Reproduce

1. Log into the app with a National Clinician;
2. Navigate to the 'Immunizations' directory and create a new immunization;
3. Open the immunization created at step 2 and make a change on it;
4. Click 'Save' at the bottom of the page.

### Actual Behavior

An error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/187213654-208d962a-6313-49af-ab98-208a682bbf6b.png)

Logs from the local machine:
[logs immunizations.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9444976/logs.immunizations.txt)

### Expected Behavior

The National Clinician should be able to successfully edit and save an immunization.

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(ae4bf18)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: National Clinician

### Additional Information

Note: the behavior is not reproducible on the release version 1.74.3.

**Comment by adinaflorea9** [comment]
#10172 - closed as duplicate of #10232

**Comment by MateStrysewske** [comment]
Same happens for e.g. cases, see #10494.

**Comment by MateStrysewske** [comment]
@carina29 We'll solve the pseudonymization issue in this particular issue like this:

- Remove the `@NotNull` annotation from the `reportingUser` field
- Ensure that we check for the `reportingUser` field being not null in the backend/that the field is not null in the database so that there's no way to create data without a reporting user

**Comment by carina29** [comment]
@NotNull field will be deleted from the reportingUser field from the following DTO classes:
CaseDataDto, ContactDto, EventDto, EventParticipantDto, ImmunizationDto.

The above mentioned error message related to the reportingUser was thrown in case of editing a case or an immunization ( after creation) and for both (case and immunization edit) the problem will be solved in this ticket.

Due to the current pseudonymizeUser() implementation, based on the existent checks, the reportingUser field will be pseudonymized in case of a National Clinician when isConfiguredToCheck is true (for National Clinician sensitiveDataFieldAccessChecker.hasRight() = false).
![image](https://user-images.githubusercontent.com/47103965/194072592-5eb5bd36-54f7-46ab-92e9-9412385e6f4b.png)

In this case the reportingUser will not be displayed on the UI:
![image](https://user-images.githubusercontent.com/47103965/194072754-c94de011-1057-4a04-bee8-01aec8c7e207.png)

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.76.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/c76bbe1b74ccdac7b084a3c7355b47069686ce5b)
Used user: Admin, National Clinician
