### ISSUE TITLE
Directories are hidden in the mobile app when the user changes the language right before logging out

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10258]
### Bug Description
When the user changes the language right before logging out, when the logs back again, all the directories are missing.

### Steps to Reproduce

1. Log in the mobile app with a SurvOff user; ( the language is set to English);
2. Navigate to Settings and change the language to German;
3. Then click 5 times on the Sormas version in order to make the log out option visible;
4. Click on Log out;
5. Log in again with the same user from step 1;

### Actual Behavior
All the directories are missing.

### Expected Behavior
All directories should be displayed as before and should work normally.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/187865627-1af80e43-f603-4d7f-a956-b42af3982a5b.png)

### System Details

* Device: Android 11 phone
* SORMAS version: Sormas 1.76.0-SNAPSHOT and Sormas 1.75
* Android version/Browser: Android 11
* Server URL: test-de.sormas.netzlink.com and release-international.sormas.netzlink.com
* User Role: Surv Off

### Additional Information
The bug was found while testing ticket #10132.

**Comment by dinua** [comment]
This bug happened because the user was no longer had rights/roles in application

When a user was changing the language, the roles of the users were deleted from the mobile database and the list of roles was empty to add new roles to database.
Until the user logout everything was fine because we took the old settings of the users (with existing roles added), but after the user log out he had no longer roles in database to fetch and he had no longer permissions to see the menu

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Congo users (mobile app and server in Franch) reported this same issue after auto upgrade to 1.74.3

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(643e1c7).
