### ISSUE TITLE
Mobile app synchronization is being failed. 

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#10250]
### Bug Description

Whenever I try to sync the data from the mobile app, it's getting failed. I have attached the logs for refreence. 

### Expected Behavior

The data should be synced. 

### System Details

* Device:
* SORMAS version: 1.73.3
* Android version: 1.73.3
* Server URL: https://inhp-ci.sormas.netzlink.com/sormas-rest/
* User Role: Hospital informant. 

### Additional Information

[Abou_android-debug.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/9460269/Abou_android-debug.log)
[Abou2_android-debug.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/9460270/Abou2_android-debug.log)

FYI: @bernardsilenou @MartinWahnschaffe @MateStrysewske @BasilKaburi

**Comment by MateStrysewske** [comment]
@zohaibhassan122 Can you please check whether this error persists in the current development version, i.e. 1.76.0? Preferably on a server with no custom user roles created, because there's a known synchronisation issue that we're currently taking care of that involves those.

**Comment by bernardsilenou** [comment]
@MateStrysewske These logs were obtained from a production server ( v1.73.3) that is suppose to host only an applroved version. The server has only default user roles.
- Can there not be another quick solution rather than waiting until 1.76 is approved?

**Comment by MartinWahnschaffe** [comment]
The log provided seem to stem from another problem, which is triggered when changing the language. It is solved by this issue #10132
The problem reported in this ticket is extremely the one fixed by #10231.

We should backport both fixes to 1.75.2.

Commits to bring into 1.75.2:
* https://github.com/hzi-braunschweig/SORMAS-Project/pull/10290/commits/5de4bab22d1d5541cce09c8740877aa6feee913f
* https://github.com/hzi-braunschweig/SORMAS-Project/pull/10221/commits/1b9586281660eed7c99478eef9f40580c807eef5

**Comment by StefanKock** [comment]
I discussed with @MateStrysewske that we maybe would reopen #10132  and #10231 to go into a 1.75.x version. That means that this ticket will then be closed as duplicate.
