### ISSUE TITLE
Visibility of event participants after archiving the event

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10298]
### Bug Description

A change was introduced with the ticket. 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/8723

The change is only visible after an unexpected reload of the page. 

### Steps to Reproduce

1. Archive an event with participants
2. Change to the event participant view. 

### Expected Behavior

The existing participants should be displayed directly. 
The value of the filter seemed to be cached. The display should show the participants independently of the saved value 

### Screenshots

![Event-Participant](https://user-images.githubusercontent.com/101708230/188872504-4209a4ed-3f9c-4f3c-8612-4c4fbb432d47.gif)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL: test1401and release-international
* User Role: Admin

**Comment by MateStrysewske** [comment]
I believe the value of the field being cached is done on purpose so that users don't always have to change it if they navigate back to the page. Imagine a user only wanting to display active EPs and then go into some of them, change something, and go back to the event. Always having to change the filter would be pretty tedious in this situation. So I think this is something we need to discuss, evaluating all possible scenarios.

**Comment by adinaflorea9** [comment]
@MateStrysewske As @KernB specified in this ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/8723 introduced the request that when events are archived, the filter on the 'Event Participants' tab is set by default to 'All event participants'.

The behavior seems to have been changed in the meantime and the value from that filter filed is cached indeed, but at a time when it does not necessarily make sense to be cached. 

The behavior described below is reproducible regardless of whether the feature type EDIT_ARCHIVED_ENTITIES is set to 'true' or 'false' in the DB.
Steps to reproduce:
1. In the vaadin-app, create an event and observe the value displayed in the filter field;
->it is set to 'Active event participants', as expected;
2. Refresh the page;
-> it is set to 'Active event participants', as expected;
3. From the event page, archive the event;
4. Observe the filter value in the 'Event participants tab';
-> filter value remained set to 'Active event participants' - not the expected behavior;
5. Refresh the page:
-> only now the filter value is set to 'All event participants' - as the expected behavior following #8723.
6. Then go and create another new event;
7. Observe the value listed in the filter from the 'Event participants tab';
-> value remained cached and it displays 'All event participants' - not the expected behavior
8. Refresh the page;
-> only now the correct value of 'Active event participants' is displayed in the filter.

This behavior was reproducible on the following testing instances, with their respective SORMAS versions:
- my local machine - 1.77.0-SNAPSHOT(c8e94c1);
- https://test-de2.sormas.netzlink.com - 1.77.0-SNAPSHOT(c2761d9);
- https://release-international.sormas.netzlink.com - 1.76.7
- https://test1402.sormas.netzlink.com - 176.7

**Additional information**
I would also argue that the behavior described seems more like a bug than a change, as it seems so far that it is a deviation from what was introduced with https://github.com/hzi-braunschweig/SORMAS-Project/issues/8723

**Comment by leventegal-she** [comment]
@MateStrysewske Should the caching of filters removed for event participants or just change the relevance status filter based on the archive status of the event?

**Comment by MateStrysewske** [comment]
@leventegal-she I would say keep the caching but make sure that the behaviour introduced in #8723 still works. My suggestion would be the following:

- Whenever the user CHANGES the relevance status in an event participants view, also store the UUID of the event in the criteria (`relevanceStatusChangeEventUuid`); add a comment to that field to describe what it's about to store
- Whenever the user enters the event participants view and a UUID is stored and matches the UUID of the current event, don't change anything about the relevance status (I guess this is how the cache already works, right?)
- Whenever the user enters the event participants view and NO UUID is stored OR the UUID does NOT match the UUIDI of the current event, change the relevance status according to the archived status of the event:
  - Archived: "All event participants"
  - Active: "Active event participants"

Does that make sense to you? Also would like the input from @adinaflorea9 here.

**Comment by adinaflorea9** [comment]
@MateStrysewske @leventegal-she the proposed solution makes sense to me. I'd be happy with it.

**Comment by MateStrysewske** [comment]
Discussed with @leventegal-she again and decided that the use case for my suggestion is very unlikely to happen, so it should be sufficient to not cache the user's selection here and instead always use a default relevance status when opening an event participants view (i.e. "Active" for active events and "All" for archived events).

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behavior - the user can no longer manually filter the event participants of an event as the selection is always refreshed:
![event participant](https://user-images.githubusercontent.com/96909231/224316058-51f96265-82e0-41b5-b574-f5ea7abb87d1.gif)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: 
- [ ] when filtering based on any of the values 'Active/Archived/All active and archived/Deleted event participants' and then clicking 'Reset filters' the filters are not reset (this behavior should be that all the filters should be rest when the user clicks 'Reset filters' similar to the behavior in other directories and the behavior on release instances for the 'Event participants' tab too);

- [ ] when being in bulk edit mode, filtering based on the values 'Active/Archived/All active and archived/Deleted event participants' and then clicking 'Reset filters' the user is taken out of bulk edit mode (this behavior should be as it currently is on release systems where the filters are rest and the user remains in bulk edit mode).

**Comment by abrudanancuta** [comment]
Ticket is reopened because when archiving an Event and going to Event Participants list, the filter remains set on "Active Event Participants"
