### ISSUE TITLE
Edit User Role: Improve validation message for dependent user rights [3]

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10339]
### Change Description

In order for the admin to make an informed decision, he lacks information. In addition to the required right, the rights causing the message should also be displayed. This way the admin can decide whether to add the required right again or to remove the causing rights as well. 

### Steps to Reproduce

1.  Create a user roll from the Admin (Default) template
2.  Remove the e.g. the "View existing cases" right
3.  Try to save 
4.  Have a look at the message

![image](https://user-images.githubusercontent.com/101708230/189642559-f6a9e710-9c5d-4493-a652-3da5a583efa9.png)

### Expected Behavior

The causing / selected rights are mentioned.  
~~A problem has occurred: The user right(s) [...] are required based on the selected ones:  [  **- List of rights  -** ]~~

> A problem has occurred | The following user right(s) are required based on other user right(s):
> 'View existing cases' required by 'Edit existing cases', 'Delete existing cases'
> 'Edit existing cases' required by 'Classify case'

Note: The list of depending user rights should only contain rights that are selected for the current role.

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrom
* Server URL:  https://test1401.sormas-oegd.de/
* User Role: Admin

**Comment by MateStrysewske** [comment]
Not a bug in my eyes because it's not a malfunction of the software, but an additional convenience function for the user.

**Comment by MateStrysewske** [comment]
Since the list of user rights requiring a certain other user right can be very large, the format suggested in the issue description is not universally practical.

Additional requirements as a result of this behaviour:
- As long as the list of user rights requiring a missing user right contains three or less elements, write them all down as suggested in the issue description
- If there are more than three user rights requiring a missing user right, use the following format instead: '{missing user right}' required by {requiring user rights count} enabled user rights, e. g. '{first requiring user right}'

**Comment by AndyBakcsy-she** [comment]
Validated ticket on Local setup  + test-de.sormas.netzlink.com 
using latest version of sormas 1.77.0-snapshot (708b537)

**Comment by KristinaBorch** [comment]
Hello @dinua @AndyBakcsy-she,  Sorry, I just saw that the german translation is missing even though it was translated 18 days ago. Could you check if the translations are pulled correctly? Thanks in advance.
