### ISSUE TITLE
Requesting users to enter complications when creating a case for any disease

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1034]
I logged in as event officer, created a CSM case on the web version, under the symptom tab, there is a tab for "complications" to be filled in.  If I could remember well, we agreed not to request for complications when creating a case but this should only appear under "clinical course". Requesting for clinical course when creating a case, no matter the user role might overburden the user with much information. Any explanation?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou We still don't show any additional signs or symptoms in the normal symptoms tab, but only restructured the form because we were asked to do so. This means that users won't have to fill in additional information, especially none that only apply for clinical courses, for the normal case surveillance process.
