### ISSUE TITLE
Sub lists sometimes take a while to load

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1038]
The code to load the sub lists (e.g. samples) sometimes takes quite a long time to be called which results in an initially empty list that is then updated after several seconds. Find out why this takes so long and how to fix it.

**Comment by MateStrysewskeSym** [comment]
This SEEMS to happen only for cases that are lazy loaded, i.e. those that don't immediately appear in the case list.

**Comment by MartinWahnschaffeSymeda** [comment]
I have tried to reproduce this with cases from the end of my list (61 entries) and opening their tasks and samples list. It worked without problems.

**Comment by MateStrysewskeSym** [comment]
This is probably caused by the lazy loading still being done on the background thread.

- [ ] Fix lazy loading processing more objects than it should (sometimes it loads all remaining cases after the initial reload); make sure that the values for setInitialLoadSizeHint and setPageSize are correct (see comments on the respective methods for directions); check whether setMaxSize or setPrefetchDistance should be included in the config builder.

**Comment by MartinWahnschaffeSymeda** [comment]
The lazy loading worked fine, but I increased the page size a bit to make it less annoying. The real problem is that the pre-loader is hidden before the actual data is loaded. This happens because there are currently two ways to load data. Thus I have removed the (no longer needed) threading of prepareFragmentData.
In addition I have limited the loaded data of a case to the actually needed fields (#941).
