### ISSUE TITLE
Contact Dashboard runs into parameter limit with many contacts

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10528]
### Bug Description

When and Admin+NatUser or a Contact Supervisor(with the jurisdiction in 'Voreingestellte Bundesländer') filter contacts on the dashboard based on 'Custom' - 'By date', an error message is displayed.

The issue could not be reproduced on my local machine, or on test-de.sormas.netzlink.com, with any of the 2 users; could only reproduce it on test-autom.sormas.netzlink.com.

### Steps to Reproduce

1. Log into the app with an Admin+NatUser, or a Contact Supervisor (with the jurisdiction in 'Voreingestellte Bundesländer');
2. Navigate to the 'Dashboard' directory;
3. In the first Epi week related filter, select 'Custom'; for 'Custom persion' select 'By date'; in the 'From' field select the 1st of September 2021;
4. Click 'Apply Custom Filter' then 'Apply filters'.

### Actual Behavior

An error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/193787260-6e0aac77-a8b4-4112-8ed3-30d269212f87.png)

### Expected Behavior

No error message should be displayed.

### Screenshots

GIF of the behavior and the steps to reproduce:
![Custom error](https://user-images.githubusercontent.com/96909231/193788223-028cb4f4-4917-4fe9-9654-ab1edf85a4cc.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0SNAPSHOT(5111f71)
* Android version/Browser: Chrome
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Admin+NatUser; Contact Supervisor (with the jurisdiction in 'Voreingestellte Bundesländer')

### Additional Information

Observed while testing for #10381. 

Could not provide server logs as I do not have access to them for this specific testing instance.
---> I put the error log here
[logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9771804/logs.txt)

**Comment by StefanKock** [comment]
Too many parameters problem in `ContactService.getContactsForDashboard(ContactService.java:652)`, easily solvable by using `IterableHelper.executeBatched` fetching for the `DashboardVisit` data. Problem caused by #1329.

**Comment by dinua** [comment]
This bug was reproducible here only because the amount of data in this server .
When we open Dashboard as describe here , in backend , in ContactService.getContactsForDashboard(...) , we create 2 queries for the data 
In the first one we search for the contacts
`select contact0_.deleted,contact0_.archived,contact0_.id as col_0_0_, contact0_.reportDateTime as col_1_0_,
contact0_.contactStatus as col_2_0_, contact0_.contactClassification as col_3_0_, contact0_.followUpStatus as col_4_0_, contact0_.followUpUntil as col_5_0_, contact0_.disease as col_6_0_, contact0_.quarantineFrom as col_7_0_, contact0_.quarantineTo as col_8_0_ 

from contact contact0_ 
left outer join cases case1_ on contact0_.caze_id=case1_.id 

where contact0_.deleted=false 
and ((contact0_.followUpUntil is not null) 
	 and contact0_.followUpUntil>='2021-10-01 00:00:00'
	 or (contact0_.lastContactDate is not null) 
	 and contact0_.lastContactDate>='2021-10-01 00:00:00' or contact0_.reportDateTime>='2021-10-01 00:00:00') 
and ((contact0_.lastContactDate is not null) 
	 and contact0_.lastContactDate<='2022-10-11 00:00:00' or contact0_.reportDateTime<='2022-10-11 00:00:00')
`
This query will return a list with ~6600 rows of active contacts and over 110.000 rows of archived contacts
After this we extract the list of ids and use it in next query

The contact with visits query 

`select contact0_.id as col_0_0_, symptoms3_.symptomatic as col_1_0_, visit2_.visitStatus as col_2_0_, visit2_.visitDateTime as col_3_0_ 
from contact contact0_ 
left outer join contacts_visits visits1_ on contact0_.id=visits1_.contact_id 
left outer join Visit visit2_ on visits1_.visit_id=visit2_.id 
left outer join Symptoms symptoms3_ on visit2_.symptoms_id=symptoms3_.id 

where 
(contact0_.id in (**list_of_ids**)) 
and 
(exists 
	 (select visit5_.id 
	  from contacts_visits visits4_, Visit visit5_ 
	  where contact0_.id=visits4_.contact_id 
	  and visits4_.visit_id=visit5_.id)
	)`

So doing like this the sql will fail because we try to put in in CLOUSE a list with over 123.000 ids and the limit is about 65.000 params

Suggestions :
1) to not include the archive contacts in list
2) use "exists" instead of "in" in second query 
in

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-auto.sormas.netzlink.com/ using SORMAS version - 1.76.0-SNAPSHOT(f34a7c8).
