### ISSUE TITLE
Multiple cases can be created based on the same sample and pathogen test

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10525]
### Bug Description

Multiple cases can be created starting from the same sample and pathogen test, even if a case has already been created starting from the same sample and pathogen test.

### Steps to Reproduce

1. Create a Covid-19 case;
2. Add to the case a sample with a positive pathogen test result of Anthrax;
3. 'Generate new case for Anthrax?' pop-up is triggered;
4. Click 'Yes' in the pop-up and create the new case;
5. Navigate to the case created at step 1 and open the sample associated;
6. Open the pathogen test and edit some information on it, or edit nothing, and just click 'Save'.

### Actual Behavior

Pop-up to 'Generate a new case for Anthrax?' is triggered again, even though a case was already created based on the same pathogen test and sample. If a new case is created, no duplicate detection for cases is triggered.

### Expected Behavior

If a case was already created based on the respective pathogen test, the pop-up to generate another case should no longer be triggered.

### Screenshots

GIF of the steps to reproduce and the behavior:
![Multiple Cases from the same Pathogen Test](https://user-images.githubusercontent.com/96909231/193781063-16eb6a08-12db-442a-a116-2c9b0521a442.gif)

### System Details

* Device: Windows 10 
* SORMAS version: 1.76.0-SNAPSHOT(5111f71); also on 1.75.3.
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by MateStrysewske** [comment]
@dinua I'd go with an adjusted solution 2: If we find such a case (my suggestion would be same person, disease of the pathogen test, and the case must have a sample with the same sample date and the same sample material as the sample of the pathogen test that's currently saved), we simply don't show the popup because we can very safely assume that the case in question belongs to this sample; if no case is found, we show the popup as usual.

**Comment by roxanamlendea** [comment]
Reopening ticket because multiple cases for the same disease based on the same pathogen test can still be created for Event Participants:

1. Create a Contact with Covid 19 as disease;
2. Add a Sample with a positive Pathogen Test result for Anthrax
3. In the 'Create Case for this contact person' select 'Yes' and fill in the form for 'Create new Case'
4. Open the Sample and then open the Pathogen Test', edit a field and Save;

-> the 'Create Case for this contact person' gets triggered again, and a new Case for Anthrax can be created

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.79.0-SNAPSHOT.
