### ISSUE TITLE
When a Person has 2 Cases, all Visits that are created have the same caze_id

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10616]
### Bug Description
When a Person has 2 Cases, and a Visit is created for each Case, all Visits have the same caze_id.

### Steps to Reproduce

1. Create Case no. 1 and add Visit no. 1;
2. Create Case no. 2 for the same Person;
3. In the 'Pick or create person' pop-up, select the matching person from step 1;
4. In the 'Pick or create case' pop-up, select 'Create new case';
5. Add Visit no. 2 for the Case no. 2;
6. Check the caze_id column in the DB;

### Expected Behavior
Visit no. 1  should have the Case no. 1 caze_id and Visit no. 2 should have the Case no. 2 caze_id.

### Actual Behavior
Both Visits have the caze_id of Case no. 2.

### Screenshots
![caze id](https://user-images.githubusercontent.com/89522688/195317893-302b25da-b0ad-4600-8b7a-203acce2e707.gif)

### System Details

* Device: Windows 10
* SORMAS version: discovered on the current version of Sormas 1.76.0-SNAPSHOT, but it is probably an older issue (I don't have access to the DB of the release instances, so I couldn't test there)
* Android version/Browser: Chrome
* Server URL: local setup
* User Role: admin + national user

### Additional Information
This bug was found while testing ticket #9666.

Note: The automatic deletion of Visits is affected by this issue.
Trigger the automatic deletion for the Case no. 2.
-> Both Visits are deleted;

**Comment by sergiupacurariu** [comment]
I think more details are needed before fixing or not this issue. I will start by describing this functionality based on how is currently implemented in the system. Let's say the user creates a visit on a case. During the save process the visit is attached to the most relevant case. The most relevant case is searched based on the person, disease of the case on which the visit is created and visit date. It might be the same case but if there are multiple cases for the same person and disease the visit might be attached to a different case. However this will not impact the user experience on the Follow-up grid  as the new visit will still be displayed even if it is attached to a different case in the database. This is possible because the visits in the Follow-up grid are displayed based on the person, disease, relevance period (30 days). It is possible to create multiple visits on a case and all be saved in a different one.
There is however an impact of this logic. When a visit is saved the case symptoms are also updated with the visit's symptoms. When the visit is attached to a different case from the one the user is creating the visit from the symptoms of that case are updated not the initial one.
Please review this logic and clarify if the current logic is correct or a different one should be implemented.

**Comment by MateStrysewske** [comment]
Kind of surprised that we actually have this "closest case possible" logic in place when a user creates a visit for a specific case because it doesn't seem to make that much sense since in real life, no person should have two cases for the same disease at the same time (which is also why I believe that this won't be a problem in a production system). I think the reason why we display all visits that meet the time threshold in the case visits list is that we also want to display contact visits for the same person in a similar time period there, which would otherwise not be shown, so I believe that part of the logic is fine and shouldn't be touched, but we could think about getting rid of the fuzziness in the initial assignment logic. Should probably be taken into a refinement session and discussed there though.

**Comment by MateStrysewske** [comment]
This logic actually makes sense. We could theoretically inform the user when a visit is re-linked to a different case, but since this is a niche case, this should not have any priority.
