### ISSUE TITLE
Server error when the DB contains entities with Disease Variants that no longer exist

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10648]
### Bug Description
The system throws a server error message when the user accesses the Cases Directory when the DB contains entities with Disease Variants that no longer exist.

Logs: 
[disease variants logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9800945/disease.variants.logs.txt)

### Steps to Reproduce

1. In the DB, in the costumizableenumvalue table, create a new Disease Variant (here you can see how you can do this https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Customizable-Enumerations);
2. Restart the server;
3. In the UI, add some Cases with that specific Disease Variant;
4. In the DB, delete the entry for the Disease Variant created at step 2;
5. Restart the server again;
6. Open the Cases Directory;

### Expected Behavior
The user should be able to access the Cases Directory; the information regarding the Disease Variants should not be displayed if the Disease Variant doesn't exist anymore.
The expected behavior needs to be confirmed.

### Actual Behavior
The user receives a server error;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/196188165-5f86800d-3283-4f33-acef-f57cad36ff5a.png)

### System Details

* Device: Windows 10
* SORMAS version: discovered on Sormas 1.77.0-SNAPSHOT, but it is probably an older issue (I don't have access to the DB of the release instances, so I couldn't test there)
* Android version/Browser: Chrome
* Server URL: local setup
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
We need to talk about how to deal with these kinds of issues. I DO believe that we SHOULD show this error message because if somebody deleted a disease variant from the database that is actively used somewhere, the database has a significant data integrity problem that needs to be dealt with.

@JaquM-HZI What's the reason for putting this into the hotfix milestone? This situation should never occur on a system that is carefully managed; is it really that urgent to deal with it? In any way, we would need to have some input from you how you believe this should be handled if the current behaviour is not okay.

**Comment by JaquM-HZI** [comment]
@MateStrysewske if this situation can not occur on the productive systems right now, we can move it to 1.77 and discuss it there.

**Comment by MateStrysewske** [comment]
@JaquM-HZI It COULD theoretically occur, but only if someone with database access consciously deletes a disease variant from the database, i.e. the same risk that always exists for all data when people have database access.
