### ISSUE TITLE
Add counts and percentage of sample attributes to sample dashboard [3]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10738]
### Feature Description

An illustration using line or infobox widgets for attributes on a sample should be added to the dashboard (#10723).
The information should be located below the overview of all samples and presents the counts for each enum + proportion.

### Proposed Change

Add widgets for the following sample attributes:
 
- [x] Purpose of sample:  external lab testing, internal lab testing
- [x] "Specimen Condition of external samples": adequate, not adequate.
  - Only consider samples with purpose "external lab testing"
  - Add an info icon next to the heading with the following text: "Only samples with the purpose external lab testing are considered".
- [x] "Shipment status of external samples": shipped (shipped == true, received == false), not shipped (shipped == false, received == false), received (shipped doesn't matter, received == true)
  - Only consider samples with purpose "external lab testing"
  - Add an info icon next to the heading with the following text: "Only samples with the purpose external lab testing are considered". 

The boxes/ line widgets  illustrate the following: 
- [x] sum for each category (enum)
- [x] Percentage of each category. The denominator is the total number of samples / external samples.

### Acceptance Criteria

The feature is implemented as described above.

### Additional Information

![grafik](https://user-images.githubusercontent.com/23217632/219331506-baae6e4a-584d-4fbe-b823-b32f65b17adc.png)

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou I'd suggest to:

1. Switch colors of adequate & not adequate
2. Don't show "missing".
3. Clarify "shipment status" to "shipment status of external samples"
4. Exchange the placement of "speciment condition" and "purpose" on the dasbhoard. So specimen condition would be in the center of the first row and purpose at the left of the second row.

**Comment by bernardsilenou** [comment]
> @MartinWahnschaffe :
> 
> 1. Switch colours of adequate & not adequate 

 (OK)
> 2. Don't show "missing" 

 (OK)
> 3. Clarify "shipment status" to "shipment status of external samples"

 3.1  I also thought of this and realised that it applies to specimen conditions also 
There are two options I can think of:
              3.1.1 Clarify specimen condition to "Specimen condition for external samples that have been received" (this seam too long even if we use just "Specimen condition for external samples")
               3.1.2 Keep the initial specification and add a tooltip (prefer this option)
> 4. Exchange the placement of "specimen condition" and "purpose" on the dasbhoard. So specimen condition would be in the centre of the first row and purpose at the left of the second row.

(OK)

5. For the info boxes, What do you think about replacing them with the once we used on the surveillance dashboard, just to be consistent
![image](https://user-images.githubusercontent.com/12996724/216132146-191836e4-f438-445d-9cb5-2bcb17cbf73a.png)

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou I have updated the mockup accordingly. Since specimen condition is also filtered by external samples, I'd leave it in the second row, as in the original proposal.

I would leave the boxes as they are, since the text is a bit longer than the short text of diseases, so I think it's better to have the numbers above.

One thing I just noticed: I the description it always says that the second number should be the proportion (%), but in the mockup it's the difference compared to the previous time period. We would go with the proportion now.

**Comment by leventegal-she** [comment]
The Specimen Condition is not a required field. 
How should the samples with no specimen condition be counted/displayed?
Do we count those as "Adequate" or we introduce a new box on the dashboard labelled with "Not specified"(or something similar)?

For the shipment status of the sample there are two flags that can be used to calculate but it not clarified how.
I mapping like the following table would be ok?

| shipped | received | shipment status |
| -------------| -------------| -------------|
|true|true|SHIPPED|
|true|false|NOT_RECEIVED|
|false|true|RECEIVED|
|false|false|NOT_SHIPPED|

@MartinWahnschaffe @KristinaBorch @bernardsilenou

**Comment by bernardsilenou** [comment]
@leventegal-she 

1. The info boxes in the second row of the dashboard are conditional and only apply to a subset of external samples, just as you mentioned.
2. Since `specimen condition` actually represents the specimen condition at the reception of the sample, it only applies to samples having received == true, no matter the shipment status.
3. In your suggested mapping all  internal samples will fall in the "not_shipped" category by design, thus falsely raising the counts for not_shiped
4. I think we can only use the received sample as the denominator and count the "trues", end exclude all samples with received == false
5. What do think about putting shipment status on the left and specimen condition on the right on the same row? since specimen condition applies to received samples.
6. In 3.1.2 here https://github.com/hzi-braunschweig/SORMAS-Project/issues/10738#issuecomment-1412536982 I suggested adding a tooltip near specimen condition. Similar to shipment status, we can add a tooltip saying "For samples with the purpose of sample set to external lab testing"

**Comment by bernardsilenou** [comment]
@MateStrysewske @leventegal-she 
* Can we rename "Not specified" to "Missing", since it's missing data (null)? We would often face this same situation and we can always use the same name.
* It would be good not to use the suggested mapping table but just count the individual data as they are in the DB. If adjustment is needed to keep the counts consistent, then we add a contains that reception can be checked only if the shipment is true (not part of this ticket of course). The dashboard audience, often not sormas users, will not have this information about the mapping
* For shipment status ==shipped == counts for shipmnet == true (external samples only)
* For shipment status ==not shipped == counts for shipmnet == false (external samples only)
* Similar for received and not received
* For clarity, we can split the shipment status into two items: 
               - shipped status (shipped| not shipped)  
               - received status (received| not received)
* The comment `I think we can only use the received sample as the denominator and count the "trues", end exclude all samples with received == false` is about the proportion of the samples with specimen condition == adequate for example, ie to use the counts for received samples as the denominator.  This is not important since we do not compute proportions.

**Comment by leventegal-she** [comment]
> * For shipment status ==shipped == counts for shipmnet == true (external samples only)
> * For shipment status ==not shipped == counts for shipmnet == false (external samples only)
> * Similar for received and not received

@bernardsilenou This means we count twice all samples because `shipped` and `received` fields cannot be empty so we always have a *false* or *true* value in the database. Are you ok with it?

**Comment by MateStrysewske** [comment]
@bernardsilenou @leventegal-she 

- I believe "Not specified" is currently used in multiple places throughout the app, "Missing" would be a new naming convention that is never used right now; I agree that the word makes sense, but it would break convention right now
- I think the mapping is natural; we don't have the "not shipped" value anyway because "shipped" and "received" are two individual checkboxes. So basically the mapping table I proposed is an exact portrayal of the states of the two checkboxes + the addition of using "not shipped" when both checkboxes are unchecked because you need to find a word for that state
- If you have a sample with `shipped == false` and `received == true` this would then be counted as "not shipped"; I don't agree with this because the "received" status should have priority
- "Not received" is a lot more confusing than using "Shipped" for a sample that has been shipped, but not received, because it doesn't accurately reflect the current status of the sample
- And I agree with Levi that this would result in samples being counted twice, which doesn't sound like a good idea because we want to give the user an overview of the state each sample is in here

**Comment by bernardsilenou** [comment]
> @bernardsilenou @leventegal-she
> 
> * I believe "Not specified" is currently used in multiple places throughout the app, "Missing" would be a new naming convention that is never used right now; I agree that the word makes sense, but it would break convention right now

Ok, I did not know
> * I think the mapping is natural; we don't have the "not shipped" value anyway because "shipped" and "received" are two individual checkboxes. So basically the mapping table I proposed is an exact portrayal of the states of the two checkboxes + the addition of using "not shipped" when both checkboxes are unchecked because you need to find a word for that state
> * If you have a sample with `shipped == false` and `received == true` this would then be counted as "not shipped"; I don't agree with this because the "received" status should have priority

Absolutely right
> * "Not received" is a lot more confusing than using "Shipped" for a sample that has been shipped, but not received, because it doesn't accurately reflect the current status of the sample

"Not received" is a lot more confusing than using "Not_Shipped" ....
> * And I agree with Levi that this would result in samples being counted twice, which doesn't sound like a good idea because we want to give the user an overview of the state each sample is in here

That's true, I did not think of this

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(1eb69c5).
