### ISSUE TITLE
Add  bar graphs to sample dashboard [3]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10744]
### Feature Description

A graph should be added to the sample dashboard to provide an overview of samples documented and tested over time. The structure should be similar to the epidemiological curve on the surveillance dashboard. 

### Proposed Change

- [x] add heading `Sample Bar Chart`
- [x] add a legend for each colour for enums  for `final laboratory test`, group by: Positive, Negative, Pending, indeterminate, Not done
- [x] add a graph which shows the number of samples (y-axis) based on the selected options in the "grouping" button; there needs to be a dropdown that allows the user to choose between report date, sample collection date (i.e. `sampeldatetime`) and most relevant date (default); most relevant date uses the earliest pathogen test date among all pathogen tests associated with the sample, and falls back to the sample collection date if there are no tests or there is no test with a pathogen test date; then the user can group by day, epi week or month as shown in the graphic below (x-axis) 
- [x] add button to enlarge/scale down the graph to the top right
- [x] add button Chart Context Menu to download the graph (formats: PNG; JPEG; PDF; SVG; CSV; XLS) on the top right below the button to enlarge the graph
- [x] add button to change grouping between day, epi-week or month and to decide if at least seven entries should be shown

**OPEN QUESTION:**
~~Shouldn't we also consider relevance date here? According to https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721, we allow filtering for relevance date on the samples dashboard, only considering report date in the graph seems inconsistent.~~

![image](https://user-images.githubusercontent.com/98821699/197943211-96e65c84-e5e4-4833-af0c-abe6e6292933.png)

![image](https://user-images.githubusercontent.com/12996724/215924928-12694009-6c31-43c0-af2b-a0e463a2186d.png)

### Acceptance Criteria

The weekly sample overview is implemented as described above. 

### Additional Information

The data used in the global filter  is the report data of the parent entity of the sample:
* cases:  case report date
* Contact: report date
*  event participant:  report date of event
~~mmunization participant: report data of immunization or that of the associated case (reduced immunization)~~
* travel return:  return data of travel return

**Comment by bernardsilenou** [comment]
add titile for final lab results

**Comment by MateStrysewske** [comment]
@bernardsilenou Shouldn't we also consider relevance date here? According to #10721, we allow filtering for relevance date on the samples dashboard, only considering report date in the graph seems inconsistent to me.

**Comment by bernardsilenou** [comment]
> @bernardsilenou Shouldn't we also consider relevance date here? According to #10721, we allow filtering for relevance date on the samples dashboard, only considering report date in the graph seems inconsistent to me.

- I was just about to add this change after discussing it with @faatihi a few days ago.
-  yes, we should add two date options to #10721 : the report date and the most relevant date., just as on the surveillance dashboard. The default can be the relevant date. The date type chosen here will be used to filter the whole dashboard (maps, graphs, counts)
- One important difference in the logic for a relevant date for samples from that of cases can be that the priority is pathogen test date (earliest if multiple exist for the sample) + fall back to sample collection date if missing among all tests of the sample (no need to fall back to report date of parent entity since sample collection date is always present).  @MateStrysewske @faatihi  What do you think about this point?

**Comment by faatihi** [comment]
@bernardsilenou, I agree with the points you made.
With point 3, regarding the pathogen test date, can we also consider the result date on the sample's final result.
Especially when there are multiple tests for the sample. The reason I'm suggesting this is because the sample's final result kind of solves the problem of deciding which test result to use in a situation when multiple tests exist for the sample.

**Comment by MateStrysewske** [comment]
@faatihi I agree that would be a good idea, however, we currently don't have a final result date; neither do we have such a date in the sample entity, nor do we have a field that flags a specific pathogen test as the final result of a sample. This would have to be added in a separate change request in order to be used here.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(0e006cf).
