### ISSUE TITLE
Replace Case ID with Case SN on the case directory view

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1082]
Can we do this please? we reference the casesn more in the process of cleanup than the case ID. Both IDs are unique. This will be greatly appreciated! Thanks!!!

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar 
The serial number may seem convenient to use now, but over the next years it will become very large numbers that will be very difficult to distinguish. It's quite easy to mix up two SN.

Can you give an example process of how and when you would need this? We need to discuss this, because it does have a lot of implications.

**Comment by Chinedar** [comment]
Yes Martin,

I agree with you on this. We can leave it as it is. I've advised them to
export the data for any form of referencing they need to do.
