### ISSUE TITLE
cases marked with "don't share with reporting tool" getting shared by automatic archiving

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10830]
### Bug Description

cases which are marked with the checkbox "don't share with reporting tool" are beeing send to reporting tool in the night by the system.

### Steps to Reproduce

1.create a case
2. send it to survnet
3.hit the checkbox "don't share with reporting tool"
4.trigger the automatic archiving
5.case is send to reporting tool

### Expected Behavior

The cases should not be sent.
The checked checkbox must never be ignored 
### Details
The checkbox "don't share with reporting tool" does only prevent the user to be able to click Send to Reporting tool in the UI. That means, that every other action, that triggers the SurvNet Converter like
- automatic archiviing
- automatic deletion
- send with ownership using S2S

should also check for that checkbox and, if checked, does not trigger the converter and does not send that specific dataset

### System Details

* Device:
* SORMAS version: 1.75.4
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

The checkbox was introduced May 2020, the automatic trigger of the "send to survnet" with auto-archiving and/or Sormas 2 Sormas was implemented end of 2021 and 2022 so no one thought of this checkbox

**Comment by ChristopherRiedel** [comment]
So far, this field is only considered in the ui, in the context of whether the share button is displayed.
However, since cases are also automatically sent to the external surveillance tool in the following cases, this field must also be taken into account here: Archiving cases, deleting cases and sending cases with ownership via Sormas2Sormas.
It must be taken into account that we also adjust the pop ups in the ui regarding bulk actions (how many cases were sent to the external surveillance tool).

**Comment by AndyBakcsy-she** [comment]
Validated ticket during a peer testing session with Carina
