### ISSUE TITLE
"don't send to reporting tool" should just be avaliable if the case was never sent to external reporting tool before

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10833]
### Problem Description

the checkbox "dont sent to reporting tool" is clickable even if the case was send before to the external reporting tool.
### Proposed Change

when the case was once send to the reporting tool, the checkbox should not be clickable.
### Implementation Details

- [x] adding a hover text to inform the user why the box is not clickable
- [x] make sure the filter in the case overview works correct

### Additional Information
As discussed with @cmeyerhzi 
![Bildschirmfoto 2022-11-24 um 11 43 23](https://user-images.githubusercontent.com/62540178/203764715-2b5126b0-c953-4f2a-b968-662b212b92ec.png)

1. The filter number 1: "Only cases not yet shared with reporting tool" should ignore the value of the checkbox which is used to no longer send to reporting tool. The list will contain items where the checkbox is checked AND unchecked.
2. The filter number 2: "Only cases already shared with reporting tool" should also ignore the value of the checkbox which is used to no longer send to reporting tool. The list will contain items where the checkbox is checked AND unchecked.
3. The filter number 3: "Only cases changed since last shared with reporting tool" SHOULD take the "checked" of the checkbox which is used to no longer send to reporting tool into filtering the results. The list will only include items where the checkbox is unchecked.
4. Filter number 4: no change 

This partially reverts the changes made in: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6273

ADDITIONAL: 
When the checkbox "Don't send to reporting tool" is checked, then the delete icon (to delete the item in the reporting tool) on the right side should be hidden, as this would trigger a communication with the reporting tool, which is explicitly not wanted.

**Comment by dinua** [comment]
@cmeyerhzi 
For a case if 
Step1) We send it to the report tool so the export status is SHARED . After this step the checkbox is disabled
Step2) We press the delete button for the same case. The latest status will be DELETED.

After this the checkbox should still be disable ?

**Comment by ChristopherRiedel** [comment]
@dinua Just to be sure: The checkbox should also be disabled if the case was imported from survnet. I guess that meens, that it has to be disabled if the case has at least one ShareRequestInfo.

**Comment by cmeyerhzi** [comment]
> @dinua Just to be sure: The checkbox should also be disabled if the case was imported from survnet. I guess that meens, that it has to be disabled if the case has at least one ShareRequestInfo.

thats right.

**Comment by cmeyerhzi** [comment]
> @cmeyerhzi For a case if Step1) We send it to the report tool so the export status is SHARED . After this step the checkbox is disabled Step2) We press the delete button (from Reporting Tool card) for the same case. The latest status will be DELETED.
> 
> After this the checkbox should still be disable ?

when the case was deleted in the reporting tool, the checkbox can be clickable again.

**Comment by carina29** [comment]
Hello @all,

When I've reviewed and tested the PR for this change I've found some problems related to the filtering.
Not only the status "SHARED" or no status for not shared entities are checked in case of filtering but also the value of the checkbox "Don't share with reporting tool" and the outcome is that the filtering will not work correctly for some of the cases.

@dinua will investigate the filtering in the scenarios from the below screenshots. 
**NOTE:** The QA who will test this change should also test the below mentioned scenarios

I have the below 4 cases ( the first 3 are shared, the last one is not shared with the Reporting Tool)
![AllTheCases](https://user-images.githubusercontent.com/47103965/202175671-2650bbc1-5a4c-4bd0-b854-eae34e2a7394.PNG)
![AllTheCases2](https://user-images.githubusercontent.com/47103965/202175682-83483f2f-4521-44e5-8d85-d9849d024213.PNG)

When I filter "Only cases already shared with Reporting Tool" one case will not be retrieved : S35GZR.
![S35GZRMissingAsSharedBecauseTheFlagIsTrue](https://user-images.githubusercontent.com/47103965/202175775-7e31f039-b943-445b-8979-2077e42929b1.PNG)
This case was shared with the Reporting Tool but after sharing the user clicked the "Don't share..." flag which for future cases will not be a problem but for existent , old cases should work properly.
![S35](https://user-images.githubusercontent.com/47103965/202175839-6d3e9c4f-cbee-4ba7-9ff7-db367be8866b.PNG)

2)For filtering with "Only cases not yet shared with reporting tool" 1 case(WCMCE2) should be retrieved and 0 case is retrieved.
![OutcomeOfTheFiltering](https://user-images.githubusercontent.com/47103965/202175913-967a5623-f745-454d-b317-f289d702ec95.PNG)
The case has the "Don't share with..." flag but never was shared with Reporting Tool so the case should be retrieved for this type of filtering.
![image](https://user-images.githubusercontent.com/47103965/202176011-114afe5a-2297-4f67-be36-4657646cb982.png)

3)When I click the filtering "Only cases changed since last shared with ..." I receive an error.
![ONly cases changed since](https://user-images.githubusercontent.com/47103965/202176082-c765bdbf-7cf8-4a92-a382-46cd76be3690.PNG)

4)The last type of filtering related to the sharing with reporting tool, "Only cases marked with Don't share with reporting tool" is working fine.

**Comment by dinua** [comment]
1) In the system we already have cases like this
- the case was shared with reporting tool 
- after that the checkbox "Don't share this case with the external tool" was checked
- after this feature is merged the view will look like this
![image](https://user-images.githubusercontent.com/4202109/202430507-abeb7711-f830-49c7-a6a8-ab3f28bd8ad2.png)
- the checkbox is set on true and is also disable (because of the new feature), the user can not make any change
- is this correct to have it like this ?
2) In the Case List View if we apply filters on search "Only cases already shared with reporting tool" the cases same as in step 1 will not be included in the 
list because the value case "dontsharewithreportingtool" is on true and those values are ignored
Is this correct ?

3) In the Case List View if we apply filters on search "Only cases since last shared with reporting tool"
- the cases that were never shared are not included in result list
- the shared cases with checkbox "Don't share this case with the external tool" on true are not included in result list
Is this correct ?

**Comment by cmeyerhzi** [comment]
1.:
No, the user must have the possibility to make sending to the reporting tool possible again, for example to delete the case.

2.:
no the case should also be displayed there.

3.:
thats ok.

@JaquM-HZI can you please double check my statements? thx

**Comment by markusmann-vg** [comment]
As discussed with @cmeyerhzi 
![Bildschirmfoto 2022-11-24 um 11 43 23](https://user-images.githubusercontent.com/62540178/203764715-2b5126b0-c953-4f2a-b968-662b212b92ec.png)

1. The filter number 1: "Only cases not yet shared with reporting tool" should ignore the value of the checkbox which is used to no longer send to reporting tool.
2. The filter number 2: "Only cases already shared with reporting tool" should also ignore the value of the checkbox which is used to no longer send to reporting tool.
3. The filter number 3: "Only cases changed since last shared with reporting tool" SHOULD take the "checked" of the checkbox which is used to no longer send to reporting tool into filtering the results. The result should exclude the items where the checkbox is checked.
4. Filter number 4: no change

**Comment by carina29** [comment]
As we agreed in Demo , we will need a new ticket ( change) in order to fix a workflow: When the case was already sent to the Reporting Tool, the user should still be able to delete the case from Reporting tool ( Delete Icon should be enabled in order to delete the case from Reporting Tool too).
![image](https://user-images.githubusercontent.com/47103965/204825746-e70fc3fb-966b-4336-b9cd-a3d70bb6833c.png)

**Comment by adinaflorea9** [comment]
I am reopening the ticket based on @carina29 's comment from above.

**Comment by adinaflorea9** [comment]
Verified ticket using the latest version of SORMAS FROM https://test-de2.sormas.netzlink.com/ - 1.77.0-SNAPSHOT(7fe7cd2) an in a peer to peer testing call with @dinua on his local machine.
