### ISSUE TITLE
National Clinician - Sample - Cannot Edit

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10944]
### Bug Description
As National Clinician role cannot make a save for a sample because of the Laboratory name and description

### Steps to Reproduce
1. As National Clinician go to Sample directory
2. Choose a Sample and make open in edit mode
3. Look at the field for Laboratory Name and description
4. Try to Save without changing anything in the form

### Actual Behavior
Sample cannot be saved because an error pop-up that appears related to the field Laboratory Name and description

### Expected Behavior
Sample should be saved because the Laboratory Name and description field has already a value but is confidential as NatClinician

### Screenshots

https://user-images.githubusercontent.com/91872179/202473741-f84e2f45-da94-4906-b68e-6db5a6e6fb05.mov

### System Details

* Device:
* SORMAS version: 1.76.5 and 1.77.0-snapshot
* Android version/Browser:
* Server URL: test and realease environments
* User Role: National Clinician

**Comment by carina29** [comment]
I've talked with @abrudanancuta and in edit mode when the laboratory details field is pseudonymized ( example when we log in with a NatClin but the case and sample were created by a NatUser) the field will not appear anymore as mandatory ( in order to be consistent with the handling of other pseudonymized fields in edit mode). The outcome should look like this: 

![image](https://user-images.githubusercontent.com/47103965/204250024-9a01d75f-dc2e-4289-964b-91d17fe0c91a.png)

**Comment by abrudanancuta** [comment]
I am reopening the ticket because when editing a pathogen test the Laboratory name & description appears to have the same problem as was reported in the ticket

Steps to reproduce:
1. As National Clinician edit a Sample
2. Choose a pathogen test from the Sample
3. Press the edit icon
4. Look at the Laboratory name & description field
5. Try to save the Pathogen test  **=>** At this point Pathogen test cannot be saved because of the Laboratory name & description field

<img width="1440" alt="Screenshot 2022-12-01 at 14 06 56" src="https://user-images.githubusercontent.com/91872179/205061064-6058229a-5625-4920-8c37-d55d0c2599e2.png">
