### ISSUE TITLE
Rename "Incidence" to "Attack rates"

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1097]

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Do you remember what this is about?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda It was about the incidence proportions. Incidence proportions are also called attack rates. 
Definition of incidence proportion
Synonyms include attack rate, risk, probability of getting disease, and cumulative incidence. Incidence proportion is a proportion because the persons in the numerator, those who develop disease, are all included in the denominator (the entire population).
https://www.cdc.gov/csels/dsepd/ss1978/lesson3/section2.html

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig We have recently changed to to incidence proportion #1180 . So I guess this issue is obsolete?
