### ISSUE TITLE
[Test-de3 - Cases - Send to reporting tool] An error appears when trying to send cases to the reporting tool

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11064]
### Problem Description

Only on https://test-de3.sormas.netzlink.com an error appears when trying to send a case to the reporting tool. A support ticket was opened to Netzlink, they closed it and stated that the issue was fixed, however, this is still reproducible so I am opening this ticket so that someone from the team can investigate.

#### Steps to Reproduce

1. Log into test-de3 with an Admin+NatUser;
2. From a case's page, on the card 'Reporting tool' card click on 'Send to reporting tool', and then click 'Yes' in the 'Confirm sending' pop-up.
Actual behavior: An error appears.

#### Screenshots

![image](https://user-images.githubusercontent.com/96909231/205002212-e95af47a-9d5a-4d14-9a97-eb215067a7ef.png)

#### System Details

* Device: Windows 10
* SORMAS version: 1.77.0-SNAPSHOT(4b7b97e)
* Android version/Browser: Chrime
* Server URL: https://test-de3.sormas.netzlink.com/
* User Role: Admin+NatUser

### Expected Behavior

No error should appear. The case should be successfully sent to the reporting tool.

### Additional Information

Logs from Grafana for test-de3 at the time when the error was reproduced:
[logs test-de3 reproting tool.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10130584/logs.test-de3.reproting.tool.txt)

**Comment by carina29** [comment]
I've investigated the ticket and based on the logs , the same problem we had in the past for test-de2.
https://github.com/hzi-braunschweig/SORMAS-Project/issues/10904
The problem was that the Survnet user was expired and Netzlink had to reset this user's password.

I wrote an e-mail to Netzlink in order to check this problem. 
I'll come back as soon as I received an answer.

**Comment by MateStrysewske** [comment]
@carina29 Do you have an update? Can we close this issue?

**Comment by carina29** [comment]
@MateStrysewske is not finished the work on Netzlink side yet and because of this the behaviour is still present on test-de3.

The problem here is that the Sending to the Reporting tool of Cases/Events never worked on test-de3 because the SurvNet Client was never created. Netzlink said that RKI is also involved in the SurvNet Client setup procedure and it will take a few weeks the setup. 
I've asked today for a status update from Netzlink. As soon as I receive an answer I'll add a new comment here.

**Comment by carina29** [comment]
**Update:** The Survnet Client setup was finished and the Sending to Reporting Tool of Cases and Events is working now. :)

Sending cases to the Reporting Tool:
![image](https://user-images.githubusercontent.com/47103965/220052857-9a51c16f-fb92-44a2-b5eb-881768f7e568.png)

Sending events to the Reporing Tool:
![image](https://user-images.githubusercontent.com/47103965/220053477-7a59e962-9c35-4954-9e8c-3b9f42ea6867.png)

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de3.sormas.netzlink.com/ using SORMAS version 1.81.0-SNAPSHOT(6435d82).
