### ISSUE TITLE
[Reporting Tool] Button for deletion should not be displayed if the Case was not sent to the Reporting Tool yet

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#11076]
### Problem Description
1) The Reporting Tool card of Cases that were not sent to the Reporting Tool has the option for deletion (the delete button). If the button is clicked, the user is able to delete the Case from the Reporting Tool. However, this shouldn't be possible if the Case was not sent to the Reporting Tool in the first place.

![image](https://user-images.githubusercontent.com/89522688/205092891-8ff270c7-f034-44e3-bd95-5221d549557b.png)

2) Added by @carina29: The same functionality ( displaying/hiding delete button in case of Events was also totally missing so this functionality will be also added with this change). => When an Event was already shared the Delete icon will always appear, when not the Delete icon will not appear.

### Proposed Change
1) The delete button should not be displayed for Cases that were not sent to the Reporting Tool.
2) The same behaviour described above should be in place for Events too

Added

**Comment by carina29** [comment]
The problem was that besides checking if the case/event was already shared with Reporting Tool, also the value of "Don't send to Reporting tool " checkbox was checked.

In https://github.com/hzi-braunschweig/SORMAS-Project/issues/10833 we agreed ( please check my last comment from this issue) that the delete icon should appear even if "Don't send to Reporting Tool" was set to True if earlier the case/event was already shared. 

Based on this requirement (https://github.com/hzi-braunschweig/SORMAS-Project/issues/10833)  and this change's requirement the conclusion is  that the Delete Icon should appear always if at least once the case/event was shared ( independently of the value of "Don't share with Reporting Tool" checkbox.

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version 1.79.0-SNAPSHOT(aa62529).

Note: the events that can be shared to a reporting tool are the ones with 'Event Status' = 'Cluster'.
