### ISSUE TITLE
Bed-side lab testing

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1109]
Informants and Officers need to be able to document certain Pathogen Tests on their own without the need of sending the samples to a laboratory first.

Prerequisite: App users need to be able to create and edit pathogen tests #1134

- [x] Add new required field labType to the sampleDto and the backend and app entities. Values: external, internal
- [x] All lab and shipment/received fields should only be visible when external is selected.

Based on that a user can create a sample for internal testing and add a pathogen test to it using rapid test as type (already exists).

**Comment by MartinWahnschaffeSymeda** [comment]
Notes from review:

- [ ] The final result of the sample likely needs to be set based on created pathogen test. Same process that happens when doing this in the web app. 
* What about the lab field for bed-side tests?
* What  about the "verified by supervisor" field?

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym I have merged this now, but this needs some further work:

The final lab result of the sample needs to be displayed in the read and edit form of the app
The final result of the sample likely needs to be set based on created pathogen test. Same process that happens when doing this in the web app
The fragments still have the most recent pathogen and additional test layouts. At least the pathogen test layout is seemingly no longer used and can be removed. I'm not sure about the additional tests. Since there is currently no way to edit them in the app the "most recent" layout probably still makes sense for them.
