### ISSUE TITLE
[S2S] Error during share operation_ unmatched country: Deutschland]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11121]
### Bug Description

Accepting a case leads in the following error message:
![image](https://user-images.githubusercontent.com/100844689/206005091-0950080d-d146-4b4e-bb73-0a1d876b9134.png)

#### Steps to Reproduce

1.
2.

#### System Details

* Device:
* SORMAS version: 1.77.2
* Android version/Browser: edge
* Server URL: 1402 to release-sormas-x
* User Role: admin

### Additional Information

application log source system_1402:
[application log source system_1402.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10169789/application.log.source.system_1402.txt)

application log target system_release-sormas-x:
[application log target system_release-sormas-x.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10169794/application.log.target.system_release-sormas-x.txt)

**Comment by JonasCir** [comment]
The `uuid` for `Germany` in both systems is different, so the error is expected. This is not an error in the application. At some time in the past we had to update the Germany entry in central because naming was wrong, see [here](https://github.com/hzi-braunschweig/SORMAS-central-data/commit/583beed094548333f60594bcb5c2ccfcdefd81cd#diff-54f9de0ebceb32f432a6de059c6ee31486f2040b41b8e577ff39a90143096ec7L913).

As we had to switch out the `uuid` it is clear that this cannot be picked up by the normal sync, which relies on the `uuid` to be correct. TL;DR; NL needs to fix this by hand in the DB.



test1402:
```
sormas=# SELECT defaultname, uuid, changedate from country where defaultname='Germany';
-[ RECORD 1 ]-------------------------------------
defaultname | Germany
uuid        | 2c5c1849-9d24-5c63-beab-ddb0965c89d8
changedate  | 2022-07-08 11:59:46.057
```
release-x
```
SELECT defaultname, uuid, changedate from country where defaultname='Germany';
-[ RECORD 1 ]-------------------------------------
defaultname | Germany
uuid        | 6f51e20f-a727-5010-9b39-fef592fbe358
changedate  | 2022-05-27 11:04:07.397
```
