### ISSUE TITLE
[S2S] Error message when the receiving instance accepts a share of a Case which was soft-deleted or the share was revoked meanwhile by the sending instance 

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#11143]
### Bug Description

When a receiving instance accepts a share for a Case that was soft-deleted meanwhile by the source system, an error message is thrown
The error is also reproducible if the source system revokes the share.

#### Steps to Reproduce

1. Open a Case and send the Case from Sormas A to Sormas B with ownership handed over;
2. Soft-delete the Case;
3. Open Sormas B and accept the share;

#### Screenshots
![image](https://user-images.githubusercontent.com/89522688/206560356-5214e37a-3a44-4e44-9157-ed0d359576a8.png)

#### System Details

* Device: Windows 10
* SORMAS version: 1.77.3
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and release-de.sormas.netzlink.com
* User Role: admin + national user

### Expected Behavior
Needs to be discussed.
However, my suggestion would be that when the receiving instance tries to accept the share, he should be informed that the share is no longer available and cannot be processed, or something like that.

**Comment by dragosb-vg** [comment]
The issue is only occurring when the target system page is opened on the 'Share directory' page **while performing the case deletion**. On page refresh, the share request is deleted.

The behavior for shared entity deletion is described in ticket [#10625](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10625), but the behavior for this situation is not specified.

**Comment by abrudanancuta** [comment]
Validated on test.de2, test.de1, with the version: 1.79.0-SNAPSHOT (2cbcbbe)
