### ISSUE TITLE
[ ] - Brackets in comment fields lead to server connection lost

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#11235]
### Bug Description

When users enter [] brackets in comment fields, saving leads to server connection lost. This can only be reproduced on itz Bund instances.  

#### Steps to Reproduce

1. Enter following Text as an example in comment fields:  Feld 8421 - Einheit: [kA]; Feld 8480 - Ergebnis-Text: [positiv]; Feld 8470 - Testbezogene Hinweise: [CT-Wert: SARS-CoV-2-RNA (Ct-Wert):32.3]
2. Click save 

#### System Details

* Device:
* SORMAS version: 1.77.3
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

when entering [] - brackets in comment fields, the changes can be saved correctly without server connection lost.

**Comment by MateStrysewske** [comment]
Closing this issue as this has been discussed quite a few times before. It's exclusive to itz Bund instances, if I remember correctly, because of Firewall settings that prevent those kinds of special characters. I think the discussions have already been taken outside this repository. @markusmann-vg please reopen this issue if I'm mistaken.
