### ISSUE TITLE
Entities read-only can be soft deleted from API [1]

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11319]
### Problem Description
The case described refers to the environments that have S2S.

As NatUser+Admin having a Case, Contact, that is read-only(to view) can make an API request to delete that entity.
In the UI the entity is not possible to be deleted because the delete button is not enable.

The entity is in read-only mode because:

- was handed over to another health department
- was received with only to view from another health department

### Proposed Change
- Allow users who have the respective delete user right to delete read-only entities ONLY if they are in their jurisdiction

### Additional Information
The changed appeared while testing this ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/8465

**Comment by sergiupacurariu** [comment]
@markusmann-vg @abrudanancuta @MateStrysewske The delete restriction implemented impacts also the cases and contacts merge flows. For example, we have 2 cases (first and second) that we want to merge. The second one is outside of the user's jurisdiction. If the user picks the first one the merge process will be interrupted because this user cannot delete the second case as it is outside of his jurisdiction. This behavior is similar to what happens on save. In the same example if the user picks the second case the merge process will also be stopped as saving is not possible. 
The kind of merges mentioned in the above example can still be performed by an user with higher jurisdiction.

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe @sergiupacurariu That sounds like an issue to me; do we have the possibility to overwrite the deletion restrictions in case of merging?

**Comment by MartinWahnschaffe** [comment]
I don't think that we should override those. If the user doesn't have full access to the case they should not be able to merge it.
The question is whether the user should not be able to start the merge for this in the first place or whether we need to propose what to do to the user (e.g. ask a responsible user to hand the case over into your jurisdiction).

**Comment by sergiupacurariu** [comment]
@MartinWahnschaffe I had a discussion with @MateStrysewske and checked on the web app the messages returned when the user is not able to merge.  The save and delete messages are meaningful. Due to this, I will merge the ticket. However, a change request ticket will be created in order to clarify what cases should be shown when "Merge Duplicate Cases" feature is triggered and how to deal with cross jurisdictions merges.

**Comment by abrudanancuta** [comment]
The ticket will be reopen because the problem described in the ticket is not fixed.

**Comment by abrudanancuta** [comment]
The ticket is closed, and as result of discussion with @sergiupacurariu a new ticket related to S2S will be created for the UI part.
This ticket covers only the BE part (API endpoint to delete an entity) that checks for the logged in user if has rights of deletion and has the correct jurisdiction to do the delete action.
The UI part for having enable delete button for S2S environments in case of read-only entity will be covered with this ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/11482
