### ISSUE TITLE
Error message appears when opening Epidemiological data tab for a case created from contact

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11337]
### Problem Description

When opening the Epidemiological data tab for a case, that was created from CONFIRMED contact an error message pops up.

#### Steps to Reproduce

1. Login as a National user
2. Create contact
3. Click on epidemiological data tab
4. Click on YES button in Exposure details known
5. Add new entry
6. Fill the data and save
7. Click on the Contact tab
8. Select COMFIRMED contact from contact classification
9. SAVE contact
10. Create a case from contact with a required data
11. Click epidemiological data tab

#### Screenshots
![image](https://user-images.githubusercontent.com/105210214/212057969-5de9a18d-29a0-4d94-acba-7e69ff193eb7.png)

#### System Details

* Device: Windows 10
* SORMAS version: Version: 1.79.0-SNAPSHOT (50d6548)
* Android version/Browser: Chrome
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: National user

### Expected Behavior
Exposure details are displayed wiyhout any error.

**Comment by carina29** [comment]
I've received the logs from @abrudanancuta from https://test-auto.sormas.netzlink.com/.
[EpiError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10411824/EpiError.txt)


I've investigated the problem and in the logs is visible that a NullPointerException is thrown from ExposuresField.java line 230.

This line created the NPE because exposure.getContactToCase() existed but exposure.getContactToCase().getCaseName() was null and it was not checked the value of it:
exposure.getContactToCase().getCaseName().buildCaption()

@hms-sgent we'll let you know when the changes will be testable on https://test-auto.sormas.netzlink.com/.

**Comment by hms-sgent** [comment]
@carina29 thank you for your investigation

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.79.0-SNAPSHOT (edb980c)

**Comment by carina29** [comment]
Hello @hms-sgent ,

The fix was deployed on https://test-auto.sormas.netzlink.com/ and it was tested by @abrudanancuta and me too.
Everything looks fine, the error message is not appearing anymore. You can also test it :) 

Regards,
             Carina

**Comment by hms-sgent** [comment]
Hi @carina29,

Thank you for a quick fix! I verified it and it looks fine to me too :)

Regards,
Halima

**Comment by carina29** [comment]
@hms-sgent you're welcome :)
