### ISSUE TITLE
Unable to modify responsible Jurisdiction in tablet version

### ISSUE THREAD

**Issue by gtmdipen** [hzi-braunschweig/SORMAS-Project#11440]
![IMG_4940](https://user-images.githubusercontent.com/33200588/216751488-525f0cdb-9779-4883-b290-7aca18c16611.jpg)

### Problem Description

Unable to modify Responsible Jurisdiction from Tablet However it can be done from web version.

User: Case officer/Surveillance officer

### Proposed Solution

Grant permission to select responsible jurisdiction in tablet

**Comment by adinaflorea9** [comment]
@gtmdipen Thank you for submitting this issue, but in the future, please refer to the contributing guidelines and submit the appropriate type of issue.

The current behavior is as follows for a Case Officer or a Surveillance Officer - if the entity (case. for instance) is within the user's jurisdiction, then the user can edit the responsible jurisdiction of the entity both in the web app and the mobile app.

The responsible jurisdiction of the entity is not editable both in the web app and the mobile app if that entity is not within the user's jurisdiction, Therefore, the behavior reported here could not be reproduced.

Could you please provide the following details so that I could further look into this:
- [ ] all of the exact steps to reproduce that you took (from starting to create the entities, which user created them, which jurisdiction do the Case Officer or the Surveillance Officer have)

- [ ] the SORMAS version where you were able to reproduce this

**Comment by MateStrysewske** [comment]
@adinaflorea9 The screenshot in question shows the creation of a new case, not a user trying to edit an existing case.

However, @gtmdipen, this is on purpose. Users of the mobile app are restricted from creating data outside their own assigned jurisdiction. What I think might be an issue though is that the user, even though they're on district level, also can't edit the community, and I believe that should definitely be possible. We'll investigate this.

**Comment by adinaflorea9** [comment]
@MateStrysewske  Thanks you!  Missed that somehow

**Comment by bernardsilenou** [comment]
Informants (hospital + POE) do not have the right to change their jurisdiction when reporting or editing cases. 
@adinaflorea9  can you verify that you did not use the hospital informant role?

**Comment by adinaflorea9** [comment]
I was not logged in the mobile app with a Hospital Informant or a POE user. I was using a Surveillance Officer.

For Hospital Informants and POE Users in the mobile app, they are not able to report entities that are outside their jurisdiction, just as @MateStrysewske mentioned above that is the expected behavior in the mobile app. The Surveillance Officer that I was using is also not able to report entities outside their jurisdiction in the mobile app, as per the expected behavior. 

@MateStrysewske I am not sure if there is such a right as Bernard mentioned above, as I could only find in the list the right to 'Transfer cases to another region/district/facility'.

@bernardsilenou If you feel that such a right is needed, please document this request in a change request and specify the reason for this need and the necessary details.

**Comment by MateStrysewske** [comment]
No, there is no such user right.

**Comment by bernardsilenou** [comment]
@adinaflorea9 @MateStrysewske 

@adinaflorea9 mentioned that `The Surveillance Officer that I was using is also not able to report entities outside their jurisdiction in the mobile app, as per the expected behaviour.` This may not be a bug.
The checkbox called "place of stay differs from responsible jurisdiction" offers the user the option to create cases outside their jurisdiction.

**Comment by bernardsilenou** [comment]
@gtmdipen @adinaflorea9 @MateStrysewske 

1. One reason why we added the check box "place of stay differs from responsible jurisdiction" was to permit users to report outside cases ie cases that are in their jurisdiction but were supposed to be reported by another jurisdiction (maybe based on their home address)
2. The responsible jurisdiction is the jurisdiction related to the user, probably why it can not be changed
3. What about preventing users from changing their responsible jurisdiction (on creation form only) and providing the option  "place of stay differs from responsible jurisdiction"  to all user roles (flexibly created + default(except informants))? We can add it on the edit forms also, both web and mobile apps. 
4. Allowing users (except informants) to change responsible jurisdiction only on edit form == transfer of the case

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't believe that was the purpose; iirc the checkbox was added because it's possible that a person is situated outside the jurisdiction that is responsible for managing the case; e.g. in Germany, when a citizen from Hamburg gets admitted to a hospital in Berlin, Hamburg is still responsible for the case. The purpose is not to allow users to report cases outside of their jurisdiction - it's to allow them to report cases IN their jurisdiction, but still indicate that they are currently situated somewhere else.

The checkbox "Place of stay differs from responsible jurisdiction" does not make sense for a user on facility level in my eyes because those users are supposed to only manage their specific facility; if they report cases, those cases are in fact situated in their facility. In order for the checkbox to make sense, we would need to give these users the right to change the responsible jurisdiction irrespective of their own jurisdiction (which could be done by introducing a "Allow creation of cases outside own jurisdiction" user right). Such a user right does not exist right now though.

**Comment by d1pen** [comment]
@MateStrysewske 
Thank you the comment. 
This is the exact request that we are seeking from Nepal. 
If it can be done from user roles. It would be great specially for Nepal implementation.

**Comment by bernardsilenou** [comment]
@MateStrysewske @d1pen 
@MateStrysewske Thanks for the explanation, I did not get it and the data field is not self-explanatory as you did. I thought the home address of the case person was used to map the citizen's jurisdiction (Hamburg) in reporting to national authorities.

The need to report a case in the user's jurisdiction but recording that the case is in another jurisdiction is very rare in the international context. Facility and district users often report cases that they face, a proportion having home addresses in their districts and others outside. Thus very likely that a user would want to report a case for another district rather.

In addition to adding the rights to "Allow creation of cases outside own jurisdiction", I would also like to suggest that we make "place of stay differs from responsible jurisdiction" DE only. If you do not see any harm, then we can create another issue and tag it NP

**Comment by MateStrysewske** [comment]
I don't think making that field DE only is a good idea, the process might be pretty similar in other European countries.

**Comment by MateStrysewske** [comment]
@bernardsilenou I would say so, yes

**Comment by d1pen** [comment]
With one addition: make the place of stay static if it is a hospital user. So that they do not need to double enter the place of stay field while they are admitted in the hospital.

**Comment by bernardsilenou** [comment]
> With one addition: make the place of stay static if it is a hospital user. So that they do not need to double enter the place of stay field while they are admitted in the hospital.

@d1pen  this is already the case for facility users (hospital informants)

**Comment by bernardsilenou** [comment]
Replaced by https://github.com/hzi-braunschweig/SORMAS-Project/issues/11512
