### ISSUE TITLE
[DEMIS - External messages] 'Laboratory' for sample and pathogen test should be imported from the external message

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11456]
### Problem Description

Currently, we do have a mapping for notifierFacility.identifier.value, which is mapped to Sample.lab and PathogenTest.lab; and a mapping for notifierFacility.name.value, which is mapped to Sample.labDetails AND PattogenTest.labDetails.

### Proposed Change

The current mapping however does not always bring the correct information from the external message into the sample and pathogen test, when a message is processed.

As observed, even though some of the laboratories listed in the external messages exist on the instance where this is processed, often times the value is added in the sample and test as 'Other laboratory' + 'Laboratory name and description' instead of the laboratory being selected directly from the list.

- [ ] the information referring to the laboratory and laboratory details from the external message should be imported into the sample and pathogen test result forms when the message is processed;

### Acceptance Criteria

- the fields for 'Laboratory' and 'Laboratory name and description' should remain editable after the information is prefilled;
 
- current validation for those fields should be maintained.
 
### Additional Information

Part of #11447

**Comment by adinaflorea9** [comment]
I was able to reproduce this issue on test-de2 for the following laboratories:
![image](https://user-images.githubusercontent.com/96909231/222145845-91278321-3bc2-448a-8b94-9e99558b2aba.png)

1. For Testlabor DEMIS - when 'Testlabor' is present in the lab message, the value ''Testlabor DEMIS' is in the sample and pathogen test directly selected from the dropdown.

2. For Primarlabor and Sekundarlabor - when the values 'Primarlabor' or 'Sekundarlabor' are present in the lab message, the values 'Primarlabor' and 'Secundarlabor' are not selected directly from the dropdown in the sample and pathogen test, but the vlaue 'Other laboratory' is selected and the corresponding values are filled in the free text field 'Laboratory name and description'.

This behavior seem inconsistent to me, as all three laboratories do not have an assigned specific region and district, they are all active, they all come from the lab messages we imported into test-de2 and at lest in the UI I can not see a difference between them.

Also, all three values are visible in the 'Laboratory' dropdown and are selectable when samples are created, so in the regular flow they all present the same 'behavior':
![image](https://user-images.githubusercontent.com/96909231/222146824-ad2700ea-0a66-45be-8bb3-dd2b36b80530.png)

**Comment by abrudanancuta** [comment]
The lab messages used in the comment above, they were added intentionnaly to map or not map the laboratories that are on test.de2.
The message id(lab id) XA2TLJ-C4HOGN-27I2KA-YYLHSDFE it was intentionaly to not map any laboratory
The message id(lab id) U55REN-KZ6TBL-MOYE6N-QELWCFT4 is mapping an existing laboratory.

The reason why the name of the Laboratory is completed with "Organization for laboratory tests" and not with a selected Laboratory from the dropdown is because the mapped laboratory is not found in Sormas, the id from the Json coming from Demis is not found in Sormas(ex: XA2TLJ-C4HOGN-27I2KA-YYLHSDFE)

As a conclusion:
if the JSON which comes from Demis contains an ID that is existing in Sormas, then it will map to that laboratory
if the JSON which comes from Demis contains an non-existing ID in Sormas, then it will not map any laboratory, it will choose Other and as description will have the name specified in the JSON(for the above lab messages will have Organization for laboratory tests)

More details about the mapping of Facility can be found in this story: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8949

**Comment by markusmann-vg** [comment]
Mapping works in production as expected.
