### ISSUE TITLE
[Events] Events without jurisdiction can not be saved

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11502]
### Problem Description

Due to a validation that was added in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10110 events can not be saved (created or edited) without a jurisdiction set.

It used to be possible to create events without a jurisdiction, or edit them without having a jurisdiction, as long as the associated event participants had a jurisdiction set.

Additionally, it seems like the region and district fields are not marked as mandatory when no country is selected in the country dropdown (maybe this is only applied after doing an initial change, or it never happens), even when a server country is specified in the properties file. The fields are only supposed to be optional when no server country is specified in the properties.

#### Steps to Reproduce

1. Open the 'Create new event' form - the fields for region and district are mandatory (if the country is not set or if the country is set to Germany);
2. For an event already created, set a region and a district for the associated event participant; then remove the region and district that were previously on the event page;

### Actual Behavior

The events that do not have a region and district filled can not be saved.

### Expected Behavior

API level/backend validation should match the UI validation here, i.e., region and district are mandatory except for the following scenarios:

1) A different country than the server country is selected (if NO country is selected, the fields still have to be mandatory)
2) No server country has been specified in the properties file and any country has been selected (makes sense to review whether this is a good idea, but right now that's how we do it in the UI, so we should reproduce this behavior)

Additionally, make sure that the region and district fields are always marked as mandatory if a country is specified in the properties file and no country is selected in the country dropdown.

#### Screenshots

![image](https://user-images.githubusercontent.com/96909231/218685845-cd265a87-b890-4076-bdc3-72f2a301b500.png)
![image](https://user-images.githubusercontent.com/96909231/218685860-ec4f5809-7f9a-46c2-ada1-883fbdc9d018.png)

#### System Details

* Device: Windows 10 
* SORMAS version: 1.80.0; 1.78.0
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by bernardsilenou** [comment]
- Entities without jurisdictions are not useful to be in the system, what was the reason to link the jurisdiction of the event to that of the event participant?
- No matter the country, it would be good to have the region and district  to be required when creating or editing events
- Rather than  implementing the expected change `It should be possible to create or save/edit an event that does not have a region and a district set.`, it's better to prevent such situatons

**Comment by adinaflorea9** [comment]
@MateStrysewske would it be then an option to update this ticket as change and request that at all timed the 'Region' and 'District' fields of the 'Location' section of an event be mandatory? 
If yes, what should happen with the event that were already created without those fields being filled? As the behavior described regarding the errors would still be reproducible; the issue is not necessarily when it is reproducible on the event page (as the user could simply fill in those fields) but in 'Bulk edit mode' when a large number of events would still be un-editable.

**Comment by MateStrysewske** [comment]
@bernardsilenou @adinaflorea9 No, that's not an option, at least not in all cases. They need to be optional in the following scenarios:

1) A country that is NOT the server country has been selected, because it is very likely that regions and districts have not been added for other countries.
2) NO country has been selected AND there has not been a server country specified in the properties file (which would be kind of a misconfiguration in the first place); in this case, since we can't assume that "no country equals server country", which we usually do when no country has been selected, we also can't make these fields mandatory.

The problem in this finding is that there's apparently an inconsistency between API level validation and UI validation, and that needs to be solved. @adinaflorea9 can you please check whether you have a server country specified in your properties file? I guess you don't, because otherwise the region and district fields should be shown as required in the UI when you don't select a country. It's definitely expected that they are optional when you select Afghanistan (unless you specifiy Afghanistan as your server country of course).

**Comment by adinaflorea9** [comment]
@MateStrysewske I have Germany - DE specified in my properties:
![image](https://user-images.githubusercontent.com/96909231/221537533-591cb4e1-214c-4c5f-ae2f-cbdab663e3b8.png)

So when I have Germany or no country in that filed, then the region and district fields are not marked as mandatory, but I still can not save the form as an error message appears letting me know that those fields are required.

The same happens when I select Afghanistan, or any other country, the fields are not marked as mandatory, but when I try to save the form I get the same message that says that those fields are mandatory.

**Comment by bernardsilenou** [comment]
@adinaflorea9  Is the country name in the properties file the same as that in the system?  Issues can occur when the country names is not the same

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Thanks for the clarification.
What is your take on this? Following this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/11502#issuecomment-1446020522 :
1. OK
2. If NO country is selected in the properties file, then it means the instance represents an international instance. At this point, can we not enforce that jurisdiction is required? ie if users do not want to associate the instance to a specific county, then they must first import the infrastructure of all the countries they wish to document data from.
3. In terms of reporting (dashboard,stats), 
     3.1 for an instance linked to a country, records without jurisdiction can be documented but they are not useful since they do not contribute to the counts.
     3.2 for an instance not linked to a country, we can prevent documenting records without jurisdiction

**Comment by MateStrysewske** [comment]
@adinaflorea9 I'm not sure whether "Deutschland" is legit here because the default names in the database are English; can you change it to "Germany" and check whether that changes the behaviour?

@bernardsilenou Right now SORMAS isn't really crafted towards being used in an international context, i.e. across multiple countries; basically, no country being specified in the properties file is currently considered a misconfiguration. Even if you would use SORMAS in different countries, it's still possible that you want to create an event outside the boders of those countries, e.g. because you know that a lot of people from your country have visited that event (e.g. a big festival or a sports event, like a world cup). So the requirement that it must be possible to create events without a jurisdiction still remains relevant.

**Comment by adinaflorea9** [comment]
@MateStrysewske The names in my DB, by default (from the import file that I use and how they are displayed in the DB) are in German.

I tried to update the value to Germany as you suggested above, and the behavior is pretty much the same - I can not save the form if I do not have a region and district specified. 

What has changed is that now the fields are never marked as mandatory.

**Comment by MateStrysewske** [comment]
@adinaflorea9 Okay, seems like there's something not working properly there then. The region and district field should be marked as mandatory when the country dropdown is empty. I think we should fix this alongside the bug that you've reported here, I'll update the initial issue description accordingly.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following scenario:

Steps to reproduce:
1. Create an event with any country other than the empty value or the server country (make sure that you have at least 1 region and district created for the chosen country);
2. Create an event participant without jurisdiction associated with that event;
3. Then go to the event page and remove the region and district of the event.
Actual behavior:
Both the event and event participant no linger have a region and district. The fields for region and district on the event participant page are marked as mandatory and highlighted but the user can not see that unless they navigate to the event participant page. 

Expected behavior: It should not be possible to save an event without region and district set if at least one event participants does not have its own responsible region and district.
