### ISSUE TITLE
Enable the 'Delete' button for users that have deletion rights but no edit rights over entities [5]

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11509]
### Problem Description
Have a User role configured like this:
![Screenshot 2023-02-15 at 10 11 36](https://user-images.githubusercontent.com/91872179/219301925-49741f14-8768-4212-b1d9-05a91ff9ab3e.png)
 The user having the role above cannot delete user roles because it has disable the delete button

As discussed with @carina29 and @MartinWahnschaffe the current ticket has been converted from bug report to change request. There is a use case for the change requested, from a data security point of view - a user might be created that is only tasked with deleting data from SORMAS, and no edit rights over the respective data.

#### Steps to Reproduce

1. Login with the user explained in the Bug description section
2. Go to User Role tab
3. Choose a Role from he list
4. Edit the role
5. Check the delete button

### Actual Behavior
The delete button is disable

### Expected Behavior
The delete buttons should be **enabled** to be able to delete the entity for which the user has delete rights, but no edit rights. (View rights over the entity are a prerequisite).

### Additional Information
The same happens also for other entities. This scenario will be extended also to the rest of the entities, to support the deletion action without having the right to edit.

Entities that should support delete right without edit right:

- [x] Users
- [x]  Case
- [x]  Contact
- [x] Task
- [x] Event - Added by @carina29 - https://github.com/hzi-braunschweig/SORMAS-Project/issues/8868 should be retested by QA Team too because of the change on EditDataView component
- [x] Event Participant
- [x] Event Groups (added by @adinaflorea9 and @carina29)
- [x] Event Actions (added by @adinaflorea9  and @carina29  )
- [x] Samples
- [x] Additional Test  (added by @adinaflorea9 and @carina29)
- [x] Immunization - Added by @carina29 :  https://github.com/hzi-braunschweig/SORMAS-Project/issues/6639 should be rechecked since here was added that without IMMUNIZATION_EDIT right the returned EditPermissitonType will be REFUSED.
- [x] Vaccination (Added by @carina29 ) - Till now if the IMMUNIZATION_EDIT right was missing, the buttons ( discard, save, edit) did not appear at all. It was agreed with @MateStrysewske to display/enable/disable the buttons in the same way as we have for Additional Tests.
- [x] Entries
- [x] Campaigns (added by @adinaflorea9 and @carina29)
- [x] Campaign Form Data  (added by @adinaflorea9 and @carina29) - (Added by @carina29 ) There was no editAllowed flag on Campaign Form Data component. It was added the isEditAllowed flag as we have it in case of other entities ( when the user has edit right will be able to edit the component)

**Note:** In this ticket the changes related to mSERS (Aggregated Reports), Messages and Child Entities (Prescription, Follow-up, Treatment, Clinical course, Pathogen test ) and the changes related to the mobile app will not be handled.

**Note**: If the entity was deleted, instead of the Delete button the Undo Deletion will remain enabled.

Take into account that when deleting an entity, the user should also have the correct jurisdiction. The validation should be done on BE and FE.

**Comment by adinaflorea9** [comment]
I am reopening the ticket so that the following behavior can be updated to be consistent with the behavior in the other directories:

- a user restricted by jurisdiction can delete events and event participants that are not in the user's jurisdiction. The behavior for events is reproducible only on the current version of SORMAS 1.82.0-SNAPSHOT(6dc0dba) while the behavior for the event participant is reproducible on released versions of SORMAS 1.81.0 AND 1.80.0.

Steps to reproduce:
1. Create a user restricted by Region A and District A;
2. With another user, create an event and an event participant in Region B and District B;
3. Save the URL of the event and event participants;
4. Log in with the user created at step 1 and observe and click the 'Delete' buttons on the event page and the event participant page.
Actual behavior: the user can successfully delete the event participant and the event that is not within their jurisdiction.
Expected behavior: 
- [ ] the user should not be able to delete the event participant or the event that is not within their jurisdiction; 
- [ ] for consistency with the behavior in cases and contacts, the delete button can be visible and clickable, the pop-up for deletion reason should appear, and when the user clicks 'Yes' a warning message should appear in a similar format to the one currently implemented in cases and contacts: 'The event outside the user's jurisdiction can not be deleted. Please reload the page to see the latest changes' and 'The event participant outside the user's jurisdiction can not be deleted. Please reload the page to see the latest changes'.

**Comment by adinaflorea9** [comment]
Event Actions that belong to events outside the user's jurisdiction can be deleted when the user has only the following user rights:
![image](https://user-images.githubusercontent.com/96909231/224939808-b6d56086-25b5-49cb-9079-7b98cb959359.png)
Expected behavior here is to prevent the deletion of event actions that are outside the user's jurisdction.

Note: When the user also has edit rights over actions and events, the deletion of actions outside the user's jurisdiction is prevented as the whole page is read only.

**Comment by adinaflorea9** [comment]
Immunizations and vaccination outside the user's jurisdiction can be deleted by a user that has immunization view and delete rights (and is restricted by a region+district).

- [ ] The immunization outside the user's jurisdiction can be deleted if the user has the URL of the immunization. 

- [ ] The vaccination outside the user's jurisdiction can be deleted if the user has the link of the person page associated with that vaccination (the vaccination can be deleted only from the person page and event participant page, not the case page or contact page)

**Comment by adinaflorea9** [comment]
Travel entries outside the user's jurisdiction can be deleted if the user has the URL of the entity (the user has the following travel entry related rights: view existing travel entries, access the travel entry directory and delete travel entries from the system).

If the user also has edit rights over travel entries, the deletion is prevented as the button and the whole page is read only.

**Comment by adinaflorea9** [comment]
Campaign forms outside the users jurisdiction can be deleted when the user has the URL of the form. The user has the following rights:
![image](https://user-images.githubusercontent.com/96909231/225042540-8c8b917b-1cfe-442c-84d4-9dad60ce84a0.png)

**Comment by carina29** [comment]
**UPDATE:**
The jurisdiction check and message was added for the following entities:
1)Event 
2)EventParticipant 
3)TravelEntry 
4)Immunization
5)Vaccinations ( can be checked from Person Page and from EventParticipant Page)
6)Campaign form data
7)Actions

For the above entities, when a deletion is tried and the user has a different jurisdiction the message will appear in the console log and also in the UI. 
**NOTE:** The message will not appear in the UI for Event Actions and Campaign Form Data but the delete will not take place ( in the server log the exception will be displayed)

It was agreed with @MateStrysewske that does not make sense to investigate why the message is not appearing in UI too in case of Event Actions and Campaign Form Data, since he wants to create a follow-up ticket based on which the Delete button should be enabled for a user only if the jurisdiction is the same.

**Comment by MateStrysewske** [comment]
Reopening because there's a test failure and the changes won't work for campaign forms and actions

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(b40a84e).

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to:

I am reopening the ticket due to the following:

I:
1. Have the featuretype EDIT_ARCHIVED_ENTITIES set to false;
2. Log in the app and archive an event participant;
-> the side cards on the event participant tab are still editable.

II:
1. Have an event and event participant set in jurisdiction 1;
2. Save the URLs;
3. Log in with a user restricted to Jurisdiction 2;
4. Paste the URL of the event and of the event participant;
-> the side cards on the event participant tab are editable; the user can create entities but they are not displayed on the cards;

Expected behavior: The side cards should not be editable.

@MateStrysewske believed that the issues are related to this ticket and not #11514

**Comment by adinaflorea9** [comment]
Verified ticket after the latest fixes were applied on the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(bed5a43).

**Comment by carina29** [comment]
I'll reopen this ticket in order to add a styling ( a space between the total number of test results and the text).
All the other functionalities were already tested by @adinaflorea9.
