### ISSUE TITLE
POC Performance tests - Using Gatling framework to have performance tests 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11543]
### Problem Description
At the moment the perfomance tests are written  with Jmeter but only for the test environments. There is no possibility to configure the already existing ones to be run on release environment.

### Proposed Solution
Because there is a need to run performance tests on release environment, it is also the need to re-write them.
Having a POC with Gatling which can be included in the E2E tests will give us the possibility to run the tests on multiple environments.

Update (Razvan)
Using Gatling would allow us running performance tests over all testing environments from json file.
This would increase security, we'll get rid of exposed data for test-performance environment, will allow us to query entities UUIDs from API and use them in tests without hardcoding them, use automation framework json generation implementation.
Report is more readable than jmeter.
Has implementation with Jenkins and is Java based.
Will allow us to vary user threads from command instead of hardcoded values, and time.
Will reduce number of jenkins jobs for performance, since we'll be able to transform a job to cover different scenarios (time measuring, load, breaking point of controllers etc).

**Comment by rdutu-vg** [comment]
Gatling documentation:
https://gatling.io/docs/gatling/

Achievements:
* Managed to implement users and time parametrization to allow different types of performance testing
* Managed to implement automation framework approach to read data from json in order to remove environment, users and password

Benefits:
* Allow us to run same code over multiple testing environments
* Better reporting with more useful metrics
* Reusability of code and maintainability 

POC branch:
https://github.com/hzi-braunschweig/SORMAS-Project/pull/11589

Report example:
![main report](https://user-images.githubusercontent.com/83643843/224657652-54b20b6b-2d80-4768-a4b8-e1f223029ca9.JPG)

Extra useful KPI found during checks:
Tested GET UUIDS for multiple endpoints with 100 users in 1 second and discovered that first 44 users are getting the response under 800ms, then the rest of the users are getting it in 800-1200ms. 
This will allow us to better monitor the performance of controllers even if they don't fall as it happens right now with Jmeter.

![report 2](https://user-images.githubusercontent.com/83643843/224657994-a6f4e6bf-9841-41b0-921b-bef6f9a95c56.JPG)
