### ISSUE TITLE
[SurvNet] Sending cases to SurvNet randomly fails

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11549]
### Problem Description

On the release instance **https://test1402.sormas.netzlink.com/** sending cases to the external surveillance tool SurvNet randomly leads to an error and the case is not sent. 

#### Steps to Reproduce

1. Log in with the Admin+NatUser into https://test1402.sormas.netzlink.com/;
2. In the cases directory, open multiple cases and try to send them to SurvNet.

### Actual Behavior

Some of the cases can be sent, some of them can not and an error appears:
![image](https://user-images.githubusercontent.com/96909231/221205851-80fe77cb-3505-49df-bf93-e88e0c277097.png)

### Expected Behavior

All of the cases should be successfully sent to SurvNet.

#### System Details

* Device: Windows 10
* SORMAS version: 1.80.0
* Android version/Browser: Chrome
* Server URL: https://test1402.sormas.netzlink.com/
* User Role: Admin+NatUser

### Additional Information

Logs from the server:
[Converter_1402.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10825309/Converter_1402.txt)

[SurvnetError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10825310/SurvnetError.txt)

**Comment by adinaflorea9** [comment]
I was able to reproduce this issue today on https://test-de2.sormas.netzlink.com/ - it was reproducible when trying to send cases to the reporting tool and the cases were created by the automation admin (so created via API calls).

**Comment by carina29** [comment]
I'll attach the analysis sent to Alicia Raber from Netzlink. 
Based on her answer (how she creates cases/events) we will know if this ticket can be closed or further steps should be done. 

The following cases were analyzed:
282ce215-e87c-42f2-8b01-298a567a1917 | 2023-02-23 11:56:23.04 
3efc7679-e2f1-448b-a6ca-8b5a1c9c6186 | 2023-02-23 11:58:19.37
fb72a16f-c6a6-4d88-b50a-34e3fb166ec0 | 2023-02-23 11:58:42.174
SOFEND-KDJ5MI-JXIVAA-PJI6KCLU        | 2023-02-23 14:00:55.519
00491f43-6c22-4ead-8431-09871bd53d37 | 2023-02-23 14:27:58.1
7669d0f3-fdfd-484a-857d-269e3bd02e6a | 2023-02-23 14:29:52.664
0e6a6ffe-a615-4b02-80ee-40f7f3e0dd83 | 2023-02-23 14:31:46.868
1c032f07-c675-4bc3-98ef-d7d8c8c8b1d5 | 2023-02-23 14:33:40.978
8fe148e9-a9ba-4fd9-b871-50ed1f894944 | 2023-02-23 15:17:31.069
40d98804-d80b-4a9e-bd1b-ae4d4fccf00a | 2023-02-23 15:19:25.21
03812208-87c9-4117-924f-176931578e96 | 2023-02-23 15:21:19.288
fac1ba77-30a4-4b9a-9300-8240d7c20a96 | 2023-02-23 15:23:13.224
XNTOBC-TUNMSD-GCWYOC-O6RF2G7I        | 2023-02-23 16:24:11.036
U3TTFI-BYEYIQ-2LOFHZ-CSS72LGE        | 2023-02-24 11:46:38.568

In the above list there are 2 types of Uuids:
1)	Cases/events with shorter Uuids ( like SOFEND-KDJ5MI-JXIVAA-PJI6KCLU)
These cases/events are created by a logged in Admin user ( Admin user will be the reporting user) and the Sending to Survnet is working without problems.
 

2)	Cases/events with a longer Uuid (282ce215-e87c-42f2-8b01-298a567a1917):
These cases/events with the long uuids were created by Rest AUTO ( which means that is not a normal reporting user logged in but a call is made from a Rest interface). 
        For these cases/events which have as reporting user REST Auto and have those long uuids, the sending to Survnet Tool is failing and those cases/events  were never sent to
      Survnet. I’ve checked the logs and it looks like one of the conversions is throwing an error because the uuid is too long ( is not a usual uuid which is shorter).
    

1.   If the creation of cases/events is done with a logged in user ( the reporting user will be a logged in user) the cases/events will be sent without problems to the Reporting tool ( the uuids will have normal size).

  If the creation of cases/ events is done with reporting user REST Auto, it should be investigated why those cases/events are created with those long uuids or change some restrictions in Survnet project in order to accept the cases/events with longer Uuids.
