### ISSUE TITLE
Samples Dashboard should display results of samples that the user has access to

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11605]
### Problem Description

As a follow-up for #10721 :
On the 'Samples Dashboard' the results displayed should take into consideration the jurisdiction of the user accessing it.
![image](https://user-images.githubusercontent.com/96909231/223695832-6ddb3256-5dd4-413c-b34c-5f1098fd6bb9.png)

Currently, for the users limited by a disease the filtering works as expected - meaning that the user can only see the results for the disease they are limited to or for 'No disease'.

But for the users limited by a region, district or community the results displayed do not take into account the jurisdiction of the user.

### Proposed Change

Take the jurisdiction of the user into account when displaying results in the samples dashboard and when filtering.

**Comment by leventegal-she** [comment]
In some situations on really huge database for users below National level the database queries could be slow because postgres can't estimate the real size of the result. This probably will be solved in future versions of postgres.

The query for getting all fields of the samples is more performant then the one selecting only a few fields

Query for all fields:
https://explain.dalibo.com/plan/d249dc39db34gce3
Query for some fields:
https://explain.dalibo.com/plan/e363903h07e8b7af

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(0c268ff).
