### ISSUE TITLE
[Statistics] Date range intervals are not calculated correctly

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#11717]
### Bug Description

In statistics menu the query which contains time attributes does not include all the records which have that attribute at the beginning or at the end of the specified interval. 

### Reproduction Steps

1. Create cases with report dates at the beginning and the end of a month.
2. Generate a report which has a wider report date range around those cases and group the results by report time month of the year. Save the monthly results.
3. Generate a report which has a date range of a single month. 
4. Check the report from point 3 with the same month from point 2. For the period of the cases create at point 1 the number of cases will be different.

### Expected Behavior

The results should be the same.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS version: 1.82.0

### Android version/Browser

Chrome

### User Role(s)

National user

**Comment by MateStrysewske** [comment]
@sergiupacurariu Interestingly I can't reproduce this on my system right now, even though I've seen it on yours. I've created a case with its report date on the 1st of February 2023 and one on the 28th of February; even if I apply a date range from the 1st to the 28th in the filters, both appear in the result.

Probably makes sense for you to pick up this bug as soon as you find the time because you already have a state on your system that allows you to reproduce the bug.

**Comment by abrudanancuta** [comment]
Validated in local environment with the version: 1.82.0-SNAPSHOT (dd8b900)
