### ISSUE TITLE
Line listing case entry [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1172]
- [x] Create mockups for app and web (mobile doesn't need inputs for region and district)

Steps to implement (web app):
- [x] Display inputs for one case by default
- [x] Allow users to add more sets of inputs/delete existing ones (except the last one in list)
- [x] Only display captions once (web app, probably not a good idea in the mobile app)
- [x] Save cases one by one, display duplicate case prompts if necessary

**Comment by MartinWahnschaffeSymeda** [comment]
Use the variables we defined as important for LBDS.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou @hzi-braunschweig Please define the fields that should be used for this, and please remember that these will be presented line by line in a popup, so having too many fields in here will make it basically impossible to use the feature in the mobile app and on small screens for the web app.

**Comment by bernardsilenou** [comment]
I suggest we start with these fields:
disease
first name
last name
state
district 
health facility
Date of onset of first symptoms. 
Date of report. I suggest we do not add report date if space is not enough because it is mostly the same date of creation since this functionality will be used mostly by DSNO and Informants
case classification
OB/ agge
Sex
Occupation
Infrastructure data should be the same only for localized users like Informants and localized DSNOs.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym @ChristopherRiedelSymeda 

### Web line listing: https://app.moqups.com/3NUENEwuOE/edit/page/afcdb72b4

* It would be great to have these additional fields as proposed by Bernard: date of onset, classification, DOB, age, occupation. Obviously this would make the grid too big, so I'm wondering whether we could restrict users to do a line list for a specific health facility (and maybe even disease) - this would save us 5 columns. This likely needs to be discussed with @hzi-braunschweig 

### App line listing

* Since users have at least 7 inch tablets, maybe we can use a vertical view and have an actual line list
* onset, classification, age, occupation, ...
* we could have a disease field in the "shared information" section. When it's empty the disease field is visible for every single case

**Comment by bernardsilenou** [comment]
I agree with you Martin, we can restrict by disease always and for informants by HF, districts and state in addition, DSNO by distinct and state by default but provide the option to change district if needed for DSNO who have the right to create cases from another district. For national users, only by disease restriction

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda @bernardsilenou DOB is already in the mockup; I disagree with classification because a) we don't have that in the normal case creation form as well and b) users should normally enter the details that are necessary for automatic case classification anyway. I don't think date of onset has to be in there because users need to visit the symptoms tab anyway to enter information about symptoms. Also, I don't think we should restrict web app line listing to facilities or even districts because line listing case entry for those will be done in the mobile app anyway (by informants or officers). That's why I think we should really limit ourselves to the most important fields, and I wonder whether something like occupation is really that relevant.

Concerning the mobile app, please take in mind that the resolution of the tablets that are in use in Nigeria is incredibly low and we don't really have nearly as much space as you might've had in mind when you wrote that comment. I don't think there's any way to have a "real" line list in the mobile app.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  I think you have a point here about the limitation of the mobile devices that we might have overlooked.
I will also like to mention that when we collect data especially in case based, the general epidemiology rule is that the data must  have "**person** (name, age, sex), **place** (state, LGA) and **time** (date of onset) variables". Date of report is for surveillance purposes not to understand the epidemiology of the disease, so date of onset has priority over all the other dates. 
 The goal of occupation is just to know if the disease is occupationally driven, so if it comes to the worse due to limitation of the devices, we can drop occupation and Date of report.

Hospital registries (Informant) and excel linelist  are often sorted by disease, this might be a motivation to limit data entry be disease.

Lets discuss this more on Wednesday.

**Comment by ChristopherRiedelSymeda** [comment]
Last commit is only work progress. There are a few things to do:
[] Make fields required (Databinding as in MergeCasesFilterComponent)
[] Fix or use correctly CssStyles.CAPTION_OVERFLOW
[] Check distance between rows
[] Check width of Popup-Window

**Comment by MateStrysewskeSym** [comment]
- [ ] Layout breaks (i.e. exceeds the window) if captions are wider than the fields (happens with french translation)
- [ ] When removing the first line, some of the captions disappear

**Comment by Iheanacho2027** [comment]
As an observation and suggestion, case classification should be included in the line list case entry

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig What do you think about @Iheanacho2027 s suggestion?
