### ISSUE TITLE
[DE] Untranslated option in Case

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#11750]
### Bug Description

When accessing a case in the section "Samples" is a wrong translated button. The button name is displayed in english.

### Reproduction Steps

1. Open SORMAS
2. Switch language in user settings to "Deutsch"
3. Go to a case
4. Look on the right hand. Section "Samples" (in German "Proben") show a sample.
5. If there is no sample available you can create a new sample.
6. After entering all data the sample is visible in case.
7. The button appears in english

### Expected Behavior

The button should show the german description "Alle Proben für diesen Fall anzeigen"

### Affected Area(s)

Web app

### SORMAS Version

1.80.0

### Android version/Browser

Edge

### User Role(s)

Admin

### Server URL

https://test1402.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
@AliciaRaber Translations are done via Crowdin; there was indeed an issue with the integration that I hopefully fixed, but in general, when strings aren't translated yet, that's because either there haven't been any translations submitted to Crowdin yet or we haven't merged them into the development branch (in that case, please let us know e.g. through a task issue or through GitHub discussions, but don't open a bug issue).
