### ISSUE TITLE
Disease: Polio, AFP & Guinea Worm generic [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1177]

**Comment by bernardsilenou** [comment]
We should consider prioritizing including AFP in SORMAS. Upper west had suspected cases and used disease X module as of now. However, many pints are still missing. Here are main points to design the module.
* Cases notifiable as usual with specific variables to be collected as on case forms.
* After 60 days from onset date, there is a follow up and documentation of data 
* SORMAS should remind the SO for follow up visit after 60 days
* Possibility to filter cases by overdue follow up 60 days
* If there evaluation confirms week legs, the case can be classified as probable
* Clinical follow up + lab = final classification

**Comment by MartinWahnschaffeSymeda** [comment]
First step:

- [ ] add new diseases to SORMAS: Polio, AFP, Guinea Worm. Use all the fields of "other disease". No contact tracing

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] Define colors for the new diseases. (How much darker is ther darker one?)

**Comment by MateStrysewskeSym** [comment]
* Full names: Acute Flaccid Paralysis, Poliomyelitis, Guinea Worm
* Short names: AFP, Polio, Guinea Worm
* You may define the colours for the diseases yourself; just make sure that they're not extremely close to those already used (it's fine to have two or three shades of green, e.g., but they should differ); for the darker one, just pick a colour within the same colour scheme - you can use the existing colours as a guideline
* Simplified data entry mode is deactivated right now anyway, so no
* Because afaik that's the only classes where we use disease annotations in; if we're mistaken and there are more, the annotations of course also need to be added there

**Comment by MateStrysewskeSym** [comment]
- [ ] Disable contact tracing and set follow-up period to 0
