### ISSUE TITLE
Delete immunizations in reduced module when the last other entity related to the person is deleted [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#11786]
### Problem Description

When using the reduced immunization module, as soon as a vaccination is added to a person, that person will never be automatically deleted even if all cases, contacts, event participants and travel entries related to it have already been deleted because the immunization will always stay in the system (since users can't delete them).
 
### Proposed Change

Before permanently deleting persons, for servers using the reduced immunization module, delete all immunizations related to persons that are NOT related to any case, contact, event participant or travel entry.

### Added Value/Benefit

Without this change, permanent person deletion is not working on systems using the reduced immunization system.

### Acceptance Criteria

- [x] A method has been added to ImmunizationService that returns all immunizations related to persons that are not related to any case, contact, event participant or travel entry
- [x] The `deleteOprhanEntities` method in CoreEntityDeletionSerivce has been extended to delete all these immunizations as a batched operation; this needs to be done before deleting the persons
- [x] A unit test covers the new functionality and ensures that on a system with the reduced immunization module active, persons that are only related to immunizations and no other entity are properly deleted

### Implementation Details

Add the immunization deletion to the `CoreEntityDeletionService.deleteOrphanEntities` method.

**Comment by MateStrysewske** [comment]
The requested functionality has already been implemented. We need more details about the system where this happened on in order to decide how to proceed.

**Comment by sergiupacurariu** [comment]
@markusmann-vg @MartinWahnschaffe Additional to the above implementation details it has to be mentioned that the deletion of orphan immunizations will be triggered only when the feature configuration - IMMUNIZATION_MANAGEMENT is set to REDUCED = true. 
When the system is transitioned from FULL Immunization to REDUCED then ALL the immunizations and persons who are NOT related to any other case, contact, event participant, or travel entry but who could exist in the FULL configuration, after the transition will be permanently removed from database. Since the feature configuration change is done in the database the db admin will not be informed about these consequences.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.84.0-SNAPSHOT(b0860b4).
