### ISSUE TITLE
Rename "Pathogen test result" to "Final pathogen test result" and disable it when no results have been created

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1183]
As it stands, there are two places to enter lab results on the "samples" section of the SORMAS platform (Image A and Image B) ![Image A](https://user-images.githubusercontent.com/50739609/58872901-f3934780-86bc-11e9-9cb4-1dd742b8d6a1.PNG) and ![Image b](https://user-images.githubusercontent.com/50739609/58873006-32c19880-86bd-11e9-9e14-450d3e4ffe6e.PNG)
 
The appropriate area for result entry on the SORMAS platform should be image A but as it stands alot of lab users enter the results in image B as it is easier. The implication is that the results entered wont be reflected on the SORMAS platform and variables like "date of test results", "lab where result was tested" and "result verification by lab supervisor" wont be known.

Image B should therefore be removed or trasferred to another area on the platform other than the sample section of the platform if it plays a specific role on the platform @MartinWahnschaffeSymeda @Chinedar @MateStrysewskeSym @foyiri

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 The purpose "Pathogen Test Result" variable in Image B is to set the final result of this sample, i.e. whether it's a positive sample of this disease or not. As such, it's very important that we keep this because we don't have another way to determine this status. We can't simply say the sample is positive when there's a positive test, because there might be another one that is negative and deemed more appropriate than the positive one, or there might be tests to exclude other diseases that might turn out positive, which should not be reflected in this sample because it's for a different disease. I agree that it's misleading though, and we should probably rename the variable to better reflect what we use it for. Do you have a suggestion?

**Comment by Iheanacho2027** [comment]
The problem is that image b doesnt reflect on the SORMAS dashboard as we have observed. Secondly, the result ought to have a "date of testing", "lab of testing" and "result verification" which are all provided in image A. Image b can be moved somewhere else but not in the samples section of the platform as its causing alot of problems in terms of data quality

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 The field we're talking about does not represent a full-fledged test. It specifies what the final lab result of the sample is, i.e. whether it has ultimately been tested positive or negative for the disease in question. As such, it should not have the variables you specified because those belong to an actual test. That's why I said we should probably rename the field to make it more clear that it's not an equivalent to an actual pathogen test.

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym  The problem is that the users see it as an easier way to enter sample results and ignore Image A. Telling them to work with image A and ignore image B hasnt solved the problem, they still update image b with the sample results   (either negative or positive) as its easier to update results in image b. You can check image C to properly understand what i am trying to say or discuss more with @foyiri and @Chinedar to get further explanation
![Image C](https://user-images.githubusercontent.com/50739609/58875040-618e3d80-86c2-11e9-89a2-d9c07d2d18ce.PNG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 @Chinedar @foyiri I understand your problem. I still don't think we can get rid of the field (and putting it somewhere else doesn't make much sense semantically). My suggestion is to a) rename the field to clarify what its purpose is and b) disable it as long as no pathogen test has been created. That would make sure that they need to add at least one test before they can set this variable.

**Comment by Chinedar** [comment]
@MateStrysewskeSym I suggest we put a restriction to this field, preventing it from being the only field that can have a result (whether positive or negative). If users select an option while "new test result" hasn't been filled, then the constraint should come with a red flag and constraint message advising the user to proceed to entering the result details in the "new test result" section first. 
We can also change the name of this variable to "final pathogen test result".

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Thanks for your input! I think we have found a good solution for this issue. You can check the new logic after we've published the next release. Feedback on whether you're happy with it would be much appreciated.

**Comment by Iheanacho2027** [comment]
Alright. We await the next release. Thanks

**Comment by MateStrysewskeSym** [comment]
- [ ] Rename final pathogen test result to final laboratory result
- [ ] changing the pathogen test result from the popup results in an exception
