### ISSUE TITLE
'Unsaved changes' pop-up is triggered after discarding changes to place of stay

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11883]
### Bug Description

When updating the 'Place of stay' of  case and the discarding the changes from the 'Discard' button at the bottom of the page, if the user then tries to navigate to another page the 'Unsaved changes' pop-up gets triggered.

### Reproduction Steps

1. Open an existing case and change its 'Place of stay' (from home to hospital or hospital to home);
2. At the bottom of the case page, click on the 'Discard' button;
3. Afterwards, click on another tab of the case ('Case person');

Actual behavior: the 'Unsaved changes' pop-up appears.
 

### Expected Behavior

The 'Unsaved changes' pop-up should not appear as the user has already discarded the changes made.

### Affected Area(s)

Web app

### SORMAS Version

1.83.0, 1.82.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine, https://release-international.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
Closing this issue as it's a very unlikely niche case, i.e. it probably won't ever happen on a production server, and if it happens, it doesn't break anything, but is merely an inconvenience. Since we will move to a different UI technology at some point, fixing it before that happens doesn't seem to be worth the time needed to do so.
