### ISSUE TITLE
 auto epid numbering  in bulk action 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1211]
it good we have auto epid numbering system i notice that for cases already in the system you will need to click assign epid number which means you have to open cases one after the other to resolve this it will be good to do this in bulk action

**Comment by MartinWahnschaffeSymeda** [comment]
We discussed this today and guess that this is not needed:

All cases that are created or imported since we introduced the automatic epid-number will already have an epid number, so this would only be relevant for cases that have been created before the feature was introduced.

Do these old cases really need a complete epid number? If so one option could be to do this in the database.

**Comment by MartinWahnschaffeSymeda** [comment]
@foyiri Any comments or can we close this?
