### ISSUE TITLE
userRole=CONTACT_SUPERVISOR not working on web dashboard

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1234]
https://sormas.helmholtz-hzi.de/sormas-ui/#!users/?userRole=CONTACT_SUPERVISOR
Currently when you are only a contact supervisor and you log in you get an error message saying no view for this user @MartinWahnschaffeSymeda 
![image](https://user-images.githubusercontent.com/19344651/61766596-b0fb0b00-ade1-11e9-9307-31001790966e.png)
We should have the contact dashboard as the main view for this user.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig You get this error because you're trying to open the "Users" view which the Contact Supervisor right now has no access to. Please note that the URL does not change when you log out, so whoever you try to log in as afterwards will attempt to open the last page you visited before logging out. Logging in on /sormas-ui/ without any appendix will automatically redirect the Contact Supervisor to the Dashboard.
