### ISSUE TITLE
Export date format update

### ISSUE THREAD

**Issue by chukwuemekauzoho** [hzi-braunschweig/SORMAS-Project#1260]
There is an urgent need to update/change the date format used in the exported .csv files to this format - 29-Feb-2019 ie. having the month in letters.
@Chinedar @foyiri  @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@chukwuemekauzoho If this is about not really knowing which date format is used (and therefore needing the month abbreviation for clarification), we have added the specification of the date format to the respective column headers some time ago. Additionally, you can always change the format of single columns within Excel to provide you with the exact data format you need; since the current SORMAS export is a CSV export, we should keep the data as clean and generic as possible. Please default to the current possibilities for now - we might add something like this in the future when we do the dedicated Excel export mentioned in #1161
