### ISSUE TITLE
Add completeness to case directory

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1294]
On the case directory that shows you the percentage of completeness we will need to know or the should be a way to show which variable are missing in a particular case

**Comment by foyiri** [comment]
I notice that completeness only show when you  click the merge can this completeness show when you go to the case directory

**Comment by MateStrysewskeSym** [comment]
- [ ] Add completeness to case directory

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Define the fields/information that should be considered for calculating the completeness value

**Comment by bernardsilenou** [comment]
I wan to propose  that we program the completeness  to be generic, meaning the function takes as input a vector of character variables provided by the admin in properties file for example and return the completeness which is the percentage of theses variables that are not missing for the case. 
If we set the completeness to be based on some foxed set of variables, we will latter always get arguments when we meet people who do not agree with the set of variables because it some times depend on the disease also. e.g. Occupation might be importance for some diseases and not for some. The same with vaccination, contacts, etc

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] move `updateIsSymptomatic(symptoms);` to saveAndSnapshot in SymptomsDao

**Comment by MateStrysewskeSym** [comment]
- [ ] Change "complete" to "completed" in the mobile app
