### ISSUE TITLE
Infinite loading on duplicate detection in case import

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1300]

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 This is from issue #1148 - I can't reproduce this, neither on my local system, nor on the Nigerian server. Can you explain precisely what happens, i.e., when does this issue occur (during the first detected duplicate or later), how many cases were you trying to import at once, how many duplicates were detected?

**Comment by Iheanacho2027** [comment]
It occurs at the detection of the first duplicate. It occurs with the import of as few as 5 cases are

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Could you send me the smallest (i.e. the one with the least cases) you're using to m.strysewske@symeda.de so I can try to reproduce it with this exact data on my local system?

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I really can't seem to reproduce this, neither on my local development system, nor on the Nigerian system, which makes me agree that this could be a server problem. Can you observe this issue over the next two weeks and give me an update on the development? I've increased the available RAM on the server to 4 GB and I'm curious whether this will change anything.

**Comment by Iheanacho2027** [comment]
Alright that's fine

**Comment by Iheanacho2027** [comment]
This issue still exists

**Comment by MartinWahnschaffeSymeda** [comment]
It's likely that my changes in 2e7ae4f will have either fixed this or at least give us a clear error.

**Comment by Iheanacho2027** [comment]
We will try in 1.29.0 and give feedbacks

**Comment by Iheanacho2027** [comment]
As a follow up on 1.30.1, this issue still exists

**Comment by MartinWahnschaffeSymeda** [comment]
Still no idea what is causing this. I have refactored the code (#1374) and added a few debug log outputs. Hopefully this will help us to get closer to the problem source.

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 You mentioned that it's still not working. Can you give me a timestamp of an import that ran into infinity? This will allow me to have a look at the logs.

**Comment by Iheanacho2027** [comment]
Pls check the logs on 19th January 2020, and 25th January 2020 around 1 - 2pm Nigerian time

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 For 25th I found an import that was started at system time 17:28:24 and ended 18:06:58 with 1703 rows. Could this be what you are referring to? From the log it looks like the import worked. 

1. Is 1703 cases correct?
2. At what point did the UI element stop to update itself?
3. Were the cases that you wanted to import really not in the system afterwards?

What I can definitely say is that 1 second per case (the current average) is too long for the import - so that's definitely something that needs to be improved?

**Comment by Iheanacho2027** [comment]
So what happens is, whenever this problem occurs we turn off the internet connection for the infinite loading to stop, then we make a decision on the action to take as regards the case about to be imported before turning back on the internet connection. Turning off the internet connection for the infinite loading to stop is an inconvenient step as this takes alot of time. You can check this current time 30th January (9:31pm nigerian time), i am currently importing a case, and it has been loading for more than 5 mins since the detection of an existing case similar to a case about to be imported

**Comment by MartinWahnschaffeSymeda** [comment]
Findings: It takes very long to import 1000 cases (approx 20 minutes). My guess is that this causes problems with the request handling done by vaadin. 

Long-term this will be solved by replacing Vaadin with another UI framework. For now we should do two things:

1. We need to improve the import speed -> #1504 
2. Let users know about this "constraint" and add a suggestion to split the import files and import max. 500 cases at a time.

**Comment by faatihi** [comment]
We also faced this issue last week. We're on version 1.36.2.
When importing cases, the system presents possible duplicates for user to decide and then continue with the import. The options are presented alright, but user has no way to select an option to proceed.
The loader animation (and its backdrop) is layered on top on the form, so the options are behind this backdrop. I understand if user is fast enough, he can pick an option before the loader appears.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I've turned your report into a separate issue: #1861

**Comment by Iheanacho2027** [comment]
Great, this has been resolved. I can testify @MateStrysewskeSym
