### ISSUE TITLE
Duplicates from different regions are not considered in duplicate detection [0.5]

### ISSUE THREAD

**Issue by Mabayoje** [hzi-braunschweig/SORMAS-Project#1307]
Some duplicates cases that appears in Case Directory don't appear in Merge Duplicate section, even after filtering with all variables.

**Comment by MateStrysewskeSym** [comment]
@Mabayoje Thank you for submitting this issue. Please, never upload anything here that has sensitive data in it. The image you provided had the name of a SORMAS case on it, which is why I removed it. I'll look into this and get back to you.

**Comment by MateStrysewskeSym** [comment]
@Mabayoje The two cases are not displayed in the Merge Duplicate section because their respective cases are in different regions/states. This is expected behaviour - showing potential duplicates without narrowing them down by region could result in a lot more false duplicates. We'll discuss whether to change this in our upcoming meeting, though.

**Comment by Mabayoje** [comment]
Noted with thanks.

**Comment by MateStrysewskeSym** [comment]
- [ ] Allow users to exclude region from the criteria used for searching for duplicates (only in duplicate case detection)
