### ISSUE TITLE
Dashboard amendments

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1318]
1- Display of statistics by different date types: On the surveillance dashboard and in other sections, we decided in the past that users can filter by choosing the date type that they want among most available date, onset date, report date and creation date. On the case directory, creation date only is lacking. On the dashboard is is not clear which date is used. We need to add these date filters with the option that one can choose multiple date types.

2- Reverting of date from "By epi week" to "By date" when filtering  on dashboard and case directory. The date filter always changes back to "By date", this might be a bug.

3. When the "Hide overview" box is checked on the dashboard, the "compared to" and the date cell that follows need to be hidden because this difference only make sense when we look at the overview not on a disease specific dashboard. This is not a big issue but might confuse users.

4. Generally,  I suggest that default date should be creation date for all tabs in SORMAS. Exception for the epi curve that should be onset date with a radio button for users to choose among other options to view the curve. This means users should be able to filter cases created in SORMAS in 2018 and few epidemic curve based on only onset data among the cases for example.

**Comment by MateStrysewskeSym** [comment]
The creation date is technical data that is not meant to be presented ot the user (apart from admins who know what it is about). I disagree that we should use it for anything that contains logic apart from the duplicate merging (because duplicate merging by itself is a very technical process). Also, creation date was never part of any date filters in the past - we prevoiusly had reception date in there, but this has been replaced with "date received at LGA" and we decided that it should not be taken into account for any calculations since its purpose is purely informatively.

The dashboard uses onset date first, then report date. This is explained in the popup that opens when you hover the information icon next to the date filters.

The bug you mentioned has been fixed in #1311.

The date filters on the dashboard still apply to the disease specific informations. They still need to be visible to the users when hiding the overview tiles.

I'll close this issue because I think that the way this currently is implemented is the right way. If you disagree on any point, we can discuss this again in our next sprint review.
