### ISSUE TITLE
Change contact, person and visit association [6+2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1329]
The current way contacts and visits are handled in the system is pretty complicated to understand for users and makes it impossible to link visits directly to contacts. We have found a potential solution for this problem:

Preferred solution

* Let contacts and visits have an n-to-n relation
* Automatically assign visits to all relevant contacts on creation
* Show a dialog when the visit is saved to let the user know that the visit is associated to multiple contacts

- [x] Consider migration 
- [x] Make sure that visits are only associated to contacts of the same person/disease and vice versa
- [x] Re-assign visits and contacts when the last contact date/report date/visit date are changed
- [x] Use visits as the leading entity, i.e. always work on the contact list on the visit

#####
to be reviewed by @MartinWahnschaffeSymeda @BarnaBartha 

----------- out of scope -------- DO NOT READ!

* Directly associate **one** contact with **one** person; if a person *has* a contact, it *is* a contact
* Add contact events for every contact to a case this person had; all these contact events are added to the contact
* Add visits directly to the **contact**, not the contact event; this way, visits only need to be added once and always appear in every relevant contact event
* The contact is merely a reference entity; all details that are currently part of the contact would be moved to contact events

While the old contact <-> person relation looked like this:

<pre>Person  1 .. n  Contact
   1
   ..
   n
 Visit</pre>

... the new relation would look like this:

<pre>Person  1 .. 1  Contact   1 .. n  Visit
                   1
                   ..
                   n
             Contact Event</pre>

Clarification:

* One person should have one contact association per incubation period and disease
* Contact events increase the incubation period
* All contact events of one contact share the same visits
~~

~~**Alternativelier**

* Let contacts and visits have an 1-to-n relation
* Duplicate visits for all relevant contacts~~

**Comment by MartinWahnschaffeSymeda** [comment]
This will also solve the problems of visits "disappearing" when the disease of a contact is changed (see #1599 and #1643).

**Comment by MateStrysewskeSym** [comment]
This is also necessary to provide a stable interface for PIA. The REST interface possibly has to be adjusted afterwards.

**Comment by markusmann-vg** [comment]
- [ ] Consider migration

**Comment by markusmann-vg** [comment]
Uncertainty: S
Size: M
Risk / Impact: L
Complexity: M

**Comment by MateStrysewskeSym** [comment]
- [ ] Follow-up until date also needs to be considered for calling updateContactVisitAssociation

**Comment by bernardsilenou** [comment]
Visits are copied to all contacts that the contact person is associated to. This is fine.

The user doing the visit is not informed that the visit are copied to other contacts.  This is a nice to have but not important, the important point I found that is missing is the fact that on the visits table, we can not tell who did which visit. 

 It will be good to have the user who did the visit as a column in the visit table so that the responsible contact officer is not confused when they see a new visit on their tablet.

![image](https://user-images.githubusercontent.com/12996724/87339152-7a645600-c546-11ea-93c6-f11a2f0d52ef.png)

Or we can add any indicator for the users to know visits are carried over from one contact to another. Maybe even send a task to inform the SO?

@MateStrysewskeSym i have reopened because i was doubting id this should be  a new issue

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Don't reopen closed issues, please. If you have change requests for already completed issues, open a new one. This issue was closed two months ago.
