### ISSUE TITLE
Generation of case tasks offline on the mobile app

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1353]
Currently on the mobile app of the SORMAS platform, case tasks are generated or created after the user synchronizes  with the SORMAS server. Since the purpose of the SORMAS mobile app is for offline entry, creation or generation of case tasks should be offline immediately a case is created by a user

**Comment by MartinWahnschaffeSymeda** [comment]
Generating tasks in the mobile app is something we shouldn't do because we need all the information that is available to the backend. However, we could introduce custom notifications that remind officers that they still have to do investigation for X cases. Also, this could be incorporated in the mobile dashboards that we have to create in the near future (see #88)
