### ISSUE TITLE
Menu selection in Android app strange behaviour [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1358]
1. Opened a Rhabies case. Go to epi data. Switch to edit mode. Saved. -> View switched to tasks
2. Open any case. Go to tasks. Switch to edit mode. -> Plus button is not working

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou @hzi-braunschweig These bugs are associated with a very, very complex system that builds the page menus. The problem is that this system was built in a completely inflexible way that doesn't support removing some of these entries on the fly (which we need though, e.g. to hide the contacts tab for cases that don't support follow-up). We've already had this problem in the past and found ways around it, but the current issues made us realise that we need to properly rebuild this logic.

For now, in order to not run into these problems, users who want to edit stuff in the mobile app should simply click on the "Edit" button as soon as they enter a case (i.e. in the Case Information section).

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym 
Danke Maté, It is well noted

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] define how to change the architecture of the menu selection

**Comment by MateStrysewskeSym** [comment]
Follow-up issue: #1417
