### ISSUE TITLE
Deletion of cases does not delete cases in DB and on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1375]
We had 15 tablets used during training and  deleted the cases at the end of the day. The following issues were noted:
1. Cases were not deleted from the database but were deleted from the web view. I exported the whole DB and found the cases. This is not what we wanted because the server is a life server. 
2. Cases were not deleted on the mobile tablet, and when the tablets were turned on the next day, some of the cases were resubmitted to the server as created the next. This only happens to some of the tablets.
3. When the cash of the tablets were cleared, the cases disappeard on the tablet, but still remain in the database and web app
4. When the account of a user is changed, the cases form the old user were carried over and displayed on the view of the new user. Changing the user on a tablet should clear the data and cash  on the mobile DB automatically. 
5. Cases having synchronization conflict at before they were deleted from the web are not deleted on the app and are resubmitted to the server at a latter time. Cases should be deleted from mobile app no matter their status in relation to the server
6. When the cash and data is cleared on the mobile app, the user is suppose to change the URL to ghsurveillance. This should not happen. I think there is an issue to have country specific apk files, this might solve this issue.
Recommendation:
When we delete on web app, all cases should be cleared from tables in the database, the server should request the mobile app and delete all data (Case, person, task, samples, etc) in the local DB and also in the cash memory that is related to the case. If the tablet is not online, it should save the case ID and do the same thing the next time that the tablet request from the server.

For now, we will deleted cases and clear data on mobile devices for the training. My issues is that the test cases are still in the production DB even though they are deleted from front end. Maybe there should be a backup DB for deleted cases? 
@MartinWahnschaffeSymeda We will train on Monday and Tuesday on the production server. We need all DB tables to be cleaned on Tuesday. How can we do this without resetting the server?

**Comment by MartinWahnschaffeSymeda** [comment]
Hi Bernard,

1. That is correct. The delete function does not delete data from the database. Instead it marks the cases as deleted in the database (see column "deleted")
2. The sync that removes those cases from the tablet is done once per day. When those cases are synced in the meantime it should not have an effect on the deletion of the case. Does this mean you now have two cases with the same UUID in the database?
3. The cache of the tablet should not affect the server database, so that's fine.
4. Sounds like we have to investigate on that. I have create a separate issue for this #1378 
5. That would indeed be the case once per day (see 2)
6. Why are users clearing data of the mobile device? Is this related to point 4? The server relation of the apk is an important issue, you are right. Having a country specific apk will cause a lot of manual work (see https://github.com/hzi-braunschweig/SORMAS-Project/blob/18acb883da2f1e00bcdd9f5ee0ad3bf184454783/DEMO_APP.md#step-2-sign-the-changed-apk-file). I guess it would be better to have no default server and let user's enter the server url in the login screen when the app is freshly installed (or has all data cleared).

We don't have a good solution for this scenario. Probably something that we need to solve for the future. For now we can create the SQL statement needed to truncate all the data. 
In the app users can go to the setting's and use the re-sync function.
Am I right that **ALL** cases need to be deleted tomorrow evening, while infrastructure, users and config is supposed to remain?

**Comment by bernardsilenou** [comment]
When server was restarted after all tables was cleared cases still remain on the tablet. This doesn't happen for all tablets.
We sync, re-sync, clear data and catch but this does not still clear the cases on the tablet. This is because the database
was declared while some of the tablets were not connected online. This then causes the cases to be submitted to server as new cases:
The right way to "hard deleted" cases on tablet and server is to:
1. Soft delete on server
2. Sync or re-sync tablets with server and make sure all cases disappear on tablet
3. Hard delete server cases
