### ISSUE TITLE
Request for mandatory entry of EPID number by mobile users

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1427]
National level stakeholders in Nigeria have requested three things

1) Entry of case Epid number should be made mandatory for Surveillance Officers. They shouldnt be allowed to proceed to the next stage without entering case EPID number in the correct syntax 

2) If an EPID number entered is a duplicate of another, a message should pop up telling them its a duplicate, and they should be mandated to resolve the duplicate before proceeding

3) Surveillance Officers should be alerted of EPID numbers assigned by other users to cases coming from their LGAs.

@Chinedar @hzi-braunschweig @bernardsilenou @foyiri

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 There's a problem with this approach. We don't have any way to make sure that an epid number entered by a surveillance officer is not a duplicate in the mobile app because the mobile app does not have the necessary information (and even if it had, it might be outdated in case the device has been offline for a while).

That means that, in case we force officers to enter an epid number, we might send a lot of duplicate numbers to the server. We could then automatically correct this on the server and send the updated information back to the mobile app, but that makes it pretty pointless to force the officer to enter an epid number in the first place because, if they enter none, the backend automatically assigns one anyway (this is already implemented).

**Comment by Chinedar** [comment]
Can we make the character length restricted to 18 digits? for example: (NIE-ZAS-GUS-20-001). By implication, they cannot add extra digits or remove at the serial number part. @MateStrysewskeSym @MartinWahnschaffeSymeda 
The folks who do data cleaning and quality checks always complain when they export into other statistical tools.

**Comment by bernardsilenou** [comment]
Since the number of digits differ from country to country, and also with in county, I recommend that we keep the epid number field as it is. For the export function, we retain only 3 digits. 
@Chinedar Is this ok by you?
In addition, the current number of digits does not matter when SORMAS  uses epid number in any comparison.

**Comment by MateStrysewskeSym** [comment]
@Chinedar What happens in an outbreak situation where there's more than 999 cases over the course of a year for a specific disease? I don't believe we can be sure that this won't be a possibility, right?
