### ISSUE TITLE
What does UNDEFINED  disease means?

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1449]
The list of diseases has 'undefined' and 'other' as categories.  My expectation is that both are the same. We have always been using ''Other" category for any unknown/ undefined disease. Any comment?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Please don't open GitHub issues for understanding problems, but write a mail instead. "Undefined" disease is meant to be used for cases where the creator does not have any idea about which disease the patient might have. This is especially meant to be used in point of entry cases because there might be no epidemiological information available about the patient. "Other" disease is meant to be used for diseases that are clearly defined, but not part of the system (yet).
