### ISSUE TITLE
A few issues from Ghana

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1475]
Hi, 

I've collected a few issues from users:

- [ ] 	'Other Epidemic Diseases' is not included in dashboard's slideshow

- [ ] 	Dashboard should also show the specific disease for 'other' diseases. 
Currently, it just says 'OTHER' but it would be more useful to see numbers for the particular disease.

- [ ] 	GHS requests an exact implementation of their dashboard design proposal. 
It's the first image on issue #835 . They want that for the non-technical staff.
I'm thinking we can make the components (on the dashboard) configurable. 
That way, Ghana may include the components it needs and, may be, place them where they want.

- [ ] 	Officers with restricted district or region are able to generate reports of places outside their jurisdiction

**Comment by bernardsilenou** [comment]
Hi,
Just few comments:
1. "Other Epidemic Diseases" is a variable that contain many different diseases that do not have a management and response module programmed in SORMAS, but the surveillance system still finds it important to notify them in SORMAS. We cannot show it on dashboard because dashboard is diseases specific. Stakeholders should specify the diseases that they need to see on dash board and we can add them as a disease in SORMAS.
2. The response to point 1 also holds here. Even though "other" contains many diseases, we cannot show those diseases on dashboard because the names of the diseases are not an entity that has been defined in the database. However, in the case directory, all details are displayed. One user can create  a disease under "Other epidemic diseases" and call it AFP, another Polio, another Accute flacid paralysis. These are all the same thing but the system can't know in advance the text that the users will write in order to count the cases.
3. We design the current dashboard by merging the request from GHS #835 and the old SORMAS dashboard. We will need a have a design thinking meeting with the GHS to clearly define the needs before moving on this path.
4. Does this mean SOs can create cases outside their districts? If yes then it is a clear proof that the users are wrongly logged in the system. This is not a SORMAS problem. The user accounts should be critically checked especially the new districts.

**Comment by MateStrysewskeSym** [comment]
@faatihi I totally agree with Bernard on points 1 and 2.

Concerning point 3, we will discuss this in our next review.

Concerning 4, could you please specify what exactly you mean by "reports of places outside their jurisdiction"?

**Comment by faatihi** [comment]
Hi,

Here's a quote from GHS concerning my fourth point:

The Statistics, all users at various levels (Regional, District) can generate a statistics of all the data on the system. We want the users to generate statistics on data concerning their jurisdiction only.

**Comment by faatihi** [comment]
And on points 1 and 2, we tried out a Corona Virus scenario, which isn't in the system yet.

We thought if Ghana wanted to keep an eye on this disease (a new disease, for that matter), it would be difficult because its classified under 'Other Diseases'.

Maybe we can have a way for the Admin to quickly add a disease from the UI (or developers add it in the DB) so that it can be specifically monitored on the dashboard. This way, we don't have to wait for a new release of SORMAS to get the new disease.

**Comment by MateStrysewskeSym** [comment]
@faatihi The statistics are specifically desigend to include all data from the system. It's possible to add a filter to restrict the data to specific regions or districts though - isn't that exactly what you need?

On points 1 and 2, the (currently) desired process for a scenario like this would be that "Other disease" is temporarily used as a fallback while the new disease is built into the core system asap. As "Other disease" will not only be used for the disease in question, but for other diseases as well that aren't part of the SORMAS system, any statistics on the dashboard won't be reliable anyway (since the case counts will not only involve one single disease).

Adding a module to manually create diseases from within the UI is a really complicated feature that we might add in the future, but is currently out of scope.

**Comment by faatihi** [comment]
@MateStrysewskeSym We're aware that creating a disease is complicated. We could, however, think of a way to only add a new disease by the name. The system can set defaults for a newly added disease. When that disease is finally coded in the system, that will then override the defaults for the disease. That way, countries do not have to pack numerous diseases into the 'Others'. 
With this strategy, officers will directly select the newly added and specific disease when they're recording a case. They wouldn't have to type the name of the disease (which is the source of different naming of the same disease).

> but for other diseases as well that aren't part of the SORMAS system, any statistics on the dashboard won't be reliable anyway (since the case counts will not only involve one single disease).

This is why we can't use 'Other disease' to monitor a new disease.

**Comment by MateStrysewskeSym** [comment]
@faatihi Good point. We'll definitely discuss this possibility!

**Comment by faatihi** [comment]
Additional concerns:

- [ ] We need a userrole that can create users but can't create an admin user.
	GCNet is handing over the creation of users to GHS, but we do not want
	them creating admin users. If there's a way to have another Admin user who cannot create an admin user, that would be great.

- [ ] We need an audit trail module. One should be able to pick a user and see all activities the user has done on SORMAS.

- [ ] There's this Samsung Android tablet running on Android 5.1.1. We updated its SORMAS app from version 1.18.0 to 1.32.0 and the app keeps crashing when you run it. We downgraded to SORMAS 1.25.0 and same issue. Is it that SORMAS isn't compatible with that android version?

**Comment by MateStrysewskeSym** [comment]
@faatihi There is an audit database you can use to extract exactly this kind of information. For now, there's no UI to retrieve it. Concerning the crashes, we'll have a look into it. The minimum supported Android version is 5.0, so that's definitely not the root of the issue.

**Comment by MateStrysewskeSym** [comment]
@faatihi Concerning your first additional concern: We're currently about to significantly change the user role/user right system and make it fully configurable from the UI. There will be no fixed user roles in the system anymore after the change. I suggest we discuss this again once these changes are implemented and see whether it's still needed and, if yes, how we can proceed.

**Comment by MateStrysewskeSym** [comment]
@faatihi When exactly does the crash happen? Immediately when SORMAS is opened or after the user has entered their PIN?

**Comment by faatihi** [comment]
> @faatihi Concerning your first additional concern: We're currently about to significantly change the user role/user right system and make it fully configurable from the UI. There will be no fixed user roles in the system anymore after the change. I suggest we discuss this again once these changes are implemented and see whether it's still needed and, if yes, how we can proceed.

Aha. That's exactly what I was thinking. An overhaul of the user-role system. Though I didn't think that idea would be accepted (at least in the short term). But I'm glad we have that in the roadmap.

This issue will still be a special one because, its not about denying a user the access to the 'Create User' access right. Its about denying him of 'Creating an admin user'. One way to approach this is to have a user-right specifically for creating admin user. If that is included, we'll be fine.

**Comment by faatihi** [comment]
> @faatihi When exactly does the crash happen? Immediately when SORMAS is opened or after the user has entered their PIN?

Immediately when SORMAS is opened. The crash happens even before you could see the app on the screen.

**Comment by MateStrysewskeSym** [comment]
@faatihi It's probably a good idea to have an "Admin" user role that can't be deleted anyway, so I see the reasoning behind this. I'll add a hint to #898.

I don't really have any idea what could cause this... Could you just remove the app from the device and re-install it with the newest version?

**Comment by faatihi** [comment]
Yeah, we did that several times

**Comment by faatihi** [comment]
> Concerning point 3, we will discuss this in our next review.

@MateStrysewskeSym may I know the outcome and how far we've gone with the point 3 (dashboard).
The dashboard redesign is currently Ghana's top priority.
I opened a dedicated issue #1507 for it.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi I have replied now in #1507
