### ISSUE TITLE
General comments after testing version 1.32

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1491]
Here are some minor comments:
       Web app
1.	on the dashboard, we should replace "cov" with "CoV"
2.	 I (admin) created a case and investigation task is assigned to me while there is an SO and SS in the district that the case comes from. We should always assign the investigation task with respect to the district of origin of the case. First the SO, if not present, then the SS. If there are many SOs, we randomly choose one.
3.	We should have a full drop down for variables that have many choices like occupation, such that users do not have to scroll down to choose the best option. The partial display prevent users to see all options provided.
4.	Giving the DOB of a case, the age was automatically computed, but when latter deleted the DOB, the age is retained and saved. This is prone to errors. In addition, DOB does not starts with 1980 as in the app but with 1900. 
5.	Under clinical signs and symptoms: date of symptom onset should be on the right and first symptom on the left side of the screen. This is because we write from left to right.
Date of symptom onset and first symptom should be below the list of all symptoms. This is because they are to be filled after all symptoms are filled already.
6.	During creating a visit for a contact person, under "Clinical measurement", symptoms and complications should not show up when the person is unavailable. If the visit information is created before setting availability to be “unavailable”, SORMAS should not allow the user to safe the data.
7.	When creating a case as SO, religion and district prefilled and can’t be edited but when an old case is edited, the SO can edit the region and district of the case. I think SO should not be able to change the district and region of the case since they always notify cases in their region. OR are we allowing SO to notify cases in any part of the country?
8.	For a visit to a contact person, date and time of visit is prefilled using the current date and time. This is prone to errors because we assumed that the user is doing the visit in real time. We should not prefill this but allow the use to choose the date and time.
        Mobile app
9.	When the outcome is chosen as unknown, the date of outcome should not appear. 
10.	Hide “environmental exposure “caption under epidemiological info because it stand alone for CoV disease.
11.	The similarity measure to identify similar contact persons is very week. For example, the suggested similar persons for "contact bakala" are "contact Omar" and "contact person". This can lead to false match as there are many people with the same first name in a country. We should define a similarity measure considering:  first name, last name, sex, and if possible DOB.
12.	Date and time of visit is prefilled using the current date and time. This prone to errors because we assumed that the user is doing the visit in real time. We should not prefill this but allow the use to choose the date and time.
13.	When registering a visit, symptoms, clinical measures and complications are not available for CoV.
14.	Bug in assignment of automatic case investigation tasks. An SO in a district creates a case and the investigation task is assigned to the clinician in the same region. We need to review the logic in all task assignments.

**Comment by MateStrysewskeSym** [comment]
A few comments from my side - let's discuss this in detail during our next sprint review:

1.) The caption indeed is CoV, but the dashboard uses capslock most of the time, so it's actually COV, not cov.
7.) SOs need to be able to move cases to other regions and districts in case they were transfered to another health facility; that's why they can't create cases outside their district, but edit the infrastructure details of existing cases.
8.) This is a convenience feature because we figured that visits probably won't be entered retrospectively; we probably should ask Chinedu about this in the review.
11.) Try increasing the namesimilaritythreshold in the sormas.properties file on the server to a higher number; anyway, we need to discuss this mechanism and whether it still makes sense (maybe it's also time to start talking about re-structuring the whole contact logic).
13.) Works for me. You have to create the visit first, afterwards you're redirected to the created visit and can switch to the "Symptom Information" tab as usual.

**Comment by foyiri** [comment]
From my own end I think most of the issues have been raised am more concerned with the map part of the platform we can we start working different shape file for state,LGA and ward this will really add more value to sormas
