### ISSUE TITLE
Change type of contacts

### ISSUE THREAD

**Issue by chukwuemekauzoho** [hzi-braunschweig/SORMAS-Project#1503]
@Chinedar @bernardsilenou @danieltomaba @MartinWahnschaffeSymeda The Lassa fever TWG has asked that for VHFs, type of contact be classified into 3 broad categories instead of the current way on the platform

Category 1: **No-risk contacts** 
Description- No direct contact with the patient or body fluids. • Casual contact, e.g., sharing a room with the patient, without direct contact with body fluids or other potentially infectious material. • Handling of laboratory specimens under contained conditions

Category 2: **Low-risk contacts** 
Description - • Direct contact with the patient, e.g., routine medical/nursing care, OR • Handling body fluids wearing appropriate personal protective equipment, OR • Breach of laboratory containment without direct contact with specimen

Category 3 - **High-risk contacts** 
Description- • Unprotected exposure of broken skin or mucous membranes to potentially infectious blood or body fluids and secretions (including splash injury) clothing and bedding on confirmed case. • This includes: unprotected handling of clinical/laboratory specimens; mucosal exposure to splashes; penetration of skin by contaminated sharp instrument e.g. needle-stick injury and kissing and/or sexual contact; breastfeeding. • HCWs involved in emergency/exposure prone procedures i.e. surgery/CPR/ intubation /suctioning on confirmed cases and without use of appropriate PPE. • Prolonged (i.e. for hours) and continuous contact in an enclosed space without use of appropriate PPE • Infant of a RT-PCR Lassa virus-positive mother.
[Contact categorisation.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/4165464/Contact.categorisation.pdf)

**Comment by bernardsilenou** [comment]
Hi Emeka,

Can you respond to issue #1506. which export do not have the pregnancy variable?


________________________________

**Comment by MateStrysewskeSym** [comment]
We could add an additional variable (e.g. called "Type of Contact Risk") that is only visible for Lassa. HZI will further discuss this.

**Comment by bernardsilenou** [comment]
@chukwuemekauzoho 
We had a loot at the categories and realized that they are related to the default SORMAS contact types. Since the categories in SORMAS  were programmed based on WHO, CDC and NCDC guidelines  in 2015, we will need to review the current WHO and CDC guidelines before the contact categories.
Here are the relationships that you can use fro now
1. No risk contact corresponds to 4 and 5 in SORMAS
2. Low risk contact corresponds to 2
3. High risk corresponds to 1
I recommend that after exporting the data, you can use these classifications to get the new varibles.

**Comment by MartinWahnschaffeSymeda** [comment]
Also see #1635
