### ISSUE TITLE
Remove default country data and write import guide [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1522]
- [x] Remove the default infrastructure .csv files from the backend
- [x] Extend StartupShutdownService to create dummy infrastructure data for the default users
- [x] Review the current infrastructure import guide and extend it if necessary
- [x] Add a short guide to GitHub

**Comment by MartinWahnschaffeSymeda** [comment]
Review notes

- [ ] Looks like the default infrastructure would now be created again and again whenever the server ist started. This should only be done when no region/district/etc exists.
- [ ] Make sure that the default sormas.properties has no country name set, uses "en" as language and some default for the EPID code. Same for the default valzes in ConfigFacadeEjb
- [ ] GeoShapeProviderEjb.loadData() currently throws an exception when no shape files are found. The should be a change to a log info instead. In the long-term the shape import will also be done from the UI

**Comment by MartinWahnschaffeSymeda** [comment]
Review notes:

- [ ] don't log in ConfigFacadeEjb.getCountryName/getEpidPrefix -> this would generate a lot of spam, because getEpidPrefix is called a lot. I think we don't need to log this at all
- [ ] maybe rename buildNecessaryInfrastructureData to createDefaultInfrastructureData (so it matches createDefaultUsers)

When this is done you can merge the branch into development

**Comment by MartinWahnschaffeSymeda** [comment]
@ChristopherRiedelSymeda  Review notes:

- [ ] don't log in ConfigFacadeEjb.getCountryName/getEpidPrefix -> this would generate a lot of spam, because getEpidPrefix is called a lot. I think we don't need to log this at all
- [ ] maybe rename buildNecessaryInfrastructureData to createDefaultInfrastructureData (so it matches createDefaultUsers)

When this is done you can merge the branch into development
