### ISSUE TITLE
User role for a national and state level contact officer

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1549]
### Feature Description
Can we have a user role for a national and state level contact officer? We are at the point where we need to deploy surge capacity contact officers who are not necessarily tied to an LGA or even to a state. These surge teams are moving out of the national response team and we need to set them up to do contact tracing for as many cases of corona as can come up in the country.

**Comment by Iheanacho2027** [comment]
Alternatively, we could grant the contact supervisor user account access to the mobile app, since the contact supervisor can be considered to be a state-level contact officer

**Comment by bernardsilenou** [comment]
@Iheanacho2027 The contact supervisors can always use a mobile device but  using a browser. Building a mobile version of the contact supervisor is a huge task and I don not think it can be done on a short notice.
@Chinedar 
- Please describe and write down the rights of this user role so that we can discuss it in details in the next sprint.  However, the current SORMAS users are always attached to an infrastructure data that can be a region, district or HF, but what you are asking is like a user who is not attached to any of this. 
- You asked for a user role for "state level contact officer", Is this not already the contact supervisor in the state?
- In addition, a contact officer can follow up on a contact person that are not in their LGA. The contact supervisor of the state just need to assign the contact person to the respective contact officer.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar From my understanding this goes back to what we discussed yesterday and should be resolved by #1561 and #1562, right?

**Comment by Chinedar** [comment]
Yes please @Martin Wahnschaffe <m.wahnschaffe@symeda.de> Thanks.
