### ISSUE TITLE
Validation between temperature and fever is deactivated

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1588]
### Bug Description
In the earlier versions, when the temperature  is more than 38, then fever should be yes and vice versa when documenting symptoms of the case. This does not work now.  
### Steps to Reproduce
1. Log on symeda play server and try if out, set temperature of a COV case to 40 and save.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/76452342-4a0e7e80-63d1-11ea-8421-62e5162e190e.png)

### System Details
* Device: web
* SORMAS version: 1.35
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
From what I can tell, this was always supposed to work only for visits, because the symptoms within a case are a collection of all symptoms that have ever been present throughout the whole case period, while fever is the highest temperature that has been measured in this time period.

So, no changes here, it works as intended.
