### ISSUE TITLE
Prevent users from editing cases and contacts outside their jurisdiction [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1591]
### Situation Description
Users are able to see data outside their jurisdiction, e.g. the case of a contact that has been assigned to their jurisdiction. This data should not be editable for them.

### Feature Description
Make forms read-only when their data is not in the jurisdiction of the current user. However, it should still be possible to create contacts for read-only cases.

- [ ] add backend method to check whether the user can edit the case or contact
- [ ] make forms readonly in user interface
- [ ] enforce this when saving a case or contact and the associated person

### Review
@MartinWahnschaffeSymeda

**Comment by sergiupacurariu** [comment]
an issue has been found to the following check: the user who created the case is not recognized. Current behavior : if the user from jurisdiction 1 creates a case with a jurisdiction 2 after save it will not be able to access it
Correct behavior: the user who created the case should be able to edit it no matter what jurisdiction comes from. 
The issue is present only for cases. The contact edit check works well.
