### ISSUE TITLE
Sever URL dropdown will make it more easier when setting up same way we have the languge 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1611]
looking at the way the language dropdown appears in the sever setting it will also help and make it easier if we have a dropdown for both servers

**Comment by MateStrysewskeSym** [comment]
@foyiri There already are quite a few and many potential SORMAS servers in a significant number of countries. Providing a list of those is a) not necessarily possible because we might not even know about all existing servers and b) it doesn't make much sense for users from e.g. Nigeria to see other places where SORMAS might be used. Additionally, this would make it impossible to connect to development environments.

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym the importance of this ticket is borne from the difficulties users experience when trying to enter the  server url for either the practice or test server accurately. Your point is also very valid, what we can do is, we can have two navigation points.

1) Users should select their country of operation or choice in a dropdown containing all countries where SORMAS is present

2) After making selection from number 1, then the server URLs available to their country should be displayed for them to choose in another handle below the handle for selecting their country of choice or operation

I think this ticket should be reopened and considered @MartinWahnschaffeSymeda @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 1) is still not possible because we might not be aware of every country that SORMAS is being used in. It's an open source software, so technically we don't need to ever get to know about it.

2) also means that countries who want to use SORMAS are **required** to give us a list of servers that they use. That is not something we can do.
