### ISSUE TITLE
Limit contact duplicate detection to only contacts within the source case

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1624]
-->
### Feature Description
Currently when a contact is created, the system brings out all similar contacts within the system database. When a contact is created, only similar existing contacts within the source case contacts should be presented as a similar existing contact @bernardsilenou

**Comment by bernardsilenou** [comment]
@Iheanacho2027 As you already know, when creating a case, the system checks for duplicate cases. BUT when creating a contact, the system checks for duplicate contact persons in the whole database. The system does not limit the search to contact persons of the source case alone because It is usually the case that a person can be a contact to two cases. If there are many suggested persons when creating a contact, then one solution to this will be to make the similarity measure for the duplicate person identification to be more sensitive. Can you explain the maximum number of contact persons you got when creating a contact?

**Comment by Iheanacho2027** [comment]
This becomes a huge issue due to the presence of #1300 which still exists during import. Import becomes very slow and quite frustrating

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 As Bernard explained, we never search for duplicate contacts on contact creation, only for persons with a similar name. If that list is too long, which I could definitely understand, please open a new issue specifically for narrowing down that list (e.g. we could add more person details to the contact creation form, like sex and age, and use that to shorten the list of potential existing persons).

**Comment by Iheanacho2027** [comment]
I think we have to have a further discussion on phone, as to why an individual can be a contact of two cases and the search should be limited to only contacts of that case @bernardsilenou
