### ISSUE TITLE
Event participants should have follow up information

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1631]
### Situation Description
This is due to the State Quarantine being done in Ghana now for all travelers who arrive in the country. They are neither cases nor contacts to cases, but they are being quarantined and monitored for 14 days. The monitoring involves checking their temperature and signs and
symptoms everyday for 14 days until they become a case of are discharged from
quarantine.

### Feature Description
Event participants should have follow up information

### Possible Alternatives
For now, we've asked them to create cases for each of the event persons and leave those
cases as "Not yet classified", while we work on this request.

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba @bernardsilenou Guess this is also relevant for other countries. How do they deal with it?
Will the option to create a contact without the need to assign a case be a solution? (see #1599)

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda They ar actually event participants and once they are created as persons within the event situation, we should be able to note if they are on quarantine for a specific period based on the disease and also follow them up. it is better to keep that separate from the contact entity we currently have. ONce the event participants become symptomatic, we already have the function to create a case for the event person and also be able to link him up with the source case who was the reason for being an event participant in the first place (E,g. flew on the same plane)

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda: I am  not a fan of the option of cerating contact without a case. The definitiion of a contact in the first place means there is a case existing which we know  and either have the cease information now or we do not have and might have latter if we search further. Even if we allow the possibility to create a contact without a case, we should have the necessary data or information available to later link all these contacts to their respective cases even if they are in different regions.
@danieltomaba: If the  goal is to follow up on persons and latter convert them to a case, then we should use the case contact module rather than event. However the feature to record follow up data for event is nice to have in SORMAS. My recommendation is: If there is an "event" with at least one case known, e,g, flight with one person as a case, then we should create the other persons as  contact to the case. and follow up on then based on the contact proximity.

**Comment by hzi-old** [comment]
@bernardsilenou It is not everytime that there exists an existing case to add contacts to. Sometimes you want to follow up people who are coming from a high risk zone while they are being quarantined at home. In this case, they are not contacts to anyone. This is a current problem with Nigeria COVID-19 response. They are following up people who came from China or UK or US to be self-quaratined at home. That is an event. Passengers who flew on Flight 376 from China will be followed up within the incubation period until someone becomes ill. Create event persons in an event and then when an event person becomes ill, then you create a case for that person and then find who he was a contact to and link his source case.

**Comment by bernardsilenou** [comment]
@danieltomaba Now I understand you better. The implementation is prioritized for the current sprint.
Here are the 3 main features:
1. Import module for events persons
2. follow up of event persons
2. Converting an event person to a case

**Comment by MateStrysewskeSym** [comment]
@hzi-old We're about to implement a feature that allows creating contacts without assigning a case to them. Wouldn't this be more fitting for your scenario than, in a way, abusing events and event persons to do follow-up?

**Comment by hzi-old** [comment]
@MateStrysewskeSym Ok that should work for passengers on flights without a case. Please I ask for one favor. Kindly include the edit on the bulk function for events. Right now its just delete option under bulk mode. This could help to migrate existing event participants as contacts of a case when they finally have one passenger who becomes ill and becomes a source case

**Comment by MateStrysewskeSym** [comment]
@hzi-old Please open a new issue for this because it doesn't really belong to this issue. Also, please explain in a bit more detail what that edit functionality should do.

**Comment by bernardsilenou** [comment]
With the possibility to now create contacts without necessariry linking them to a case or by linking them to an exposure ( e,g travel to high risk areas), do we still need this feature? I think not needed for now. We just need to create the travelers as contacts without a case and follow them up

**Comment by bernardsilenou** [comment]
What have we finally decoded  with this issue?
I got a request about this issue today. My previous comment on creating contact without a case and following up on them might not be the best in all situations because there will be no indicator to link these contacts to the same "event".
@MateStrysewskeSym Is there a possibility currently an option to create contacts without a case and have an indicator to link them to a common exposure (eg event)?
I think we need the feature to followup on events participants just as we do for contacts.
@faatihi have you started any implementation in this direction?
I will write more about this after talking with the German users

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Not possible right now, no.

**Comment by faatihi** [comment]
@bernardsilenou we haven't started any implementation on this issue. It is, however, dearly needed (apparently, not only in Ghana)

**Comment by bernardsilenou** [comment]
@faatihi Do you have resources to work on this now? 
We have not specified it completely. If you want to work on it them we can specify the module in details.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou How does this relate to #2200? From my understanding we could create a contact without a case and then link it to the event.
This would be a bit complicated thought, since it would not be possible to go throught the list of event participants and see there status.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda I agree with you. It will not be possible to go through the list of eent paersons and see the ir contact status.

What we need may be to link contacts ids (not contact person) to an event, just as we do when we convert an event person to a case, add the event id on the contact table and add the contact person among list of event participants. 

Using the contact id, we should ea  bale to filter the event persons but will not be able to see their contact classification as you said since these persons can be linked to many contacts

**Comment by faatihi** [comment]
@bernardsilenou @MartinWahnschaffeSymeda Creating a contact from an event participant is done when said participant becomes a contact to a case.

What we're looking at here is tracking some vitals of event participants. They're just participants of an event, and not a contact. #2200 is for when a participant becomes a contact.

**Comment by faatihi** [comment]
I spoke with @bernardsilenou on the phone, and below is what we're looking at:

1. Sometimes, an event of high risk is captured. Participants are quarantined (for about two weeks, depending on the situation and disease). These persons are regularly checked for temperature and other vital signs during the quarantine period.

2. Follow-up module should be extended to event module to enable users undertake above exercise.

3. Not all events require follow-up. Users should therefore be able to turn on follow-up. Follow-up can be off by default.

4. Include phone number and location of participant on initial EventParticipant form so they can easily be captured.

**Comment by bernardsilenou** [comment]
@faatihi I thought you were to implement this issue, any update?

**Comment by faatihi** [comment]
Yes, I have it in my to-do.
I'll target it for v1.48

**Comment by bernardsilenou** [comment]
perfect, thanks

**Comment by bernardsilenou** [comment]
@faatihi 
- If possible, we should have the option to choose the specific event participant to activate followup
- followup until date = date of event or last date of event if multiple + incubation period
- Just as contacts, followup to one event participant should be copied to all other event participants linking the same person and have followup up status as under followup

**Comment by faatihi** [comment]
Noted

**Comment by bernardsilenou** [comment]
@faatihi I hope this initial target is still possible? If not please, let us know by tomorrow

**Comment by faatihi** [comment]
Hello, @bernardsilenou 
I'm finding it difficult to make progress on this issue
I'll need to put this aside and attend to other requests

I hope somebody else can handle it within reasonable time frame

**Comment by bernardsilenou** [comment]
@faatihi  no prob, thanks

**Comment by Candice-Louw** [comment]
For: hzi-braunschweig/SORMAS-Switzerland#5

**Further specifications:**

Event Participant follow-up visits should have the same follow-up mask/questionnaire as for Contact follow-up visits and Case follow-up visits.

This means that when an Event Participant is opened and "follow-up visit" is selected, the same form content that appears for Contact follow-up visits and Case follow-up visits should appear for the Event Participant follow-up visit.

All follow-up masks/questionnaires at Cases, Contacts and Event Participants should thus be identical.

**Comment by bernardsilenou** [comment]
@Candice-Louw Perfect!
We need to add all mockups after the meeting tomorrow

**Comment by markusmann-vg** [comment]
closed because there is a refinement on #3003
