### ISSUE TITLE
Extend the facility types [5+3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1637]
### Feature Description
We need to allow users to import lists of:

* General practitioners
* Treatment centers
* Elderly care facilities

The best approach is probably to add these as facility types and then decide for individual facility fields which types of facilities should be added to the dropdown. Also, we probably have to think about changing the captions of these fields.

In addition, general practitioners probably need information like address and phone number, so we might need to add these as fields to facilities.

Before upload a selection of type is mandatory
- [x] Update facility types for old facilities in the db
- [x] In places where a health facility is selected, the system first asks for the type of facility and then displays a list of facilities of that type. This list shall also contain the option "Other facility". If this is selected, the "Additional Details" will also be displayed.
- [x] Consider the facility type during import
- [x] hospitalization should only be changed if transfer is related to hospital

### Review 
@MateStrysewskeSym

**Comment by max-hzi** [comment]
I received a couple of requests for a directory for GPs/ doctors offices. By having a directory, are no longer required to type in address and other info every time. One request was to have these doctors offices separate from bigger health facilities like hospitals.

**Comment by markusmann-vg** [comment]
Facility types:
Arztpraxen
Labore
Krankenhäuser
Betreuungseinrichtungen: Altenheim, Obdachlosenunterkunft, 
Einrichtungen zur gemeinschaftlichen Unterbringung von Asylbewerbern, vollziehbar Ausreisepflichtigen, Flüchtlingen und Spätaussiedlern; sonstige Massenunterkünfte, Justizvollzugsanstalten, ambulante Pflegedienste) 
Gemeinschaftseinrichtungen: Kindertagesstätte, -Horte, Kindertagespflege, Schulen und sonstige Ausbildungseinrichtungen, Heime, Ferienlager)

**Comment by bernardsilenou** [comment]
@markusmann-vg  The list you provided has mixture of health facilities, lab and other facilities is in the current  system. 
In issues #2340 #2211, # 2093 we have the variable typeofplace which will contain a similar list including facilities that are not health facilities. We need to maybe consider implementing one methods to handle both issues. Don't know how it sounds to you

**Comment by ChristopherRiedelSymeda** [comment]
Facility types:
GENERAL_PRACTITIONERS_OFFICE
LABORATORY (was ther before)
HOSPITAL
ELDERLY_CARE_FACILITY
HOMELESS_SHELTER
REFUGEE_HOSTEL
OTHER_COLLECTIVE_ACCOMMODATION
CORRECTIONAL_FACILITY
MOBILE_NURSING_SERVICE

AFTERSCHOOL_CENTER

SCHOOL
OTHER_EDUCATIONAL_FACILITY
CHILDRENS_HOME
VACATION_CAMP

**Comment by MateStrysewskeSym** [comment]
New list of facility types can be found in #2340

**Comment by MateStrysewskeSym** [comment]
@ChristopherRiedelSymeda Consider the new types mentioned in #2406

**Comment by markusmann-vg** [comment]
[Facility types_200107_FINAL_GaPo.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4862863/Facility.types_200107_FINAL_GaPo.xlsx)
@ChristopherRiedelSymeda Please consider this to be the final xls sheet

**Comment by bernardsilenou** [comment]
@markusmann-vg I had a quick loot at the final table and was wondering why certain type 2 categories are doubled only to realize it may be a translation issue: 
Hotels appear in line 7 and 20 (we need to correct the translation i suppose)

Another comment is that some level 2 categories for residence are actually accommodation felicities, e.g Mass accommodation (e.g., guest and harvest workers),  Asylum accomodations/initial reception facilities are classified under residence but seem more of an accommodation. 

Since there is no clear cut difference between residence and accommodation, what do you think about merging residence and accommodating into a single  level 1 variable called "Residence/Accommodation" and merge all the level 2 categories?

**Comment by bernardsilenou** [comment]
One last point we decided that is not mentioned in the excel table is to add "Other" + free txt to all level 2 categories

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou There's not Hotel in line 7; it's Hostel, which is a difference. Concerning accommodations vs. residences, I agree that Mass accommodations probably are a better fit for Accommodations because they're not officially living there. However, asylum accommodations are where the people are actually and officially living (since they don't have any other official residence), so we definitely should keep that as a residence.

And I don't agree to merge those two together because there's a very, very distinct difference between them. Residences are the official place where the person is living, while accommodations are temporary, almost always for a very short amount of time.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Grand merci, I now see clearer. I have no suggestion anymore.

**Comment by bernardsilenou** [comment]
- Add "unknown" among the categories to be chosen when creating a case. This is because there are users who who manage cases without knowing the facility of the case.
Another option is to make facility of a case "not required field", do you thin this is a good solution @MateStrysewskeSym?

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Please create a separate issue for the "district and facility should not be required" requirement.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda if we have entities with null values for health facilities and district, will that not affect our statistics adn filters?
I was thinking we go with the option of keeping them required and adding an "unknown" as an option. Please confirm what you prefer then i will create a new ticket.

**Comment by MartinWahnschaffeSymeda** [comment]
- [x] overnight stay -> type statt group
- [x] case: pre-select facility type "hospital" for new cases and bulk data entry
- [x] use CaseDataDto.FACILITY_TYPE instead of local string
- [x] clinician fields only visible when hospital or other medical facility
- [x] correctly handle read-only based on jursidiction for new fields
- [x] for facility of birth allow "home or other place" when no facility type is selected

@ChristopherRiedelSymeda Next steps:

- [ ] add the facility type for place of birth and occupation to the person entity
- [ ] during case, contact and event participant import correctly handle the import of the facility type
- [ ] define what still needs to be done on the app

**Comment by ChristopherRiedelSymeda** [comment]
> * [x]  during case, contact and event participant import correctly handle the import of the facility type

won't do it for event participants because they can't be imported
