### ISSUE TITLE
Event import together with event participants [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#1642]
### Situation Description
Users would like to use events to e.g. trace all persons that have arrived in a country via airplane without having to create them as cases or contacts. In order to do this, they would like to create events and add all these persons as event participants.

### Feature Description
Add an import that allows importing events and associated event persons.

### Possible Alternatives
Split these imports into two, i.e. create an event import and a separate event person import.

### Additional information
Reuse the functionality of importing  "cases with n samples"

**Comment by Iheanacho2027** [comment]
I was about logging this as a ticket, pls this is very important

**Comment by bernardsilenou** [comment]
I got a request from the field about this issue today. Can we consider implementing it in the next print?

**Comment by bernardsilenou** [comment]
I got request from another group of users needed this feature. Option to import persons per even not importing the event. Can we add to future sprint?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou You're free to make this a priority during any sprint review.

**Comment by Candice-Louw** [comment]
+1 Request for this feature by Berlin (DE) on 27.07.2020.

**Comment by bernardsilenou** [comment]
@markusmann-vg I will add this to my list of prioritization against Monday.

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske  The French team will work on this ticket against next sprint.
- Will implement import of event participant first

**Comment by carolinverset** [comment]
@benchaabaner
it's up to you :-)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @olivierleuci

After analysis, the french developers team propose the following specification : 

1. addition of an import button in the list of participants of an event

1. this button asks to load a csv file (a popup explains the process and allows you to download a template as is usually the case in SORMAS for other imports)

1. once the file is loaded we start the import.

1. for each line we check if the person indicated already seems in base :
- if similar person (s): a popup is displayed with the list of people. The user then chooses a person from the list * or can decide to finally create a new person (or to go to the next line without doing anything)
- otherwise: we create a new person with the information from the file
- in all cases the person selected or created is associated with the event with the "involvement description" indicated in the file


The mandatory columns of the import file will be: person.firstName, person.lastName and eventParticipant.involvementDescription.

@bernardsilenou is this proposal ok for you ? 

Thank you and see you later

**Comment by bernardsilenou** [comment]
@carolinverset This is good. 
I think it would be nice to use all the default import icons as we have for case import. 
After checking for duplicate person and choosing or creating a new person, we check for duplicate event participant
   - of found, merge both
   - If not found, create new event participant (similar to case creating)

![image](https://user-images.githubusercontent.com/12996724/98360259-c83b2780-2029-11eb-8c75-1f7fa5826b69.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske French dev team is working on this in 1,52

**Comment by ChristopherRiedel** [comment]
@carolinverset After the person duplicate detection an event participant duplicate detection must be performed if an existing person is selected. The event participant duplicate detection is currently under development (#3392).

**Comment by markusmann-vg** [comment]
Event import will be treated in another issue

**Comment by ftavin** [comment]
This "old" issue looks a lot like #4041 which is under review on our side (PR coming soon)
