### ISSUE TITLE
Extend the person "selection" (search) logic when creating contacts [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1644]
### Problem Description
When creating or importing contacts, the component that presents persons in the database that potentially match the imported person only operates based on first and last name. 

### Proposed Change
The component needs to be extended by at least the jurisdiction, but preferably also by additional variables like sex and birth date. To do this, the contact creation form needs to be extended by those variables (likely the same that are also used in the new case creation form).

Make sure this is consistent with the fields used when creating a case.

- [x] Add an explanation text to the person selection field
- [x] Unit test the search logic (expected list of matches).
- [x] The component needs to be extended by at least the jurisdiction
- [x] preferably also by additional variables like sex and birth date
- [x] the contact creation form needs to be extended by those variables (likely the same that are also used in the new case creation form).
- [x] Only take persons into account that are associated with a non-archived contact or case
- [x] Only take persons into account that the user has access to

**Comment by MateStrysewskeSym** [comment]
- [ ] rename "uuids" in person facade to "personUuids"
- [ ] fix bug on test system when creating a person that has no duplicates

**Comment by Iheanacho2027** [comment]
@bernardsilenou @MateStrysewskeSym from my experience so far during import of contacts, the speed of importing contacts is very slow. The system still spots contacts that are really far from being related e.g in some observed instances, it still considers similarities using only the variable of first or last name.
We should also add to the algorithm

Only take persons into account that have exact first name and last name combined, in collaboration with age and gender

**Comment by bernardsilenou** [comment]
@Iheanacho2027  similarity of cotantact has 2 levels:
1, Similar contact person: This uses only the first name and last name for now, We can latter add variables linked to the person like sex and  DOB/age. We do not considers region and district at this stage of identifying similar person. I do not think we should also limit the search only to persons thath the user has access to because this will prevent us from identifying contacts outside the jurisdiction of the user.
I suggest we go with this: Only take persons into account that have exact (not exact but high similarity match, say >90% and can be changed by user) first name and last name combined, in collaboration with age/ DOB, gender and  National health ID.
This will mean creating another parameter to determine the cutoff limit for similar person detection in addition to the parameter that we have for similar contact detection. This will prevent the system from suggesting many persons to the user but will not improve search time much since we still have to search the whole person table. This issue is related to #2178 

2, Similar contacts: For this, the system will check for similar names, regions, districts, age, sex, National health ID of all the contacts related to the source case.

**Comment by bernardsilenou** [comment]
I did no reopen the issue because it is similar to  #2178
