### ISSUE TITLE
Make dashboard accessible to district users [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1646]
### Feature Description
Since district users are now able to access the web app (#1567) they also need to have a dashboard.

- [ ] Define what data they should see in the dashboard (e.g. only cases of their district or region or the whole country).

**Comment by MateStrysewskeSym** [comment]
@hzi-old @bernardsilenou @Chinedar Do officers need to see the transmission chains on the contact dashboard?

**Comment by bernardsilenou** [comment]
This may be complicated since they are not allowed to see contacts outside their districts and most important is when theirs contact become cases and have more contacts.
I suggest we give them the feature but limited to only contacts  and cases that they have right to see. ie. a filtered version of the transmission chain.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou For now, I've removed the transmission chains from the dashboard for officers because the feature currently doesn't really allow this kind of access restriction. We can re-add them as soon as that's changed.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym That is very fine for now. Thanks

**Comment by foyiri** [comment]
yes this will also help them see their case count
