### ISSUE TITLE
doc: REST API reference

### ISSUE THREAD

**Issue by shawnsarwar** [hzi-braunschweig/SORMAS-Project#1671]
The REST API is emphasized in the documentation, but I can't find any reference for its use. Any direction would be appreciated, but we're currently most interested in reading contact information into a foreign system.

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym Please respondn accordingly
Thanks

**Comment by MateStrysewskeSym** [comment]
@shawnsarwar Hey! Because of the current situation with COVID-19, we don't have the resources to create a dedicated REST documentation right now. Please have a look at the sormas-rest and sormas-api projects, you should find the required information there. Do you have a specific question, or maybe a suggestion how this documentation should ideally look like?

**Comment by shawnsarwar** [comment]
Hi @MateStrysewskeSym, no worries we're in the same boat working with the Nigerian CDC instance of SORMAS. We have a couple of sets of data that need to be continuously imported into SORMAS and there's a request to get contact tracing data out of SORMAS into some other tools for visualization.

In the very short-term a sample showing how to get `contacts` via cURL would be very helpful.

In the longer term, it would be ideal to have something like Swagger provide a browsable API as part of SORMAS. 

It looks like you all use Retrofit on the Android side, so there may be an opportunity to scrape that:
https://github.com/swagger-api/swagger-codegen/issues/465

In the meanwhile we'll take a look and see where we get parsing the code. Thanks again and good luck!

**Comment by bernardsilenou** [comment]
@shawnsarwar Which kind of visualization do you need to do please? We currently have a transmission chain and follow up visits  visualization in addition to contact dashboard. What is not an The Nigerian server now is the transmission chain. This will be ready hopefully in the next release.
Please share the the kind of visualization and performance indicators of contact tracing that the are needed so that we can include in SORMAS also. Thanks

**Comment by shawnsarwar** [comment]
@bernardsilenou I'll let you know when I get concrete requirements. As of now we're just building capability as we wait for a specific request.

**Comment by StefanKock** [comment]
Was merged to development by @MateStrysewskeSym
