### ISSUE TITLE
Make follow-up until date editable

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1680]
### Problem Description
In the current COVID-19 situation, the follow-up period is not necessarily defined by the contact date, but more by the quarantine date. If the quarantine is extended, the follow-up period should also be extended.

### Proposed Change
Make the follow-up until date editable. Users should never be able to shorten it, but it has to be possible to lengthen it. Additionally, add another validation to the date of a follow-up visit that prevents users from entering a date after the follow-up period ends. This avoids confusion because if they, right now, create a visit after that date, it just won't appear in the list.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I do not ques understand this issue but will explain in my words of it is the same thing that you meant.
My understand is that the expected "follow up  until date" is disease specific and calculated as date of last contact with case + d, e.g d = 14 for COVID. However, If the user decide to follow up a particular contact person for more days (d+20 for example) and another for d days only, then they should be able to do so in SORAMS. 
In addition, if the contact person happens to have a another contact to a case of the same disease while their d days of follow up is not completed, then the follow up counter starts from 0 all over.

WHOs recommendation is that the follow up period stats from the date of last contact with the case. The quarantine date to my understanding is the date that the contact person went on quarantine which might have no relation to the date of last contact with the case.

When you say "Make follow-up until date editable", do you mean edible for a disease or for a particular contact person of a disease? If it is for a particular contact person, then is this not already the case? because users are not restricted to record follow up visits after the expected d days. If it is disease specific, don't we already have that in the properties when setting  the server?

Please let me know what you think about this

**Comment by MateStrysewskeSym** [comment]
We need to extend the follow-up duration because a) this will ensure that users get a task to do a visit and b) because we need this date to calculate which visits are actually belonging to which contacts. This is associated to the bug issue you created; if users create a visit for a contact that takes place after the follow-up period ends, this visit just won't appear in the list for that contact. We avoid that situation by extending the follow-up period. This is per contact, not in general.

The association with quarantine is just what it works like for COVID-19 in Germany right now. It's only a justification for implementing this feature, there won't be any hard-coded links between the two information in SORMAS.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Fantastic idea. I got it!
