### ISSUE TITLE
Contact officers continue to get daily follow up task for contact persons after the expected d days of follow up is over.

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1710]
### Bug Description
- CO continue to get task fro contacts  whose follow up days is over.
### Steps to Reproduce
1.
2.

### Expected Behavior
- When the expected followup days is over, contacts should be automatically classified as "Stopped Follow-up". However, the CS should have the right to extend the follow days for specific contacts.
- CO should not receive daily follow up task when contact is classified as stopped followup.
- All contacts are classified as under follow up  even when d days is over
### System Details
* Device: tablet samsung
* SORMAS version: 1.36.2
* Android version/Browser: A 8

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Follow-up tasks being generated for contacts where the follow-up days are over is most likely due to a missing visit for the last day of follow-up. In that case, SORMAS keeps creating follow-up tasks until one of them is done to ensure that follow-up was performed on the last day of the incubation period.

Apart from that, I've made sure that follow-up tasks are only generated for contacts that are under active follow-up.
