### ISSUE TITLE
Dashboard: Public cases should not be counted for other regions

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1737]
### Bug Description
This case is appearing for all states even though it is a Lagos case. This is affecting states count and dashboard. 
### Steps to Reproduce
1. Deactivate it's visibility for all states
2. How can we make cases with contacts in different regions available for contact addition but yet not increase their own count of cases or appear as a case in that state? 

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by chukwuemekauzoho** [comment]
@MartinWahnschaffeSymeda @bernardsilenou @Chinedar @tomabadaniel please this is urgent as all our dashboards, case counts are showing false information. Can this be treated as soon as possible, please.

**Comment by bernardsilenou** [comment]
@chukwuemekauzoho Thanks for calling attention to this point. I think we need to address it urgently.
When a case is made public, it should only count in the statistics of its region and district of notification. Both on the dashboard and in statistics section.
The contacts of the case should count in the statistics of the contacts' region and district,
We should also allow users without default assess to the case that is made public to only edit contacts of the case and not the case data. The case data should not even appear in the drop down of their case listing not to confuse them whey the sum is not adding up. Contacts can appear on drop down of contacts

**Comment by MateStrysewskeSym** [comment]
@Chinedar @bernardsilenou I'm not sure how exactly we should handle this. One step would definitely be to ignore the case for the dashboard, but it will still show up in the case directory and affect the count there because otherwise, the feature wouldn't make any sense as users wouldn't be able to access it. Could you please give us an exact definition of what we should do here?

**Comment by bernardsilenou** [comment]
I suggest that when a case is made public, sormas should make a copy of the contacts of the cases and share only these contact information to the districts that the contacts belong. We should not share a copy of the case, i think this is what  we are currently doing.

We can use the same module we already have to create a contact having a case in another system.

-Since the initial goal of this feature was to be able to create a contact without having access to the source case, we may not need this feature anymore since it is now possible to create contact without a case.
-No matter the final solution, it is not good to make a copy of a case and share among user groups.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou That doesn't make sense. The whole purpose of making a case public is that people from other jurisdictions can create contacts for that case. To be able to do that, they need to see the case.

Also, we don't make a copy of the case. We just allow everybody to see it. The feature to create contacts without a source case is no replacement for this feature, because ideally, contacts should always have a source case if it's possible. Since the source case is in the system, just in another jurisdiction, sharing the case with the country solves this problem.

@Chinedar can you help with the definition?

**Comment by Chinedar** [comment]
Thinking about this deeply now, no logical way comes to mind on how to set
this up without the case appearing for all the other regions. For a start
we can hide the count from the dashboard for them, and make other fields of
the case not editable except for the contacts bit. But of course when they
download can this case not be part of their download? Thanks.

**Comment by MateStrysewskeSym** [comment]
@Chinedar The cases that are downloaded always match those that appear in the case directory, so unfortunately, it's not that easy to exclude them from any downloads.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym maybe i am not using the right technical words. I will explain again please.
Fiji if facing this same problem after a case was made public.
Here is my suggested solution, maybe it is already implemented:
When we make a case public, 
1,users groups that do not have default assess to the case data should only be able to edit the contact section of the case. The other tabs of the case (person, epid data, hospitalization, ,,, ) of the case should be grayed out and be non editable to these users.
2, This case should only count in the statistics or dashboard of its initial jurisdiction. The same for contacts,
3, when we decide to latter unchecked the bottom so that the case is no longer public, the other case information shared to other groups should also disappear from their view. However, the contacts should remain shared with external groups users.
What do you think about this?

**Comment by bernardsilenou** [comment]
After reading all the comments, I suggest we talk about this in person in our next meeting to find a walk around this. It is an error for users outside the default group of a case to be able to download or change the case data.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou That makes sense so far. 1) is already outsourced to another issue that we're going to take care of soon. 2) is something we need to fix. 3) isn't doable; if the case is no longer shared with the country, the contacts will be gone as well (except the contacts in the jurisdiction of the respective user, of course; so if a user used that case to create contacts in their jurisdiction and later loses access to the case, the contacts in their jurisdiction will stay visible for them).

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Make sure to apply the user's region/district as a filter on the dashboard (see DashboardFilterLayout.createRegionAndDistrictFilter)

@raghupola-vg Can you add a UI test for this? 

- [ ] Test: A "public" case (can be set in the case data form) should only be counted on the dashboard of a surveillance supervisor that is associated to the region of the case. 

@Chinedar Besides the dashboard, is there another view that currently counts the public case, although it should not?

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda @Chinedar I've also added a checkbox filter to the case directory that allows users to exclude cases that have been shared with them; this should allow them to be able to report correct case numbers.

**Comment by Iheanacho2027** [comment]
Pls re-open this ticket, the problem still exists
