### ISSUE TITLE
Duplicate detection for contact creation [5]

### ISSUE THREAD

**Issue by shaneelprakash2910** [hzi-braunschweig/SORMAS-Project#1750]
### Situation Description
The current SORMAS for Fiji does not have the capability to identify the duplicate case contacts with a case.

### Feature Description
The data entry clerak together with the SORMAS team requests for a feature that can be used to identify and merge the contacts with the same case.

### Possible Alternatives
 None

### Additional Information
n/A

**Comment by MateStrysewskeSym** [comment]
We're currently refining the way persons within a contact are detected as duplicates. As soon as we're through with that, we'll tackle the point of duplicate contact detection. Thanks for your submission!

**Comment by shaneelprakash2910** [comment]
Thank you.

Desperately waiting for this in the next release.

**Comment by MateStrysewskeSym** [comment]
For orientation, we already have person and case duplicate detection that can be used as references during the implementation of this issue.

Since we also have person duplicate detection for contacts, we need to chain these two components. It makes sense to check for person similarity first because the person also determines which contacts may be duplicates. That means that, when a created or imported contact person is detected to be similar to an existing person, the existing person duplicate selection component pops up, and as soon as the user has made a selection, the system checks whether it can find potential duplicates for the contact and, if so, opens another popup window that asks the user to select or pick a contact.

- [ ] Add contact duplicate detection mechanic that is done after the person duplicate detection
- [ ] Use this mechanic during contact creation and contact import

* Only check contacts with the SAME person entity as the created/imported contact; this also means that we don't need to check for sex, age etc. because we've already checked for person similarity before doing the contact duplicate detection
* Additionally, only regard contacts where the last contact date is within 30 days of the last contact date of the created/imported contact (if the date is available), same for report date time
* Rest of the logic can probably be taken from the case duplicate detection

**Comment by MartinWahnschaffeSymeda** [comment]
Additional notes:

1. Just to make sure: The disease of the imported contact is used as a filter to only search for potential duplicate contacts of that disease, right?
2. The case of the contact should be used as a filter when it's a case in the system. When no case is provided the "case id in external system" field is something we should show to the user
3. Fields to show:  date of last contact, type of contact (ContactProximity).
4. If there is some space left we can also display contact classification, contact status and follow-up status

**Comment by MartinWahnschaffeSymeda** [comment]
Review notes:

- [ ] Update info text: `The database already contains at least one contact that seems to be very similar to the details of the created contact.<br/><br/>Please look through the list of contacts. If you feel certain that one matches your contact, select it and click on the <i>Save</i> button. Otherwise, click on <i>Create new contact</i> to create a new contact for the person.<br/><br/>If you are unsure, you can discard this window and cancel the contact creation process.`
- [ ] contact id of (not yet) created contact should not be shown
- [ ] ContactSelectionField: wrap the contactDetailsLayout inside a Panel, so it has scroll bars. e.g.
mainLayout.addComponent(new Panel(contactDetailsLayout));

**Comment by BarnaBartha** [comment]
- [x] add duplicate detection check also for imported contacts
- [x] add last date of contact as a column to the similar contacts grid and the contact being created to the contact duplicate detection modal

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add case information to similar contact
