### ISSUE TITLE
List of official supported Web browsers needed

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1766]
### Situation Description
We receive calls from users about display problems on different browsers. But we don't know if the browser is officially supported by SORMAS: 
### Feature Description
Provide a list of officialiy supported browsers in the README

**Comment by kadeng** [comment]
Possibly useful services:

- https://crossbrowsertesting.com/ ( costs money after free trial, pretty comprehensive )
- http://browsershots.org/ ( free, rather simple, with XMLRPC interface for automation )

Likely there are more..

**Comment by MartinWahnschaffeSymeda** [comment]
@fhauptmann It would be very good to have some details on what those users perceive as display problems. From my experience this is highly subjective.
In addition we need to check display resolutions.

Example: Especially in the German version we have several UI elements that overlap, because the text is too long (not browser related).

**Comment by fhauptmann** [comment]
@MartinWahnschaffeSymeda at least it would be very helpful to have a list of supported browsers versions. So we can filter out the real display problems from problems that arise, because people use outdated browsers or browsers with a very small market share.

**Comment by MateStrysewskeSym** [comment]
@fhauptmann We're testing SORMAS on Firefox and Chrome, so that should involve most browsers that have been built based on Chromium. We don't officially support Safari, Opera or IE. The version is always the latest version because that's what we're testing against.

I'll add this issue to the next sprint because we should have this list in one of our readmes.

**Comment by HolgerReiseVSys** [comment]
According to https://vaadin.com/download/release/8.8/8.8.3/release-notes.html#supportedversions 
Vaadin Framework 8.8.3 supports the following desktop browsers:

Mozilla Firefox 54+
Mozilla Firefox ESR 52+
Internet Explorer 11, Edge (latest version)
Safari 9+
Google Chrome 59+

Additionally, Vaadin Framework supports the built-in browsers in the following mobile operating systems:

iOS 9+
Android 4+ with Chrome 42+

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Can you add the link to Vaadin to the readme in a "supported browsers" section or so?
