### ISSUE TITLE
Remove PersonNameDto and directly load SimilarPersonDto instead

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1773]
### Feature Description
The person duplicate detection has been refactored some time ago in order to do the similarity detection directly in the database.

### Problem Description
We are still retrieving PersonNameDtos and then use them to immediately query for SimilarPersonDtos based on the UUIDs. The PersonNameDtos were used before to match the names, but they are not necessary anymore.

### Proposed Change
Get rid of the PersonNameDto, rename PersonFacade.getMatchingNameDtos to getSimilarPersonDtos and let it directly query for SimilarPersonDtos; PersonFacade.getSimilarPersonByUuids can also be removed then.

### Additional information
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2782

**Comment by Iheanacho2027** [comment]
This is highly needed. Another problem is that the algorithm checks using one name variable to check for persons in the database. It should consider both names and ensure that the scanned duplicates have the same first name and last name with the contact about to be imported.

**Comment by bernardsilenou** [comment]
@Iheanacho2027  I understand you perfectly. 
@MateStrysewskeSym we may need to increase the similarity threshold to say 0,95. 
I also do not know if we do the similarity person search based in the db. This may also increase the speed.
Since this is about contact persons, I think we should always search the whole db.
