### ISSUE TITLE
Wrong fatality and sample count on dashboard

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1792]
### Bug Description
The dashboard on the user account of a surveillance supervisor from Kwara State, Nigeria, showing COVID-19 surveillance data for the state is erratic. 
a) First, the fatality in the state for the year 2020 is one (1) as shown on the case directory but the dashboard shows two (2)
b) Second, the positive results in the state for the year 2020 are four (4) as shown in the sample directory but the dashboard shows two (2)

**Comment by Iheanacho2027** [comment]
@bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 For the second, please verify that a) the samples are actually part of cases in the specific state and b) that those samples actually belong to four different (!) cases.

**Comment by Iheanacho2027** [comment]
a) All the samples belong to the state
b) All samples belong to different cases

@bernardsilenou has confirmed that it's a bug

**Comment by MateStrysewskeSym** [comment]
The first bug is caused by a case person that has a "cause of death disease", but a present condition status of "alive".

**Comment by bernardsilenou** [comment]
I had a look and realized that the bug depend on the user group. If you log in as  national user, you might not identify the issue. Please log in using national user  and surveillance supervisors roles and obtain statistics  on dashboard and by filtering in the statistics section. discrepancies will show as mentioned above

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 @bernardsilenou I've identified both issues.

a) is caused by a COVID-19 case that has the present condition "Alive", but for some reason has a casue of death disease set which makes it appear as a fatality on the dashboard. I've fixed the logic that calculates this and also made sure that, when a person is saved and the present condition is empty or "Alive", the cause of death fields are cleared.

b) is not a bug and actually works as expected. For two of the cases that these four positive samples in the sample directory belong to, newer samples have been created and tested (one of those negative, one pending). The "new test results" on the dashboard currently always take into account the most recent sample of any case, but never more than one, which is why two of these samples are ignored (as their cases have a more recent "pending" sample). This is not a perfect logic and we'll refactor this in the near future when we introduce a "final laboratory result" variable to the case, but for now, it's how it works and how we were told it should work.

**Comment by Iheanacho2027** [comment]
For purpose of clarity, the dashboard should take into account the result of the first sample collected, if there is no variable for "final laboratory result" for the case as you said. According to the surveillance structure, the result of the first sample collected determines the case classification for the case. Pls you may have to refactor it as i have explained to make it part of friday's release. This is because people are already getting wrong information as regards COVID-19 happenings in their state from the dashboard @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Aren't they getting wrong information if we change it that way? These two cases that we are talking about had a negative result after the positive one. The case classifications can still be collected independent of that. I'd like to hear the opinions of @Chinedar, @bernardsilenou and @hzi-old on this as well.

**Comment by Iheanacho2027** [comment]
What i mean is, only one result per case should be accounted for by the dashboard, and that should be the result of the first sample collected as that is the result that determines the case classification. Other tests are usually tests that determine the outcome of the case and not the classification

**Comment by bernardsilenou** [comment]
here are my comments please:
1. If a sample has more than  one result, then SORMAS should always ask the user which test result to use as final results of the sample and use this variable  anywhere else in the system.

2. @MateStrysewskeSym Thanks for your clarification. I went further and realized the validation between outcome of a case and present condition does not work backward. For example if
outcome = disease, then present condition = dead (works fine). When you latter change
outcome = recovered, then present condition = dead (remains as dead). I think we need to correct the validation rule for all options of outcome and present condition. I can send the rule by email if needed.

3. I understand your comment about fatality is link to a person. I recommend we calculate fatality  based on the outcome of the case not present condition of person. This is because a person can die from other causes than the disease concern. OR if a person linked to 2 cases die due to disease x, then the fatality for disease y should not include the person because they did not die as a result to disease y. This means a person linked to a case of a disease can die but does not necessarily count among fatality of the disease. 
4. Concerning point b. We should show the final lab results for samples linked to the cases shown/ filtered by ui, but not the recent or first sample result only. If there are more than one results of a sample, we always asked the user to choose the result to use as final lab results of the sample and this is not necessarily the recent result. If a case has more than one sample then we use the same logic for each sample and show both on dashboard. This might lead to more samples than cases but it is fine for now.  When we will finally have a final lab result variable for a case; we can then show only one sample result per case as you mentioned.

5. @Iheanacho2027 the first sample result is often use but not always the case to determine the final lab classification of the case. As i mentioned in point 4. we should allow the user to choose.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou HZI specifically requested multiple times that the "new sample test" count on the dashboard MUST NOT exceed the case count. What I'd like to know is whether you agree that the sample counted for this should always be the first sample documented for a case, or whether you suggest a different logic. We have to make this fixed for now because we don't have any logic that allows users to determine which sample should be counted, so please - for now - decide on a general rule that we can use until we have the laboratory result variable directly for a case.

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym pls its only the result of the first sample that should be counted by the dashboard to ensure that its equal to the case count

**Comment by Iheanacho2027** [comment]
@bernardsilenou you are right but like i said pending when @MateStrysewskeSym will implement the variable for "final laboratory result" for the case, let him refactor as i have explained (using the only result of the first sample as the count for the count on the dashboard) to make it part of friday's release

**Comment by StefanKock** [comment]
Already released, no findings in code review (except unit tests would have been nice).
