### ISSUE TITLE
Allow filtering follow-up visit overview by a single date [1.5+0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1821]
### Situation Description
Users want to be able to filter the number of cases and total case count under followup on a particulate day. The current system only give them the option to select cases for 8 days.
### Possible Alternatives
none
### to be reviewed by
@BarnaBartha

**Comment by markusmann-vg** [comment]
- [ ] Add a FROM Input field, so that we have FROM and TO dates to define the range
- [ ] Set default value FROM to "date - 14" and TO to "date"
- [ ] keep the buttons and take the diff from the selected range 
- [ ] Display the according data in the grid
- [ ] Show "apply" button when FROM or TO was changed
- [ ] Pressing the buttons applies automatically

Example:
FROM = 01.05.2020
TO = 11.05.2020
DIFF = 11 days, so the buttons show "- 11 days" and "+ 11 days"

**Comment by sergiupacurariu** [comment]
The actual implementation is according to the requirements less this behavior: when a "From" or "To" date is changed the search is triggered automatically without the need to use an "apply" button. Note: the wait time is related to the range selected.
