### ISSUE TITLE
Contact Dasboard not opening

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1839]
### Bug Description
Contact dasboard does not open, eventually times out the instance on the Nigerian server.
### Steps to Reproduce
1. Login as admin and national user
2. 

### Expected Behavior
Dashboard should open as normal as the surveillance dashboard 

### System Details
* Device: laptop
* SORMAS version: 1.38.0
* Android version/Browser: browser.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Seems like this is happening because we need to retrieve the last visit of every contact for the dashboard, and there seem to be a lot of contacts to display. This is caused by the loose association between contacts and visits. I'm not sure how to quickly fix this; the only thing that comes to my mind right now is disabling the affected section on the dashboard (the part that lists the current follow-up status of the contacts).

**Comment by MateStrysewskeSym** [comment]
@Chinedar Did this already happen before the update? I don't really see any new code changes that would've caused this.

**Comment by Chinedar** [comment]
Yes this was already happening before the update. So best we disable the
part affecting it, while we work on a better solution.

**Comment by MateStrysewskeSym** [comment]
Changes will be done in #1558

**Comment by StefanKock** [comment]
I suggest the changes of #1558 should be reviewed by @MartinWahnschaffeSymeda or @ChristopherRiedelSymeda to check if the problematic feature is deactivated.
