### ISSUE TITLE
Dashboard should include all cases by default and not filtered by epiweek

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1862]
### Feature Description
The current dashboard by default only includes cases that were reported in the current epiweek. User has to adjust the filters to get the overall figures on the dashboard.

### Problem Description
The need to always adjust the filters to get the overall figures is not ideal.

### Proposed Change
The dashboard should show figures similar to the way the online covid-19 dashboards do, that is, include all cases since the onset of the epidemic/pandemic. This way, user does not have to adjust the date filters to get these figures

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi @bernardsilenou 
We need to find another solution for this.
WHen "since outbreak onset" is selected, the pull request implementation will always show ALL cases of all disease in the top part of the dashboard and have individual time filters for the bottom part of the dashboard.

It is important to understand that the dashboard in SORMAS is not for a single disease only, but to give an overview on the situation for the whole country. 

Besides that you are right, there is a big need to make it as easy for users as possible to look into the time filter that they are currently interested in - and that is define by the onset of COVID these days.

We need to have a consistent time filter here. There are three options that come to mind:

1. Define a default time filter for the dasboard in the sormas.properties for the whole server that can be activated in times like these
2. Store the picked date filter option for the current user
3. Encode the filters in the URL, so users can use the url to always open the dashboard for the same time filter

**Comment by bernardsilenou** [comment]
> WHen "since outbreak onset" is selected, the pull request implementation will always show ALL cases of all disease in the top part of the dashboard and have individual time filters for the bottom part of the dashboard. _(I think this will be too heavy for dashboard and it may crash as in the case of Nigeria )_
> 
> It is important to understand that the dashboard in SORMAS is not for a single disease only, but to give an overview on the situation for the whole country. _( This is the goal but focusing on lower part or hiding the upper part will give us disease specific dashboard only for a particular time, not for all time from onset of used on the tool)_
> 
> Besides that you are right, there is a big need to make it as easy for users as possible to look into the time filter that they are currently interested in - and that is define by the onset of COVID these days.
> 
> We need to have a consistent time filter here. There are three options that come to mind:
> 
> 1. Define a default time filter for the dasboard in the sormas.properties for the whole server that can be activated in times like these _( this will also need to be disease specific and will not make sense for regions that got affected 9  months after the first region in the country, so I will not vote for this option)_
> 2. Store the picked date filter option for the current user _( this is good and will also be an solution for issue #1883)_ 
> 3. Encode the filters in the URL, so users can use the url to always open the dashboard for the same time filter (ditto)

**Comment by faatihi** [comment]
@MartinWahnschaffeSymeda I vote for option 2

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Ok. I think we need 2 and 3 then. When 3 is working you can use the encoded string and save it for the user. 
Can you create a new issue for this?

**Comment by faatihi** [comment]
Okay
