### ISSUE TITLE
Automatically pick current location coordinates when creating case and contact

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1865]
### Situation Description
Users usually forget to enter location coordinates when creating a case. Same happens with creating a contact.

### Feature Description
The system should automatically pick current location for the coordinates. Users can modify the coordinates later on. This way, all cases will have coordinates and will show on the map.

**Comment by MateStrysewskeSym** [comment]
@faatihi The mobile app already does that automatically - what exactly is missing here?

**Comment by faatihi** [comment]
We have a lot of cases and contacts without coordinates. We looked into ways to keep that in check. One option is to put the picker on the first page of CreateCase/CreateContact and make it the first field so that users may see it first and pick the coordinates.
The second option is to pick the coordinates automatically and allow user to make changes.
Third is to have a new field that keeps the auto-picked location so that if user forgets to enter the coordinates, the auto-picked one will be used for the maps.

> Picking the current coordinates for the person's address seems not like a good idea to me

Users who remember to pick a location can do so to overwrite the auto-picked one.

**Comment by MateStrysewskeSym** [comment]
@faatihi We obviously can't automatically pick locations for cases created in the web because it's very likely that the device used to create those cases does not have a GPS module. We'll talk about the other suggestions in our next sprint review.

**Comment by faatihi** [comment]
I agree with you. This is about the mobile app.

**Comment by bernardsilenou** [comment]
Faat and I had a call and I suggested that we do not activate automatic picking of coordinates as will significantly affect the epidemiology of the disease in terms of space. The reason is that, the place of creating a case is not always the address of the case nor case person.  
The need for this feature was because many cases without health facilities did not show up on map.
Here are possible solutions we decided:
1, For cases with a HF, we use the geo coordinate of the HF (already implemented )
2, For cases at home, we use the centroid of the district of the case with random error. For example cases at home with coordinate missing will have coordinate d + ei, where d is the centroid of the district and ei is small random error lying in the districts. ei is just to prevent all case from having the same coordinate.
3, Add a reminder for users to update and correct this predicted coordinate, twice or once a week
3, Add coordinate to the list of variable in calculating the completeness of the case. This will remind users to always complete it,

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Based on what Bernard is saying: Will you create separate issues for those missing things, please?
I guess the pul request for the automatic location picking can be deleted, right?

**Comment by faatihi** [comment]
Ok. I'll create issues for those. 

With regards to deleting this PR, the implementation also moves the location picker to the first page of Create/Edit Case and Create/Edit Contact so that users can see it and remember to pick locations. Furthermore, the location picker is placed as the first field. That is, before Report Date.
@bernardsilenou is not OK with the field being placed at the top, so it may have to be moved down a bit.
We may have to separate this additional code into it's own PR and delete this one.
