### ISSUE TITLE
Community import Still does not work

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#1875]
The error message is: 
Invalid value Binah in column district; District name is not unique in the chosen region, make sure there is only one district with this name belonging to the chosen region in the database

Obviously there are several communities in one district and therefore this error message, requiring a unique district name, not logic.

**Comment by RafaelKluender** [comment]
I have found out where the problem is. 
During import of Communities, archived Districts are taken into account. 
That means that if something went wrong during the import of districts, and you have duplicates, you can no longer import communities. 
That is because Sormas does not know  where to add the community: to the active district, or the archived equivalent duplicate. 

As a result, once you have duplicates, as they cannot be deleted (WHY?) you're stuck and can't go on. 

Please at least tell how to delete the duplicate entries at the database level.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Please see my answer to #1783.

Deleting the duplicate entries within the database can be done with a simple SQL script:

`DELETE FROM district WHERE name = '...';`

SORMAS does not contain a permanent deletion mechanic for core data because accidentally deletions could mess up a lot of data.
