### ISSUE TITLE
Duplicate input fields in case/ contact person: Community

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1887]
### Feature Description
The pages "case person" and "contact person" contain two similar input fields for community/ Gemeinde. "Community" provides a drop-down menu with pre-defined communities (by admin) while "community contact person" is a free text box.

### Problem Description
Having two input fields for the community is confusing, as reported by a few German health departments.

### Proposed Change
Integrate the option "other community"/ "andere Gemeinde" in the drop-down menu. If this item is selected, display the previously shown free text box.

### Possible Alternatives
Open to suggestions.

**Comment by ChristopherRiedelSymeda** [comment]
Unfortunately there has been a misunderstanding due to a translation error. I have corrected the translation. The field is not for the contact person's municipality, but for the contact person of the municipality. This field is necessary because in some countries there are communities where only one or two people have a mobile phone and they are called instead of the actual cases or contacts
