### ISSUE TITLE
Add "Type of surveillance" field to case

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1898]

**Comment by bernardsilenou** [comment]
Adding the type of surveillance is necessary but I think it will not solve the problem of "Currently, there isn't a way to take lab samples of contacts".  Since the enhanced surveillance requires visiting cases or contacts or just any person and collect a sample for testing, to document this in the current version, we will need to create a case for each person visited under "Enhances surveillance" which is not a right thing to do in my opinion as it will mess up the dashboard with nuisance suspected cases.

The point i wan to make is that, we urgently need issue #1638 in addition to this issue in this release.
The need to record samples for contacts persons or any other person (#1638) is not only urgently needed for Ghana and Nigeria but in Fiji and Germany also.

This will mean, for either Routine Surveillance or Enhanced contact tracing, we will be able to register either a case or contacts and be able to collect samples and sent to the lab.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi 
If I get you right, you are basically saying that you will use the case for both cases AND contacts. In my oppinion this will cause a lot of problems, especially when you are trying to build transmission chains!

I don't know how to go forward with this. We should at least make it "Ghana only" for now.
I'd also like you to add a description to the field, so people have an idea what it is about.

Again: Note that you will have a lot of work with this, once you try to convert those "contact cases" back to actual contacts.

@bernardsilenou You are right, but this can't be done anymore. Implementing #1753 and the simplification needs to be a top priority of the next sprint.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  I most absolutely agree with our last comment.

**Comment by faatihi** [comment]
Pushing #1753 is a great idea. We'll hold back from using the case entity for contacts.

> Adding the type of surveillance is necessary but I think it will not solve the problem of "Currently, there isn't a way to take lab samples of contacts"

@bernardsilenou you mentioned that "Type of surveillance" is necessary. So do we keep this new field in the case entity? 
Also, enhanced surveillance is carried out for contacts and other persons. If we're keeping this field for cases, do we add same field for contacts?

**Comment by bernardsilenou** [comment]
@faatihi I will say this field is not  needed because we can derive it from the reporting users of the case or contact. It is needed only for Ghana for now. Adding more field that can be derived is not a good this to do because we already have may fields in the system.
I call you please

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda @ChristopherRiedelSymeda @faatihi 
There is a variable demanded from German users called "Type of reporting": issue #1822.
I realised that it is technically the same thing as "Type of surveillance" but used different categories.

I was thinking if we can use the caption: "Type of reporting" and use categories "Routine Surveillance and Enhanced contact tracing"  for non German users.

**Comment by bernardsilenou** [comment]
I discussed with Faath and he will verify and let us know is this issue is still needed for Ghana.

**Comment by faatihi** [comment]
GHS has mentioned that it's not the only reason for the type of surveillance. 
Ideally, the module they would like to use is Event. 
That module perfectly fits the purpose of the Enhanced Surveillance. 
But since Event doesn't allow for follow-up and taking samples, we can't use it.

The next best thing is Contact. GHS has agreed to use Contacts for collecting samples ...when the feature is ready.

Also, we're looking forward to making followups on Event participants and taking their samples.
It's a popular demand.

**Comment by faatihi** [comment]
We may now wrap-up on this issue and close it.
