### ISSUE TITLE
Network visualization does not show cases and contacts

### ISSUE THREAD

**Issue by juusotam** [hzi-braunschweig/SORMAS-Project#1921]
### Bug Description

Contact network visualization is not working. Returns "No data available" message.

### Steps to Reproduce
1. Clean installation (Ubuntu)
2. Installed R environment (3.6.3)
3. Added cases and contacts to COVID-19 disease (all cases and contacts investigated and confirmed)
4. Admin role - opened contacts dashboard

### Expected Behavior

Network visualization shown.

### System Details
* Device: Ubuntu 18.04.4 LTS / R 3.6.3
* SORMAS version: 1.38.0
* Browser: Chrome

### Additional Information

Error log: 

```
[2020-04-26T15:15:28.731+0000] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=27 _ThreadName=http-thread-pool::http-listener-1(1)] [timeMillis: 1587914128731] [levelValue: 800] [[
  W151528.731|     > R failed with code 1 : Rscript /opt/sormas/temp/vis_5570115948802915654/transform_contact.R (de.symeda.sormas.backend.visualization.VisualizationFacadeEjb.java:241)
]]
```

**Comment by bernardsilenou** [comment]
@juusotam After installing R, did you install the following packages
RPostgreSQL
ggplot2
dplyr
plotly
extrafont
visNetwork
rpart

Check issue 1168 please,
Installing R in Ubuntu:

sudo apt install libpq-dev
sudo apt install r-base
sudo R
install.packages(c("epicontacts", "outbreaks", "RPostgreSQL", "GGally", "network", "sna", "visNetwork", "dplyr"))
library(RPostgreSQL)
library(visNetwork)
library(dplyr)
...

**Comment by bernardsilenou** [comment]
I recommend you also install devtools, to good to have it
<https://www.r-project.org/nosvn/pandoc/devtools.html>

**Comment by juusotam** [comment]
Yes, I checked that all those packages are installed and up-to-date. The problem remains.

**Comment by bernardsilenou** [comment]
We will have a deeper look and diagnose the problem please.  There will be a release in the coming  days. 
@HolgerReiseVSys any idea ?

**Comment by HolgerReiseVSys** [comment]
Unfortunately there is not yet a simple way to debug the script on a running server.
The output of the R scripts is neglegted and the environment is purged immediately.
The R scripts can be run, hovever, independently in the shell.

```bash
cp -r /opt/domains/sormas/applications/sormas-ear/sormas-backend_jar/visualisation/ .
cd visualisation/
Rscript transform_contact.R
```

You may have to set  some of the environment varibles for the database connection:
`DB_USER, DB_PASS, DB_HOST, DB_NAME, DB_PORT`
In order to regulate the nodes of the network, the `CONTACT_IDS` variable (comma separated ids from the contact table) can be set.

The scrip has been revised quite a bit since the last release. The current version can be found at https://github.com/hzi-braunschweig/SORMAS-Project/tree/development/sormas-backend/src/main/resources/visualisation.

You could also try to directly modify the R script in `/opt/domains/sormas/applications/sormas-ear/sormas-backend_jar/visualisation/transform_contact.R` and have it e.g. write its output to a target outside of its working directory.

**Comment by juusotam** [comment]
Thanks for the tips! The problem was an old library that was not updated after the r-core package was updated.

```
Error: package ‘yaml’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted
```

After reinstalling ```yaml``` package it started to work.

I guess the list of R packages required should be documented a bit more in detail and also the required R version...?
