### ISSUE TITLE
Mockup of SIA Dashboard [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2004]
### Situation Description
During an SIA campaign a lot of data is collected that needs to be visualized.

### Feature Description
Refine and create a mockup that shows what the final dashboard for the intra-campaign pilot should look like.
Should be a dashboard similar to the existing dashboards for case surveillance and contacts.
The user needs to be able to filter by campaign, time and geography/admin unit.

List of indicators to be shown: #2553 

### Mockups
https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf
https://app.moqups.com/3NUENEwuOE/view/page/aab33f609

**Comment by MartinWahnschaffeSymeda** [comment]
Feedback on mockup: https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf

* use tabs to group the diagrams

**Comment by MartinWahnschaffeSymeda** [comment]
I have updated the mockups accordingly.

Source of the diagrams provided by Ben:
[Intracampaign_Indicators_26May2020_BN.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4730703/Intracampaign_Indicators_26May2020_BN.xlsx)

**Comment by bernardsilenou** [comment]
I had a look at the plots and a short sprint to discuss them will be good. They were not very clear to me

**Comment by tomabadaniel** [comment]
@MartinWahnschaffeSymeda About the initial mockup design when the country requested for the buttons for Pre-Campaign, Intra-Campaign and Post-Campaign on the dashboard due to Political reasons to ensure that the country and partners know that the APMIS system will be a comprehensive SIA system not just for Intra-campaign. See mockup before development began. https://app.moqups.com/3NUENEwuOE/view/page/a46ac00af
<img width="2047" alt="Screen Shot 2020-11-23 at 15 38 30" src="https://user-images.githubusercontent.com/60390281/100012938-11b5a180-2da2-11eb-83e6-670af84c37cc.png">
I explained to them that we will include those buttons when we have the comprehensive system but they have strongly insisted that even though its not an active link, for political reasons within the EOC, their system needs to be seen as a comprehensive SIA system in development so we need the buttons there as placeholders.
