### ISSUE TITLE
Add "Final Lab Result" and "date of result" to the case directory view

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#2013]
### Feature Description
The above mentioned variables need to be part of the case directory view.

**Comment by MateStrysewskeSym** [comment]
@Chinedar That's currently not possible because we don't have a "final lab result" for cases yet.

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> are we not able to bring to the
cases view, the latest result and it's date of report?

**Comment by MateStrysewskeSym** [comment]
@Chinedar Kind of, but we always need to make an assumption about which sample might be the one that is the most relevant (just using the latest sample might not be appropriate). We could do that for now and later revisit the logic as soon as we have a defined final result on the case.

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> Thanks. I absolutely agree. Let's
rely on the latest date for now.

**Comment by bernardsilenou** [comment]
@Chinedar, what do you mean by "Let's rely on the latest date for now." Do you mean the latest sample result?
If I can remember well, you or Acho mentioned in an earlier issue to use the first result as the final lab result of the case.
@MateStrysewskeSym Since the sample result counted on the dashboard is the result chosen by the user as the result of the "final lab sample" which is not necessarily the latest result of the sample, I will recommend that we keep the same logic in every sector where sample results are displayed. 

I will create an issue about the final lab result of a case and each person can write how they think the logic should be so that we can include it in the next sprint.

**Comment by Chinedar** [comment]
Let's close this. We can work with what's available for now. Thanks.
