### ISSUE TITLE
Add information window to detailed sample export

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#2034]
### Bug Description
Detailed export from samples directory does not export. 
### Steps to Reproduce
1. Click on the detailed export button and nothing happens
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
The problem here is not that the samples export does not work, but that

a) exports generally take a lot of time depending on the amount of exported data
b) unlike for the case and contact export, there's no feedback to the user that they need to wait for the exported file to be generated

Improving the export speed is a separate and bigger issue, but we'll make sure to integrate the user feedback in this version.
