### ISSUE TITLE
Dashboard includes cases based on contact association

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2053]
### Bug Description
With respect to #1737, Contacts of confirmed cases having responsible regions in other places causes the source case to pop up as a confirmed case in the user account of the surveillance supervisor of that state. Pls this needs a hotfix if possible as it will definitely give wrong values on the dashboard. Pls note, this is just for surveillance supervisor user accounts, for admin and national user accounts, the correct values are shown
### Steps to Reproduce
1. create a contact for a confirmed case in Lagos state, Nigeria
2. Select Kaduna State, Nigeria as the responsible region of that contact
3. Login as the surveillance supervisor of kaduna state
4. Filter out the confirmed cases and you will see the confirmed case of Lagos state popping up in Kaduna state

@bernardsilenou @MartinWahnschaffeSymeda @MateStrysewskeSym 

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Just for clarification purposes: This is not related to #1737. The problem we face here is that our backend contains logic to figure out which cases are visible to the current user. This, naturally, includes cases from outside the user's jurisdiction as long as the user has access to at least one contact of that case. For most parts of the application, this is the absolutely correct behaviour. The dashboard is an exception because here, the user only wants to see the numbers based on their region.

The fix here is to exclude cases from the dashboard that are only visible to the user because of this contact association.

**Comment by Iheanacho2027** [comment]
Pls this error still exists in 1.40.1.  Contacts of confirmed cases having responsible regions in other places causes the source case to pop up as a confirmed case in the user account of the surveillance supervisor of that state. This confirmed cases are seen in the case directory @MartinWahnschaffeSymeda @MateStrysewskeSym @StefanKock

**Comment by Iheanacho2027** [comment]
Pls kindly re-open this ticket

**Comment by bernardsilenou** [comment]
@

**Comment by bernardsilenou** [comment]
@Iheanacho2027 do the cases that show up on the case directory also count contribute to the total number of cases in that region of the contact? either in case directory or dashboard?

**Comment by Iheanacho2027** [comment]
Yes

**Comment by bernardsilenou** [comment]
OK, Please test more and add details. In the directories, do the cases or contacts just show up or contribute to the statistics (dashboard, directory, statistics section) in both of the regions

Please also write how you think kin should work in both regions

**Comment by MateStrysewskeSym** [comment]
We've fixed the cases showing up in the dashboard as that's what this issue was about. If you have another request to also exclude these cases from the case directories, please open another issue for it.
