### ISSUE TITLE
Show home-based quarantine and supply ensured fields only for germany systems [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2095]
### Feature Description
![grafik](https://user-images.githubusercontent.com/23217632/81901766-570d4100-95bf-11ea-828c-86c81f2e4b26.png)

### Problem Description
The two fields are not needed for other countries

### Proposed Change
Hide them

@bernardsilenou Is this correct?

**Comment by bernardsilenou** [comment]
We should  add the option "Others" as a category to quarantine. This will handle contacts in Hotels, etc

**Comment by markusmann-vg** [comment]
@bernardsilenou 
Please specify the countries, where we should hide it

We don't want to hide it for other countries (like France, Switzerland, Fidji, Finland etc.)

**Comment by markusmann-vg** [comment]
Add constants for the needed countries to the "hide for country annotation"

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Any update on this? We need a list of countries that explicitely DON'T need these fields in order to finalise this issue.

@sergiupacurariu As soon as that list is ready:
- [ ] Use the HideForCountries annotation instead of HideForCountriesExcept
- [ ] Create constants for the country codes in some helper class (e.g. COUNTRY_GERMANY = "de") and use these in the annotation instead of hard-coded Strings

**Comment by bernardsilenou** [comment]
We make it visible to ui only for Germany. thanks

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Have you talked to representatives of all countries that currently use SORMAS about this?

**Comment by markusmann-vg** [comment]
Proposal:
Hide for Nigeria and Ghana

@bernardsilenou Pls. confirm

**Comment by bernardsilenou** [comment]
@markusmann-vg  I confirm that we:
1.  hide the variable "home based quarantine possible" and "supply ensured"
2, Keep the variable quarantine and add another category "Others" as a category to quarantine. This will handle contacts in Hotels, etc. If other is chosen then a free text follows. Maybe another issue is needed to add the other option?
3, keep the variable "help needed in quarantine". This variable gets activated only if quarantine is set to home
The reason is that the information in 1 is technically captured by 2 and 3 and the goal is to capture the same amount of information with min set of variables.

**Comment by MateStrysewskeSym** [comment]
Follow-up issue: #2219

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Understood. It makes sense this way.
