### ISSUE TITLE
Implement deletion concept for non-cases or non-contacts

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2102]
### Feature Description

**Non-cases [i.e. records of persons for whom at any time the status of case to non-case has occurred]**

**What is deleted?** 
- The complete data set (!)

**When is deletion about to happen?** 
- At the latest on 1 January of the following year after the last relevant processing of the data record in question by the competent public health authority

++++++++++++++++++

**Non-contacts and non-exposed persons [i.e. records of persons for whom at any time the status of contact person, or exposed person has changed to non-contacts or non-exposed person, which is also the last available status].**

**What is deleted?** 
- The complete data set the data set ID

**What is not deleted?** 
- The data record ID

**When is deletion about to happen?** 
- At the latest on the 1st working day of the following month after the last relevant processing of the data record in question by the competent health authority

**Comment by markusmann-vg** [comment]
Why do we keep the data record ID for Non-contacts and non-exposed persons but not for non-cases and what is the usecase for keeping the data record ID or do you mean the UUID?

Consider deleting everything from history & audit tables
- [ ] Introduce a deletion history table

**Comment by max-hzi** [comment]
Some thoughts from Gaby: 
- each case (case/contact/exposed...) has an ID But what does it mean if the data record ID is not deleted?  Is the case then retrievable? 

In an issue (#2102) it is explicitly mentioned that data set record is not deleted. Perhaps all issues should specify what happens to the data record ID. 

"Non-cases" are special, because the persons had symptoms. It could be that you have to find them again if the case definition changes. 

- history/audit table: What does it mean, if everything here is deleted?

- history: I always like documentation!

**Comment by max-hzi** [comment]
Once again I'd like to document some info from Gérard:

The health departments should be able to set a few essential configurations of the deletion periods for personal identifying data.

**Comment by MartinWahnschaffe** [comment]
Deletion will be fully configurable on field level. See https://github.com/hzi-braunschweig/SORMAS-Security/issues/11
I'm closing this, because the implementation needs to be sliced differently.
