### ISSUE TITLE
User Authentication with Keycloak (create users, login- logout users, forgot password) [5+5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2111]
### Situation Description
France: 2f Authentication
Current situation of password generation & transmitting password
Change & Forgot password methods
Password Policy
Keycloak is required (open source) 

### Feature Description
Deliverable:
New issues that descibe the next steps
- one ticket needs to contain a Migration Guide

APP & Web

**Comment by BarnaBartha** [comment]
Within the timeframe I setup a local keycloak and tried integrating the payara openid connect support into sormas-ui, unfortunately I've ran into some issues:
- authorization issue:
[2020-06-04T10:02:28.793+0300] [Payara 5.192] [WARNING] [] [fish.payara.security.openid.OpenIdAuthenticationMechanism] [tid: _ThreadID=46 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1591254148793] [levelValue: 900] [[
  Error occurred in validating Authorization Code : unknown_error caused by Unknown]]
- infinte redirect redirect between keycloak authentication and sormas-ui.

Documentation and example I've used for the changed that can be found in the branch:
- https://docs.payara.fish/docs/5.201/documentation/payara-server/public-api/openid-connect-support.html
- https://github.com/bcgov/moh-iam/wiki/How-to-secure-a-Jakarta-EE-application-deployed-to-Payara-with-Keycloak
- https://github.com/bcgov/moh-iam/tree/master/keycloak-javaee-example

For installing local keycloak I've used:
- https://www.keycloak.org/getting-started/getting-started-docker
The guide is quite ok but the docker image referenced does not work I've used jboss/keycloak (https://hub.docker.com/r/jboss/keycloak/)

Another example worth checking is:
- https://blog.payara.fish/openid-connect-in-the-payara-platform-5.183
- https://github.com/javaee-samples/vendoree-samples/tree/master/payara/openid

@markusmann-vg 
At this point I think we need more time to continue with investigation or ideally somebody with in depth knowledge of keycloak and oauth2/openid connect to debug and continue with this.

**Comment by BarnaBartha** [comment]
@HolgerReiseVSys @MartinWahnschaffeSymeda please feel free to update these steps
Steps to do: 
- Have a correctly configured Keycloak
- Integrate app-auth into sormas-app
- Integrate a Keycloak client with sormas-ui (possible starting point code from existing branch - feature-2111-keycloak)

- Document how to setup local Keycloak for development machines
- Document Keycloak for production - setup & migration

Things to clarify/investigate:
- what happens to external users of the rest API - should they be authenticated also by Keycloak - if yes integrate a Keycloak client to sormas-rest
- should we have one realm: 'sormas' and different clients for UI, rest, app or different realms for each ?
- how to map / migrate users ? :
	-> (based on the authorization code Keycloak provides after authenticating a user it is possible to get from Keycloak the user information) - using this we can create the current user context
	-> if the users will no longer be in the sormas_db how will we handle the existing queries like: getAllByRegionAndUserRoles, getInformantsOfFacility, getAllByDistrict etc.?

**Comment by markusmann-vg** [comment]
@BarnaBartha: Thank you! Please consult alex.karle@vitagroup and schedule a meeting

**Comment by markusmann-vg** [comment]
Deliverable: POC & follow up tickets made by @vidi42

**Comment by vidi42** [comment]
Outcome of the concept:

- Integration at UI and REST API level
- Integration should be optional, so that systems that don't need Keycloak to not be forced to upgrade
- Keep the Roles management in Sormas
- Deploy Keycloak as standalone or in a docker container

![Sormas-Keycloak Big Picture](https://user-images.githubusercontent.com/3462897/91694208-f1948e80-eb74-11ea-8a42-5ce6cf5afeec.png)

Detailed affected user flows #2745 
At first, the deployment will be done trough Docker image in  [SORMAS-Docker](https://github.com/hzi-braunschweig/SORMAS-Docker)

**Comment by vidi42** [comment]
2FA:
- Keycloak already supports this out of the box trough Google Authenticator and FreeOTP
- Currently the OTP can only be activated in two ways from Keycloak admin console:
  - By default for all the new users trough making Configure OTP a default action
  - Per user trough required actions
- Once a user is required to Configure OTP:
  - They cannot skip that step
  - And once setup the OTP cannot be removed by the user, only by a Keycloak admin
