### ISSUE TITLE
Duplicate detection should not be case-sensitive

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2185]
### Bug Description
There is a case in the db with name aaaa, bbbb and when creating another person with name AAAA, BBBB, the case aaaa, bbbb isnot proposed by the system among list of duplicate persons
### Steps to Reproduce
1. crate a case with the name names all on capital letters
2. create person in an event with the same name in small letter. System does not suggest the person in the db

### Expected Behavior
- For all character variables used in similarity, convert them to lower cases before calling the similarity method.
### System Details
* Device: web
* SORMAS version: 1,40,1
* Android version/Browser:

### Additional Information

![image](https://user-images.githubusercontent.com/12996724/82929135-7d4dbc00-9f83-11ea-939b-f23f1c127e6a.png)

![image](https://user-images.githubusercontent.com/12996724/82929249-a2422f00-9f83-11ea-9ba7-125a622d0236.png)

**Comment by bernardsilenou** [comment]
In addition the method is dependent on the order of the names: eg reverse the first and last name and method does not suggest them as duplicates always.
@MateStrysewskeSym Can we not concatenate both names to a string and parse the single string the the similarity method? I do not understand why we have this bug?

**Comment by xavier-calland** [comment]
Shouldn't the accents also be removed before the qGramsDistance calculation?
A name / first name with several accented characters risks increasing the distance and "missing" the similarity if the accents are not always entered.
I suppose that for the combined characters (œ, æ,…) there is less risk because less numerous in the same name / first name.

A normalize function like this may be useful:

```java
	public static String normalizeString(String str) {
		String nfdNormalizedString = Normalizer.normalize(str, Normalizer.Form.NFD).toLowerCase(getDefaultLanguage().getLocale());
		Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
		return pattern.matcher(nfdNormalizedString).replaceAll("");
	}
```

Similarity is based on qGramsDistance https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/person/PersonHelper.java#L44-L46, it computes the distance between 2 strings and compares it with `NAME_SIMILARITY_THRESHOLD`.
I think, that's why it's sensitive to the order of first name and last name.
To change that, the app should call `areNamesSimilar` 2 times, combining : first name + last name and then last name + first name.

Something like this :

```java
PersonHelper.
  areNamesSimilar(criteria.getFirstName() + " " + criteria.getLastName(),
  dto.getFirstName() + " " + dto.getLastName()))
&&
PersonHelper.
  areNamesSimilar(criteria.getLastName + " " + criteria.getFirstName(),
  dto.getFirstName() + " " + dto.getLastName()))
```

**Comment by MateStrysewskeSym** [comment]
@xavier-calland Good input! We'll definitely consider this!

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym @markusmann-vg Please consider this for tomorrows priority, to include it in this sprint.We planned but did not finally implement it in the last sprint.

**Comment by BarnaBartha** [comment]
@MateStrysewskeSym @markusmann-vg I would suggest updating this bug title to:
"Duplicate detection is case-sensitive" or "Duplicate detection is not case-insensitive". Current title describes the desired functionalities state not what was before the bugfix.
