### ISSUE TITLE
Add contacts to sample export

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#2207]
### Situation Description
In #1753 samples have been added to contacts and the sample grid has been updated accordingly, but what we missed is adding the contacts to the sample export.
### Feature Description
Add the needed contact fields to the sample export:
contactfirstName;
contactlastName;
contactUuid;
contactAge;
contactSex;
contactAddressId;
contactAddress;
contactReportDate;
contactClassification;
contactStatus
contactRegion;
contactDistrict;

Also make sure to rename firstName and lastName to caseFirstName and caseLastName.

**Comment by MateStrysewskeSym** [comment]
Should be done after #1158

**Comment by MateStrysewskeSym** [comment]
Review: @BarnaBartha

**Comment by bernardsilenou** [comment]
I am sorry to reopen this issue, I had and look and realized the variables are mixed up. For example there is a column on the export table for samples called "Sex of case/contact/event participant person", "Address of case/contact/event participant person". This does not make sense because it does not help the user to easily use the table after exporting it.

I suggest we use this logic fro all fields that have need merged:
1. add a column called "entity type" that the sample belong to. Categories will be: case, contact,  event participant
2. rename "Sex of case/contact/event participant person" to just sex
3. split address in to different columns
4. Fields like case region, contact region  will just be one column called "region" the is inherited from the entity type that the sample as associated to.
5. caseuuid becomes entity uuid and contain uuids for cases, contacts and event participant

@MateStrysewskeSym what do you think about this please?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Don't reopen closed issues, please. If you have change requests, open a new one.

**Comment by bernardsilenou** [comment]
Sorry, i had a document on old issue i work on yday, so was tempted to write on the same issues
