### ISSUE TITLE
Improve loading times on Merge Duplicate Cases view [Timebox: 1d]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2227]
### Problem Description
Any action selected for the system to take on the merge duplicate mode, takes a very long time before it's executed. It also slows down the system and can potentially crash the server This wasnt happening in previous versions @MartinWahnschaffeSymeda @MateStrysewskeSym

Possible approach: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2227#issuecomment-691061549

**Comment by StefanKock** [comment]
Please do not mark me.

**Comment by MateStrysewskeSym** [comment]
I think the problem here is that there are too many recent cases which has a severe impact on the loading time of the duplicate merging view.

**Comment by MateStrysewskeSym** [comment]
Review: @leventegal-she

**Comment by leventegal-she** [comment]
Review: OK

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls kindly reopen this ticket. As a matter of fact, the situation is worse off on the recent release. On clicking the merge duplicate functionality, it loads infinitely with no response and ends up crashing the live Nigerian server

**Comment by markusmann-vg** [comment]
Proposal:
Limiting the number of duplicate cases to xxx before showing the next yyy.
Add debugging/Logging to find out where the time is spent!
Some investigation is needed before being able to implement.

**Comment by bernardsilenou** [comment]
- This is similar to  #2539  in terms of "Add debugging/Logging to find out where the time is spent!"
- I think with the introduction of DOB and social security number of the person, the list of possible duplicates will not be long. Maybe we focus on improving the time factor

**Comment by MateStrysewske** [comment]
Possible approach:

* Add a table called person_similarities
* Create a method (automatically executed as a nightly cronjob) that calculates for every person that has been changed since the last execution whether its name is similar to any other person in the database and, if yes, adds the two ids to the person_similarities table
* When entering the merge cases view, call the method as well to make sure the similarities are up to date
* When searching for potential duplicates, only compare cases with persons that have a common entry in the persons_similarities table
* When the threshold is changed in the properties, the similarities have to be re-calculated

**Comment by JonasCir** [comment]
### Additional Information
Screenshots and dump of the network request which shows the problem are available on request, I cannot share them publicly.

**Comment by StefanKock** [comment]
Will be addressed by #9054
