### ISSUE TITLE
Don't show "Home or other place" in hospitalization

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2278]
### Problem Description
German health departments are confused by "Home or other place" showing up in the hospitalization tab.

### Proposed Change
Don't show "Home or other place" in hospitalization; also, probably, make sure that no previous hospitalizations are created for this option.

**Comment by Fede923** [comment]
Hi, i'm new of the project, which page or part are you referring to?

**Comment by bernardsilenou** [comment]
@Fede923 when crating a case, after entering the region, district , ,,, there is a field called health facility with a drop down option called "Home or other place" to document cases that are not in a health facility but at their home.
After creating a case at home, when you migrate to the hospitalization tab of and case, you still see hospitalization information.

@MateStrysewskeSym I think we should keep previous hospitalization and only hide the hospitalization information because a case can be at home but have a previous hospitalization. The current figure is what we have in the current system, users cant edit data for cases at home, what is the change that should be implemented now? hide the hospitalization data?

![image](https://user-images.githubusercontent.com/12996724/87885023-e5b09b00-ca12-11ea-9196-f96b1f92c2ad.png)

**Comment by MateStrysewskeSym** [comment]
This has actually already been resolved in another issue.
