### ISSUE TITLE
The day of the date of birth is not editable

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#2335]
### Feature Description
The feature that should be changed is the  `DATE OF BIRTH` displayed in `CASE PERSON` after a new case was created.

### Problem Description
![sormas-birthday](https://user-images.githubusercontent.com/20031875/84880524-e8734580-b08c-11ea-8175-95f8e437316a.png)

- [ ] The day of the date of birth is not editable with a drop down menu. 

- [ ] Also  `LETZTE AKTUALISIERUN` is missing a `G` in the German translation

### Proposed Change

1. Make the day of the date of birth editable

1. Maybe introduce a calender picker which is faster and more concise than drop down menus  

### Additional Information
Found in SORMAS Docker deployed from latest `master`.
About page says `Version 1.42.3`

**Comment by MateStrysewskeSym** [comment]
@JonasCir Unfortunately we can't use a calendar picker because SORMAS is used in African countries where people sometimes don't know their exact birth date, which makes it necessary for users to be able to only document parts of it.

I'm seeing that first and last name are also not editable. Can you edit anything else on this screen, except the two birth date dropdowns?

Concerning the translation, that might have to do with the field not being wide enough to display the whole caption. That's a general problem we're facing that we'll hopefully be able to take care of at some point in the near future.

**Comment by JonasCir** [comment]
@MateStrysewskeSym 
1. Calendar picker: Understood
1. Display space: Is there already a general issue which tracks these kinds of bugs?
1. I didn't pay attention but yes: there seem to be more sections which are not editable or buggy:

Personal Information
---
- [ ]  English translation shows `Personen-Informationen` in German as section title
- [ ] The day of the date of birth is not editable with a drop down menu
- [ ] Birthday label says `MONTH/DAY/YEAR`, however menus are ordered `YEAR/MONTH/DAY`
- [ ] LETZTE AKTUALISIERUN is missing a G in the German translation

Place of residence
---
- [ ] No possibility to edit any of the eleven fields 

Contact information
---
- [ ] Nickname and Mother's maiden name not editable
- [ ] Mother's and father's name not editable

Occupation & education section seems to be fine

**Comment by MateStrysewskeSym** [comment]
I'm not sure right now whether we have a general issue for it, but we're aware of the problem.

The reason why you're not able to edit these fields is that the case is outside the jurisdiction of the user you're using. Normally, these fields wouldn't even contain values but would be pseudonymized. However, we had to disable pseudonymization in 1.42.3 because of serious performance issues. It will likely be re-enabled in the next major release.

So this behaviour is actually expected, but seems weird right now because you're still able to see the values.

**Comment by JonasCir** [comment]
Alright :)
I was logged in as `admin`, I thought this role would have sufficient permissions to edit the fields :smiley: 
Still, it looks weird that year and month are editable but day is not, may this should be fixed @MateStrysewskeSym ?

**Comment by JonasCir** [comment]
Fore the sake of consistency :)

**Comment by MateStrysewskeSym** [comment]
@JonasCir Actually, admins aren't allowed to see or edit anything at all by default. The reason why year and month are editable is that by German law, only the day is considered personal data, but month and year are not.

**Comment by JonasCir** [comment]
The more you know thank you :)
