### ISSUE TITLE
Contact entered from the contacts menu must be linked to a confirmed case

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2337]
### Feature Description
Epidemiologically, its wrong for a contact 
1) to have no link to a confirmed case  or a probable case
           or
2) to have a link to suspect case
### Problem Description
On the contacts menu of the SORMAS platform, users are allowed to enter contacts without being forced to enter the confirmed or probable case they are linked to, and they are allowed to link a contact to a suspect case. This is why we have alot of contacts without a link to a confirmed case
### Proposed Change
On the contacts menu, the variable "case ID in external system" displayed in image A should be renamed "ID of confirmed or probable case in external system",  made compulsory and limited to confirmed or probable cases on the system. Also the search functionality on the "choose case" link as displayed in image B should be renamed "confirmed or probable case" and limited to confirmed or probable cases. This should also apply to the contacts of the import template too @bernardsilenou @tomabadaniel @MateStrysewskeSym @MartinWahnschaffeSymeda  @Chinedar 

<img width="352" alt="Image a" src="https://user-images.githubusercontent.com/50739609/84894896-810fc280-b099-11ea-873f-dabaa85eb4f8.PNG">

<img width="646" alt="image b" src="https://user-images.githubusercontent.com/50739609/84894917-8836d080-b099-11ea-8ab7-2a57951c9c3b.PNG">

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 We run into problems with systems in other countries if we restrict it like this.

The reason why it's possible to create contacts without defining a source case is that it's possible that the source case is either unknown or currently not in the system where the contact is created in. Possible situations:

* In Fiji, all people coming in from the outside via airplane are created as contacts to allow to track their health status; they can't select a source case for these contacts because there might not even be a source case in the first place.
* Also relevant for Nigeria: Person A has traveled to an area in another country that has an outbreak of an infectious disease; after they arrive in Nigeria, they are created as a contact because they might've had contact with a source case, but even if they had, the source case is definitely not in the Nigerian SORMAS system because they're living in another country. Creating the Nigerian person as a contact without a source case allows users to do contact tracing anyway.

I'd say that this feature is useful for any country that SORMAS is currently being used in. If you really don't need it, we could make it configurable whether creating contacts without source cases is allowed, but I'd like you to thoroughly discuss this with HZI and every party involved in Nigeria.

Concerning your other points:

* Renaming "case ID in external system" to "ID of confirmed case in external system" could be done via translation for Nigeria; I disagree to make it compulsory because there might not be a case in any external system that can be referred to.
* Concerning the restriction to only allow contacts to be linked to confirmed source cases: Does that mean that Nigeria is NEVER adding contacts to suspect or probably cases, even if they know about potential contacts? If that's the case, we will discuss this in our next sprint review.

**Comment by Iheanacho2027** [comment]
Ok, your points are noted and well understood. @MateStrysewskeSym could we make i request specific to Nigeria alone

**Comment by MateStrysewskeSym** [comment]
Okay, we'll refine this in the next sprint meeting!

**Comment by bernardsilenou** [comment]
@Iheanacho2027 This is a problem that an be handled by training. You have to inform the users to always create contact  through a case data not through the contact directory.
Currently, we do not have specific configurations for Nigeria so I am afraid it will not be possible to do the configuration to mentioned. I recommend that you do the translation and remind all users to always create contact through a case. I hope this can be applied as a solution for now?

**Comment by Iheanacho2027** [comment]
I agree with you guys @bernardsilenou @MateStrysewskeSym . Since there is no module for POIs, i think the current algorithm is relevant, and this isnt needed for now.
