### ISSUE TITLE
Enable manual selection of contact category [0.5]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2345]
### Situation  Description
The contact categories 1a and 1b were recently implemented for the German system (#2094 ). Based on the type of contact, the contact category is set automatically by the system. 

### Proposed Change
The user should be able to manually choose between the categories 1a and 1b whenever the respective types of contact are selected ('Medizinisches Personal mit hohem Expositionsrisiko,...', 'Medizinisches Personal mit begrenzter Exposition,...').

**Comment by MateStrysewskeSym** [comment]
As an extension to this request, as discussed in the last review, it should be possible in general to overwrite the contact category that's automatically assigned when choosing a contact proximity.

This is actually already possible, but the UI doesn't reflect it because when entering a contact, the logic to set the contact category is executed automatically. The solution to fix this issue is to not execute this logic when the contact form is opened, but only when the user changes the contact proximity manually afterwards.
