### ISSUE TITLE
Add additional Details to Events [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2391]
### Situation Description
Currently there are "social events" in the epidemiological data tab from a case. Those social events are just meantto be additional information to a case. 

### Feature Description
WEB & APP

To be able to work with events in a more efficient way we want to add additional information to the menu item "Events" and link them properly to cases. 

1.) Add to the events status Screening and Cluster, so that we have the following states: "Signal; Event; Screening; Cluster; Dropped)
2.) The "Event description" will be replaced by "Description" as we use the same form and fields for every event state
3.) Add the details and dependencies from the attached form mockup
4.) Location will be replace by "Type of place (Setting)" should be selectable from the 2 level facilties list. Example:
First Level "Medical treatment facilities".  
     Second Level "Hospital"
5.) Add a place of exposure - could be selectable from the 3 level facilties list. Example:
First Level "Medical treatment facilities".  
     Second Level "Hospital"
            Third Level (when available) => "Heiligenfeld Klinik Berlin - 12683 Berlin–Marzahn -  Brebacher Weg 15"

The address field will be automatically filled, if the 3rd. level entry is selected.
If no or not all levels of the place of exposure is selected, the user can manually add an address or remark to the field.
This will not go into the list, but is only available in this certain event.

6.) If the event's state is "cluster" we show the field "nosocomial", which can be "yes, no & unknown"
![Bildschirmfoto 2020-06-26 um 09 42 07](https://user-images.githubusercontent.com/62540178/85833017-599fb080-b791-11ea-9fff-0bb95b137aa7.png)

![Bildschirmfoto 2020-06-26 um 08 33 35](https://user-images.githubusercontent.com/62540178/85828051-c7df7580-b787-11ea-9feb-041c8ab500a5.png)

**Comment by markusmann-vg** [comment]
Migration:
"not an event " => "dropped"
"date" => "from date"

Event date:
Add "end date" checkbox, if checked then the "end date" appears to be selected

**Comment by markusmann-vg** [comment]
- [ ] "Place of exposure" as heading
- [ ] Add a comment field "Setting"

**Comment by markusmann-vg** [comment]
can be finished when  #1637 is done

**Comment by bernardsilenou** [comment]
> * [ ]  "Place of exposure" as heading

Can we not leave this out for now and add it when the refinement is complete?
We decided last time to not add "place of exposure" in this implementation.

> * [ ]  Add a comment field
> * [ ]  Extend the detailed export

**Comment by bernardsilenou** [comment]
@markusmann-vg  I have comments on some of the points:
> 4.) Location will be replace by "Type of place (Setting)" should be selectable from the 2 level facilties list. Example:
First Level "Medical treatment facilities".

"Location" remains since it is just a caption.  We replace "Type of place" with "type of place/ setting". This is just only on the form.
I recommend we do not implement point 5 in this implementation because the variable 'place of exposure' is specific to certain statues of the event.

>The address field will be automatically filled, if the 3rd. level entry is selected.
If no or not all levels of the place of exposure is selected, the user can manually add an address or remark to the field.
This will not go into the list, but is only available in this certain event

For this sprint, can we include the following amendment:
The address field will be automatically filled, if the region, district and 2nd. level entry  for the  typeofplace is selected.
If no or not all levels of the typeofplace is selected, the user can manually add an address or remark to the field.
This will not go into the list, but is only available in this certain event.

We discussed last time that adding the place of infection variable now will be confusing to user because the options are very close to those of setting, thus not include it now.

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewskeSym 
The 2 levels for  type of place (location) is mentioned in this issue but not implemented. Was is a deliberately left to be added when the facility changes will be implemented?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I reopened so that you can see the comment, If it was deliberately left out , you can then close it back please

**Comment by MateStrysewskeSym** [comment]
Type of place is handled in a different issue.
