### ISSUE TITLE
Add date of birth filter to case and contact directories [1]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2396]
### Situation Description
A few health departments have asked for this filter.

### Feature Description
Add date of birth filter to case and contact directories.

**Comment by bernardsilenou** [comment]
We can add it among the list of variables is the box: ID, name, EPID number, Facility.
I suggest we use the order: Name, DOB, ID, EPID number, facility
Since this list will grow over time with more variables, can we not also add a icon with description of all the possible varietals that  this filter can hold?

**Comment by max-hzi** [comment]
Christin asks to prioritise this as high.

**Comment by MateStrysewskeSym** [comment]
@max-hzi We'll implement it for the next release.
