### ISSUE TITLE
Implement additional values in the dropdown “type of place” list 

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2406]
### Problem Description

To allow complete and adequate description of events, additional values have to be implemented in the “type of place” lists. 
Those lists are however not configurable in the current SORMAS version and appear as being enum type in the code.

### Proposed Change

New list proposed 

-	Home* 
-	Extended family environment
-	Public or private : temporary people gathering (parties, ceremonies …)
-	Nurseries
-	School and university environment
-	Institutions providing accommodation and care to elderly and dependent persons
-	Institutions providing care to people with disabilities
-	Hospitals*
-	Institutions for social accomodation and integration
-	Specific communities (vulnerable people, travelling communities, migrants, …)
-	Insitutions providing care for homeless people
-	Penal institutions
-	Professional environnement
-	Means of transport (airplane, ship, rail)
-	Small size geographical unit (suggesting common exposure)
-	Other*
-	Unknonwn*

[] * Among the following values, those marked with a * are already available in the current SORMAS version.

**Comment by bernardsilenou** [comment]
@carolinverset  Thanks for submitting this informative issue. It is exactly the same request from the German users and it is under implementation in this sprint and will hopefully be in the next release. There are more additional features that will added to events that are not mentioned in this issue. To have an overview, please read issue #2340 and the associated issues.

**Comment by bernardsilenou** [comment]
@carolinverset  Please have a look at the excel table i commented on June 23, 2020 to issue #2340 and let us Know if there is any vital facility missing

**Comment by MateStrysewskeSym** [comment]
@carolinverset The "Type of place" will likely be replaced by facility types in the future as we're currently implementing a lot more of them that can also be associated with physical addresses. Many of the types you've listed will be part of that. For all the other ones, @bernardsilenou please check with your colleagues whether they fit one of the already defined facility types or whether we need a decidated new one for them.

@bernardsilenou This will not be in the current sprint because it's a very extensive issue that takes quite a lot of time. We hope to deliver it in the next one.

**Comment by OlivierLeuci** [comment]
@MateStrysewskeSym @bernardsilenou We've done a translation and we'll see if we can manage to find our needs in your list. Is it possible to propose/add some new values?

**Comment by bernardsilenou** [comment]
@OlivierLeuci of course you can add. However we do not want the list of "facility types" to be infinitely long, so if there is a facility type you know is highly linked to a case or event and is not mentioned in our list, please add it to the excel table and we can discuss it in the next meeting. Since the team is programming this now, it will be good to do it now also.

**Comment by carolinverset** [comment]
@OlivierLeuci @bernardsilenou 
If it's possible, we want to add the follow list : 

- Institutions providing care to people with disabilities
- Specific communities (vulnerable people, travelling communities, migrants, …)
- Insitutions providing care for homeless people
- Small size geographical unit (suggesting common exposure)
- Structure of child welfare

**Comment by bernardsilenou** [comment]
@carolinverset  These are mu comments on the categories to know what you think about. we can discuss this further in the meting tomorrow also.

> * Institutions providing care to people with disabilities 
This can map with Rehab facilities

> * Specific communities (vulnerable people, travelling communities, migrants, …)
 This can be mapped with "Others" you mentioned more than one type of facility: vulnerable people, travelling communities, migrants

> * Institutions providing care for homeless people
This maps with "mass accommodation" under residences. If this match is not good, we can add it as a new facility type. Which name can be use please?

> * Small size geographical unit (suggesting common exposure) 
This will correspond with many of the categories under Leisure, for example:  Big gathering (e.g. stadion, festival), Zoological garden, animal park, etc

> * Structure of child welfare 
This is represented by "Child day care" or Kindergarten/After school care found under "care facilities" category

**Comment by carolinverset** [comment]
@bernardsilenou @OlivierLeuci 
As agreed yesterday, you will find attached the excel file specifying the modalities of the typeofplace variable that we wish to add
[Prop_typeofplace_sormas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4865605/Prop_typeofplace_sormas.xlsx)

**Comment by MateStrysewskeSym** [comment]
@carolinverset Please provide the list in English.

**Comment by carolinverset** [comment]
@MateStrysewskeSym @OlivierLeuci 

the translation into English of the three modalities that we wish to add is in column F. Best regards

**Comment by MateStrysewskeSym** [comment]
@carolinverset Oh, sorry! My Excel opened the file starting with column G for some reason. Thanks!

**Comment by MateStrysewskeSym** [comment]
@carolinverset 

* "Structure of child welfare" makes absolute sense to us.
* Specific communities are possibly a bit problematic because it doesn't make much sense as a facility type; i.e., we'd prefer to leave this out and handle it by selecting already existing options and specifying the exact community with a "Setting" text field; is that okay for you?
* "Institutions providing care to people with disabilities": There will also be an "Other medical facility" option; would this be sufficient for your needs? If not, can we find a more generic category that will also include other care facilities or, if not, could you find a shorter description (ideally a single term) for this category?

**Comment by carolinverset** [comment]
sorry for the late response. I agree with your proposals. Thanks !
