### ISSUE TITLE
Unify install scripts

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#2427]
### Feature Description
Integrate `/sormas-base/dev-setup/server-setup-dev-docker.sh` back into `/sormas-base/setup/server-setup.sh`
and clearify setup documentation

### Problem Description
https://github.com/hzi-braunschweig/SORMAS-Project/pull/2331 has duplicated the `server-setup.sh` script.
Having duplicate install scripts for different purposes is error prone when it comes to maintainace.
Also, the installation procedures must be well-documented to facilitate developer onboarding and rollout.
Requiring the latest release artifacts in order to setup a development system has always been cumbersome.

### Proposed Change
Incoroprate use cases that lead to the secession of `/sormas-base/dev-setup/server-setup-dev-docker.sh` back into `/sormas-base/setup/server-setup.sh`.
If needed, `server-setup-dev-docker.sh` could call `server-setup.sh` and control it via environment variables.

Setting up development servers directly from the workspace should be the preferred approach.

The documentation needs to be clearified.
For development systems, only the setup directly from the workspace should be described
(`DEVELOPMENT_ENVIRONMENT.md` should not mention `SERVER_SETUP.md`).
`SERVER_SETUP.md#postgres-database` should give specifics concerning Docker.
Maybe a docker-compose file could be helpful.

### Possible Alternatives
Place a reminder in `server-setup.sh` that `server-setup-dev-docker.sh` has to be kept in sync

#### Aspects to consider:
- SORMAS deployment
  - Machine
  - Container
- System type
  - Productive
  - Demo
  - Development
- OS
  - Win
  - Linux ( /Docker)
- Source
  - Workspace
  - Release
- Postgres
  - Local
  - Remote (/Docker)

**Comment by jabrandes** [comment]
#2375 should provide a fix for most of that :)

**Comment by MartinWahnschaffe** [comment]
It happened as expected - server-setup-dev-docker.sh is no outdated, because it's not actively being used.
sormas-base/server-setup.sh is already taking care of the following things:

1. Local dev system vs. actual server
2. Demo/test vs. production system
3. Linux vs. Windows
4. Authentication provider: SORMAS vs. keycloak on docker (including keycloak-setup.sh) (#2848)
5. Postgres: Existing or new database (#4601)

What remains:

* For dev systems it should be possible to run the server-setup.sh from a local workspace instead of having to download the latest release
* Install and use postgres in a docker container - could be extracted from https://github.com/hzi-braunschweig/SORMAS-Project/pull/2375/files#diff-8ffce37680eadaf828c804cc978a3e5a7a2a825f27c89101417c1776d5cc5c9e but would need to be modified to work with the keycloak docker and probably some other aspects.

From my point of view these changes are optional and not something that we will realistically do at this point.

We should do the following though:

- [ ] Delete the dev-setup folder with the server-setup-dev-docker.sh

**Comment by StefanKock** [comment]
#11633 will take care of the deletion.
