### ISSUE TITLE
Jurisdiction issue if cases are hospitalised outside the district/ region they reside (Germany)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2430]
### Problem Description
German health departments are responsible for all the cases which are registered at the local municipality. I. e. this means that the health departments need to manage all cases registered at addresses within their district/ Landkreis. This jurisdiction is untouched even if the case is hospitalised in a different district (which is often the case for communities near borders).

Let's imagine the health department Berlin Mitte. They have several users, and these are assigned to the region Berlin (refer to 'edit user' window in user management). We now have a new case in Berlin (region) / SK Berlin-Mitte. So our health department Berlin Mitte is responsible for this case. For different reasons, the case is referred to a hospital outside of their jurisdiction, lets say to Hospital X in Potsdam, which is located in the region Brandenburg/ district SK Potsdam. The case will now no longer show up for other users from Berlin Mitte, as Sormas presumably assigns the jurisdiction to Brandenburg/ Potsdam. 
This is a major issue, as Berlin Mitte is still responsible for the case as needs to track the case in Sormas.

The user who created the case in Sormas is able to keep track of the case, but it does not show up for the other users, which is required.

What is the best way to appoach this? The challange is that during case creation, Sormas asks for region/ district/ health facility. By default, health departments would choose their region and district because they usually work with the home address vs. the location of the hospital.

We also try to keep health departments from creating dummy health facilities.

Further comment from Christin: : It must be possible that a Gesundheitsamt can do the Follow-Up BASED on the place of residence. If that is the case, the GA is able to do the follow up, even if the case or contact is in a hospital which is in another landreis/district.

**Comment by bernardsilenou** [comment]
@max-hzi The infrastructure data (health facility, region, district) in the system is just to make sure the case is not counted twice.
There is a  long time issue I know exist thats permits us to share a case not with the whole country but with a particular user, region, district, or user role. This will permit the case thath has been moved to Potsdam to also be available for editing in Berlin Mitte but will not count in the satistics of cases in Berlin Mitte.

The user rights in the system do not use place of residence of the person associated to the case, I do not think we can use this option because it has a lot of limitations.
I think one solution we can begin with is implementing the possibility to "share a case with a district and a user"

**Comment by max-hzi** [comment]
> This will permit the case thath has been moved to Potsdam to also be available for editing in Berlin Mitte but will not count in the satistics of cases in Berlin Mitte

Well thats not desirable, as the department in Berlin Mitte is responsible for the case and also reports the case.


> The user rights in the system do not use place of residence of the person associated to the case

This is a major issue as the health departments in Germany usually determine responsability by address (i.e. where the case is registered)

**Comment by kwa20** [comment]
Will be handled in #3254
