### ISSUE TITLE
Similarity threshold from properties file is ignored

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2443]
We're currently using the hard-coded PersonHelper.NAME_SIMILARITY_THRESHOLD instead of the value that can be configured in the sormas.properties file. This needs to be changed.

**Comment by bernardsilenou** [comment]
The default value for the threshold in the sormas.properties file is empty on a newly setup server. 

@MateStrysewskeSym I suggest we set the default value to  be restrictive. In my comment yesterday to issue #2178, a suitable default value i found was 3. I do not know how this relate to the threshold in sormas.properties since it is between 0 and 1.
Is there another method added to the default q gram method? 
Please have a look at my comment to #2178  and clarify the difference between the retained values, mine ranges from 0 to infinity (0 = perfect sting match).
