### ISSUE TITLE
Network diagram should be reactive in terms of date of report [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2476]
### Feature Description
When the date of report is chosen, the network diagram does not filter accordingly
### Proposed Change
-When report data is supplied by the user, the corresponding contacts should be plotted, not all contacts in the db.
- If contacts are too many to be plotted (eg > 5000), user should be warned and asked to either choose a smaller time window (show actual number of contacts) or continue with a warning that it might put down your browser.
- Display network by default using the last 30 days from current date.
- Do not display nodes without edges: this corresponds to contacts without a source case or cases without a contact
### Additional Information
Version: 1,44

**Comment by MateStrysewskeSym** [comment]
If the network diagram should adhere to the date filters selected in the dashboard, we can't use the last 30 days as default because the dashboard's default time period is the current week. Also, please open a separate issue for your third request (don't display nodes without edges) as it's a totally different topic than this change request.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Super, 1 week default is perfect. Thanks

**Comment by bernardsilenou** [comment]
I added point 3 to  #2323

**Comment by bernardsilenou** [comment]
- The firs step would be to filter contacts based on dates entered by user on UI, then parse to the R script as usual.
- By default we parse only contacts fro the last week
- further refinement will be handled in #2323
