### ISSUE TITLE
Delete compared to date on contact dashboard

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2477]
### Feature Description
Compared to date is needed only for the surveillance dashboard.
### Proposed Change
- Hide the "compared to date" on the form for contact dashboard
- add "report date" near or inside the date cell for users to know the type of date that is used. The description in exclamation icon is not visible enough.

![image](https://user-images.githubusercontent.com/12996724/87327388-4d0eac80-c534-11ea-8b17-e4d099925003.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou There are elements on the dashboard that require the date comparison, e.g. the Visits section on the right.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  permit me to reopen this so that we can discuss more on it. I had no idea that we had a backend method to compare visits across time. 
Since visits are dependent on number of contacts, I think the values computed are not comparable across time. Just as we do for cases, it would be much better to compare but the number of contacts across time which  is not also all that helpful since it depends on number of cases.
If you do not have any strong reason why we need to keep it then I will suggest we take it out.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Your proposed change would require a redesign of the Dashboard because, like I said, we do use the comparison date for at least the rightmost column that you can see in your screenshot. Therefore, your request right now can not be implemented. Apart from that, I still think that having a comparison date makes a lot of sense for the contact dashboard as well because it still allows users to compare the current situation to the same time period last year, the month before, etc., which especially in the current Covid-19 situation would be very helpful e.g. to find out how well people are behaving in terms of limiting their contact with other people.

**Comment by bernardsilenou** [comment]
OK, i also think it not that important for now. I understand you.
