### ISSUE TITLE
Arbeitgeber erfassen

### ISSUE THREAD

**Issue by tobiasschellhorn** [hzi-braunschweig/SORMAS-Project#2480]
### Situation Description
Die Angabe des Arbeitsgebers ist ein wichtiger Anhaltspunkt für die Kontaktnachverfolgung. Zudem ist es über den Arbeitgeber möglich die Häufung von Fällen zu erkennen.
(siehe Fall Tönnies)

### Feature Description
Die Möglichkeit den Arbeitgeber aus einer Dropdownliste auszuwählen, ist dieser dort nicht vorhanden, dann kann man ihn dort direkt anlegen.
Angabe mit Adresse und Kontaktdaten wäre super.
Wichtig ist nach diesen Angaben später suchen und filtern zu können.
### Possible Alternatives
Ein Freitextfeld für Arbeitgeber
### Additional Information
Eine ähnliche Funktion gibt es schon für Gesundheitseinrichtungen.
Schlachtbetriebe z.B. Fallen hier nicht drunter,

**Comment by MateStrysewskeSym** [comment]
@tobiasschellhorn Hey! Please use English when communicating over GitHub to make sure that everyone associated with the project (or anyone else, since it's an open source project) is able to understand you.

This is mainly covered by a number of other issues we're currently working on. E.g. we're introducing many new facility types for which facilities can be created with a location, businesses being one of those.
