### ISSUE TITLE
ContactServiceTest.testGetAllRelevantContacts fails regularly on Travis CI

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2552]
### Bug Description
This exceptions happened on different feature branches in Travis CI, wher we were not working on this feature.

```
Tests in error: 

  ContactServiceTest.testGetAllRelevantContacts:114 » OutdatedEntity EpiDataDto ...
```
```
Tests in error: 

  ContactServiceTest.testGetAllRelevantContacts:122 » OutdatedEntity EpiDataDto ...
```

Both times it was `getContactFacade().saveContact(contact1);` after changing some data.

https://github.com/hzi-braunschweig/SORMAS-Project/pull/2536
https://github.com/hzi-braunschweig/SORMAS-Project/pull/2540
https://github.com/hzi-braunschweig/SORMAS-Project/pull/2546
https://github.com/hzi-braunschweig/SORMAS-Project/pull/2551

### Steps to Reproduce
Unknown. It did not happen on my maschine running this test alone or all sormas-backend tests.

### System Details
* SORMAS version: 1.46.0-SNAPSHOT

**Comment by StefanKock** [comment]
I ran into this after I changed this:
```
		Thread.sleep(2_000L);
		getContactFacade().saveContact(contact1); // line 114
		Thread.sleep(2_000L);
		getContactFacade().saveContact(contact2); // line 115
```

In constantly fails on the next `getContactFacade().saveContact(contact1);` in line 122.

**Comment by MartinWahnschaffeSymeda** [comment]
Explanation what is happening:

The dto comes with a change date that is used to check against the entity whether the dto is outdated or not.
The "save"-method does not update the passed dto, instead it returns a new one. This means the passed dto will still have the old change date.
In the unit tests the passed dto is re-used in another "save"-method call.

Why is this working in most cases?

The change date validation method (DtoHelper.validateDto) comes with a tolerance of 1 second. Since most unit tests will take less time, the validation does not fail here.

I think we introduced this to account for missing precision in the change dates exchanged with the mobile app.

Looking at this now I'm wondering on whether this tolerance makes any sense. The missing precision of the android is not about milliseconds, but about nano seconds.
