### ISSUE TITLE
Event officers can't view or edit samples

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2557]
### Bug Description
Gesundheitsamt Berlin:
"we have tried to use the new feature that allows you to assign a sample to an event participant without having to make a case out of it. Now no test result can be added to the created sample.
The sample and the complete input is greyed out. 
This occurs both with the person who created the sample (monitoring line, event representative*r) and with me (administrator, contact line, monitoring line)."

### Expected Behavior
Adding a sample to an event participant that is not a case should be possible

**Comment by StefanKock** [comment]
On which version is this defect seen?

**Comment by bernardsilenou** [comment]
I tested on version 1.45 and all works fine

**Comment by markusmann-vg** [comment]
1.44.3

We found the issue - jurisdiction filtering problem.
With national user it works fine

**Comment by MateStrysewskeSym** [comment]
I don't necessarily think it's a jurisdiction filtering problem, more like a user rights problem. Event officers aren't allowed to edit samples because we didn't have samples for events in the system so far and forgot to change the user rights when we introduced them. I'll add the respective user rights for the role.
