### ISSUE TITLE
Import function records case as error even after skipping or picking an existing case or contact

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2567]
### Bug Description
When a user tries to import a case with the same EPID number as an already existing case, and selects "pick an already existing case" or "Skip", the system records it as an error. This shouldnt be so because both options on "pick an already existing case" and "Skip" should instruct the system to completely ignore the about to be imported case or contact
### Steps to Reproduce
1. Put on an import template, a case having the same name, Epid number, age and sex
2. Attempt running an import on SORMAS
3. On duplicate detection, select "pick an already existing case" or "Skip"
4. Check your error log or document

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@Iheanacho2027  whats ur version? I could not reproduce it

**Comment by bernardsilenou** [comment]
I used 1,45 and all went well

**Comment by Iheanacho2027** [comment]
Oh wow, we are still on 1.43.2. We decided to hold on with the upgrade due to app issues experienced in 1.44.0. So far I think it's safe to upgrade to 1.45.0

**Comment by ChristopherRiedelSymeda** [comment]
@Iheanacho2027 Is this still an issue than?

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls reopen this ticket. This applies in 1.45

**Comment by bernardsilenou** [comment]
The reason is because epid number is not used in duplicate case detections and also not a required filed when creating a case, But system only retains unique apid numbers per disease.
Correction:
- If duplicate case is suggested with the same epid number and user click on save or merge, do not count it as error and do not import the new case.
- If duplicate case is suggested with the same epid number and user decide to create a new case,  count it as error and import the case. This case will then have a warning exclamation mark on the epid number field as usual.

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls any plan for this?

**Comment by bernardsilenou** [comment]
@Iheanacho2027 I tested with 1,47,1 and could not reproduce the error. Please test and let us know is all if fine on your system also

**Comment by bernardsilenou** [comment]
could not reproduce the error with newer versions of the application
