### ISSUE TITLE
Fix case creation prompt when saving positive pathogen tests for event participants

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2582]
### Feature Description
If a case of disease X has the first positive lab result registered for disease Y, the final lab result variable is updated to positive. When a subsequent positive lab result is registered for disease X, the final lab result if not updated and thus automatic case classification.
### Proposed Change
- For all updates of final lab result variables, the disease of case sample is associated to, case to which contact is associated to,  event which the sample of the event participant is associated to, must be the same as disease of lab result.
- If diseases are the same, ask if user want to update final lab result each time a new result is saved
- If different, document the result but do not update final lab result

- This is important because the final case result variable is selected from one of the final lab result of samples associated to the case.
### Additional Information
- We can implement this issue together with #1860

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Are you sure you didn't mix things up here? If a positive pathogen test for a different disease than the disease of the tested case is created, the test result is not updated to positive, instead the user is asked whether they want to create a new case for the tested disease.

I see that it's not working as expected for event participants, but for cases it's fine.

**Comment by MateStrysewskeSym** [comment]
Solution: When saving a positive pathogen test on an event participant with a different disease than the event's disease, ask the user whether they want to create a new case for the event participant, but also notify them that the case will not be associated with the event since the diseases are different. If the event does not have a disease assigned, still associate the new case with the event.

**Comment by bernardsilenou** [comment]
> Solution: When saving a positive pathogen test on an event participant with a different disease than the event's disease, ask the user whether they want to create a new case for the event participant, but also notify them that the case will not be associated with the event since the diseases are different. If the event does not have a disease assigned, still associate the new case with the event.

This sounds good.
No matter the decision of the user, i think we should not set the finial lab result of the sample to positive as long as the diseases is not the same.

**Comment by vlad-ciucescu** [comment]
Regarding the samples associated to event participants, these will be transferred to the new case, without associating the event to the case. 
TBD: what happens if a sample contains pathogen tests for multiple diseases? E.g. COVID-19 sample with 1 positive test for COVID-19 and 1 positive test for Cholera, will the whole sample be transferred to the new Cholera case?

**Comment by bernardsilenou** [comment]
@vlad-ciucescu Yes, transfer whole sample. The only thing we need to maintain is that for actions like:
-converting event participant to case
-converting contact to case
-change case classification to "confirmed case", 
etc
disease of case == disease of sample result.
