### ISSUE TITLE
Add Age entry option rather than Date of Birth while entering the case (New-case> entry detail (Age))

### ISSUE THREAD

**Issue by d1pen** [hzi-braunschweig/SORMAS-Project#2606]

**Comment by bernardsilenou** [comment]
@d1pen The initial form when creating a case is just a minimum data collection form. If you do not know only the age of the case person, while creating the case, do not enter the dob (since you do not know), save the data and latter go to the case person tab, you will then have the option to enter the age and more data you wish. See picture attached:

![image](https://user-images.githubusercontent.com/12996724/89551603-6b9e5580-d80b-11ea-9b4c-53297397017a.png)
