### ISSUE TITLE
Consistent use of Java 11

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#2612]
### Problem Description
SORMAS appears to use Java 11. The problem is that some places in the documentation still mention Java 8, the SORMAS build fails for me using `openjdk-11` and the CI pipeline still runs Java 11.

### Proposed Change

- [x] Update docs
- [x] make build for plain `openjdk 11` pass
- [x] Upgrade CI pipeline to Java 11

**Comment by MartinWahnschaffeSymeda** [comment]
Good point. The PR also looks good. Just one request:

We want to stay backwards compatible for some time, so SORMAS still compiles against Java 8. I think it still makes sense to use the Java 11 openJDK on developer systems, but I'd suggest to:

- [ ] add a note to SERVER_DEV_SETUP.md that makes clear the only Java 8 language features can be used since the system still compiles against Java 8.

The sormas-api project compiles against Java 7, since Android still has only partial support of Java 8 language features.
