### ISSUE TITLE
[SORMAS2SORMAS] Manage Ownership 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2628]
### Feature Description
Add functionality & option of handing over the ownership 
    Remark: Once transferred, the dataset is readonly in the sender’s system

**Comment by MateStrysewske** [comment]
It's no longer possible to edit created contacts in the mobile app because when determining whether the "edit" icon should be shown, "isOwnershipHandedOver" is always consulted first and that is by default false for new contacts.

This might also affect other entities, e.g. cases - I haven't tested that.
