### ISSUE TITLE
Add reporting user to the event download and to event view directory

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#2637]
### Feature Description
The event module needs to show on the event directory, the reporting user, for ease of data monitoring
### Problem Description
The event export and directory does not have reporting user at the moment. Need to include this.
### Proposed Change
Add reporting user to the event export as well as to the event directory view

**Comment by bernardsilenou** [comment]
@Chinedar We do not show reporting user to any of the directories, so of we now add reporting user, then what should be taken out? because the screen is full

For export, I thinks is valid to add but we should not add by default because this is sensitive and personal data of the workers. Maybe add a check box or use the custom export module (exist for cases only).

**Comment by VitaliHZI** [comment]
hello @bernardsilenou  and @Chinedar the reporting User is already added to event export.
Can we close this issue? 

BR 
Vitali

**Comment by bernardsilenou** [comment]
Already implemented
