### ISSUE TITLE
Status is not persisted in the import of contacts 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2641]
### Bug Description
Problem: We want to import (CONFIRMED) contacts with the status Tracking completed (COMPLETED), and the status dropped (DROPPED), because the isolation time is already over. 
With a few test entries we then noticed that the information in the csv (COMPLETED and DROPPED) is overwritten by SORMAS and is displayed in Sormas as FOLLOW_UP (in tracking) and ACTIVE (active contact). 

### Steps to Reproduce
1.see problem

### Expected Behavior
The imported values must be adopted and not overwritten by the import process of SORMAS?

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
I think this is caused by the fact that completed means there is a followup visit registered on the followup until date.
While implementing this issue, I suggest we also implement issue #1855. Contacts status is set to dropped when followup is completed. This is not right because all contacts will definitely become dropped after 14 days. Just as in cases, we should use 'dropped' to mean 'discarded'.
