### ISSUE TITLE
[FRENCH TEAM] Handle follow-up visits when merging a case

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2652]
### Feature Description
#1886 has added follow-up visits to cases.

### Problem Description
The process of merging cases has not been adjusted to this yet.

### Proposed Change
Make sure that follow-up visits of a cases or correctly handled when merging them.

**Comment by bernardsilenou** [comment]
@markusmann-vg  @xavier-calland is working on this in this sprint

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  This is the solution we decided today we merging, please comment it you prefer otherwise:
- Combine visits from both cases using report date. This may result to duplicate visits but it better than deleting or cloning
- We show and colour only last visit on the overall followup table based on visit date
