### ISSUE TITLE
Surveillance supervisor user account shouldnt show region as part of location attribute filter in statistics menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2791]
### Feature Description
Currently in the statistics section, a surveillance supervisor can view statistical data from other regions outside his jurisdiction as the location attribute filter includes region as shown by the arrow in the image below. The location attribute filter for a surveillance supervisor should be "District/Community/Health Facility" as the region should only be that of the surveillance supervisor

![image](https://user-images.githubusercontent.com/50739609/92046072-0ee67a00-ed7a-11ea-9144-eefaf4fdcb5e.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou Do you agree with this? In my opinion, the statistics should generally be open for anyone because they don't contain any personal data.

**Comment by bernardsilenou** [comment]
@Iheanacho2027 I agree with Maté. The initial goal was to permit users to have an idea of statistics in other region or districts without seeing sensitive data. That is also the reason why data export is not possible in the statistics section.
If you are fine with this please signal so that we close the issue.
Thanks

**Comment by Iheanacho2027** [comment]
This is fine then
