### ISSUE TITLE
Case Directory | Filters | Table Header overlapping with other rows

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2812]
### Bug Description
Header fields get misaligned and overlapped.

### Steps to Reproduce
1. Login to Test environment https://test.sormas.netzlink.com/ as one of the users 
2. Go to Cases
3. Click on Show More Filters
4. Scroll down to the table and then scroll horizontally to the end 
5. After the Completeness Column is being displayed, scroll inside the Table. 

### Expected Behavior
The scroll functionality should work as expected and the header and rows should be readable in the cases table

### Actual Behaviour
 The Header section of the table containing "Date of Report", "Quarantine End", "Follow-up Status", "Follow-up Until", "Number of Visits" and "Completeness" get overlapped with other rows from the table.
### Screenshots
![CAseDirectory_FilterBy_Follow_up_headerTransparnecy](https://user-images.githubusercontent.com/70562142/92243244-d655b600-eec9-11ea-9b3b-ff7820e2e8df.jpg)

### System Details
* Device: Windows OS
* SORMAS version: 1.48.0-SNAPSHOT
* Android version/Browser: Chrome

**Comment by Seal33** [comment]
This appears to be the same issue as #2853

**Comment by Seal33** [comment]
The issue seems to only appear if side-scrolling in the table is enabled and necessary. In that case, only those lines "out of sight" when scrolled all to the right are affected. If your screen is wide enough to show the whole table, the bug will not appear.

The issue seems to appear across all tables. Usually it isn't noticed though because most tables aren't wide enough for sidescrolling to be an issue.

**Steps to reproduce:**

1.   Go to any table view
2.     Make your window small enough so that a side-scrolling-bar appears
3.     Scroll to the right and then down, so that table headers and content overlap

**System Details**

- Linux OS (Ubuntu)
- SORMAS version 1.50.0-SNAPSHOT
- Browser: Firefox

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
