### ISSUE TITLE
Statistics > Daily quarantine statistics for Cases and Contacts [3]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2832]
### Situation Description
Statistics based on quarantine and conversion for Cases and Contacts is required for daily reporting and monitoring purposes to the BAG.

### Feature Description
The possibility to generate the following statistics is requested:

- How many people (cases) are "today" (or on a calendar day X), in quarantine?
- How many people (contacts) are "today" (or on a calendar day X), in quarantine?
--
- How many people (cases) were newly placed in quarantine in the last 24 hours (or on a day X)?
- How many people (contacts) were newly placed in quarantine in the last 24 hours (or on a day X)?
--
- How many people have been converted from contacts to cases in the last 24 hours (or on a day X)?
--
- ~~How many people passed away (died) on day X?~~ :heavy_check_mark:
Already possible - 
Cases > Case Directory > Show more filters > Present condition of Case selection box: [Deceased] > Apply filter > Date: X to X (select same day) > Apply Date Filter > Apply filter (again)
Statistics > Add Filter: Case Outcome > Add filter: Report Time: Date Range: "From" and "To" dates the same > Generate

### Possible Alternatives
Where not possible on the Statistics page, introducing filters on the Cases and Contacts directories to see totals and details of individuals involved could achieve the same outcome.

**Comment by markusmann-vg** [comment]
How many people have been converted from contacts to cases in the last 24 hours (or on a day X)?
How many people (cases) are "today" (or on a calendar day X), in quarantine?
How many people (cases) were newly placed in quarantine in the last 24 hours (or on a day X)?
=> will be shown on the Surveillance Dashboard

---

How many people (contacts) are "today" (or on a calendar day X), in quarantine?
How many people (contacts) were newly placed in quarantine in the last 24 hours (or on a day X)?
=> will be shown on the Contacts Dashboard

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske  just a minor comment:
This request is in the direction of the collection of issues we have in the pipeline on predefined reporting, e.g #904. Instead of calculating the indicators using fixed dates as defined here, we should have date as a parameter and use default value as the previous day. For some diseases like TB, it does not male sense to look at contacts under quarantine in last 24 hrs while for others like covid it does. Even for covid alone, some countries will need to report these indicators for last 3, weekly, monthly, etc

**Comment by bernardsilenou** [comment]
Additional specifications:
Consider this point "How many people (contacts) are "today" (or on a calendar day X), in quarantine?"
Since for each indicator, we need to report both counts and proportions, the denominator need to be specified and it is also time dependent.
Proposition:
1. User need to first choose the first time interval (t1) based on report date of the entity (case, contact, event), this filter will give us the data with denominator N. t1 is our current default dashboard filter.
2. Users then need to choose the second time interval (t2) (""today" (or on a calendar date interval)") based on the management (quarantine, isolation, converted to case, ...) date. We then use previous day as default here but should be editable. t2 should be restricted to fall within t1 only.
2.1 The date used for t2 should also depends on the disease management activity, for example for quarantine we can use end date  (not system date that this activity was registered in sormas in order to be be consistent with followup chart and retrospective data entry). Similarly, for isolation, use date of isolation, for contact that converted to case, use date of report of the resulting case.

**Comment by bernardsilenou** [comment]
> How many people have been converted from contacts to cases in the last 24 hours (or on a day X)?

Number (Proportion) among the cases that resulted from contact. Denominator = Number of cases, not number of contacts 
does this mean we will have this proportion twice on dashboard: converted to case and converted to case in last 24 hrs?
There is an indicator on the contact dashboard called "New cases not previously known to be contact" that was design for this indicator but was not shown on surveillance dashboard and was wrongly named. Please use this same indicator and migrate it to surveillance dashboard and call it "Number of cases that resulted from contact"

> How many people (cases) are "today" (or on a calendar day X), in quarantine?

I also have the same comment on two date issue here, do we show total proportion on quarantine among the cases filtered and additionally show the same proportion on quarantine in last 24 hrs?
> How many people (cases) were newly placed in quarantine in the last 24 hours (or on a day X)?

> => will be shown on the Surveillance Dashboard
> 
> How many people (contacts) are "today" (or on a calendar day X), in quarantine?
> How many people (contacts) were newly placed in quarantine in the last 24 hours (or on a day X)?
> => will be shown on the Contacts Dashboard

**Comment by bernardsilenou** [comment]
@markusmann-vg sorry for all the comment, they are not sorted because when i read the issue a lat of stuffs came to my mind. We can use the last 24hrs as initially specified for t2 and only think of making it configurable when we have the management dashboard. https://github.com/hzi-braunschweig/SORMAS-Project/issues/904

I also think for each indicator on the dashboard, we should show the overall proportion + last 24 hrs. When we will have the management dashboard, we can then migrate all indicators on last  24 hrs there.

**Comment by raghupola-vg** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2944

**Comment by raghupola-vg** [comment]
#2944

**Comment by sergiupacurariu** [comment]
[#2832 - quarantine selection logic.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5266328/2832.-.quarantine.selection.logic.xlsx)
