### ISSUE TITLE
“Event” printing function

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2906]
### Situation Description
Sormas does not offer a print function. It would be interesting in that it allows information to be transmitted to a third party without giving them access as a user. The print function would be particularly interesting for tracking events and associated actions.

### Feature Description
Develop a function allowing users to print an HTML page from the information entered for each event:

- title of the event 

- event identifier

- event status

- event date

- description of the event

- Region, department and municipality of the event

- Community Contact Person

- For each action :

Title of the action
Description of the action
Creation date
Date of last modification
Status of the action

### Additional Information

@xavier-calland @bernardsilenou

**Comment by xavier-calland** [comment]
@ftavin

**Comment by JonasCir** [comment]
@syntakker @markusmann-vg Maybe we can build this on top of the template engine we are currently working on?

**Comment by bernardsilenou** [comment]
@markusmann-vg I did not know we already started implementation. Please share the logic so that we can have the same design and method for other entities too. Do we need to call or there is already an issue about the specification?
The french team team has this on their plate for this sprint, so its good we quickly share ideas
Thanks,

**Comment by JonasCir** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2696 is the issue, it is in the current sprint. I don't mind a call to see how we can share functions :D

**Comment by syntakker** [comment]
@bernardsilenou We are working on document generation for quarantine orders in this branch:
https://github.com/ImisDevelopers/SORMAS-Project/tree/feature-2696-document-generation-quarantine

Document generation is based on XDocReport using the velocity template engine.
We read docx templates and generate docx documents. Currently I'm working on a generic mapping of variable names to entityDto values, such that, e.g., "case.person.firstName" maps to the respective value in the caseDto according to the Data Dictionary.

The approach is intended to be generic and work for all entityDtos, so the code can be extended to further workflows including documents.

**Comment by bernardsilenou** [comment]
@syntakker This sounds good. Generic approach is the way to go.
There is also the need to print the summary of followup (or clinical course) for cases, contacts, event participants, .... This generic approach will be very helpful.
@JonasCir I suspect issue #2696 will be done in this sprint, or it is a multi-sprint issue?
@carolinverset Since this similar issue is currently under development, I think is is better for the French dev team to wait until it is completed before extending the feature to events. What do you think please?

**Comment by syntakker** [comment]
@bernardsilenou I think I will have a working example for document generation from EntityDto data by Monday.
For the complete version we have to see if we can finalize everything in this sprint, but we surely get it done in the next sprint.

**Comment by bernardsilenou** [comment]
@syntakker Many thanks. I think it will be fine to wait until it is done and then the french dev team can then build on a working module. @carolinverset hope this is fine by you?

**Comment by syntakker** [comment]
@bernardsilenou the working example is ready and can be seen in said branch https://github.com/ImisDevelopers/SORMAS-Project/tree/feature-2696-document-generation-quarantine .
We start from a docx template and a root Dto, where variable naming is generic and follows the SORMAS_Data_Dictionary. So if the root is `CaseDataDto`, `case.person.phone` references the phone number of the case's person.
For a start on document generation, see test cases `TemplateEngineServiceTest` and `QuarantineOrderFacadeEjbTest`, for accessing Dto properties see `EntityDtoAccessHelperTest`. 
We've built a preliminary button in the Case Information page and prepared a docx template in the cargoserver setup, so if you start the cargoserver you can generate a quarantine order from a case in the db.
All this is WIP, feedback is appreciated.

**Comment by carolinverset** [comment]
> @syntakker Many thanks. I think it will be fine to wait until it is done and then the french dev team can then build on a working module. @carolinverset hope this is fine by you?

Yes, it's ok ! Thanks

**Comment by ftavin** [comment]
Short-term alternative using css : #3020

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas version 1.55.0-Snapshot on local environment.

**Comment by syntakker** [comment]
Under Windows, there are test failures in `EventDocumentFacadeEjbTest` and `TemplateEngineTest`, where expected and actual texts to compare differ in line separators
SORMAS version: 1.55.0-SNAPSHOT, OS Windows 10.
Bugfix in PR #4227.

**Comment by AndyBakcsy-she** [comment]
Reopening issue because: 

- The Status of the action is not displayed 
- Region, department and municipality of the event
+ The Event Handout document displayes information that was not requested in this ticket: $participant.person.phone

**Comment by syntakker** [comment]
Important: Html output of both templates and SORMAS data has to be cleaned.

**Comment by syntakker** [comment]
> Reopening issue because:
> 
>     * The Status of the action is not displayed
> 
>     * Region, department and municipality of the event
> 
> 
>     * The Event Handout document displayes information that was not requested in this ticket: $participant.person.phone

@AndyBakcsy-she the event document is generated from a user supplied template, intended to be modified according to the user's needs. What you see is actually the output of an example template.

I refined the example template to include the missing information about status, region, distrcit and community.

For the surplus information, however, I'd go for leaving it in the template, since the example template should demonstrate the template features. In case the information is not needed, it is easier to delete the superfluous parts of the template than figuring out how to create them.

**Comment by StefanKock** [comment]
Findings needed to be fixed, that's why the milestone is appropriatly change to Sprint 100.

**Comment by raghupola-vg** [comment]
Tested on latest version 1.57.0-Snapshot and the templates are generated as expected with all the necessary data.
