### ISSUE TITLE
Authorize all user roles to be able to filter events by region, district, community in  event directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2914]
### Problem Description

Need to have a filter to select the regions in the directories of cases, contacts and events. Only departments are available as a filter

### Proposed Change

Add region filter

### Additional Information
@bernardsilenou

**Comment by bernardsilenou** [comment]
@MateStrysewske I can remember we had these filters in the past, please can you confirm if this is a bug?
before the french developers can work on this need.

**Comment by ChristopherRiedel** [comment]
@bernardsilenou @carolinverset These filters definitely exist. My guess would be that the users used do not have the permission to see cases etc. from other regions. Basically you can say that users who are assigned to a certain region or district can only filter below this level.

**Comment by carolinverset** [comment]
@ChristopherRiedel @bernardsilenou 

For cases and contacts,i'm agree with you. But for events, i think it's different. Users see all events in the country and cannot filter on only events in their region

**Comment by ChristopherRiedel** [comment]
@carolinverset It is the same for events, except that you can only filter down to district level.

**Comment by carolinverset** [comment]
@ChristopherRiedel @bernardsilenou 
I'm sorry but i don't understand. In the next screenshot, you see that the french users see events of two regions Bretagne and Provence Alpes Cote d'Azur. In the futur, all the other region will also write the events of their region. We consequently will see all the events of France which complicates the search for an event for example. I'm wrong ? Thank you verry much for your explanations. Best regards. 

![image](https://user-images.githubusercontent.com/65449450/93739739-4a41cf00-fbe9-11ea-8399-a3889103a889.png)

**Comment by bernardsilenou** [comment]
French team is working on this in this sprint

**Comment by bernardsilenou** [comment]
Since events are public and every user can see the meta data of all events, in a centralized system it is difficult for users to see and manage events in their jurisdictions only.
- Add filter to event directory based on region, district, community of events, all web user roles  would be able to see and use this filter 
- split event location in individual columns for region, district, community

Only users accounts in the jurisdiction of the event or those that create the event would be able to edit the event meta data
The right to see or edit event participant would apply as specified in #2902

@ChristopherRiedel @MateStrysewske is this specification correct and enough?

**Comment by MateStrysewske** [comment]
Looks good to me.

**Comment by raghupola-vg** [comment]
Tested and works fine on test systems.
