### ISSUE TITLE
Bulk actions on all directories should respect pseudonimization [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2918]
### Bug Description
A user that has no right to sensitive data of a case, contact or event participant is able edit these entities through bulk actions. I rested only on event participant but I think this holds  cases and contacts also.
### Steps to Reproduce
1. log is as admin
2. go to an event that you are not allowed to edit participants
3. Use bulk action mode to delete  an ep
### System Details
* Device:
* SORMAS version: 1,48
* Android version/Browser:

### Development Specifications
* When the user tries to perform any bulk action (including opening the "Edit" window, i.e. do this before the window opens), check how many of the selected entries are pseudonymized; if at least one is pseudonymized, don't perform the bulk action, but instead present an error message to the user: "X of the cases/contacts/event participants/... you've selected is pseudonymized. Please deselect all pseudonymized cases/contacts/event participants/...." Do this for case, contact, event, eventparticipant directories
* Allow Admins to always Archive and/or Delete entities

**Comment by DavidBaldsiefen** [comment]
Alternative suggestion: Wouldn't it make sense to make pseudonymized  entries un-selectable? That way the workflow of selecting all entries through the checkbox at the top of the column wouldn't be hindered

**Comment by kwa20** [comment]
@bernardsilenou @DavidBaldsiefen 'Delete' is mentioned in the steps to reproduce and 'any bulk action' is mentioned in the development specifications. How do we account for users that merely have the admin role? These users will have pseudonymized entities because of their default user rights. Therefore, they'll be prohibited to delete/archive anything via bulk action because their rights contradict each other.

**Comment by DavidBaldsiefen** [comment]
@kwa20 

> How do we account for users that merely have the admin role? These users will have pseudonymized entities because of their default user rights. Therefore, they'll be prohibited to delete/archive anything via bulk action because their rights contradict each other.

That is correct, yes. However, IMO that would make sense too. If the admin wants to edit/delete entities he also needs the "Admin Surveillance Supervisor" role, which would then also remove the pseudonymization

**Comment by kwa20** [comment]
@DavidBaldsiefen For editing I think it makes sense because you cannot properly edit entities that are pseudonymized. However, admins can still go into each individual entity, regardless of them being pseudonymized, and archive or delete them. Prohibiting them to do so via bulk actions therefore makes little sense and only makes the mass action less feasible.

**Comment by DavidBaldsiefen** [comment]
@kwa20 alright, I've updated the developer specifications
