### ISSUE TITLE
Infinite loading on Cases follow up tab

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2969]
### Bug Description
When clicked on Follow up tab on Cases directory, the screen stays in infinite loop and the screen flickers.

### Steps to Reproduce
1. Login to Sormas (https://test.sormas.netzlink.com/) as any user and click on Cases
2. Select Follow up tab on the top, next to default view and detailed view.
3. See if the follow up details are correctly loaded and displayed.

### Expected Behavior
The screen shows infinite loading time and doesn't load fully

### Screenshots
![Cases Follow up](https://user-images.githubusercontent.com/62763628/94027790-87f65180-fdbb-11ea-9cea-424dc965cd88.PNG)

### System Details
* Device:
* SORMAS version: 1.49.0
* Android version/Browser:

**Comment by raghupola-vg** [comment]
On today's build, Click on follow up tab and then click on Previous to Reproduce the issue.

**Comment by xavier-calland** [comment]
Perhaps it could be from inconsistent results between the call to `count()` and `getCaseFollowUpList()`.

**Comment by MateStrysewske** [comment]
@xavier-calland My thought as well, but it's a little strange because it never happened before (not in the contact follow-up overview either), and I also can't reproduce it on my dev system. Both methods use identical filters anyway, so there shouldn't be any inconsistencies.

We had infinite loading problems in the task and sample directories recently, but those were caused by making a distinct selection in the getIndexList method that wasn't added to the count method. There's no distinct selection for the follow-up list however, and there's no duplicate cases displayed in the list when the error occurs.

**Comment by MateStrysewske** [comment]
@xavier-calland It's definitely caused by this though; the number on top of the list on the test server says "16" while there are only 11 items displayed in the list.

**Comment by xavier-calland** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/blob/df6ef3ff73fb55db3b4b55f8efb2125ff51cd809/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java#L2880

`caseService.createCriteriaFilter` does not use already joins created in the query. This may cause adding the same join multiple times (see https://github.com/hzi-braunschweig/SORMAS-Project/pull/2974/commits/574b544c09b4b0f85a92dbd406ac2654fa06d29a in PR #2974 )
I don't know if this can explain that bug.

**Comment by MateStrysewske** [comment]
@xavier-calland Possibly. I think I'll move this issue to waiting and we'll see whether your PR fixes the problem. I can't merge it for this release unfortunately, but we'll see it on the nightly builds.

**Comment by MateStrysewske** [comment]
@xavier-calland Seems like your changes fixed this bug! At least it doesn't happen anymore on the test instance. Thanks a lot!
