### ISSUE TITLE
 Add new field: Quarantine before isolation

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2977]
### Feature Description

 Cases > Open Case > Case Information: Quarantine before isolation

New field (CH only) -
"Was the case in quarantine before isolation?" (en) | "War der COVID-19-Fall bereits in Quarantäne vor der Isolation?" (de-CH)
Data Type: Yes/No/Unknown

@Candice-Louw What does "before isolation" mean ? (converted from contact to a case? Hospitilisation or isolation filled?)

Remarks:
Automatically calculate this field 
@Candice-Louw How do we do the Migration with existing cases / contacts
Field should be readonly but visible. / @Candice-Louw Can the user override it?
Field is automatically calculated and changes automatically when the quarantine entry in the contact changes
It will be included in the export, the value will be calculated and updated auto

**Comment by bernardsilenou** [comment]
@markusmann-vg @Candice-Louw  Since we have date of quarantine and date of isolation, can we not derived this and report as an indicator? I also agree with you that the definition of this veritable if subjective.
I think we should handle this in statistic section since it is a derived variable
We should not allow users to edit it directly, they can do so by editing the date of isolation or quarantine

**Comment by Candice-Louw** [comment]
In the Swiss context:
Cases go into Isolation
Contacts go into Quarantine

---

The question is in essence: Contact converted to a Case?

---

If the Contact was recorded in SORMAS, it can then be converted to a Case.  This could possibly be automatically calculated if recorded in SORMAS.

In certain situations, however, the Contact is recorded by an external application (such as the SwissCovidApp).  Only if this Contact develops symptoms and becomes a Case, they are recorded in SORMAS.  SORMAS therefore does not have the Contact data.  This calculation can then not be done (as there is no quarantine date as suggested by Bernard since this would be in the Contacts details).

By introducing this additional variable, the BAG would be able to create a Case directly in SORMAS and indicate that the case has previously been a Contact as identified by external applications/situations (such as the SwissCovidApp, returning travelers from neighboring risk countries that have to go into quarantine etc.  See point 5 on these reasons for CH here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2959).

These values should therefore not be static and must be editable.

---

**To calculate:**
Where information is already available in SORMAS (i.e. existing Contact converted to Case), calculate this field and set to 'YES'.

The values should still be able to be manually set/changed, even if automatically calculated. If not possible, it is requested that automatic calculation should **not** be done as users must be able to change values for this variable.

**Data migration:**
For existing Cases in SORMAS that have been converted from existing Contacts in SORMAS - YES
For all other Cases - UNKNOWN

---

Specifications from the BAG for the MED:
Var BAG | Already in SORMAS? | Criteria | Question |DataType BAG | Values BAG|
| -- | -- | -- | -- | -- | -- |
quar_yn | No | Quarantine before Isolation/Contact converted to Case | Was the COVID-19-Case already in Quarantine before Isolation? | codelistElement | 1=yes, 2=no, 3=unknown

**Comment by bernardsilenou** [comment]
@Candice-Louw With this explanation, i understand better now. The main message here is that the resulting case of a contact is in sreomas but the source case is not and we need to document this information.
We have another issue in the current sprint that will answer this  question and add more information. Please read the main  issue  and tell us what you think #2946
The way it works is to link this resulting case with the case in the external system by creating the contacts. 

If the case in the other system is not know, we still create a contact without a case and record date of isolation and together contact variables that ate known. All this information goes to the epi data tab of the case.
This solution will be added to all sormas instances with the introduction of the new epi data tab. 
The epi tab is to document all exposure inflammations that may have resulted to the case, and this variable fall in that class.
The case tab is for variables of the current case

Please can you present this solution to them and If they are still interested in having this variable on the case tab, then we can add it on Swiss instance only.

**Comment by Candice-Louw** [comment]
Discussion with CH colleagues on 30.09.2020 - keep the variable separate and on the case tab (for Switzerland only), please.  The user should be able to override this value at all times.

**Comment by AndyBakcsy-she** [comment]
Issue verified on SORMAS Version: 1.50.0-SNAPSHOT
