### ISSUE TITLE
 Addition of an investigation status field for events

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2992]
### Situation Description
Each event is the subject of an in-depth investigation by one or more ARS teams. Many events are entered every day by the teams. Each of them is subject to a thorough investigation which can take several days.

It now appears essential to have a variable relating to the level of the survey.

This information will allow :

- filter the directory of events on the level of investigation: uninitiated, in progress, to be closed, closed

- to give overall consistency: we have this variable for the different actions implemented for a given event. Having the same variable for the event itself increases readability for the SORMAS user, especially in the detailed view relating to actions which is under development (issue # 2907)

- to give greater flexibility to users in the management of the investigation. To date, only administrators have the ability to archive or unarchive a closed event. It is not conceivable to give the profile of administrator to all the people in charge of the investigation. However, it is essential to be able to allow them to indicate whether the investigation has ended and whether, in his opinion, the event should be closed. The final decision will be up to the supervisor who would switch the status “to be closed” to “closed”. It is only after a period of time to be defined by the different regions that the event can then be archived for greater readability of the directory of events.

### Feature Description
Develop a "investigation status" variable to qualify the event. This variable should take the form of a drop-down list with the following modalities:

- Investigation to start
- Ongoing investigation
- Investigation to be closed
- Investigation closed

This variable would be included in the detailed view of actions and in the events directory : creation of a column and a search field allowing the events to be filtered according to the status of the investigation.

@ftavin @xavier-calland  @bernardsilenou

**Comment by ftavin** [comment]
@carolinverset can we be more specific concerning the following :
- is this new data mandatory ? (if so, what is the default value - probably "investigation to start" ?)
- where should the field appear on the page ?
- where should the column appear on the list ?
- editable via bulk edit mode ?
- should it be added to the event printing function ? [2906](https://github.com/hzi-braunschweig/SORMAS-Project/issues/2906)

thank you in advance for your answers !

**Comment by carolinverset** [comment]
@ftavin Lot of questions, sorry for the late answer... :-)

- Yes it's a verry important information. Consequently, this data must be mandatory and i agree with you that the default value would be "investigation to start"
- is it possible to place this variable above the status of the event? or on the right of the event status ?
- in the event directory, it would be interesting to include it to the right of the event status
- Yes for the bulk edit mode
- Yes, insofar as this field is essential for teams, it must be integrated into the printing function

Thank you ++

**Comment by bernardsilenou** [comment]
@carolinverset @ftavin  I just happen to see this issue but today. I have some suggestions:

"Investigation to be closed" sound subjective. I will suggest the following nomenclature in order to be
consistent with the case investigation status:

investigation pending (default status at event creation)
investigation ongoing   + investigation start date
investigation done     +  investigation end date
investigation discarded +  investigation end date

- Add this variable to the event directory
- Add this variable this variable to the event exports (basic + detailed)
- Can we locate the investigation status just above the disease as in the diagram ?

![image](https://user-images.githubusercontent.com/12996724/95510095-afe9d580-09b5-11eb-9fef-fa4eff06d743.png)

- I see it more as a filter with drop-down box. Since we already have investigation status at the top of the event directory, adding the investigation status will result to additional 4 boxes wish looks much and users may this they are all categories of the same variable.

![image](https://user-images.githubusercontent.com/12996724/95510769-b9c00880-09b6-11eb-819a-641f84292e50.png)

**Comment by ftavin** [comment]
@bernardsilenou I'm ok with your remarks !
