### ISSUE TITLE
Add Country to location details [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2994]
### Feature Description

Prerequisite: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2993

Country is freetext as long there is no list provided on the server.
Default: Server Country

**Comment by kwa20** [comment]
When considering the addition of countries to the home address, region, district and community could be free text fields when "other" than the server country is selected (applicable when no list is provided as mentioned above).
<img width="905" alt="Screen Shot 2020-10-08 at 10 12 59 PM" src="https://user-images.githubusercontent.com/70317594/95509391-bc216300-09b4-11eb-96e5-555bc0f6a031.png">

**Comment by HolgerReiseVSys** [comment]
Currently the geocoding does not consider the country.
Implicitly it is expected to match that of the server.
Many, if not all, of the currently relevant geocoding services only cover a single country.
Maybe geocoding should only be available when "Server country" is selected.

**Comment by kwa20** [comment]
- Instead of the proposed mock-up above, add the country drop-down with all the countries deposited in the system and pre-fill this field with the server country. When another country as the server country is selected, disable region, district and community for now because we don't have a link in the infrastructure with countries yet. 
- Considering events: region and district are compulsory fields when the server country is selected. If another country is selected, make these fields non-compulsory and make the event participant jurisdictions compulsory instead (own server country jurisdictions).

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment.
Validated only the web part of this ticket

**Comment by MartinWahnschaffe** [comment]
@alexcaruntu-vita Please add the country.name entry with a short description of what it's doing to the documentation:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_CUSTOMIZATION.md
