### ISSUE TITLE
Refactoring the headers to help user navigation

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3062]
### Situation Description

Event participants and event actions are two screens linked to an event. Those two screens does not give enough information to identify quickly the concerned event (just the disease, the status, the date of report and the start of the event id in the top right corner).

### Feature Description

We would like to have a header on those two pages that gives, at least, the title of the event.

This information would help to identify quickly the concerned event, for example if you use multiple tabs on the browser or if you prints the page or takes screenshots.

This modification should be applied to all screens (not just for events) to keep the UX consistent.

After discussion in the comments and by mail, @carolinverset and @bernardsilenou choose the three row design in the following mockup designed by @hellerdominik :

![mockups](https://user-images.githubusercontent.com/15834125/96686553-f6a8d980-137e-11eb-8e46-1000ef6fd0fb.png)

@carolinverset @bernardsilenou

**Comment by bernardsilenou** [comment]
@ftavin This is a good idea. Please can you have a look at the mockup of the newly event participant form from issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/3003  ? I see this as the solution for the event participant entity, we may just need to do the similar one for the followup form

**Comment by bernardsilenou** [comment]
please can you add a small mockup just to be sure were are thinking about the same thing?

**Comment by ftavin** [comment]
@bernardsilenou Here are two mockups :

![participants](https://user-images.githubusercontent.com/15834125/95079789-641a0080-0717-11eb-95cc-3a415a1aee2c.PNG)
![actions](https://user-images.githubusercontent.com/15834125/95079992-b3f8c780-0717-11eb-9a02-3b88dfefc7b2.PNG)

**Comment by bernardsilenou** [comment]
@ftavin In the figure below, the box at the top right was meant to serve this purpose, linking entities to their principal entity. I can see that only the event title is lacking. Can we not instead add it to the list of variables in the box, and make it nicer? Having both leads to duplicate information.
A similar box exist on the contact directory page, showing information about the source case.

![image](https://user-images.githubusercontent.com/12996724/95113073-25e60680-0742-11eb-9617-e285591c3dd9.png)

**Comment by ftavin** [comment]
@bernardsilenou I am ok with your remarks if we make the box nicer : the one on the screenshot is to small to include the title of the event and I believe that it is not user friendly (top right with a large blank on the left does not catch the eye, I made the test with two collegues, it took minutes for them to see that bloc).

I suggest this block should at least stick to the left (just right to "Event Participants") and be more clear (nothing tells us that these are event related informations)

**Comment by ftavin** [comment]
meeting this morning with @bernardsilenou and @carolinverset :
- we use the blox
- we move the box to the left (just right to the screen title)
- we make the box larger in order to have the title of the event fitting

after this development and confirmation it is ok, an issue will be created to generalize the position of the box to every screen with a box like this one

mockup @MateStrysewske  :
![mockup](https://user-images.githubusercontent.com/15834125/95342327-995d5480-08b7-11eb-811f-149fe8ae3bdb.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske What do you think about this please?

**Comment by MateStrysewske** [comment]
@bernardsilenou I really don't like that visually. It looks weird to have this box directly next to the heading and then a huge blank space to the right of it. Also #3096 proposes to completely get rid of the box anyway.
I think we should rather think about something like adding an additional line to the page heading that can be used for further details, e.g. the event title in this case.

**Comment by bernardsilenou** [comment]
@MateStrysewske, your comment makes sense.
@ftavin  have ask @HellerDominik if he can suggest a mockup. Please François, can we wait and see what he will propose before we begin implementation?

**Comment by ftavin** [comment]
@bernardsilenou ok to wait for the mockup, we hope this could be done within a week to let us the time to implement this for 1.51 !

**Comment by HellerDominik** [comment]
Hello everybody,
a nice coincidence that you were addressing this issue around the same time. 

My suggestion, to remove the big navigational header and replace it with the actual title of the entry comes a bit from real life patient folders where I would probably search for the patients name in the top left corner. I need to know with one glance who I am dealing with or with which event etc. 
In my opinion the navigational element is just not as high in the visual priority as the name of the event, patient or sample.  

This is my mockup for the header.
![grafik](https://user-images.githubusercontent.com/63474971/95611898-c13ceb80-0a62-11eb-95f5-14ce8a976601.png)
I took all the info from the badge that was on the right and tried to work on a hierarchy. Which is the most important is to be defined by you in the end. 

Therefore I did this version with placeholders for 3 informations, the most important ones on the top in the bigger front, another one with the date (or a fourth info) below.
![grafik](https://user-images.githubusercontent.com/63474971/95612283-740d4980-0a63-11eb-915c-a83916fe2188.png)

While working on this issue I noticed two other things that I'd like to address. 
The first is another redundancy. I think that the arrow below the header and the click to the Event list have the same function. 
![grafik](https://user-images.githubusercontent.com/63474971/95613309-0cf09480-0a65-11eb-9380-726be85e7d3e.png) 
But that's not so important, it just takes noise from the screen if I have fewer options which have the same function.   
  
In what I actually see an improvement would be to stick the header and the navigational elements to the screen and make them not scroll anymore. 

![grafik](https://user-images.githubusercontent.com/63474971/95613562-72448580-0a65-11eb-9126-e36c7f1c1699.png)

This may work not too well as a mockup therefore I created a little scroll dummy in axure, which you can find here:
https://nhxmpe.axshare.com
Make sure to set the view in the top right corner to 'Scale to fit' to get the best experience. 
![grafik](https://user-images.githubusercontent.com/63474971/95611668-6dca9d80-0a62-11eb-8992-825e86c879c9.png)

Hope this helps. What do you think?

**Comment by bernardsilenou** [comment]
@HellerDominik Many thanks for this quick and nice design.  I think there are 2 needs here:
1. How to display information about the record on the form in front of us 
2. How to display information about the primary entity that this entity is linked to. For example, the parent entity case has children such as contacts, samples, followup, etc. So on the contact from, users should be able to see information about the source case. On the event participant from, we present information about the event, on sample form, show information about case, contact or event participant referenced by the sample, end so on.

I just realized after looking at your mockup that the current event participant form was not rightly design because the top right information box shows the same information as the event participant from (this should have been the information about the event).  The person uuid is shown but the event participant uuid is not shown

Form my understanding, I think that your solution is for point 1 and not point 2, is this right?

![image](https://user-images.githubusercontent.com/12996724/95662006-2dd3eb00-0b34-11eb-8534-a50aeaf7a40f.png)

Please can we (@ftavin , @HellerDominik , @bernardsilenou ) schedule a call on Monday, any time from 16:30 to discuss this issue?

**Comment by HellerDominik** [comment]
Yeah, sound's good to me. 16:30 CET?

**Comment by bernardsilenou** [comment]
Thanks, 16:30 is fine by me, lets wait to hear what François says

**Comment by bernardsilenou** [comment]
@HellerDominik I am writing to confirm our call today at 16:30 - 17:00.
Please can you send my your email through bernard.silenou@helmholtz-hzi.de
meeting link: https://conf.dfn.de/webapp/conference/979151124

**Comment by ftavin** [comment]
@HellerDominik if I understand correctly, you will develop this feature

You will also have to adapt the @media print in css to have this header printed (in the current version, the header is ignored for printing)

**Comment by HellerDominik** [comment]
Hey @ftavin 

that's not right. I am not a developer. I work in UX and help with prototypes and mockups. 

The mockups for these features were the following. In the mail correspondence with Carolin and Bernard they agreed on using a three row design. 

![page_2](https://user-images.githubusercontent.com/63474971/96221328-b31f2b80-0f8a-11eb-92f3-0a3681860861.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT

**Comment by vidi42** [comment]
This seems to break the Patient Diary integration

In the constructor for `de.symeda.sormas.ui.contact.AbstractContactView` there is where the `btnClimedoAccount` button is added to the header, but down bellow the method `refreshMenu` calls `AbstractView.replaceViewHeader` which removes everything from the header and only adds back the labels

**Comment by kwa20** [comment]
I have a problem with the execution of this issue (after testing on test-de.sormas.netzlink.com). The implemented change here can not be allowed to be applied to the person form since it ruins the emphasis on differentiating between person and cases/contacts. 

<img width="748" alt="Screen Shot 2020-12-12 at 10 17 33 PM" src="https://user-images.githubusercontent.com/70317594/101995132-2cf03e80-3cc8-11eb-8403-f6054180b1d0.png">

The information given here only applies to the contact itself because the person can have many contacts to any other source case, not to mention all the other possible diseases those source cases can have. We should therefore only show information related to the person itself here. This means that we should either keep it 'Person information' or only reference the name with the shortened person Id here instead of the contact Id.

Furthermore, I don't understand the logic behind showing the contact classification in the heading since it is visible right below the heading as well. Showing the contact category here would be much more useful.

<img width="681" alt="Screen Shot 2020-12-12 at 10 05 50 PM" src="https://user-images.githubusercontent.com/70317594/101995284-27dfbf00-3cc9-11eb-8ebf-67124c956bae.png">

According to the concerns mentioned above, the same thing applies to the person form of the case entities. Disease and classification can not be shown here and instead of the case Id it should reference the shortened person Id.

<img width="390" alt="Screen Shot 2020-12-12 at 10 11 56 PM" src="https://user-images.githubusercontent.com/70317594/101995355-9b81cc00-3cc9-11eb-9ef2-940a044df2a1.png">

@bernardsilenou @MateStrysewske

**Comment by bernardsilenou** [comment]
@kwa20  We discussed this issue before implementing it like this. Since this implementation is not obvious from someone who was not invoked like you, I think it is a sigh that we need to have a second look at it.
- In the header panel, the uuid is the uuid of the entity concern, not the uuid of the sub form (eg person) that is displayed below. 
his header panel always stay the same not matter the sub form below it. This is one of the main reason whey this change was requested because the old design showed the same information twice: header panel and tab panel below it.
- We can refine the second line in the header  and show both contact status and category, this is good point.
- Here is a possible arror:
![image](https://user-images.githubusercontent.com/12996724/101997691-c4f42500-3cd4-11eb-98e7-a3d29bf88d3b.png)

**Comment by bernardsilenou** [comment]
@kay and I will discuss and add the comment here or create a refinement issue
What I think we need to address in this issue is to correct the uuid of the source case when on the contact tab

**Comment by MateStrysewske** [comment]
I disagree with @kwa20 here. First of all, this issue doesn't really add anything new, it just moves the information from the top right to the top left to make it a) more visible and b) get rid of the useless headers that we used so far. Secondly, the purpose of this information is that the user knows exactly which entity they are looking at right now, even if they aren't in the "contact information" or "case information" tabs; when inside a case or contact, while you're right that the person form refers to its own entity, we are still displaying everything related to that contact or case, so that's also the information that should always be visible to the user. Showing information about the person itself in the header wouldn't make any sense because you can already see that anyway when you're inside the person form.

I don't really see any reason to change the specifications of this issue besides making the font smaller.

**Comment by kwa20** [comment]
@bernardsilenou @MateStrysewske Thanks! I understand better now. I was a bit confused about how the entities are referenced for contacts since this issue focused on cases and event participants but the Id is the correct one then because it describes the contact itself and neither the contact person or the case. Putting an Id behind a name might lead users to naturally associate it with that name. I don't have an idea how to simplify it even further but as soon as someone references that Id, the referenced entity should be clear. I guess everything else would be resolved with the planned person directory.

Reducing the font by a bit is indeed all that remains. I might just create another issue for referencing the contact category in the heading. I think that'll be useful.

**Comment by MateStrysewske** [comment]
- [ ] Reduce font size

**Comment by AndyBakcsy-she** [comment]
Validated the header change on the latest SORMAS Version: 1.53.0-SNAPSHOT
