### ISSUE TITLE
Broken formatting on classification rules

### ISSUE THREAD

**Issue by Seal33** [hzi-braunschweig/SORMAS-Project#3220]
### Bug Description
Formatting of Classification Rules and "Classified-By"-Label is broken. The popup containing classification rules is also needlessly large.

### Steps to Reproduce
1. Go to any Case overview, with a disease which requires Classification (e.g. Cholera, Dengue-Fever)
2. When clicking on an Info-Button for Classification Rules, html is not correctly displayed (see second screenshot)
3. After classifying the case, a linebreak after "Classified by" is missing (see first screenshot)

### Expected Behavior
1. Correct display of html
2. Linebreak after "Classified By"
3. Info-Popup only as large as necessary

### Screenshots
![image](https://user-images.githubusercontent.com/4655486/96448832-3ef7b880-1214-11eb-9e3e-a95743a068a5.png)
![image](https://user-images.githubusercontent.com/4655486/96448861-47e88a00-1214-11eb-8d16-251997abbc32.png)

### System Details
* Device: Ubuntu
* SORMAS version: 1.51.0-SNAPSHOT
* Android version/Browser: Firefox 81.0.2
* Server URL: local
* User Role: admin

**Comment by Seal33** [comment]
@MartinWahnschaffeSymeda @syntakker @JonasCir 

The issue seems to be caused by numerous (redundant) calls of `StringEscapeUtils.escapeHtml4()` in `ClassificationHtmlRenderer.java`. Logically it is only necessary to escape strings on the lowest level, in this case only i18n strings would need to be escaped. However, there are numerous i18n strings containing html-tags themselves.
How should we solve this issue? Two possible ideas would be to

1. Allow some tags (like `<br> <b> <i>`) to be ignored by `escapeHtml()`
2. Disallow usage of tags in i18n. This would require larger code changed in several places

**Comment by JonasCir** [comment]
Ignoring HTML tags in in  the `escapeHtml()`function implies that you cannot anymore rely on it to properly handle all untrusted content. Meddling with HTML-Encoders or writing custom implementations _will_ [fail](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#you-need-a-security-encoding-library) and ultimately leave you open to injection or scripting attacks. 

The root cause for this issue is that I18n Strings were used in an unintended way and the HTML document building process does not handle encoding correctly. Instead of introducing a potentially dangerous workaround, I opt for removing the tags from I18n and use a vetted encoder library like the [owasp-java-encoder](https://github.com/OWASP/owasp-java-encoder)

**Comment by Seal33** [comment]
> Ignoring HTML tags in in the `escapeHtml()`function implies that you cannot anymore rely on it to properly handle all untrusted content. Meddling with HTML-Encoders or writing custom implementations _will_ [fail](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#you-need-a-security-encoding-library) and ultimately leave you open to injection or scripting attacks.
> 
> The root cause for this issue is that I18n Strings were used in an unintended way and the HTML document building process does not handle encoding correctly. Instead of introducing a potentially dangerous workaround, I opt for removing the tags from I18n and use a vetted encoder library like the [owasp-java-encoder](https://github.com/OWASP/owasp-java-encoder)
> 
> See [OWAS XSS Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#cross-site-scripting-prevention-cheat-sheet) for background information.

Surely it would be best if i18n-Strings were simply disallowed from using tags, so one could just unescape strings everytime `I18nProperties.getString()` is called. However, in some cases it seems like some kind of markdown would still be necessary. Using a simple util-implementation that re-enables specific tags (<b>, <i>, <br>) is a simple and reliable workaround for now.

**Comment by MartinWahnschaffeSymeda** [comment]
Thanks @Seal33 and @JonasCir  for reporting and looking into this. From my point of view there are two things that need to be done:

1. I had a look into ClassificationHtmlRenderer. The escaping we introduced in #2859 is obviously covering a bit too much. For example line 57 calls createSurroundingDiv and passes a string that is already escaped and contains html element that have been added in the code. This needs to be fixed, by clearly distinguishing strings that contain already escaped html.
2. A few parts of the classification (e.g classificationInfoNumberText in strings.properties) and also other text (e.g. infoCaseDate in strings.properties) use basic HTML elements: <b>, <i>, <br>, <ul>, <li>. From my point of view this will still be needed, because structuring text like this increases the readability and needs to be a part of what is translated. 
We need to find a good solution for this - either another escape method that keeps them or an additional method that unescapes them explicitly - as suggested by @Seal33. The later one will probably be sufficient. Ideally we wrap this in a helper method so it's easy to adjust this whenever needed.

@JonasCir Is there a difference (performance, behaviour?) between the OWASP encoder and the apache commons encoder that is currently used?

**Comment by JonasCir** [comment]
@MartinWahnschaffeSymeda To answer your questions:

- regarding behavior: I hope that both of them work and properly escape HTML tags such that injection attacks/XSS is prevented :)  
- regarding performance: there might actually be a difference but I cannot tell without proper testing which one is faster. Given the fact that in Vaadin the DOM is processed on the server for each client and request, this might actually become a factor for  single server deployments with many clients accessing SORMAS concurrently. The OWASP project claims to be high performance and I tend to believe them :) But again, this is just speculation b/c without doing performance measuring, it is hard to tell.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
![image](https://user-images.githubusercontent.com/70562142/96962708-060b5c80-1510-11eb-93d9-bcd1135c8413.png)
