### ISSUE TITLE
Only show facility categories that allow a permanent residence when selecting home in locations

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3237]
### Feature Description
This issue is a refinement of #2456
When creating cases, we do not ask for facility if the case person is at home. When documenting the home address of a person, we asked for details about the facility categories that do not match a home address
### Problem Description
- Validate address types and facility variables
### Proposed Change
- If address type == home, do not show facility variables

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/96629165-89139380-1313-11eb-95b8-5daa57a10ce8.png)

**Comment by bernardsilenou** [comment]
@Candice-Louw  Please link this to the other issue on address formats. Danke

**Comment by Candice-Louw** [comment]
Related entries: 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2979
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2994

**Comment by MateStrysewske** [comment]
@bernardsilenou @Candice-Louw We disagree that these fields should be hidden because there are certain facility categories that make absolute sense for "Home", e.g. retirement homes. However, we will limit the selectable categories to those that actually make sense, e.g. selecting "Educational Facility" will no longer be possible.

**Comment by raghupola-vg** [comment]
Verified both on app and web and the selectable categories are now limited for Home address selection
