### ISSUE TITLE
Decouple Place of stay from the responsible jurisdiction from cases [13]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3254]
### Situation Description
In German health departments - but potentially also in other countries - it's possible that the place of stay of a case (e.g. the hospital they haven been admitted to) does not match its responsible jurisdiction (e.g. because the person has been submitted to a hospital in a different district than their home district).

### Feature Description
* Add new fields to cases:
    * `responsibleRegion` (caption: Responsible region)
    * `responsibleDistrict` (caption: Responsible district)
    * `responsibleCommunity` (caption: Responsible community)
* Change the caption of the existing fields by removing the "Responsible" keyword from region, district and community
* In both the case creation and case edit forms (app and web), move the "Place of stay" field to above the region, district and community

#### Case edit form/fragment
* Add a heading above the "Place of stay" field that is also called "Place of stay" and remove the caption from the "Place of stay" field
* Add a heading below the facility fields that is called "Responsible jurisdiction"
* Add a checkbox below the heading that is called "Responsible jurisdiction of this case differs from its place of stay"
    * Checked by default when a responsible region has been entered, unchecked if not
    * When unchecked, the three new fields are disabled; when checked, they can be edited
    * When checked, responsible region and district are mandatory
* Add the three new fields below this heading

#### Backend
* Every piece of code that currently checks the region, district or community of a person in terms of visibility, edit rights or anything related now needs to check whether the responsible region, district or community have been filled in, and if so, use this information instead of the region, district and community associated with the place of stay

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @JaquM Can you tell us how task assignments and notifications should be handled after this change? E.g. when a case is created, there's an automatic case investigation task generated and automatically assigned to a user; should this be a user from the responsible jurisdiction or the place of stay? Is there a fallback if the primary option is not available? What about tasks/notifications that are on facility level? Since we don't have a responsible facility, how would those be handled?

**Comment by bernardsilenou** [comment]
@MateStrysewske I have similar questions like you. Would be good I discuss this with others before responding.

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @JaquM We need an answer to this as soon as possible because this question blocks us from continuing implementation on this issue. Any update?

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @JaquM Follow-up question: Which kind of access should users in the place of stay have if the responsible jurisdiction is filled in? Should they even see the case? If yes, pseudonymised or not? If not, should they be able to edit it?

**Comment by kwa20** [comment]
@MateStrysewske 

- If the responsible jurisdiction and place of stay differ, users in both regions should have full access to the case. Users in any of the two jurisdictions should then be able to be assigned as the responsible user.
- Automatic tasks should get assigned to the responsible user, otherwise to users in the responsible jurisdiction. 
- Tasks should also be able to be assigned to users of the place of stay jurisdiction. 
- If there is no available user in the responsible jurisdiction, the assignment should fall back to a user in the place of stay jurisdiction.
- statistics counting should be based on the responsible jurisdiction.

**Comment by MateStrysewske** [comment]
@kwa20 What should we do about email/SMS notifications? Same rules as for automatic tasks, or should they get sent to users from both the responsible jurisdiction and the place of stay by default?

**Comment by kwa20** [comment]
@MateStrysewske Honestly, I'm not quite sure how the notifications are handled at the moment but I think sending the notifications to users in both jurisdictions is a good idea and I guess it also wouldn't cause any harm since it's merely a notification.

@bernardsilenou any objections?

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  
I agree also, if both jurisdiction types have different districts, then we send sms/ emails to surveillance officers and fall back to supervisors in both districts. Similar to events groups

**Comment by MateStrysewske** [comment]
@leventegal-she Sorting is missing for the new columns, see #5341

**Comment by raghupola-vg** [comment]
Verified on version 1.60.0-Snapshot and the sort issue is fixed.
