### ISSUE TITLE
Lab officers can't edit the reason for specimen condition not adequate

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3263]
### Bug Description
Lab officers are not localized as compares to other user roles like surveillance officers and supervisors. This means they can have read and write access to  entities (case, contacts, event participants) irrespective of their responsible jurisdiction nor reporting user. The basic condition for a lab user to have full access to an entity is when a sample of the entity is assigned to the lab.

- Lab users do not see personal data for cases whose associated sample is assigned to the lab that the user account of the lab officer is assigned
- Lab users have read access to samples that are not assigned to their lab 

### Steps to Reproduce
1. Log in as national user, create a case
2. send a sample of the case to a lab
3. log in as lab officer of the lab
4. Check if you have full access to the case and sample

### Screenshots
1. This is a screenshop when i logged in as a lag officer in Frankenstains lab in Berlin. I would see a sample assigned to another lab.

![image](https://user-images.githubusercontent.com/12996724/96910029-24853f80-149f-11eb-8271-26c4a840cae5.png)

2. Reason for "specimen condition" == "not adequate" should not be "confidential". User can not edit the varaible "reason" which is a required variable. Comment should not be confidential also.
![image](https://user-images.githubusercontent.com/12996724/96912343-885d3780-14a2-11eb-8c32-39a08fe07584.png)

### System Details
* Device: web
* SORMAS version: release candidate 1,50
* Android version/Browser: web
* Server URL: test 1401
* User Role: lab officer in Frankensteins Lab in Berlin

**Comment by bernardsilenou** [comment]
In summary rules:
1. Jurisdiction on entity (case, contact, event participant) has full access to entity + sample of entity (this in works fine already)
2. All lab officer users accounts in the responsible "laboratory" of the sample has full access to the sample + entity that the sample is associated to. Normally we would have hidden the sensitive data of the entity from the lab user here, but this not good because lab user need then name of the person to search and manage the sample. We can add a variable to configure this at the server side latter.
3. This condition is about a situation that the reporting user of the sample is a lab user who later transfer the sample to another lab.  If reporting user == lab officer and lab of reporting user != lab of sample then
   3.1 Read access only to reporting user
   3.2 No access to other lab officers in the lab of reporting user. That is, sample and entity records disappear from their repositories

**Comment by bernardsilenou** [comment]
@MateStrysewske please can you check if i have omitted something? The lab users in Nigerian need full assess to the entities they are working on

**Comment by MateStrysewske** [comment]
The fact that lab users don't see personal details of the cases they see the samples for is done on purpose. There is absolutely no reason why someone working in a laboratory should know the name of the person they're processing a sample for. If the Nigerian users need access to the case details, the user rights will need to be adjusted in the database (i.e. give lab officers the user rights to see personal and sensitive data inside and outside their jurisdiction; outside is necessary because lab officers don't really have a jurisdiction besides their laboratory; this is something worth looking into - to make sure that jurisdiction filters apply for lab officers based on the region/district of the laboratory, if they have been specified).

What is definitely a bug here is that lab officers can't edit the reason for the specimen not being adequate for samples that are assigned to their lab. I'll change the title of this issue accordingly and open another one for the change mentioned above.

**Comment by MateStrysewske** [comment]
I just double-checked and there actually is a condition in the code that prevents lab officers from seeing personal case data under all circumstances, no matter the user rights. I think we need a discussion on how to proceed here because I don't think we should generally change that. I could imagine either a new user right that explicitely allows/prevents users from seeing personal data of cases/contacts/event participants or some kind of a server property to toggle on or off whether users on laboratory level are allowed to see this data.

**Comment by MateStrysewske** [comment]
What needs to be done in this issue:
- [ ] Check the region/district/community of a laboratory when determining whether or not users assigned to a laboratory are allowed to see/edit personal or sensitive data

**Comment by MateStrysewske** [comment]
#3267 will take care of the discussion about the access to case data

**Comment by bernardsilenou** [comment]
@MateStrysewske can we close this issue?

**Comment by MateStrysewske** [comment]
@bernardsilenou No, since there's still the issue that the specimen condition reason isn't editable.
