### ISSUE TITLE
Wrong caption for a checkbox in contacts directory filters

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3314]
### Bug Description

The restricting checkbox in the development of #2922 was badly labelled by the developper. The checkbox effect is good and correspond to the issue but the caption is not exact.

### Steps to Reproduce
1. Go to Contacts Directory
2. Develop the filters with "show more filters"
3. The caption is "Only contacts whose source case is linked to their latest event"

### Expected Behavior

The caption should be "only contacts who have an event in common with their source case"

### Screenshots

![Capture](https://user-images.githubusercontent.com/15834125/97418960-c1196880-1909-11eb-9dfd-bccca204fba6.PNG)

### Additional Information

@bernardsilenou @carolinverset @alexandre-gille

**Comment by ftavin** [comment]
@MateStrysewske : @alexandre-gille will submit a PR to fix this today

**Comment by bernardsilenou** [comment]
@ftavin  I think both options have the same meaning. I did a test among some colleagues and they did not easily understand both text. Since this checkbox can be used only after filtering the contact directory based on an event, I would like to suggest the following text:
"Contacts with source case linked to the specified event"
Hope this is fine by you?

**Comment by ftavin** [comment]
@bernardsilenou ok, it's fine for us

@alexandre-gille did the correction and the pull request. He changed the behavior to disable the checkbox if no event is specified (to match exactly your description and the new label)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
