### ISSUE TITLE
Disable selection option 'home' when 'no' is selected for 'home-based quarantine possible?'

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3326]
### Feature Description
Quarantine section in Case and Contact Information forms
### Problem Description
In the quarantine section you can initially select whether home-based quarantine is possible. In the field below you can then select the quarantine type. When 'no' has been selected for the 'home-based quarantine possible?', selection of 'home' as a quarantine type is still a possibility.
### Proposed Change
Since this is contradictory, disable the selection option home when home-based quarantine possible is set to no.

This change would be applicable for case and contact informations (also apply this logic to the event participant information when #3003 is implemented)
### Additional Information
<img width="699" alt="Screen Shot 2020-10-28 at 10 01 21 PM" src="https://user-images.githubusercontent.com/70317594/97497499-dd99bd00-196a-11eb-9505-4777df33bcc2.png">

**Comment by bernardsilenou** [comment]
@kwa20  The fact that you created this issue means the design need to be improved.
It was design like this purposefully because the users needed to know people who are not comfortable in home quarantine. Home based quarantine possible does not mean the person is quarantine at home, it is just additional information of the wish of the person

**Comment by bernardsilenou** [comment]
please think of an improvement and we can discuss it

**Comment by kwa20** [comment]
Since this issue hasn't been touched in a long time I'll close it
