### ISSUE TITLE
SurvNet Adaptations - Create new field “Blood donation in the last 6 months” for cases [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3414]
### Feature Description

Create new field “Blood/organ/tissue donation in the last 6 months” for cases
Cases > Open Case information

New field (only DE) –
„Blut-/Organ-/Gewebespende in den letzten 6 Monaten“ (de – de) | „Blood/organ/tissue donation in the last 6 months“ [SurvNet field name: StatusDonation]

Values (de-de) | (en)
Data Type: Dropdown/enum

• -nicht erhoben- | data not collected
• -nicht ermittelbar- | unknown
• Ja | yes
• Nein | no

### Additional Information
- No dropdown but switches will be used in the UI
- position of the new field: above the outcome of a case
- should also be available in the detailed/custom export

**Comment by GabrielePoggensee** [comment]
IfSG relevant: § 11 (1) 1 d - infection risk
Data are transmitted to RKI

**Comment by markusmann-vg** [comment]
we do it for countries

**Comment by kwa20** [comment]
@markusmann-vg This field seems a bit random in the case form. Wouldn't it be more fitting in the hospitalization tab?

**Comment by bernardsilenou** [comment]
@markusmann-vg 
No international user asked for this variable.
I also think It fits better to the person entity
I see no harm if we decide to add it to the bottom of the person form for all users
If we decode to add to the case, then it would be better to activate it for DE only for now.

**Comment by kwa20** [comment]
@bernardsilenou I'll continue commenting here since this is the right issue.

> With respect to 8. I also agree with you that a date of vaccination should be added. However, I would say we keep the date open and add no 6 months validation for now. We only validate when mapping to SurvNet.

> We may also need to decide if we still need to keep the old data if the person donate blood a second time. I think just last blood donation + date is fine for now, right?

What do you think about this solution?
<img width="423" alt="Screen Shot 2021-01-30 at 4 52 45 PM" src="https://user-images.githubusercontent.com/70317594/106361028-f9bb4a80-631b-11eb-8941-d5918fad9443.png">

I don't think it's necessary or required to keep the old data if the most recent donation is asked for. In this way users would be able to update the date and we wouldn't need any other date as reference. We could then map it to SurvNet ("Blood donation in the last 6 months") as "yes" when last date differs from current date < 6 months and otherwise map it as "no".

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 Unfortunately we can't really add this to the person form because updating the date would effectively remove the information from old cases. So adding a field "Blood donation in the last six months" to the case is actually the way to go here. Germany only.

**Comment by JonasCir** [comment]
@kwa20 Please open an issue for implementation in the converter in the private repo

**Comment by AndyBakcsy-she** [comment]
validated tiket on the latest version f Sormas version 1.57.0-snapshot
