### ISSUE TITLE
Update automatic "Cancel follow up" flow [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3424]
There is a followUpStatus for Contacts and for Cases.  It's an enum with the following values:
`FOLLOW_UP,
COMPLETED,
CANCELED,
LOST,
NO_FOLLOW_UP;`
We should use this to synchronize with climedo, and make sure that the followUpStatus is updated in any reasonable situation 
- [ ] when a Contact is dropped
- [ ] when a Contact is converted to a Case in a system that has Case follow up disabled
- [ ] when a Case classification is set to 'Not a case' in a system with Case follow up enabled. Here, we need to make sure that we don't unreasonably cancel Person's follow up. Imagine a Person has a Contact. The Contact is the converted to a Case. Because of that, the Contact follow up is disabled. Now the Case classification is set to 'Not a case' which disables the person's case follow up as well. We should not have a Person who had a valid (yet converted) Contact and no follow up at all.

_Originally posted by @FredrikSchaeferVitagroup in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3294#issuecomment-721538138_

**Comment by markusmann-vg** [comment]
results from: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3294

**Comment by BarnaBartha** [comment]
After some clarification with Fredrik:
- [ ] when a contact is dropper => set follow-up status to 'Canceled'
- [ ] when a Contact is converted to a Case in a system that has Case follow up disabled => set follow-up status to 'Canceled'
- [ ] when a Case classification is set to 'Not a case' in a system with Case follow up enabled. Here, we need to make sure that we don't unreasonably cancel Person's follow up. Imagine a Person has a Contact. The Contact is the converted to a Case. Because of that, the Contact follow up is disabled. Now the Case classification is set to 'Not a case' which disables the person's case follow up as well. We should not have a Person who had a valid (yet converted) Contact and no follow up at all. => set all converted contacts of case back to follow up status ' follow up' where the followUpUntil date is not in the past and contact status is not set to dropped  (do also when Case follow up is disabled)

**Comment by Candice-Louw** [comment]
@BarnaBartha - _when a Contact is converted to a Case => set follow-up status to 'Canceled'_ - would this logic be applied when importing Contacts (line listing or file) as well, please?  Should we create a seperate issue for this?

Related to: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/147 (After import, converted contact is on "in follow-up" instead of "canceled")

**Comment by BarnaBartha** [comment]
@Candice-Louw @markusmann-vg We can do this also for import but it contradicts a decision we made in #2641 to not execute change logic on contact import.

**Comment by Candice-Louw** [comment]
@BarnaBartha - understood, thank you. 👍

**Comment by MateStrysewske** [comment]
* We should probably integrate the new logic into the existing logic that also updates the follow-up comment.

**Comment by MateStrysewske** [comment]
Seems like the follow-up status is only updated after saving the contact twice.

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest build SORMAS Version: 1.53.0-SNAPSHOT
