### ISSUE TITLE
Admin role has very limited access and edit rights

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3450]
### Bug Description
When the admin is not combined with any other user role, access is very limited, only very few cases are shown and none of them are editable. All contacts seem to be shown but are not editable as well. Same goes for events. Event participants however seem to be editable apart from personal/sensitive data. Maybe this issue is then connected to #2902?

Interesting to note is the missing information of the reporting user which is shown when opening the same forms with other users (e.g. national user, surveillance supervisor).
### Steps to Reproduce
1. Log in as a user who only has the admin user role.
2. Open the case directory and check shown cases.
3. Open a case.
4. Also open a contacts and events.

### Expected Behavior
Admins only have restrictions on seeing personal and sensitive data but would be able to otherwise see all cases and edit cases and contacts. (cf. user rights document)
### Screenshots
<img width="1100" alt="Screen Shot 2020-11-11 at 12 34 27 PM" src="https://user-images.githubusercontent.com/70317594/98809600-13847a00-241e-11eb-86da-1730f5200a57.png">
<img width="1078" alt="Screen Shot 2020-11-11 at 12 38 07 PM" src="https://user-images.githubusercontent.com/70317594/98809651-2b5bfe00-241e-11eb-90ab-ec9ee5946a0f.png">
<img width="1066" alt="Screen Shot 2020-11-11 at 12 38 46 PM" src="https://user-images.githubusercontent.com/70317594/98809408-c4d6e000-241d-11eb-85ae-8bb709f330af.png">
<img width="1075" alt="Screen Shot 2020-11-11 at 12 42 51 PM" src="https://user-images.githubusercontent.com/70317594/98809416-c99b9400-241d-11eb-897e-dc0d701bee64.png">
<img width="1071" alt="Screen Shot 2020-11-11 at 12 57 29 PM" src="https://user-images.githubusercontent.com/70317594/98809424-cdc7b180-241d-11eb-8853-9c0b20fcb53f.png">

### System Details
* Device:
* SORMAS version: 1.51.0
* Android version/Browser: chrome, firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin

### Additional Information
Note on the side: The admin role is the main role that does imports (aside from users that also got the 'import user' role as an addition. Although admins are not supposed to see personal/sensitive data, this data is basically available to them since everything is entered in the import templates.

**Comment by kwa20** [comment]
@MateStrysewske I also checked this for version 1.50.0 and it applies there as well. So this is not actually blocking since it's already on productive systems and the workaround is simply combining the admin role with another user role.

**Comment by MateStrysewske** [comment]
That's not a bug, and it's intended. The admin user role is primarily intended to do technical stuff like creating users. I agree that it's a bit messed up because they're also the only user that by default can do stuff like bulk editing and importing, but that's because the user rights are still based on the defaults in Nigeria where these are things that only a user with a lot of techincal knowledge is supposed to do. National users don't necessarily match that requirement.

Once we have the user role customisation feature, countries will be able to define this based on their needs. For now, there is nothing we can change about it; server admins can change the user rights in the database to grant admins more rights however.
