### ISSUE TITLE
Faulty error message when symptom onset date is set in the future

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3462]
### Bug Description
When symptom onset date is set in the future, error message mentions 'null'.
### Steps to Reproduce
1. Create a new case.
2. Try saving a new case with the symptom onset date set in the future.

### Expected Behavior
Error message should say 'Date of symptom onset cannot be in the future'.
### Screenshots
<img width="579" alt="Screen Shot 2020-11-11 at 7 26 42 PM" src="https://user-images.githubusercontent.com/70317594/98850284-d38cb980-2454-11eb-9afb-b233d45bdc0c.png">

### System Details
* Device:
* SORMAS version: 1.51.0
* Android version/Browser: Chrome, Firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by Seal33** [comment]
The issue is a result of i18n translations. When creating a new field, the caption is generated by `I18nProperties.getPrefixCaption(propertyI18nPrefix, propertyId, field.getCaption());`
In this case `propertyI18nPrefix` is "CaseData" and `propertyId` is "onsetDate".
If no i18n-caption `CaseData.onsetDate` is found, the method will instead look for a caption with just the id `onsetDate`.
If that isn't found either, it defaults to the original fields caption - which was not yet set in this case, and thus returns `null`.

The simple solution is to add the `CaseData.onsetDate` Caption

**Comment by AndyBakcsy-she** [comment]
Validated the issue on local environment on SORMAS Version: 1.52.0-SNAPSHOT
![image](https://user-images.githubusercontent.com/70562142/99791468-56d19d80-2b2e-11eb-9829-c9551e1bb6b8.png)
