### ISSUE TITLE
Allow to set default values for disease, region, district, community and other jurisdiction drop-down fields [5]

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#3507]
## Feature Request

Default value setting for region, district, community and other drop-down fields

### Situation Description 
When contact officers create new cases, they have to **fill in the region, district and community every time**, even if it is almost always the same (since they are responsible for the cases of their own community or district).
It should be possible to set default values for the according drop-down fields, which then are pre-filled from then on.
This would speed up the working process of contact supervisors.
Some fields already are pre-filled, depending on the user role (e.g. the field "responsible region" as "surveillance supervisor", but not as "national user"), at least in the [german play version](https://demoversion.sormas-oegd.de) (1.50.0).

### Feature Description
Create a **right-click event for drop-down fields** which allows to **set one entry as default value**.
The workflow to set a default value should be as follows:

1. Click into the drop-down field
2. Navigate to the value that should be the default value
3. Right-click the value, a one-entry menu opens
4. Click the only entry **"Select this value as default value"**

Now, if you open the same form again for e.g. creating a new case, the field should be pre-filled with the default value.

### Possible Alternatives
Another possible solution would be to introduce a "Defaults" section in the settings, where the administrator could set default values for specific fields.

### Additional Information

![drop_default_small](https://user-images.githubusercontent.com/34276062/99387381-2db5d080-28d4-11eb-90a1-682c7d6f6710.gif)

This issue is created in consultation with @kwa20, based on feedback of German public health departments.

**Comment by markusmann-vg** [comment]
- [ ] In Settings: set default values for case creation 
- Region
- District 
- Community
- health facility

**Comment by bernardsilenou** [comment]
@chThie 
* If surveillance supervisors need to create cases and contacts, you can create a surveillance officer account for them to use. Can this help ?

* Even if we have a configuration for users to set their default jurisdiction, it is much likely that the supervisors may forget to change the configuration each time they create a case which can lead to  then it will cause errors.

**Comment by kwa20** [comment]
@bernardsilenou This is the issue I've mentioned to you before. Often enough, users in the health departments have user roles with a high hierarchy because they need the extensive rights. On local servers, users mostly enter cases, contacts or events in the jurisdiction where the server belongs to. Therefore, being able to define prefilled values will help in reducing the amount of entries users will have to make individually.

The idea here is to give users the option to decide which value they want to set as default prefilled value and make this dependent on the user account.

**Comment by bernardsilenou** [comment]
@kwa20 OK,
Then we can follow the steps mentioned in #1091 merge all and dependent issues and come up with the final specification. Hope users can wait till 2021

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 I feel like the main part of this issue (allowing users to set defaults for jurisdiction fields) is simply a workaround for the missing user rights management. As Kay confirmed, it's basically only needed because server admins are "misusing" the user right system by assignig user roles to users that don't really make sense in terms of jurisdiction because they need the associated user rights.

A temporary solution would be to adjust the user rights on these servers in the database (which is already possible). Adding these fields to the user configuration would only be of use until we have the user rights management, at which point it would be a practically useless feature because it doesn't make any sense in a SORMAS instance that is used in its designated way.

Because of that I would suggest to not implement this issue apart from making sure that a) the user's jurisdiction is automatically selected in dropdowns in creation forms where this is not yet the case and b) if the user has a limited disease or the server only has one disease activated, that disease is automatically selected in dropdowns in creation forms where this is not yet the case. We should rather make sure that we start implementing the user rights management soon.

**Comment by kwa20** [comment]
@MateStrysewske I think the main underlying problem is actually being able to pre-fill specific fields that often enough get filled by the same value and thereby minimize the time needed for data entry. The jurisdiction fields might be highly requested from a solution driven approach but if we look from a problem driven perspective, customizing pre-fill options could ideally even be reusable for other fields.

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske  I also agree with you that the issue we need to focus on is the user management #1091

**Comment by MateStrysewske** [comment]
@kwa20 I just don't really see a use-case for it right here (given that user roles are customisable). Users on a higher jurisdiction level will never have a real default. E.g. a supervisor (region level) is supposed to handle all (or at least most) districts in their jurisdiction, so when they create data, they will alternate between those districts. If they only take care of one district, they should not be a region-level user. I agree that being able to define defaults might make sense at some point, but given how many priorities we have right now, we should only implement that if it's really necessary and makes sense.

**Comment by AliciaRaber** [comment]
According to a high number of cases I see the need of prioritization for this issue.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
