### ISSUE TITLE
Option to set missing geo-coordinates based by one click for all cases/contacts [2]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3545]
## Situation Description

We are on the way to implement Sormas to our district and are ging to import thousands of contacts and cases. They have mainly all an address included, but no geo-coordinates as the data come from an excel-file ....

### Feature Description

It should be possible to create geo-cordinats for the cases and contacts where the are missing.

### Possible Alternatives

The coordinates must be set manually in every case.

**Comment by bernardsilenou** [comment]
@marko958 I do not know if i understand you:
- It is possible to set the coordinate manually after importing the cases
- sormas does not have a db for coordinate fro all addresses in the world and we not also use providers like google. There is an option to configure sormas to your external address db and that will permit you to auto till the coordinates.

**Comment by kwa20** [comment]
@bernardsilenou I think what is requested here is basically to bulk create the geo-coordinates. Right now, users would have to look up geo coordniates themselves and import them. Otherwise they would have to open each imported entity individually to generate the geo coordinates. This is not very practical.

**Comment by bernardsilenou** [comment]
@kwa20 Thanks for the explanation, i understand better now. 
I assume you are referring the coordinates of the addresses, like home address of the case person, right?
how will the bulk adit help here since case persons stay in different houses?
One possibility i can see is to filter the cases by post code, city and assign the same centroid coordinate to all cases, i do not know if this is what they want

**Comment by kwa20** [comment]
@bernardsilenou When address fields are entered, you usually can click the geo button and thereby generate the coordinates automatically. This however is not done during the import. When e.g. hundreds or thousands of cases/contacts have been imported, you would have to go through each entity individually to manually generate these coordinates. Therefore, bulk generating such coordinates would be helpful since they would be missing for such entities. 

Filtering for cases with missing geo coordinates is already possible but still has to be developed for contacts (#3099). 

<img width="619" alt="Screen Shot 2020-11-23 at 4 56 17 PM" src="https://user-images.githubusercontent.com/70317594/99984403-4aa74380-2dad-11eb-89ae-cfaecf98d1cc.png">

**Comment by bernardsilenou** [comment]
I got it now.
I think we need to refine the issue just as your last comment says

**Comment by Marko-ilmkreis** [comment]
@kwa20 @bernardsilenou Would it be an option to set the geo-coordinates automatically when the address is entered an saved? Maybe there could be an option to activate this function, if wanted.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  You can automatically set the coordinate already fro a single case as long as the postal code is provided, but not for many at once.
You can test it here: https://musterstadt.sormas-oegd.de/sormas-ui/

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou I tested it and it still works "only" by clicking the geo-button. A wish were that the coordinates are set automatically by saving the contact/case.

**Comment by kwa20** [comment]
@bernardsilenou I think this is clear. @Marko-ilmkreis Correct me if I'm wrong but I think the main necessity for this issue comes down to the quality of data displayed on the dashboard map. The process of individually having to hit the geo button to generate the data is not always reliable, especially when many entities are imported because users would have to go back to such entities individually to generate coordinates. An automatic process or bulk action would make this much more easy and result in a proper display of the data on the map.

**Comment by Marko-ilmkreis** [comment]
@kwa20 yes, you ar right. The problem is also that some users might forget to click the geo-button when there is a high workload or they just forget it ;-)

**Comment by kwa20** [comment]
Issue Tracker Comment

**Comment by DavidBaldsiefen** [comment]
Conisdering the geo-coordinates are linked to persons (not cases or contacts), would it make sense to add this button to the case directory? Should the button be executed for all persons then, or only those which are selected using bulk actions?

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen 
Suggestions pls:
I think we should not add coordinates to the case.
The coordinate for the cases are the coordinates of the facility of the case, If the case in not in a facility but at home, then the coordinate of the home address are used. So for cases, we only need to specify the coordinates of the facility and all cases in the facility would adopt the coordinate.
- On the map, you can then choose the coordinate type to be used
- The person coordinates that we used in computation and on map is the home address, so to me,  the bulk action should affect home addresses  that are missing  and selected for bulk action, only.
- The system should not work in the first place if there is not  zip-code, right? because you can have the same address in two difference districts

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou @DavidBaldsiefen This are two different things we are talking about. One is the coordinates for facilities, but I was talking about the coordinates for the person. The option should include:

1. bulk action to set the coordinates for the person of cases and contacts 
2. option to select if cases/contacts where the coordinates already set should 
a. be replaced or 
b. should be left like it is. (b ist the default option)
3. Later on integrate this feature is migrated to the persons directory

**Comment by DavidBaldsiefen** [comment]
@Marko-ilmkreis @bernardsilenou 

I was also only talking about setting the coordinates of the persons home addresses. If I understand the system correctly, this will not effect the facility addresses or anything in that regard.
This change would only add the possibility to add coordinates to all persons, where home addresses are set (e.g. zip code and street name), but no coordinates were set. So that instead of clicking on every case, going to "case person" and then pressing the localization button, you just press one button to do that for *all* persons.

> 2. option to select if cases/contacts where the coordinates already set should 
a. be replaced or 

When would you ever want to bulk-**replace** home coordinates? I don't really think this option is necessary

> 3. Later on integrate this feature is migrated to the persons directory

Why not from the beginning on?

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen 

> This change would only add the possibility to add coordinates to all persons, where home addresses are set (e.g. zip code and street name), but no coordinates were set. So that instead of clicking on every case, going to "case person" and then pressing the localization button, you just press one button to do that for _all_ persons.

Exactly this is what we want. It would make sense to have it only working if city and street is entered. Just in case if the zip-code was not known. The house number should not be mandatory for the calculation as there are might be houses without number or not known number.

> When would you ever want to bulk-**replace** home coordinates? I don't really think this option is necessary

Good point. There should be no good reason to replace it. If the user re-enter another address and/or change something on it, he/she must click the button manually.

> Why not from the beginning on?

If this is possible yes. But I understood that the extension of the functions (e.g. duplicate detection) of the person directory is not in the top of the list for development. And therefore this issue could be delayed.

**Comment by bernardsilenou** [comment]
> @bernardsilenou @DavidBaldsiefen This are two different things we are talking about. One is the coordinates for facilities, but I was talking about the coordinates for the person. The option should include:
> 
> 1. bulk action to set the coordinates for the person of cases and contacts
> 2. option to select if cases/contacts where the coordinates already set should
>    a. be replaced or

Suggest we add an extra variable (check box) for this and set to false by default, similar to what we have for duplicate case detection. There can be rare situations that users would like to replace old coordinates.

>    b. should be left like it is. (b ist the default option)

This is fine to maintain as default

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou

Oh no, it seems like I accidentally edited your comment instead of commenting myself, sorry!! 😂

**Comment by DavidBaldsiefen** [comment]
But I have another question: If I press the button to add the missing coordinates for all persons, should that really affect _all_ persons or only those within my jurisdiction? @bernardsilenou

**Comment by bernardsilenou** [comment]
> But I have another question: If I press the button to add the missing coordinates for all persons, should that really affect _all_ persons or only those within my jurisdiction? @bernardsilenou

I suggest it should only affect the persons that the user has full access to  ie persons with 
  - home address in the jurisdictions of the user or
  - if users has full access to at least one entity linked to the person
I think users without full access to a person would not event see the person in the first place. If it possible to see a person if any of the conditions are false?

**Comment by DavidBaldsiefen** [comment]
Upon further discussion I've decided that I would add the checkbox to overwrite existing coordinates (default false)

**Comment by StefanKock** [comment]
Finding by @ChristopherRiedel: Do not show the button if no geo service is configured.

**Comment by DavidBaldsiefen** [comment]
> Finding by @ChristopherRiedel: Do not show the button if no geo service is configured.

I have created a new ticket: #4883 As I won't be able to work on this today. You can close the new ticket if you think this is the better place for that

**Comment by StefanKock** [comment]
Findings by @StefanKock:

- `PersonFacadeEjb.setMissingGeoCoordinates` loads all persons a user is allowed to see, loads all as JPA entities and then does the changes. This will fail at some point (maybe in the thousands, maybe earlier) and make the JPA session grow bigger and bigger which leads to exponential performance decrease. Proposal: Gather personUuids from DTOs, split it into batch runs of 100, move the actual changes to PersonService with new Transaction.
- Bad exception handling, narrow down to a more specific exception (no catch all), use appropriate logging, :
```
				} catch (Exception e) {
					// This exception might be called when an invalid addess was entered, resulting in a server timeou
					e.printStackTrace();
				}
```
- Do not comment in the same line as in the code, move the comment above

**Comment by StefanKock** [comment]
Waiting for `mvn verify` to finish in pull request.

**Comment by DavidBaldsiefen** [comment]
@maxiheyner This feature has been removed with 1.58.1 due to performance concerns, so that it is only available in 1.58 and from 1.59 onwards. I removed the `de-public` label to prevent confusion, but feel free to re-add this

**Comment by maxiheyner** [comment]
@DavidBaldsiefen thanks David, we recognized this during testing,  thanks for removing the tag.

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - is it possible to confirm this for the upcoming 1.59, please?

**Comment by DavidBaldsiefen** [comment]
@Candice-Louw The button should be part of 1.59 again. It might still take a long time to execute the geocoordinate-setter for large databases, but it should no longer cause timeouts/crashes or anything like that.

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - thank you! :)
