### ISSUE TITLE
General person entity 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3560]
### Situation Description
Thus far it is not possible to only handle persons in SORMAS. However, this is highly requested by users since they often want to work with person information by itself. Integrating this feature will also serve as the scaffold for future integrations independent of associations with cases, contacts and event participants. 
### Feature Description
Develop a general person entity that consists of its own directory including filter and search options, creation function, import and export options and merge duplicate function.
From there, allow navigation to respective person information via the Person ID. The forms should provide information about existing linkages to other entities in the system (i.e. cases/contacts/event participants). When navigating to such entities, linkages to other entities should still be shown in person tab and allow navigation while also highlighting the entity the user is currently working on. The person information should also enable the creation of tasks. Furthermore, creating associated entities should be possible out of this form. Also allow navigating to the person information from person forms in other entities.

edit: also include facility filters since facilities can be part of addresses.
### Additional Information
Find mock-ups here: 
[General_person_entity.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/5586264/General_person_entity.pdf)

#2108 represents the first step to this issue.

**Comment by kwa20** [comment]
@JonasCir @bernardsilenou This is the larger issue to the first step integration of the person search. Feel free to give feedback overall and on the mock-ups.

@markusmann-vg This issue would be following issue #2108. Since this is still a very large issue, feel free to suggest how to split it further if necessary.

**Comment by bernardsilenou** [comment]
@kwa20 Danke!
Nothing to add for now.
We are still working on refining this issue but from our point of view  #2108 is ready for implementation in 1.53

**Comment by Johannes-Schmidt-GA-RT** [comment]
The mock-ups look great! I would just switch "case" and "case person" an rename "case person" to "person". Then it makes no difference whether you are in the case or in contact. 
Please hurry up with this feature, it is extremely important to us.

**Comment by Marko-ilmkreis** [comment]
@Johannes-Schmidt-GA-RT I agree also that this feature is very important for our office too.

Thanks to @kwa20 for the good mock-ups.

**Comment by bernardsilenou** [comment]
A user should be able to just create a person to stand alone in the system and can latter decide to link it to entities like cases, contacts, etc

**Comment by JonasCir** [comment]
@bernardsilenou Yes please as this allows us for very flexible applications in the future. Imagine the case of returning travelers again which need to be recorded, but likely never become symptomatic. With this, you could just automatically store them, tag them with a label and remove them after a time X to keep your system clean.

**Comment by kwa20** [comment]
@bernardsilenou We also need to decide what happens to persons then don't get linked to entities after a while because we need a reason for them to stay in the system.

**Comment by JonasCir** [comment]
This could be justified by a label which provides a reason e.g., returning traveler, vaccination study participant, preregistered for reason XYZ. Labels should be created by the admin and we could decide to ship SORMAS with some reasonable default

**Comment by Marko-ilmkreis** [comment]
@JonasCir Travel returning travellers are currently entered as contacts. There is a field there to mark them accordingly. After consultation with our team for the travel returnees, they must also prove a test, so that this can/must also be recorded.

The person entity should only stand for the natural person and provide an overview if they were/are already a case/contact and maybe later if and when samples are taken.
Of course, it should be possible to enter a person and then create a case/contact for it, that would be great.
To keep the data collection simple, we should not open a third category (person) next to contacts and cases where data can be entered.

I would suggest that there is a possibility for the administrator to delete the data. I would set a deadline of 1 month, but leave this configurable. All personal data older than one month should be deleted.

**Comment by kwa20** [comment]
@JonasCir I think the link to any entity (case, contact, etc.) itself will be the justification for keeping the person in the System. @Marko-ilmkreis I think similarly to what you proposed, this will also be the overall plan considering the deletion concept. For persons standing alone in the system that might actually be straight forward.

**Comment by JonasCir** [comment]
@Marko-ilmkreis Yes, you're right and I'm aware that ret. travelers are stored as contacts. However, this was a dirty hack (due to time pressure) to support returning travelers :D It's not a clean design at all, as ret. travelers are not contacts.

I understand the need for you to preserve a clean person directory, I am completely in favor of that and it was one of the first requirements that @bernardsilenou and I identified. Mixing recorded persons and data of live cases is bad and must be avoided.

On the other side, the general person entity allows us to properly model returning travelers, self registration of persons(there is a lot of 3rd party work going on to provide the health offices with data) and the like. This entity provides us with a generic landing pad to support these (future, potentially yet unexplored) use cases almost out of the box.

Based on the tag, we could decide if the person record should show up in the directory by default(cases, contacts, event participants should be default). If we are searching for a traveler, we could filter and search just for the persons with the corresponding tag applied. 

By this we can have our cake and eat it too :)

**Comment by JonasCir** [comment]
@kwa20 Yes the link should serve as criteria, otherwise retention period could be determined per label and system settingf

**Comment by JonasCir** [comment]
@kwa20 Now we have #4019 being concerned about the import of returning travelers, thanks for filing @Marko-ilmkreis :) I advocate to implement this issue first, to have a proper solution for #4019

**Comment by Marko-ilmkreis** [comment]
@kwa20 @JonasCir From our side the person entity (this ticket) is much more important then the traveller import.

**Comment by Johannes-Schmidt-GA-RT** [comment]
for us too. I thing this is the most important ticket.

**Comment by JonasCir** [comment]
Got it thank you :)

**Comment by StefanKock** [comment]
Check what gap is there when #2108 is done.

**Comment by bernardsilenou** [comment]
immunization tab + basic person filters are missing in the current mock up.
Updated version from #4081

![image](https://user-images.githubusercontent.com/12996724/105441284-83a64c00-5c68-11eb-9dd3-6c7304737fb9.png)

**Comment by Marko-ilmkreis** [comment]
@kwa20 @bernardsilenou Is there anything we can do from our side to lift this issue into a higher priority?

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  Sorry for the delay. We did not forget this issue.
The team has been working on the prerequisite issue #2108 and hope to have it completed in the next release.
After that then we would work on this one.
Hope this is fine by you?
There is nothing to be done for now I suppose
@kwa20 did I forget something?

**Comment by kwa20** [comment]
@bernardsilenou you're right. This issue should also directly follow #2108 as well, i.e. it's not just a prerequisite but partially covers features described in this issue.

**Comment by Marko-ilmkreis** [comment]
Thank you for the work on #2108 so far. I just want to mention, that the person entity must come with a duplicate merge function from the beginning. I see in our Sormas a lot of duplicates.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis This feature does not allow the creation of persons without any associated case, contact or event participant (and it will never allow that), it's actually "only" a person directory and a list of associated cases, contacts and events when opening one of these persons. A retrospective duplicate merging function for persons already existing in the system would be something for a follow-up issue.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske its not "only", its a great work. Thank you all for that. I will open an follow-up issue.

**Comment by kwa20** [comment]
@MateStrysewske @Marko-ilmkreis This issue is exactly that follow-up issue :)

**Comment by Marko-ilmkreis** [comment]
So then I close #4411 and we are using this for further imporvement.

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 I suggest to turn this issue into a collective concept issue and move any follow-up tasks to individual issues. As far as I see it, there are three tasks that come out of this:

* Allow users to directly create cases, contact or event participants from within the person form by adding buttons to the headers of the lists
* Display the list of cases, contacts and event participants in every person form, not only when opening a person from the person directory
* Add a retrospective duplicate detection for persons; this is a very tricky and complex issue because it might require to also do a follow-up duplicate detection of associated cases, contacts and event participants (the latter two not being implemented yet) - we need to define this; maybe it's okay to ship such a feature without the follow-up detection

Anything I've missed?

**Comment by kwa20** [comment]
@MateStrysewske I'd include the export (basic/detailed) function. basic would follow what we have elsewhere, meaning we export what is seen on the directory and detailed including all further person form information.

 I remember the independent person creation being heavily debated so an import function would only make sense if this would be available.

**Comment by MateStrysewske** [comment]
@kwa20 I'm heavily against the independent person creation because it contradicts a lot of principles that a) make sense from an epidemiological point of view and b) in terms of data minimalism, but I think that's something we should discuss again.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 
- I suggest we to not add the option of exporting the person entity.
- I also think we should not create stand alone persons. But we can add further entities to the persons that already exist. This is @MateStrysewske first point.
- A nice export i can see from the person perspective is to add an export on the person form to export all entities linked to the person, ie person based export.

**Comment by Candice-Louw** [comment]
+1️⃣  from CH users for development of this, please (especially the 'merging duplicates' aspect of it).

**Comment by kwa20** [comment]
Exports covered in #6206
