### ISSUE TITLE
New Column "Death count" in event directory

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3562]
### Feature Description

A new column in the event directory that indicates the count of death would be useful for monitoring.

This value would be computed as follow : for each event we count the number of linked cases that have outcome = deceased.

@bernardsilenou @carolinverset

**Comment by ftavin** [comment]
Question : should this column be sortable ?

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
YES, this field should be integrated into the export to allow internal reprocessing as needed

**Comment by bernardsilenou** [comment]
@carolinverset @ftavin 
Some suggestions from my side:

* I suggest we add total number of resulting cases also. It is good information to know the baseline for which the number of death is calculated and also possible to compare death proportions across events since just the number of death can give misleading information. This is just part of the logic to calculate number of death described below.


* suggested logic to apply on event participant table:
event_id = the selected event id
and
resultingcase_id != NA 
and
deleted = FALSE
and 
no duplicate resultingcase_id (this should normally not be need, butt in the past, we did not have validation rules to prevent this)
 and 
 filter case table  such that resultingcase_id == case_id, deleted = f (sum this to get number of cases)
 filter case table such that resultingcase_id == case_id, deleted = f, outcome = death (sum this to get number of death. )
 
We then recalculate this sum each time the evet is modified as usual.

**Comment by ftavin** [comment]
@bernardsilenou 

I think your first suggestion corresponds to #3276

**Comment by bernardsilenou** [comment]
@faatihi That is right, thanks, so it will be better to implement both at once , right?

**Comment by ftavin** [comment]
@bernardsilenou there already is a PR for #3276 from @Seal33 since 15 days

**Comment by Seal33** [comment]
I think I can relatively easily add this to my current PR, if you want @ftavin 
Actually the most difficult parts right now are contact counts, case count and death count should be implemented with a few lines.

**Comment by ftavin** [comment]
@Seal33 : would be great !

@carolinverset

**Comment by bernardsilenou** [comment]
@Seal33 Whats complicated with contact counts please?

**Comment by bernardsilenou** [comment]
@Seal33 Many thanks to add this to the earlier pool request. We plan to add this feature to 1,53. Will it be possible for you to complete this in this sprint? Thanks

**Comment by Seal33** [comment]
@bernardsilenou 
I've got deathcount, casecount and contact count where source case _isn't_ part of the event ready.
So mainly I've got a lot of polishing to do, including making columns sortable (currently, sortable columns make the backend fail).
The Milestone for 1,53 is 04.12.2020 if I'm not mistaken, so I should definetely be done till then. But I'll try to get done this week.

**Comment by bernardsilenou** [comment]
@Seal33  Thanks

**Comment by carolinverset** [comment]
@Seal33 Thank you very much for this work !!! 
Have a nice evening !

**Comment by raghupola-vg** [comment]
Are the Fatalities and Case count sortable? At the moment it doesn't look like.

**Comment by MateStrysewske** [comment]
@raghupola-vg No, they're generated properties that can't be sorted.
