### ISSUE TITLE
Show event participant creation window when linking a contact to an event [1]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3566]
### Feature Description
#3133 added the possibility to link a contact to an event directly from within the contact by creating an event participant. This process does not involve opening an event participant creation window; it's all done automatically. Because of that, no involvement description is given, which results in an event participant without an involvement description being created even though the involvement description is a required field.

### Proposed Change

* When linking a contact to an event, the event participant creation window should be opened to allow the user to enter an involvement description
And
* Remove the requirement (optional instead of mandatory) from the involvement description field; this may be something to consider anyway because it might be a redundant field if someone is entering event participants e.g. for a concert (the involvement description will probably just be "took part" most of the time)

**Comment by kwa20** [comment]
@MateStrysewske I agree that the involvement description doesn't have to be compulsory. Since we need to choose an event to link the contact to anyway, do you think it might be possible to show the involvement description in the same window?

<img width="866" alt="Screen Shot 2020-11-24 at 12 01 13 PM" src="https://user-images.githubusercontent.com/70317594/100093850-63b8fe80-2e58-11eb-925f-265ac746dc82.png">

 I assume this might be difficult since it relates to a different entity. If it's possible, though, users won't have to navigate through two windows.

Otherwise only a window with the involvement description could be shown after selecting the event since this represents the event participant entity thus far. This is what you've already described I guess.
<img width="480" alt="Screen Shot 2020-11-24 at 12 01 57 PM" src="https://user-images.githubusercontent.com/70317594/100094091-c90cef80-2e58-11eb-80e1-9068fc2b815c.png">
The separation of such windows also becomes very relevant when #3003 would be implemented.

**Comment by MateStrysewske** [comment]
@kwa20 Adding the involvement description to the "Pick or create event" form would theoretically be possible (of course not with automatic databinding, but that would be fine); the problem is more that, in your mockup, it looks like the field is actually also used for filtering (because it's in the same section as the other filters). I think in terms of workflow, it's hard to fit it in there, but we'll have a look at it in the next sprint and see whether it's possible somehow.

**Comment by kwa20** [comment]
@MateStrysewske You're right, that might not be logical. We could also move the field underneath the event list.

**Comment by kwa20** [comment]
This actually applies to cases as well when linking them to events through the case form.

**Comment by syntakker** [comment]
When linking a contact person to an event, the dialog title reads "Create new person"
![image](https://user-images.githubusercontent.com/5616564/104937245-d2748d00-59ad-11eb-8a04-e899d29480cc.png)

This is misleading, since the person is already registered. A better wording would be "Add new event participant".
I think this would be preferable when starting from the event participants tab, too. The button to get started from there already reads "Add person". Here, too, "Add participant" would be more consistent.

**Comment by bernardsilenou** [comment]
I vote for "Create new event participant"

**Comment by syntakker** [comment]
I opted for "Add new event participant" since this dialog is also shown when linking a contact to an event. In this case, no new person is created. If it is really about creating a previously unknown person, this is somewhat subsumed by "Add  new ...".

**Comment by raghupola-vg** [comment]
@syntakker The existing window was used and no changes were done to the title. Please create a new change request for the title change

**Comment by syntakker** [comment]
I would advocate to fix it here. The window existed before, but it is the new context which makes the dialog title misleading (in the use cases before, a new person was indeed created).

**Comment by MateStrysewske** [comment]
@raghupola-vg @BarnaBartha After thinking about it again, I think @syntakker is right that it should be fixed in this issue. The title is indeed misleading - all the time, not only in this case, because this particular window is always primarily about creating an event participant.

**Comment by raghupola-vg** [comment]
verified on latest deploy, the title has been changed as desired
