### ISSUE TITLE
Add mass generation of quarantine documents [3]

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#3575]
Version 1.51 of SORMAS allows for the generation of documents for cases.
But doing this manually for dozens, maybe hundreds of cases takes a very long time and is not feasible for large amounts of data.

Please add the option to automatically generate multiple documents at once.
Ideally this would be integrated directly into the list of all cases with the possibility to use filters and then select for which of the results a document should be generated.

As stated in issue #3544 SORMAS should also include the option to automatically send the quarantine document by email as a PDF document.

### Development Specifications
* Add a new bulk action to the case and contact directories: "Create documents"
* Clicking on this action opens a popup window that allows the user to select the document template they want to use (similar to how it's done when creating a document for a single case/contact); actions for this popup should be "Cancel" and "Create"
* All additional fields that can be filled in when selecting a document template for an individual case or contact also need to be displayed in this popup and users should be allowed to fill them
* Clicking on "Create" then should create the document for all selected cases/contacts; display a tray notification with the text "Documents successfully created" when the creation process has finished
* Generated files should be zipped and that zip should then be downloaded; name the zip file "sormas_documents_{date+time}" (similar to how export files are named)

**Comment by JonasCir** [comment]
@syntakker @Seal33 FYI :)

**Comment by syntakker** [comment]
@JanBoehme1982 The workflows in instutions using SORMAS differ widely in places where batch generation of documents is used. WIth the generation of documents on a per-case basis, many of these workflows can be implemented by adapting the process:

- At a certain point of the process, it is decided to order quarantine for a specific case. Besides entering the respective data (quarantine start and end date etc.), the respective document can be generated already here with a few clicks (per-case instead of batch mode later in the process).
- Generated documents are collected then by saving them to a designated folder (at generation time), further batch processing starts from there.
- Implementations outside SORMAS (mostly data from Excel/Access -> serial letter in Word) produce at some point of the process exactly this result: a folder of generated documents. By identifying this point, the necessary adaptions to the process should become clear.

Can you provide feedback on use cases, where these adaptions of the process are not sufficient to achieve the desired result?
A first candidate might be a notification of all participants of an event in batch mode.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by leventegal-she** [comment]
Event participants also have Quarantine order documents, do we need mass generation for them too?

Currently there as a sample and a pathogen test selector on the document generation dialog. In bulk mode it doesn't make sense to display them but we could use a sample and test by default. Maybe the latest positive one?

@MateStrysewske @markusmann-vg What do you think?

**Comment by DavidBaldsiefen** [comment]
Why is this in interactions instead of application?

**Comment by syntakker** [comment]
@leventegal-she there's currently a preselection rule for sample and pathogen test, however it applies to cases with only one sample and one related pathogen test.
In the list view for event participants there is a column for samples, here the newest sample is shown, if there are several, the positive ones precede the others (see `EventParticipantFacadeEjb.getIndexList`, l. 261 ff). So best would be the first result ordered by sample date (newest first) and result (some reasonable including positive > negative).

**Comment by JaquM** [comment]
@leventegal-she 
if easy possible, yes please add this for event participants aswell

**Comment by MateStrysewske** [comment]
@leventegal-she I agree that we should automatically choose the newest sample with final laboratory result = POSITIVE, and the latest pathogen test with test result = POSITIVE from that sample; if there's no positive sample, we'll just use the newest sample and its newest pathogen test. Please make sure that you use as few queries as possible to retrieve this data (so ideally only 2).

**Comment by leventegal-she** [comment]
* Added bulk action on the case/contact/event participant directory
* No sample and pathogen test selector shown on the create document dialog
* Uses the latest positive sample and it's latest positive test if exists, otherwise the latest sample with it's latest pathogen test
* Single document generation from the detail pages works as before; with sample and test selector

**Comment by kwa20** [comment]
@syntakker @leventegal-she The document configuration section is structured in a way that allows users to use any kind of document templates and it's no longer only used for quarantine orders. Since we also don't have quarantine information for event participants, we should probably make the string names more generic to fit many use cases. Do you think we could cover this in this issue? I'd suggest to rename "create quarantine order documents" to "create documents" and headers associated with "quarantine orders" to "documents".  Would that be fine with you?

**Comment by MateStrysewske** [comment]
@kwa20 I think we run into a problem then because we also have a feature in the current sprint that adds the general "document" module to cases and contacts. You would then have "Documents" twice in there. I think this is probably something we should properly think about for the next sprint because I can totally see users getting confused because of the wording, and because it's not really clear what the purpose of the two individual modules is.
