### ISSUE TITLE
Error when sorting countries by name or UNO code

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3675]
### Bug Description
When inside the country infrastructure, sorting by country name results in an error. Sorting by UNO Code is also faulty since its sorted by number sequence rather than order.
### Steps to Reproduce
1. go to the country infrastructure in configurations.
2. sort columns 'name' and 'UNO code'

### Expected Behavior
Name column would be expected to sort alphabetically and UNO code by the order of numbers.
### Screenshots
<img width="1142" alt="Screen Shot 2020-12-03 at 8 19 02 PM" src="https://user-images.githubusercontent.com/70317594/101077809-a2139380-35a5-11eb-87f1-5582f171b1a2.png">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
Abnormal behavior also occurs in the search field:

![image](https://user-images.githubusercontent.com/12996724/101105783-bfa92300-35ce-11eb-9645-7c2e71f1a16b.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou Create this as a separate issue please, and please write down the problems, don't add them to the picture because that's a) easy to miss and b) kinda hard to read.

**Comment by MateStrysewske** [comment]
@kwa20 Sorting by name is a bit tricky and can't really be done perfectly because we can only sort on what's directly in the database, and the values in the UI are translated; so the sorting will be perfect on an English server, but not on e.g. a German one. Still, better than not being able to sort at all. We might find a way to do this more accurately in the future.

Concerning the UNO code, the default import actually was wrong here. Afghanistan for example shouldn't have the code "4" but "004", which also fixes the sorting. You might have to drop all countries from the databases on the test servers and re-import the countries after the hotfix has been rolled out, I've corrected this mistake.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT

**Comment by kwa20** [comment]
@AndyBakcsy-she Were you able to also verify if the uni code gets imported with every entry having 3 digits? Since I imported the file the first time it was available, another import failed because it would produce duplicates (to be expected).
