### ISSUE TITLE
Sormas Import should handle UTF 8 with BOM [1]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3747]
### Feature Description
Currently the import is very strict and only accepts UTF8 without BOM.

### Problem Description

As the local health authorities getting also list from clusters like school, elderly cares, the lists are generated by Excel. There is, in our case, a second Excel file, which imports the the rows in the right format an add the field descriptions. 

If you then export the file as csv in Excel, this will be UTF with BOM, wich cannot changed at this point. The user have to use a second tool (like Notepad++) to change the encoding to UTF8 without BOM. As the users very often doesn't have an IT background they are struggling at that point.

### Proposed Change

Implementing the import of UTF8 with BOM

### Possible Alternatives

Sormas accepts the direct import of Excel-files.

**Comment by AndyBakcsy-she** [comment]
Verified issue on the local environment on SORMAS Version: 1.54.0-SNAPSHOT

**Comment by kwa20** [comment]
@Marko-ilmkreis Since you are also using excel to create the import data, may I ask you if you face a similar problem? I successfully imported data with the encoding UTF-8 with BOM, so I was able to verify this issue. However, when I'm filling a template with umlauts and save the file as csv and UTF-8, excel automatically encodes it as ANSI instead of UTF-8 with BOM now, which results in a critical error during the import.

**Comment by Marko-ilmkreis** [comment]
@kwa20 I haven't had this issue. Excel usually have to option to select fore a csv file. One is based on UTF-8 and the other is based on the Windows encoding. Maybe you wrongly select the other one?
I'm not in office for two weeks, so I cannot provide screenshots.

**Comment by kwa20** [comment]
@Marko-ilmkreis Thanks a lot for your feedback on a sunday! I think I'm using the right option, which is the comma delimited one. When I reopen the saved file in Notepad++, ANSI is shown as the encoding. Here some screenshots:

<img width="605" alt="importTemplateSave" src="https://user-images.githubusercontent.com/70317594/106383304-735b4300-63c5-11eb-8339-889c71e8c9f2.PNG">
<img width="110" alt="importTemplateSaveANSI" src="https://user-images.githubusercontent.com/70317594/106383306-748c7000-63c5-11eb-98af-b5497e4a402a.PNG">
 
I just fear that users might have the same problem and don't realize it since they seem to properly save it as csv, UTF-8 with/without BOM

**Comment by Marko-ilmkreis** [comment]
@kwa20 I just checked it again

In Excel 2010 it looks like your screnshots from Excel, but saved successful in UTF-8 (surprisingly without BOM).

At work we are haveing Office 2016 and 2019 (deping how new the computer is. Ther it looks like the screenshot below and you have the two options for csv-files.

Thats why I haven't had the mentioned issues. Maybe it could be a good idea to show an datailed arreor when the import failes beacuse of the enconding (e.g. "the file is encoded in {encode-format]. Please use UTF-8").

![grafik](https://user-images.githubusercontent.com/74791118/106396397-eab1c680-6407-11eb-8d93-5b75c099a05d.png)
