### ISSUE TITLE
 Modify the modalities of the drop-down list of the nature of the tasks to be assigned

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3752]
### Feature Description

In the context of the investigation of an event, the current modalities of the drop-down list relating to the nature of the tasks to be performed are limited to "investigating the event" and "other task".
We propose to complete the terms of the drop-down list.

### Problem Description

The current list of tasks to be assigned as part of the management of an event is not sufficiently detailed

### Proposed Change

In order to optimize the use of tasks, we suggest adding three other modalities:
- continue the investigation following a change in the signal
- Follow an event already investigated
- Request for an investigation report / request for a summary / additional information to be collected

### Additional Information
@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
@carolinverset  I have questions related to the options:

1.  continue the investigation following a change in the signal : 
It is not advisable to use the word "signal" since it is used as an event status, suggest to use "continue investigation due to modification in the event" or "continue investigation due to re-notification of the event"

2.  Follow an event already investigated (I do not understand how this differs from point 1)

3.  Request for an investigation report / request for a summary / additional information to be collected:
Can we replace with "Request for a report" . This is because there can be many types of report, and in the text we can then specify the type of report: investigating, followup/ actions, etc

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin
For point 1 and 3: no problem to change the name of the task and take the terminology you suggest

For point 2 : 
When the investigation of an event is completed, it may not be closed immediately. Sometimes the investigation must be extended by less intensive surveillance, which can be carried out by another team. The idea would then be to assign a task to a person from another team to carry out this monitoring.

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
Following our last exchange, we agree to remove the modality relating to the follow-up of the event which is probably too sopecific to France and to certain regional organizations. Therefore, we will keep only the other two:
- continue the investigation following a change in the signal
- Request for an investigation report / request for a summary / additional information to be collected

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg Dev France plan to work on this story for 1.54
