### ISSUE TITLE
 Add the signal evolution date in the event file and in the event directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3753]
### Situation Description

It often happens that a signal relating to an event is supplemented by information received several days / week after the initial signal. Currently SORMAS offers the date of the signal (not modifiable in the HMI), and the date of the event which can be modified.
The teams in the field tell us the need to have two date fields to trace on the one hand the date of the initial event and, on the other hand, the date of change of the signal (today the teams modify the date of the event but thus overwrite the information on the initial date of the event).

NB: This date is different from the date of modification of the signal which is updated automatically with each intervention on the event file (eg: correction of a typing error); the requested field will be entered by the investigator who is informed by a partner that the initial situation has changed and that the investigation must resume

### Feature Description

We propose to complete the event sheet with a second date block allowing teams to enter the last modification date of the signal. This information is essential and should also be included in:
- the event directory
- the actions directory
- basic and detailed export
### Additional Information
@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
* Add a date variable "Date of last modification" to event
- Default value = NA
- Do not validate this date with any other date, user has to enter this date manually.  This is because not all modifications need to result in updating this date. 
- To know what the last modification was about, it may be good to add the " general comments" variable to events.

@carolinverset  The date of last modification can be before the date of last action, hope users will not get confused when added to the actions directory? because we are assuming here that:  date of last modification of event  is not equal to date of last action of event.

**Comment by bernardsilenou** [comment]
@MateStrysewske any comments ??

**Comment by MateStrysewske** [comment]
Nope :)

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin
Excellent idea to add a comment field to specify the nature of the modification

In my opinion, having a last modification date before the date of the last action is not problematic. And the possible confusion for the user will be removed with the comment field that you mention and which allows to specify the nature of the modification of the event

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
I have another small request: could the "general comment" field that accompanies the modification date also be integrated into the detailed export of the event directory?

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg Dev France plan to work on this story for 1.54

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset

we did not indicate in this issue the name of the new field. I like the word "evolution" to insist on the difference with the technical "last change" field

@aponcon-atolcd just finished the development using the name signalEvolutionDate, corresponding to the title of the issue but this leads to the question : should this field be limited to events of type "Signal" ? should we name it otherwise ?

Thank in advance for your quick answers as time is running for 1.54 ! ^^"

**Comment by carolinverset** [comment]
@ftavin @aponcon-atolcd @bernardsilenou 
In my opinion, the term "signal" is suitable. At the beginning, a signal reaches the teams to indicate that a potential event, cluster ... has been detected. It is only afterwards that the teams characterize this signal as an event or cluster.
So when the situation evolves, the teams receive a new signal for that event or cluster. It is in this sense that I think that the term "signal" is adapted.

Therefore, I  think that the name of the variable can be "signalEvolutionDate"

**Comment by bernardsilenou** [comment]
@aponcon-atolcd  questions pls: Since this variable is not limited to signals only , what name is used as the caption in the forms? "evolution date" ?

**Comment by aponcon-atolcd** [comment]
Hi
That's currently ```Signal evolution date``` for the date field and ```Nature of the signal evolution``` for the comment field.
It can be changed if needed of course.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset 
Note that @aponcon-atolcd will be on meetings all day long so if we change the name it will have to be for 1.55 (tofay is the feature freeze)

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin 
As I indicated above, personally the date of evolution of the signal corresponds to the need. At the start of the process, the investigators receive a signal to investigate and then, depending on the investigation, to classify as an event, cluster or screening.

**Comment by MateStrysewske** [comment]
@ftavin There definitely needs to be some clean-up work on the PR at least because there are merge conflicts. Is someone else from your side able to do that? Otherwise, we'll have to delay this feature to the next release anyway.

**Comment by ftavin** [comment]
@MateStrysewske

@aponcon-atolcd will have some time between meetings so he may be able to handle small changes and merge-conflicts, his time will just be limited.

Of course I am aware that if there are major issues to correct, the feature will be delayed

**Comment by MateStrysewske** [comment]
Okay, @bernardsilenou could you please asap make a decision whether the naming of the field (signalEvolutionDate) is fine for you?

**Comment by bernardsilenou** [comment]
Dear All,
Sorry to reply late, still catching up on old emails:
Rather than delaying, we can merge the PR as it is,  we can rename later if needed.

@carolinverset I totally agree with your logic. The issue why I suggested that we change the naming is because when an event of status ==  signal is created, then we have the "signal evolution date" on the form. When the signal is latter changed to a cluster  or event, then on the event form, we would have variable called "signal evolution date" rather than "event evolution date" or "cluster evolution date".
In order for users not to get confused, I was suggesting that we just use "evolution date" and this would then apply to signal, screening, events, cluster.
Another option is to use the name of the status as prefix on the forms; eg "signal evolution date", "event evolution date", "cluster evolution date", etc. This may need additional logic added.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset 

Looks like the issue was not merged on friday so I think it will be delayed to 1.55 => we can change the label

**Comment by AndyBakcsy-she** [comment]
Validated ticket o the latest version of SORMAS
Version: 1.55.0-SNAPSHOT
