### ISSUE TITLE
 Notification to the investigator of an event when a person attending an event becomes positive for COVID

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3794]
### Situation Description
The management and investigation of an event leads teams to understand the characteristics of an event, the actions implemented and the people participating in the event. To date, the list of people participating in an event is static and has not changed. However, it would be interesting for SORMAS to alert the person in charge of the investigation when a person becomes positive for COVID and becomes a case. The objective would be to optimize the uses of SORMAS, in particular for monitoring clusters and chains of contamination by developing a mechanism that informs the investigator as quickly as possible of the evolution of a status of a person involved in an event. 

### Feature Description
-	The creation of a case / the transformation of a contact in the event of a person participating in an event triggers an automatic task (note, this automatic task should be individualized because the activation of all automatic tasks is inconceivable) and a notification addressed to the person in charge of the investigation. For contacts of a case and / or for participants in an event (eg screened in a group)
-	Ideally and if possible, the events for which the mechanism is triggered would be configurable : only the events for which this option is activated would be subject to such monitoring. The advantage of making this mechanism optional is that it does not increase the sending of notifications and limit them only to events / clusters deemed critical.

### Additional Information
@ftavin @bernardsilenou @Olivierleuci

**Comment by bernardsilenou** [comment]
* we can implement this after or with #3751 
* when event participant (ep) is converted to case, inform responsible user of event. information should contain the case uuid, event uuid and case classification eg "A participant in event WMQBEI is liked to a case with id WMQBEI"
* we do not necessarily need to show the name of the case person because the responsible user may not have full access to the ep nor the case.
* We also need to decide if we inform the responsible user when a case is retrospectively linked to an event.
I suggest we use the contrail that:
if  current date - report date of case <= 30 days, inform responsible user, else do not. If event is archived and this date is date validation is true, also inform responsible user.

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske 
Any further refinement you can think of ?

**Comment by bernardsilenou** [comment]
@Chinedar do you also have any comment about this?

**Comment by bernardsilenou** [comment]
The goal of this issue is related but not the same as #3853. One is based on test result and the other if the case already exist

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg  Dev France plan to work on this story for 1.54

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 
The final mecanism discussed and validated this morning :

When a person becomes a confirmed case of a particular disease:
- we search for all the events for which it was a participant for this same disease within X days (same value as the detection of duplicate cases)
- we notify the user in charge of the investigation for these events (with the exception of the user reporting)
- if the same person is reponsible of several events, we send several notifications (1 for each event)

The text of the notification will be as follow:
_"A person that participates to the event of id XXXX has been identified as a confirmed case (id YYYY).
Please check if the link should be explicitly created between this event and the case."_

**Comment by bernardsilenou** [comment]
@kwa20 @Candice-Louw Please can you have a look at the summary from @ftavin  above and add comment is something if missing?
Just to explain some points from @ftavin refinement in another way:
. "with the exception of the user reporting" == do not notify if reporting user of case == responsible user of event
. only notify when case classification == any of the "confirmed" categories.

**Comment by kwa20** [comment]
@bernardsilenou Sorry for the late reply. It is mentioned in the issue, that this might be a configurable feature, where enabling of such notifications could be done for individual events. Can you elaborate on how this will be implemented? I think it's a good idea to prevent massive amounts of notifications appearing, that might be overwhelming. If this is still unclear, we could introduce a configuration in the database that enables this feature overall and maybe add a checkbox for users to mark the desired events, for which those notifications should be triggered.

Otherwise, I'd only change the specific text in the notification:
_"A person that was an event participant in the event "(title)" (id) was identified as a confirmed case (id). Please check if an explicit link should be created between this event and this case."_

I think at least the title here might be useful to add because it gives the notification more meaning. Otherwise, users will have to check the id's first in order to know exactly what the context is. For servers with more enabled diseases, adding the event disease might be useful too.

**Comment by bernardsilenou** [comment]
Thanks @kwa20 
* We decided to drop the entity specific configuration in this issue. We would create another generic issue for it if needed.
* Your text is very good. I added the disease to it.
"A person that was an event participant in the event "(title)" (id) was identified as a confirmed "disease" case (id). Please check if an explicit link should be created between the event participant and the case."

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @kwa20 

The title can't be added to the notifications as it may contain private informations.

**Comment by carolinverset** [comment]
@ftavin 
we could keep the same text but remove the title.

**Comment by Candice-Louw** [comment]
@bernardsilenou @kwa20 @ftavin @carolinverset 
Thank you for the great feature suggestion and refinement. 👍 Nothing more to add.

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of SORMAS Version: 1.54.0-SNAPSHOT on the local environment .
