### ISSUE TITLE
"no risk contact" contacts under follow-up do not appear in follow-up view

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3909]
### Bug Description
Contacts with the contact category "no risk contact" that also have a follow-up status "under follow-up" do not appear in the follow-up view.
### Steps to Reproduce
1. Make sure there are contacts with respective statuses and categories in the system.
2. Look for such contacts in the default/detailed view compared to the follow-up view.

### Expected Behavior
All entities with an "under follow-up" status should appear in the follow-up view. 
### Screenshots
<img width="1111" alt="Screen Shot 2021-01-04 at 6 44 36 PM" src="https://user-images.githubusercontent.com/70317594/103564970-bfe35980-4ebf-11eb-85a1-f758bfb3558c.png">
<img width="1120" alt="Screen Shot 2021-01-04 at 6 50 29 PM" src="https://user-images.githubusercontent.com/70317594/103564982-c540a400-4ebf-11eb-88a7-f0c28d239e6c.png">

### System Details
* Device:
* SORMAS version: 1.53.0/1.52.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 The "follow-up visit" overview only shows contacts for which the follow-up period falls into the date filters on the top right of the grid. In this case, you have six contacts in the first screenshot that have their follow-up until date in May or October 2020, but the filters in the second screenshot are set from 12/22/2020 to 1/6/2021. None of the contacts from the first screenshot have follow-up in that period which is why they're not shown.
