### ISSUE TITLE
[CLIMEDO Integration] External User doesn't have rights to see personal/sensitive data

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3925]
### Bug Description
Users with the role `REST_EXTERNAL_VISITS_USER` do not have the necessary rights to see personal data of persons, which means they receive pseudonymized data.
As a result, when trying to register a patient in Climedo, a validation error is always shown, since they do not receive the actual data of the person. The first validation failing is of th

### Steps to Reproduce
1. Enter on a server connected to Climedo
2. Create a new contact or choose a contact with a person who is not registered in Climedo
3. Provide a valid data, including a phone number e.g. 004901603755555
4. Register the person using the 'Climedo Ediary' button.

### Actual Behavior
A validation error is returned from Climedo, even if the data is valid.

### Expected Behavior
The person should be successfully registered

### Screenshots
![image](https://user-images.githubusercontent.com/65336966/103799120-55632280-5053-11eb-972b-6b78da61ecc9.png)

### System Details
* SORMAS version: 1.54.0-SNAPSHOT
* Server URL:  https://ga1.sormas-oegd.de
* User Role: REST_EXTERNAL_VISITS_USER

**Comment by bernardsilenou** [comment]
@vlad-ciucescu Question please:
If i understand you well, you want the external user to be able to create entities in sormas and have full access to only those entities that they create,  right?


If we then allow the external users to be able to create and have access to personal data

**Comment by vlad-ciucescu** [comment]
Hi @bernardsilenou
No rights to create, only rights to read data of already created persons. The data is needed to register the persons in the external journal.

**Comment by bernardsilenou** [comment]
@vlad-ciucescu Inderstood now. 
one last question just for my understanding please: In sormas, only users in the responsible jurisdiction of the entity see and  can edit the personal data of the associated person. Do external users in climedo also have an assigned jurisdiction in order to match with that in sormas?  How to we control such that the external user only see personal data for specific entities in sormas. Do we use the contact uuid from sormas to create the the same contact in climedo in order to permit the external user to have full assess to the personal data? 
Please can you shortly explain or direct me to any issue on how this works?
Thanks in advance

**Comment by vlad-ciucescu** [comment]
@bernardsilenou 
Climedo has a single user per Sormas server, so there is no jurisdiction. No contact or case is created in Climedo, when the 'Climedo ediary' button is pressed in a contact, they just take the person data and use it in their journal. Since there is a single user for Climedo, they should be able to read data of persons in any jurisdiction.

**Comment by bernardsilenou** [comment]
@vlad-ciucescu Thanks for the clarification.
@markusmann-vg This means we have to clearly communicate this to the GE that uses Climedo, right?

I think in the centralized instance, we may need to redefine the rights of the Climedo user.

**Comment by AndyBakcsy-she** [comment]
Validated issue on SORMAS Version: 1.54.0-SNAPSHOT
