### ISSUE TITLE
Show cluster risk level on event and actions directory and add filter

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3951]
### Situation Description
#3271 added a risk level to events that are clusters. However, users cannot see risk level information on the directories and will therefore have to open events individually to find out their risk level.  To have a more informative overview about the clusters, adding this information as well as a filter would be quite useful (e.g. different people might want to focus on different risk levels).
### Feature Description
I suggest to add the risk level on the event and actions directories inside the event status. Since the risk level is only assigned to clusters, a separate column is not necessary because it would have many empty rows.
### Additional Information
<img width="288" alt="clusterCriticality2" src="https://user-images.githubusercontent.com/70317594/104104047-e6c9d300-52a5-11eb-9c8f-cb5e470eb642.PNG">

<img width="372" alt="clusterCriticality3" src="https://user-images.githubusercontent.com/70317594/104104033-d7e32080-52a5-11eb-9ab9-a87cf920dc63.PNG">

**Comment by bernardsilenou** [comment]
@kwa20 since this is a variable by itself, i think it would be good to have it as a new column and also add filter. Thus this would require that the variable "risk level" apply to all event statuses.
@carolinverset @ftavin Is it fine by you  to activate the risk level for all event statuses?

**Comment by kwa20** [comment]
@bernardsilenou Would a risk level make sense for a events with a signal or screening status though?

**Comment by bernardsilenou** [comment]
> @bernardsilenou Would a risk level make sense for a events with a signal or screening status though?

The risk level is a categorization of the probability of the disease to spread among event participant. If the event is a cluster (>= n cases), then it make sense to have a risk level.
To me it also make sense to have the risk level for an event that is not a cluster, for e.g. Many people drank gluhwien from a seller and we latter realized the drink had expired and could lead to sever sickness. There is yet no case but due to the exposure (drink), we would wan to classify the event as high risk and take certain measures.

- For screening it may not make sense. Since it caused not harm if it exist, then I would say we just add to all event status.

**Comment by ftavin** [comment]
@bernardsilenou

ok, #4047 will first activate the risk level for all event statuses. Afterwards, this issue should be done

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
I'm agree with you. Ok for activate risk level for all event statuses

**Comment by AndyBakcsy-she** [comment]
Verified the ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on test.sormas.netzlink.com
This ticket might be related to #4149
