### ISSUE TITLE
Add typing ID to specific pathogen test types [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3957]
* Add new field `typingId` (text) to pathogen tests
* Add a new pathogen test type called "DNA Microarray"
* Only show the new field when one of the following pathogen test types is selected: PCR, Sequencing, DNA Microarray

**Comment by kwa20** [comment]
@bernardsilenou @Candice-Louw This might be interesting to implement for other diseases too, we might want to check where it would apply. 

Further refinement point:
- Should variants be defined and therefore be variables in a drop-down? Advantage: less errors, better filter, free text would be hard to migrate in case we later change it to variables; downside: variables might constantly have to be updated in a fast pace.

**Comment by bernardsilenou** [comment]
@kwa20 We have a similar model for diseases like dengue or plague
- The initial idea was to also include the family (or type) of cororna virus in a drop-down for which we latter decided to go with only covid19 for now.
- Lets use drop-down for variant type. Optional variable with NA as default + lists of names + unknown
- We still need to investigate the names of the different variants especially the one reported from Britain

**Comment by bernardsilenou** [comment]
@kwa20 As more information keeps coming in from experts, to sound as if this variable need to be added to the sample or pathogen test. The reason is that the to know the mutant, you need to so some sequencing which happens to be a test type. Thus this may just be an attribute of a "sequencing pathogen test". More information would follow

**Comment by bernardsilenou** [comment]
@Juliane-D

**Comment by kwa20** [comment]
@bernardsilenou Ok, I think it still makes sense next to the disease. Maybe we can add some kind of logic that updates this field depending on the corresponding test. This would of course make things a bit more complicated.

**Comment by bernardsilenou** [comment]
@kwa20 Ja, thats fine. The additional point that i am making is that since this is related to molecular surveillance, we may need to collect data not just the variant name.

**Comment by kwa20** [comment]
@bernardsilenou SurvNet also requires a Typ ID, if this is not applicable internationally, we might just add this field for germany.

**Comment by bernardsilenou** [comment]
@kwa20 I do not know what  Typ ID means in SurvNet, so can't tell. Please can you check what it means?
If it is something related to the sequencing throughput, then it would be better to add to the pathogen test

**Comment by kwa20** [comment]
In regards to this issue, also add a "Typing ID" free text field. This field should be enabled when COVID-19 is selected as the disease. The typing ID will also be transmitted via DEMIS in the future so this field should be also enabled through the Lab message interface and eventually automatically adopted.

<img width="553" alt="Screen Shot 2021-01-31 at 9 52 47 PM" src="https://user-images.githubusercontent.com/70317594/106397732-200de280-640f-11eb-94a5-a3102f2efa15.png">

**Comment by bernardsilenou** [comment]
@kwa20 I have a suggestion in case i now understand you. 
This variable is "typing id" not t"ype id", right? Then it is about genotyping.
This implies this variable is similar to the Cq/Ct that only applies to any of the type of the test types that corresponds to genetic typing.
The "pathogen test form"  + "type of test" options are not disease specific, since a person having covid can also have another test performed on the same sample for another disease. It would be better to show the typing id based on the type of test.

To change:
- Show typing id if test type == any of the following: PCR, Sequencing, DNA microarray
- Add DNA Mocroarray as type of test, in case some labs use this technology for genotyping. Sequencing is commonly used.

What do you think about this pls?

**Comment by kwa20** [comment]
@bernardsilenou yes, I think this is what we're looking for.

**Comment by kwa20** [comment]
Here is also the collection of variables for a drop-down field for variants:

<img width="698" alt="Screen Shot 2021-02-01 at 8 50 28 AM" src="https://user-images.githubusercontent.com/70317594/106429401-a86da100-646a-11eb-91c4-6efad6a713ee.png">
 @bernardsilenou Is this fine with you?

**Comment by Candice-Louw** [comment]
@MateStrysewske @bernardsilenou - Please take note of pull request in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4042 which may conflict with SurvNet specifications/mappings as required and stipulated here.

**Comment by Candice-Louw** [comment]
RKI specifications 27-Jan-21 10:18:

the information about the mutations is very urgent. Therefore we also finished this Survnet version at very short notice. From my point of view, the relevant 3 fields should be included in the SORMAS SurvNet interface as soon as possible. These are:

- Typing ID: The value is reported via DEMIS, so it must be taken from the DEMIS message. This ID is required so that the sequences available at the RKI in another way can be linked with the reporting data.
- MutationCVD: Field with a catalog for selecting the important mutations
- MutationCVDDetails: Free text field in order to be able to enter other mutations if necessary

The catalog of mutations will certainly expand several times in the short term.

In addition, the case definition of COVID-19 was changed on December 23. slightly adjusted. These changes should also be adopted in SORMAS, if they have not already been done.

---
de-DE:

die Informationen zu den Mutationen sind sehr dringlich. Daher haben wir auch diese Survnet-Version sehr kurzfristig fertiggestellt. Aus meiner Sicht sollten die relevanten 3 Felder möglichst umgehend in die SORMAS-SurvNet-Schnittstelle aufgenommen werden. Das sind:

TypisierungsID: Wert wird via DEMIS gemeldet, muss also aus der DEMIS-Meldung übernommen werden. Diese ID wird benötigt, dass die auf anderem Weg am RKI vorliegenden Sequenzen mit den Meldedaten verknüpfen zu können.
MutationCVD: Feld mit Katalog zur Auswahl der wichtigen Mutationen
MutationCVDDetails: Freitext-Feld, um bei Bedarf andere Mutationen eintragen zu können

Der Katalog der Mutationen wird sich sicher kurzfristig noch mehrfach erweitern.

Zusätzlich wurde die Falldefinition von COVID-19 zum 23.12. etwas angepasst. Diese Änderungen sollten also auch in SORMAS, wenn noch nicht geschehen, übernommen werden.

**Comment by MateStrysewske** [comment]
@Candice-Louw @bernardsilenou I don't fully understand whether the typing ID is related to the case itself or related to the tests performed on samples of the case. Can you concretise that for me?

**Comment by bernardsilenou** [comment]
@MateStrysewske isssue #4042 is about the variant of the case when provided by user.
@This issue is similar but provided by the pathogen test.
@kwa20 @Candice-Louw I do not know if typing id is the same as variant. Typing is generally a Technic to determine the variant of the disease, it can be PCR, sequencing etc.
How does the typing id from Demis looks like?

**Comment by kwa20** [comment]
@bernardsilenou Technically, this issue is about both, the variant in the case information and the typing ID provided by the pathogen test. The Typing ID is for molecular surveillance so it belongs to the sample and pathogen test whereas the variant is part of the case that provides information about the variant that the person is infected with.

**Comment by MateStrysewske** [comment]
@kwa20 Okay, that means the typing ID is nothing that needs to be considered for #4042 because that's strictly about the virus variant. I will rename this issue then.

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 Please confirm that this is correct:

* Add new field `typingId` (text) to pathogen tests
* Add a new pathogen test type called "DNA Microarray"
* Only show the new field when the disease is Covid-19 and one of the following pathogen test types is selected: PCR, Sequencing, DNA Microarray

I don't think there's more we have to do in terms of this issue, right? Everything associated with the virus variant will be handled in #4042.

**Comment by kwa20** [comment]
@MateStrysewske Limit the condition of enabling the field only to the test type, not the disease because this might also be relevant for other diseases beside COVID-19. 

> I don't think there's more we have to do in terms of this issue, right? Everything associated with the virus variant will be handled in #4042.

If the specifications are met there then yes.

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou @kwa20 
I have some short followup questions:
1. Are there any limitations to the typingId textinput? (e.g. maximum length)
2. Should the "Type of Test" Dropdown be ordered in any way? At the moment I just added DNA Microarray to the bottom above "Other"
3. Should the typing ID be shown in the overview on the right:
![image](https://user-images.githubusercontent.com/4655486/106727139-734c8480-660b-11eb-86ec-3f8035a0755d.png)

This is how it looks right now:
![image](https://user-images.githubusercontent.com/4655486/106727261-9414da00-660b-11eb-91cd-341f3a29b5d7.png)

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Since the typing ID is only relevant under specific circumstances, I wouldn't include it in the overview

**Comment by bernardsilenou** [comment]
I think its perfect as you did.
The typing would be a long txt, better just free txt
Micro array is hardly used, thus good to say at bottom
When we would latter map the type of test to disease then we can order, no order exist for now.

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen Please can you add space between typing and id?

**Comment by DavidBaldsiefen** [comment]
> @DavidBaldsiefen Please can you add space between typing and id?

Sure, it's just a placeholder at the moment. German translation would be "Typisierungs ID", right?

**Comment by bernardsilenou** [comment]
> > @DavidBaldsiefen Please can you add space between typing and id?
> 
> Sure, it's just a placeholder at the moment. German translation would be "Typisierungs ID", right?

Yes please, my point is only valid for the English version in case this is not the variable name on the form (front end).

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  SORMAS Version: 1.55.0-SNAPSHOT on the local environment
