### ISSUE TITLE
Update Keycloak Default Password Policy [0.5]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3977]
### Situation Description

At the moment there is no Password Policy defined by default for systems that choose to use Keycloak as their Authentication Provider and each System owner is responsible of defining one.

### Feature Description

Since having no Password Policy should not be the case for any system and to help any new System Owner during the setup we would setup a default set of rules which are already required by some Health Centers.

Length of minimum 12 characters
At least 1 upper case letter 
At least 1 lower case letter
At least 1 digit
At least 1 special character

**Comment by chThie** [comment]
Sorry, if I am a bit late to address this, since you just made a pull request, but I want to give some input concerning the elaboration of the policy.  

There are standardized recommendations for password policies, based on security research including user behavior and security of different approaches.
The current NIST recommendation e.g. proposes the following guidelines:
> - Eight or more characters when created by humans
> - Six or more characters when generated by a service or system
> - Maximum length of at least 64 characters
> - Periodic password changes are no longer mandatory
> - At least ten login attempts for user-entered passwords before blocking the account
> - No password hints
> - No codes for multi-factor authentication (MFA)
> - No knowledge-based authentication (such as secret questions)
> - Support for all ASCII characters (including space)*
> - Check passwords against password dictionaries and databases**. 
> 
> \* Previously, the use of special characters was one of the criteria for a complex, strong password. Since the 2019 update, NIST no longer requires the use of special characters.
> 
> ** You can use special services and open dictionaries or create your own database of weak passwords that should be prohibited. Such a database should include both easy-to-guess and default passwords.  

(Source: https://www.ekransystem.com/en/blog/password-policy-compliance-checklist)
(original NIST source: https://pages.nist.gov/800-63-3/sp800-63b.html (-> 5.1.1.2 Memorized Secret Verifiers))

The main difference to the password requirements you proposed is that they **recommend to check user passwords against dictionaries** (with e.g. commonly used insecure passwords), while **not requiring users to use characters from multiple character sets**.

Keycloak seems to support using password blacklists, so I guess this could be implemented with low effort.
https://www.keycloak.org/docs/5.0/server_admin/#_password-policies
Examples for blacklists that could be used for this purpose can be found here: https://github.com/danielmiessler/SecLists/tree/master/Passwords
Probably there are lists for specific languages as well.

I think it could be worth refining the policy to match the NIST recommendations to improve security and user friendliness at the same time.

**Comment by vidi42** [comment]
@chThie thanks for the investigation and recommendation.

The proposed password policy in this issue is however just an incorporation of already defined and an agreed Password Policy across other SORMAS installations. 

While I do agree that the NIST recommendation is more actual and addresses some aspects of the password policy that could improve security and user friendliness I think it's out of scope for this issue.

The password policy is also something that each SORMAS host can customize for themselves without being required to do any programming so they can easily adhere to some of the NIST recommendation if that is needed.

Since you comment brings up a lot of good points I would suggest that you create a new issue out of it which can be prioritized or contributed upon.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on test-de2.sormas.netzlink.com on SORMAS Version: 1.54.0-SNAPSHOT

**Comment by AndyBakcsy-she** [comment]
Note: 
When creating the new password, the policy rules are displayed one by one every time one of them is not met. 
A Usability suggestion would be to display all required policy info in a text message or as a tooltip for the user to know from the beginning
