### ISSUE TITLE
Use the (custom) SORMAS instance name and localized entity names for export file names [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3992]
### Feature Description
The current export is manually coded to start with something like "sormas_cases_" or "sormas_regions_".

### Problem Description
* For branded systems (e.g. APMIS) the "sormas" is a bit confusing.
* For systems that are completely based on another locale the english entity names are confusing.

### Proposed Change

- [x] Use the calculated instance name (ConfigFacade.getSormasInstanceName) for the first part of the prefix. Should be lower-case and also escaped to only contain valid file characters
- [x] Use the i18n name of the exported entity based on the systems locale (not the user's!) for the second part of the prefix.  Should be lower-case and also escaped to only contain valid file characters

Do this for all exports in the system: cases, contacts, events, event participants, ... regions, districts, ... Search for usages of GridExportStreamResource and DownloadUtil to find entry points for those exports.

**Comment by vlad-ciucescu** [comment]
note: some entity names are not translated yet and will appear in english no matter the system language e.g. facilities

**Comment by vlad-ciucescu** [comment]
To validate:
Make exports and check the file names. As some entity names are not translated yet, it is best to try with cases or contacts for example, since they are surely translated.
Please note: the system language is used, not the user language. Changing the user language should not change the export file names.
The file names are of the form `sormasinstancename_entityname_date.csv`.
If testing locally, the instance name and the system language can be changed in `sormas.properties`
e.g `country.locale=de` and `custombranding.name=fancy name 99`
Spaces in names are replaced with underscores and only letters are retained. An example case export file name for the above settings would be `fancy_name_fälle_2021-03-24.csv`

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot on localhost + test-de.soramas.netzlink.com
