### ISSUE TITLE
Creation of a drop-down list for selecting COVID variants

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4042]
### Feature Description

We want to add the notion of variant for diseases. You would need a variant table with variant id, disease id (CF) and variant name. This table would initially be directly entered in the database by the administrator using a script. Finally, a new field in the case file must allow, after choosing a disease, to specify the variant (combo box).

List of Tasks
-	variant table 
-	script for adding a variant
-	field varying in a case file (after illness)

### Additional Information
@ftavin @bernardsilenou @olivierleuci @emond

**Comment by JonasCir** [comment]
Similar   [issue](https://github.com/hzi-braunschweig/SORMAS-Project/issues/3957) :smiley:

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 

should we add this field to case directory, filters and/or exports

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin 
Yes i think so

**Comment by bernardsilenou** [comment]
@carolinverset I am trying to get to you by email

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @aponcon-atolcd 
in the current version of SORMAS we see that some diseases have an additional field to indicate the type :
![image](https://user-images.githubusercontent.com/15834125/105177256-b7795880-5b26-11eb-8c07-91fbd22ff916.png)

is there any chance that the new concept of "variant" would be redundant with those ? (the mecanism in the screenshot is hard-coded so if we want to keep only one of the two, the new mechanism, with a table, would be better)

**Comment by bernardsilenou** [comment]
@ftavin @carolinverset 
We have the a similar thing for Plague.
Technical we can use the same logic although this may not be good in future. 
Corona virus in fact has generally 3 different types (families) with different properties, namely SARS-CoV-2 (COVID-19), MERS-CoV, SARS-CoV. The idea is to latter user this variable "corona virus type" for these types. 
Currently, only SARS-CoV-2 is implemented in SORMAS.

Each of these types can then have a variant.

The disease types can be hard coded since they are generally not many but not the case with the variant.

I would suggest we keep to the initial idea

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @aponcon-atolcd 

I'm ok with your point, I just wanted to be sure !

**Comment by MateStrysewske** [comment]
@carolinverset It would have been good to close this issue and move the discussion and implementation of #3957 that @JonasCir already linked here because that would've allowed you and HZI to work together in defining it, since this issue is a duplicate. I will have a look at the pull request today, but there will be change requests due to different specifications coming in #3957.

**Comment by ftavin** [comment]
@MateStrysewske sorry for the mess... This whole issue was refined with @bernardsilenou who agreed to use this one rather than #3957 ... So we did work with our main contact from HZI as usual, we would not have start the dev without Bernard's approval

For what I understand, the differences in specifications in #3957 are mainly additions (link with tests, new field "Typing Id" and the possibility to handle an "other variant" case with free text) is this correct ? If this is correct this can be added afterwards (#3957 is still under specification process and Sormas is already late on the variant subject...).

If I am misunderstanding the differences we can still try to adapt the PR in time for 1.55

**Comment by MateStrysewske** [comment]
@ftavin Alright! The "other" variant isn't even necessary with your approach because nobody should ever need to select that (as a newly emerging variant should be added to the database in the first place). It's possible that we need another new field which we would need to add in the context of this issue, but I will let you know once I've reviewed the PR.

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of sormas version 1.55.0-snapshot
The script works with a small change:
INSERT INTO diseasevariant (id, uuid, creationdate, changedate, disease, name)
VALUES
  (nextval('entity_seq'), gen_random_uuid(), now(), now(), '{{ DISEASE ID }}', '{{ VARIANT NAME }}'), 
  DISEASE ID is actually DISEASE NAME
  
 
![image](https://user-images.githubusercontent.com/70562142/107081270-1c0d0680-67fb-11eb-8d62-316a4388958c.png)
