### ISSUE TITLE
Allow regional level users to send a task to a national user

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4048]
### Problem Description

To date, users with a regional profile cannot send a task to the user with a national profile. When the regional user identifies a case involved in an event in his region, and that case resides in another region, he does not have the possibility to link it to his event. Only the national user can do this. It is therefore important to allow the regional user to assign a task to the national user asking them to relate the case of region A to the event of region B.

### Proposed Change

The objective of the development is therefore to allow the regional user (Surveillance Supervisor,Admin Surveillance Supervisor,
Clinician, Contact Supervisor, Event Officer, POE Supervisor) to assign a task to a national user  (National User, Lab Officer, External Lab Officer, National Clinician, POE National User, Sormas to Sormas Client) and thus to notify him of the cases or contacts listed in another. region but involved in an event in its region in order to establish the link between this person and the event.

### Additional Information
@bernardsilenou  @ftavin @emond @olivierleuci

**Comment by kwa20** [comment]
somewhat relates to #3955

**Comment by ftavin** [comment]
**regional users =**
- Surveillance Supervisor
- Admin Surveillance Supervisor
- Clinician
- Contact Supervisor
- Event Officer
- POE Supervisor

**national users =**
- National User
- Lab Officer
- External Lab Officer
- National Clinician
- POE National User
- Sormas to Sormas Client

**Comment by bernardsilenou** [comment]
@MateStrysewske Dev France work on this for 1.55, do you have further comment?

**Comment by MateStrysewske** [comment]
I would like to add the following:

* Create a feature configuration ASSIGN_TASKS_TO_HIGHER_LEVEL that turns this feature on/off. It can be on by default because I think it makes sense in general, but there might be countries that explicitely don't want users to be able to assign tasks to their supervisors
* Make sure that you're not considering user roles, but only jurisdiction level here, because we will get rid of default user roles at some point; i.e. the feature has to be as generic as possible

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on test.sormas.netzlink.com
