### ISSUE TITLE
Final Lab Test Result drop-down to include "Not Done" as one of its options

### ISSUE THREAD

**Issue by Ikemefule** [hzi-braunschweig/SORMAS-Project#4063]
Situation Description
Under the Final test result drop-down, there is no "Not Done" test status from the list of drop downs where we have (Positive, negative, indeterminate, pending). This is only for yellow fever and Measles disease

Feature Description
In the Create new sample module, for yellow fever and Measles disease, the Final Laboratory Test Result drop-down should include "Not Done" test status @bernardsilenou
![sormas_final_lab_result](https://user-images.githubusercontent.com/36294145/104916492-6f293180-5992-11eb-8a2e-dfa0d29bf49a.PNG)

**Comment by bernardsilenou** [comment]
@Ikemefule I think that if we make a change, it should apply for all diseases.
- The final lab result variable is not to capture if the test was done but to capture the result of the test.
- The value penning and NA can be combined to identify samples with "note done" test.
- What do the users need to document please: result of test or if test was done? 
- 
- A bug I can see is that the default value of final test should be NA, not pending
![image](https://user-images.githubusercontent.com/12996724/104957056-b2ed5c80-59cd-11eb-80e5-45d589635500.png)

- Please communicate with the users and drop a feedback

**Comment by bernardsilenou** [comment]
Bug is with 1.53.
- Default final lab result  value should be NA
- Add "unknown" category

**Comment by bernardsilenou** [comment]
@Ikemefule Another option may be to add a new variable 
test done? yes, no, unknown

**Comment by Ikemefule** [comment]
Yes the second option were a new variable test done? Yes, no or unknown should be incorporated. Thank you!

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  @Candice-Louw  wheat are your comments on this please?

- set default final lab result value to NA
- add "unknown" category
- Add an optional variable to sample called: Was pathogen test done?: yes, no , unknown, NA. This can go by the left of "final lab result", split in 2 info boxes.
 - if at least one pathogen test is registered for the sample, set variable to yes, If all test are latter deleted, set variable to NA
 - If "Was pathogen test done == yes", and no sample test is registered, maintain final lab result as NA.
 - In final lab result is not NA  or a pathogen test exist, it should no be possible to set "Was pathogen test done == no",

**Comment by MateStrysewske** [comment]
@bernardsilenou @Ikemefule I don't see the value of such a field yet because whether or not a test has been done can easily be seen by having a look at the amount of pathogen tests connected to the sample. I definitely see the value of another option called "No test performed" for "final laboratory result", so I'd definitely agree with adding that one. "Unknown" doesn't really make sense to me either.

Also, the default of "Final laboratory result" is meant to be Pending, there indeed seems to be some kind of bug there.

**Comment by kwa20** [comment]
I agree with @MateStrysewske. I also think that the default vale should be pending since the whole purpose of collecting a sample is to perform a test. What we might want to consider is that when we add an option to say "no test performed", the user should not be allowed to add a test without having to change the final result too. Otherwise, the final result and added tests might contradict each other.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  I think you have a valid point. From Kays' last comment, it is also needless to add the option of "no test performed"
@Ikemefule Please use "pending" for "not done".  Pending can be interpreted as: not done, unknown, waiting for  the pathogen test to be completed, etc

What we can do now is to remove the option of "NA" as a category of "final lab result" since default is pending

**Comment by bernardsilenou** [comment]
@MateStrysewske there is no need then to remove NA as a category for final lab result since it does not permit the user to save the data anyway? just like case classification #4115

**Comment by bernardsilenou** [comment]
@MateStrysewske He have this in 1.57, so you can close it.
