### ISSUE TITLE
Country of Birth and Citizenship not pseudonymized [0]

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#4074]
### Bug Description
"Country of Birth" and "Citizenship" not pseudonymized on the case person view do not seem to get pseudonymized.
Is this intended?

### System Details
* SORMAS version: 1.53

**Comment by MateStrysewske** [comment]
@kwa20 Do you think these two fields should be pseudonymised? We don't pseudonymise region and district, but the country of birth might be more sensitive than that. What should we do here?

**Comment by kwa20** [comment]
@MateStrysewske I would agree that it might not need to be pseudonymized since it's very generic. However, I assume that such information could theoretically lead to prejudice which might not be desired. An advantage we have is that these fields don't allow free text entries and are therefore not prone to include further sensitive data. I'll check back with a data security officer to make sure how to proceed here.

**Comment by MateStrysewske** [comment]
@kwa20 Any update?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
looking at nationality alone, it does not need to be Pseudonymized. However since there are other variables like age, region and district that are not Pseudonymized, then it is recommended to Pseudonymized Country of Birth and Citizenship.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of Sormas 1.58.0-snapshot on test-de.sormas.netzlink.com Using NatUser and National Clinitian users.
