### ISSUE TITLE
Null/ NA values should be removed from forms on ui

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4115]
### Bug Description
Certain variable now have the NA as categories. For some varaibles, it is fine to have NA as default value in the db and this value should not be possible to be chosen by the user because of the definition of NA. For others we have the option "Unknown" at front end that the user can choose in case they do not now the right answer but want to document this information.
Giving the user the option to choose NA result to an error for variables like case classification, final lab result, etc

### Steps to Reproduce
1.
2.

### Expected Behavior
- NA should be removed as an option to be chosen by the user for final lab result and case classification
- I did not have a look at all the variables in the system but it would be wise to check on other variable.
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/105497879-bf203500-5cbf-11eb-8b37-c69fd23f908c.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really get the problem here. The app will not allow users to save a form anyway if a mandatory field is not filled in. Having an "empty" option is pretty nice to have though because it allows users to reset certain fields in order to have a clean form before they decide on an actual value. This has absolutely no negative effect on the data whatsoever.

**Comment by bernardsilenou** [comment]
@MateStrysewske In this regard, then we leave it as it is since it produces no wrong answer. I was just thinning from a different point that since the option is presenter to me, i should be able to choose it in the case i do not know the right answer.
