### ISSUE TITLE
Geo-location is not calculated in 1.55-snapshot

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4154]
### Bug Description

Because of #3014 there were changes for the geo-converter. I tested it on 1.55-snapshot and the converter is not workign at the moment.

I entered a location and by pressing the "tear-drop" no location is generated. A test in our own instance shows that it is working on 1.52.1

### Steps to Reproduce
1. enter a adress for contact/case
2. press the geo-location-button
3. no sucess

### Expected Behavior

The location should be generated.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/106100256-4fd19780-613c-11eb-81f9-03424b5d74cc.png)
https://test.sormas.netzlink.com/

![grafik](https://user-images.githubusercontent.com/74791118/106100270-54964b80-613c-11eb-810e-19e555c2305a.png)
https://test-de1.sormas.netzlink.com

![grafik](https://user-images.githubusercontent.com/74791118/106100262-5233f180-613c-11eb-9e24-2037016b6f0b.png)
Our working system (1.52.1)

### System Details
* Device: Win10
* SORMAS version: 1.55.-snapshot
* Android version/Browser: Firefox
* Server URL: https://test-de1.sormas.netzlink.com / https://test.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Thanks a lot for pointing that out! @BarnaBartha I'm not exactly sure whether the problem is actually caused by your changes, but could you still have a look at it?

**Comment by BarnaBartha** [comment]
@MateStrysewske @Marko-ilmkreis This issue is not related #3014. Upon checking this it is not even a bug but only a missing configuration. For this service to work one needs to setup a working geocoding service with correct credentials:
`#geocodingOsgtsEndpoint=https://sg.geodatenzentrum.de/gdz_geokodierung_bund__{credentials}`
Credentials part is missing for the mentioned instance thus the geocoding service responds with an error.
There are two options here:
- extend the part when we show these buttons for geocoding, that is actually do a test call to the geocoding service and only if it is successful show those buttons (but this call to be done for each view that should contain this opening adds quite the overhead, doing it only on server startup leaves a small option for the service to become unavailable in the meantime
- on exception from the geocoding service show a useful message to the user that there is something wrong with the geocoding service
I believe both of these are changes and should be refined and estimated by the team. (@MateStrysewske let me know what you think)
As for the current bug fixing the configuration for the needed instances should be the solution.

**Comment by Marko-ilmkreis** [comment]
@BarnaBartha Thanks for clarifying. Then it is fine. I don't think that we need the geo-coordinates for the test-systems urgently as long as it works in the live-systems.

**Comment by MateStrysewske** [comment]
@BarnaBartha Thank you!

I've created a follow-up issue: #4173
