### ISSUE TITLE
[SurvNet Interface] Care/accommodation/work in facility (Web part) [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4163]
see refinements: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4163#issuecomment-778303753

Android part will be implemented with this ticket #4445 

### Situation Description
This is a reference issue for point 1. in #3312 
### Feature Description
Create new field „Care/Accomodation/Work in facility” for cases and contacts

Cases > Open Case information (position: see case information)
Contacts > Open Contact information (position: in between "description of how the contact took place" and "prohibition to work")

New fields (only DE)-
“Betreuung/Unterbringung/Tätigkeit in Einrichtung (de-de) | “Care/Accommodation/Work in facility” (en) [SurvNet field name: Exposition]

“Von … bis” | “from … to” [SurvNet field names: FromDate, UntilDate]
Data Type: Date

“Rolle als “| “in the role of” [SurvNet field name: PatientExpositionRole]
Data Type: Dropdown/enum
Values (de-de) | (en)
• (null)
• nicht ermittelbar| unknown
• tätig is | working at
• untergebracht in | accommodated in
• betreut in | cared for in
• andere/sonstige | other

    - _This field was initially put under exposure details. After consolidation with the RKI, the field name "Exposition"     is misleading and the field merely serves as a general information and is not specifically used for exposures. The     field would therefore have to be moved to the case and contact information._

“Art der Einrichtung (IfSG)” | “Facility type (IfSG)“ [SurvNet field name: KindOfOrg, referenceData Adressen]
Data Type: Dropdown/enum
Values (de-de) | (en)

-nicht erhoben-  |  (null)
-nicht ermittelbar-  |  unknown
Einrichtung gemäß § 23 IfSG
o Krankenhaus
o Einrichtung für ambulantes Operieren
o Vorsorge- oder Rehabilitationseinrichtung, in der eine den Krankenhäusern vergleichbare medizinische Versorgung erfolgt
o Dialyseeinrichtung
o Tagesklinik
o Entbindungseinrichtung
o Behandlungs- oder Versorgungseinrichtung, die mit einer der in den Nummern 1 bis 6 genannten Einrichtungen vergleichbar ist
o Arztpraxis
o Zahnarztpraxis
o Praxis sonstiger humanmedizinischer Heilberufe
o Einrichtung des ÖGD zur Diagnostik, Prävention, Therapie
o ambulanter Pflegedienst, der ambulante Intensivpflege in Einrichtungen, Wohngruppen oder sonstigen gemeinschaftlichen Wohnformen erbringt
o Rettungsdienst
Gemeinschaftseinrichtung gemäß § 33 IfSG
o Kindertageseinrichtung (z.B. Kita)
o Kindertagespflege
o Schule
o Heim
o Ferienlager
o Kinderhort
o sonstige Ausbildungseinrichtung
Einrichtung gemäß § 36 IfSG
o voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung
 älterer Menschen
 behinderter Menschen
 pflegebedürftiger Menschen
o Obdachlosenunterkunft
o Gemeinschaftsunterkunft für Asylsuchende u.a.
o sonstige Massenunterkunft
o Justizvollzugsanstalt
o ambulanter Pflegedienst
o aufsuchende ambulante Hilfen

### Additional Information
Table 
<img width="662" alt="Screen Shot 2021-01-28 at 2 48 04 PM" src="https://user-images.githubusercontent.com/70317594/106148365-43b7fb00-6179-11eb-8b89-e72ad16b5afd.png">

New entry mask:
<img width="395" alt="Screen Shot 2021-01-28 at 2 17 04 PM" src="https://user-images.githubusercontent.com/70317594/106148453-58948e80-6179-11eb-910c-8b2d25a5a10d.png">

**Comment by MateStrysewske** [comment]
@kwa20 What's the point of moving this out of exposures and putting it directly into case/contact data? The point of the epidemiological data section is to track things like these, and we have the exposure types "work" and "habitation" for these exact use cases. In my opinion, the only thing that we actually need to change is that "in the role of" should probably only be visible for habitation, and "working at" would then be obsolete (because "work" would already mean "working at").

The additional facility types here should ideally be merged with the existing ones because it's not a good idea to have separate fields and enums for those. That would require a new issue however.

**Comment by MateStrysewske** [comment]
@kwa20 Keeping this in exposures would basically make it obsolete because of the new "role" field in #4036, so I'd actually vote for getting rid of the patient exposition role ("in the role of") completely and replacing it with that new role field with more values. That would also make this issue here obsolete.

**Comment by bernardsilenou** [comment]
I just saw this one by reading @MateStrysewske comments and also suggest we do not add this to the case form but to the epi data of the case.

**Comment by kwa20** [comment]
@MateStrysewske The problem we face with this field is that in SurvNet it is not limited to exposures, meaning they also document general data (i.e. not just if the case was potentially exposed in such a setting but also if the case was technically a risk factor to others). I tried mapping this exactly how you proposed it but this did not really work out because it overlaps with the InfectionEnvironmentSetting variables in SurvNet (also part of epiData and exposures) and implementing the missing facilities that are part of the SurvNet wasn't very intuitive considering the different structure.

**Comment by bernardsilenou** [comment]
@kwa20 maybe we have a session to work on this ?

**Comment by MateStrysewske** [comment]
@kwa20, @bernardsilenou and I had another discussion about this:

* Add a new property to exposures that defines whether it was an exposure FROM another person TO this case/contact person (as is the status right now) or an exposure FROM this case/contact person TO another person (which is what is needed in this issue). This property would not be visible to the user
* Add a second list to epidemiological data that allows to add exposures for the second (new) use case; this does not require any further backend changes because we will use the same exposure entity for it

Open questions:
* What should the headings for these two lists be? They need to be distinct enough for the users to know what each of them is supposed to do

**Comment by StefanKock** [comment]
Discussed in planning:
- Extend exposures with direction
- Add second list of exposures (with inverse direction, handled by logic)
- Only needed for cases, not for contacts

**Comment by StefanKock** [comment]
@MateStrysewske will refine the working with @kwa20

**Comment by bernardsilenou** [comment]
@StefanKock @MateStrysewske @kwa20 
What about calling the backed  variable: infectionDirection ie exposureInfactionDirection with enums: infector| infectee
Infector == entity giving the disease
inifectee  == entity receiving the disease in the exposure/ contact
However, using these words on the forms is not the best because users may not be accustom to. Short description txt may be good.
`probable direction of Infection due to this exposure`: case/contact person was at risk of being infected| case/contact person was at risk of infecting others| unknown, default == NA
I used others because the sick person may be exposed to a substance or an animal. ie person infect animal or substance infect person.
I have not information to say anything on facility types.

**Comment by MateStrysewske** [comment]
@bernardsilenou The field itself will be hidden in the user interface anyway, it's purely a techincal one to allow us to sort the exposure into the correct list. It can therefore also just be a boolean. The question would be which headlines we're using for the two lists to make sure that users know what they are supposed to add to each of them.

**Comment by bernardsilenou** [comment]
@MateStrysewske I have understood only 95%
@kwa20 do you get? I may need to make a call

**Comment by kwa20** [comment]
Further refinements: 

- Name the new table "activity as case" and the yes/no/unknown field to enable this table "activity as case known"
- Display the role in the table
- Remove "name of source case" since it's not applicable for this section
- Hide yes/no/unknown fields in exposure details
<img width="640" alt="Screen Shot 2021-02-12 at 3 07 06 PM" src="https://user-images.githubusercontent.com/70317594/107793490-a0f5a400-6d56-11eb-8ee9-8fde099dafee.png">
<img width="562" alt="Screen Shot 2021-02-12 at 5 16 39 PM" src="https://user-images.githubusercontent.com/70317594/107793505-a652ee80-6d56-11eb-802f-cc0f6f5542c3.png">

**Comment by raghupola-vg** [comment]
verified on 1.57.0-Snapshot.
