### ISSUE TITLE
Event : creation of a variable allowing to define the state of the event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4167]
### Situation Description
The management of an event consists of several stages:

- receipt of information relating to an event leading to registration in SORMAS then designation of the person in charge of the investigation
- Investigation process during which the responsible user formalizes the various actions taken to collect all the people involved and to limit the spread by insisting on the actions to be taken. As soon as the investigation is completed, the user informs the coordinator that the investigation is complete and proposes the closure of the event.
- The coordinator checks the elements and closes the event when he thinks that no evolution of the event is to be expected. 

It is only after a few weeks that the event is archived (which causes it to disappear from the events directory)

### Feature Description

To date,
-	the event status variable qualifies the nature of the event: is it a signal, a cluster or an event (and dropped)
-	The investigation status variable allows the responsible user to indicate the level of progress of the investigation.

In the event sheet:
-	rename “event status”  in “event category” or “event nature” 
-	create a 3rd variable to define event status or event state with the terms: initiated, in progress, to be closed and closed. 
-	transfer the "abandoned" mode, currently integrated in the event status variable, into the new  variable. A script will be developed to ensure the recovery of items entered in the past.

In the event directory:
-	Addition of the new column in the event and action directory
-	Filter in the event and action directory
-	Include this variable in all exports (basic, detailed) of event and action directories

### Additional Information
@bernardsilenou @ftavin @emond

**Comment by MateStrysewske** [comment]
@bernardsilenou @Chinedar Do you agree with these changes?

@carolinverset I don't really see a difference between the current investigation status and the proposed event status/state - initiated basically maps to pending, in progress maps to ongoing, closed maps to done. Could you explain which additional information we're getting from introducing that new field?

**Comment by carolinverset** [comment]
@MateStrysewske @ftavin @bernardsilenou @emond

French users explain to us that, from a functional point of view, the investigation is only one phase of the "life" of an event. At the end of the investigation, the events are studied by coordinators to know whether or not the events / clusters can be closed and later be archived. 
This is why the investigation status allows the responsible user to indicate the level of progress of the investigation. 
The new field does not concern the investigation itself but the event in the broad sense. An investigation may be completed but the event is not yet closed as it may change a little later.
It is however important to allow the coordinator to indicate that an event is really closed because this status will result in the archiving of the event a few weeks later.

**Comment by bernardsilenou** [comment]
@MateStrysewske @ftavin  @emond
I can find some reason in both point of view.
I agree with @MateStrysewske that this new variable is highly related to the investigation status but with different names.
One point @carolinverset mentioned that is missing in the current investigation status is some grading of the progress of the investigation.
What about 
1. merging both points and add a "be closed" state between ongoing and done. I personally do not think this is a good idea because "to be closed" is not an investigation status but a decision based on the % of completion of the investigation.
2. add a variable called % complete 0 to 100, and show it on form when investigation == ongoing.

![image](https://user-images.githubusercontent.com/12996724/106339527-20836d80-6297-11eb-85f6-a464faad1f5b.png)

3. Leave it as it is and explain to user to only set the status to done when the event is "closed". There is an end date of investigation, thus users should only provide this date when the event is to be closed.

**Comment by carolinverset** [comment]
Yes I understand your different comments. I approached the region which issued this request for development. @bernardsilenou  @ftavin @emond can we talk about that again on Wednesday?

**Comment by carolinverset** [comment]
Alternative proposed in the issue #4255
I close this issue

**Comment by carolinverset** [comment]
Alternative proposed in the issue #4255
I close this issue
