### ISSUE TITLE
Number of points on the dashboard map should be rendered by the time filter [2]

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4176]
### Bug Description
After activating the setting to not display the map when it exceeds a defined number of points, the message indicates a very high number of points to display.
After discussion with Bernard, it seems that it is theoretically expected that the number of points to be displayed by default in the map are the cases of the last month and not all the points of the base?
The screenshot below indicates in fact 640 thousands points to display and the case directory of this test environment contains just this number of cases.

### Steps to Reproduce
1.go to the dashboard 
2.compare the number of points indicated in the message on the map with the number of cases: the total of cases is shown on the map when you click on "display" Only the points of cases recorded in a recent period (1 month?) should be displayed

### Expected Behavior
If I understood correctly, only points cases from a recent period (1 month?) should be displayed. 

### Screenshots
![image](https://user-images.githubusercontent.com/65449450/106283709-87c30280-6242-11eb-895b-7ade4c9c848e.png)

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser:
* Server URL:
* User Role: admin

### Additional Information
@bernardsilenou @olivierleuci @emond @ftavin

### Developer Specifications

- Apply the Dashboard Date & DateType Selection to the Map. Add a checkbox to the map to filter the entities based on relevance instead (=> `CaseService.createCaseRelevanceFilter`)
  - Remove the Map layer date filter, as that might cause unnecessary confusion as to which dates are actually used
- Map Contacts should always be filtered based on the contacts `reportDate`, nothing else
- Use the `dashboardMapMarkerLimit` property for the maximum amount of entities to be shown on the dashboard map. **Make sure the marker counter uses the same algorithm that is also used to pull the entities** (this is what causes the bug described above)

**Comment by MateStrysewske** [comment]
@carolinverset The dashboard map is supposed to display all cases that are relevant in the date period selected. That means that:

a) their onset or report date is before the filter end date and
b) their date of outcome is after the filter start date

Do the cases in your system have outcomes? If not, that explains the number of cases that are gonna be displayed in the map.

**Comment by bernardsilenou** [comment]
@MateStrysewske @carolinverset I think we need to make a change to the filter on the map to be more conservative, i.e we restrict the map only to the entities selected in the filter. A similar issue was raised by a user.

Let "date" = onset or report date or date of event, ... (depending on the entity)
a) filter start date <= date <= filter end date (show entities on map)
Since the map entities are either cases, contacts and events, then we can drop condition (b) i.e exclude all cases whose date does not all in the filter time interval but whose outcome does.

What do you think?

**Comment by MateStrysewske** [comment]
@bernardsilenou As I said, that's basically what can be achieved in the statistics, but the dashboard map was originally designed to give an overview of the overall situation in the country, not based on the selected filters. If we change this, this definitely needs to be confirmed with Nigeria and Ghana.

**Comment by carolinverset** [comment]
Thank you @MateStrysewske for your explanations. Indeed, by selecting a region with the region filter for example, the number of points on the map decreases. On the other hand, the date filters do not cause any variation in the number of points. @bernardsilenou I must be making mistakes, could you show me Wednesday at our meeting?

**Comment by MateStrysewske** [comment]
@carolinverset Yes, that's exactly the desired behaviour. You can restrict the area where points are shown with the filters, but the dates don't do anything because they don't influence the map - as the map is always a reflection of the **current** situation (i.e. it shows all cases that are currently active).

**Comment by carolinverset** [comment]
OK I understand. @MateStrysewske @bernardsilenou  Wouldn't it be interesting to develop the possibility of displaying the new cases reported during the last week, the last month, in a personalized period ...?

**Comment by MateStrysewske** [comment]
@carolinverset I think there's a date filter directly in the map that was introduced by external developers several months ago and that might basically be able to do that. Not quite sure though.

**Comment by bernardsilenou** [comment]
@carolinverset 
Before COVID-19, there was not a situation that we had many cases and contacts to show on the map, that is why we did not filter the map by time. The internal filter within the map may not also be the optimum solution if the time you need does not correspond to any of the grouping.
I would communicate with the Nigerian and Ghana team tomorrow.
The different countries in Europe already expressed their interest to filter the map by date. If Ghana and Nigeria accept, then we would do the change for everyone, if not we would add a configuration.
We discuss further on Wednesday.
Thanks

**Comment by bernardsilenou** [comment]
@MateStrysewske @MartinWahnschaffe @kwa20 @Candice-Louw @Chinedar 
Nigeria also prefer that we filter the map based on the time specified by the user. Ghana is a special case and this would be fine for them also.
I suggest we change the default configuration of all instances to show only the cases, contacts and events returned by the time filter.
We then have to use the same type of date (report date or symptom onset or date of event, etc) for each entity as used to obtain the total counts such that if there are 10 cases and 5 events reported in a week and all have a coordinate, then we would end up with exactly 15 points on the map. 

Please give a thumb up before tomorrow if your agree with this change.

**Comment by bernardsilenou** [comment]
Related to #3004

**Comment by bernardsilenou** [comment]
The decision from last meeting is to add a configuration to determine if top n (5000) entities (case, contact, events) are shown or only cases returned by the filter are shown on the map. If filer returns more than top n entities, then show only top n entities are shown.

**Comment by bernardsilenou** [comment]
@MateStrysewske @MartinWahnschaffe @StefanKock 
Question pls: The threshold (n) on the map is the sum of all the entities or just cases? 
If  n = 500 for example,  does this mean 500 for each entity or combined OR which proportions do we use to combine the entities to obtained n?
I asked because there are systems with thousands of events.

**Comment by MateStrysewske** [comment]
@bernardsilenou If I'm not mistaken, it's the sum of all markers that would be shown on the map, so basically it depends on which checkboxes have been checked by the user.

**Comment by bernardsilenou** [comment]
- Just to mention that we should remember to use the same date type as specified by user for cases:
![image](https://user-images.githubusercontent.com/12996724/116165691-af6c1e80-a6fc-11eb-8a1d-93112a8fb282.png)
- For contacts and events, we can use report date always.
- If n > 500, then we can pull a random sample  from the collection of node types: cases, contacts, events ( depending on what is selected by user)  + inform user of number of nodes that are not plotted. eg "5000/50000 nodes are plotted". If we sort and plot the most recent entities based on report date, then we may end up plotting only one type of entity which would not be good.

**Comment by DavidBaldsiefen** [comment]
Added developer specifications.

@MateStrysewske @bernardsilenou woud it make sense to disable the date filter of the map in this case, in order to prevent confusion on which filter is currently used?

![image](https://user-images.githubusercontent.com/4655486/116851482-b5796800-abf2-11eb-9ce5-2ecb27075f0a.png)

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Yes, the date filters specific to the map should be removed. However, please add a checkbox that says "Show current epidemiological situation" that basically replicates the current logic (i.e. showing all currently active cases/contacts); should be unchecked by default

**Comment by DavidBaldsiefen** [comment]
It seems like currently, the dashboard filters are already applied, and then made "more strict" by the dashboard which adds filters for classifications (only showing cases where the classification is `!= null` and `!= NO_CASE`) (`DashboardMapComponent.fillCaseLists`)

However, the method determining the marker count and then deciding whether or not  too many markers need to be displayed, only uses the dashboard date filters, _ignoring_ the classification (`DashboardMapComponent.refreshMap`). 

This leads to the described behavior, where the case count does not include the classification filter, leading to a count over the defined limit, which prevents the map from being displayed - even though the amount of actual cases that would normally be displayed is lower than the limit

**Comment by MateStrysewske** [comment]
@carolinverset @bernardsilenou To further clarify: 

* Most elements on the dashboard display all NEW cases in the specified time frame
* The map displays all cases that are RELEVANT in the specified time frame, i.e. at least one day in the period from their report/onset date until their outcome date falls in the specified time frame

The number of cases that you've seen in the warning message is caused by the bug mentioned by @DavidBaldsiefen. Taking this into account (i.e. this bug being fixed), do you still want us to do the change that would lead to the map also only displaying NEW cases, not RELEVANT cases?

**Comment by bernardsilenou** [comment]
@MateStrysewske @DavidBaldsiefen 
- Since case classification can not be null, then  can we not reduce the logic to  case classification != NO_CASE to show cases on the map?

> @carolinverset @bernardsilenou To further clarify:
> 
> * Most elements on the dashboard display all NEW cases in the specified time frame
> * The map displays all cases that are RELEVANT in the specified time frame, i.e. at least one day in the period from their report/onset date until their outcome date falls in the specified time frame
> 


> The number of cases that you've seen in the warning message is caused by the bug mentioned by @DavidBaldsiefen. Taking this into account (i.e. this bug being fixed), do you still want us to do the change that would lead to the map also only displaying NEW cases, not RELEVANT cases?

The meaning of relevant defined here included outcome date.   Suggest we use NEW cases, ie consider entities with date type chosen by user to fall in the time interval  or at the end points of the interval specified by user. In this way, we end up having either the same points on the map as the indicators on dashboard or lesser, but not more.

**Comment by DavidBaldsiefen** [comment]
Then I would suggest going with @MateStrysewske 's suggestion, to add a checkbox to the map layer filters called "Show current epidemiological situation" (Default: Off)

If ticked, cases/contacts/events on the map will be shown based on the relevance filter, as described above. If not ticked, cases/contacts/events will be shown based on the date-type selected in the dashboard filter.

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou 
I have one more question regarding contacts.
Currently, contacts for the map are not filtered by date at all. Basically, a list of relevant cases is retrieved, and then all contacts of those cases are displayed; but also, all contacts _without a source case_ are displayed, as long as they are under follow-up.

Should this be changed, so that for example contacts without a source case are only shown if their report date is within the selected timeframe?

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen 
- You are right, we implemented like this because there was no COVID. With COVID, this solution is not realistic since the number of contact nodes grows exponentially and can not be plotted.
- I would suggest we select only New contact ie use only the date of report.  We show contacts as long as their report date fall in the time interval irrespective if they have a source case or their source case report date fall in the time interval.
- Since the contacts on the map are actually the unique contact person nodes (since we use the coordinates of the home address of the contact person - hope this is right?) then we may end up having more contacts than nodes on map. This is not an issue because we would soon add a toggle on the dashboards to display entities by person and at this point the number of contacts would then match the number of contact nodes on map.
- On surveillance dashboard, the date types: relevant, report, onset, would apply to cases only, no matter what user chooses, we then only  user report date to extract new contact. We may end up having a contact whose source case is not in the selected case set, no problem.
- We can later implement selection by different date types for contact in another issue: last contact date/ report date
- Hope this helps

**Comment by DavidBaldsiefen** [comment]
Thank you, this really helps.

One more question: On the surveillance dashboard map, should we consider contacts whose case is not part of the current filter, but whose report date is within the filter? That is currently not the case (we consider only those whose case is relevant or who do not have a case at all)

**Comment by bernardsilenou** [comment]
> Thank you, this really helps.
> 
> One more question: On the surveillance dashboard map, should we consider contacts whose case is not part of the current filter, but whose report date is within the filter? That is currently not the case (we consider only those whose case is relevant or who do not have a case at all)

Yes please, we should consider them  since they were reported in the time specified. We try to keep the map the same irrespective of the dashboard: surveillance, contacts, events (to come later)

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou 
Alright, then for contacts I will only consider report date and nothing else.

**Comment by RazvanHodisan** [comment]
Validated on 1.60.0-SNAPSHOT.
