### ISSUE TITLE
[SORMAS2SORMAS] Resending data in bulk edit mode fails with unclear generic error message

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4190]
### Bug Description
When data was already shared with another instance, resending it through the bulk edit mode does not work and results in an error 400. I believe this problem occurs because the system tries to go through the share functionality again rather than sync instead.
### Steps to Reproduce
1. Select an already shared case in the bulk edit mode in the cases directory and try resending it to the same instance.

### Expected Behavior
When trying to share a case with the same instance again through the bulk edit function, the case should sync the data previously sent to this instance.
### Screenshots
<img width="1112" alt="Screen Shot 2021-01-31 at 4 19 37 PM" src="https://user-images.githubusercontent.com/70317594/106388927-efaf4f80-63e0-11eb-9bcb-3b6ced7fec89.png">

<img width="373" alt="Screen Shot 2021-01-31 at 4 16 46 PM" src="https://user-images.githubusercontent.com/70317594/106388919-e4f4ba80-63e0-11eb-89d9-d73db1b8dea5.png">

<img width="369" alt="Screen Shot 2021-01-31 at 4 19 25 PM" src="https://user-images.githubusercontent.com/70317594/106388913-dc9c7f80-63e0-11eb-995c-b44fa75f6272.png">

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by leventegal-she** [comment]
I wouldn't consider not syncing in bulk is a bug. Syncing in bulk is not yet implemented.

The bug I see in this ticket is the error popup that displays "400 bad request" but it should show more relevant message like "the case already exists" but I couldn't reproduce this.

Some more details are needed about the context, what options where checked, is it sure that the case was shared already. maybe some details about the shared data: an export csv would help a lot.

----
For handling sync in bulk mode I would suggest to create a new change/feature request and refine it because there are some open points that should be discussed: 
- share and sync work slightly different that's one reason it is separated on the details page
- in bulk mode the user can select some shared cases but also some unshared => how to proceed in this case? should we separate the share and sync actions here too?
- sync preselects previously used options => what options to reuse in bulk mode if some cases where shared with samples and others without samples

@markusmann-vg @MateStrysewske @MartinWahnschaffe

**Comment by MateStrysewske** [comment]
@leventegal-she If bulk-resending isn't implemented yet, I agree that we should rather open a new feature request for it. Can you please rename this issue to match the actual bug that you've described?

**Comment by vidi42** [comment]
Opened a new feature for the Bulk sync feature https://github.com/hzi-braunschweig/SORMAS-Project/issues/4858
