### ISSUE TITLE
New final laboratory result (Samples)

### ISSUE THREAD

**Issue by generalkolo** [hzi-braunschweig/SORMAS-Project#4219]
### Situation Description
In addition to the currently available final laboratory result for a sample (Indeterminate, Pending, Negative, Positive), a new option/selection; **NOT DONE**.

**NOT DONE** would be the representation of a sample that a pathogen test was never carried out on due to one reason or the other and not just the specimen condition.

### Feature Description

- Users would still be able to enter pathogen test result details as is implemented at the moment.
- The **NOT DONE** laboratory result would **ONLY** be available for selection when the pathogen test result is on **PENDING** or there is none recorded (NA), any other pathogen test result would work as is implemented currently.
- Ie users would not be able to set final lab result of sample  to **NOT DONE** when there is at lease one pathogen test for the sample recorded with a result  != pending.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  @Candice-Louw  Please what are you thoughts on activating this an all instances? 
Not done would be translated as nicht erhoben I suppose.
Background information:
- Since measles is a very contagious diseases, it gets to a point that an outbreak is declared and the workers can no longer test all samples. So the ideas is to be able to distinguish samples that are awaiting to be tested (pending) and those that would never be tested (not done). So we though of just adding this to the final classification of the sample, no matter the disease as information on samples are not related to disease.

**Comment by MateStrysewske** [comment]
I think this is a very reasonable addition, so I have no objections.

**Comment by Candice-Louw** [comment]
@bernardsilenou - makes sense, yes.  And yes for activating on CH instances, please.

**Comment by raghupola-vg** [comment]
Verified both on Web and Android app on version 1.57.0-snapshot. Works fine

**Comment by bernardsilenou** [comment]
@raghupola-vg Which server are you using to test the mobile app pls?

**Comment by raghupola-vg** [comment]
@bernardsilenou I have tested both on test.sormas.netzlink.com and test-de.sormas.netzlink.com
