### ISSUE TITLE
Make external ID fields (cases & events) read-only when SurvNet interface is configured

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4254]
### Steps to Reproduce
1. Open one Event and add a Superordinate event and also a subordinated event
2. Make sure the External ID is present for the event
3. Sent the event to SurvNet

### Expected Behavior
The External ID field should be grayed out in the case of SurvNet connected environments
### System Details
* Device: Windows
* SORMAS version: SORMAS Version: 1.55.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she Can you specify why this should be the case? Do we make any other fields read-only after their entities have been sent to SurvNet?

**Comment by MateStrysewske** [comment]
@kwa20 Can you specify what exactly is wrong here?

**Comment by kwa20** [comment]
@MateStrysewske When the SurvNet interface is configured, the external ID field will be filled with the Guid from SurvNet that gets generated upon transmission. If this field is filled, an error appears because the external Id field is already filled and cannot adopt the generated guid. Since the Guid is unique and serves as the reference for SurvNet, we could make this field unavailable when the interface is configured. The token would still available for customized references if needed.

**Comment by kwa20** [comment]
@MateStrysewske It could look something like this when the interface is configured:

<img width="892" alt="Screen Shot 2021-02-04 at 6 55 12 PM" src="https://user-images.githubusercontent.com/70317594/106934636-a5004100-671a-11eb-8773-a5c6499ab761.png">

**Comment by MateStrysewske** [comment]
* Add a description when the field is read-only for this reason: "Will adopt SurvNet GUID"

**Comment by kwa20** [comment]
I noticed, that editing and re-sending data to SurvNet is possible and produces a new case in SurvNet, therefore, it's quite important.
