### ISSUE TITLE
[SurvNet Interface] Add Reports to case information

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4282]
**FOR ACTUAL IMPLEMENTATION TODOS SEE:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4282#issuecomment-778132975**

### Situation Description
Thus far, users can only select one type of reporting. This is not enough since many types of reports with additional information can reach the health departments. To document the various reports that are received, users need to be able to store such information in a manner that does not clutter the case information form too much.
### Feature Description
Add a "reports" section on the right of the case information that allows creation and storing of various reports. Creating a new report should open an entry mask that includes the type of reporter (rename type of reporting and move the enum to the new section), date of report (may differ from date of report of the case!), date of diagnosis, the creating user, facility selection option, address fields, phone number and email address and a details section (free text). The creating user might be helpful for internal communication.

The box in the case information should contain the type of reporter, date of report and diagnosis as well as the name of the reporter which would be the facility name. An edit button should open the entry mask again. 
When lab messages are processed through the DEMIS interface, a report of the type "laboratory (DEMIS)" for the created or chosen case should automatically be created. The processing user would also be the creating user. For lab message reports, there should also be a link to view the respective lab message (eye icon).

Integration of the reports will allow a more complete interface and mapping to SurvNet.
### Additional Information
<img width="916" alt="Screen Shot 2021-02-06 at 7 32 14 PM" src="https://user-images.githubusercontent.com/70317594/107126770-14f4ff80-68b2-11eb-8604-22a67fc820cb.png">

**Comment by kwa20** [comment]
@JaquM @bernardsilenou @Candice-Louw I'd appreciate your feedback on this issue. Since this is quite specific to Germany, we should probably make this configurable

**Comment by JaquM** [comment]
It should also be possible to enter the address and telephone number of the reporting entity.
In the best case, these are also stored under facilities and fill in automatically when selected.

**Comment by kwa20** [comment]
I've updated the mock-up to include address fields, phone number and email address.

**Comment by bernardsilenou** [comment]
@kwa20 Nice design,
Minor comments, not all may be important, would be better we have a call:

-  What does date of diagnose mean? this variable applies if the report is a lab result, right? Since the report may be any report related to the case, do you think we can drop the date of diagnose? not to get confused with the report date on the case form. I suggest we document just the date that the document was produced.
- The case form has "date of report",  which date do we need here, date report arrived the user or when it was sent, produced,  etc? The word 'report' as used on the case form is used as a verb ie date the entity was notified. What about calling it document as in event? and call this date: `document date` or `date of document`. No matter the entity, we would soon use this feature to import and store documents, thus nice to use one name for all.
![image](https://user-images.githubusercontent.com/12996724/107130494-4976b480-68ce-11eb-97b4-99d8b6ad83ac.png)

- I think we should add at least one required variable, eg type of reporter and date

**Comment by bernardsilenou** [comment]
@kwa20 Is this the first state of #1771 with just the meta data of the document?
The second phase would then focus in attaching one or multiple documents of any type per report/ document.

**Comment by Candice-Louw** [comment]
Definitely a configurable feature, please.

If the values in the dropdown (enum) are used as is, this will not be relevant to any other country and the values will constantly be changing according to SurvNet values to make the mapping possible/keep it up to date.

It should also be verified with the RKI directly please whether both the "Community Facility (..." entries are required in this list at this level.  I believe in SurvNet these are merely first level section differentiators (?) and may erroneously have been made selectable.

Please also include the table for mapping variables from SORMAS to SurvNet here for Vitagroup to be able to document which variables are mapped where (SurvNet variable, SORMAS variable).  This way it is easier to keep track of which Issues are explicitly created in order to make mapping to SurvNet possible and also makes it clear why these are given priority.

**Comment by kwa20** [comment]
@bernardsilenou I don't think that we can drop date of diagnosis because it might also be relevant for physician reports etc. This date can also differ from the date of report. Date of report can also differ from the date of report on the case form. The language is unfortunately not easily distinguishable but the date of report (case) is the date where the health department got knowledge of the case whereas the date of report (reports) is the date where the report was submitted. To make things more clear we can name reports "messages" instead and also name the date of report "date of message".

Making type of reporter compulsory could be fine I guess. 

This feature will be separate from the documents part. It'll be nice to have to also store pdf's for example but documents could not be mapped the way we need it for SurvNet.

@Candice-Louw Thanks for the hint, the first community facility ($8) would actually be conform to "hospital or stationary care". We might however have to rename this to medical facilities though to cover a broader range of included facilities.

**Comment by bernardsilenou** [comment]
@kwa20 OK with all your comments but one.
It is not clear how this issue is related to the document management module. Do you mean we would have 2 boxes on the right of the case from, one for messages (only meta data) and another for documents (meta data + options to upload files)?
I have sent an invite to discuss this tomorrow. It would be good that we refine the complete story.

@Candice-Louw  I also agree with you that when activating type of reporting, we would make it configurable. Most of the option presented already applies to the international instance so we may end just handle minor differences with translation.

**Comment by StefanKock** [comment]
Questions: 
1. Migrate Case.reportingType to new Entity, or keep it redundant for different countries?
2. Only needed for cases?
3. What is about reporting district? Is this somehow linked?
4. Does this have any purpose aside sending this information back to SurvNet?

**Comment by kwa20** [comment]
@StefanKock 
1. migrating would be better since it is DE exclusive anyway and I guess preventing redundancy would be good.
2. only needed for cases thus far.
3. reporting district is separate and can stay where it is.
4. The purpose is to allow users to document incoming reports that reach the health departments in regards to cases. The main reason for implementation is however the SurvNet interface indeed.

**Comment by MateStrysewske** [comment]
@kwa20 Can you write down what the purpose of this feature is BEYOND SurvNet compatibility? I.e. in which way do SORMAS users benefit from it?

**Comment by kwa20** [comment]
@MateStrysewske Thus far, users do not have the possibility to store or manage incoming reports to specific entities in the system. This will help the users with bureaucracy  problems that occur often in health departments. I guess @JaquM could also elaborate on that.

**Comment by bernardsilenou** [comment]
@MateStrysewske @StefanKock 
Some few comments from us:
- The purpose of this feature is to be able to add documents/reports/messages (name does not matter) to entities. It has two sub-component:  meta data describing the document + optional attachment
- In this ticket, we want to be able to create a new report (with information of type of reporter/ document source type, date, jurisdiction of reporter, etc) . There can be multiple of such reports from different source linked to a case, contact or event.
- The case form is not affected; This is just a new document entity
-  We would need this feature for cases, contact and event as final goal. Propriety is to begin with case, then contact
- This ticket is just the first part, to be able to document the meta data of all official documents related to cases and contact. The second part would then be on attaching document for each "new report". If you think we can do all in one ticket, then that is perfect. We already have the option to attach documents for event but meta data is lacking.
- All SORMAS users would benefit from the fact that they would be able to attach documents related to entities.
- Even type of reporting is not activated in all instances, It would be good that we activate this module for all instances.

**Comment by MartinWahnschaffe** [comment]
![grafik](https://user-images.githubusercontent.com/23217632/107759955-514cb380-6d29-11eb-9b9e-670309c58f62.png)

We have discussed this again today. In the context of this issue we have to keep it simple. The core need is to be able to document reports/notifications for the case. Documents and other things can be added later.

We also decided to not include reports of type "LABORATORY", because the existing PathogenTests already have almost all the needed information and we don't want to duplicate this.

- [ ] Add a new SurveillanceNotification entity to the system. A case can have a list of these.  (I think the name Report would be misleading and we may also need this for other entities, like contacts later, so CaseReport also is not a good option) 
- [ ] The entity should have fields: reportingType, creationUser, reportDate, diagnosedDate, facilityType, facility, facilityDetails (as used in other places), notificationDetails (see screenshot). reportingType and reportDate are mandatory
- [ ] The existing Case.reportingType will be removed and existing values migrated by creating one entry in the list with the reportingType and the reportDate of the case
- [ ] The type LABORATORY is removed. During migration no report is created for this
- [ ] Display the list in the main view of the case, as in the screenshot
- [ ] Add functionality to create, edit and delete entries. Depends on the CASE_EDIT user right
- [ ] The reports are not synchronized to the mobile app for now. So when receiving a case from the mobile app, don't delete the existing values
- [ ] Add a feature configuration

@kwa20 Please double check this.

**Comment by kwa20** [comment]
@MartinWahnschaffe Thank you! looks good for me. Just note that SurveillanceReport.reportDate is not the same as case.reportDate and may differ. The SurveillanceReport.reportDate is the date when the reporter issued the report to the health department.

**Comment by bernardsilenou** [comment]
@kwa20  
- Why not adjust the mockup and use use the name as you defined not to cause confusion
 `date reporter was issued`?
- It may be good to know the date that the report was received by user documenting it, right? eg  `date reporter was received`

**Comment by leventegal-she** [comment]
@MartinWahnschaffe there is a *Reporting district* field besides the *Reporting type*, should it be kept there or can be migrated to the new *Surveillance report* as *Facility district*?

**Comment by bernardsilenou** [comment]
@kwa20 I think this question from @leventegal-she  involve you also.
Whats the definition of the reporting district on the case from pls?

**Comment by MartinWahnschaffe** [comment]
@leventegal-she Thanks for pointing this out. This field is currently also only used for Germany, so I'm pretty sure that we have to move it into the new report entity. This means it has to be removed from the case and migrated, like we do for the type.
@kwa20 Please confirm.

**Comment by kwa20** [comment]
@MartinWahnschaffe @leventegal-she the reporting district field is independent of the reports section so it can stay where it is and doesn’t have to be migrated.

**Comment by MartinWahnschaffe** [comment]
@kwa20 Are you sure? From my understanding this field is highly related to the "Art der Meldung" field. Since we move that field we should probably also move the related district field?!

![grafik](https://user-images.githubusercontent.com/23217632/107930580-789abf00-6f7b-11eb-9013-7bdabf3d7d31.png)

**Comment by kwa20** [comment]
To elaborate on the reporting district field: In Germany, being responsible for a case does not necessarily mean that departments are actually the ones reporting the case to the higher health institutions. Cases are being reported depending on where the case person is registered. Thus, responsible district and reporting district might differ if e.g. the current place of stay is somewhere else than the home address of the case person. A case might be hospitalized in a hospital in another district for example.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.57.0.snapshot on local environment

**Comment by MateStrysewske** [comment]
Reports are not shown and can't be created when the user language is set to German. Seems like there are some date formatting problems.

```
Caused by: java.lang.NullPointerException: null
	at de.symeda.sormas.api.utils.DateHelper.getLocalDateFormat(DateHelper.java:65)
	at de.symeda.sormas.api.utils.DateHelper.formatLocalDate(DateHelper.java:101)
	at de.symeda.sormas.ui.caze.surveillancereport.SurveillanceReportList$SurveillanceReportListEntry.<init>(SurveillanceReportList.java:118)
	at de.symeda.sormas.ui.caze.surveillancereport.SurveillanceReportList.drawDisplayedEntries(SurveillanceReportList.java:78)
	at de.symeda.sormas.ui.utils.PaginationList.showPage(PaginationList.java:95)
	at de.symeda.sormas.ui.caze.surveillancereport.SurveillanceReportList.reload(SurveillanceReportList.java:64)
	at de.symeda.sormas.ui.caze.surveillancereport.SurveillanceReportController.lambda$0(SurveillanceReportController.java:51)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.onCommit(CommitDiscardWrapperComponent.java:525)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commit(CommitDiscardWrapperComponent.java:392)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent.commitAndHandle(CommitDiscardWrapperComponent.java:412)
	at de.symeda.sormas.ui.utils.CommitDiscardWrapperComponent$1.buttonClick(CommitDiscardWrapperComponent.java:285)
	at sun.reflect.GeneratedMethodAccessor3030.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:712)
	... 87 common frames omitted
```

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of Sormas Version 1.57.0-snapshot on local environment

**Comment by Candice-Louw** [comment]
@leventegal-she @AndyBakcsy-she - could we please have an indication in the documentation on how this should be configured per instance, please?
