### ISSUE TITLE
Activate external token to all server instances [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4328]
### Feature Description
International users need this variable but it is not activated by default
### Problem Description
- activate external token to all server instances by default

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske 
International instance also wish to use these variables for all entities: case, contact,  person, etc

**Comment by carolinverset** [comment]
@bernardsilenou @MateStrysewske @MartinWahnschaffe @olivierleuci @emond-fuseau @ftavin
I confirm that these fields are very important in France since they allow you to find information imported from another data system.
We had also offered this development and were delighted to see that it was already supported by HZI. A little annoyed that these fields are finally not accessible in 1.56.1.

If this development is ok for you, tell us if HZI can proceed with this configuration or if you prefer that the French team do it.

it would be great if these fields were accessible from the next release.

Thank you very much for all !

**Comment by JonasCir** [comment]
is it an option to remove the server property completely?
