### ISSUE TITLE
Region infrastructure administration

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#436]
Enhancement for #232 

- A user interface should enable users to add, edit and archive regions, districts and communities. #803 and #1412 
- It should be possible to import a complete set of regions, districts and communities via csv based on a defined format #1464 
- It should be possible to change the region of a district and district of a community. This will have to update all entities that are using the district/community (see #803)

**Comment by bernardsilenou** [comment]
This is excellent idea. However, I see challenge with retrospective case creation whose epid number is based on old infrastructure. Can we make it possible to fro the user to load more than one infrastructure data and choose the one to use at any time? this will solve the issue of retrospective data entry.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I'm not sure whether I understand you correctly, but if you mean that users should be able to create cases in facilities using their "old" district, I doubt that will be possible. However, I don't really see a problem with it anyway because they can just type in the original epid number and will be fine.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  That is what I meant but I think it will complicate the whole stuff. Lets go with what you suggest.

**Comment by MartinWahnschaffeSymeda** [comment]
See issues mentioned above
