### ISSUE TITLE
Line listing allows the creation of cases that have missing mandatory information

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#4390]
### Feature Description
The line listing form is one of the options of adding cases to the SORMAS database. The mandatory fields ensure some minimum essential data of cases are captured.
### Problem Description
The following mandatory fields are not marked on the line listing form.
1. Date of report
2. Facility
3. First name
4. Last name
5. Sex

### Proposed Change
Could we mark these five fields as mandatory fields?
### Additional Information
![Screenshot 2021-02-15 at 10 55 20 AM](https://user-images.githubusercontent.com/71414361/107935523-c87c8480-6f81-11eb-8109-101e9287ab9f.JPG)

**Comment by MateStrysewske** [comment]
This is actually a pretty significant bug. The fields aren't only not marked, but they aren't mandatory at all, and there's no check when clicking on "save" whether any field that is usually mandatory has been left empty. This allows the creation of cases without a name, facility, and so on. We urgently need to fix this.

Concerning the original request in this issue (marking the fields as mandatory) - I think we had problems with that in the past because it potentially messes up the form. We might not be able to do that with the current UI techonology. If simply making the fields required is too bad for the styling, we need a solution that manually checks whether any field that is usually required during case creation is empty as soon as the user clicks on "save" and then presents an error to the user.

**Comment by BasilKaburi** [comment]
@MateStrysewske: Thanks. Alerting users to check and complete mandatory fields in order to add a case will be a good start.

**Comment by MateStrysewske** [comment]
Okay, so it seems like Vaadin uses very, very questionable method names. We've been using a method called "setValidationIndicatorsVisible" to hide the small red stars because they can mess with the layout. Turns out that this method actually DISABLES the requirement validation on these fields, which is something that's not described by the method name AT ALL. I'll re-enable the indicators, let's hope that users won't run into too many problems with the layout.

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as there is no validation for the Sex field 
![image](https://user-images.githubusercontent.com/70562142/107986154-246ff900-6fd4-11eb-9164-d1d720d18da2.png)

**Comment by Candice-Louw** [comment]
Related:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2201 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/1857

**Comment by raghupola-vg** [comment]
verified on latest version 1.57.0-Snapshot and issue is Fixed.
