### ISSUE TITLE
[SORMAS2SORMAS] As a recipient I want to be able to accept or reject a shared case from another SORMAS Instance [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4423]
### Situation Description
SORMAS 2 SORMAS interface pushes the information to the recipient's database without 
a.) letting know
b.) giving the opportunity to decline or accept the new case/contact

### Feature Description
There will be a limited set of information, that the recipient should be able see.
With this limited set of information the recipient hat to be able to either accept or reject the receiving of the case/contact
When accepting, the case/contact information will be available in the recipient's SORMAS instance
When rejecting, nothing of the information will be persisted in the recipient's instance.

### Additional Information
@HZI: The workflow has to be specified. 
1. How will the recipient know, that there is a new case/contact coming from another SORMAS instance? 
2. How will the sender know, when the attempt to send case/contact was a.) accepted or b.) rejected?
3. What information does the sender see so that he can decide wether to accept or reject?
4. Is there a time limit to reject / Accept?
5. Who is able to accept / reject?
6. Is withdrawing possible, this means: When a case was sent and not yet accepted or rejected, can the sender cancel the transmission request.
@Candice-Louw 
@kwa20 
@JaquM 
 
Brainstorming:
Add a new view in cases and contacts for "incoming/outgoing" with cases/contacts from other instances and  cases/contacts which were rejected or accepted

Answers and mockups will be provided until 24th of feb

**Comment by Marko-ilmkreis** [comment]
In my view it is mandatory that the receiving health office can reject/accept the shared case. It must also defined which user get a notification for the new case and whats happens if ths user is not in office (holiday, sick).

There must also a report or follow-up notification that the case war sucessful received by the new office to avoid any loss by technical/connection-error.

There is also a different way to initiate a sending like used in the XAusländer-Standard (http://www.osci.de/xauslaender1160/XAuslaender-1160.pdf).

The sendin health-office sends a request to the receiving one if they are in charge. If they agree, they accept the get the data send. That could be also a good option for data protection as the "new" health office only see all personal data and medical data if they agree that they are in charge.

Hier the flow-chart from page 97 of the specification (unfortunately ony in German):

![grafik](https://user-images.githubusercontent.com/74791118/108676565-b605cc00-74e8-11eb-907b-ddd09a08b070.png)

**Comment by Candice-Louw** [comment]
@AxelNennker - not sure if this topic is in your field of expertise, but your input is most welcome, please.

**Comment by AxelNennker** [comment]
Seems to be a needed feature worth implementing. 
Although, persons / cases must not end up in limbo between two Sormas instances. And reporting to the national authority (RKI) must stay consistent. cases must no disappear because the sender stops reporting it while the receiver has not accepted it.

Not sure about use case the receiving Sormas user being sick or on leave. I assume the received cases are shown to all users with the permission to import cases. So, there should always be someone on duty.

Maybe involve the person this case is about to prevent collusion between sender and receiver e.g. when the sender has too many positive cases and anti-corona measures would be advised but sends some percentage of cases to their "friend" who has a low number. The person who lives in one city, works in the same city might find it strange when the responsible authority changes. IDK - maybe I am overthinking this. Sormas wants to stay out of this legal and political minefield.

**Comment by Marko-ilmkreis** [comment]
@AxelNennker @Candice-Louw A limbo (nice word for this!) between two instances should not happend. If the sender ask/send the person to the receiving instance, he should be rsponsible until the new instance accept it. So the receiver should not able to send the case to the RKI or any other instance. 

Maybe the request can be forwarded to the responsible authority. e.g. Sende A request B to take over the case. Sender B resides in the city nor Nuremberg and the address belonges to the district of Nuremberg (C), The sender A might send it wrongly to B, so B should be able to forward it to C and A get a notification about it. But thats a point for much later. For now the rejection with the message "Please send to office C" is the best way.

In #4508 is explained how the responsibilty for the cases ae organized. So its not that easy to hand over a case to the friendly health office nearby. While the contact tracing might be possible by them, the quaratine order must come from the responsible office to become valid.

> Not sure about the use case the receiving Sormas user being sick or on leave. I assume the received cases are shown to all users with the permission to import cases. So, there should always be someone on duty.

The question is, who gets the notification if the person responsible is not in office. We arr having a front office and they are having shifts (early, late, weekend), so it must be possible that at least two users get notified if a new case arrives by Sormas2Sormas.

**Comment by Candice-Louw** [comment]
Notes from devs:

1. This issue seems to reference only cases or cases and contacts, so I think this should be made clear from the begining
2. The Sormas2Sormas feature seems to be a continuously growing feature, along with other Share mechanisms like Share to SurvNet, so I think this kind of feature would make more sense to have it's own dedicated place in the UI rather then being spread out across all existing entities which support sharing
2.a. For this I propose that instead of introducing a SORMAS 2 SORMAS button on each Directory, maybe consider introducing a new part of the application called Shared Data (name not very important) which could be a central place where users with certain roles can access it and view all the data that is being shared with a status like (Successfully Shared, Pending Approval, Rejected), besides this
2.b. Besides this, the same Shared Data place can be used a place to view incoming data and offer options to Approve or Reject certain data.
2.c. This way this Shared Data place can be easily extendable for any future data that is to be shared between SORMAS instances, and even further down the road, maybe for SurvNet as well.
2.d. Also, being a separate place can be easily hidden for systems which do not use this Share functionalities and even restricted to only certain roles, which I saw it's an open point of concern for not having entities in limbo
3. At the moment when a case is shared for example, the whole entity is sent to the receiving instance. I think technically what's to be requested here is a preceding step which only asks for permission, so my assumption is that when a Case is pushed, the Sending SORMAS instance will only ask for permission with a very limited set of info about the case, then when it's approved the handshake happens and the process that is currently happening at send will happen automatically on the backed side.
4. Being a system where approvals or rejects can happen by mistake, I think that all the attempts of sharing should be persisted with their final result -> Approved, Rejected

**Comment by Candice-Louw** [comment]
1. Reference is to Cases and Contacts.
2. a&b) 'Shared Data' menu item introduction is a great idea (Menu on the left).
3. Yes, please - limited data to be included in viewing (for Cases and Contacts) when deciding to accept/reject - UUID, DOB... (to be confirmed by data security officer).
4. Yes, please - if possible, with list of 'approved' or 'rejected' by whom (receiving entity, including date/time).

**Comment by markusmann-vg** [comment]
@Candice-Louw Please specify exactly:
"with a very limited set of info about the case" (& the same for contact)

**Comment by markusmann-vg** [comment]
General rules:
- The sending system keeps the editing rights until the receiver accepted the package
- The sending the system can revoke the request  
- The sending system sends just a preview (limited data set)

Shared data section:
- feature configuration
- just for accepting incoming packages (phase 1)
- includes the package, comment, preview data ( to be defined ) // (Types: cases & contacts, events, lab-messages)

**Comment by vidi42** [comment]
@Candice-Louw we still need to know what the following statement refers to:
> With this limited set of information the recipient hat to be able to either accept or reject the receiving of the case/contact

For starters we could maybe just show the:
* uuid
* some details of the attached Person like first and last name
* sender name
* comment

What do you think?

FYI @markusmann-vg @leventegal-she

**Comment by JaquM** [comment]
@vidi42 
They need to see:
For starters we could maybe just show the:

- uuid
- some details of the attached Person like first and last name, date of birth, sex
- reporting date
- place of stay
- sender name
- comment
- if it's handed with ownership or not

@Candice-Louw anything else in your opinion?

**Comment by kwa20** [comment]
They should also see 

for cases:
- disease (potentially also the variant)
- case classification
- outcome
- investigation status
- symptom onset date (if available)

for contacts:
- disease of source case
- date of last contact
- contact classification
- contact category (potentially type of contact)
- (contact status)

Depending on how extensive the comment via S2S we should think about how to best visualize them.

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket might also affect the problem discussed and worked on in #5333. I propose to leave it at the [solution proposed there](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5333#issuecomment-836253499). Don't change anything about the SymptomJournalStatus unless a Case/Contact gets transmitted after acceptance.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT
