### ISSUE TITLE
[Angular][BE] Cases Overview lazy loading. Cases Filtering. Proxi-api.

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4452]
### Situation Description
In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
- As it was discussed internally by the development team, some additional support (BE support) will be required as to facilitate the "lazy-load" and filtering on the cases overview page.
- Please add more specific requirements (dev wise). [MARIUS PLEASE FILL IN THE DEV REQUIREMENTS]

### Possible Alternatives
N/A

### Additional Information
- Only pick this task up in development when the requirements are set. Thank you!

**Comment by marius2301** [comment]
- do we intend to keep the cases in a cache for a better performance? For the moment I haven't seen any cacheing system in the application?

**Comment by MateStrysewske** [comment]
@marius2301 I don't know the technical details, so bear with me if I'm talking nonsense here. In theory it could be great to do this, and probably also a lot more feasible because this would be happening on the user-side and not on the server-side (as probably would be the case with our current Vaadin application?). However, that cache would have to be maintained pretty extensively, because there will be changes to cases or new cases very, very often, and that would either require to completely reload all cases OR partly reload the cache based on change dates, which would however be a bit volatile to technical issues (such as the change date not being updated for any reason).
