### ISSUE TITLE
 Message that the error will be reported to the support is confusing the user

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4478]
### Bug Description

If for some reasons some data could not be saved the user get the error message that it will be reported to the support. As far as I know no support ticket will be generated automatically.

This is confusing the colleagues.

Maybe there is a way to eliminate the part of reporting to the support.

22.021.2021: NEW WORDING: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4478#issuecomment-783123836

en-US | de-DE
|--|--|
An unexpected error occurred. Please contact your administrator and inform them about it. | Ein unerwarteter Fehler ist aufgetreten. Bitte kontaktieren Sie die IT-Administration und teilen Sie dieses Problem mit.

**Comment by Candice-Louw** [comment]
@Marko-ilmkreis - a error is reported/recorded in the system logs.  An administrator/support worker would then be able to access the logs to see what happened.

Agreed that it is not relevant for the end users to see this message, though.

We would be able to adjust this for the de-DE error message popups in the translation engine.  Please give your input? 

**Current:**
Der Fehler wurde automatisch an den Support gemeldet. | The error was automatically reported to the support.

**Suggested:**
Bitte versuche es erneut. Wenn der Fehler weiterhin besteht, wenden Sie sich bitte an Ihren Administrator und teilen Sie ihm dieses Problem mit. | Please try again.  If the error persists, please contact your administrator and inform them of this.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis The purpose of this error message is to let the user know that it's potentially possible for whoever manages the server to follow up on the issue, and that it isn't strictly ignored. I agree that it is misleading though, and that we should probably change the message. Doing this for the standard English language would be our task, everything else needs to go through Crowdin as Candice already mentioned.

@Candice-Louw I would not use the phrase "Please try again" in the error message because it's highly unlikely that whatever the user tried would work when they try it again. If these red error messages appear, they will continue to appear. I would suggest the following text instead:

"An unexpected error occurred. Please contact your administrator and inform them about it." / "Ein unerwarteter Fehler ist aufgetreten. Bitte kontaktieren Sie ihren Administrator und teilen Sie ihm dieses Problem mit." 

I would also suggest to use proper gender language for the German version, but I have to admit that I don't know what the currently suggested approach is in this regard.

**Comment by Marko-ilmkreis** [comment]
@Candice-Louw @MateStrysewske Thank you for the feedback. The gender the German version I would suggest:

"An unexpected error occurred. Please contact your administrator and inform them about it." / "Ein unerwarteter Fehler ist aufgetreten. Bitte kontaktieren Sie die IT-Administration und teilen Sie dieses Problem mit."

I know that the German expression is not the best, but the best I found to gender it (https://www.genderator.app/wb/it-administrator/)

**Comment by Candice-Louw** [comment]
@Marko-ilmkreis - thank you!  Looks and sounds great. 👍

**Comment by DavidBaldsiefen** [comment]
Weirdly enough, this change was already done for the swiss translations.

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - I do the Swiss translations, yes, and made the change for them soon after this issue was created as a temporary workaround. :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
