### ISSUE TITLE
symptoms at contact person

### ISSUE THREAD

**Issue by hamedhedayat** [hzi-braunschweig/SORMAS-Project#4487]
### Situation Description
It is not possible to enter symptoms in contact person.
### Feature Description
Because the contacts can be a case later, the symptoms that were in the contact time will also be important. therefore, it must be able to enter the symptoms at contact person.

### Possible Alternatives
No possible alternatives

**Comment by bernardsilenou** [comment]
@hamedhedayat I think we are using terms differently here. 
- The symptoms of a contact person are recorded for each followup done on  the contact person. 
- when a contact person becomes a case, then the symptoms are transferred to the case, mainly the last visit symptoms.

- A contact can have symptoms that has nothing to do with the case. For example, when following a contact person to a covid case, on day 1, the person can have headache. The person doing this followup can document this symptom while doing the visit.
When the contact then become a case on day 10, we do not need to copy all the symptoms of the contact to the case because this may produce wring data.  We automatically copy the last symptom since this is likely related to the contact becoming a case. 

- The symptom in the case is the collection of symptoms from symptom onset of the person as a case not any other symptom while the person was a contact .
- All the symptom data is stores in the systems, thus not lost

- Do you want that the system should automatically copy all symptoms from the visits of the contact to the case? Or how should the symptom table of a contact be defined?

**Comment by hamedhedayat** [comment]
Has resolved many thanks for the explanation
