### ISSUE TITLE
Cases > Case > Changing the "Facility" results in reassignment of an existing Task to a random other user

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4507]
Updated definition: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4507#issuecomment-793539839

### Bug Description
Changing `Facility` for Cases assigns a random new `Assigned to:` value for Tasks associated to the Case.

### Steps to Reproduce
1. Cases > Open/Create Case1 > 
2. Create Task for Case1 and assign it to "User A".
3. Case1 > Set ` Place of Stay` to be "Facility", `Facility Category` as "Medical Facility", `Facility Type` as "Hospital", and select a value from `Facility` (from the list defined in the Configuration/Infrastructure data).
4. Save [Works fine]
5. Case1 > Change value from `Facility` (from the list defined in the Configuration/Infrastructure data) to another value > Prompt appears to change infrastructure data > Agree
6. Task associated with Case1 is now randomly assigned to "User X" (and not "User A" as it is supposed to stay).

### Expected Behavior
Task assignment should not change.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/108757271-e893e100-7549-11eb-990b-e01f4d86c634.png)
![image](https://user-images.githubusercontent.com/65529128/108756809-51c72480-7549-11eb-8645-ff83b9017be5.png)
![image](https://user-images.githubusercontent.com/65529128/108757376-0d885400-754a-11eb-914d-2911b794c806.png)

### System Details
* Device: Web
* SORMAS version: 1.56.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/ (Majatovic)
* User Role: admin

### Additional Information

**Comment by syntakker** [comment]
This behaviour seems to be intended, see `CaseFacadeEjb.assignOfficerOrSupervisorToTask` l. 2794. See code comments for the order of the assignee choice which indeed may include a randomly chosen assignee:

```
	private void assignOfficerOrSupervisorToTask(Case caze, Task task) {

		User assignee = null;

		if (caze.getSurveillanceOfficer() != null) {
			// 1) The surveillance officer that is responsible for the case
			assignee = caze.getSurveillanceOfficer();
		} else if (caze.getDistrict() != null) {
			// 2) A random surveillance officer from the case district
			List<User> officers = userService.getAllByDistrict(caze.getDistrict(), false, UserRole.SURVEILLANCE_OFFICER);
			if (!officers.isEmpty()) {
				Random rand = new Random();
				assignee = officers.get(rand.nextInt(officers.size()));
			}
		}

		if (assignee == null) {
			if (caze.getReportingUser() != null
				&& (caze.getReportingUser().getUserRoles().contains(UserRole.SURVEILLANCE_SUPERVISOR)
					|| caze.getReportingUser().getUserRoles().contains(UserRole.ADMIN_SUPERVISOR))) {
				// 3) If the case was created by a surveillance supervisor, assign them
				assignee = caze.getReportingUser();
			} else if (caze.getRegion() != null) {
				// 4) Assign a random surveillance supervisor from the case region
				List<User> supervisors =
					userService.getAllByRegionAndUserRoles(caze.getRegion(), UserRole.SURVEILLANCE_SUPERVISOR, UserRole.ADMIN_SUPERVISOR);
				if (!supervisors.isEmpty()) {
					Random rand = new Random();
					assignee = supervisors.get(rand.nextInt(supervisors.size()));
				}
			}
		}

		task.setAssigneeUser(assignee);
		if (assignee == null) {
			logger.warn("No valid assignee user found for task " + task.getUuid());
		}
	}
```

**Comment by JonasCir** [comment]
@Candice-Louw As already mentioned, this is intentional. Here is the readable logic:

Re-assign the tasks associated with this case to the new officer (if selected) or the surveillance supervisor if the facility has changed:


1. Pick the surveillance officer that is responsible for the case
2. A random surveillance officer from the case district
3. If the case was created by a surveillance supervisor, assign them
4. Assign a random surveillance supervisor from the case region

So in case you change the facility and there is a `SurvOff` or `SurvSup` it will be retained. In case they are missing, a new user gets randomly picked. Do you see need to adjust the existing logic of this @Candice-Louw ?

**Comment by Candice-Louw** [comment]
@syntakker @JonasCir - thank you for figuring this out!  In the context of COVID, it seems that the majority of these tasks are assigned to users with role SurvSup and ContSup (at least in CH).

Would it be possible to add in checks to see if there is already a SurvSup assigned to the case (which didn't necessarily create the case), which falls in the case district, please?

I.E. Before "2. A random surveillance officer from the case district", would be the new number 2 as: "If the case was not created by a surveillance supervisor, but currently has a surveillance supervisor assigned, and the assigned surveillance supervisor is also in the case district that the case will be moved to, assign them".

So, if the case is changing institution, not changing Responsible District, and has a SurvSup assigned already, assign them.

If you don't agree with the logic, it's understandable.  I was informed that this change is very seldom, but when it does happen, the case goes lost with the current logic even if it is transferred within the current Responsible District and technically then stays in the same jurisdiction, so nothing should change.

**Comment by MateStrysewske** [comment]
@Candice-Louw @JonasCir @syntakker That sounds like a pretty complicated logic to me :)

I think in general it doesn't really make much sense to reassign tasks if ONLY the health facility changes. It totally makes sense if e.g. the district is changed as well because at that point another surveillance officer would definitely need to be assigned, but I guess that's not a problem in Germany anyway because their servers are operating on district level.

So my suggestion would be to simply change the logic in a way that makes sure that tasks are not reassigned if the only jurisdiction that was changed is the health facility - unless a user on facility level is assigned, in that case we would still need to reassign the task.

Do you agree?

**Comment by JonasCir** [comment]
Ok I think I have a fix. It will take some time to test it though.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
