### ISSUE TITLE
Facility data not shown when open the location dialog

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#4511]
### Bug Description
Existing Facility data which is shown in the location of Exposure and "Activity as Case" forms is not shown. The data can be saved but it is not shown.

### Steps to Reproduce
1.Open a case, GoTo "Epidemiological info", start edit mode
2. Open an exiting Exposure or ActivityAsCase form on which you know that Facility data has been previously recorded.
3. Open Location Dialog
4. The Facility fields are empty

### Expected Behavior
4. The facility fields should be seen on the form

Hints: 

### System Details
* Device: Android
* SORMAS version:1.58
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
Additional details:
* I guess this does not happen when you properly record a facility; it does happen when you only record a facility category and type (@sergiupacurariu correct me if I'm wrong)
* If you only select a facility category and type, but not a region and district, the facility list will be empty (not even the "Other" facility will show up) - this basically leads to this problem because users can't select a facility in the first place
* I, however, think that's somewhat fine, we just need to make sure that the facility type is properly shown even when no facility is selected

**Comment by sergiupacurariu** [comment]
There is one allowed situation in which an Android user cannot see correctly the Location data while in the web app this situation is allowed.
At the moment on the web app is possible to add an exposure or activity, set the facility type and category to it, and leave Region and District fields empty.
If the above record is opened in Android app the user sees the Facility information fields from Location empty. The user might presume that nothing was inserted there.

**Comment by raghupola-vg** [comment]
Tested and verified on Android app with version 1.58.0-snapshot and issue is Fixed.
