### ISSUE TITLE
[EDiary Integration] add button to stop using the ediary and switch to manual Follow-Ups by phone. [2]

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#4516]
### Situation Description
If a contact (or case) has been enrolled in the external symptom journal but wants to receive a call and not a Email (or was enrolled by accident) this cannot be done, except by pressing "Nachverfolgung abbrechen" (Cancel Follow-Up). This cancels the whole Follow-Up process, including the manual one, and affects the filters. 

### Feature Description
Add a button **(tbd: where? next to 'Climedo ediary' button/ next to 'Cancel followup' button)** used for cancelling tracking by the external journal and switching back to manual follow-up.
The external journal status of the person should be changed. **(tbd: no status / changed to CANCELED / add new status?)**

### Additional Information
Check with the CLIMEDO team if their API supports this (un-registering a person)

**Comment by FredrikSchaeferVitagroup** [comment]
It is supported by the API. See https://github.com/hzi-braunschweig/SORMAS-Project/issues/4292. 

Again, the followUpStatus and the SymptomJournalStatus should not be mixed up. To cancel follow up just to unregister a person from a symptom journal is not the way to go. What users are expected to do here is to go to the external journal (for example via the button in a related contact or case in SORMAS) and delete the account there. The external journal should then update the SymptomJournalStatus of that Person to DELETED, while the follow up status remains untouched. 

In the last planning, we decided against a deletion function for external journals from within SORMAS.

**Comment by vlad-ciucescu** [comment]
Won't do then.
Similar to #4517 , #4292

**Comment by FredrikSchaeferVitagroup** [comment]
It was decided with @markusmann-vg that this issue has to be reopened. The reason is that users shall be able to manage required climedo functionalities from within SORMAS (they shall not need to deal with the climedo UI at all). That is why I propose the following approach:

1. For persons with a SymptomJournalStatus that is not REGISTERED or ACCEPTED, show the climedo button like it is now.
2. For other persons, show the button similar to the export button in the contact view:

![image](https://user-images.githubusercontent.com/67001822/109138851-1c922080-775b-11eb-843c-dd170da15fcb.png)

The CANCEL EXTERNAL FOLLOW UP makes a DELETE call to the endpoint described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4292 and shows the response in a popup window. When the request was processed sucesfully, the SymptomJournalStatus of that person shall be updated to DELETED.

The OPEN PERSON IN CLIMEDO forwards to the climedo UI like the button did so far for registered persons.

This approach does not strain the UI experience with another button and should be nicely extendable with further climedo functions. 
Also, the climedo button like that shows blue for unregistered persons, and white for registered ones. So the SymptomJournalStatus can nicely be determined when in the ContactDataForm, for example.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest versio of SORMAS
Version: 1.58.0-SNAPSHOT on GA1 environment

**Comment by FredrikSchaeferVitagroup** [comment]
When registering a new person from the contact data view, the registration works. But the button "REGISTER IN CLIMEDO EDIARY" still shows after that. Instead the view should refresh automatically and the dropdown-like climedo button should show.

It also necessary to check oe same for the case data view.

**Comment by FredrikSchaeferVitagroup** [comment]
Furthermore, when a user clicks the REGISTER IN CLIMEDO EDIARY again after successful registration, the following message shows:
![image](https://user-images.githubusercontent.com/67001822/111585690-fbec4200-87bf-11eb-8c84-38cc65e5e6d6.png)
That is obvioulsy wrong. It should be check whether this results out of wrong behaviour on SORMAS-side or we get the wrong error message from climedo.

**Comment by AndyBakcsy-she** [comment]
validated on the latest version of sormas 1.58.0-snapshot on ga1.sormas.netzlink.com environment
