### ISSUE TITLE
Samples directory shows less entries than the samples.csv

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4602]
### Bug Description

In the samples directory are shown 15453 entries for samples:

![grafik](https://user-images.githubusercontent.com/74791118/109780583-708f8000-7c07-11eb-9f00-8808aeee9b30.png)

If you download the database data via statistics -> database export in the samples.csv are 24531 entries.

The difference is very high in my opinion. One possible cause could be that before we used Sormas I very often tested the import of the old data and deleted the cases/contacts afterwards. I remember that I checked after deletion of the cases if the directory was empty and it was. Maybe the samples were not deleted automatically or they were only unlinked. 

I think thats the cause as for the very first imports I used "NASAL_SWAB" for samplematerial, while for the final tests and the final import I used "NP_SWAB". There are more then 4000 entries in the csv with this samplematerial.

I tried to make an detailed export, but this fails due to the high amount of entries in the directory.

### Steps to Reproduce
1. Import datas with samples into the database
2. delete the cases 
3. export the database and check if  the sample is still in samples.csv

### Expected Behavior

Samples should be deleted together with the cases/contacts/ep automatically.

Maybe there could be a tool implemented to delete unused/unlinked data from the database, specially samples where no person is linked to.

### System Details
* SORMAS version: 1.56.1
* Android version/Browser: FF10
* User Role: National Clinician, Admin, ReST User, National User

**Comment by MateStrysewske** [comment]
Cases, contacts and event participants aren't actually deleted from the database when you delete them in the UI, they are only flagged as deleted and hidden from the user. That's why they still appear in the database export, but not in the directories or statistics anymore. I don't see any misbehaviour here - it's expected that the sample directory contains less entries than the database export.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske I got it. But thats weird to the user, because for data protection there shouldn't saved data in the database which are "deleted" in opinion. Maybe a way could be to introduce a  "trash bin" for admins.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Normal users would never be affected by this because they don't have access to the database export, so for them, the cases, contacts, event participants, samples, etc. are actually deleted. Not hard-deleting them is necessary because we need to store data for a specific amount of time. A trash bin is also something that we discussed in the past, but ultimately doesn't really make much sense because deleted data is indeed totally irrelevant, and there's no reason to look at them again retrospectively.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske But in my opinion it is a breach of data protection rules if we store datas of users which should be deleted. In excample if we save data from a person by mistake, that data must completely deleted and not only marked as deleted.

Do you know for what reason we have to store data the data of deleted persons for a specific amount of time?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis There will be a proper deletion concept introduced soon that e.g. will contain things like completely anonymising deleted data after a specific amount of time. Also I think it makes sense to introduce some sort of functionality that allows completely deleting stuff from the database within, let's say, 10 minutes of creation (so if I mistakenly create a case, I can remove it from the database directly afterwards, but not a day later or so).

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Thats would be good. I would stretch the time for completely deleting stuff to 24 hours. Sometimes the person entering the data did not know that this is wrong and it only appears if someone double check it. We also have regular that colleagues by mistake entering a contact twice and just clicking the duplicates detection :-/ I know thats a mistake by user, but also for that contacts it should be possible to delete them completely.
