### ISSUE TITLE
[SurvNet Interface] Add additional fields to event clusters [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4720]
### Situation Description
The SurvNet interface requires additional IfSG relevant fields that describe the mode of transmission in more detail.
### Feature Description

- (DE only) Add a subsequent enum field `INFECTION_PATH_CERTAINTY` (caption: "Certainty of infection path") to nosocomial. Only show the enum when YES is selected in nosocomial. Add the following values:
    - Suspect
    - Probable
    - Confirmed
    - Unknown
    
- Add a subsequent enum field `HUMAN_TRANSMISSION_MODE` (caption: "Mode of human to human transmission") to primary mode of transmission. Only show this field when "primarily via human to human" was selected. Add the following values:
    - Fecal-oral/smear infection
    - Parenteral
    - Direct skin contact
    - Respiratory 
    - Sexual
    - Connatal
    - Other

- Add a subsequent enum field `PARENTERAL_TRANSMISSION_MODE` (caption: "Mode of parenteral transmission") to mode of human to human transmission. Only show this field when "Parenteral" was selected. Add the following values:
    - Intravenous drug use
    - Household contact
    - Medically associated
    - Tattooing/piercing
    - Pedicure/manicure
    - Other
        
- Add a subsequent enum field `MEDICALLY_ASSOCIATED_TRANSMISSION_MODE` ("Mode of medically associated transmission") to Parenteral. Only show this field when "Medically associated" was selected. Add the following values:
    - Operative or diagnostic procedure
    - Blood products
    - Organ transplantation
    - Dialysis
    - Injection for medical purposes

### Additional Information
<img width="756" alt="Screen Shot 2021-03-10 at 11 25 32 PM" src="https://user-images.githubusercontent.com/70317594/110706323-f7d88700-81f7-11eb-83a3-35413d9b139a.png">

**Comment by bernardsilenou** [comment]
@kwa20 question and comments pls:
- [ ] What does infection path/ source ...  of an event mean? Can we use another names for the categories rather than suspected, probable and confirmed as used for case classification? A group name that represents all the options (med, vehicle, source) may be good. If we can find a group for all, then we can consider collecting them a separate variables.
- [ ] Nosocumial infection by definition should only apply to clusters in hospital. Options like sexual, Tatooing, Household contact, etc, do they apply for hospital exposures ? If I got it, then would suggest we migrate some of the variables to general events.
- [ ] Parenteral are more about infections through needles/ blades that cut into the body, maybe we drop the category  `Household contact`
- [ ] Can we call the caption medically associated as `medical procedure` or `medical Intervention` `medically associated procedure`, just not to use the same name twice.

**Comment by kwa20** [comment]
@bernardsilenou the infection path etc. describes the certainty of the infection path that is associated to the nosocomial outbreak. All these fields are IfSG relevant so I'd prefer to keep the values and map them one to one. If the values do not apply to other users outside of Germany I'd suggest to hide them as we do for swiss values too

**Comment by MateStrysewske** [comment]
@kwa20 @bernardsilenou I agree with Bernard that the name of the first field is really, really hard to understand and should be renamed. Why don't we call it "Certainty of infection path" if that's what's described by it?

Apart from that, I've also edited the initial post and changed the names of the new fields to differentiate them from the enum values. Do you agree with these names?

**Comment by kwa20** [comment]
@MateStrysewske your headers name look good to me. Maybe we should add a mouseover for the header of the infection path field? Maybe even an (i) info icon? Something like this: "certainty of proof in regards to the infection path/ source/ vehicle/ medical procedure in a nosocomial relation of the infections".

**Comment by MateStrysewske** [comment]
@leventegal-she Please add the text suggested by @kwa20 as the description of this field

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske  :+1: 
What i still do not understand is the relationship between Parenteral and household contact, but all is fine.

**Comment by AndyBakcsy-she** [comment]
Verified titcket on the latest version of sormas v 1.58.0-snapshot
