### ISSUE TITLE
Search for double contacts

### ISSUE THREAD

**Issue by heineltp** [hzi-braunschweig/SORMAS-Project#4724]
Hello,
i was searching for similar issues but did not find one. If i did not find it please close my issue and then sorry.

there is an option to search for double cases.

but there is no option to search for double contacts too.

I am talking not about the persons, i am talking about the contact situations.

I Cant understand why this feature is not given, it is very important for the cases and even more important for the contacts because of the probably multiplicated higher number of contacts in comparison to the managed cases.

could this feature be added to the contact menue too?

Thank you
kind regards
Philippe Heinelt

**Comment by MateStrysewske** [comment]
@heineltp Hey! #2409 is this exact same feature request. It's not been done yet because of different prioritisations. A development team from French had already started to work on it, but they had to restructure their teams and had to drop their work again. I guess that they will continue development on it again soon.

**Comment by heineltp** [comment]
okay thank you i will follow up on the other issue
