### ISSUE TITLE
Individualize the notifications sent to users responsible for an event when an event participant becomes a case

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4732]
### Situation Description
Development # 3794 must be extended with additional development.
To date, this notification is integrated into all "other notifications". In France, we do not want to activate all the other notifications since this generates too many emails (change of status of a case, new associated contact ...)

### Feature Description
Two solutions can be considered:
1. Individualize the notifications sent when a person participating in an event becomes a confirmed case (such as the notification sent in the event of a named assignment of a task)
2. Make a more substantial development allowing you to configure the choice of notifications that you want to activate or not. There will no longer be "other notifications" grouping together several actions, but the notifications will be individually configurable for each action.

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by MateStrysewske** [comment]
@carolinverset The second option would of course be really great, but indeed require quite some design thinking and development work. What's your preferred solution for now?

**Comment by carolinverset** [comment]
@MateStrysewske @ftavin
I think that other developments relating to notifications will follow, so in my opinion it will be better to carry out the second proposal and I'm sure François and his team will have some very relevant suggestions like always :-)
But I'll let @ftavin clarify what he thinks about it in terms of timing. It should not be implemented too late in order to be able to use the function developed for 1.56.

**Comment by ftavin** [comment]
@MateStrysewske @carolinverset solution 2 needs to be refined with my developpers but I had in mind a configuration using a format more practical than .properties for this part, more like json, in a separate file (I'm not sure if it is a good thing to make sormas.properties bigger and bigger with time).

We could have a notifications.conf with a tree-like structure that would permits to choose the level of detail wanted for a given instance.

Here is an exemple of what I have in mind :

![notifications](https://user-images.githubusercontent.com/15834125/110864907-0f307680-82c3-11eb-8cd3-78c3f1095418.png)

In this exemple we activate all notifications related to contacts, none related to tasks and some of the notifications related to cases...

(this is not an actual format, I'll let the developpers see what would fit best to the need)

Of course this will imply that we start by listing all the existing notifications and group them to elaborate the structure of the conf file.

That's why I would suggest to start with the first solution (actually the developement is already done on our side, it was not time-consuming). That will permits to use the "event participant becoming case" notification in France while we take the time to elaborate the more advanced notifications configuration mechanism that, I believe, will quickly become necessary.

**Comment by MateStrysewske** [comment]
@ftavin I definitely support a solution like this. I think configuration files in the JSON format are the way to go for all kinds of configurations that we will have to introduce in the future. If you want to work on this and your developers can come up with an implementation proposal, I'd review it together with our lead architect. I'm also totally fine with using the first approach for now if it's important for you.
