### ISSUE TITLE
[DEMIS Adapter] Return XML representation of a labMessage when conversion to HTML fails

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4742]
### Feature Description

The DEMIS-Adapter provides a method to convert labMessages to viewable format. This method parses the original demis notification (represented as XML) and returns a html representation of it.

### Problem Description

When something goesg wrong in this process, the adapter returns an error. An error message is then showed to the user in the SORMAS-UI. Like that, when something goes wrong, the user can just not open a labMessage to find out more about it, which blocks the processing.

### Proposed Change

Some users dealt with XML-representation of demis notifications before. If the conversion of a DEMIS notification fails, it would be better to return its XML-representation instead of just returning an error message. Like that, users could at least see some (ugly formatted) information about the labMessage instead of not being able to see any details of a labMessage at all.

**Comment by vlad-ciucescu** [comment]
The alternative display mode is used when the message received from Demis has a modified or wrong structure. Since we cannot depend on that, in order to test this functionality the code or database data must be modified. I and @FredrikSchaeferVitagroup tested this locally on our systems and using different browsers and I think we can consider this ticket validated.

Hopefully we see this feature as rarely as possible on other systems :)
