### ISSUE TITLE
Certain event participants get transferred to mobile app without their events getting transferred as well

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4748]
### Bug Description
Fixing the persons displayed in the person directory has introduced a new bug that will synchronize event participants from the user's region to the mobile app without also synchronizing the event itself.

### Steps to Reproduce
1. Create an event in a region that differs from the app user's region
2. Create an event participant for that event and set its responsible jurisdiction to the user's region and district
3. Try to synchronize

### Expected Behavior
Preferably:
* Synchronize events to the app when at least one event participant is in the user's jurisdiction

Alternatively:
* Don't synchronize event participants when the event would not also be synchronized

**Comment by bernardsilenou** [comment]
@MateStrysewske Just to further checking for contacts in a jurisdiction of the user with the source case of the contact is not  the jurisdiction of the user.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really understand what you're trying to say

**Comment by bernardsilenou** [comment]
@MateStrysewske You know when case A is  in district A and the contact of the case is in district B. I connected with a surveillance officer + contact officer tablet in district B and saw the case in district A as Pseudonymized ( this is OK) but the contact directory was empty. Normally I was to see contacts B.

This is just a suspicion that the cases A sync to the mobile app but contact B may have issues.  I could not validate this since app could not sync back with server.

**Comment by MateStrysewske** [comment]
@bernardsilenou That's working fine for me, it's possible that the contact just wasn't synced for you because of the problems during event syncing.

**Comment by AndyBakcsy-she** [comment]
verified on the latest version of sormas 1.58.0-snapshot on test.sormas.netzlink.com
