### ISSUE TITLE
Immunizations II: Immunization overview and add/edit form [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4764]
### Situation Description
#4081 introduces the full immunization module. It would be good to read it before working on this.
### Feature Description
- [ ] Immunization directory
- Add a menu  item below samples 
- column variables: uuid, disease, first name, last name, ImmunizationStatus, immunidationStartDate, immunidationEndDate, 
- [ ] Immunization directory filter options
- followup status: all, under followup, ….. 
- general filter based id, person identifiers
- immunization person month, day and year of birth
- facility filters: region, districts, community, facility, ….
- checkbox called "Overdue immunization": computed on the fly as true if (current date > immunidationEndDate and sum (vaccination) < expected number of dose)
- disease (no multi-select)
- date:
-  date type: report date | immunization start, this should be enough, no need for (immunization end)
-  date ranger filter: from … to
- [ ] Immunization directory link to person search
-  add a box on the right below events to show all immunizations that the person is associated to.
- Variables to show in the box are: date of last vaccination, immunization end date, followup status , see immunization of this person link to the immunization directory filtered for the specific immunizations of the person.
### Development Specifications (WIP)

For all the new elements, ONLY show them if the `IMMUNIZATION_MANAGEMENT` feature configuration is enabled.

#### Overview
* Add a new main menu entry called "Immunizations" below Samples
* Only accessible for users with the `IMMUNIZATION_MANAGEMENT_ACCESS` user right
* Add a grid that contains all persons that the user has access to (similar to the already existing person directory) and that have at least one immunization entity connected, but with the following columns:
  * Immunization ID (containing the UUID)
  * Person ID (containing the UUID)
  * First name
  * Last name
  * Age and birth date
  * Sex
  * District (from the home address)
  * Means of immunization
  * Management status
  * Immunization status
  * Immunization start
  * Immunization end
  * Last vaccine type (the vaccineType of the latest vaccination)
  * Date of recovery
* The grid always needs to be filtered by a single disease and shows the data from the most recent immunization for that disease; if no disease has been selected, don't show the grid, but instead a label with bigger font size with the following text: "Please select a disease to display the immunization overview."
* Add the following filters:
  * Disease (if there is only one active disease on the server, set it to that disease by default)
  * General text filter to search for persons (as in person directory)
  * Birth date filters for persons (as in person directory)
  * Home address filters for persons (as in person directory)
  * Means of immunization
  * Management status
  * Immunization status
  * Jurisdiction filters for the most recent immunization (down to facility level)
  * Date filters (date type: report date, immunization end, validUntil, date of recovery, last vaccination date (= the date of the latest vaccination), first vaccination date (= the date of the first vaccination))
  * Checkbox: "Only show persons with overdue immunziation" (should show persons where the latest immunziation is ONGOING and the current or filtered date is after the immunization end date)
* Add a "New immunization" button to the top right of the screen that opens the immunization creation form

#### Creation form
* Add a new `ImmunizationCreationForm` that can, for now, be accessed by clicking the "New immunziation" button in the immunziation overview
* Only accessible for users with the `IMMUNIZATION_CREATE` user right
* The form consists of two parts - information about the immunization itself and about the person that it is associated to; person fields can be similar to those in the case creation form and should be at the bottom of the form
* Add the following fields for the immunization:
  * Report date (required)
  * Disease (required)
  * Means of immunization + details if "Other"; if "Recovery" or "Other" is selected, set the management status to `COMPLETED`
  * Checkbox "Overwrite immunization management status" - if checked, management status becomes editable
  * Management status (read only; set to SCHEDULED) - automatically updates the immunization status: if scheduled or ongoing, immunization status = pending; if completed, immunization status = acquired; if canceled, immunization status = not acquired
  * Immunization status (read only; set to PENDING)
  * External ID
  * Responsible region, district, community and facility (required)
  * Start date (required)
  * End date
  * Number of doses (text field, validation that makes sure only integers are added; only visible if means of immunization == Vaccination or Vaccination/Recovery)
* When clicking on "Save" in the creation form, we need a two-part duplicate detection process (person duplicate detection is similar to e.g. when creating new cases):
  * First, check for potential duplicates of the specified person
  * Secondly, if an existing person has been selected in the first step, search for immunziations associated with that person according to the following criteria:
    * Same disease
    * Overlapping immunization period defined by start and end date
  * If a duplicate immunization is found (there should never be more than one), show a popup (use the dupliate case popup as a reference) with the following contents:
    * An info text (and an info icon to its left side): "The system already contains an immunization for {disease name} for this person that overlaps with the specified immunziation period. Please compare the existing immunization with the one you created and decide whether to discard the new immunization or use its information to update the existing one."
    * An overview of the existing immunization, displaying the same information as in the creation form (without person information)
    * A radio button below this line: "Keep the existing information and discard the new immunization"
    * An overview of the immunziation information that was just entered, same as for the existing immunization
    * A radio button below this line: "Overwrite the existing immunization with this data"
    * None of the radio buttons should be selected by default
    * Popup has two options: Discard and Confirm; Confirm should only be enabled when one of the radio buttons is selected

#### Edit form
* The edit form should be displayed on an individual page after clicking on the UUID of the immunization or double clicking on a row in the immunization overview
* Read-only for users without the `IMMUNIZATION_EDIT` user right
* Edit rights are based on the responsible jurisdiction of the immunization
* The page has two tabs: Immunization and Person 
* The immunization tab contains the same information as in the creation form (without the person information, of course), plus the following fields:
  * Reporting user (read only)
  * Previous infection with this disease (Yes/No/Unknown)
  * Date of last infection (only visible if previous infection == Yes)
  * Additional details (text area)
  * Heading "Vaccination" (this and its dependent fields are only visible if means of immunization == vaccination or vaccination/recovery)
    * Number of doses (text field, validation that makes sure only integers are added)
  * Heading "Recovery" (this and its dependent fields are only visible if means of immunization == recovery or vaccination/recovery)
    * Date of first positive test result
    * Date of recovery
  * Immunization country (not related to the responsible jurisdiction fields)
* When saving, check whether there is any other immunization of this person and disease in the system that has an overlapping time period (defined by start and end date); if that's the case, DON'T save and display a popup instead:
  * Show the following message: "The system already contains an immunization for {disease name} for this person that overlaps with the specified immunization period. Please adjust the immunization period and save again."
  * Show two read-only text fields below: "Immunization period of this immunization" and "Immunization period of existing immunization"
  * Caption for the button that closes the popup: "Okay"
* Use the same logic and automation for means of immunization, management and immunization status as in the create form
* Edit form needs to include archive and delete option (only for users with the `IMMUNIZATION_ARCHIVE` and `IMMUNIZATION_DELETE` user right, respectively)

**Comment by kwa20** [comment]
@MateStrysewske Minor comment:

- Instead of just latest vaccine type, use latest vaccine name (+ type)
- Also add latest vaccination date as a column on the directory next to lastest vaccine name

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske 
Few comments please:
- Can the developer add  some mockups for the forms and directories before implementation just to be sure that we are all on the same page? Similar to other related issues.
-  Means of immunization (`order: vaccination, recovery, ..., other`) + details if "Other"; 
- `Management status (read only; set to SCHEDULED) - automatically updates the immunization status: if scheduled or ongoing, immunization status = pending; if completed, immunization status = acquired; if canceled, immunization status = not acquired` 
- I do not think i understand this point well, suggest immunization status should not depend on the management status.
We can compute immunizationstatus based on, if (the expected number of dose == sum of vaccinations) OR user can directly override the logic and chose the category for immunizationstatus.
- `Immunization status (read only; set to ONGOING),`
- can we call this "unaquired", Ongoing sounds more like a management status
- External ID (move to edit form in case the reduced from it full?)
- Maybe add the `Expected number of dose` on the creation form also since we need them for the logic for manamgement status 

`Heading "Vaccination" (this and its dependent fields are only visible if means of immunization == vaccination or vaccination/recovery)
Number of doses (text field, validation that makes sure only integers are added)
Heading "Recovery" (this and its dependent fields are only visible if means of immunization == recovery or vaccination/recovery)
Date of first positive test result
Date of recovery`
* A person can recover and still  get enrolled in an immunization program,  ie immunization == vaccination and recovery, so it would be good to show all variables as optimal on forms? 
* Is there a reason why do we need Date of first positive test result ?, can we just document "Date of recovery" only? you get immunized when you recover often, so better to start counting on this date.

**Comment by MateStrysewske** [comment]
@kwa20 Updated the specifications accordingly.

@bernardsilenou
* We calculate the immunization status based on the management status because we automatically update the management status based on the status of the immunization entity; I think the logic makes sense, but Kay might explain it to you in a bit more detail.
* "ongoing" was actually meant to be "pending", changed it
* I would like to leave everything that is dependent on the means of immunization out of the creation form to keep it simple, but I see your point; what do you think @kwa20?
* If "Vaccination/Recovery" is selected as a means of immunization, both sections are shown; this is already specified in the instructions

**Comment by kwa20** [comment]
@MateStrysewske @bernardsilenou adding elected number of doses to the creation form would be very good yes :)

**Comment by bernardsilenou** [comment]
@MateStrysewske 
The management status is not still clear, Kay would explain it to me tomorrow and we would add a comment.

Consider a scenario whereby a person get the first vaccine and never comes back (lost to followup). The management status can be ended (closed or cancelled) and immunization status at this point is unknown/ missing.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't see a problem with that; if the management status is set to CANCELED, according to the rules stated above, the immunization status will be set to NOT_ACQUIRED, which would cover your described scenario.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4764#issuecomment-871196716 is the exact point I wanted to clarify with @kwa20 and @JaquM 

The thought  I had in mind is that if the management status is CANCELLED then we can set the immunizaton status to something like "Unknown" (undetermined).  NOT_ACQUIRED would then represent a state for management status that are not closed.

**Comment by MateStrysewske** [comment]
@alexcaruntu-vita Since you have added the missing validUntil date in this issue, could you please also adjust the logic in ImmunizationFacadeEjb.updateImmunizationStatuses to use the validUntil date instead of the endDate? Thanks!

**Comment by AndyBakcsy-she** [comment]
Validated feature on the latest version of Sormas 1.64.0-snapshot on local environment

**Comment by MateStrysewske** [comment]
- [ ] Label for management status is missing
- [ ] Error when setting the management status back to empty

**Comment by MateStrysewske** [comment]
All these changes apply to the mobile and web app (unless the functionality is not present in the mobile app):

- [ ] Take over immunizations in case duplicate merging
- [ ] Show popup when changing means of immunization with at least vaccination present
- [ ] Start date has to be not required (make sure to remove the annotation in the DTO)
- [ ] Add all facility types to the immunizations, not only accommodations
- [ ] Display the UUID in the popup that displays similar immunizations when creating new immunizations
- [ ] Fix the date filters in the duplicate detection mechanism in the web app because they seem to have a bug; to reproduce it, create an immunization with start date 2021/09/06 and end date 2021/09/20, and then another immunization for the same disease and person with start date 2021/09/08 and no end date
- [ ] Extend the duplicate detection mechanism when creating new immunizations
  - [ ] Change the info text to "The system already contains at least one immunization for COVID-19 for this person and means of immunization that overlaps with the specified immunziation period. Please compare the most recent existing immunization with the one you created and decide whether to discard the new immunization, use its information to update the existing one, or create it anyway."
  - [ ] Add the means of immunization to the criteria used to identify potential duplicates, i.e. only detect duplicates if they have the same means of immunization
  - [ ] Add another option to the popup below the "Overwrite" option: "Create the new immunization anyway" - selecting it and clicking on Confirm creates the new immunization
  - [ ] Change the ordering of the `getSimilarImmunizations` method to order by creation date instead of change date
- [ ] Extend the duplicate detection mechanism when updating the start/end date of existing immunizations
  - [ ] Change the info text to "The system already contains at least one immunization for COVID-19 for this person and means of immunization that overlaps with the specified immunization period. Do you still want to update the start and end date or go back and adjust your changes?"
  - [ ] Change the caption of the "Okay" button to "Save changes" and change its behaviour to save the immunization
  - [ ] Add another button to the left of the "Save changes" button (styled like a Discard button), call it "Adjust changes" and use it to close the window (i.e. same behaviour as the current "Okay" button)
- [ ] Remove the label that asks the user to select a disease in the immunization directory, and instead directly display the immunization list not filtered by disease; this logic is also not necessary in the mobile app
- [ ] When the user changes the means of immunization to `RECOVERY` or `OTHER` and there is at least one vaccination in the vaccination list, show a popup with the following text: "Changing the means of immunization will delete all vaccinations that have been added to this immunization. Are you sure you want to proceed with the change?" and two buttons ("Confirm" and "Cancel")
  - [ ] Clicking on Confirm sets the field to the new value and removes all vaccinations from the vaccination list (i.e. when the user saves afterwards, the vaccinations get deleted, if they discard the form or don't save otherwise, they remain in the system)
  - [ ] Clicking on Cancel resets the means of immunization to the former value
- [ ] Change the logic that retrieves the immunization lists in the person, case, contact, and event participant forms to ignore the user filter, i.e. retrieve all relevant immunizations in the system irrespective of jurisdiction
