### ISSUE TITLE
Turn about-section into localized help-section [1]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4766]
### Feature Description

The about-section of Sormas should turned into a help-section, where beside the current informations also a link to the hand-book, trainings and the numbers/mails of the hotline is available.

### Problem Description

Currently the normal user did not know directly the numbers of the hotlines oder how the find the hand-book or training materials. Its very time-consuming for them to find this out.

### Proposed Change

Turn the about section into something similar to this:

![grafik](https://user-images.githubusercontent.com/74791118/111122275-1af39580-856e-11eb-90a3-b1fd0cc01163.png)

### Possible Alternatives

Leave it like it is.

### Additional Information

I know that this is very specific for every country, but maybe @Candice-Louw can give the input for Switzerland and someone else for other countries,

**Comment by MateStrysewske** [comment]
This looks like another use case for custom HTML content similar to what we already have for the login page.

**Comment by maxiheyner** [comment]
@Marko-ilmkreis and @MateStrysewske this would be really helpful for German SORMAS users. The current content and layout of the info section needs urgent improvement. Since our partners from ÖGD provided lots of helpful and freshly updated documents like handbooks, manuals on server configurations and an e-learning courses, all this material should be provided directly in SORMAS, too.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske @maxiheyner @Candice-Louw @kwa20 The local health offices in Germany are not able to customize the login page (which would be nice) as the complete server is managed by ITZ-Bund and Netzlink. There is no way to access the relevant files, which also means that the new help section must be provided centrally either by Netzlink for all instances or (what I prefer) from Sormas for all instances by the locale-settings.

**Comment by carolinverset** [comment]
@Marko-ilmkreis @bernardsilenou @ftavin @emond-fuseau
In France, we also think that it would be very relevant to make this part configurable in order to allow each server administrator to upload important documents for users in each country, region, local health offices, ... 
We have a GPDR theme in France and would like to allow users to download a document informing them of their rights in terms of the use of their personal data.

**Comment by bernardsilenou** [comment]
This issue seam to be very important to the community. 
@ftavin @carolinverset  We can discuss it tomorrow.

**Comment by Candice-Louw** [comment]
@bernardsilenou @carolinverset - a temporary workaround that you could perhaps consider for uploading of documents on the About page is described here: https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Customizing-the-Login-and-About-Pages#about-page

It has not been done on any DE or CH servers yet, so please do share a screenshot or two with us if you decide to give it a try on your servers, please. :)

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - is https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Customizing-the-Login-and-About-Pages#custom-help-and-info-section the description on how to do this?

**Comment by DavidBaldsiefen** [comment]
@Candice-Louw From 1.62 on, yes. In 1.61, only the custom documents are implemented

**Comment by Candice-Louw** [comment]
Great, thank you!

**Comment by DavidBaldsiefen** [comment]
Review finding: Increase spacing between columns and width of each column
