### ISSUE TITLE
Always show extended classification fields if multi classification is enabled

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4901]
### Bug Description
The confirmation fields are only enabled when confirmed is selected in covid cases
### Steps to Reproduce
1. Open or create a covid case
2. check for confirmation fields
3. select confirmed in the case classification

### Expected Behavior
The separated confirmation fields should always be available, at least for Covid cases or german servers since different combinations of such fields also determine other case classifications. 
### Screenshots
<img width="442" alt="caseClassificationMissing" src="https://user-images.githubusercontent.com/70317594/112660117-61da6880-8e55-11eb-89d4-782a596d9145.PNG">
<img width="449" alt="caseClassificationMissing2" src="https://user-images.githubusercontent.com/70317594/112660124-63a42c00-8e55-11eb-8225-ec63bb075a02.PNG">
<img width="436" alt="caseClassificationMissing3" src="https://user-images.githubusercontent.com/70317594/112660129-64d55900-8e55-11eb-882a-29f6c99b6ca7.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 I disagree that the fields should be displayed all the time because it doesn't really make any sense if the case is not classified, suspect or probable. I agree, however, that they should be displayed for the individual "Confirmed" classifications that we have in German systems.

**Comment by kwa20** [comment]
@MateStrysewske We use the classifications suspect and probable when either only a clinical confirmation or both, a clinical and epidemiological confirmation is present. Technically, a case can only be confirmed when a positive pathogen test, i.e. a laboratory confirmation is present. Otherwise, clinical and epidemiological confirmations are never certain.

I know that for measles this was requested in a different manner, but it's necessary for Covid at least and possibly other diseases as well.

@bernardsilenou could you give some more input on what is needed from the international side?

**Comment by bernardsilenou** [comment]
@MateStrysewske  @kwa20 
Epidemiological criteria != epidemiological confirmation case classification,  we deduce the case classification form the criteria.
This would very much depend if these variables means that the epidemiological (or clinically) criteria is valid for the case OR if the case was confirmed by  epidemiological (or clinically) basis. If it is about the criteria, then Kays suggest is better but if is about the classification, then the current is better.
From our case definition of a suspected case, we already included the clinical criteria (symptoms) and epidemiological criteria (travel, contact, exposures, ...) in the case definition. Similar to measles, these 3 extended classifications were added to determined the basis for classification  rather than the criteria.

From @kwa20 comment  it shows that these variables are used in terms of a CRITERIA ,

@kwa20 Please can you look in to the definitions of these variables in Survnet + case definitions + case classifications.

This is a very sensitive topic and suggest we hear from others before deciding.
Nothing is certain, event a lab test. In some circumstances you can confirm clinically and it can be as sensitive as the lab. But this depends on the disease and the Artz. In a large outbreak, it can be impossible to confirm all cases by lab.
[WHO-2019-nCoV-Surveillance_Case_Definition-2020.2-eng (1).pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6215017/WHO-2019-nCoV-Surveillance_Case_Definition-2020.2-eng.1.pdf)

**Comment by bernardsilenou** [comment]
I just had a quick look at RKI and think Kay is correct, 
They are criteria not extended case classification categories of a confirmed case as in measles.
In this case, they do not apply to confirmed cases only.
[Falldefinition.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6215065/Falldefinition.pdf)

What we can do is:
- Rename them to lab, clinical, epi criteria and show on form always 
- Disconnect the extended case classification from the criteria. Just maintain this as its own variable
- Add extended case classification a new variable in export and db

**Comment by kwa20** [comment]
@bernardsilenou Exactly, for the purposes they were initially implemented for they were fine as they were, I think there was just a different requirement for measles which involves the same terms but a different use case. Thus, the misunderstanding.

**Comment by MateStrysewske** [comment]
@kwa20 @bernardsilenou Can you please summarise what the final solution is that works for both Measles and Covid-19 (and all other diseases where users might turn on extended classification)?

**Comment by JaquM** [comment]
@MateStrysewske 
In summary:

- Disconnect the extended case classification from the criteria. 
- Maintain this as its own variable 
- Rename them to lab, clinical, epi criteria and show on form always

@bernardsilenou I think the export is not a bug fix, so should be added in a new Issue.

**Comment by MateStrysewske** [comment]
@JaquM I don't really get the first two points

**Comment by kwa20** [comment]
@MateStrysewske @JaquM @bernardsilenou Since the multi confirmation fields were good as they were and cover another use case, revert them back to their original state. We could do this in the following way:

**Backend/API**
- change extendedClassificationMulti to be classificationCriteriaMulti
- change defaultExtendedClassificationMulti to be defaultClassificationCriteriaMulti - true for CORONAVIRUS
- (migration might also need to happen)

**UI**
- Move the classificationCriteria fields above the case classification
- Disentangle the fields from the case classification field
- When the configuration for classificationCriteria in the db is set to true, show them always
- if extendedClassification is enabled for a disease, show the single drop down extended classification field when CONFIRMED was selected in caseClassification

**Comment by MateStrysewske** [comment]
@kwa20 Okay, that would require a bigger change and some more thoughts. I'd suggest for now that we keep everything like it is, but show the extended classification dropdowns (when multi is true) independent of the case classification, but leave it tied to confirmed cases when multi is false.

**Comment by kwa20** [comment]
@MateStrysewske Would that mean that on the UI, the fields would only seem to be repositioned for the users? If so, I guess this would work until it's fully fixed.

**Comment by MateStrysewske** [comment]
@kwa20 They actually wouldn't be repositioned, I'd only fix the problem that they're only visible for confirmed cases for now.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the last version of sormas 1.59.0-snapshot on local environment
