### ISSUE TITLE
reselecting a country in exposures does not auto-refill continent and subcontinent fields

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4904]
### Bug Description
When a country is changed in exposures, associated continent and subcontinent fields do not get automatically refilled with the associated infrastructure data.
### Steps to Reproduce
1. Enter or edit an exposure
2. Select a country and let continents and subcontinents autofill
3. change the country to one on a different continent

### Expected Behavior
continent and subcontinent fields should refill according to the selected country, even if they have previously been entered.
### Screenshots
initial selection:

<img width="379" alt="autofillConSubcon" src="https://user-images.githubusercontent.com/70317594/112662523-12e20280-8e58-11eb-9488-cdeadeff8b9c.PNG">

change:

<img width="392" alt="reselectingCountry" src="https://user-images.githubusercontent.com/70317594/112662536-16758980-8e58-11eb-94e6-d49e049a4d20.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
To clarify: This happens when a country is directly selected without selecting a continent or subcontinent first. In this case, the list of countries is not filtered according to the now selected continent. The expected behaviour would be to make sure that the country list is filtered accordingly (so that it's not possible to select a country from a different continent/subcontinent in the first place).

**Comment by bernardsilenou** [comment]
@Candice-Louw @kwa20 What does the continent option: Foreign Countries (Unknown) mean pls? Its confusing since this variable is about continent, can we use just Unknown?
Since we have unknown as an option for continent, then it would be good to add for  sub continent and country also, No validation with other fields are needed for unknown. If not then we can remove the unknown from continent.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot on local environment.
The android part will be verified tomorrow using test-de.sormas.netzlink.com
