### ISSUE TITLE
[Angular] Case Therapy tab [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4951]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes

### Feature Description
Design: 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/D131F560-81B3-463F-B335-3B2C2BDB0938

-NOTE:  Implement the component (without the edit / delete functionality)
- If we have more than 8 items, display the "Show more" action. Whenever we click on show more we will display the next  X items

### **DEPENDENT ON: [Angular] Cards component #4972**

@MateStrysewske , when clicking on "Show more" do we display the next 8 items (as on the first page), or all of the remaining items (regardless of their number) ? How many items can there be ? ('10s, '100s) - We will be showing all of the remaining items (regardless of the number) - confirmed by @cristinacoza .

### Possible Alternatives
N/A

### Additional Information
N/A

### Story Points: 3 POINTS

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup I would probably go with showing all remaining items (because it could be very, very annoying to be forced to click multiple times if you want to see one of the earliest entries). I can't really say how many entries we can expect to be in these lists - very likely not 100s of items, but that really depends on how exactly SORMAS is used in the respective country.

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
