### ISSUE TITLE
[Angular][Backend] Case Save "Patching" method [8]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4956]
### Situation Description
Based on the discussion had on: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4615 together with the team, it was concluded that we should implement a patching system for when saving a case (save only the updated items and not all of the case fields).

### Feature Description
- Enable "patching" for when saving a case.
- We should only save the updated fields
- Supply an end-point for the patching which should be available for the FE (angular).

### Possible Alternatives
- If there is no development time, or developer availability we can leave the "save" functionality as is.

### Additional Information
N/A

**ESTIMATION: 8 POINTS**

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup I think it would be worth doing this even if it would delay development in other places a bit because we're getting more and more requests for a POST functionality (which would require this exact patching logic), so this would benefit both the Angular app as well as SORMAS in its current state. We can set up a meeting concerning how implementation should look like in the backend if you want to (or, if you already have a specific implementation in mind, discuss your ideas). :)
