### ISSUE TITLE
Database 1.58.1 > Generate new Schematic (SchemaSpy)

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4960]
### Request
With each SORMAS version, new database fields are introduced.  It would be helpful for all users of SORMAS, technical and non-technical to be given the opportunity to view the new DB structure, relationships between tables, and adjust external/internal tools/analysis appropriately.  This information contributes to understanding SORMAS and delivering up to date, quality documentation to enhance user acceptance and understanding of the system.

### Details
Please generate a new schematic to share with DE and CH users of the 1.58.1 database scheme as done here: https://github.com/hzi-braunschweig/SORMAS-Glossary#schemaspy The output would be a .zip file.  Please upload the generated .zip file: https://drive.google.com/drive/folders/1W18Z0YdB4pY0CQ9Onanx5S30WXusi87k?usp=sharing It will then be shared from there through appropriate channels to those requesting it.

### Alternatives
Documentation on using PGAdmin or another tool documented/explained and published on GitHub so that all interested parties may be referred there to do this after each release/when convenient themselves. @GD-ZH

**Comment by Candice-Louw** [comment]
@marko-ilmkreis - do you have an alternative approach/suggestion to this by any chance, please?

**Comment by Marko-ilmkreis** [comment]
@Candice-Louw This would be very good to make the dependencies more visual for the users. I think it could be very helpful to have this.

**Comment by AxelNennker** [comment]
I don't subscribe to this view "It is important for all users of SORMAS, technical and non-technical to be given the opportunity to view the new DB structure, relationships between tables, and adjust external/internal tools/analysis appropriately."

Especially non-technical users usually don't understand DB schematics.
I would also question the word "important".

If a "normal" - what ever that is - user has to view the database tables and the relationships then there is probably something wrong with the Sormas user flow and tutorials.

I think that database schemas are more relevant for developers.

So, I would say, having the schematics prepared is a good thing and generating them does not cost us much when a new version is deployed.

Thinking about deployment, if the schematic did not change then switching Sormas versions should be easy because the DB stays the same. If the schematics changed then a DB migration is probably needed. Maybe there is potential to automate migrations guides and release documentation. That's a different topic.

**Comment by JonasCir** [comment]
done :tada:
