### ISSUE TITLE
Refine the update mechanism between case outcome and person death date [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4964]
### Bug Description
This is a continuation of #4248
-  When outcome == death, date of date of outcome is set to current date and present condition of person is set to death and date of death == current date.  This make up data that may not be real. 
### Steps to Reproduce
1. creat a case
2. set the outcome to death and provide no date of outcome
3. save and check the case and case person

### Expected Behavior
How logic should work:

Validation between outcome of case and present condition of person should be activated only if (outcome = diseased) AND (present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case)
If outcome of a case == death or buried then set present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case. If date of outcome is know, then assign it to date of death of person. You can override previous data.
if present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case, then set outcome = diseased. If date of death in not null, then assign it to date of outcome.
else do not validate outcome or date of outcome with present condition of person.

- If there are multiple cases of the same disease linked to the person, then this should apply only to the most recent case based on report date
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Development Specifications (Confirmed 11-6-2021)
Refine the logic that is responsible for updating the case outcome / present condition of the associated person as follows. Most of that logic will already work this way, but something seems off.
* Do not set the `outcomeDate` automatically to the current date anymore
* If `caseOutcome` is updated to `DECEASED`, always update `presentCondition` of the person to `DEAD`, set `deathDate` to the `outcomeDate` of the case, `causeOfDeath` to `EPIDEMIC_DISEASE` and `causeOfDeathDisease` to the disease of the case.
* If the `caseOutcome` of a case is later changed to `RECOVERED` or `NO_OUTCOME` again, change the `presentCondition` of the person back to `ALIVE` (and clear all fields that depend on it) ONLY if:
    * there is NO other case associated with this person in the system with outcome `DECEASED`
    * the `causeOfDeath` is filled in and set to `EPIDEMIC_DISEASE`
    * the `causeOfDeathDisease` matches the disease of the case
    * the `deathDate` is within the threshold of the `reportDate` according to the formula below
* If `presentCondition` is updated to `DEAD` or `BURIED` AND there is a `deathDate` AND the `causeOfDeath` is set to `EPIDEMIC_DISEASE` AND `causeOfDeathDisease` is filled in, check if there is a case within the time threshold defined below (only retrieve the newest case with this condition) with `caseOutcome` != `DECEASED` - if there is one, set `caseOutcome` of that case to `DECEASED` and `outcomeDate` to the `deathDate` of the person
* Time threshold used for the calculations: `reportDate <= (deathDate + 30 days) && reportDate >= (deathDate - 30 days)`
* If a persons condition is changed back to alive:
   * Take the latest case, and if it is deceased change the value back to "No Outcome Yet" and set the outcomeDate to null, IF the case disease equals the old `causeOfDeathDisease`
* If only the `outcomeDate` of a deceased case is changed:
   * ONLY update the death date of the person if `outcomeDate != null && causeOfDeath==EPIDEMIC_DISEASE && causeOfDeathDisease=CaseDisease`
* If only the `deathDate` of a dead Person is changed;
   * ONLY update the `outcomeDate` of the most recent case if ` deathDatea != NULL && causeOfDeath==EPIDEMIC_DISEASE && causeOfDeathDisease=CaseDisease`
* Add unit tests for all of the above

**Comment by MateStrysewske** [comment]
@bernardsilenou I've updated the initial post with development specifications. Can you confirm that what I wrote there matches your expectations?

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou :)

**Comment by bernardsilenou** [comment]
@MateStrysewske Sorry I missed it. I would do it now

**Comment by bernardsilenou** [comment]
@MateStrysewske I would prefer to comment here and you can then add the once you agree in the main summary above.

> ### Development Specifications
> Refine the logic that is responsible for updating the case outcome / present condition of the associated person as follows. Most of that logic will already work this way, but something seems off.
> 
> * If `caseOutcome` is updated to `DECEASED`, always update `presentCondition` of the person to `DEAD`, set `deathDate` to the `outcomeDate` of the case (only overwrite this if an `outcomeDate` has been provided!), `causeOfDeath` to `EPIDEMIC_DISEASE` and `causeOfDeathDisease` to the disease of the case.

Perfect
> * If the `caseOutcome` of a case is later changed to something else again, DON'T update the `presentCondition` of the person

A user can mistakenly set the outcome of the case to  `DECEASED` and latter set it to the known right category  `RECOVERED` or `NO_OUTCOME`, In this case, we can update the `presentCondition` accordingly (ALIVE if  caseOutcome is `RECOVERD`or `NO_OUTCOME`), conditioned on the fact that there is NO OTHER CASE OF ANY DISEASE linked to the person with `caseOutcome` set to  `DECEASED` and `reportDate` and `outcomeDate` are true for the condition below: ie `reportDate < (deathDate + 30 days)  & reportDate >= (deathDate - 30 days)`

> * If `presentCondition` is updated to `DEAD` or `BURIED` AND there is a `deathDate` AND the `causeOfDeath` is set to `EPIDEMIC_DISEASE` AND `causeOfDeathDisease` is filled in, check if there is a case with `reportDate < deathDate & reportDate >= (deathDate - 30 days)` (only retrieve the newest case with this condition) with `caseOutcome` != `DECEASED` - if there is one, set `caseOutcome` of that case to `DECEASED` and `outcomeDate` to the `deathDate` of the person

Since there can be instances that we have the outcome before the case is reported, it would be good to add the delay to both end of the time interval. ie 
`reportDate < (deathDate + 30 days)  & reportDate >= (deathDate - 30 days)`

**Comment by MateStrysewske** [comment]
@bernardsilenou Thanks! Updated the specifications.

**Comment by DavidBaldsiefen** [comment]
> set deathDate to the outcomeDate of the case (only overwrite this if an outcomeDate has been provided!)

So if `outcomeDate` is not manually set, thus being automatically set to the current date upon saving the case, should the persons deathDate _not_ be set? @MateStrysewske

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen I'd say so, yes. Maybe we should actually think about not automatically setting the outcome date to the current date at all. @bernardsilenou What do you think?

Concerning your second point - because only one case can be responsible for the death of the person. If the person had previous cases of the same disease, those couldn't have lead to their death (since they apparently recovered and became sick again afterwards).

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske Thanks! Is the most recent case determined based on the report date?

**Comment by DavidBaldsiefen** [comment]
There is another part of logic we need to discuss:

What should happen, when just a case `outcomeDate` or persons `deathDate` is changed (but the outcome is still `DECEASED` and the person still `dead/buried`)

My suggestion would be the following:

If a cases `outcomedate` was changed:

- If `outcomeDate==null`, use deathdate
- else use the `outcomeDate`, and set the persons `deathDate` to the same value

On the PersonFacade we would need a similar logic, that gets activated whenever the persons `deathdate` gets changed:

- If `deathDate==null`, use `outcomeDate` of most recent case
- else use the `deathDate`, and set the cases `outcomeDate` to the same value


@bernardsilenou please confirm :)

**Comment by MateStrysewske** [comment]
1) I think that's some kind of automation that we can't do because these changes could in fact be wrong, or they would specifically overwrite user input. If we do this, we need additional validation for it. My recommendation:

* When the outcome date of a case is changed, ONLY update the death date of the person if the old outcome date of the case equals the current death date of the person - else leave it untouched
* When the death date of a person is changed, ONLY update the outcome date of the most recent case (with outcome date <= old person death date) if the outcome date matches the old death date of the person - else leave it untouched
* Setting the outcome or death date to null explicitely should NOT update the other date again because we have to assume that the user cleared those fields on purpose and wants them to stay empty. I heavily recommend to not fill these fields again. Alternatively:
  * When setting the outcome date of a case to null, ONLY use the death date of the person if `(case start date - 30) <= death date <= (case start date + 30)
  * When setting the death date of a person to null, ONLY use the outcome date of the most recent case (with outcome date <= old person death date) if the old death date equals that case's outcome date

2) I agree with this change, with the restriction that this may only happen if causeOfDeathDisease before the change = disease of that case

@bernardsilenou your feedback would be necessary here

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou can you comment on the following questions? They are a summary of the questions above:


1. If `outcomeDate` is not manually set, thus being automatically set to the current date upon saving the case, should the persons `deathDate` not be set? In this regard: Should we just completely disable automatically setting the `outcomeDate` or force manual Input by the user on this field?

2. What should happen if only the `deathdate` / `outcomedate` changes, but not the actual outcome or condition? Maté suggested this: 

- When the outcome date of a case is changed, ONLY update the death date of the person if the old outcome date of the case equals the current death date of the person - else leave it untouched
- When the death date of a person is changed, ONLY update the outcome date of the most recent case (with outcome date <= old person death date) if the outcome date matches the old death date of the person - else leave it untouched
- Setting the outcome or death date to `null` explicitly should NOT update the other date again because we have to assume that the user cleared those fields on purpose and wants them to stay empty

3. What should happen if a persons condition is changed back to alive? Suggestion: Take the latest case, and if it is deceased change the value back to "No Outcome Yet" and set the `outcomeDate` to `null`, IF the case disease equals the old `causeOfDeathDisease`

**Comment by bernardsilenou** [comment]
@MateStrysewske  @DavidBaldsiefen  
Yes please, we should not automatically set the outcome date to current date. If user does not provide the outcome date or date of death (person), then we keep it as NA.

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen @MateStrysewske  Sorry to respond late. Suggestion below:

> @bernardsilenou can you comment on the following questions? They are a summary of the questions above:
> 
> 1. If `outcomeDate` is not manually set, thus being automatically set to the current date upon saving the case, should the persons `deathDate` not be set? In this regard: Should we just completely disable automatically setting the `outcomeDate` or force manual Input by the user on this field?

Suggest we should not automatically fill outcome date upon saving. If user provide outcome date and outcome == deceased, then we use the same for death date and vice versa. The reason is that in case of retrospective data entry, outcome date for cases with missing outcome date are set to current date which may result in false records. It is better to have NA than false value.

> 2. What should happen if only the `deathdate` / `outcomedate` changes, but not the actual outcome or condition? Maté suggested this:
> 
> * When the outcome date of a case is changed, ONLY update the death date of the person if the old outcome date of the case equals the current death date of the person - else leave it untouched

 When the outcome date of a case is changed, ONLY update the death date of the person if the conditions hold, is cause of death == epidemic disease and responsible disease == disease of case, condition that the outcome == deceased. Since a person can not die on a date after the deceased outcome date, then it may be necessary to only check that the condition linking the cause of death is the case.

> * When the death date of a person is changed, ONLY update the outcome date of the most recent case (with outcome date <= old person death date) if the outcome date matches the old death date of the person - else leave it untouched  :+1: 

This is a difficult one. Since we only take the most recent case of the person based on most relevant date, then we can use the  condition: `with outcome date != old person death date` Since a person can only die once, if condition linking cause of death and disease of case is satisfied, then we should always update the outcome date of the most recent case.


> * Setting the outcome or death date to `null` explicitly should NOT update the other date again because we have to assume that the user cleared those fields on purpose and wants them to stay empty  :+1: 
> 
> 1. What should happen if a persons condition is changed back to alive? Suggestion: Take the latest case, and if it is deceased change the value back to "No Outcome Yet" and set the `outcomeDate` to `null`, IF the case disease equals the old `causeOfDeathDisease`   :+1:

**Comment by bernardsilenou** [comment]
In summary:
- If the condition linking case outcome and cause of death is satisfied, then we always match the latest cases' outcome and date of outcome to that of the present condition of the person.
- If a person is sick of covid in January, recovered and later got sick again of covid in December and die as a result of the case in December. The we would only update the outcome  of the case in Dec to death while the case in January remain as recovered. This is the reason whey we take only latest case I suppose.

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou 
I have updated the developer specifications again, please confirm :)

@kwa20 FYI

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou bump :)

**Comment by RazvanHodisan** [comment]
Verified on test.sormas, Version: 1.62.0-SNAPSHOT
