### ISSUE TITLE
Persons > Error displayed instead of list of Persons

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4986]
### Bug Description
Persons Directory is not displaying values, but displays error message (CH configured server).

### Steps to Reproduce
1. Open Persons Directory
2. Error message appears

### Expected Behavior
No error

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/113318184-7ebce300-9310-11eb-92db-4c8b4115168d.png)

### System Details
* Device: PC
* SORMAS version: 1.58.2
* Android version/Browser: Chrome
* Server URL: https://stable-release-ch.sormas.netzlink.com/
* User Role: admin, National User, National Clinician

**Comment by kwa20** [comment]
@Candice-Louw  Can you check if there are multiple primary contact details for one contact type (e.g. email)?

**Comment by kwa20** [comment]
@Candice-Louw I found this contact person on that system. The problem occurred because two email contact details were labeled as primary which should not be possible. The person directory displays the primary email address and can gets an error because it cannot decide between the two primary options.

<img width="467" alt="multiplePrimaryEmails" src="https://user-images.githubusercontent.com/70317594/113327309-19baba80-931b-11eb-9ba2-4ee2a3b2f13f.PNG">

 I think that this entry might've carried over from the 1.58.0 version before multiple primary options were fixed. However, it could also relate to PIA because this also happened on release-de.sormas.netzlink.com and PIA is configured on both instances
