### ISSUE TITLE
Cases & Contacts > Bulk mode for linking/adding to Events [3]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4991]
### Situation Description

As an outbreak management team, I would like to use events to group related cases/contacts and to optimally accompany and support affected facilities in on-site outbreak management. An important part of this work is to link the people affected by an outbreak (via cases and via contacts) with the corresponding event.

So that not only the person, but also the corresponding case or contact is correctly linked to the event, must

the case mask or contact mask for each individual case or contact is opened,
clicked on the button "+ link event",
the event to be linked can be searched for and selected.
This procedure means a very high expenditure of time for the employees.
Linking the case to the event is important because the MA in outbreak management depends on the information while working on the phone.

If event participants are linked directly to the event with the "+ Add event participant" button, only the person is linked, but not the case or the contact. If you then click on "Create" in the "Case ID" column, a completely new case will be created for the linked person.

![image](https://user-images.githubusercontent.com/9933294/110965326-5ca8f400-8354-11eb-96fb-f3a13974e4da.png)

The case register can be used to search for cases that are assigned to a specific facility.
![image](https://user-images.githubusercontent.com/9933294/110967098-4dc34100-8356-11eb-94b6-ffa3399aa1d4.png)

At the top right under "MORE" you can switch on the bulk processing mode, select all cases and on the right above the case table under "Bulk processing" select the option "Edit". In the pop-up window that opens, it is not possible to link all selected cases to an event.

![image](https://user-images.githubusercontent.com/9933294/110967390-9a0e8100-8356-11eb-99fb-cb6ea9a902f3.png)

Analogous to contacts:
![image](https://user-images.githubusercontent.com/9933294/110967517-c1654e00-8356-11eb-8ef1-75825d90c443.png)

### Feature Description
In these pop-up windows, an option to link the selected cases or contacts to an event would be very helpful. Components: "Link event" tick box, search field to find the event, option to select the desired event.

### Development Specifications
* Add a new element to the bulk edit dropdown for cases: "Link cases to an event"
* If clicked, bring up a popup that is identical to the popup opened when clicking on "link event" inside a single case (only exception: the info text should read "selected cases" instead of "current case" and "these cases belong to" instead of "this case belongs to")
* Don't show the "create event participant" popup that opens after the user has selected/created an event
* If a case is already linked to the event (i.e. it's the resulting case of an event participant in the event), skip it; if the case person is part of the event as an event participant WITHOUT a resulting case, update the resulting case of the event participant
* If cases with multiple diseases are selected, don't open the popup and instead display a warning notification: "You can't link cases with different diseases to the same event. Please only select cases of the same disease."
* Hide the new option when the `EVENT_SURVEILLANCE` feature is turned off

**Comment by michadavid** [comment]
Thank you very much @Candice-Louw!

**Comment by kwa20** [comment]
@Candice-Louw I'd suggest to make this a separate bulk action besides "... edit" and show the same window upon selecting "link event" that usually appears when using it inside entities.

**Comment by bernardsilenou** [comment]
@Candice-Louw Thankd for the issue.
I have a comment on this statement:
`If event participants are linked directly to the event with the "+ Add event participant" button, only the person is linked, but not the case or the contact`. == Correct, this should create an event part entity only and link it to the event and the person.

`If you then click on "Create" in the "Case ID" column, a completely new case will be created for the linked person.` == This is right, at this point, you link the event part entity created in the point  above to the resulting case.

Cases are not directly linked to events but they are indirectly linked to events through the event participant.

Was this suppose to work differently?

**Comment by kwa20** [comment]
@markusmann-vg @Candice-Louw The Development Specifications that @MateStrysewske already added cover the cases. These would also apply similarly for contacts with only minor differences I suppose:

- Add a new element to the bulk edit popup for contacts: "Link **contacts** to an event"
- Show a hint below the checkbox: "All **selected contacts** will be linked to the selected event if they are not linked to it already"
- If checked, enable a "Search event" button and an involvement description text field; clicking on the "Search event" button brings up a popup that is identical to the popup opened when clicking on "link event" inside a single contact (only exception: the info text should read "**selected contacts**" instead of "**current contact**" and "**these contacts belong to**" instead of "**this contact belongs to**")
- Don't show the "create event participant" popup that opens after the user has selected/created an event
- If a contact is already linked to the event, skip it; if the contact person is part of the event as an event participant WITHOUT a **linked contact**, update the **contact links** of the event participant
- If contacts with multiple diseases are selected, display a warning at the top of the bulk edit popup: "You have selected **contacts** with different diseases. Some bulk edit options might be unavailable."; disable the new option if this is the case
- Hide the new option when the EVENT_SURVEILLANCE feature is turned off

**Comment by StefanKock** [comment]
No ticket progress since weeks.

**Comment by StefanKock** [comment]
Removed ticket assignee (not working on this ticket anymore) and removed it from the Sprint Backlog since it was moved to Sprint 107 in the Product Backlog

**Comment by michadavid** [comment]
So what is happening regarding this issue?

**Comment by Candice-Louw** [comment]
@michadavid - planned for 107/1.64 release.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  SORMAS: 1.63.0-SNAPSHOT on local environment
