### ISSUE TITLE
Changing the handling of facilities

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5001]
### Feature Description

Currently you have to know which category you find the facility. You have also to know the excact name as the names are sorted and the field is not searchable. So if the name  would "Sonnenschein Kindertagesstätte" or "Kindertagesstätte Sonnenschein",  ideally you enter "Sonnenschein" in the field and it gives you all facilities containing this word. If you select the facility the category is automatically filled.

### Problem Description

The users struggeling at the beginning about finding a facility. E.g. an retirement home is under residence, a elderly day care unter caring facilities and so on. It is on the second view very clear why it is like this and its also clear that this comes from SurveNet (?) as well. But on the first view its very complicated for the users.

**Comment by bernardsilenou** [comment]
- I think this is a valid need because users do not remember the the grouping of facilities in practice and changing the grouping would not help also.
- Suggest we add a global search for all repositories based on facility name.  
name similarity would be called an any entity with associated facility is the system with similar name would be suggested on the repository.
- We can even extend the global search based on any of the variables in the detailed view of the repository, similar to what  is presented here https://datatables.net/

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou That datatables looks very help- and useful.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis its the same we used in sormas-stats, I am not sure it can work well for a table with many records like our directories. We may need to investigate further or build something similar.

**Comment by kwa20** [comment]
@Marko-ilmkreis @bernardsilenou This might be the same or a similar request as mentioned in #4843 and might compliment each other.

**Comment by bernardsilenou** [comment]
@kwa20 
This is very similar to #4843 .  Following https://github.com/hzi-braunschweig/SORMAS-Project/issues/5001#issuecomment-814413737 I think adding a global search field would address the both needs.
I would then close this one an migrate the comment to #4843
