### ISSUE TITLE
Translation is missing for tranferred general practitioner

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5004]
### Bug Description

In the current version the field of general practitioner was transferred into the new contact, but in Germany the translation for it is missing and confusing the non-english-speaking user:

![grafik](https://user-images.githubusercontent.com/74791118/113815792-0c1a9000-9774-11eb-8ee4-90862c3e3fe2.png)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Unfortunately there's nothing we can do about that. When we migrated the old contact details into the new system (that allows users to specify multiple contact details), we had to create a new contact detail for every person where the general practitioner field was filled in. However, because we have no way of knowing which language a server is using while doing this in SQL, we had to go with a default approach here, and that default approach was to write "General practitioner" into the "Owner name" field.

You may contact Netzlink and ask them to update all contact details where owner name = "General practitioner" and change the owner name to the correct term (so "Hausarzt" I guess) - they should be able to do that on all German systems managed by them.
