### ISSUE TITLE
Re-add primary phone number and primary email address to import templates [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5011]
### Bug Description
personContactDetails cannot be imported since respective columns are missing in the templates. The table is also missing in the data dictionary.
### Steps to Reproduce
1. Download an import template (e.g. for cases)
2. Check columns for person contact details

### Expected Behavior
personContactDetails should be able to be imported. The personContactDetails table should also be displayed in the data dictionary.
### Screenshots
<img width="549" alt="personContactDetails" src="https://user-images.githubusercontent.com/70317594/113855307-2d917100-97a0-11eb-86d4-6874efcb70da.PNG">
### System Details
* Device:
* SORMAS version: 1.58.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Development Specifications
* Add primary phone number and primary email address to the person sections of import templates for cases, contacts and event participants
* During the import, when these are not empty, use the helper methods in PersonDto (setEmailAddress and setPhoneNumber) to automatically create contact details when the person is saved
* Align with the export

**Comment by cazacmarin** [comment]
Additional information for QA:
3 templates has been modified: 
1. sormas_import_case_template.csv 
2. sormas_import_contact_template.csv
3. sormas_import_eventparticipant_template.csv

Attached are 3 files which are working if we will import all of them with admin user:
[3-templates-populated-with-data-for-import.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6428906/3-templates-populated-with-data-for-import.zip)

Note(in order to upload an event participant, is needed to open an event, navigate to EVENT PARTICIPANT tab, and from here to upload attached populated `sormas_import_eventparticipant_template.csv` file with admin user.
