### ISSUE TITLE
Setting caseOutcome to DECEASED continuously produces very large logs 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5099]
### Bug Description
It occurred that setting caseOutcome to DECEASED produces very large log files (gb/min) and results in the server having to be restarted.

Thus far, we could only reproduce this by bulk editing cases and setting them to DECEASED, however, we suspect that this also can be reproduced with individual cases since it was reported by users on productive systems.

### Steps to Reproduce

1. Enter the bulk mode and select many cases
2. Edit all of them and set the caseOutcome to DECEASED
3. Set it for individual cases (exact reproduction steps still have to be identified)

### Expected Behavior
Error should result in an error message. Logs should only be written once when an error occurs and don't loop.
### System Details

* Device:
* SORMAS version: 1.58
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
This error message seems to occur very often:

[stackoverflowerror.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6317948/stackoverflowerror.txt)

@nliakm

**Comment by DavidBaldsiefen** [comment]
I could not reproduce this locally when bulk editing 300 cases (nothing appeared in my logs). 
According to the logs, the problem occurs somewhere in 
`CaseFacadeEjb.onCaseChanged` -> `CaseFacadeEjb.updatePersonAndCaseByOutcome` -> `PersonFacadeEjb.onPersonChanged`

If this issue is very urgent it would probably help to just put a `try{}...catch(StackOverflowError ex){}` around those parts. However, that would be quite bad practice as it just covers up the problem instead of solving it

**Comment by MateStrysewske** [comment]
@kwa20 Could you please try to reliably reproduce this with an individual case on that test system? My initial suspicion was that there might be an infinite loop between setting the case outcome and the person death details (and so on and so on) under specific circumstances, but those circumstances aren't really clear to us (if that's the reason anyway).

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske 

I think I found it, this happens when one person has multiple cases, and both cases are being changed to DECEASED using bulk actions. The infinite loop then gets started in `PersonFacadeEjb.onPersonChanged` on the second call of `onCaseChanged`

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Great, thanks for finding out!

**Comment by DavidBaldsiefen** [comment]
The problem was the following:

1. The first case was set to DECEASED
2. This causes the case-person to be also set to dead, and a corresponding `deathdate` being set
3. This caused all the persons cases to be set to DECEASED with new `outcomeddates` too. However, these new outcomedates were newly generated and thus a few milliseconds different from the `deathdate`
4. Now the second case is evaluated. There is no longer any difference between the new and "old" outcome, as the "old" outcome was changed in step 3
5. This caused the code to go to an `else()` section, which would enter the infinite loop if the persons `deathdate` didn't equal the cases `outcomedate`

I will open a PR with a fix that should make the `deathdate` and `outcomedate` be equal from now on. If, for some reason, the issue still persists, one could consider using a tolerance when comparing the dates in `onCaseChanged`, like [here](https://github.com/hzi-braunschweig/SORMAS-Project/commit/b98503c6f527fedb6ce18f593c1bd92dc35696e5)


**For Testing:**

1. Create a person, and multiple cases for that person
2. Enter bulk action mode in the case directory and change the outcome of several of these persons to DECEASED

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the last version of Sormas 1.60.0-snapshot on local environment
