### ISSUE TITLE
[SurvNet Interface] Sending data to SurvNet with an inactive survnet user results in endless loading

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5153]
### Bug Description
When the SurvNet user was set to inactive, sending data results in endless loading. The system then had to be restarted.

### Steps to Reproduce

1. Go to users and set the survnet user to inactive
2. Send a case to the reporting tool

### Expected Behavior
The sending of data to survnet should either result in an error with a descriptive error message so users know what the problem is or the data should also be possible to be sent even if the user is set to inactive.

### System Details

* Device:
* SORMAS version: 1.58.3
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by vidi42** [comment]
It seems that in case the user is inactive the SurvNet converter not respond to SORMAS and will keep the connection open.
On the SORMAS side we added added a timeout of 60 seconds for this, after which an error will be displayed and not keep the user blocked with an endless loop.

![image](https://user-images.githubusercontent.com/3462897/115530903-e07fc580-a29c-11eb-8323-8543af009f5a.png)

In order to fully address the issue a SurvNet Converter ticket has to be opened as well which should require the converter to respond with a proper error message if it cannot connect back to SORMAS.

@kwa20 Can you open a ticket for the converter?

**Comment by AndyBakcsy-she** [comment]
verified ticket on test-de1.sormas environment on the latest version of sormas version 1.60.0-snapshot
