### ISSUE TITLE
Synchronisation after jurisdiction change

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#5184]
### Bug Description
Changing the case jurisdiction in mobile app fails synchronisation.

### Steps to Reproduce
1. Login if with SurvOff to mobile app 
2. Edit a case this user has access too and change the district.
3. Synchronise with server
4. Synchronisation of the case is successful but there is an error and sync log says :
![image](https://user-images.githubusercontent.com/8166805/115668043-462c8a00-a34f-11eb-8aef-2c03b290b753.png)

### Expected Behavior
There shouldn't be any error (discuss if user should not be able to update or sync process needs to be updated)
Case list on mobile app should no longer show that case (as web UI doesn't show it any more) - these should be consistent!

Note: this issue is most probably in place for other entities as well.

**Comment by MateStrysewske** [comment]
One note: The mobile app will drop the case, but not immediately. The app checks for any entities it no longer has access to once a day, and then removes these entities. Doing it more often would increase the traffic from the mobile app to the backend too much.

The general problem persists though. I'm not quite sure how to ideally solve that, but it indeed probably makes sense to just not update the sync log in this case. The question is how to do that technically. I don't think it necessarily has priority for this sprint though (because it's not a huge issue), so I'm gonna move it to the next one.

**Comment by StefanKock** [comment]
Do it as suggested here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5184#issuecomment-841190357

**Comment by BarnaBartha** [comment]
After retesting this with SurvOff user:
- changing the jurisdiction of case does not work because of a null-pointer : 
```
2021-08-17 07:55:31.727 8735-26174/de.symeda.sormas.app.debug E/de.symeda.sormas.app.caze.edit.CaseEditActivity$1: Error executing an async task
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long de.symeda.sormas.app.backend.common.AbstractDomainObject.getId()' on a null object reference
        at de.symeda.sormas.app.backend.user.UserDao.getByDistrictAndRole(UserDao.java:127)
        at de.symeda.sormas.app.backend.caze.CaseDao.onCaseChanged(CaseDao.java:486)
        at de.symeda.sormas.app.backend.caze.CaseDao.saveAndSnapshot(CaseDao.java:439)
        at de.symeda.sormas.app.caze.edit.CaseEditActivity$1.doInBackground(CaseEditActivity.java:280)
        at de.symeda.sormas.app.core.async.DefaultAsyncTask.doInBackground(DefaultAsyncTask.java:54)
        at de.symeda.sormas.app.core.async.DefaultAsyncTask.doInBackground(DefaultAsyncTask.java:29)
```
- changing the jurisdiction of contact does not work: You do not have sufficent permisssion to edit the record from this jurisdiction.
