### ISSUE TITLE
Automatic task for supervisors to define the outcome of a case when it is still missing [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#522]
We need to define what is a trigger for ther generation of this task.

**Comment by MateStrysewskeSym** [comment]
@dta16 Please specify the trigger for the generation of this task (e.g. how long after the end of the follow-up/incubation period the task should be generated and whether there are any other triggers).

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig See above

**Comment by bernardsilenou** [comment]
Since we can filter case listing by outcome, and in the real database, more than 80% of the cases have missing values for outcome, I suggest we should not create such a task reminder system. It will just end up creating a lot of task that the supervisors or who so ever is responsible will not be able to do. I suggest we keep this as low priority for now.
