### ISSUE TITLE
Introduce an internal token field [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5224]
### Situation Description
Thus far, entities already have external Id and external token fields. As the names suggest, these fields are used for external references and are therefore not optimal for internal use. This becomes even more apparent when these are needed to be used when implementing the reporting tool interface. Further, the uniqueness validation seems to be a hindrance for some as well, which is required for the interface.

### Feature Description

- To accommodate the users needs, introduce a free text field `internalToken` (Caption: Internal Token) for cases, contacts and persons. For events, rename internalId to internalToken (in the Android app, just rename the entity field, but keep the column name the same). This field should be placed underneath the external token.
- This field should be searchable on all respective directories (by including it into the already existing main search fields)
- Add respective sortable columns to the right of external Token on case, contact and event directory.

### Additional Information
<img width="254" alt="internalToken" src="https://user-images.githubusercontent.com/70317594/115915754-0c08d880-a474-11eb-8b44-e66aed8e5048.PNG">

**Comment by MateStrysewske** [comment]
@kwa20 What exactly is the purpose of this new field? How would users use it?

**Comment by kwa20** [comment]
@MateStrysewske Users are missing an option to have a field merely for internal purposes, especially when interfaces for reporting tools are now implemented and fields for external id and token have specific uses and validations. Thus far, users often used external id or token for varied purposes since interfaces have not been in use previously.

**Comment by MateStrysewske** [comment]
@kwa20 Any reason against using the UUID for such purposes?

**Comment by kwa20** [comment]
@MateStrysewske The uuid might not necessarily what they need. An example would be #5037

**Comment by MateStrysewske** [comment]
@kwa20 So it's basically more like a note where they put in... whatever? Because I feel like "Schnelltest Apotheke" as an example contradicts what a token/ID is supposed to be used for

**Comment by kwa20** [comment]
@MateStrysewske pretty much, technically it refers to a token because it adds to this whole section in the entities but the main objective is to have a field that can be used with as much freedom as possible. The comment field is not ideal for this because it accumulates too much information. It would also provide us with an option to potentially migrate entries in external id and token to this field if interface independent entries have been made in these fields previously. Something like "Schnelltest Apotheke" could also be handled by #5225 in the future. The important thing is that we don't use this field for anything else and leave the exact use up to the users desires.

**Comment by MateStrysewske** [comment]
@kwa20 We've talked about this issue internally and pretty much all agree that the meaning of this field will be relatively confusing to users who don't know what exactly it should be used for. Also the name "internal token" might be misleading because it's not about a SORMAS-internal funcationality, which is what the word "internal" hints at. Our fear is that especially international users will be confused by both the pure existence of the field as well as its name. Is this field supposed to be used for all countries or only Germany? If the former is true, I think the name might have to be revised.

**Comment by kwa20** [comment]
@MateStrysewske The need indeed occurred through german users but I believe that the field could potentially be used for all others as well. I wouldn't mind to implement it for germany only for now. I'm also open for naming revision if there are better suggestions. If this field becomes relevant for everyone later on we can always enable it accordingly.

**Comment by cazacmarin** [comment]
@MateStrysewske - please provide a better name for this field. So far, only discussed (might be another name) is missing. I will start to work on it by taking into consideration `internal token` - and in parallel, if a better name will be found, I will rename this field.

**Comment by kwa20** [comment]
@cazacmarin @MateStrysewske I think 'custom token' could be an alternative considering the function of this field. If we make it available for everyone later on, however, we could always adjust it then.

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of sormas 1.61.0-snapshot on test-de1.sormas.netzlink.com environment

**Comment by kwa20** [comment]
@AndyBakcsy-she @cazacmarin I tested on test-de.sormas.netzlink.com but found the following problems:

1) internalToken is not searchable on directories
2) internalToken does not seem to be able to be saved for contacts

Steps to reproduce 2):
- Open or create a contact.
- Enter the internal Token and save. 
- Check the internal Token field.
- Refresh page and check again.

**Comment by MateStrysewske** [comment]
@cazacmarin Please check the functionalities mentioned by @kwa20 again. In addition, please also check and correct the refactorings in the mobile app. At least for events where internalId was renamed to internalToken, the annotation you've added to the field does not use camel case, which probably leads to synchronization issues.

**Comment by cazacmarin** [comment]
@MateStrysewske - rechecked all the flows. All is working fine.
At the moment when @kwa20 did the tests, were some issues with contact controller which have been fixed.
The mobile internalId which is not using camel case, was present at the moment when internal id field was there. It was not touched at all. Synchronization for events is working fine. Mobile app was tested with sources from development branch taken ~1 hour ago. Internal Token is also searchable. Based on that, I'm closing this issue.

**Comment by MateStrysewske** [comment]
@cazacmarin Please take a look at the following code:

``` 
case 287:
				currentVersion = 287;
				getDao(Event.class).executeRaw("ALTER TABLE events ADD COLUMN internalId text;");
```

This was the addition of the internal ID field to the events in the mobile app. As you can see, it's using camel case. 

Now this is the code in Event.java that was introduced in this issue:

```
	@Column(name = "internalid")
	private String internalToken;
```

As you can see, it's not using camel case. However, since SQLite is case-sensitive, this means that a database that was already set up with 1.60.0 or before will not recognise this field, which is probably exactly the error that @BarnaBartha had reported internally yesterday:

```
Unknown field 'internalid' from the Android sqlite cursor, not in:[connectionNumber, disease, diseaseDetails, diseaseTransmissionMode, endDate, eventDesc, eventInvestigationEndDate, eventInvestigationStartDate, eventInvestigationStatus, eventLocation_id, eventManagementStatus, eventStatus, eventTitle, eventType, evolutionComment, evolutionDate, externalId, externalToken, humanTransmissionMode, infectionPathCertainty, internalId, meansOfTransport, meansOfTransportDetails, medicallyAssociatedTransmissionMode, nosocomial, ownershipHandedOver, parenteralTransmissionMode, reportDateTime, reportLat, reportLatLonAccuracy, reportLon, reportingUser_id, surveillanceOfficer_id, riskLevel, sormasToSormasOriginInfo_id, srcEmail, srcFirstName, srcInstitutionalPartnerType, srcInstitutionalPartnerTypeDetails, srcLastName, srcMediaDetails, srcMediaName, srcMediaWebsite, srcTelNo, srcType, startDate, superordinateEventUuid, transregionalOutbreak, travelDate, typeOfPlace, typeOfPlaceText, workEnvironment, pseudonymized, changeDate, creationDate, id, lastOpenedDate, localChangeDate, modified, snapshot, uuid]
```

@BarnaBartha Maybe you can say a few words about this, especially whether changing the column definition from `internalid` to `internalId` fixes your problem. In any case, I believe this is the issue.

@cazacmarin Can you please install 1.60.0 on your device, make sure you have an event in the database that is synchronised to the mobile app, and afterwards upgrade from 1.60.0 to the current development version? You should run into this issue then. If that's not the case or you believe it isn't an actual issue, please get in touch with Barna and look into his issue, and make sure that it is indeed unrelated to this issue here.

**Comment by cazacmarin** [comment]
@MateStrysewske  - I got your point. I will retest it again based on the provided scenario.
