### ISSUE TITLE
Make clinical, epi and labconfirmation DE only

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5241]
### Bug Description

- These variables were initially DE only but now appear on international web and also on mobile app for COVID only

### Steps to Reproduce

1. 
2.

### Expected Behavior

- Make this variables DE only
### System Details

* Device:
* SORMAS version: 1.59
* Android version/Browser: 
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: national user + admin, hospital informant

**Comment by MateStrysewske** [comment]
@bernardsilenou Are you sure that they're not used in other countries as well? It's not a bug, but a configuration that can be changed in the database. By default Covid-19 is using the extended classification system. We could change the default, but I'm not sure whether we should do that.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- The only minor drawback that I can think of is the fact that it shows for covid-19 only, and for measles we have another view, thus from users perspective, it would be good to have a uniform view in terms of classification.
- We can keep this issues and maybe when  extending the feature to all diseases, we can then decide on how the default would look like. Thanks

**Comment by MateStrysewske** [comment]
@bernardsilenou That's because Measles is classified differently, i.e. it can only be clinically, epidemiologically OR laboratory-diagnostically confirmed, while Covid-19 (at least in Germany) can be each of those. I don't know how exactly it's handled for Covid-19 e.g. in African countries.

So my question in regards to this issue would still remain - do we need to change anything about the default for Covid-19? Because if not, I'd like to close it.

**Comment by bernardsilenou** [comment]
@MateStrysewske I think we should do nothing for now. I would close it and reopen another one when we would add these variables to other diseases.
