### ISSUE TITLE
Mobile app does not sync when user account is changed

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5269]
### Bug Description

- An informant account on the devices worked fine. App does not sync when user account was modified.
### Steps to Reproduce

1. install 1.59 and log in with informant. Make sure all works including sync bidirectionally, confirm this by creating few entities
2. log out and log in with a surveillance + contact officer account on the same device. Login works, infrastructure data pulled, but no data on entities (case, contact, events, samples etc) was pulled on device. I did not clear cache before changing since cache should normally be  cleared when a new user account is logged on device.  
3. re-logged in with the same user but same situation.
3. App works normally as new entities can be added but does not sync, show error message.

### Expected Behavior

I do not know if the change of user account was the cause of this bug, but this is how it happened.
### System Details

* Device: A9 samsung
* SORMAS version: 1.59
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: Informant, surveillance officer

**Comment by bernardsilenou** [comment]
@VitaliHZI  experienced the same issue after switching the user account.

**Comment by sergiupacurariu** [comment]
@bernardsilenou I tested the issue on Sormas version 1.60 with surveillance officer + contact officer user, surveillance office only user, community informant user. Added cases or events. Log in and out with the same user or a different type of user. German and international servers. Synchronization always works. However, I have found a situation in which synchronization does not work. The issue is linked to the missing place of stay which is not saved if the selection is Home. Could you tell me if the error message is this one: "Some entries could not be synchronized. Please try again later"?.

**Comment by bernardsilenou** [comment]
@sergiupacurariu  I just tried again on release-international. Upgrade to 1.5.1 was fine. The error massage is "Synchronization failed. please try again later"
I have not tested with 1.60

**Comment by bernardsilenou** [comment]
@StefanKock 
Will https://github.com/hzi-braunschweig/SORMAS-Project/commit/d477bdf9f11369df7242a456f2b6f64ab385f051 resolve this issue please?

**Comment by bernardsilenou** [comment]
@StefanKock All works fine with 1.60 now
