### ISSUE TITLE
Different results at different times in CasesView

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#5276]
### Bug Description

It seems to happen from time to time that filtered queries in the CasesView lead to different results at different times, although nobody has worked in the system in the meantime.

### Steps to Reproduce

1. Go to CasesView
2. Filter for report date from one day to the same day
3. Apply filters

### System Details

* SORMAS version: probably 1.58.3

### Additional Information

At first, there was a suspicion that possibly the query is performed with date values with strange time values. However, this could be disproved by debugging.

**Comment by DavidBaldsiefen** [comment]
What do you mean by "different results"? Do you mean different sort orders, each time `Apply` is pressed?

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen No, different numbers of cases. Christopher and I talked about it, we'll need the creation dates of the cases in question before we can further investigate this.

**Comment by ChristopherRiedel** [comment]
@kwa20 @JaquM Is this still an occurring problem? If yes, could you please try to provide us the creation dates of the cases in question?

**Comment by kwa20** [comment]
@ChristopherRiedel So far I only got correct numbers when filtering for individual days. However, I noticed that the numbers on the case directory for case report date differs from numbers on the dashboard.

The count on the dashboard not only seems to be off by one but also very different from the directory.
<img width="830" alt="dashboardNewCases" src="https://user-images.githubusercontent.com/70317594/121652439-effcdd00-ca9b-11eb-89a1-1735fc5a5aba.PNG">
I guess the count on the dashboard might be off because of 'not a case' being included.

This discrepancy I can not explain however:
<img width="846" alt="dashboardNewCases2" src="https://user-images.githubusercontent.com/70317594/121652442-f12e0a00-ca9b-11eb-9acc-b8c6bacab73a.PNG">

**Comment by ChristopherRiedel** [comment]
@kwa20 This problem was named by a health department 1,5 monts ago. If you haven't heard of it again, maybe a newer Sormas version fixed the problem.

**Comment by ChristopherRiedel** [comment]
@kwa20 shoul i close this or are we waiting for a response?

**Comment by kwa20** [comment]
@ChristopherRiedel Yes, I think it can be closed. If it comes up again I'm sure it'll make it's way to github :)
