### ISSUE TITLE
Use last contact date for follow-up calculation [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#529]
- [ ] Calculate follow-up until based on last contact date, if available - only use report date as a fallback

**Comment by MateStrysewskeSym** [comment]
@dta16 I think some time ago we agreed that the last contact date has to be before the report date of the contact, and that it's better to create a new contact in the system in case two persons had contact again after the initial contact. The last contact date is purely for information in this case, because the follow-up duration is always calculated based on the report date to make sure that, even if a wrong last contact date has been entered, we still always get the maximum follow-up duration just to be safe.

Do you want us to change that system or are we keeping the logic that we brought together earlier?

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym I will confer with my colleagues and get back to you on the best way forward. 


Thanks

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda 
About this issue. 
Please use this only if the last date of contact is missing but in calculation, always use the date of report as day 1 of follow up just to be safe and use the maximum of incubation period according to WHO definitions
Please the last contact date has to be before the report date of the contact, and that it's better to create a new contact in the system in case two persons had contact again after the initial contact. The last contact date is purely for information in this case, because the follow-up duration is always calculated based on the report date to make sure that, even if a wrong last contact date has been entered, we still always get the maximum follow-up duration just to be safe.

**Comment by Chinedar** [comment]
Dear @MateStrysewskeSym 

this still calculates the "follow up until" bearing from "date of report" instead of "date of last contact". 

Please look into this. 

@dta16 @hzi-braunschweig please advice further.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Please have a look at the last comment in this issue. We've explicitely decided to always use the report date for follow-up calculation. I'll close this ticket again, should your discussions with Daniel come to a new conclusion, we should open a new ticket instead.
