### ISSUE TITLE
Server Configuration Options > `namesimilaritythreshold` default value unclear

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5315]
On the page https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Server-Configuration-Options it is listed that:

`namesimilaritythreshold`

The similarity threshold after which two names are identified as similar enough to consider them for duplicate detection. The higher the value, the more restrictive the similarity search. The default value should work for most servers. If you need to change it, please change it carefully as slightly higher or lower values already lead to significant differences. The "D" after the number is required and specified that it is a decimal number.

**Default: 0.65D**
Possible Values: 0.0D - 1.0D

---

When inspecting the actual config file of a productive server (zh.sormas.ch), after the update to 1.38.3, the following is visible:

**default: 0.4D**; use a value between 0 and 1 (the higher the value, the more restrictive the similarity search)
namesimilaritythreshold=1.0D

---

It is not quite clear if 0.4D or 0.65D are the default value? Feedback/input/confirmation of the default value would be much appreciated, please.  Also, is it possible that this value changed programmatically during the update to 1.58.3 in the server config file...?

**Comment by MateStrysewske** [comment]
@Candice-Louw The .properties file on the server is not updated when a new SORMAS version is released, which is why there will be inconsistencies over time. 0.4D was the threshold we were using at an earlier point of time before we switched to a slightly different method to calculate the duplicate names, which required us to increase it to 0.65D. 

The Wiki (and the sormas.properties file on the current release branch) is the up-to-date resource.

It's not possible that the value changed programmatically in the server config file, no.

**Comment by Candice-Louw** [comment]
Thank you!
