### ISSUE TITLE
Add a checkbox to avoid sending this case to SurvNet [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5324]
### Development Specifications
- Add a new boolean field called `dontShareWithReportingTool` to cases
- Extend the case creation and edit forms in the web app with this new field (checkbox); only visible if the SurvNet interface is configured; position it below the external ID; caption: "Don't share this case with the external reporting tool"
- When the checkbox is checked, display a warning label (exclamation icon + text) below it: "This case is actively prevented from being sent to the external reporting tool"
- ~~Add a checkbox filter to the case directory: "Only show cases that are not shared with the external reporting tool"~~ 
- Add a checkbox filter to the case directory: "Only cases marked as don't share with reporting tool"
- Extend the case bulk edit form to include the new field
- Hide the "Send to reporting tool" button in the case view if the checkbox is checked
- Prevent cases from being sent to SurvNet if the checkbox is checked; this includes cases that may be sent as part of event clusters

*** Additional Info
- in GERMAN call this box please "Senden an Meldesoftware erfolgt in anderem Landkreis".

_Originally posted by @maxiheyner in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4770#issuecomment-832503288_

**Comment by MateStrysewske** [comment]
@markusmann-vg @maxiheyner Can't this be calculated based on the share information that we already have? E.g. when the ownership of a case has been transferred to another instance, don't send the case to SurvNet by default because it will be handled by the other instance anyway?

**Comment by JaquM** [comment]
@MateStrysewske 
Cases that are not reported are often recorded for the purpose of tracing infection chains and because people from other areas of responsibility are also tested. There is currently no workaround without data loss, and cases are repeatedly reported incorrectly because it is not possible to filter them in mass processing mode. This is why this selection option is very important for the German offices.

**Comment by bernardsilenou** [comment]
> @MateStrysewske
> Cases that are not reported are often recorded for the purpose of tracing infection chains and because people from other areas of responsibility are also tested. There is currently no workaround without data loss, and cases are repeatedly reported incorrectly because it is not possible to filter them in mass processing mode. This is why this selection option is very important for the German offices.

@JaquM @MateStrysewske There is something about this comment that is not clear.
Do you mean the users register data in sormas, using their jurisdiction/ reporting jurisdiction while the data is not suppose to be reported to SurvNet ?
Why should there be cases that should not be reported?
Why is there a data lost? Is this about using certain user roles that can not see certain data?

I am asking this questions because only data for notification to public health authorities should be documented in SORMAS. If we decide to document that is not for notification, then we may need to add such a future for  all entities and also decide if we count them in statistics (Centralized and local instance) or not.

**Comment by JaquM** [comment]
@bernardsilenou 
If a case is in a hospital in Berlin Mitte but lives in Berlin Neukölln, then the case is documented in both departments, processed in both, but only reported in one. A similar scenario is that someone lives in France, works in Germany, is tested in Germany and generates contacts in Germany. Then it is documented but not reported to the country authority.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by leventegal-she** [comment]
@markusmann-vg @JaquM If a case is set to "don't share with SurvNet", should this state be kept when sharing via SORMAS to SORMAS?

**Comment by JaquM** [comment]
@leventegal-she  it should stay with the sending HD but not shared with the receiving HD

**Comment by AndyBakcsy-she** [comment]
Validated ticket using test-de1.sormas.netzlink.com

**Comment by JaquM** [comment]
@leventegal-she could we please move this to the part "Responsible jurisdiction" and above the "Responsible jurisdiction of the case differs from its place of stay" so it would be directly at the fitting place

**Comment by leventegal-she** [comment]
@JaquM On the case creation dialog I would move this field below the Region/District/Community fields to be somewhat consistent. I mean to have it around the jurisdiction fields on both forms.

Do you agree?

**Comment by JaquM** [comment]
@leventegal-she sounds good
