### ISSUE TITLE
Performance analysis and script implementation

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5342]
- [x] Analyse what was already created (test plan , documents, scripts)
- [x] Identify what needs to be included in the first batch of performance scripts
- [x] Identify the needs/problems related to Performance
- [x] Create POC
- [ ] Suggest Strategy to go forward

**Comment by JonasCir** [comment]
@AndyBakcsy-she I think there are older issues which were already estimated which talked about using the data-generator for performance testing. However due to resources this never took off...

**Comment by tamasvlad** [comment]
- [x] Analyse what was already created (test plan , documents, scripts)
- [x] Identify what needs to be included in the first batch of performance scripts
- [ ] Identify the needs/problems related to Performance
- [x] Create POC
- [ ] Suggest Strategy to go forward


**Existing performance testing subjects**
performance test plan
data generator
performance tests written in gatling - Heavily outdated according to Maté Strysewske


**Identify needs**
build to build performance monitoring
load testing on the import


**What we can achieve**
build to build execution and monitoring for the rest api’s
identify performance bottlenecks
find application breaking points
we can receive information about the response times, stability, reliability, scalability, etc.

**Existing proposal**
Data size to test (push and load):
1_000 cases
1_000 contacts
1_000 event participants
Test after each 100 entries how long it takes to fetch 100 entries.
Integrate SORMAS-data-generator in the TEST instance.
Report in the log after each run:
average duration per entry push
duration for the fetch data calls (all timestamps).
Reset the database to an empty/previous state so that results are comparable.

**What do we want?**
from the existing proposal, nb. 1 and 3 are covered with the new Jmeter scripts. Regarding nb. 2 - we need to investigate if it is still needed because the data is injected into the database via the implemented post requests. Nb. 4 is not done.



**Plan going further**
add the script to sormas gitlab and configure them to run in CI environment (jenkins/gitlab) for every build
install and configure application monitoring tools. Eg: New Relic - in order to monitor server resources during performance testing execution or investigate where the performance bottleneck is.
the environment used for load testing should be similar to the production environment, otherwise the results are not relevant for production users.
add more scripts covering different areas?

**Results**
the application could hold 500 concurrent users doing different requests for 12 minutes. After that we received 502 error until the end of the execution
the application could hold 100 concurrent users load for 11 minutes, however we can see a big spike in response times after 7 mins.

**How to run the scripts**
Preconditions:
Java 11 and apache Jmeter is installed on the machine that you want to use
download the jmx file on the machine
open the console and navigate to the Jmeter bin folder
execute the following from the command line:  jmeter -n -t <PathToTheJMXFile>\SormasPoc.jmx -l <PathWhereTheResultsWillBeSaved>\Results.csv -e -o <PathWhereTheHtmlReportWillBeSaved>

Example: execute the following from the command line:  jmeter -n -t C:\projects\sormas\performance\SormasPoc.jmx -l C:\projects\sormas\performance\results\10threads\Results3.csv -e -o C:\projects\sormas\performance\results\10threads\report3
