### ISSUE TITLE
Allow all sexes to have pregnancy attributes [0.5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5418]
### Feature Description

Pregnancy related fields for a person only show when the person gender is set to female.

### Problem Description

Persons with the gender other can also be pregnant. 

### Proposed Change

Those fields should be selectable for them as well.

### Additional Information

I stumbled upon this when reviewing a pull request for #5377. It may be that there a more fields that are so far specific for female person, but should be present for the third gender, too. It may be worth checking.

### Development Specifications
* Remove the sex restriction from the pregnancy (and depending, i.e. postpartum and trimester) fields in the case and vaccination forms. This applies to both the web app and the mobile app.

**Comment by richardbartha** [comment]
Hi @FredrikSchaeferVitagroup! I left a similar change/functionality option comment in the #5377 bug's additional info that I think is a similar issue, maybe when this ticket is addressed that can be also checked.   
I think pregnancy related field should have an age limit for female patients. **For a 2 year old female patient you should not have the option of selecting pregnancy options in additional medical info !**

**Comment by kwa20** [comment]
In terms of this issue, we might actually consider making pregnancy related fields available to any entity independent of the gender for diversity and inclusiveness reasons. Data entered in the gender field does not necessarily have to refer to biological genders. 

@JaquM

**Comment by bernardsilenou** [comment]
- But asking a male if he is pregnant may also be interpreted by the user as a bug, which was partially the reason for adding the validation in the first place.
- What about excluding males and validate using NA, female, other and unknown?
-  `For a 2 year old female patient you should not have the option of selecting pregnancy options in additional medical info !`  this is probably a bug because it was not programmed like that.

**Comment by kwa20** [comment]
@bernardsilenou The issue is that a person labeled as male may very much be able to be pregnant because their biological gender is e.g. female. Therefore, pregnancy would be a necessary risk factor to be documented as well and therefore doesn't need to be hidden. Agreed, this might not happen often but it is possible and labeling them as 'other' would also no be correct.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't think we ever added age validation to the pregnancy fields - and the question is whether we should actually do that because I believe it's hard to decide where to draw the line here. The youngest confirmed mother, according to a quick Google search, has been 5 years old - even if that's incredibly rare, it has to be possible to document such cases in SORMAS.

Concerning the topic of males becoming pregnant, I'm with @kwa20 here. We should remove the validation that is currently in place because of this exact reason.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
This means we discussed but did not implement.
In summary, you suggest we:
-  remove the validation using sex
- add a validation using age but with wider range 5 to 70 inclusive 
:+1:

**Comment by roxanamlendea** [comment]
I found an issue regarding this ticket which is reproductible on the vaadin app only. If the sex is unknown / other or male and has some values set in the 'Pregnancy' and 'Postpartum' fields (eg screenshot), when I change the sex to 'female' the values set to those fields remain saved, which is correct, but if I change the sex to other / unknown or male, the values are reset.
So, the values remain set only if you change the sex to 'female', otherwise, if the sex is changed to male / other or unknown, the values are reset. 
![image](https://user-images.githubusercontent.com/89522688/148520760-7c9ca783-2d5e-41ae-998c-434a72172940.png)

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT for the vaadin app and on Android Studio, connected to the server test-de.sormas.netzlink.com/sormas-rest/ for the android app.
