### ISSUE TITLE
Events modification synchronization issue

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#5436]
### Bug Description

Changing event's region and district fields doesn't sync on android app correctly
### Steps to Reproduce

1. Create an event for a specific district and region
2. Log in on android with a user that has view rights for given district and region of the created event
3. Modify the given event's district and region fields to a different one that the user on android has no access to
4. After synchronization you can still see the event on android

### Expected Behavior

After synchronization the logged in android user should not see the event since it has no view access to different district and region event. 
### System Details

* Device: windows, android
* SORMAS version: 1.60.0-SNAPSHOT
* Android version/Browser: Android10/Chrome
* Server URL: localhost
* User Role: any with district and region view restriction

### Additional Information

The issue is not present on the web app.

**Comment by MateStrysewske** [comment]
@richardbartha That is okay. We only check for entities that the user has no longer access to once a day, because otherwise there would be way too much traffic between the mobile app and the web server. You can see this in the code at `sormas-app/SynchronizeDataAsync.java:116). There's a comment there:

"// pull and remove deleted entities when the last time this has been done is more than 24 hours ago"

You could test that it works locally by changing that logic to always do this kind of synchronization (i.e. remove the condition that only does it after one day has passed).

**Comment by richardbartha** [comment]
Thanks for the info :)
