### ISSUE TITLE
Deleted pathogen tests are still shown in the UI

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5443]
### Bug Description
Deleting pathogen tests does not work. After confirming the deletion, the pathogen test remains.

### Steps to Reproduce

1. Open a sample with an existing pathogen test
2. Try deleting the pathogen test

### Expected Behavior
Pathogen tests should be able to be deleted.

### Screenshots
<img width="693" alt="deletionPathogenTest" src="https://user-images.githubusercontent.com/70317594/118262442-33702580-b4b5-11eb-851b-54acc8c74a75.PNG">

### System Details

* Device:
* SORMAS version: 1.58.3/1.59.1
* Android version/Browser: firefox
* Server URL: musterstadt.sormas-oegd.de; test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by richardbartha** [comment]
Can this be fixed for better end user experience, and refresh the sample page after deletion ?
Now after deletion the pathogen test on the UI is still there since the page is not refreshed causing the end user to try again maybe resulting in frustration :)
![image](https://user-images.githubusercontent.com/83635257/118274559-910c6e00-b4c5-11eb-9c4d-8814c61a8350.png)

**Comment by MateStrysewske** [comment]
Good point, sure! I'll take care of that!
