### ISSUE TITLE
[Angular][BackEnd] Case Search [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5484]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

1. We need to unify (or check) the current two search fields (from legacy Sormas) which searches in both the case (ID, Name, EPID, facility, etc) and event (ID, title, description)
2. On the get_all request we need to have "search" available as a param
3. This needs to work together with the current pagination / filter functionalities

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup An alternative could be to keep the separated fields (because they make sense from a user point of view, and they should probably stay separated in the UI filter forms) and add an alternative endpoint that allows to retrieve cases based on a criteria (similar to the new /indexList endpoints)
