### ISSUE TITLE
Addition of a Variant field in the "EVENT" part

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5525]
**_Warning : Ticket update_**

### Situation Description
To date, the field for entering the disease variant only exists for cases. Users regret not categorizing events according to the variant strain of the disease.

### Feature Description
Develop a drop-down list allowing the user to have information relating to the major variant of the event.

This variable will be positioned in the event file, to the right of the disease field.
![image](https://user-images.githubusercontent.com/65449450/119466200-ae063400-bd44-11eb-8260-d3c75392883c.png)

This variable can be completed in two ways:
1) Directly and manually by the user who will select the major variant of the event from the drop-down list.

2) Automatically by SORMAS: a "magical wand" button located to the right of the field is used to launch the base calculations to identify the majority variant among the event participant (ep).

![image](https://user-images.githubusercontent.com/65449450/119775252-a4efa100-bec3-11eb-9a1a-8156d85c3a10.png)
 
The management rules for this automatic calculation are as follows:
•	if among the ep, no one is the case, the field remains empty and the user can himself select a variant strain from the list configured on the server
•	if among the ep, one or more people are cases and have the same and unique variant strain, the system would switch the drop down list to this variant (the user could, however, modify it if he wanted)
•	if among the ep, several different variant strains are identified, the system proposes the majority variant strain by number or, in the absence of a majority (ie presence of tie variants), use the most recently (based on report date of the associated cases) identified variant. The user will always have the possibility to modify the strain manually by scrolling the drop down list.
•	If among the ep, the majority variant strain is `unknown` , the "variant" field will indicate the "unknown"  if only unknown and NA exist, else use the second majority category over Unknown.
•	If among the ep, the majority variant strain is `NULL` , the "variant" field will indicate the "NULL" 

The result returned by the query will overwrite the information previously entered in the field.

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou
I think the management rules shouldn't be applied automatically but should be triggered by a button (on the right of the input box, with a magic wand icon for example) or this will leads to a lot of input errors

**Comment by bernardsilenou** [comment]
@carolinverset @ftavin 
`if among the PPs, one or more people are cases and have the same and unique variant strain, the system would switch the drop down list to this variant (the user could, however, modify it if he wanted)` -> Here users should be able to choose only among the possible variants of the cases of the PPs.

**Comment by bernardsilenou** [comment]
> @carolinverset @bernardsilenou
> I think the management rules shouldn't be applied automatically but should be triggered by a button (on the right of the input box, with a magical wand icon for example) or this will leads to a lot of input errors

Do you mean we should not compute the variant automatically?

**Comment by Marko-ilmkreis** [comment]
@carolinverset @bernardsilenou @ftavin ist similar to my issue #4978. Maybe it can be solved together.

**Comment by carolinverset** [comment]
> @carolinverset @bernardsilenou @ftavin ist similar to my issue #4978. Maybe it can be solved together.

@Marko-ilmkreis @bernardsilenou @ftavin 
Ah yes indeed. sorry I didn't see your ticket.
I am also of the opinion to keep a specific variable in connection with the disease variable in order to avoid an excessive DE specificity.

**Comment by bernardsilenou** [comment]
@marko-ilmkreis  @carolinverset 
- What is missing missing when compared to #4978 if a filter on the event directory.
- @kwa20  @marko-ilmkreis @carolinverset :  One question pls: should the users be allowed to tag an event as VOC when there is no EP  person that is linked to a case with VOC? ie point 1 of the main specification. To me i can only think of a use case whereby sormas is used to manage events only and users are needed to tag events directly as VOC while the cases of the ep are stored in another system. OR should we prevent users from directly taging an event as VOC when there is no ep person linked to a VOC case?
- The event inherits the majority VOC category from the cases linked to the ep  of the event.

**Comment by bernardsilenou** [comment]
@JaquM  please can you also comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/5525#issuecomment-847835879

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou In my opinion a user could be tag an event as VOC-event manually. I have no doubts for this. Today we handle it with adding the prefix VOC to the title and haven't had a bad experience. It would be good if the system tags it automatically if one ep has VOC.

The other question is: What should sormas do if someone removes and VOC from an ep or if we have eps with different variants of concerns. In a ideal world the event should split up as one event can only have ep with the variant otherwise they might have not the same source-case, or?

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin @Marko-ilmkreis @emond-fuseau
I see a small limit to the automatic addition of "VOC" in the title. In the current context where several variants exist and in anticipation of the multiplication of escape variants expected for the near future, it seems a little reductive to me to know the existence of a variant in the form of a binary variable VOC yes / no. Wouldn't it be interesting to: 1) add VOC in the title and 2) create a drop down list allowing you to select the variant strain present in the event? (based on the operation developed in the case section with a list of configurable variants in the database).

**Comment by bernardsilenou** [comment]
@carolinverset 
You are right, we do not only code VOC yes / no but actually the variant, just as we do for cases.

**Comment by bernardsilenou** [comment]
> @bernardsilenou In my opinion a user could be tag an event as VOC-event manually. I have no doubts for this. Today we handle it with adding the prefix VOC to the title and haven't had a bad experience. It would be good if the system tags it automatically if one ep has VOC.
> 
> The other question is: What should sormas do if someone removes and VOC from an ep or if we have eps with different variants of concerns. In a ideal world the event should split up as one event can only have ep with the variant otherwise they might have not the same source-case, or?

The ep can have different variants but all these variants would correspond to the same disease as that of the event.  The solution we suggest is not split the event but user the variant with maximum frequency. Maybe in another issue we can refine how to split the event.

The question `What should sormas do if someone removes the VOC from the ep case` is that same as `what should happen to a case when the variant of the test result is deleted/ changed` ?   maybe show a pop up to ask the user what to do?
@ftavin   I can see signs of performance issues if for each time that that the event is saved, we compute the variant  of the event based on cases linked to the event. Maybe this is what you mentioned here https://github.com/hzi-braunschweig/SORMAS-Project/issues/5525#issuecomment-847677684

**Comment by kwa20** [comment]
Maybe this issue #5567 might help solving this issue in a way. Since the approach proposed there might not necessarily allow filtering for events, it could be complementary to this approach, would however allow users to get an idea of the current disease variant distribution.

**Comment by tbroyer** [comment]
In the management rules, what should happen if among the event participants who are cases some have no identified variant? Should they be ignored? Or should the absence of variant be counted as an unknown variant?

For example:
* if among 5 participants who are cases, 2 have the same variant V and 3 have no identified variant, should the event variant be set to V or left empty?
* if among 4 participants who are cases, 2 have no identified variant, 2 have variant V, should the event variant be set to V, or possibly left empty because the most recent case has no identified variant?

And regarding the unknown case, are we talking about leaving the field empty? (as I proposed in the examples above) or setting it to an explicit "unknown" value? (if so, I'm not sure it's actually possible, given that the variants are customizable and could have no "unknown" value, or possibly have on by another name)
The question also applies to the event participant variants: should such an "unknown" value be treated as a special value? e.g. repeat the 2 examples above with an "unknown" variant rather than no identified variant, what should the outcome be in each case?

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou

**Comment by tbroyer** [comment]
When creating an event, I think we all agree that the "magic wand" 🪄 button should be disabled. But when creating an event from a case, a contact, or another event, today the disease is initialized from those and set as read-only in the creation form; should the variant be initialized as well (I think so) and should it be read-only or left modifiable?
The behavior could possibly be different depending on the source, e.g. read-only if it comes from a super or subordinate event, and read-write if it comes from a case or contact? And/or depending on the initial value, e.g. read-only if non-empty, read-write otherwise?

**Comment by carolinverset** [comment]
Thank you @tbroyer for these elements and questions which show in my opinion the complexity of the automatic calculation of the variant, which would be launched by clicking on the button to the right of the field.

Several elements must be taken into consideration:
- the list of variants is configurable on the server and can potentially integrate modalities of the type "at least 1 variant" ... which can lead to strange calculation results (ex : even if 1 case suffers from the Indian variant but the larger EP's have a "at least 1 variant" variant, the result would be "at least 1 variant" while an Indian variant is likely to be more relevant.
- in France, we no longer look for variants as such but for mutations of interest which for one case can be multiple. In the event that the event groups together many EPs, the management rules will therefore have to manage all of these possible combinations.


Therefore, to date and taking into account these questions which remain numerous, I propose to @bernardsilenou @ftavin @tbroyer  @emond-fuseau not to develop the automatic calculation and to keep the only drop-down list allowing the user to define himself , from the information collected during the investigation, to define the major variant of the event

To be discussed of course.
thanks a lot

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou in addition can you tell if this new field should be added :
- to the event directory ? (can be used to order ?)
- to the filters ?
- to exports ? (which ?)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @tbroyer 
If no opposition, thank you for:
- add it as a column in the event and actions directory with the possibility of sorting on this field
- also add the filter (event and actions directory) to reduce the directory to only the observation of a selected variant
- add it in all exports (events and actions)

**Comment by ftavin** [comment]
@bernardsilenou can you confirm as soon as possible ?

**Comment by bernardsilenou** [comment]
@tbroyer @ftavin 
The specification of filters and export is fine.
- In this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/5525#issuecomment-859370333 I hope you meant ` when creating a case from an event participants?` When linking cases, contacts to events or converting ep to case, we do not pre-fill and transfer the  variants from the event to the case. Because if an event has a variant is does not mean all the cases linked to the event must have the same variant.
- But the reverse is not true since the event variant is computed as the majority vote among all cases linked to the event with available data for variant.
- Point 1 and 2 in this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/5525#issuecomment-858838329 is fine. In presence of tie, we use the variant of the case with the recent report date. If report date is also a tie, then we randomly chose one variant.
- If there is no case or all cases linked to event has NULL variant, then variation of event == NULL
- NULL does not contribute as a count and If Majority  count is Unknown then variation of event == unknown if only unknown and NA exist as categories. ie If there are 5 cases, 4 have unknown and one has variant V,  then variation of event == V

**Comment by ftavin** [comment]
@bernardsilenou I totally agree with @carolinverset in [#5525 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5525#issuecomment-859467625) : the multiple comments here shows the formula is not ok for everyone. As the develpment has already started we should delay the automatic calculation to a later issue and let the developer finish is work on the field.

**Comment by bernardsilenou** [comment]
@ftavin I think all of us agree on the same thing:
- No automatic computation for now
- One point that I added in the initial specification is to prioritize known variants over unknown, even if unknown is the most frequent category among cases linked to the event. Hope this is fine by you?

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @tbroyer 

confirmed this morning during conf-call : no automatic calculation and no magical wand for this issue. Should be done in another issue.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the local environment on the latest version of 1.62.0-snapshot
