### ISSUE TITLE
CaseFacadeEjb.calculateCompleteness: Avoid long wait time when the completeness need to be updated [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#5543]
### Feature Description

When a case is created or changed, the completeness is calculated and persisted as a case attribute. Part of the completeness is, if there is any contact and any sample linked to the case.

### Problem Description

In some use cases, calculating the completeness for a case costs ~1s to query for existing contacts and samples (Follow-up to #4304, there it was ~9s only for checking the sample). This adds up to long running data processing when inserting a lot of data into SORMAS.

### Proposed Change

Basic idea: Don't do this calculation live, but update the case the completeness needs to be recalculated. Do the completeness calculation automatically per cronjob every few minutes async.

### Possible Alternatives

Introduce a date when the calculation was done, and if `null` recalc. But setting the completeness field to `null` looks enough for me.

### Additional Information

> Importing 2000 cases and 1000 contacts yesterday in preproduction, we're seeing ~7000 queries like this, taking up more than an hour ? and a similar query on samples, ~7000 times, accounting for approximately half an hour. The import started at 5:40pm and ended at 9:10pm, that's 3h30, with ~1h40 spent checking whether a contact or sample exists.

Here are execution times for the queries recorded with glowroot.
![grafik](https://user-images.githubusercontent.com/24678567/119654923-3fe76d00-be29-11eb-889b-a27c84e2b688.png)

### Developers specification
1. In `CaseFacadeEjb.onCaseChanged`: replace `newCase.setCompleteness(calculateCompleteness(newCase));` with: `newCase.setCompleteness(null);`
2. Prepare methods in CaseService to be used for updating Case completeness with JTA transaction separation.
  - Move `CaseFacadeEjb.updateCompleteness` to `CaseService`
  - New method `@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW) CaseService.updateCompleteness(List<String> caseUuids)`
3. New method `CaseFacade.updateCompleteness:int`: It checks which cases have no completeness (get uuids of cases, where `completeness = null`), runs this in batches of 10 cases (use `IterableHelper.executeBatched`), calculates and persists it (see above).
4. Define in `CronService` a job that runs regularly. My proposal is "every two minutes". Log the duration and how many cases were updated on DEBUG level.
```java
// as last method before nightly job are listed
@Schedule(hour = "*", minute = "*/2", second = "0", persistent = false)
calculateCaseCompletion()
```

**Comment by bernardsilenou** [comment]
@carolinverset
This is the ticket to address the performance issue

**Comment by tbroyer** [comment]
:thinking: before re-architecting things that way, shouldn't the root cause have been addressed first? Namely that the `exists()` queries return as many rows as there exists in the table, when we're only interested in the first one and we know we compute the exact same value for all rows? (https://github.com/hzi-braunschweig/SORMAS-Project/pull/4310#issuecomment-821053534)
I don't know JPA much (such an awful API), but wouldn't using `setMaxResults(1)` tremendously help here in `BaseAdoService.exists`? (looking quickly at Hibernate's implementation, `getSingleResult()` doesn't issue an SQL `limit 1`, it only makes sure that all returned rows contain the same value, which also implies getting those millions of rows out of the database: https://github.com/hibernate/hibernate-orm/blob/e76241a3091078713dd4b57de085f5fadce5e0db/hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java#L1648-L1673)

**Comment by StefanKock** [comment]
Hello @tbroyer, thanks for contribution. The [BaseAdoService.exists method (v1.60)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/v1.60.0/sormas-backend/src/main/java/de/symeda/sormas/backend/common/BaseAdoService.java#L275-L300) does indeed use `getSingleResult()` but on a `true/false` result. But we are going to look again into this if we can optimize the surrounding query.
