### ISSUE TITLE
Contact follow-up calculation contradicts the expected until date

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5548]
### Bug Description
When contacts are created and the follow-up duration calculation is less than 14 days (set in the database), the follow-up until date shows an error which contradicts the expected until date This results in contacts not being able to be saved properly.

cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/3243#issuecomment-843321677
### Steps to Reproduce

1. Set the follow-up duration to less than 14 days in the database
2. Create a contact
3. Check the follow-up until date

### Expected Behavior
Follow-up until date should not contradict the expected until date and prevent saving
### Screenshots
<img width="622" alt="Screen Shot 2021-05-26 at 11 05 35 PM" src="https://user-images.githubusercontent.com/70317594/119778877-4e389600-bec8-11eb-813c-763b260e12e8.png">

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by StefanKock** [comment]
@kwa20 we are missing at least the validation error message from the field "Follow up until" (red box).

**Comment by kwa20** [comment]
@StefanKock 
<img width="439" alt="followUpError4" src="https://user-images.githubusercontent.com/70317594/119969771-456ebf80-bfaf-11eb-832d-877097b24816.PNG">

**Comment by StefanKock** [comment]
@syntakker please check ContactDataForm::addFields. It seems that `							FacadeProvider.getDiseaseConfigurationFacade().getCaseFollowUpDuration(getSelectedDisease()))` is wrong, it should invoke `getFollowUpDuration` (implicit for contacts.

**Comment by af-pwo** [comment]
https://test.sormas.netzlink.com 
National User
Snapshot 1.60.1 from the hotfix-1.60.1 branch.
Windows 10 Home
Opera Version :76.0.4017.154
Mozilla Firefox 89.0 (64-Bit)

QA Done

User is able to manually set a follow up date after the expected follow up date (14 days) and receives an error message when he tries to manually set a follow up date before the expected follow up date (14 days). The logic for the expected follow up date is taken from here:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3243#issue-726321006

1. If (for a case) a symptom onset date or (for a contact) a last contact date is present, always use it; otherwise:
2. If a positive sample has been collected for this case/contact and the sample date time of the EARLIEST sample is BEFORE the report date, use it; otherwise
3. Use the report date
