### ISSUE TITLE
Multiple clicks on edit icons in tables/grids open many pop-up windows

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5549]
### Bug Description
Implementation of #5227 should prevent being able to double-click buttons. However, clicking edit icons in grids multiple times opens many forms which stack on top of each other.

### Steps to Reproduce

1. Go to e.g. the user section or configurations and click any edit button  many times in quick succession.
2. Check how many windows were opened.

### Expected Behavior
Buttons should not be able to be double-clicked

### Screenshots
<img width="519" alt="doubleClickError" src="https://user-images.githubusercontent.com/70317594/119790979-b0979380-bed4-11eb-8fa9-aff6c46e1244.PNG">

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by StefanKock** [comment]
Technically spoken, double clicks on buttons are prevented, but multi clicks on Grid cells not because they work different. This was not considered or found to be changed in #5227.

Findings:
- TasksView: Edit icon: Single click opens, several clicks open several dialogs
- TasksView: DoubleClick is a feature here, but can be exectued on grid rows more than once
- This does not affect most list view, but also for example for follow-up visits (presumably everywhere where it does not switch the view but opens a modal dialog).

**Comment by DavidBaldsiefen** [comment]
As mentioned by @StefanKock above, this is an architectural problem. Due to the nature of Vaadin there is also no easy fix for this. I've looked into this and it would definitely require a dirty workaround
