### ISSUE TITLE
Pseudonymize data in merge views for users without access to personal/sensitive data [2]

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#5550]
### Bug Description

Logged in as a user without the user right to see personal/sensitive data in their jurisdiction (e.g. admin) you cannot see confidential data of cases however if you go to the merge cases and contacts views, you can see the confidential data.
### Steps to Reproduce

1. Log in as NatUser and create two cases with same data for same person
2. Log in with normal admin user and go to merge cases view

### Expected Behavior

Personal and sensitive data should be pseudonymized if the user does not have access to them (either by jurisdiction or by user rights) in the merge views just as in the directories.

### Screenshots

![image](https://user-images.githubusercontent.com/83635257/119797653-b55f4600-beda-11eb-9f76-5712ec9fd55e.png)

![image](https://user-images.githubusercontent.com/83635257/119797362-73360480-beda-11eb-9060-5a5004644d12.png)

### System Details

* Device: windows
* SORMAS version: 1.61.0-SNAPSHOT
* Android version/Browser: chrome
* Server URL: https://test.sormas.netzlink.com/
* User Role: admin

**Comment by MateStrysewske** [comment]
Users who have access to the duplicate merging view need access to all these details to be able to use it properly. I think this is more like a configuration issue on the respective server (i.e. they should take the user right to access this view away from user roles that aren't supposed to see personal data), but this is a valid concern anyway. @markusmann-vg could you please get in touch with the data security team and ask them how this should be handled?

**Comment by adinaflorea9** [comment]
I am reopening the ticket as discussed with @carina29 so that the day from the birth date should not be displayed in the 'Merge duplicate contacts' just as it is not displayed in the 'Merge duplicate cases' view for a user that does not have rights to see it:

Merge duplicate cases:
![image](https://user-images.githubusercontent.com/96909231/231170031-c1b5fdc1-9b9d-4e0d-8913-dfba51aa0540.png)

Merge duplicate contacts:
![image](https://user-images.githubusercontent.com/96909231/231170114-a1309761-17b4-498b-9266-7c6ee9e5f475.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(2f7e4db).
