### ISSUE TITLE
Adding back deleted event participants is not possible

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#5559]
### Bug Description

Having a person participate in multiple events, removing him from events and adding back is not possible.
### Steps to Reproduce

1. Log in with NatUser
2. Create a new **eventA** with default region and district, select as responsible user Surveillance Supervisor
3. Add a participant to this event
4. Create a new **eventB** with default region and district, select as responsible user Surveillance Officer
5. Add same participant to this event also
6. Delete from both events the participant
7. Go to **eventB** and add back the same participant that was deleted
8. Go to **eventA** and try to add back the same participant also (error pops up)

### Screenshots

![image](https://user-images.githubusercontent.com/83635257/119834001-dbe3a800-beff-11eb-8790-f99bc1b45937.png)

### System Details

* Device: windows
* SORMAS version: 1.61.0-SNAPSHOT
* Android version/Browser: chrome
* Server URL: localhost but same happens on https://test.sormas.netzlink.com/
* User Role: NatUser

### Additional Information

[logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6554400/logs.txt)

**Comment by MateStrysewske** [comment]
This is a tough one. The reason is probably that event participants aren't actually deleted, they have a `deleted` attribute that is set to true, so they're technically still associated to the event. A solution could be to allow persons to be added to the same event multiple times if ALL other event participants of this person in this event are deleted.

**Comment by RazvanHodisan** [comment]
Verified on test-de Version: 1.61.0-SNAPSHOT
