### ISSUE TITLE
UserFacade: get methods with UserReferenceDto directly into the DTOs [3]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#5614]
### Feature Description

For select or filters in a lot of views, a list of users is loaded from the backend.

### Problem Description

The current implementation loads `User` JPA entities, which results in big burden with a lot of data (a second run costs almost nothing).

### Proposed Change

1. Add missing unit tests for the methods listed in 2.
2. Change the following UserFacade methods to directly load UserReferenceDto lists as DTOs (one method in UserFacadeEjb with variable parameters).
`getUsersByRegionAndRoles`
`getUsersByRegionsAndRoles`
`getUserRefsByDistrict`
`getUserRefsByDistricts`
`getUsersWithSuperiorJurisdiction`
`getAllUserRefs`
3. Remove then unused methods in UserService.

**Comment by StefanKock** [comment]
I think there is a lot to consider, refactor and keep parallel usage in the backend possible with entities. Nothing for a quick shot in a hotfix.

**Comment by StefanKock** [comment]
I found that collections cannot be fetched with the usual "directly" to DTO approaches. Some others also fell into this challenge:
- https://forum.hibernate.org/viewtopic.php?p=2319163
- https://hibernate.atlassian.net/browse/HHH-2253

One idea I already implemented in the past was to have a stripped down copy of the User entity only used for read access and containing the needed attributes.

**Comment by StefanKock** [comment]
Reason for a bigger estimate: reuse of methods with need for User entities.

**Comment by StefanKock** [comment]
I created a working start for the ticket, but more where conditions need to be implemented and the whole integration into existing code is missing.

**Comment by StefanKock** [comment]
Discussed with @syntakker: Do UserReference JOIN User on uuid/id to reuse where conditions based on User and avoid remodeling more User attributes in UserReference ([this is how](https://laptrinhx.com/hibernate-tip-join-unassociated-entities-in-criteria-query-2943936790/)).

**Comment by syntakker** [comment]
We investigated the usage of other methods in `UserService` operating on full `User` entities (see list below). These cannot easily be switched to `UserReference` since they need additional data in their usages (messaging, access to district or community, display in grids) or are used in operations at entity level (e.g., set the user of another entity).
We therefore decided to take no further action here, unless actual performance problems manifest, which we do however not expect.

Method                                                                                                | Usage                                                                                                                            
:------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------
public List<User> getInformantsOfFacility(Facility facility)                                          | in CaseFacadeEjb.setResponsibleSurveillanceOfficer (Case.setSurveillanceOfficer)
public List<User> getLabUsersOfLab(Facility facility)                                                 | in SampleFacadeEjb.onSampleChanged (messaging)
public List<User> getAllByAssociatedOfficer(User associatedOfficer, UserRole... userRoles)            | in UserFacadeEjb.getUsersByAssociatedOfficer for WeeklyReportInformantsGrid, community and healthFacility used for sorting
public Map<String, User> getResponsibleUsersByEventUuids(List<String> eventUuids)                     | in EventGroupFacadeEjb.notifyModificationOfEventGroup (messaging)
public Predicate buildCriteriaFilter(UserCriteria userCriteria, CriteriaBuilder cb, Root<User> from)  | in UserFacadeEjb.getIndexList to provide data for UserGrid
public List<User> getAllActive()                                                                      | in StartupShutdownService for initial asynchronous syncUser
public List<User> getAllDefaultUsers()                                                                | in UserFacadeEjb.getUsersWithDefaultPassword for password update reminder
public List<User> getAllByRegionAndUserRoles(Region region, UserRole... userRoles)                    | WeeklyReportFacadeEjb.generateSubmitWeeklyReportTasks (Task.setUser), PathogenTestFacadeEjb.onPathogenTestChanged (messaging)
public List<User> getAllByRegionsAndUserRoles(List<Region> regions, UserRole... userRoles)            | CaseFacadeEjb, PathogenTestFacadeEjb.onPathogenTestChanged, TaskFacadeEjb, VistFacadeEjb (all messaging)
public List<User> getAllByRegionAndUserRolesInJurisdiction(Region region, UserRole... userRoles)      | WeeklyReportFacadeEjb.getSummariesPerOfficer (district used for sorting)
