### ISSUE TITLE
Add property to force the dashboard map to always center on country-center-coordinates

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5666]
### Bug Description

The map is not properly centered if the country.name is set in the sormas.properties.
### Steps to Reproduce

1. Set the country.name in the properties and check if the deposited coordinates properly center the map on the dashboard. 
2. Leave the country.name empty and check the map again.

### Expected Behavior

The map should always be properly centered according to the deposited coordinates.
### Screenshots

**properly displayed map according to coordinates:**

country.name=
<img width="831" alt="mapNoCountryName" src="https://user-images.githubusercontent.com/70317594/120787476-b114d780-c52f-11eb-92f4-bbbccc28069b.PNG">

not considered line also displays the correct center on the map
<img width="627" alt="mapNoCountryName2" src="https://user-images.githubusercontent.com/70317594/120787484-b2de9b00-c52f-11eb-8795-9699b3842533.PNG">

**Wrongfully displayed map:**

If the country.name is set (country.name=germany), the map is centered like this
<img width="827" alt="mapNoCountryName3" src="https://user-images.githubusercontent.com/70317594/120787491-b40fc800-c52f-11eb-9f5c-2168132fc9d6.PNG">

### System Details

* Device:
* SORMAS version: 1.59.2/1.60
* Android version/Browser: firefox
* Server URL: 
* User Role: admin, national user

### Developer Specifications

- Add `map.usecountrycenter` property to `sormas.properties` (default: false)
- If the property is true and `country.center.latitude` / `country.center.longitude` are provided, force the `DashboardMapComponent.java` to always center the map on these coordinates

**Comment by kwa20** [comment]
@T-Hundt for you information

**Comment by DavidBaldsiefen** [comment]
As found in #4936, this is "intended" behavior defined in `DashboardMapComponent.java`.
Currently, the center of the dashboard-map is calculated like this: 

- If User is of national user type OR does not have a region determined:
   - Calculate the center of all regions
- Else if the user has a region:
   - calculate the center of that region
- Else if both above methods fail (e.g. because of incorrect shapefiles):
   - Take the center defined in the sormas.properties

When removing the `country.name` from `sormas.properties`, the first two steps fail (no region/districtdata), thus making the system use the values defined in `sormas.properties`.

Do you want this changed somehow?

**Comment by kwa20** [comment]
@DavidBaldsiefen Thank you, I think I now better understand the behaviour. I guess there might be a collision of interest depending on what the server set up is.
For centralized servers it makes sense to calculate the maps depending on the users assigned region and fall back onto the deposited coordinates if necessary. However, for localized servers, users would always like to be centered on their defined coordinates and don't base it on the user because they often assign higher rights to the users of their system and also deposit coordinates that pinpoint a specific location rather than the center of a country.

We could maybe make this configurable by changing the direction of the fall back, meaning that for servers with this specific configuration, maps will be displayed always according to the deposited coordinates (independent of the users settings) and if these are not set, be calculated based on the assigned region. Maybe you have a better idea how to handle this?

**Comment by DavidBaldsiefen** [comment]
@kwa20 I think the server does not really know if it is a centralized or localized instance. I see two options:

a) Add another property `map.usecountrycenter` (default: false), which always forces the map to focus on the center of the country according to the `sormas.properties`
b) If the user has custom coordinates assigned, use that, otherwise use the old system.

Option b) would of course require the coordinates to be manually set for every user.

**Comment by kwa20** [comment]
@DavidBaldsiefen Considering the effort of doing it depending on the user, I'd prefer option a).

**Comment by RazvanHodisan** [comment]
Verified on the local environment, Version: 1.61.0-SNAPSHOT
