### ISSUE TITLE
Configuration > Countries > `Import Default Countries` update [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5680]
### Feature Description

Following the introduction of countries infrastructure in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4782#issuecomment-801263814 , it was noticed that certain countries are missing from the default SORMAS import or some details from countries already included are missing.

### Problem Description

The WHO list of countries has been used in SORMAS thus far, however, this is not inclusive of all countries - this results in incomplete mappings (SurvNet/CH MED) and further (see https://github.com/hzi-braunschweig/SORMAS-Project/issues/5669)

Moreover, some countries are in SORMAS per the WHO list, but are missing some details (such as an ExternalID for example).

### Proposed Change

Update the current list of SORMAS default countries to include the following (where already existing, please fill/update missing details in original form):

defaultName | externalId | isoCode | unoCode | archived | subContinent
-- | -- | -- | -- | -- | --
Ivory Coast | 8310 | CIV | 384 | FALSE | Western Africa

### Additional Information
Inform Netzlink about this change and add release notes that inform users about the addition.

**Comment by markusmann-vg** [comment]
@Candice-Louw I think this is a HZI/Netzlink ticket. The countries which are not mentioned or are mentioned but not in the list should be updated.
Please notify us, when this is done.

**Comment by MateStrysewske** [comment]
@Candice-Louw Giving a bit more detail here: We have specifically decided to use the WHO country list because it makes the most sense for an international eHealth software and because it frees us from any potential political issues in regards to which countries we're choosing to integrate into SORMAS and which not. There definitely are some countries missing that are part of the official WHO country list (e.g. Ivory Coast), but at least some of the countries you've listed above are not part of that list and therefore should not be added to the default country import. Please go through the list again and remove all countries that are not part of the official WHO country list.

What @markusmann-vg mentioned is related to the Germany-specific country import that is based on the RKI list of countries and that is not managed through SORMAS directly.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(223c5c5) - imported the default values for countries in the 'Configuration' - 'Countries' tab and Ivory Coast is now present:

![image](https://user-images.githubusercontent.com/96909231/230070912-6048445f-963f-43bf-b1a2-1836d3d17a34.png)
