### ISSUE TITLE
Add option to directly upload documents upon generation [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5703]
### Situation Description

Users would like to immediately upload documents that they have generated for a respective entity.
### Feature Description

Add the option to directly upload the documents that are generated during the document generation for respective entities and bulk edit mode.
- Add a checkbox to the creation pop-up saying "Also upload the generated document to this entity" (Might need slight adjustment for bulk action: "Also upload the generated documents to the selected entities")
    - If selected, upload to respective entity
    - If unchecked, only generate
- If the document is larger than the file size limit, after the document has been generated, display a warning message to the user: "The document was successfully generated, but could not be uploaded to the entity because its file size exceeds the specified file size limit of {SIZE_LIMIT}."; in bulk mode, if at least one document exceeds the file size limit, display an actual popup window that contains the following elements:
  - Window caption: "Document upload warning"
  - Label: "The documents were successfully generated, but at least one document could not be uploaded to its entity because its file size exceeds the specified file size limit of {SIZE_LIMIT}."
  - Below that, another label: "Documents could not be uploaded to the following entities:"
  - Below that, a list of the UUIDs of the entities for which the upload failed
  - The window only needs one primary button with the caption "Okay" that closes the window

Default: false
### Additional Information

<img width="470" alt="documentGenerationUpload" src="https://user-images.githubusercontent.com/70317594/121156186-c5ffac80-c848-11eb-9aec-9b1de8aa1250.PNG">

**Comment by kwa20** [comment]
@Jan-Boehme That is what came up during the support meeting today. @syntakker fyi :)

**Comment by Marko-ilmkreis** [comment]
@Jan-Boehme @kwa20 @syntakker This is very helpful as it saves us the steps of saving and uploading the document

**Comment by MateStrysewske** [comment]
@kwa20 I've extended the specifications to deal with the file size limit issue; is this fine for you?

**Comment by kwa20** [comment]
@MateStrysewske Looks good. However, can we add the uuid's of the entities where the upload fails in the bulk actions? Otherwise users don't know which entities are affected.

**Comment by MateStrysewske** [comment]
Updated the specifications

**Comment by cazacmarin** [comment]
As agreed with Markus, uploaded document filename for the same entity, should be different(if there is already a document with the same name uploaded in the system for this entity - another document with same name should not be added to it.). 
As current algorithm of storing files is generating always the same name, a different mechanism which will generate the filename should be applied.

**Comment by cazacmarin** [comment]
Info for QA guys.
In order to access Bulk Mode logged in user should have one from next permissions: 
			NATIONAL_USER,
			SURVEILLANCE_SUPERVISOR,
			ADMIN_SUPERVISOR,
			CASE_SUPERVISOR,
			CASE_OFFICER,
			CONTACT_SUPERVISOR,
			CONTACT_OFFICER,
			COMMUNITY_OFFICER
File size limit can be set from sormas.properties file. Parameter has value set in Megabytes and its default value is:
#documentUploadSizeLimitMb = 20   (20 MB)

I've testes with 0 MB as the files are small. All next captures from bulk mode will have 0MB.
![image](https://user-images.githubusercontent.com/6985315/148606359-e553a42e-8a29-496e-b74c-9279142bace0.png)
UUIDs values from non editable text area can be copied.

For `Event Directory` bulk edit option can be found as it is represented in next image:
![image](https://user-images.githubusercontent.com/6985315/148606596-b38b271a-6c93-4b3d-88d2-8c682ba32053.png)

For Cases and Contacts, this option was present before and as well ca be found under drop down component `Bulk Actions`

At the moment when a single document will be created, as for the multiple documents creation, same window with different text(singular/plural) will appear.
At checking the checkbox, automatically document will be uploaded on the server with unique file name and `detailed window` will be refreshed automatically by adding newly created doc. (it will be uploaded if size is not more that the size configured on server)
![image](https://user-images.githubusercontent.com/6985315/148607171-eb7bdcd8-ba62-4c7b-a17c-3553e3a896c6.png)

In case if there are no templates on testing system, with `admin` user they can be uploaded from Configuration section under `Document Templates` tab.
![image](https://user-images.githubusercontent.com/6985315/148607478-b2b9790a-d819-4e6c-8e19-6811bc29fee6.png)

(I took those files from one test server, than uploaded them locally)

**Comment by JonasCir** [comment]
Are 20mb for PDF file limit not a little bit excessive? What are we even including there? :D

**Comment by cazacmarin** [comment]
@JonasCir - it was a file size which was set at the moment when document upload feature was implemented. I leave it as is. Actually, I think that it can have some reason. In case if some specific analysis can be scanned, inserted in a DOC file, and then uploaded. It can be cast as well in PDF, but, not all the docs should have this limit.
Just imagine, 10 analyses, and all of them is much more better to put into the same document as scanned one. So, yeah, document will definitely grow in size.

**Comment by adinaflorea9** [comment]
Verified ticket on test-de.sormas.netzlink.com and test-de2.sormas.netzlink.com, using the latest version of Sormas 1.67.0-SNAPSHOT.

**Comment by cazacmarin** [comment]
One important point to comment. Initially this ticket should be divided in 2. As simple edit mode and bulk edit mode are 2 separate sides where modifications were performed. And in case of a bug in some component, will be opened entire ticket, and not separate sides of it.
3rd ticket which appeared in the process of development, is adding the bulk document creation for Events directory - which should be treated as well as a separate one.
From perspective of story points, firsts 2 tickets should take 2 points each. And last one, 1 story point.
Important to mention here, that not the same generic algorithm is using for all of the entities. All firsts 2(Cases, Contacts) are linked to docx template and Events is linked to html template.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
