### ISSUE TITLE
[Merging] Merge of cases should not leave unmerged event participants behind

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5704]
### Bug Description

This bug is linked to #5700  and #5529 
After merging cases or contacts, the discarded cases / contacts are not listed in the case or contact directory anymore, but they appear in the person directory and the event participant list.  This bug might occur due to the reason, that events are not merged
### Steps to Reproduce

1. Merge two cases or contacts that are linked to events 
2. Search in the person directory or event participant list for the discarded case 

### Expected Behavior

After cases or contacts have been merged, the discarded case / contact should be deleted from SORMAS
### Screenshots

Example: Merge cases linked to the same event 
Case 1: Remaining Case 
![image](https://user-images.githubusercontent.com/83459190/121154402-3f969b00-c847-11eb-8755-8b198a27b93b.png)

Case 2: Discarded Case 
![image](https://user-images.githubusercontent.com/83459190/121154918-a320c880-c847-11eb-9c1f-9274fab4df4d.png)

Event participants list before merging: 
![image](https://user-images.githubusercontent.com/83459190/121155423-132f4e80-c848-11eb-9834-9d5dc6aed60d.png)

Merged case: 
![image](https://user-images.githubusercontent.com/83459190/121154402-3f969b00-c847-11eb-8755-8b198a27b93b.png)

Event participants list after merging: 
![image](https://user-images.githubusercontent.com/83459190/121156300-dca60380-c848-11eb-8d67-5b427ff0c013.png)

### System Details

* Device:
* SORMAS version: 1.69 / 1.60
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: Admin, National User

**Comment by MateStrysewske** [comment]
This issue evokes some questions regarding case/contact merging:

* Currently, when merging two cases with different persons, both persons stay in the system, none of them is deleted; it might be more accurate to delete the person of the discarded case and move all associations over to the remaining person
* Merging two cases with different persons which are event participants in the same event semantically leads to the same person participating in the same event twice; technically, the persons are still different, however, which is an inconsistency
* We generally don't consider event participants or any other "loosely" related entities during the merging process, but we might need to do that

Overall, this issue needs some refinement by us because it potentially has heavy implications on the system.

**Comment by MateStrysewske** [comment]
No longer an issue. Resulting cases are either moved to the preserved case or removed if the "Pick" option is used, and the person directory by now properly hides deleted entities.
