### ISSUE TITLE
Case Bulk Edit mode |  Sharing to reporting tool of a case (marked with "don't share with reporting tool" will result in error

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5750]
### Steps to Reproduce
1. Create a case that has the 'Don't share with reporting tool' checkbox  marked
2. Go to Case directory and select the filter :"Only cases marked with 'Don't share with reporting tool'"
3. Select More and choose Bulk Edit mode and select the case based on the filter
4. Select from Bulk Actions the option to send to reporting tool 

### Expected Behavior
A Warning message should be displayed.. saying that this case can't be sent 
or
Maybe disable the option to Send to reporting tool these type of cases

### Screenshots
Error message when trying to share a case that has been marked "Don't share with reporting tool"
![image](https://user-images.githubusercontent.com/70562142/121518854-a1970200-c9f9-11eb-9ddb-cd06da2d1c69.png)

### System Details

* Device: windows 10
* SORMAS version: 1.61.0-snapshot
* Android version/Browser: Brave/Chrome
* Server URL: test-de1.sormas.netzlink.com
* User Role: natuser

### Additional Information
this ticket might be related to #5324

**Comment by MateStrysewske** [comment]
I think we should probably still execute the sharing operation, but display a message to the user afterwards that X cases were not shared because of this setting.

**Comment by kwa20** [comment]
@AndyBakcsy-she @MateStrysewske This problem seems to go further and no cases at all sent if any of the cases are checked as 'don't send'.

Steps to reproduce:
1. Uncheck any cases as 'don't send...'
2. Send cases to the reporting tool; all should work fine
3. Check 'don't send to reporting tool' for one case
4. Try sending a different case which is not checked as 'don't send...'

Screenshots:
1.
<img width="666" alt="DontSendBug" src="https://user-images.githubusercontent.com/70317594/124387626-a476d100-dcdf-11eb-8b5f-59311b76cd8d.PNG">
2.
<img width="327" alt="DontSendBug2" src="https://user-images.githubusercontent.com/70317594/124387632-a6409480-dcdf-11eb-8af3-1112998c6159.PNG">
3.
<img width="707" alt="DontSendBug3" src="https://user-images.githubusercontent.com/70317594/124387636-a771c180-dcdf-11eb-8663-a76887c60856.PNG">
4.
<img width="412" alt="DontSendBug4" src="https://user-images.githubusercontent.com/70317594/124387637-a93b8500-dcdf-11eb-9bdd-32b4bf37d9ab.PNG">
<img width="707" alt="DontSendBug5" src="https://user-images.githubusercontent.com/70317594/124387638-aa6cb200-dcdf-11eb-9abb-5aa060bc01cc.PNG">

**Comment by AndyBakcsy-she** [comment]
Reopening issue as the error message has the wrong Id.
Select one Case that has the "don't share with reporting tool" checkbox selected and try to send it to reporting tool from the bulk edit mode
Actual:
An error message is displayed with the ID of another case which has the check box marked as well. 
![image](https://user-images.githubusercontent.com/70562142/125433635-94874929-c276-4223-bd26-7ac2a698f4a6.png)

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she This issue has already been included in the hotfix. Could you please open a new issue for your finding? Thanks!

**Comment by markusmann-vg** [comment]
Reported by @JaquM that the bug is not fixed. It's still not possible to use the feature as none of the selected cases is sent to SurvNet.

**Comment by MateStrysewske** [comment]
@markusmann-vg This has been part of a hotfix and therefore is released already. Please open a new issue if the bug still persists.
