### ISSUE TITLE
Dto deserialization handles primitives and collections as required attributes

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#5891]
### Bug Description
If property values are null in the serialization of Dto objects, deserialization may fail in the `sormas-rest` module. This is the case for, e.g., `PersonDto.hasCovidApp` or`PersonDto.covidCodeDelivered`. Properties in question seem to have either primitive types (here: `boolean`) or collection types.
This requires these properties to be present in the serialization even if having the default value (e.g., `false`) and not having been intentionally set.
The overhead of obsolete data to be transmitted is relevant in a low bandwidth setting (see #3522), hence the focus on `PersonDto` and `CaseDto`.

### Expected Behavior
Missing property values - unless annotated as `@Required` - should be handled gracefully, e.g., if `PersonDto.hasCovidApp` is missing in the serialization, the property should be instantiated with its default value, but deserialization should not fail in the `sormas-rest` module.

### System Details

* Device:
* SORMAS version: 1.61.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by StefanKock** [comment]
Discussed in refinement: 
- Make deserialisation graceful for primitive values.
- Make sure collections are always initialized: Best also on deserialisation, fallback: Change all collection getters to always return a fitting mutable collection.

**Comment by MartinWahnschaffe** [comment]
It looks like deserialization of json without those properties is not really a problem - at least sending a person with only first and last name to the rest interface works fine. @syntakker will check again why this did not work for him in the first place.

The changes made in the PR also don't affect deserialzation - only serialization. It would still be good to merge them, because they strip away unnecessary parts of the json. We should merge this after the next release.

**Comment by MartinWahnschaffe** [comment]
Suggestion: Since the bug turned out to have been caused by something else we can either discard this issue or use it to take care of stripping default values from the JSON to minimize it for performance. If we do this we should find a generic solution though and not annotate every single property.
