### ISSUE TITLE
Observer users should not have access to private data

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#594]
Restrict access to names, day & month of birth, address.
This includes grids, forms and also exports.
Find a generic solution for this.

The admin user is basically also an observer.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please figure out which fields should not be shown to observer users. Do this based on the data dictionary.

**Comment by bernardsilenou** [comment]
Here is the list of sensitive personal data:
First name
Last name 
Date of birth
All place of residence fields: address, state, LGA, community, etc
All contact information fields: Nickname, mothers name, fathers name, phone number, owner of phone, etc
This applies to both cases and contacts since they are all linked to a person entity.

**Comment by MartinWahnschaffeSymeda** [comment]
Ok. I'll move it to the short term roadmap.
