### ISSUE TITLE
[Climedo Integration] Cases & Contacts > Lost Symptom Journal Link

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6013]
### Bug Description

When migrating to SORMAS-X, the problem with cases and contacts (linked to case by conversion) was that ongoing symptom diaries lost their link.

This was noticeable as follows:

SORMAS: Button for symptom diary as you would expect with an active symptom diary. However, when I want to look at the diary I get the message that it does not exist in Climedo (on the Climedo website). When trying to cancel the external tracking, SORMAS gives an error message that this does not work.

Climedo: The person cannot be found using their personal ID (SORMAS-PID). However, if you search for name, date of birth, email address, etc., it will be found.

Conclusion: Both sides know that the other side exists, but are no longer linked to each other.

### Workaround Approach
Climedo can solve the problem by manually deleting it. On the SORMAS side, this is only possible through the link with the person ID by creating a new person, manually creating cases and contacts, entering new data or re-linking samples, etc. The damaged personal ID must then be deleted. This is a very high effort.

Delete the link to SORMAS on the Climedo website, and delete the link to Climedo on the SORMAS website.  With SORMAS, however, it seems that not everything is completely deleted, so that a new link does not work here (= link deactivated, but not equal to the status "not registered with Climedo").

It would therefore help to ensure on the SORMAS side that the link can be restored if it should be lost or not been established for other reasons.

### Expected Behavior

When trying to cancel the external follow-up on the SORMAS side, instead of / in addition to the error message, the link should be automatically deleted because Climedo apparently no longer has a diary. Since you can only reactivate the diary after manually deleting the data on Climedo’s side, it would not be created twice (sending the diary twice would be the lesser evil).

### System Details

* Device: PC
* SORMAS version: 1.59.2 (ITZ-Bund hosting)
* Android version/Browser: Firefox
* Server URL: -
* User Role: -

### Additional Information
[Bug Report Vorlage.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6741362/Bug.Report.Vorlage.docx) directly from GA.

**Comment by FredrikSchaeferVitagroup** [comment]
I do not agree with the expected behaviour described above. 

The `symptom journal status` indicates the status of a person regarding external journals. The above mentioned 'deletion of the link' in SORMAS would mean to update the symptom journal status (set it to DELETED). Doing so when the external journal just reported that the person could not be removed might help in this particular scenario, but does generally not seem to be a good approach. In other scenarios, it will lead to persons being marked as deleted in SORMAS, while personal data remains in the external journal.

I see two options here: 

1. Leave everything as is. When migrating to SORMAS-X, admins can manually set the symptom journal status to DELETED for person with this problem.
2. When an external journal reports that a person could not be deleted and the according error message is shows to the user, provide the option to force the deletion in SORMAS. An according message could be: `Do you want to force the cancellation in SORMAS? This would mark the person as deleted from the external journal in SORMAS, while there is a high probability of personal data still remaining in the external journal.` Choosing `YES` would the set the symptom journal status to deleted, no matter what the external journal reports. Choosing `NO` would just cancel the popup window and leave the symptom journal status untouched.

**Comment by FredrikSchaeferVitagroup** [comment]
@Candice-Louw What do you think about those options?

**Comment by Candice-Louw** [comment]
@FredrikSchaeferVitagroup - after discussion with the reporting GA and Climedo, option 2 is the preferred solution, please.

**Comment by FredrikSchaeferVitagroup** [comment]
That might be interesing for you as well @RobYed, but probably there's no action required on your side.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT
