### ISSUE TITLE
[Sormas2Sormas] Feature configuration for events, cases & contacts, Lab-Messages [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#6021]
### Situation Description

As some health departments might consider to use Sormas 2 Sormas for cases & contacts (including samples) only, we have to add a feature toggle, so that they can disable the functionality to share DEMIS Lab Messages and/or Events. This should be applied to bulk mode as well.

### Feature Description

Add a Feature configuration to enable/disable
1. cases & contacts with samples (default true)
2. Events (default false)
3. DEMIS Lab-Messages (default false)

**Comment by MateStrysewske** [comment]
@markusmann-vg I don't really get this issue. There already are feature configurations for all of these elements in place. @vidi42 If this is not about the already existing feature configurations, are you able to elaborate what exactly this issue is about?

**Comment by vidi42** [comment]
@MateStrysewske This is not about enabling/disabling the event surveillance or sample feature (for which there are already feature configurations). This is about enabling/disabling their sharing trough S2S since some health departments don't want to allow sharing of Lab messages or maybe samples and/or events, but they might still use those features.

So I imagine there will be 3 new feature configurations like:
`SORMAS_TO_SORMAS_SHARE_SAMPLES` (default :`true`)
`SORMAS_TO_SORMAS_SHARE_EVENTS` (default: `false`)
`SORMAS_TO_SORMAS_SHARE_LAB_MESSAGES` (default: `false`)

@markusmann-vg not sure if this is considered at the moment, but we should consider how to handle sharing samples to a system which has Samples or the Ability to share samples trough S2S disabled.

**Comment by leventegal-she** [comment]
> `SORMAS_TO_SORMAS_SHARE_SAMPLES` (**default** :`true`)

I don't think we need separate feature configuration for `samples` but for `cases & contacts` ("cases & contacts with samples" as Markus wrote)
 
> @leventegal-she do you know of any special handling when sharing a case with sample for example to a system which has Samples disabled?

There is no special handling for this case, I didn't yet think on that :).
It could happen for any type of entity we share because not only samples can be disabled on a system, but all the entities.

I would say to create a new ticket for handling share to systems where the features for the shared entities are disabled. Some kind of validation would be needed. But I think it is not so important if the people who configures S2S have the option to disable sharing entities not being used.

**Comment by vidi42** [comment]
This feature configurations won't affect the sync, they only show/hide the possibility to share entities. 
For example, if a case was already shared and then the `SORMAS_TO_SORMAS_SHARE_CASES_WITH_CONTACTS_AND_SAMPLES` feature is disabled, the case will still be synchronized when updated.

Also, the feature configurations introduced with this ticket are the following:
* `SORMAS_TO_SORMAS_SHARE_CASES_WITH_CONTACTS_AND_SAMPLES`
* `SORMAS_TO_SORMAS_SHARE_EVENTS`
* `SORMAS_TO_SORMAS_SHARE_LAB_MESSAGES`

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT on local environment.
