### ISSUE TITLE
Sormas cannot start because of "No enum constant de.symeda.sormas.api.feature.FeatureType.PERSON_DUPLICATE_CUSTOM_SEARCH"

### ISSUE THREAD

**Issue by FlickyFlack** [hzi-braunschweig/SORMAS-Project#6030]
### Bug Description
When updating the Survnet-Converter to Version 8.0.0 the Sormas- Application becomes unhealthy and unavailable.
The Stacktrace leads to an error in the 'FEATURECONFIGURATION'.
Logs attached.
[trace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6747320/trace.txt)

### Steps to Reproduce

1. Update Sormas to release candidate
2. Update the survnet-converter to Version 8.0.0
3. Restart Sormas in the update process

### Expected Behavior
Sormas should be running

### System Details

* Device:
* SORMAS version: 1.61.0
* Android version/Browser:
* Server URL: test-rki.sormas.netzlink.com
* User Role:

**Comment by vidi42** [comment]
@FlickyFlack The `test-rki.sormas.netzlink.com` machine seems to be deployed using https://github.com/hzi-braunschweig/SORMAS-Docker/tree/v2.21.0-rc1 which corresponds to SORMAS 1.60.0 , while the `PERSON_DUPLICATE_CUSTOM_SEARCH` feature configuration was introduced in [1.61.0](https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.61.0)

My assumption is that this machine had deployed at some point with 1.61.0 and then reverted back to 1.60.0 which usually leaves the `featureconfiguration` table filled with values that are not valid for older versions.

A simple cleanup in the `featureconfiguration` table and removing the `PERSON_DUPLICATE_CUSTOM_SEARCH` row would help fix this issue.

Close since this is an installation related ticket.
