### ISSUE TITLE
Add the info cards to the person view of each respective entities [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6052]
### Feature Description

Thus far, it is not easy to navigate to the person page of cases, contacts or event participants that also shows all connected entities. Users currently would have to navigate to the person directory and then search the person who's connected entity they have just been working on. This makes it quite pesky to for example check if a person had a previous infection.

### Proposed Change

To enhance usability and make it easier to see the persons related entities, add the related entities to the respective person tab of every entity person tab.
- [ ] Display the content of each related entity as seen on the person form also on each respective person tab and allow navigation through the edit icons
- [ ] In the case of the respective entity that the person is currently editing, hide the edit icon and instead highlight the entity that the user has opened. 

![Person tab entity associations](https://user-images.githubusercontent.com/70317594/173099380-b5d745a6-7bb9-42d3-b4d9-c525e83d7949.png)

### Additional Information

The cards should be extended as well when https://github.com/hzi-braunschweig/SORMAS-Project/issues/6054 gets implemented.

**Comment by kwa20** [comment]
@ChristopherRiedel @Johannes-Schmidt-GA-RT @Marko-ilmkreis @ThomasVitus For your information. Please feel free to provide feedback or mention more contributors who I forgot to include.

**Comment by Johannes-Schmidt-GA-RT** [comment]
The mockup looks very good. The Person tab should also be visible when I come out of the Case or Contact search.

**Comment by MateStrysewske** [comment]
@kwa20 I would suggest to rather add the lists to the case/contact/ep/... person tabs as well

**Comment by kwa20** [comment]
@MateStrysewske Do you think the tabs should then also include create buttons as described here? https://github.com/hzi-braunschweig/SORMAS-Project/issues/6053

**Comment by MateStrysewske** [comment]
Yes, I'd say so - and I don't see a real disadvantage. Having a "<- Person" link AND a "Case Person" tab at the same time, in contrast, could be confusing to users.

**Comment by Johannes-Schmidt-GA-RT** [comment]
My first intention last year was that we don't close the case when we switch to the person but just visually highlight the open case or contact. This way one person tab would be enough.

**Comment by OleWienke** [comment]
### Situation Description
Cumbersome process when creating a reinfection. Process so far: Reinfection creation requires specification of the exact reinfection date. This is not directly visible in the case entity. Thus, the person record must be opened in the person entity in order to track this. 
Process: 
1. Switch from the case entity to the person entity. 
2. Search in the person tab for the first case (in the person).
3. Copy UUID and open case in first case entity.
4. Return to the current case (suspected reinfection) and enter the date. 

### Feature Description
It would be useful to align the "person" templates in the person entity with the "case person" in the case entity. In this case, one could jump directly from the case to the person. Also very useful for other workflows.

### Additional Information


![Angleichen_Template_Person_Fallperson](https://user-images.githubusercontent.com/94985767/169262261-34ddb065-0a1c-47d3-abe4-9ef6d1058749.PNG)

**Comment by kwa20** [comment]
Updated the original description accordingly.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch and https://test-de1.sormas.netzlink.com/ + https://test-de2.sormas.netzlink.com/ for the S2S testing part - 1.79.0-SNAPSHOT(36dfdcd).
