### ISSUE TITLE
Add creation/link buttons to the person entity links [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6053]
### Situation Description

Thus far, entity cards on the person form merely show existing links to other entities but do not allow the creation of such. If persons already exist in the system, users would have to go through the usual creation processes and go through the person duplicate detection in order to create more entities for the existing person. 

related concept issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3560
### Feature Description

To enhance usability and make it easier to create entities for existing persons, add create and link buttons to respective cards.
- Add a 'new case' button the the cases card on the person form.
    - If pressed, open the case creation form in a pop-up and fill the person fields with the entries of the edited person. Make the person fields non-editable.
    - When pressing save, navigate to the case information form of the created case.

- Add a 'new contact' button to the contacts card on the person form.
    - If pressed, open the contact creation form in a pop-up and fill the person fields with the entries of the edited person. Make the person fields non-editable.
    - When pressing save, navigate to the contact information form of the created contact.

- Add a 'link event' button to the event card on the person form.
    - If pressed, open the 'pick or create event' pop-up as seen in cases or contacts and go through the same creation process, but exclude the edit person form since it seems unnecessary. Instead, add the other event participant fields to the 'new event participant' pop-up.

- Add links to immunizations and travel entries as above.

### Possible Alternatives

Leave the person related fields out of the creation forms since the entities are created out of a person anyway.
### Additional Information

<img width="624" alt="personFormCreateButtons" src="https://user-images.githubusercontent.com/70317594/124384258-aedd9e80-dcd0-11eb-9fc5-d47e35d44916.PNG">

**Comment by kwa20** [comment]
@ChristopherRiedel @Johannes-Schmidt-GA-RT @Marko-ilmkreis @ThomasVitus For your information. Please feel free to provide feedback or mention more contributors who I forgot to include.

**Comment by kwa20** [comment]
This issue should also include immunizations and travel entries.

**Comment by bernardsilenou** [comment]
@kwa20  I really like this issue, It what I was referring to in the other issue.  This view can serve as the default view for creating all entities liked to a person.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behaviors:
I. 'Pick or create case' is triggered twice when the person already has 1 case:
1. From the person page, create a Covid-19 case;
2. From the person page, click to 'Create new case' for the same person;
-> 'Pick or create case' pop-up is triggered;
3. In the pop-up, select 'Create new case';
4. Fill in the mandatory information and click 'Save' in the 'Create new case form';
-> 'Pick or create case' pop-up is triggered a second time.
Expected behavior: The 'Pick or create case' pop-up should be triggered only after the new case is created (after step 4) as that is when there is actual information for that case that can be checked and the duplicate detection has criteria to search for.

II: No warning message appears when the user tries to add the same person as event participant to the same event:
1. From the person page, click on 'Link event' and select an existing event;
2. Save the person as an event participant to that event;
3. Then again from the person page, click on 'Link event' and select the same event as in step 1;
-> the user can click to save the person as an event participant to the same event and no warning message appears to inform them that the person is already an event participant to that event.
Expected behavior: a warning message should appear, just as it does when the same steps are done from the case page for instance: 'The person is already linked as an event participant to the selected event'.

**Comment by adinaflorea9** [comment]
There is another finding for this ticket that would need to be addressed: when the Immunization module is reduced, the 'Create vaccine' button is not visible on the person page. As the 'New immunization' button was introduced with this ticket on the person page, I think that it is reasonable for vaccines to be able to be created directly from the person page when the reduced immunization module is on.

@syntakker @MateStrysewske

**Comment by adinaflorea9** [comment]
For part I of this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/6053#issuecomment-1342307560 please note that when the same steps are reproduced but for creating contacts - the duplicate detection or 'Pick or create contact' pop-up is triggered only after the user fills in the 'Create new contact' form and clicks on 'Save'. Therefore, I think it is reasonable that for cases the behavior be the same (the 'Pick or create case' pop-up to be triggered only after the information is filled in the 'Create new case' form and the user clicks 'Save').

@syntakker @MateStrysewske

**Comment by syntakker** [comment]
> There is another finding for this ticket that would need to be addressed: when the Immunization module is reduced, the 'Create vaccine' button is not visible on the person page. As the 'New immunization' button was introduced with this ticket on the person page, I think that it is reasonable for vaccines to be able to be created directly from the person page when the reduced immunization module is on.
> 
> @syntakker @MateStrysewske

This feature was implemented in #7105
The issue of creating vaccinations from the person entity was discussed here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7105#issuecomment-956309608
The decision was not to allow creation of vaccinations here.

> For part I of this comment [#6053 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/6053#issuecomment-1342307560) please note that when the same steps are reproduced but for creating contacts - the duplicate detection or 'Pick or create contact' pop-up is triggered only after the user fills in the 'Create new contact' form and clicks on 'Save'. Therefore, I think it is reasonable that for cases the behavior be the same (the 'Pick or create case' pop-up to be triggered only after the information is filled in the 'Create new case' form and the user clicks 'Save').
> 
> @syntakker @MateStrysewske

This has been fixed.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.78.0. 

Note: as noted in ticket #11245 new entities can be created by users for person outside their jurisdiction if they have the URL of the person page. As the current ticket did not specify how the create new entities buttons should or should not be displayed based on the jurisdiction of the user, this will be addressed and refined in that ticket.
