### ISSUE TITLE
Import error report should not return mixed delimiter types 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6128]
### Bug Description

When you download the import error report, the first column has ";" while all other columns has ",".
### Steps to Reproduce

1. Import facilities on a server with wrong facility type
2. download error report, first column has ; while others have ,

### Expected Behavior

The method to generate error template should use the same delimiter as the main file being imported.
### System Details

* Device:
* SORMAS version:1.60.3
* Android version/Browser:
* Server URL: Ivory coast test server:  https://test-inhp-ci.sormas.netzlink.com/sormas-ui/#!configuration/facilities
* User Role: Admin + national user

**Comment by bernardsilenou** [comment]
[sormas_import_error_report (21).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/6816469/sormas_import_error_report.21.csv)

**Comment by MateStrysewske** [comment]
@bernardsilenou The problem here is that you've used a different delimiter than the delimiter specified in the server properties. If you look closely, your file only has two columns; the first column specifying the error, and then a second column that contains a comma-separated list of all the columns because they were not correctly split. I.e. the file you uploaded for the import was not correctly formatted in the first place.

We will get rid of problems like these once we allow users to choose their own delimiter (#5459)
