### ISSUE TITLE
Exporting symptoms via database exports produce multiple tables in one files

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6245]
### Bug Description

When exporting symptoms in the database export section, additional database tables are included in the exported files.
### Steps to Reproduce

1. Open the database export section in the statistics menu
2. Select both symptoms check boxes
3. Export the data  

### Expected Behavior

Only the selected database table (symptoms) is contained in the exported file.
### Screenshots

<img width="508" alt="dbExportSymptoms" src="https://user-images.githubusercontent.com/70317594/127635452-9497c477-baf4-4353-b97d-d776fc4745ec.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 I don't see a problem based on your screenshots. You've selected two tables (the symptoms of clinical visits and the symptoms of contact visits), and it seems like you get exactly two output files, as expected? Please note that the csv files also contain the visit/clinical visit fields as a reference, and contain different data (=> all symptoms associated with all clinical visits in the system vs. all symptoms associated with all contact visits in the system).

**Comment by kwa20** [comment]
@MateStrysewske Is that desired behaviour? I'll add a file with the exports. The confusing part to me and apparently a problem for a user for further work with the files was the fact that two db tables are exported into one file.
[sormas_export_2021-07-30.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6907078/sormas_export_2021-07-30.zip)
I would've expected the "symptoms" tables to just contain the "symptoms" columns and then have references to either "clinical visits" or "visits" respectively as seen for example for "persons involved" and "events".

**Comment by MateStrysewske** [comment]
@kwa20 Yes, it is desired behaviour as it was specifically requested at some point in the past in order to be able to have a direct link to the visit/clinical visit in question in this file.

**Comment by FrankBouillon** [comment]
Hello, I am the user who opened the ticket.
Like MateStrysewske, I "expected the Symptoms tables to just contain the Symptoms columns an then have references to ... " the master tables (1-side auf the Relation). But, to say it again and again, even when nobody listened to me until know: THAT IS NOT THE CASE !!
In the Symptoms-Tables we don't find the external_id (ex. visit_id) but the whole Master-Table (with field "id" and so on).
Please have a look at it.
Greetings - Frank (GA Enzkreis)

**Comment by bernardsilenou** [comment]
@FrankBouillon 
We got an email about this issue from you and that is why I am commenting.
- From your last comment, your issue is not about the number of tables exported but that the external ID is missing on the exported data, is this right?
- `On the Symptoms-Tables we don't find the external_id (ex. visit_id)` I assume this is about symptoms of a case. If you need to know the symptoms of a particular visit of a case, then you can export the visit_symptoms data of a case and use the following variables to merge with other tables (visits:id, symptoms: id, visits: caze_id), I have attached a symptom export of cases having the variables. It wold be good you rename the id accordingly after export.
[visit_symptoms_6245.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/6968044/visit_symptoms_6245.csv)

- On the case_symptoms table, there is no link to specific visits, thus you would find no visit id there. The symptom of a case is the sum of ( presenting symptoms + all the visits) of the case.

- If this does not help, please add a comment here.
 Thanks

**Comment by FrankBouillon** [comment]
Bonsoir Bernard, merci pour ta reponse.
Yes, it is not about the number of tables.
It is neither about the case_symptoms tables because her in column GE (opendes with Excel) there is nothing, and that's quit ok like that. We just miss the case_id (or caze_id). That'a Little bug as well.
BUT you have to look at the visit_symptoms; Here in the columns from GE to GU (Excel-View) you'll find the table "visits". 
Same for clinical_visit_symptoms where you'll find the clinical_visit-Table in GE and so on.
PLEASE OPEN THE csv-Files and have a look. All that is a bug if you propose a "Datenbank-Export" like you do.
And if you don't understand - like the many Support-collegues I talked to before - PLEASE give me a call and I'll show you with TeamViewer. You're more in statistic, isn't it. Perhaps a database specialist like me might join us.
Have a nice evening - Bonne soirée cher Bernard
Frank

**Comment by bernardsilenou** [comment]
@FrankBouillon  Bonsoir
The naming caze_id is a naming error we realized late and decided not to correct it because many methods are using the same name. It is only on the case table.
I still do not understand the bug in the export. I would send you an invite for a call by email.
Thanks
