### ISSUE TITLE
contactPersonPhone / contactPersonEmail not visible anymore 

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#6263]
### Bug Description

After update to 1.61.2, the fields contactPersonPhone & contactPersonEmail are not displayed on the webapp anymore.
As these fields have been used to store important information, they should still be visible.

Another district here used this field as their primary way of storing contact information, so it is a bigger issue.

The information is still accessible via API, 

### Expected Behavior
- Both fields should be visible
- Alternatively: Transfer Information to personContactDetails and display on bottom of "person" page

### System Details

* SORMAS version: 1.61.2
* Android version/Browser: Any Browser

**Comment by MateStrysewske** [comment]
@ophcode The fields are still available, but only visible when a facility category and type have been selected because they're specifically supposed to document the contact details of the contact person in the facility. If these fields were displayed independent of that condition before, that was the actual bug.

**Comment by ophcode** [comment]
Ah thank you, that makes total sense.

To backtrace how the issue occured:

In contact and case import templates the fields person.phone and person.emailAddress are not included by default, instead
person.address.contactPersonPhone and person.address.contactPersonEmail are there - so some people have been resorting to using these fields for imports.
(Issue #5011 )
