### ISSUE TITLE
[Angular][Backend] Superordinate Event

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6309]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- On the Get By ID request we would need the  superordinateEvent?: EventReferenceDto (currently it returns UUID and caption), but we would also require eventTitle, eventStatus, creationDate

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by laurentiustanvitagroup** [comment]
As discussed in the daily, a discussion between @marius2301 and  @MateStrysewske is necessary as to understand if our approach is correct.

**Comment by laurentiustanvitagroup** [comment]
@marius2301 discussed with @MateStrysewske and there is the need to confirm our approach with @MartinWahnschaffe. @marius2301 will have the tech talk and inform us / start development (if confirmed).

**Comment by marius2301** [comment]
After the discussion with Martin, we concluded that we will define a separate class EventDetailedReferenceDto, which contains the missing details info and extends the EventReferenceDto. Also the method convertToDto in the class EventFacadeEjb will be overload by a method which will construct an EventDTO that contains the superordinateEvent   as EventDetailedReferenceDto instead of  EventReferenceDto. the method getEventByUuid(String uuid) in EventFacadeEjb will be modified  by adding a new boolean parameter, _detailedReference_,

**Comment by MartinWahnschaffe** [comment]
@marius2301 I'm not sure whether convertToDto should be overloaded or also receive a parameter - use whatever feels better when implementing it.

**Comment by MartinWahnschaffe** [comment]
@marius2301 I tried to find a way to change the generated swagger doc to look like this:

```
    EventDto:
      ...
      properties:
        ...
        superordinateEvent:
          oneOf:
            - $ref: '#/components/schemas/EventReferenceDto'
            - $ref: '#/components/schemas/EventDetailedReferenceDto'

```

Unfortunately it's not that easy. We would need to somehow document that the superordinateEvent can be of a different type.

* To do that we could use that swagger annotations, but we don't want to introduce that dependency into sormas-api.
* Swagger itself also seems to build oneOf based on the JsonView annotation, but that doesn't match our use case
* We could introduce a custom annotation and then use that to create the correct schema in the AttributeConverter class, but that's quite tricky / a lot of work and probably not worth it

Since all of this is out of scope, we should at least add a description to the ReST endpoint (see ApiRespone annotation).
