### ISSUE TITLE
Create immunization creation request in automation framework in order to prepare data for person populating script 

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6363]
This task is related to:
#5986

### Problem Description
For #5986 we need to be able to create immunizations in order to populate the test system with it

### Proposed Solution

Create needed pojo and service. Relevant fields are:

* disease
* person
* reportDate
* reportingUser
* responsibleRegion
* responsibleDistrict
* immunizationStatus
* meansOfImmunization
* immunizationManagementStatus
* startDate
* endDate
* externalId

**Comment by rdutu-vg** [comment]
Updated description to include externalId field as well in the request, if we don't add it, the response is 204

**Comment by rdutu-vg** [comment]
Test is done, updated the current script with the immunization part.
Have changed the design for the test to run 5 times.

![executionFromScript](https://user-images.githubusercontent.com/83643843/129753550-2b470a5d-fd7f-417d-9bfd-0a1c8b1e9cef.PNG)

**Comment by rdutu-vg** [comment]
Performed checks on resources used by test execution.

1. Running the script (1-10 loops) 
![resources during run](https://user-images.githubusercontent.com/83643843/130073943-6422e037-2d0c-46e0-a25e-7e1139c3bb5f.PNG)

2. Running the script (1-5 loops) in parallel (3 executions)
![issues](https://user-images.githubusercontent.com/83643843/130074054-508d59b2-4db9-45f6-89ac-00bdb0f2ce99.PNG)

Resources wise, the test is a big consumer, and based on the provided analysis we need to find the best approach to run it in order to get as many runs as possible to populate the database quicker.
