### ISSUE TITLE
Include Case classification filter in Merge duplicate directory

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#6394]
### Situation Description
There is no availability for users to easily merge similar case records with same case classification

### Feature Description
There should be a case classification filter to bring out similar case records with same case classification

**Comment by bernardsilenou** [comment]
@Iheanacho2027 
Do not understand what you need, can you explain more?
- merge duplicate id a function that users many variables: name of person, disease of case, region, etc just like the duplicate case detection.
- Do you mean adding case classification among the variables used for duplicate case detection?

**Comment by Iheanacho2027** [comment]
@bernardsilenou what i mean is this

![image](https://user-images.githubusercontent.com/50739609/129408965-f9d750d4-74d9-4f8d-8d54-4de8b3eabbcf.png)

Including case classification as part of the filtering variables to check for duplicates i.e. A user may want to see only duplicate confirmed case records

**Comment by bernardsilenou** [comment]
@Iheanacho2027  I think I understand you now.
Merge duplicate is used to clean your database, so you can not have attributes of the case (case classification) as a filter because it contradicts the idea of deduplication. If you do that, you would not identify all possible duplicates in your database.

You can also filter by disease, report date and jurisdiction. 
But what is the reason for requesting this need?

**Comment by Iheanacho2027** [comment]
@bernardsilenou so sorry for opening this ticket. Had some conflicting ideas in my head. Thanks
