### ISSUE TITLE
person directory filters on cases instead of all

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6507]
### Bug Description

When opening the person directory it filters automatically on cases instead of all:

![image](https://user-images.githubusercontent.com/74791118/130917883-9342d486-1d93-459a-9d26-1854cea233ca.png)

### Steps to Reproduce

1. open Sormas and person directory
2. filter is set on cases

### System Details

* SORMAS version: 1.62.3

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis This is an intentional change to improve the performance of the system. Filtering the person directory by "all" can potentially have a significant performance impact, and if users are "randomly" clicking on the Persons main menu entry, this will slow down the application for them. I think this was done in #6188 if I'm not mistaken.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske @kwa20 The German users are suffering very with this new feature. I'm still attending a meeting with admins and the overall meaning is that it should be filtered on all.
