### ISSUE TITLE
[SORMAS2SURVNET] deceased Status not set to alive

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6552]
When create a new Case and set the current stae of the person to alive, after tansfer to Survnet, the deceased status of the person will be: "unlevied"
![image](https://user-images.githubusercontent.com/79255722/131472824-881e015f-2a21-471f-9a66-8a03854086da.png)

### Expected Behavior
the deceased status in Survnet should be set to: "no".

currently not tested what happens when setting the state to "dead"

### System Details
Sormas 1.62.3
SURVNET 0.9.35.2

**Comment by herrling-LRA-KYF** [comment]
is there some feedback?
its important for us, after fixing we have to resend all cases.

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF As you can see in the sidebar, the issue has been added to the current sprint backlog and will be taken care of soon

**Comment by kwa20** [comment]
@herrling-LRA-KYF As of converter 8.2.0, the mapping has been changed to the 'outcome of case' rather than 'present condition' of the person. This is because the logic needs to consider reinfections with the same disease or multiple different cases to one person. If a person dies, one case might be responsible for the passing but outcomes of the cases will differ because the person can only die once.

Therefore, we currently map `caseOutcome` in the following way:

|SORMAS "outcome"|SurvNet "verstorben"|
|:-|:-|
|NO_OUTCOME|nicht erhoben|
|UNKNOWN|nicht ermittelbar|
|RECOVERED|Nein|
|DECEASED|Ja|

The mapping of NO_OUTCOME might not be ideal, because cases that have no known outcome yet might very well still be alive. Therefore, I'd suggest the following refinement that falls back onto the `presentCondition` if `NO_OUTCOME` is selected.

- If `NO_OUTCOME` is selected in `caseOutcome`, fall back onto the persons `presentCondition` in the following way:

|SORMAS caseOutcome| SORMAS presentCondition| SurvNet "verstorben"|
|:-|:-|:-|
|NO_OUTCOME|null|nicht erhoben|
|NO_OUTCOME|ALIVE|nein|
|NO_OUTCOME|DEAD|nicht ermittelbar|
|NO_OUTCOME|BURIED|nicht ermittelbar|
|NO_OUTCOME|UNKNOWN|nicht ermittelbar|

@herrling-LRA-KYF @JaquM Feel free to provide feedback on this.

**Comment by leventegal-she** [comment]
@herrling-LRA-KYF @JaquM @HolgerReiseVSys 

Can we implement the fallback solution @kwa20 suggested?

**Comment by herrling-LRA-KYF** [comment]
@leventegal-she @kwa20 
yes, this sounds good, but not perfect.
maybe you could map the following:

<html>
<body>


SORMAS caseOutcome | SORMAS presentCondition | SurvNet "verstorben"
-- | -- | --
NO_OUTCOME | null | nicht erhoben
NO_OUTCOME | ALIVE | nein
NO_OUTCOME | DEAD | ja
NO_OUTCOME | BURIED | ja
NO_OUTCOME | UNKNOWN | nicht ermittelbar


</body>
</html>
 
because in Survnet, the information is about the person, not the case.
Currently we are not sure how to handle a covid case, which get "shoot" (for example). So the person is dead, but not because of the infection.

**Comment by leventegal-she** [comment]
@kwa20 @HolgerReiseVSys 
Do you have any notes on the mapping suggested by @herrling-LRA-KYF? 
Do you agree to implement it?

**Comment by herrling-LRA-KYF** [comment]
@kwa20 
hm ok, i understand you. I only found one reinfection who dies in our database, but in survnet there are saved as two different persons.
I guess you could implement your solution at the moment to get a fast fix.

Maybe we could later discuss this.

**Comment by kwa20** [comment]
for reference: https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/236

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske  
is it fixed now?
Because you closed it and removed it from the sprint backlog.

**Comment by JaquM** [comment]
@herrling-LRA-KYF  yes, it is fixed in converter 8.4 (not yet productive)
