### ISSUE TITLE
[SORMAS2SURVNET] male pregnancy unlevied

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6670]
### Bug Description
When we have a male case with  pre-existing diseases, after sending to SURVNET, we have the status "unlevied" for pregnancy and postpartum.
![image](https://user-images.githubusercontent.com/79255722/132639773-f05146be-14ee-4a36-9539-75957ebcd6d3.png)

### Expected Behavior
For a male case, this should automatically set to "no".

### System Details
* SORMAS version: 1.62.3
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
Preferable to use:
`For a male case, this should automatically set to NULL.`  "No" is an information that the person is not pregnant, which for this case, the variable "pregnancy" does not applies.

**Comment by herrling-LRA-KYF** [comment]
is there a new status?
Or just on wait in the backlog?

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF @kwa20 @JaquM Setting the sex to "No" by default is technically and factually wrong. Men (as in their official sex by law) can technically become pregnant, but currently it's not possible to track that in SORMAS (which is something we want to change anyway, i.e. enable the pregnancy variable for all persons irrespective of their sex). Automatically setting the value to "No" in SurvNet would therefore mean that the value represented in Survnet does not represent the status in SORMAS (because right now, in SORMAS it's always "nicht erhoben").

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske  i understand that, but for us it is necessary to fix that in a fast way.

What about enable the pregnancy variable also for man and set it default to "no" ?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- My previous comment is in agreement with yours https://github.com/hzi-braunschweig/SORMAS-Project/issues/6670#issuecomment-923939959, ie set default to NULL for all sex categories.
- @herrling-LRA-KYF  As @MateStrysewske  already described, it would not be good to set sex to NO for males. When analyzing the data after export from sormas, you can then reclassify as you wish.

**Comment by JaquM** [comment]
@bernardsilenou @herrling-LRA-KYF 
we'll prioritize the #5418 and add it to the converter

**Comment by JaquM-HZI** [comment]
I'll close this Issue, cause we solved the problem with implementing [#5918 ](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5418)
