### ISSUE TITLE
[S2S] Samples have to be send when ownership is handed over

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6684]
### Feature Description

Sharing cases and handing over the ownership
### Problem Description

Thus far, users are not obligated to share samples when handing over cases. This is very problematic because the samples' pathogen tests are accounted for when calculating the case classification. This cannot differ depending between instances because it could break the reporting process and miss-align important data. 
### Proposed Change

- When a case is being handed over, the samples always have to be selected as well to make sure that all relevant data is shared.
- As long as "Hand over the ownership" is selected, "Share samples" should not be able to be deselected 
### Additional Information

<img width="283" alt="HandOverCases" src="https://user-images.githubusercontent.com/70317594/132877016-8cf8dcff-37a6-40b6-b5d5-36734efc95a8.PNG">

**Comment by vidi42** [comment]
@kwa20 should this force sending of samples when ownership is selected also apply to sharing events witch event participants, or it's only for cases?

**Comment by bernardsilenou** [comment]
@vidi42  I respond in place of @kwa20 
1. For cases, share samples when case is shared
2. For events, share ep when the event is shared, BUT we  would control for the jurisdiction of the ep and that of the jurisdiction receiving the ep. Ie we maintain the rights while sharing.
  2.1 if the jurisdictions (ep and receiving jurisdiction) are the same, or  if jurisdiction of ep is missing and receiving jurisdiction is the same as that of the event, then  full access to events and ep
  2.2 else only read assess to ep

**Comment by vidi42** [comment]
@bernardsilenou sorry, but I cannot really understand the answer.

At the moment the jurisdiction doesn't have any influence over the options with which the user is presented when sharing.
So the user is free to choose if the ownership is handed over or not.

Since the ticket only specified to automatically share samples when handing ownership of a case, my question was if we should also automatically share samples when sharing an event with participants and handing ownership of it.

Anyway, this ticket was only concerning cases so I suggest that if further changes have to be done for events as well, we do this in a separate ticket.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de1.sormas.netzlink.com and test-de2.sormas.netzlink.com
