### ISSUE TITLE
Hospitalization caption refinements

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6716]
### Feature Description

Cases > Hospitalizations
### Problem Description

Users have difficulty understanding the process of the hospitalizations in cases. This is also due to the fact that when on the hospitalization tab, the association to the place of stay is not apparent. Further, visits to hospitals cannot specifically be counted as hospitalizations and thus should be excluded from the wording.
### Proposed Change

- Rename the caption "Hospitalization data" to "Current hospitalization"
- Add another caption above the previous hospitalizations section called "Previous hospitalizations"
- Rename "Date of visit or admission" to "Date of admission"
- Rename "Was the patient hospitalized or did he/she visit a health clinic previously for this illness?" to "Was the patient hospitalized previously for this illness?"
### Additional Information

@MateStrysewske @markusmann-vg @HolgerReiseVSys @Juliane-D FYI

**Comment by bernardsilenou** [comment]
@kwa20 
This is a tricky one:
- This point is a good one `Add another caption above the previous hospitalizations section called "Previous hospitalizations"`

- It was a decision after having a design thinking workshop with colleagues from Nigaria to call it "visits/hopitalization". 
- The reason is because  the definition of hospitalization is not fixed, ie a case person can go to hospital, stay for some hours under monitoring and  discharged on the same day (they called this visits), goes to hospital for consultation + testing and returned home immediately after consultation ( also a visits) or stayed in hospitals for >= 24 hrs (hospitalization).
- For many disease (like malaria, measles, ..), cases often go to health facility and go back home after consultation.
- The decision was to capture all the scenarios as one hospitalization entity, users can then decide what is "hospitalization to them" by comparing date of visit/admission to date of discharge.
- From this specification, it shows that visits are not included, this would not be good for other users. We can discuss this later maybe improve the ui desing the make it clear that hospitalization is sormas means the person had a consultation/examination (diagnosis + treatment (optimal) ) at a health facility, no matter the duration of stay at health facility.

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 I would then suggest to only change the German caption, but leave the default caption as it is. Is that fine for you?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- To me translation is OK, we can additional add a comment to the translation on crowdin so that no user can back-translate it, thinking that is was not a deliberate translation. 
- Is it possible to block further translations on crowdin? if possible, then we can also block it after translation.
- @kay or @JaquM would give the final say

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT
