### ISSUE TITLE
Add task status "Progress" [0.5]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6748]
### Problem Description

Currently the tasks can only have the status pending, done, removed, not executable. It cannot documented if an officer started to work on the task as the is a status "in progress" is missing.

### Proposed Change

Please add this status to the tasks.
![image](https://user-images.githubusercontent.com/74791118/134116977-245eb83c-3ed0-4f7f-88ac-d115dcec662b.png)

**Comment by kwa20** [comment]
Add this value also to the task status filter

**Comment by FredrikSchaeferVitagroup** [comment]
Just to avoid misunderstandings, here's a list of things that were not touched by the specification of this ticket and therefore remain as is:

- When the jurisdiction or a user gets removed as surveillance and contact officer, associated `PENDING` tasks are automatically reassigned. This will not happen for `IN_PROGRESS` tasks. ([UserFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java#L766))
- When status of a case is set to something other than `PENDING`, if the status is set to `DONE`, the associated `PENDING` tasks statusses are all automatically updated to `DONE`. Otherwise to `REMOVED`. `IN_PROGRESS` tasks will not be updated. ([CaseFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java#L3129))
- In the automatic task generation, contacts with `PENDING` `FOLLOW_UP` are skipped. `IN_PROGRESS` tasks have no effect here. ([ContactFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java#L1741))
-  In the automatic task generation, when there is a `PENDING` task for the `WEEKLY_REPORT_GENERATION` regarding the last week, no new task is automatically generated. It will be generated for `IN_PROGRESS` tasks, though. ([WeeklyReportFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/report/WeeklyReportFacadeEjb.java#L367))

@kwa20 @Marko-ilmkreis Please confirm this, or add specification. Things that are breaking functionalities when left untouched should be done in this ticket. Others can also be moved to other tickets. Please note that any additional specification in this ticket will probably increase its estimation. Please also note that there is feature freeze today, so this ticket might not make it into 1.75.0.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup 
> Just to avoid misunderstandings, here's a list of things that were not touched by the specification of this ticket and therefore remain as is:
> 
>-  When the jurisdiction or a user gets removed as surveillance and contact officer, associated `PENDING` tasks are automatically reassigned. This will not happen for `IN_PROGRESS` tasks. ([UserFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java#L766))

This should be fine since reassigning a task to another user while it is in progress would be quite confusing.
> 
>-  When status of a case is set to something other than `PENDING`, if the status is set to `DONE`, the associated `PENDING` tasks statusses are all automatically updated to `DONE`. Otherwise to `REMOVED`. `IN_PROGRESS` tasks will not be updated. ([CaseFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java#L3129))

This should also be fine for the same reason. If a task is in progress, it would be confusing to change the status seemingly inexplicably for the user. 
> 
>- In the automatic task generation, contacts with `PENDING` `FOLLOW_UP` are skipped. `IN_PROGRESS` tasks have no effect here. ([ContactFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java#L1741))

I'm not exactly sure about the consequences here. Does that mean that if an `IN_PROGRESS` `CONTACT_FOLLOW_UP` task already exists for the same day, another one would be created regardless? If so, we should skip those tasks as well.
> 
>- In the automatic task generation, when there is a `PENDING` task for the `WEEKLY_REPORT_GENERATION` regarding the last week, no new task is automatically generated. It will be generated for `IN_PROGRESS` tasks, though. ([WeeklyReportFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/be232d6909a8b265d522765941ac3ed7ffe9ba51/sormas-backend/src/main/java/de/symeda/sormas/backend/report/WeeklyReportFacadeEjb.java#L367))
> 
It should also not be generated when there is a task `IN_PROGRESS` for weekly report of last week.

**Comment by FredrikSchaeferVitagroup** [comment]
Should be testable on any test system, once deployed.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on test instances with`Sormas Version: 1.75.0-SNAPSHOT (b1baa08)

**Comment by kwa20** [comment]
I tested this feature on test-de2.sormas.netzlink.com, 1.75.0-SNAPSHOT (b1baa08) with TASK_GENERATION* featureconfiugrations enabled and Admin + National User roles and noticed the following:

- When a case is created and contains a case investigation task, a new task of the same type is created whenever changing the existing ones status to `IN_PROGRESS` and saving the case.
    - If this task type is se to in progress, new case investigation tasks should not be created upon saving the case because a user is already working on the existing one.
    - This can also be done for multiple tasks that get set to `IN_PROGRESS`

![additionalCaseInvestigationTask](https://user-images.githubusercontent.com/70317594/182787675-ddf6e0d5-7f47-4ef9-b456-bd8f583ac6b5.gif)

This could lead to many duplicate tasks and get confusing to users. Thus, re-opening the ticket.

**Comment by markusmann-vg** [comment]
closed, as the requested change will be covered with https://github.com/hzi-braunschweig/SORMAS-Project/issues/10053

**Comment by AndyBakcsy-she** [comment]
Closing issue as fixed and the latest changes will be tracked with the new ticket
