### ISSUE TITLE
Change of Isolation/Quarantine should be documented

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#6782]
### Situation Description

If the end of quarantine (case/contact) the previous date should be visible and there should be an option to comment, why this change was made.

### Feature Description

- if the user changes the end of quarantine, show the previous date behind the checkbox
- make this date non editable
- add a comment field below as a free text field, which just shows up, if the quarantine was changed
- add this for cases and contacts, for extended and reduced quarantine period

![Quarantäne änderungen](https://user-images.githubusercontent.com/78568406/134347610-f6567187-6f3a-41ef-85fb-7e65abb00864.JPG)
### Additional Information

@maxiheyner and @kwa20 fyi

**Comment by bernardsilenou** [comment]
@JaquM 
- Since end of quarantine is dependent on end of followup, can users not use the followup comment field?
- Often, when users extend quarantine, they also extend followup + add a comment why
- Another point is if users extend quarantine 3 times, what is then the previous quarantine end?

**Comment by JaquM** [comment]
@bernardsilenou
Since the current recommendation in Germany is to adjust the quarantine if necessary but to continue follow up, these are two different dates that are handled differently. 
If there are many changes, just the last date should be shown.

**Comment by bernardsilenou** [comment]
@JaquM The point i am suggesting that we consider is how the previous quarantine date would be related to end of followup.
- There is a possibility that when the followup is extended, then quarantine end is matched. But the the specification of this issue says that we should not override previous quarantine.
- ie what should happen to previous quarantine date if is differs from the expected (quarantine/ followup), should we override the it?

**Comment by JaquM** [comment]
@bernardsilenou we should not overwrite any data, but allow them to be two different data

**Comment by bernardsilenou** [comment]
@JaquM @kwa20  @ChristopherRiedel 
The logic to have  quarantine to be dependent on  followup was added because of a  request from the users.
Are you sure that all users would be fine with having them independent? I am still not clear with this specification. I would try to explain why.

In the current solution:
1. Quarantine end == expected end of followup == onset date + 14/10 (this is a fixed date and cannot be changed). If both are independent data, then this logic would be removed from the system, thus quarantine end would be NULL as default and users have to specify it, this was the first solution. Users often do not know the expected end of quarantine, one reason for mapping it to  expected end of followup.
2. Here is my main point:
If a user extend quarantine end OR extend followup + user validation for system to extend quarantine  end also, then the previous quarantine end mentioned in this issue would always be the same as the expected followup until date, since the previous end of quarantine cannot be overwritten.

3. What about just telling the users to use the expected followup date as previous quarantine end date. If this is not a solution, then another option is to add a configuration for not linking quarantine and followup because many user would prefer the current solution.
What do you think please?

**Comment by kwa20** [comment]
@bernardsilenou The logic of quarantine end and follow-up date will not be affected and stay the same. This issue is merely about visualizing the previous quarantine date which was changed. Currently, only the field 'Quarantine period extended?'/'Quarantine period reduced?' is shown on the UI but users don't know the previous quarantine end date which was changed. 

In summary, this field merely displays history information of the quarantine end date field

**Comment by bernardsilenou** [comment]
@kwa20 @JaquM  
I think I had a comprehension issue with the phrase `make this date non editable`
- This means this date can only be overwritten/ edited by changing the quarantine end date, right ? then all is fine.
- My previously understood was that the date should be fixed, irrespective of the number of times that the quarantine is changed.
- Thanks

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
