### ISSUE TITLE
Repeated Case pushes to the API fail.

### ISSUE THREAD

**Issue by keppla** [hzi-braunschweig/SORMAS-Project#6792]
### Bug Description

Repeated calls to the API endpoint /cases/push fail, i.e. answer `["OK"]` and `["ERROR"]` when they should just update.

### Steps to Reproduce

1. make sure that district, region, user and region exist with the used UUIDs.
2. set BASEURL, USER, PASSWORD environment variables to match your testing system
3. execute this curl commando twice

```
curl -X POST "$BASEURL/cases/push" -u $USER:$PASSWORD -H 'Content-Type: application/json' -d @- <<JSON
[{
  "uuid": "a6f73148-af6a-424c-93c6-33d285d0f8b3",
  "healthFacility": {
    "uuid": "SORMAS-CONSTID-ISNONE-FACILITY"
  },
  "facilityType": "OTHER_ACCOMMODATION",
  "person": {
    "uuid": "664c68c4-f943-4c8a-a2f0-883f7c8bae12"
  },
  "responsibleDistrict": {
    "uuid": "SO7H2Z-N6TLP5-TMDGHM-SJH6KIVY"
  },
  "district": {
    "uuid": "SO7H2Z-N6TLP5-TMDGHM-SJH6KIVY"
  },
  "responsibleRegion": {
    "uuid": "XEQZSV-MWCSUW-GEG4NN-GK57CHMI"
  },
  "region": {
    "uuid": "XEQZSV-MWCSUW-GEG4NN-GK57CHMI"
  },
  "caseClassification": "CONFIRMED",
  "disease": "CORONAVIRUS",
  "investigationStatus": "PENDING",
  "reportDate": "2021-09-23",
  "reportingUser": {
    "uuid": "X47T77-BUFZK6-NJNFXV-HA3V2GZY"
  },
  "outcome": "UNKNOWN",
  "pseudonymized": false
}]
JSON
```

### Expected Behavior
both times, the server answers with `["OK"]` and updates the case

### System Details
* Device: Some cloud linux server, running Ubuntu/Docker
* SORMAS version: 1.62.3
* Android version/Browser: n/a
* Server URL: https://sormas.recklinghausen.triplet.gmbh/sormas-ui (private instance hosted via docker)
* User Role: rest user

**Comment by MateStrysewske** [comment]
@keppla Do you have access to the server logs and could attach the log outputs that are produced when you perform the API call? There should be an exception message in there.

**Comment by keppla** [comment]
Yes, i do. I reproduce them, please stand by :)

**Comment by keppla** [comment]
This seems to be the error for the relevant call
[log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7217030/log.txt)

**Comment by MateStrysewske** [comment]
@keppla Looks like the sub-entities of cases are missing in the request, i.e. epiData, hospitalization, symptoms, therapy, clinicalCourse, maternalHistory, and portHealthInfo. You might not need to specify all of them in order to successfully save the case, but you might potentially encounter issues in the UI later when they're missing.

At least epiData and hospitalization are definitely needed when saving the case because they are used during the pseudonymization process which is why your request is failing.

**Comment by keppla** [comment]
Thanks for the reply!
I'll try adding the relevant fields.
The fields you mentioned are not classified as neccessary in the API docs. Is there a better source?
Also, i thought deactivated pseudonymization via `"pseudonymized': false`, what did i do wrong?

**Comment by MateStrysewske** [comment]
@keppla No, unfortunately not - we might have to add the annotation to these fields which hasn't happened yet because cases created in the web or mobile app automatically have these entities (and the ReST API was originally designed to be used by the mobile app to push and pull cases to and from the web backend).

Concerning the pseudonymized attribute, that's basically an informative attribute only. It doesn't really change anything about the data, it's used to tell the mobile app that the data is pseudonymized. It doesn't have a practical use if you push data to the system.

**Comment by keppla** [comment]
Thanks!

**Comment by JonasCir** [comment]
Hi @keppla ,

I think you referred to the `openApi` description when you talked about "API docs" right? In case something is wrong there, please open a new issue and state what dto you wanted to push and what entities were expected/what entities you needed to add in order to make the request work. We will take care of it and add the necessary "required" annotations in the code :) 

(Although this might be a great first PR and your chance to contribute to this project :wink: )
