### ISSUE TITLE
Case classification and reference definition gets incorrectly calculated

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6823]
### Bug Description

The case classification 'Confirmed with no symptoms' gets wrongfully calculated via the automatic and manually triggered calculation.

This also affects the reference definition calculation in the same way.
### Steps to Reproduce

1. Create a case
2. Add a positive sample and pathogen test for the disease with test type PCR
3. Check the case classification calculation ( should be 'Confirmed with unknown symptoms')
4. Open the symptoms tab and select the symptoms in the way shown in figure 1.
5. Check the case classification again

### Expected Behavior

In these constellations the classification should result in 'Confirmed with no systems' and the reference definition to 'fulfilled'.

Specifically, the above result should appear:
- If any of the symptoms set to `YES` in figure 1 are set to `YES`, `NO` or `UNKNOWN` in any constellation
AND 
- at least one of the symptoms set to `NO` in figure 1 is set to `NO` BUT none of them is set to `YES`
### Screenshots

Figure 1.:
<img width="388" alt="caseClassificationD" src="https://user-images.githubusercontent.com/70317594/135114763-3544b220-eaf6-43e2-86e4-d9c8ce47d488.PNG">

result
<img width="556" alt="caseClassificationD2" src="https://user-images.githubusercontent.com/70317594/135114889-085d4536-6102-4bc3-bd8e-9020c6add46a.PNG">

### System Details

* Device:
* SORMAS version: 1.63.1
* Android version/Browser: firefox
* Server URL: int-sormas-x.sormas.netzlink.com
* User Role: admin, national user

**Comment by syntakker** [comment]
Technically, this behaviour is consistent with the case classification rules, but probably not intended:
- "confirmed classification" does not apply, since none of the listed symptoms is present
- "confirmed classification - No symptoms" does not apply, since ,e.g., "Rapid breathing" is set to YES
- "confirmed classification - Unknown symptoms" does not apply, since a number of listed symptoms is set to either YES or NO

I assume the two symptom lists used in the definition of "confirmed ..." should be the same, or the **ones occuring in the second list only** should be treated in a way that does not prevent the case form being classified as "confirmed -no/unkown symptoms" without being classified as "confirmed"

from "confirmed":
- Pneumonia (clinical or radiologic)
- Difficulty breathing/Dyspnea
- Cough
- Runny nose
- Respiratory disease requiring ventilation
- Acute respiratory distress syndrome
- New loss of taste
- New loss of smell
- Sore throat/pharyngitis

from "confirmed - no/unkown symptoms":
- **Chills or sweats**
- Cough
- **Diarrhea**
- Difficulty breathing/Dyspnea
- **Fever; Headache**
- **Muscle pain**
- **Nausea**
- **Other clinical symptoms**
- **Rapid breathing**
- Runny nose
- Sore throat/pharyngitis
- Acute respiratory distress syndrome
- Pneumonia (clinical or radiologic)
- New loss of taste
- New loss of smell
- Respiratory disease requiring ventilation
- **Feeling ill**
- **Fast heart rate (Tachycardia)**
- **Oxygen saturation < 94 %**
- **Shivering**

@kwa20 feedback is needed here, classification rules should be updated.

![image](https://user-images.githubusercontent.com/5616564/135602434-33c81934-7211-4668-944a-8d10b32ec47e.png)

**Comment by kwa20** [comment]
@syntakker Sorry for the confusion. The English string might not be a good representation of the classification meaning. "Confirmed no symptoms" describes a case whose potential symptoms do not conform to the clinical picture of the disease but it doesn't mean that the case has to be asymptomatic.

Therefore, if any of the symptoms in the first list are set to NO and none to YES, independent of how the other symptoms are set, it should result in "Confirmed no symptoms" if there is a pathogen test fulfilling the requirement.

The problem now is that if any of the symptoms in the second list is set to YES, the classification is set to "Not yet classified" instead of "Confirmed no symptoms"

**Comment by syntakker** [comment]
@kwa20 then there's still a similar inconsistency for "Confirmed unknown symptoms" if you only set one symptom from the longer list (e.g., "Rapid breathing") to YES. The definition for "Confirmed unknown symptoms" does not apply then, nor does "Confirmed no symptoms" (since no symptom is NO).

**Comment by kwa20** [comment]
@syntakker Oh I see, this means that if at least one of the symptoms of the longer list is set to YES and any of the symptoms of the shorter list is anything BUT YES, the classification should be "Confirmed no symptoms" and the reference definition fulfilled if a respective positive test result is given.

**Comment by syntakker** [comment]
@kwa so the problem boils down to the divergence of **typical** symptoms (the longer list) and **atypical** symptoms (the longer list without symptoms from the shorter list).
In the current definitions, neither "no symptoms" nor "unknown symptoms" apply if one of the **atypical** symptoms is set to YES. This means, if none of the **typical** symptoms is YES, there is no applicable case classification for now.
Are you sure the difference between both symptoms lists is intended? To my understanding, "Runny nose" does not seem more COVID-19 specific than "Oxygen saturation < 94 %".

However, I see the following solutions:
1. use the same list of symptoms in all places
2. ignore any **atypical** symptom set to YES for "no symptoms" and / or "unknown symptoms" (i.e., adapt the "NONE OF" part of both classifications)
3. introduce a new classification for any **atypical** symptom being YES (or rather: a classification that covers the current gaps)

**Comment by kwa20** [comment]
@syntakker A while back, new german specific case classifications have been added through https://github.com/hzi-braunschweig/SORMAS-Project/issues/2230. However, the english string for category 'D.', i.e. 'Confirmed no symptoms', is not equal to its required meaning (defined by RKI). Technically, category 'D.' describes an unfulfilled clinical picture of Covid which does not have to mean that the case is necessarily asymptomatic. I totally get your confusion about 'Runny nose' and 'Oxygen saturation < 94%' though. However, the RKI does not collect data for oxygen saturation for some reason and a different calculation would lead to differences in Sormas and the reporting tool.

Since the classifications 'Confirmed no symptoms' and 'Confirmed unknown symptoms' are only present on german systems, we might also be able to adjust their original strings to be more conform to the required meaning. Since this might have other implications I'm not a big fan of this solution though.

Therefore, I'd suggest to go for solution 2.
