### ISSUE TITLE
Ignore person validation when picking an existing person in imports

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6866]
### Situation Description

The duplicate check is triggered when contacts are imported. If the person to be imported is found and the person in SORMAS is selected during the duplicate check (i.e. no new person is created), then it is checked again whether the primary e-mail address of the already existing person is a valid e-mail address. However, since this was possibly recorded when there was no such validation, the existing e-mail address may be invalid and the import of the contact person will fail.

This causes problems in productive operation, since such cases often occur and manual cleaning would involve a very large (unmanageable) effort.

### Feature Description

Validation of existing data can be configured on / off.

### Possible Alternatives

+ During the import, the user is made aware of the violation of the validation and, depending on the situation, decides whether they want to skip the import of this contact (i.e. want to clean it up first) or whether they want to import the contact despite the invalid data
or
+ All contacts are imported and at the end of the import a list with all invalid data is output. This gives the user the opportunity to decide afterwards whether they want to clean up the data or not.

### Additional Information

CH ref: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/214

### Development Specifications
* When importing data that requires the user to select an existing or create a new person, if the user selects an existing person and does not choose to overwrite existing data (only possible for cases), and the data is saved, skip the person validation (because it's possible that the existing person will fail the validation, but the user does not have any option to correct the data at this point).

**Comment by kwa20** [comment]
@Candice-Louw @ClaudeMarksteinerCSI I guess we're talking about the csv-import? I don't really like the idea of forcefully importing invalid data which could cause some problems elsewhere after they have been imported because that's usually what should be prevented with these validations.
May an alternative would be to import them so they can be valid if they're not correct. Specifically, if an imported `contactInformation` for `PersonContactDetailType` `PHONE` or `EMAIL` does not pass the validation, they get imported as type `OTHER` instead and the `additionalInformation` field is filled with the following system information:

_"[System] the entered contact information does not pass the validation of the other contact details types. It was therefore imported as type other"_

we might want to still produce an error report informing the user about which persons were changed exactly for them to check and potentially adjust the entries.

**Comment by MateStrysewske** [comment]
@Candice-Louw @kwa20 @ClaudeMarksteinerCSI I would prefer a much simpler solution that disables the person validation when an existing person is selected (because the user has absolutely no way of correcting the data in this situation anyway). Would that be fine for you as well?

**Comment by ClaudeMarksteinerCSI** [comment]
This solution sounds good for us as well (Matt Lenke, Andreas Münst and me). Go for it. 🥇
