### ISSUE TITLE
Move health conditions from clinical course to the case [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6879]
### Feature Description

Cases > Clinical Management > Therapy / Clinical Course / pre-existing conditions
### Problem Description

Currently, the clinical management module is quite dispersed across the case entity and user roles and rights are not clearly separated for this module. E.g. pre-existing conditions, in contrast to the contact entity, are present in the clinical course of the case. This tab is only accessible for clinicians or case officers but other users should also be able to enter pre-existing conditions.
### Proposed Change

- [ ]  Move the pre-existing conditions for cases to the case information tab above the additional medical information ( as seen for contacts)
- [ ] Document the following upon completion of this change:
        - Data migration from existing to new values (if applicable)
        - Changes to database structure/tables (if applicable)
        - Changes in API endpoints (if applicable)

### Additional Information

![Frame 63](https://user-images.githubusercontent.com/70317594/149362641-201bd31b-7be8-4717-8b8b-40f8e18c200b.png)

### Development Specifications
* Move the health conditions from the clinical course entities and DTO to the case entities and DTO
* In the web database, add a new column to the case table, fill it with the health conditions of the clinical course that belongs to each case, and drop the health conditions column from the clinical course table (not the history table)
* In the mobile database, do the same, but do not drop the health conditions column from the clinical course table (because SQLite doesn't support dropping columns); instead mark the field as deprecated in the entity class
* Update the change date filters accordingly
* In the web app, move the health conditions from the clinical course tab to the case tab (above the reception dates of paper form)
* In the mobile app, health conditions already have their individual tab, but there will likely be some references that need to be updated
* Document the following upon completion in this issue:
        - Data migration from existing to new values (if applicable)
        - Changes to database structure/tables (if applicable)
        - Changes in API endpoints (if applicable)

**Comment by bernardsilenou** [comment]
@kwa20 
- It would be good to hear from the Nigerian team also if merging both tabs are fine with them.
- Migrating pre-existing condition to case form is a good suggestion, the only doubt that I have if if we should merge both tabs: therapy and clinical course. The reason is that when we merge, the final form would be long and users need to scroll down to find what they need to edit.

**Comment by kwa20** [comment]
@bernardsilenou Feel free to tag someone who could provide feedback, that would be quite helpful.

**Comment by bernardsilenou** [comment]
@Chinedar @foyiri  Please can you comment on this issue?

**Comment by bernardsilenou** [comment]
@faatihi @Chinedar @foyiri 
Please can you give your feedback on this specification?

**Comment by bernardsilenou** [comment]
- We May need to split this issue in two sub issues. We can maintain  this issue to address point 1 only. `Move the pre-existing conditions for cases to the case information tab above the additional medical information ( as seen for contacts)`. If none of the people tagged here object, then we  can develop as specified for all instances.
- We would add another issue for point 2 in January 2022.

**Comment by bernardsilenou** [comment]
@carolinverset @Candice-Louw 
FYI

**Comment by Candice-Louw** [comment]
Programming documentation to be delivered on completion of the issue (as a comment on this issue, or in the release notes):
+ Data migration from existing to new values (if applicable)
+ Changes to database structure/tables (if applicable)
+ Changes in API endpoints (if applicable)

**Comment by kwa20** [comment]
I've split the initial description into 2 issues (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/7640)

@MateStrysewske I guess this issue then has to be re-estimated.

**Comment by Chinedar** [comment]
Yes please, I believe we can move the pre-existing condition to the case information tab.

**Comment by BarnaBartha** [comment]
1.  Data migration from existing to new values (if applicable)
- health conditions of each clinical course have been moved to the cases
2. Changes to database structure/tables (if applicable)
- cases now reference the health conditions directly, the relation between clinical course - health conditions has been removed
3. Changes in API endpoints:
- the following endpoints return now with the case data also the health conditions data
/cases/all/{since}
/cases/all/{since}/{size}/{lastSynchronizedUuid}
/cases/query
/cases/query/persons
/cases/getduplicates
/cases/getduplicates/{reportDateThreshold}
/cases/{uuid}

**Comment by bernardsilenou** [comment]
@MateStrysewske @BarnaBartha 
Sorry for responding late to https://github.com/hzi-braunschweig/SORMAS-Project/issues/6879#issuecomment-1034776411 
Yes please, since the web is the reference app, it would be good to always map the mobile app design to it.
Thanks

**Comment by MateStrysewske** [comment]
@bernardsilenou The question is where it should be moved to though. Please note that the health conditions are a separate entity and thus are not part of the case data form in the mobile app. They're an independent tab. Where should this tab be positioned?

**Comment by bernardsilenou** [comment]
@MateStrysewske  Ohh sorry, I hope I understand now.
- We can put it between symptom information and epidemiological info, ie ... hospitalization --> symptoms --> premedical condition --> epidemiological info ...
- Is this fine with you also?

**Comment by bernardsilenou** [comment]
> @BarnaBartha can we have the pregnancy postpartum part directly under the other pre-existing conditions, please?

- We need to hear from @JaquM  also before confirming, but this is my suggestion, please:
It is likely that the users document pregnancy than pre-existing conditions, and adding it under the pre-existing conditions table may cause users to miss it since it's hidden.
- Suggested order: additional medical infromation --> pre-existing conditions --> followup 
- This is not the same order as in contacts, this should be another issue I suppose.

**Comment by JaquM** [comment]
@bernardsilenou @BarnaBartha so maybe we just leave it as it was described in de mockup

**Comment by kwa20** [comment]
tested this issue on test-de2 with commit https://github.com/hzi-braunschweig/SORMAS-Project/commits/84778017dd069508de8daa5869742c1aaf8d356f

The pre-existing conditions are currently placed underneath follow-up but should be placed above additional medical information
![preExistingConditionsPosition](https://user-images.githubusercontent.com/70317594/155527867-d8fc3ebc-1ec7-40e0-a4b1-8bfb6fa51277.PNG)

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT
