### ISSUE TITLE
[Lab Messages] Add new userflow for lab message processing [1]

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#6981]
### Situation Description
After the processing of the lab sample it is necessary to change to the case and further to edit the case (case classification, check personal data, create tasks). In order to continue the next steps it would be rational to continue data entry for person (firstname, lastname, birthdate (DDMMYYYY), personcontactdetail, address) and in the next step the creation of tasks in the next window.

### Feature Description
During the process of a lab message (DEMIS) is a guide who lead to single steps of each process (e.g. Choose Person\Create new case; Choose case\contact\event participant\; Choose lab sample\create new lab sample; Choose lab sample ID\Create new lab sample; Create new sample result). After entry of all fields it makes sense to continue guide for next steps:
Check personal data, choose case classification, create tasks.

### Possible Alternatives
Enter alternative if possible. Possibly implementation of flow after lab sample processing (SORMAS guide for case creation).

### Additional Information
Discussed in concept meeting (Jan Böhme). I issue a visual work flow after creation

**Comment by Jan-Boehme** [comment]
@FredrikSchaeferVitagroup 
We discussed this behaviour in the weekly technical admin exchange.

At the moment after you processed a lab message there is no way to directly jump to the resulting case in order to continue working on it.
You need to go to the case directory afterwards, filter for the person's name to find the correct case (maybe even having to choose from multiple results if the name ist something like "Thomas Müller" where it is possible that multiple cases exist with different persons but the same name) and open the case in order to keep working.

This may not be a problem if you only do it once but for users in the local health departmens that have to process dozens, maybe hundreds of lab messages each day each unneccessary step is lost time being productive.

This is why we should introduce a possibility to directly jump to the created case and person after having processed a lab message.

I would refrain from adding it as a new step for the processing of lab messages or a dialog box popup everytime after the processing as this may sometimes not be desired and the amount of work neccessary would mean we won't be able to deliver an improvement fast.

Instead I propose to add it to the existing UI with mininmal changes.
If a lab message has been processed the word "Processed" in the table of all lab messages should become a hyperlink that can be clicked to directly navigate to the case, contact or event participant that resulted from this lab message.

The even better version would be if the user was able to directly see from the link's name what type of entity resulted from the lab message.
We could change the name of the link to "Processed as Case", "Processed as Contact" or "Processed as Event Participant".

From my understanding of the underlying data strucuture it should be relatively simple to find out if the message was processed as a case, contact or event participant because the lab message has a foreign key relation to the new enttity, right?

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue, a good starting point is to check whether the button exists and works for contacts, cases and event participants.

For every such entity with a related lab message, there should also be a shortcut to go to the lab messages list in the submenu. Without a related lab message, this shortcut should not show.

**Comment by FredrikSchaeferVitagroup** [comment]
There is a [problem](https://github.com/hzi-braunschweig/SORMAS-Project/runs/4593766416?check_suite_focus=true#step:7:885) with the latest state of development, probably induced through [the changes from the recent hotfix](https://github.com/hzi-braunschweig/SORMAS-Project/pull/7553).

**Comment by FredrikSchaeferVitagroup** [comment]
Has to be reopened because in some scenarios, the lab message status is not updated to PROCESSED.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
