### ISSUE TITLE
Add configurations for each entity to trigger automated deletion [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#7008]
### Situation Description
In order to comply with the requirements of data protection SORMAS has to provide a process to automatically delete entities and referenced objects. To be able to decide, when an entity and the referenced object are deleted, we have to create certain new fields.

### Feature Description

**Deletion** is done based on the SORMAS core entities:
**Case, Contact, Event, Event Participant, Immunization, Travel Entry**

Deletion takes place **relative to one of the following three events/dates**

1. Entity was created in the system
2. Date of origin (e.g. date of arrival for a travel entry) 
3. End of processing (last change date for now)

A **deletion period** in days relative to this date is defined for each core entity (later it can also be defined for each field individually).

A **nightly job will identify all entities** that need to be deleted and **trigger their deletion**. The actual deletion will be defined in a follow-up issue.

The entity configuration in regards to deletion will not be done in the UI but in the server configurations.

### Examples

* A travel entry is deleted 14 days after it's date of origin
* A case is deleted 10 years after it's end of processing

### Implementation

- [x] New DeletionConfiguration ADO (with respective Service and Facade) with the following fields:
  * entity: Name of the entity to be deleted. An enum called CoreEntityType: CASE, CONTACT, EVENT, EVENT_PARTICIPANT, IMMUNIZATION, TRAVEL_ENTRY
  * deletionReference enum value. One of: CREATION, ORIGIN, END
    * ORIGIN is currently only supported for TravelEntry. Use the report date now. There will be a separate issue to include the date of arrival in SORMAS
  * deletionPeriod: Number of days until deletion, validate to be [7,MAXINT]
- [x] A new abstract class "CoreEntityFacade" (feel free to find a better name) that provides an executeAutomaticDeletion method with a generic implementation. The method identifies all instances of one entity type that need to be deleted and calls the delete method. For deletion use the existing delete... methods for now, based on uuid or ReferenceDto. 
- [x] A job in the cron service class that executes this for all entities named above once every night.

*Note:* Make sure to implement this as generic as possible.

### Follow-up issues / out of scope

* UI that displays information on when an entity is going to be deleted #7240 
* Introduce an "end of processing date" #7247 and re-fine the process of archiving/closing #7249
* For deletion we re-use the existing soft-delete and will have a separate issue to do an actual deletion
* Field-based deletion. For entity types it must be possible to document several deletion configurations.
* Deletion after hand-over to other health-departments

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou There will be a follow-up issue for this once to implement different deletion rules per field. This would more or less be what you are asking for. 

Also thanks a lot for pointing out that disease is missing here - this is indeed very important and needs to be considered.

**Comment by MartinWahnschaffe** [comment]
== Deletion relative to the end of processing

Related to this the data security team suggested to lock datasets, after the end of processing.
Based on that I think we should connect the process of archiving data and defining the end of processing:

1. When a user decides to archive a case, the system shows a popup that shows the end of process date - pre-filled with the latest change date of the case and it's sub-entities ("aggregated change date). The user can edit it if needed. The calculated deletion date should be displayed and updated based on the end of process date
2. When a case is automatically archived, the end of process date is automatically set to the last aggregated change date

Every night a job checks all entities for deletion based on the endOfProcessDate. If the date is not given the aggregated change date is used (e.g. because automatic archiving is not active, or the deletion period for parts of the data is shorter than the archiving period).

When a user de-archives a case, the endOfProcessDate is automatically cleared.

== Deletion relative to the start of processing (creationDate)

The same job mentioned above also checks all entities for deletion based on their creationDate. There is currently no way for users to prevent/extend this. See follow-up issue number 2.

== UI experience

Users need to see when the entity is going to be deleted. This could be shown in the top-left of the main page of the core entity. Clicking or hovering could show how exactly the date is calculated.

== Fields needed for core entities

- endOfProcessDate - used as explained above

== Deletion configuration

- DeletionConfiguration with the following fields: 
  - entity: Name of the core entity to be deleted - most likely an enum
  - deletionReference: Start of process or end of process (enum)
  - deletionPeriod: Number of days until deletion

== Additional points

* We also need to delete entities that "belong" to the entity, but don't have a link from within that entity, e.g. Task and SurveillanceReport

== Follow-up issues

1. Allow individual deletion configuration per field (reference point and deletion period in days)
2. Allow users to extend the deletion period for an entity. Note that for end-of-process-deletion this is already possible by adjusting the endOfProcessDate, so this is only needed for start-of-process-deletion.
3. Extend the DeletionConfiguration by allowing the user to define a set of fields that are to be deleted. E.g. reportingLat, reportLon, symptoms.fever

**Comment by MartinWahnschaffe** [comment]
I have updated the description of the issue. Ready for estimation.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.68.0-snapshot on the local environment. 

Steps for testing:
1. Update the Table "deletionconfiguraton" as follows: set the column "deletionreference" with the value CREATION and ORIGIN for the TRAVEL_ENTRY line, updated deletionperiod column with the values: 3650 and 14 for the Travel_Entry .

2. Waited for the job in the cron service to execute and clear all older travel entries + cases + contacts + events and event participants.

**Comment by sergiupacurariu** [comment]
[testing instructions.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8087359/testing.instructions.txt)
