### ISSUE TITLE
[S2S] External ID of the pathogen test result is sent from Sormas A to Sormas B when ownership is handed over

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7014]
### Bug Description
When sharing a case from Sormas A to Sormas B, the external id of the pathogen test result is also sent. 

### Steps to Reproduce

1. Create a case with Sormas A. Add a sample with a pathogen test result (fill in the field for the External ID).
2. Share the case with Sormas B with ownership.
3. Accept the share with Sormas B.
4. Open the case -> sample -> pathogen test result. Verify if the External ID is visible.

### Expected Behavior
The external id of the pathogen test result shouldn't be visible.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/138054775-12ff9615-06ec-4ac3-a959-cc3db6abd737.png)
![image](https://user-images.githubusercontent.com/89522688/138054802-e5b6c581-ee15-4292-93d5-16066f9a4626.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local env
* User Role: NatUser

**Comment by vidi42** [comment]
Reopened issue because of the receiver system crashing when receiving a case with a Sample and Pathogen test.

Another behavior which was unclear is what happens with the external data when the Sending system is configured to ignore external data, while the Receiving system is configured to **not** ignore external data.

As the receiving system is not aware how the sending system is configured it will accept the data and handle it based on it's configuration, which means that in the situation described above it will overwrite any external data for existing entities that it matches.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
