### ISSUE TITLE
Cases & Contacts > Not possible to export Immunization&Vaccination information

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#7102]
### Bug Description

It is not possible to export Immunization/Vaccination information associated to a Case or Contact.

1. Not included in the detailed exports - values turn up as 'null' or nothing if they were previously filled.
![image](https://user-images.githubusercontent.com/65529128/139557114-4d7f0c79-a1ed-4c65-adeb-4838086960f2.png)

2. Only partially included in the custom export - old values referring directly to the Vaccination entries are still present (in direct variable names), but no values from Immunizations.
![image](https://user-images.githubusercontent.com/65529128/139557180-391964fc-5ff8-4c64-8103-894fa54fa17e.png)

### Steps to Reproduce

1. Cases/Contacts > Export > Detailed Export > Inspect file and see vaccination info not filled out

2. Cases/Contacts > Export > Custom Export > New Export Configuration > See old Vaccination Data fields

### Expected Behavior

1. Cases/Contacts > Export > Detailed Export > Inspect file and see immunizatiton and vaccination info filled out

2. Cases/Contacts > Export > Custom Export > New Export Configuration > See Immunization and new Vaccination fields

### System Details

* Device: Web
* SORMAS version: 1.64.1
* Android version/Browser: Chrome
* Server URL: https://release-de.sormas.netzlink.com/
* User Role: admin, natuser

### Additional Information

Part 1 for imports: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7101

### Development Specifications
* Properly format captions in the custom export window and export file (VaccinationDto probably needs to be added to the list of DTOs where the captions are pulled from)
* When there's immunization info exported for a case, but the immunzation is missing the "number of doses" value, make sure that the cell in the export file just stays empty instead of displaying "null"

**Comment by MateStrysewske** [comment]
In general the export works (it's necessary that immunizations have a valid from date before the case report date and a valid until date after the case report date for them to appear in the export). There are two things that aren't properly working though:

* Captions in the custom export window and export file aren't properly formatted
* When there's immunization info exported for a case, but the immunzation is missing the "number of doses" value, the export file displays "null" instead of nothing (the cell should just be empty)

**Comment by StefanKock** [comment]
Will be reviewed by @MateStrysewske to be included in 1.65

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.65.0-SNAPSHOT.

**Comment by kwa20** [comment]
@MateStrysewske @alexcaruntu-vita I know that this issue is closed already, I just don't quite understand how the export works now since we have a table for vaccinations. Can you tell me which of the entries are exported if multiple vaccinations exist? Do we produce multiple columns for the same variables of different vaccinations?

**Comment by MateStrysewske** [comment]
@kwa20 The information is currently pulled from the latest vaccination (based on the vaccination date or the creation date as fallback) of the latest immunization (end date > start date > creation date) of the associated person.
