### ISSUE TITLE
[Immunizations] Reduced entry option for vaccinations [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7105]
### Situation Description

With the implementation of the immunization module, vaccination information was migrated out of the case, contact and event participant to the immunization entity of the person. However, if users don't use the extensive immunization module, vaccination information would be hidden and there is also no easy way to document vaccinations for a specific disease.

In order to make it easy to add the vaccination information if the immunization module is inactive, a reduced version should be added as an alternative option.

Prerequisites: #7111, #7148

### Feature Description

When the immunization module is inactive, 
- add a vaccination card to the person entity and it's related entities (cases, contacts, event participants) dependending on the disease
    - Heading: "Vaccinations"
    - Creation button: "New Vaccination"
    - Card content: Display each entry separated by a line; content in the card should include the `vaccineName` and the `vaccinationDate`; in persons, it should also include the `disease`
        - each entry should have an edit icon to open and edit the respective entry. Closing the pop-up will let the user stay on the previous form

- Upon clicking "New vaccination", open the existing vaccination pop-up (cf. new entry for table in immunization) but exclude the pregnancy and pre-existing conditions fields.
    - saving the entry should leave the user on the previous form
    - if the user creates a new vaccination out of the person entity, the disease field also needs to be displayed which is usually part of the immunization entity. This is necessary in order to display the vaccinations correctly across entities.
    - display all existing vaccinations in each entity of the person but grey out the ones that are not relevant for the respective entity; determine relevance as follows
        - cases: `vaccinationDate` before `onsetDate`, if not given `reportDate`
        - contacts: `vaccinationDate` before `lastContactDate`, if not given `reportDate`
        - event participants: `vaccinationDate` before event `startDate`, if not given event `endDate` (if before report date), if not given event `reportDate`
    - if the vaccination is displayed as not relevant for the respective entity, add in info icon to the entry
        - upon hover, show the following message: _"This persons vaccination is not relevant for this case/contact/event participant."_

- If a relevant vaccination exists or a new relevant vaccination is added, set the `vaccinationStatus` to `VACCINATED`

### Additional Information

![Vaccinations Card](https://user-images.githubusercontent.com/70317594/139636254-f28154e2-f34a-46c8-8838-cbf4016820c1.png)

In cases, contacts, event participants
![New vaccination entry](https://user-images.githubusercontent.com/70317594/139636275-e3c2c761-5d25-4c0c-b67a-f6cf01cf6dc2.png)

**Comment by kwa20** [comment]
@MateStrysewske @JaquM @bernardsilenou As discussed last week. Please comment if I've missed something.

**Comment by StefanKock** [comment]
A new feature configuration or on which feature configuration this is listening should be documented.

**Comment by MateStrysewske** [comment]
* We need to decide what to do when vaccinations are added and, for any reason, there are multiple immunizations for that person and disease in the database (e.g. because the full feature was used before)

**Comment by MateStrysewske** [comment]
@kwa20 @JaquM Creating vaccinations from inside the person form will not be possible because we won't have a reliable way to determine which jurisdiction we should assign the immunization in this case. I believe this isn't really necessary anyway because users who are using this reduced version of the module will probably be working closer to cases, contacts, and eps instead of the actual persons (because they're not that interested in the general immunization status of the person), right?

**Comment by kwa20** [comment]
@MateStrysewske @ JaquM Yes I think so. We could maybe just keep the immunization card for the person then. However, I'm not sure about the usability because the immunization directory would be hidden in the reduced approach. Any thoughts?

**Comment by kwa20** [comment]
Some further question that were raised when discussing with @bernardsilenou 
1. If the full immunizations module is fully enabled, should there still be an easy option to create vaccinations? How would that look like?
2. If only the reduced module is enabled, should it be possible to create vaccinations independent of immunizations? Reasoning: If we always automatically create immunizations, are there performance implications? What about imports if we always create immunizations automatically?
3. What if there are multiple immunizations for the same disease in the reduced version? Where do vaccinations get added?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Reason for asking point 2. In practice, both reduced and full immunization modules can be activated at the same time, eg a team can be carying out an immunization campaign in Region X and this should not affect the users in region Y who are just responsible for managing covid cases by documenting only vaccination information.

**Comment by MateStrysewske** [comment]
1. No, I don't think so. If the full immunizations module is activated, we need a proper jurisdiction management - skipping the immunization creation is not an option then in my opinion. Also, the only extra step that's needed is to create a basic immunization anyway, subsequent vaccinations can then be added to that immunization. If a country decides to use the full module, they will do so for a reason.
2. That would make it a lot more complicated in the backend, and it would make it basically impossible to switch between the full and the reduced versions. I don't believe there will be significant performance implications. We currently don't have imports for the immunization module, but once we have, there will be no difference between creating a vaccination in the UI or via import. @bernardsilenou Using the reduced and the full module at the same time is not possible because of the way we have to change user filters in order to manage which users can see which data.
3. My current plan is to simply add the vaccinations to the most recent immunization. We could also introduce a selection popup where the user has to select the immunization, but I don't recommend to do that because that popup will very likely confuse the users when they don't use immunizations anywhere else.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Thanks for the response, I think we need to brainstorm on this issue further.
Here are some background information.
1. In countries using a centralized or regional  instance, the team managing the surveillance data is often different from the team managing the immunization. Immunization focuses on the every person in the district while surveillance focuses on only persons at risk (case, contact, ep).  In Nigeria, both are managed by even different public health institutions. This then translate to the fact  that in practice, they would activate the full and reduced immunization module at the same time: The surveillance team would then manage data for case/ contact/ ep etc and register just vaccinations for those entities while the immunization team manages   the immunizations (which can be linked to  just any person, case person, contact persons, etc). The main challenge with the complete immunization module is that for people working in the surveillance team, asking them to document complete immunization for every entity they create would result to much work for them. 
2. What about having just one module  + option to activate full immunization module? When full immunization module is activated, it does not affect the way in which vaccinations are documented for entities but instead provide the additional feature to create immunizations using vaccinations of entities. ie Not all vaccinations must be referenced by immunizations if those vaccination were created through an entity other than immunization. We can even add a bulk edit action for regional and national users to be able to create immunizations using vaccinations. With respect to performance, I can not also confirm but in France they import about 5000 entities (case+contact+ep) per day, if they then use immunizations and travel return modules, this may be about 10000 a day. Even if the time to create immunization is small, in order of 10000, this may become significant. This is why I was thinking that we do not include this step during import but add a bulk action for it. One person can import the entities and another team take case of deduplicating and creating immunizations.
3. Would it not be better to instead add the vaccination to the closest immunization? You can have two immunizations, (a) on 1/02 and (b) on 01/11. if a vaccination is added to the case on  02/11  with vaccine date on  02/11 it get added to (b), and if vaccine date is on 01/04 , it gets added to (a).

4.  Can we not have a  db model such that vaccinations can be either directly referenced by entities (case, contact, ep) OR by immunization OR by both? ie for vaccination that are linked to cases only, the foreign key of immunization on the vaccination table would be NA.

**Comment by bernardsilenou** [comment]
I can join the refinement meeting tomorrow to discuss further.

**Comment by MateStrysewske** [comment]
@bernardsilenou If you need to have further refinement on this issue, please make sure to do so and come to a **final and complete specification BEFORE Thursday** because that's when we'll start development on this issue.

1. Like I said, the way the access to immunizations works has to be significantly different between both modules. If the reduced module is active, access will purely be based on the persons, i.e. a user that has access to a person will have access to all its immunizations (hidden) and thus vaccinations. If the full module is active, access is based on the immunization jurisdiction, which also means that users have access to persons when they only have access to an immunization that is linked to that person. If it is required to use both the reduced and full module at the same time, this would require a rewriting of this logic, which would in turn significantly increase the specification and development effort needed for this issue. Additionally, we would very likely need additional user roles because there are no user roles that are specific to immunization management right now. Again, additional effort. Since this is a time-sensitive issue, please make sure that you have a proper discussion with a final decision asap (see above).
2./4. Adding vaccinations directly to cases, contacts, or eps would mean that they would not be shown when another case, contact or ep for the same person is created, which would result in either incomplete data or the need to document the same vaccinations multiple times (dozens of times in the worst case). @JaquM @kwa20 and I already came to the conclusion that this is not an option and that vaccinations have to be connected to a person through an immunization.
3. Good point, that makes total sense!

**Comment by bernardsilenou** [comment]
@MateStrysewske Thanks for the clarification, your comments are very helpful.

2. (/4.)  is absolutely correct.
* We would discuss it today and probably have it done by the end of the day.
* I have this other suggestion to make. This scenario is very similar to the logic between event (immunization) and event participant (vaccination) and person
21. Every vaccination would have an associated immunization (hidden on ui for reduced mode and shown for full mode)
22. On immunization table, we can add a culumn to determine the mode of creation, eg `immunizationCreationMode`: reduced mode or full mode.
   22.1 If user created immunization through ui or import by going throush the immunization tab + add immunization + vaccination, then immunizationCreationMode == full mode
   22.2 If system uses vaccination of entities to create new immunization (mainly by backed logic or bulk edit mode) then immunizationCreationMode == reduced mode. When creating this immunizations, we use the same logic we used to create immunizations from vaccinations + using the same jurisdiction of immunization as that of the  entity from which the user is creating the vaccination within, although there would be no direct link between the vaccination and entity (2. (/4.) ) 
23. For all immunizationCreationMode == reduced mode, we turn of logic for management status, but user can manually edit the field in immunization (I think this is not so needed) 
24. Duplicate detection of immunization would work as usual for full mode, but for reduced mode (where user only have to create vaccination), we can just decide if its a duplicate automatically. It is not so bad if this is not perfect because the logic to determine which vaccine to show on the entity form would then get all immunization of the person (irrespective of jurisdiction of immunization) + extract all valid (based on time , disease) and unique vaccinations.
25. We can then apply this rule to determine read and write access of users if  reduces or full or both modes are activated:
 25.1 If user has full access to person (ie full assess to any entity of the person: case, contact, ep, immizaton)
     25.1.1 if the jurisdiction of immunization == jurisdiction of user, then  full access to immunization + all associted vaccinations of the immunization
    25.1.2 if the jurisdiction of immunization != jurisdiction of user, then  read access to immunization + all associted vaccinations of the immunization + options to add more vaccination using full mode logic
       25.1.3 if user = reporting user of vaccination, then full access to vaccination

**Comment by bernardsilenou** [comment]
@JaquM @kwa20

**Comment by kwa20** [comment]
I tested this feature on test-de.sormas.netzlink.com and encountered some problems:

- When a relevant vaccination was entered and the vaccination status updated, the form does not get refreshed and after the user makes further entries and saves, the following message appears. This happens for cases, contacts and event participants.

<img width="551" alt="SaveAfterVaccinationEntry" src="https://user-images.githubusercontent.com/70317594/142640367-e1dc1f2e-7748-4684-b534-c63461d3bc93.PNG">

Steps to reproduce:
1. Create a case, contact, event participant
2. add a relevant vaccination
3. Make further entries on the respective form
4. Refresh after the error message appears and check form contents 

- When event participants or contacts are converted to cases; if cases are linked to events; if cases get contacts to their source cases entered in epiData; If event participants get converted to contacts...
    - ...the vaccination status is not adopted accordingly
    - e.g. contact persons that have 'vaccinated' as status have an empty vaccination status upon case conversion

Steps to reproduce:
1. Create a contact or event participant
2. Enter relevant vaccinations and confirm that the vaccination status is set to 'vaccinated'
3. convert them to a case
4. Check the vaccinations status
5. Create a new case
6. Enter a relevant vaccination and confirm that the vaccination status is set to 'Vaccinated'
7. create a contact to source case for the case person (report date or last contact date should be after relevant vaccination) and subsequently check the vaccination status
8. link the case to an event (event startDate or reportDate should be after vaccination date)

@MateStrysewske I assume that the immunization card structure was adopted here?

<img width="175" alt="vaccinationsDisplay" src="https://user-images.githubusercontent.com/70317594/142645149-4ef39379-9493-4ab3-a2ac-f335c46ae8e5.PNG">

- It might not be obvious that the date of vaccination is displayed in the top right without checking the content of the entry because it could also be the report date. Can we add the "Vaccination date:"?
    - The idea was to make the display consistent with e.g. "Surveillance Reports" but that's minor I guess.

- I could not trigger the info and visual distinction about the relevance of vaccinations for the specific entity. I created a case reported a few months ago with the onset date being the same as the report date. I then added a vaccination with vaccination date being today. Am I missing something maybe?

**Comment by MartinWahnschaffe** [comment]
- [ ] also check problem in ImmunizationService.inJurisdictionOrOwned

**Comment by MateStrysewske** [comment]
@kwa20 Agree with all your requests. Concerning your last point, it's likely that I've simply forgot to implement this. @sergiupacurariu will take care of it.

@MartinWahnschaffe Could you please add a little more detail to your item?

**Comment by kwa20** [comment]
Leftovers as discussed with @sergiupacurariu:

- [ ] trigger updateVaccination statuses for the following scenarios:
    - contact conversion to cases
    - contact to source case creation in epi data
    - linking cases to events and thereby creating event participants
    - event participant conversion to cases

- [ ] Grey out the vaccination entries that are not relevant based on the logic described in the initial description (make sure that this is merely visual and entries can still be opened to view details)
- [ ] Display an info icon for greyed out entries with the following descriptions per entity while hovering:
    - Cases: "This persons vaccination is not relevant for this case because the vaccination date is set after the symptom onset date or case report date."
    - Contacts: "This persons vaccination is not relevant for this contact because the vaccination date is set after the last contact date or contact report date."
    - Event participant: "This persons vaccination is not relevant for this event participant because the vaccination date is after the event date or event report date."

**Comment by StefanKock** [comment]
Discussed in the daily: Only the first point (trigger updateVaccination) are mandatory. The visual hints could be moved out and come later. Remark: transporting information by color is not accessible nor self-explainatory.

**Comment by kwa20** [comment]
@sergiupacurariu @BarnaBartha Just for some further aid here some visual examples:

![Vaccination_timeline_example1](https://user-images.githubusercontent.com/70317594/143558430-db428723-b400-40ae-85c7-e29f39113a3e.png)

The second example shows a scenario where the vaccination date is not given but the report date is used to display the relevance and determine the vaccination status
![Vaccination_timeline_example2](https://user-images.githubusercontent.com/70317594/143558427-645cd87b-29f1-4a44-908e-5611373dd89b.png)

**Comment by roxanamlendea** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/89522688/144025010-c31c7692-2262-4f23-83a7-4d8c214f5aee.png">
When the Vaccination has no Date of Vaccination, it gets greyed out and the info icon appears (the info message might be misleading for the user). A Vaccination with no date shouldn't be greyed out.
