### ISSUE TITLE
Create missing history tables for entities [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7113]
### Feature Description
We use history tables to be able to easily see the change history of individual entities.
E.g. this could be used to display a list of "revisions" for a case and to allow the user to see what the case data looked like at a certain point in time.

### Problem Description
In order to really be able to "look back in time" we also have to include infrastructure entities. E.g. it's possible that the name of a facility is changed.

### Proposed Change
Add history tables for the following tables:

- [x] "community"
- [x] "continent"
- [x] "country"
- [x] "district"
- [x] "documents"
- [x] "externalshareinfo"
- [x] "facility"
- [x] "manualmessagelog"
- [x] "pointofentry"
- [x] "populationdata"
- [x] "region"
- [x] "subcontinent"

In addition to this exempt the following tables from the checkHistoryTables.sql script:

- [x] "schema_version"
- [x] "systemevent"

**Comment by JonasCir** [comment]
@MartinWahnschaffe Can you clarify the last point? :) 
Should we really include `schema_version` as changes to this table are predictable through the update script?

**Comment by MartinWahnschaffe** [comment]
No, it says **exempt** the schema_verison table from the **checkHistoryTables.sql** script
So the schema version should not have a history.

**Comment by JonasCir** [comment]
Missed that thanks :)

**Comment by vidi42** [comment]
In order to test this you need to have access to the database.

After deploying the latest SORMAS version, run the script which [checks for missing history tables](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/utils/checkHistoryTables.sql) which should not return anything.

Second check which can be done on any of the history tables for the tables above is to update some of the entities concerning one of the table, then checking if a new entry was created in the history table.

Ex for `country`:
- Update a country from the UI
- Check the `country_history` table if it contains an entry regarding the changed country

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.68.0-snapshot deployed on local environment.
All history tables are present and empty.
Editing information causes new entries to be saved in the history tables.
