### ISSUE TITLE
Deleted cases remain linked to immunizations

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7129]
### Bug Description

When a case is deleted and linked to an immunization, the deleted case remains linked to the respective immunization.
### Steps to Reproduce

1. Link a case to an existing immunization
2. Delete the linked case
3. Press 'Open case' in the immunization

### Expected Behavior

When deleting the case, it should automatically get unlinked from the immunization.
### Screenshots

<img width="673" alt="linkedRecoveredCaseImmunization" src="https://user-images.githubusercontent.com/70317594/140021268-454e68a0-4417-4ddb-af06-0037dc232775.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

We should probably have a general option to unlink cases from immunizations manually

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.65.0-SNAPSHOT.

**Comment by bernardsilenou** [comment]
@MateStrysewske  @kwa20 
- When a case is deleted while the immunization was created using vaccination formation of the case (reduced mode),  should we no also delete the immunization ?
- In the suggested reduced immunization mode where immunizations are created from vaccinations of entities, I think we can automatically delete those immunizations also. If you agree then we may in the other specifications.
- We can also add a filter on  immunization directory to extract and delete them.
-  The feature to manual unlink cases from immunization may not be needed in the reduced mode we discusses since we would be able to directly delete the vaccinations.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't think so. The immunization will still be relevant for the person, and there might be other vaccinations added to it that aren't relevant for the deleted case, but for other cases, contacts or event participants. Since we can't say that for sure, we should definitely not delete these immunizations.
