### ISSUE TITLE
'Database entry was not updated' error when trying to save a new case

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#715]
When i create a and i try saving it come up with red alert error that read data base entry was not updated-likely it was change in between

**Comment by MateStrysewskeSym** [comment]
@foyiri It would be really helpful to have ticket names that reflect the core of the issue instead of only naming the general area in which it appears. E.g. this ticket could be named "'Database entry was not updated' error when trying to save a new case". This really helps us to get a better overview because we know about the actual problem when only looking at the title and don't have to open the issue to have a look at it. Thank you!

**Comment by MateStrysewskeSym** [comment]
@foyiri Also, please provide more information on how this happened because I can't easily reproduce it. I suppose you created a case, clicked on save, then got redirected to the case edit form, changed something there and saved again. What exactly did you change?
