### ISSUE TITLE
Move the responsible user filter in the event directory next to the jurisdiction filters

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7150]
### Feature Description

The event directory contains a responsible user filter which depends on the user selecting a region first.

### Problem Description

The region dropdown is not next to the responsible user filter, but hidden behind the "Show more filters" button. The resulting workflow is very unclear.

### Proposed Change

* Move the responsible user filter from the first row to the second row next to the region, district, community and type of place filters.
* Add an info icon next to the filter with the following description on hover: "The responsible user filter requires a region to be selected in the region filter."

### Possible Alternatives

Moving the filter to the second row might not be necessary and the info icon might be sufficient. @carolinverset what do you think?

**Comment by carolinverset** [comment]
@bernardsilenou @MateStrysewske @ftavin

Thank you for your quick feedback!

I agree with you: it would be better to move the responsible user filter to the second line. This will be more readable for users, especially since the region is hidden at first.
Can this modification be carried out quickly by HZI or is it preferable that I commission the French developers?

Thanks a lot

**Comment by MateStrysewske** [comment]
@carolinverset The next sprint (starting today) will have a very limited focus on a few specific topics for us which is why anything that's not an obvious bug is out of scope for us - it would therefore be great if your developers could do it if it's required for the next version.

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @MateStrysewske 
Ok I'll see what can be done . 
Thank you
