### ISSUE TITLE
Sormas REST Api getting cases and correspoding tests

### ISSUE THREAD

**Issue by ThomasSeitzKoeln** [hzi-braunschweig/SORMAS-Project#7219]
Hello everyone,

in cooperation with the health department of the city of Cologne we are trying to access the REST API from Sormas. We as the City of Cologne have a Sormas test instance in operation (https://test-koeln.sormas.netzlink.com/) with some sample data sets. We have succeeded in querying all cases since date X via the route "/ cases / all / {since}" using the REST API and then receiving detailed information on the cases via "/ cases / uuids". The case JSON that you get back does not contain all the information relevant to us, so we still go to the route "/ persons / uuids" to get the address data and the date of birth of the case.
What we are still missing and why I am writing this request is that we do not know how to get the test data for a case. So my question is, where in the case or person JSON is the reference to a test?
Or do I not have the authorization to do this? See "### Samples
* only users that are permitted to see samples at all
* all samples are accessible for national users
* whoever created the sample or is assigned to it is allowed to access it
@@ -70.67 +70.67 @@ In general data access & synchronization is based on the following rules:
* editing possible only for samples of cases / contacts / event participants in the user's jurisdiction
* viewing sensitive data is possible only for samples that are part of the user's jurisdiction "

That leads to the real question:
What must be set in my user so that I can access the tests (i.e. samples) via REST, and how do I find the UUID of the tests in the case or person JSON?

I hope you can help me / us here?
Thank you for your time and effort.
Kind Regards, Thomas

**Comment by MateStrysewske** [comment]
Hey @ThomasSeitzKoeln - that depends on the user roles that are assigned to your user, but in general, almost all user roles are allowed to view samples. If you're using something like a National User, Surveillance Supervisor or Surveillance Officer, you will definitely have access.

However, you can't receive the UUIDs of the samples via the case or person resources, and they are never included in any case or person JSON you will receive. Instead, you will have to use the sample resource (/samples) instead. You can e.g. retrieve all samples of one or a number of specific cases by using the /samples/query/cases endpoint and specifying the UUIDs of the case(s) which you want to retrieve the samples for.

Retrieving samples by persons is currently not possible. You would need to use the /samples/all/{since} endpoint instead and filter the resulting list by the UUIDs of the cases, persons, and event participants that are associated with that person.

**Comment by ThomasSeitzKoeln** [comment]
Hello @MateStrysewske , thank you for your feedback. 
Sadly im still struggling with the issue. 

Could you please explain in detail what i have to do to get the samples of e.g. the case with the UUID XYZ?
Thank you very much.

**Comment by MateStrysewske** [comment]
@ThomasSeitzKoeln That's quite easy - you just have to use the /samples/query/cases endpoint and pass a list containing the UUID of that case as the body.
