### ISSUE TITLE
Case Directory | Clicking on Person Id will result in a server crash

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7254]
### Steps to Reproduce

1. Go To Cases
2. Click on the Person Id column name

### Expected Behavior
sorting of the Person IDs should happen

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/141508980-27481ee5-ac77-4370-9e95-68d1e10d7f51.png)

### System Details

* Device:
* SORMAS version: 1.66.0-snapshot
* Android version/Browser: chrome
* Server URL: localenvironemnt
* User Role: NAtUser

**Comment by roxanamlendea** [comment]
I tested it on my local environment on the hotfix branch and yes, on the Cases directory is fixed, but this server crash also happens when the table is sorted by the **Person ID** in the on the **Contact Directory** page.
![image](https://user-images.githubusercontent.com/89522688/142185610-40d3ed5d-b3c5-40cf-a6f6-f626ab2fa3a7.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using version 1.65.1-SNAPSHOT on the hotfix branch.
