### ISSUE TITLE
Refactor updateVaccinationStatuses methods

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7397]
### Bug Description
When a Vaccination with a Date of Vaccination > the Report Date of the Case is created, the Vaccination Status remains empty (expected), but then if the Vaccination is edited and the Date of Vaccination is < Report Date of the Case, the Vaccination Status is not updated to Vaccinated, it remains empty. 

### Steps to Reproduce

1. Open a Case that has no Vaccination and has an empty Vaccination Status.
2. Create a new Vaccination which has a Vaccination Date > Report Date of the Case.
3. Save the Vaccination.
4. Edit the Vaccination and set the Vaccination Date < Report Date of the Case.

### Actual Behavior
The Vaccination Status remains empty.

### Expected Behavior
The Vaccination Status should automatically be updated to "Vaccinated".

### Screenshots
After adding the Vaccination
![image](https://user-images.githubusercontent.com/89522688/144083792-077ab60d-38ab-4f45-91c4-46d64381a1cd.png)
![image](https://user-images.githubusercontent.com/89522688/144083827-995de565-ef3d-4a2d-9d0f-e129807f3416.png)
After editing the Vaccination
![image](https://user-images.githubusercontent.com/89522688/144083963-e038ce3c-6204-470f-bc77-70b3f20b411d.png)
![image](https://user-images.githubusercontent.com/89522688/144084020-b9252284-fc02-41ef-bc46-b3d00b0c9c23.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
#7105

**Comment by BarnaBartha** [comment]
Issue was fixed in hotfix changes.

**Comment by MateStrysewske** [comment]
Turned into a refactoring issue

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT.

**Comment by bernardsilenou** [comment]
@roxanamlendea 
Please can you also test if the change is also fine in the mobile ?
I did a test on test-de.sormas.netzlink.com, sormas-1.67.0-SNAPSHOT, A11 samsung.
- Adding a new valid vaccination did not update the vaccination status

**Comment by MateStrysewske** [comment]
@bernardsilenou The status update does not happen on the mobile device because it possibly does not have access to all relevant entities that need to be updated. It's only performed on the backend once a synchronization has been done.

**Comment by bernardsilenou** [comment]
@MateStrysewske  
I do not think I understand the last point.
- When a valid vaccination is added to a case, then can we not directly update the vaccination status of that specific case based on the information in the db of the mobile app? After synch, the data can still be updated if needed in addition to all other entities.
- The flow does not look good on the mobile app because users may think that its a bug to have the vaccination status to NULL after just entering vaccination information.

**Comment by MateStrysewske** [comment]
@bernardsilenou The reason is that we want to avoid replicating a lot of backend logic in the mobile app because otherwise we need to maintain that logic in two separate places, which makes any further refactorings more effortful and bears the risk of the logic being different in the mobile app compared to the web app, which would compromise data.

Still, if you believe that this logic should also be executed on the mobile app, feel free to open a change request for it.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Understood. I think its not worth the effort for now.
Danke
