### ISSUE TITLE
Only consider vaccinations before the relevance date for vaccination status calculation

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7406]
### Feature Description

Cases, contacts, and event participants have a vaccination status that is automatically set to `VACCINATED` when there is at least one vaccination associated with the same person that is on the relevance date of the case/contact/ep or before.

### Problem Description

Our Survnet converter does only consider the vaccination relevant for the case/contact/ep if its vaccination date is BEFORE the relevance date, i.e. at least one day earlier.

### Proposed Change

Change the calculation in SORMAS to match the converter calculation, i.e. only consider vaccinations that either have no vaccination date at all, or that have a vaccination date at least one day before the relevance date of the case/contact/ep.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of the hotfix 1.66.1 branch on local environment

**Comment by bernardsilenou** [comment]
@MateStrysewske 
There is this statement that is not clear, `only consider vaccinations that either have no vaccination date at all`
The changes in the PR shows as it vaccination with null values for vaccination date are considered among the set of possible relevant vaccinations. If this is not the case, then all is fine.
- My main suggestion is that if we are validation relevant vaccinations based on vaccination date, then vaccinations with missing values for date should not be considered because the true value of the date that is missing can either lie before, in the seme day or after the most relevant date of the entity in questions.
- If this is specific to survnet, then it would be better to add it in the converter.

**Comment by MateStrysewske** [comment]
@bernardsilenou That part of this issue is outdated already. Vaccinations with a missing vaccination date are no longer considered after the changes done in #7424
