### ISSUE TITLE
Replace "n/a" with something clearer (e.g. not answered) [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#743]
Because n/a can also be interpreted as "not applicable"

**Comment by bernardsilenou** [comment]
I suggest we replace N/A with "unknown" in order to be genric and consistent.

**Comment by MartinWahnschaffeSymeda** [comment]
I think unknown is diferent from "not answered".
@hzi-braunschweig Can you please confirm this? You maybe also need to talk to Gérard about this. Differentation between "unknown" and "not answered"/blank is sometimes tricky.

**Comment by MartinWahnschaffeSymeda** [comment]
![grafik](https://user-images.githubusercontent.com/23217632/44092158-e9ad8b56-9fcf-11e8-82a0-2182cadd1a1a.png)

@hzi-braunschweig We are still not sure about this one. "Not answered" and "Blank - enter value" don't look really good. It's a lot of text that messes up the screen. Maybe it's better to keep N/A.

**Comment by hzi-braunschweig** [comment]
Then please leave it as not answered instead of N/A.

Tom-Aba Daniel (B.Sc MPH)
Doktorand
PhD Epidemiology Programme, Hannover Medical School (MHH),
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MateStrysewskeSym** [comment]
- [ ] either use "Blank" or "Empty" or "Not Answered" with brackets OR maybe in italic to signalize that it's different from other fields; or maybe grey it out
