### ISSUE TITLE
Add bulk deletion and reporting period filter to the travel entries directory [2]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7451]
### Situation Description

There is no option to delete travel entries with bulk action. That causes a lot of work.
In many regions, documented entries that have not become a case must be deleted after 14 days. A filter option for a reporting period is therefore additionally relevant.

### Feature Description
- [x] Add a bulk action dropdown to the travel entries directory that includes a delete action (as in other directories). Only show the bulk action dropdown if the user has the TRAVEL_ENTRY_DELETE and the PERFORM_BULK_OPERATIONS user rights.
- [x] Add "Report date from" and "Report date to" filters to the travel entries directory that filters the travel entries by report date according to the selected period.

**Comment by MateStrysewske** [comment]
@JaquM Can you please clarify how exactly the filter should look like? I suspect it's supposed to filter the travel entries by report date, and that it should look like the "from - to" filters in e.g. the case directory. Is that correct?

**Comment by JaquM** [comment]
@MateStrysewske yes this is correct

**Comment by roxanamlendea** [comment]
I'm reopening the ticket due to an issue that I found related to the Reporting Period filters.

Since we have the 'Show more / less filters' option, the Travel Entries Directory should open directly with the Reporting Period filters hidden and with the 'Show more filters' option, not with all filters visible and with the 'Show less filters' option. 

When the Travel Entries Directory is opened, it looks like this:

![image](https://user-images.githubusercontent.com/89522688/155146658-15845a79-1592-4dd5-bcc1-30cd781f23cd.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.

An aspect that is maybe worth mentioning is the performance part of the deletion. I deleted a larger number of Travel Entries (2178 Travel Entries) via Bulk Actions -> Delete, and it took approx. 4 min.

**Comment by roxanamlendea** [comment]
Reopening the ticket because of a small UI issue. The 'Enter Bulk Edit Mode' / 'Leave Bulk Edit Mode' buttons are overlapping the buttons above.

![image](https://user-images.githubusercontent.com/89522688/155476869-4b443c31-cbdd-41ad-a9e2-87737783a1d3.png)

![image](https://user-images.githubusercontent.com/89522688/155476735-13f342a4-74dd-43f3-9755-34c14da60cf7.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.

An aspect that is maybe worth mentioning is the performance part of the deletion. I deleted a larger number of Travel Entries (2178 Travel Entries) via Bulk Actions -> Delete, and it took approx. 4 min.

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT
