### ISSUE TITLE
Filter to show persons with overdue immunization is not working correctly

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7461]
### Bug Description

The filter in the immunization directory that filters the list by persons with overdue immunizations is not working correctly. It should show immunizations with management status ONGOING and where the end date has already been reached. However, the filter in `DirectoryImmunizationService` instead checks whether the end date is greater than the current date (which would be fine).

### Steps to Reproduce

1. Create an immunization with management status ONGOING and end date > today
2. Use the filter in the directory; the immunization should show up even though it shouldn't

### Expected Behavior

When using this filter, immunizations should be shown when:
* `immunizationManagementStatus` == `ONGOING`
* `endDate` < current date

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by mario-kuehne** [comment]
Tested locally with development branch (git commit hash 305a5ece878808b37a5d6ab863b5509fe81382eb).

Actual behaviour:
* Current Date (Day) is 12/9/2021
* Set End Date of Immunization entity to 12/9/2021 & immunizationManagementStatus == ONGOING
* Filter 'Only show persons with overdue immunization' also shows the Immunization entity with End Date 12/9/2021 (Expectation: entity should not be shown)

Expected behaviour (clarified with @MateStrysewske ):
"endDate < startOfDay(currentDate)"

**Comment by mario-kuehne** [comment]
Successfully tested on https://test.sormas.netzlink.com/ (Version: 1.67.0-SNAPSHOT)
