### ISSUE TITLE
Difficulty in selecting an entry point configured on SORMAS mobile

### ISSUE THREAD

**Issue by dfowe** [hzi-braunschweig/SORMAS-Project#7467]
![issue](https://user-images.githubusercontent.com/92849971/145063739-2374e55e-bb12-4f24-82ff-9f91913cb059.PNG)

### Description of functions
creation of a case on mobile sormas at the entry point configured with a "surveillance officer" user right
![Sans titre](https://user-images.githubusercontent.com/92849971/145067537-b7ed9f2b-46b9-42cd-9b12-dad0e3ca7779.png)

### 1-I check the button "the place of stay of the case differs from its responsible region."

2- informing the region and the district that made it possible to select the corresponding entry point.

3- once the entry point has been selected, I uncheck the button "the place of stay of the different case of its responsible region"

**Comment by MateStrysewske** [comment]
@dfowe Sorry for coming back to you so late. Are you sure that you're using a surveillance officer for this? Because that user role isn't allowed to create point of entry cases in the mobile app in the first place. Please let me know which user roles the user you're using to produce this problem has exactly.

**Comment by dfowe** [comment]
I confirm I used the right Surveillance Officer for this treatment

**Comment by MateStrysewske** [comment]
@dfowe Ah sorry, my mistake, the point of entry in the user's district I have in my system was inactive. :)
