### ISSUE TITLE
Hide specific person fields in German systems [0.5]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7476]
### Feature Description

Due to different data protection requirements, certain data may not be collected depending on the country and the corresponding fields should therefore be hidden in German and French instances.

### Proposed Change

Following Values should be hidden:

- [ ] `mothersMaidenName`
- [ ] ` fathersName`
- [ ] `mothersName`
- [ ] `nickname` (DON'T hide this for France)
- [ ] `educationType` and `educationDetails`
- [ ] `passportNumber`
- [ ] `nationalHealthId` (DON'T hide this for France)
- [ ] Community contact person `details`

###Additional information
During person duplicate detection, the system already don't consider `passportNumber` and `nationalHealthId` if these fields are empty.

**Comment by MateStrysewske** [comment]
@JaquM There's no such configuration right now. Fields are manually enabled or disabled for specific countries by us, directly in the code. Implementing a system that allows to do this dynamically would require proper design-thinking and specification.

Adding feature configurations for individual fields is something that I would heavily discourage because it basically crowds the system with extremely minor stuff that is not supposed to be part of it.

**Comment by JaquM** [comment]
@MateStrysewske so we need to hide these for Germany. 
@Candice-Louw swiss also?
@bernardsilenou what about france?

**Comment by MateStrysewske** [comment]
@JaquM Can you please update your issue description accordingly?

**Comment by kwa20** [comment]
How do we handle existing data in the `passportNumber` and `NationalHealthId`? If these fields are filled, they will be used for duplicate detection and I guess even though we hide them, we won't delete them.

I guess we'd also have to hide the fields in the import templates?

**Comment by MateStrysewske** [comment]
@kwa We could extend the issue to not include these fields in duplicate detection if they're disabled on the respective system. That would probably be the best solution?

Import templates already exclude fields that are not visible for the country that is specified in the server properties, so we don't need to adjust them.

**Comment by kwa20** [comment]
@MateStrysewske seems like a good solution

**Comment by MateStrysewske** [comment]
@kwa20 Just realised that we don't need to do anything about the duplicate detection. Passport number and national health ID are only considered when they're specified for the person that is about to be created, and since they will always be empty (since they're hidden), they'll never be considered.

**Comment by bernardsilenou** [comment]
This issue is a very old request that we did not work on it because of other urgent things. 
Rather than manual hiding of fields,  I also think a better solution is to add a configuration in db for each entity in order to determine the attributes to show on forms.
This is not limited to the person entity only, for example, on the case form, there are attributes like "reception date of paper forms" that may not be useful for the DE instance.

**Comment by bernardsilenou** [comment]
This issue is a very old request that we did not work on it because of other urgent things. 
Rather than manual hiding of fields,  I also think a better solution is to add a configuration in db for each entity in order to determine the attributes to show on forms.
This is not limited to the person entity only, for example, on the case form, there are attributes like "reception date of paper forms" that may not be useful for the DE instance.

**Comment by Candice-Louw** [comment]
@ClaudeMarksteinerCSI to define needs for CH systems.

**Comment by bernardsilenou** [comment]
@carolinverset
Please can you confirm which variables can be hidden for France. I think `nationalHealthId` was added by dev France.

**Comment by carolinverset** [comment]
@bernardsilenou 
I transferred the question to the person in charge of imports. It seems to me - but this is to confirm - that the passportnumber and nationalhealthID field is used in France. Hiding it would cause problems. I confirm these elements to you as soon as possible

**Comment by carolinverset** [comment]
> @bernardsilenou I transferred the question to the person in charge of imports. It seems to me - but this is to confirm - that the passportnumber and nationalhealthID field is used in France. Hiding it would cause problems. I confirm these elements to you as soon as possible

The team in charge of imports confirms that the nationhealth ID is essential for us. On the other hand, and contrary to what I indicated previously, the passportnumber is no longer supplied in France. Is it possible to make the display or not of the NationalHealthId field configurable so as to be able to hide it in Germany but display it in France? thanks a lot

**Comment by MateStrysewske** [comment]
@carolinverset What about the other fields?

**Comment by carolinverset** [comment]
@MateStrysewske 
they can be hidded

**Comment by ClaudeMarksteinerCSI** [comment]
There is no need to hide any fields for Switzerland.

**Comment by bernardsilenou** [comment]
Dev specifications:
- We may also need to adjust the import template to match with the country instance, eg for instances that the passport number is hidden, it should not also appear on the any person related import template. If this is much, then  should it be moved to another issue?
- The same applies to creation forms for case, contacts, immunization, travel returns,
- I think we do not need to boarder about hiding them on data export since it would just be empty fields, except for old data documented in the past

**Comment by Marko-ilmkreis** [comment]
I guess the `country of birth` and `citizenship `are also not needed in Germany.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 
> I guess the `country of birth` and `citizenship `are also not needed in Germany.

Those attributes were added becaus of a DE request https://github.com/hzi-braunschweig/SORMAS-Project/issues/3412. Maybe some GE still need them in SORMAS.

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou shame on me, but I did not expect that these fields are used for SurvNet.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.67.0-snapshot on local environment.
