### ISSUE TITLE
Export via the "Benutzerdefinierte Fall-Export" (User-defined case export) does not contain any data if an export of the vaccination status is requested

### ISSUE THREAD

**Issue by MallerBeach** [hzi-braunschweig/SORMAS-Project#7505]
### Bug Description

An export via the "Benutzerdefinierte Fall-Export" (User-defined cases export) does not contain any data if an export of the vaccination status is requested. Probably this was caused due to an update of SORMAS-ÖGD to version 1.66.3. 

### Steps to Reproduce

1.  Define export with caseData-id (Fall-Seriennummer) only works fine
2.  Define export with caseData-id (Fall-Seriennummer) and multiple information of the vaccinations produces an export without any data.

### System Details

* Device: Desktoop-PC
* SORMAS version: 1.66.3
* Browser: Firefox
* User Role:  Admin

**Comment by MateStrysewske** [comment]
@MallerBeach Can you please request error logs from Netzlink and attach them to this issue? I suspect that the error is caused by a specific database state (at least it's not easily reproducable for me).

**Comment by kwa20** [comment]
@MallerBeach I was also not able to reproduce the problem on a test environment. You could do the following things in order to narrow down the possible issue.

1. In succession, remove the respective variables from the vaccination section in the configuration and perform an export after every removal. This will be helpful in order to identify if a specific variable causes the issues

<img width="463" alt="vaccinationExport" src="https://user-images.githubusercontent.com/70317594/145818049-3d6108fd-5179-48d1-a1ec-148acb31f08e.PNG">

2. I suspect that specific cases are causing the files to be empty, i.e. if we reduce the number of exported cases, the files should get generated properly and we can take a look at the respective cases that include the problematic data. In order to achieve this, you have multiple options:
2.1 Filter the case directory for a specific case report date rnage and peform custom exports after applying the filters. If the file gets generated normally, the problematic case is not in the filtered range. If the file is empty, the exported data includes the problematic case
2.2 If filtering a range down to a date still leaves to many cases listed on the directoy, reduce the number of cases by applying additional filters like outcome of case etc.
2.3 You can enter the bulk edit mode and select a limited number of cases and then perform a custom export. If the file  is emtpy, the problematic case is included in the exported data. If the file gets exported as expected, the problematic case is one of the unselected cases.

**Comment by MallerBeach** [comment]
@MateStrysewske @kwa20 Thanks for your support! I could narrow down the problem to specific dates. In general the export works fine. As stated by @kwa20 it seems to be very likely that specific cases are causing the files to be empty. I'll do a further check!

**Comment by MateStrysewske** [comment]
@MallerBeach Please still share this info with us because there indeed IS a problem when the export is empty for specific cases, and we need to fix that problem :)

**Comment by MateStrysewske** [comment]
@MallerBeach Is it possible that you also get an error when trying to enter one of the cases that produce this error?
