### ISSUE TITLE
External visit API specs can't be pushed to development after changes

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7543]
### Problem Description

After introducing merge freeze, the CI step to commit changes to the external visit API specs to development fails when changes are made to the external visits API. The reason seems to be that the mergefreeze check that is now part of our CI pipeline isn't integrated into the CI step that does this push, and so the push is rejected.

### Proposed Solution

Detailed instructions below:
1. Find out how to fix this
2. Fix this :)

### Additional Information

Relates to #7012

**Comment by JonasCir** [comment]
To elaborate @StefanKock : 
The Mergefreeze app works with PRs (PRs can be merged if the branch is not frozen and cannot be merged if frozen).
However, the app prevents normal squad members and our CI bot to push to `development` at all. This is because the app introduces a required check (`mergefreeze`) which needs to pass. This check runs for PRs, however, it does not get invoked for normal pushes, and since it is required, it will allways fail what causes the git server to reject the users changes.

I tried to work around it as described in the GitHub [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) and created this [workflow](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/.github/workflows/skip_required_status.yml) but it didn't work.

So right now I see two options:
1. Reach out to the developers of the tool
1. Remove the tool from the repo as it effectively prevents squad members and bots from pushing to `development` ever again.

**Comment by StefanKock** [comment]
As workaround I try if it helps that user `sormas-vitagroup` is now a repo admin.

**Comment by JonasCir** [comment]
I restarted the CI run on `development`, we'll see :)

**Comment by JonasCir** [comment]
@StefanKock @MateStrysewske Can we close this now? Are we going to accept that the bot user as elevated permissions now=

**Comment by StefanKock** [comment]
If it's working now, I think the ticket is solved.
