### ISSUE TITLE
Bulk edit for travel entries

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7593]
In the Entries directory is the bulk edit currently not available. Please do enable ist with the features:

- Delete (important)
- Edit (less important)
   options to edit: 
 ```
    status (vaccinated, recovered, neg. tested)
    Archive
```
- Convert to a case (not important)

**Comment by JaquM** [comment]
@Marko-ilmkreis the deletion part is already mentioned here: #7451

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis @JaquM I'll close this issue because it doesn't use any of our issue templates. Please have another look at our contributing guidelines and open a new issue that uses one of the templates, and also contains more details (e.g. on how the process to convert multiple travel entries to cases at once should work).
