### ISSUE TITLE
Modify the field allowing to designate the observers of a task

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#7644]
### Feature Description
Develop the mechanics of defining observers of a task.

### Problem Description
To date, a user who creates a task has the option of defining observers who will be a copy of the notification received by the person in charge of performing the task.
To define the observer (s), the user will tick boxes corresponding to each "observer" user.
In view of the very high number of users in the regions, the list of checkboxes is very long and no search function exists to date. It would, however, facilitate the search for the person or persons to be topped as an "observer".

![image](https://user-images.githubusercontent.com/65449450/148924879-6fffe5b7-c510-4711-930e-461ca0d5d2d7.png)

### Proposed Change

We propose to develop a new mechanism:
•	a selection field (in the same style as the "assigned to")
•	a list of added observers with the possibility of removing them from the list (trash can icon)
•	when we select a user in the first field, the user is added to the list and the field is emptied to allow a new selection

### Additional Information
@bernardsilenou @ftavin @olivierleuci @emond-fuseau

**Comment by kwa20** [comment]
@carolinverset Sounds like a good change to me. Do we want to automatically add the user upon selection? Otherwise we could add an "Add" button next to the drop-down field that becomes enabled when a user has been selected. This might prevent accidental selections.

Further, we could think of other additions like a "Start observing" (/"Stop observing") button that automatically sets the current user as an observer and also add the observation feature to the bulk edit function for tasks. Additionally, implementing a quick filter on the directory that displays all tasks that users are observing might be nice.

These should probably be done in other issues though. If this sounds interesting to you, I could create issues for these use cases.

**Comment by bernardsilenou** [comment]
@kwa20  I also think  the suggested changes go in a different issue

**Comment by kwa20** [comment]
@bernardsilenou We can handle it as we do for other fields by taggin them as country specific.

**Comment by bernardsilenou** [comment]
> @bernardsilenou We can handle it as we do for other fields by taggin them as country specific.

But it can be possible that in a country having a non-centralized instance, some regions may need it and others may not.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.68.0-SNAPSHOT from the development branch.
