### ISSUE TITLE
Store accessible data in dedicated tables (PoC) [8]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7719]
### Feature Description

When we need to check which data a user has access to, e.g. when they enter a directory or synchronise data to their mobile app, we currently retrieve the accessible data on-the-fly, primarily by using user filters.

### Problem Description
 
The queries that are executed to retrieve this data can lead to significant performance issues because they - depending on the entity - have to join a lot of other tables, and they need to be executed everytime a user accesses this data.

For example, which persons a user can see depends on the cases, contacts, event participants, immunizations, and travel entries they can access, and all of this needs to be checked whenever a user retrieves the list of persons visible to them.

### Proposed Task

Create a proof-of-concept for the Case entity that makes use of a data access table instead of the current user filters.

* Create a `cases_access` table with the following columns: `uuid`/`id`, `user_id`, `pseudonymized`
* Whenever a case is saved with changes that affect user access (i.e. (responsible) jurisdiction, responsible user, or jurisdiction changes to connected contacts - [something might be missing here, check user filter and extend]), re-calculate user access for ALL eligible users in the database (i.e. users with the `CASES_VIEW` user right)
  * Find a way to do this, either in Java code or directly in the database
  * Decide when to execute this calculation; it might be necessary to not do this immediately when the data is changed, but in a separate thread that might be executed delayed depending on system load
  * The logic here is basically the current logic of the createUserFilter method
* Change all backend code that is used to retrieve a list of cases by means of the createUserFilter method to instead retrieve the list based on an IN clause that contains all uuids or ids of the cases the user has access to according to the `cases_access` table
* When a new user is created, its accesses for all cases in the database have to be calculated

### Additional Information

- Maybe try with a database dump from `test-performance` instance

**Comment by MartinWahnschaffe** [comment]
Since this would create an average of cases*(district officers + region supervisors) entries in the database, I was thinking about an approach on how to better replicate the actual access logic to reduce the amount of data created (and thus also the performance). 

Suggestion: Let's add region, district and community columns here as-well. Each entry in the access table will then bei either specific to a user_id or a jurisidiction and when looking for cases the user has access to, we search for access both by user id and the jurisidiction of the user (region or district or community).

This will allow us to reduce the number of entries per case to a few ones (region, district, community, creating user, responsible user + maybe the same based on the jurisdiction of a related contact).

**Comment by MateStrysewske** [comment]
Another suggestion: For each entity, create dedicated columns that each define one means by which a user (or user group) can gain access to the entity. E.g. for cases: `reportingUser`, `assignedUser`, `jurisdiction`, `responsibleJurisdiction`, `sourceContact`, `contact`, `shared` (potentially others). For each user (group) and case combination, set the respective column to true if the user gained access to the case by this means. When one of these properties is then updated when a case is changed, we don't always have to completely re-calculate user access, but we can use this information to check which users lose access to the case and which users might gain access.

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe and I had another discussion about this and agreed to implement the concept as follows:

* Create an `AbstractEntityAccess` superclass with the following columns: `reportingUser_id`, `assignedUser_id`, `region_id`, `district_id`, `community_id`, `facility_id`, `pointofentry_id`, `pseudonymized`
* Create a `CaseAccess` entity that extends `AbstractEntityAccess` with the following additional columns: `contact_id`, `sample_id`, `caze_id`
* For each case, store at least one row in the `caseaccess` table that contains the reporting user, responsible user, responsible region, responsible district, responsible community, health facility and point of entry
* For each case, store an additional row if the place of stay differs from the responsible jurisdiction that only contains the place of stay region, district and community
* For each contact of the case:
  * Store an additional row that contains the contact id, reporting user, responsible user, responsible region, responsible district and responsible community of the contact
  * For each sample of each contact:
    * Store an additional row that contains the contact id, sample id and laboratory (= facility) of the sample
* For each sample of the case:
  * Store an additional row that contains the sample id and laboratory (= facility) of the sample
* Write an SQL update script that populates the `caseaccess` table based on the current database entries
* When a case, contact or sample is changed, only if a field that is relevant for data acess has been changed, update the respective row in the caseaccess table according to the new values

**Comment by JonasCir** [comment]
With this design, how would the actual access control decision look like? On access attempt, take the current user and the accessed object and do a lookup in the table if the combination is allowed?

If I understand the issue correctly, currently there is no access control mechanism in place, we just relied on filtering out objects in the query based on the user's properties?

**Comment by JonasCir** [comment]
I mean this is scary to say the least.

But instead of doing a space intensive pre-computation, why not doing a normal lookup if the resource is accessible to the user?
Existing solutions/other projects likely rely on JWT to link an access rule set to a user, so on access attempt you only need to do a set lookup in case of groups and identity check for responsible user?

The approach above looks fairly complex and nonstandard to me tbh.

**Comment by MateStrysewske** [comment]
Access to individual properties will not be handled by this design, at least not in the first phase. We might very well think about using it for this purpose later though.

**Comment by JonasCir** [comment]
Alright thanks.
Having some sort of access control list in place is definitely better than just filtering the query. 

I was more thinking of something like this which does not include access to certain properties. Having an access scope of
[
 "user_a": {
   "cases": {
     "responsible_region": ["some_region", "another_region"]
     ....
     }
  "user_b": {...}
}

On accessing resource `/cases&responsible_region=some_region` you would only need to do a set contains check against the rule assignment, and if it succeeds, do a select with a filter for `some_region.`
If the user_a accesses `/cases` you iterate all responsible regions the user has access to and concatenates the result. 

By this, you have effectively confined the user and do not need to do expensive filtering in the DB, while having minimal runtime costs for the access control check. And you don't need to pre compute the access control decision, as the set lookup will cost as much as a lookup in the table.

**Comment by JonasCir** [comment]
I think this is can be realized with JWT and we can resort to established technologies  which would also benefit the Angular development team.

**Comment by MateStrysewske** [comment]
@JonasCir The performance problems we're facing does primarily come from joining additional tables, such as contacts or samples, and the two major parts of the application we're trying to improve here are the getIndexList calls and the getAllAfter calls from the mobile app. Whether a user has access to an individual case (and thus to a list of cases) depends on whether they're the assigned user, the responsible user, have access to the case through its responsible or place of stay jurisdiction, has access to at least one of the case's contacts, or is a laboratory user and has access to at least one of the case's samples. Whether or not a user has access to a case's contacts again does not only rely on the contact's jurisdiction, but also on the contact's responsible and assigned user.

So far we're always calculating this information on the fly. The purpose of the new table is to store this information so that it can be accessed quickly when needed. I'm not quite sure right now in which way the approach you're suggesting here would help with that task? Please also note that the Vaadin app does not use ReST to access its data, but directly interacts with the API.

**Comment by JonasCir** [comment]
Ok I see now, I think here are two issues at play: The performance issue that you referred to and the access control part that I was talking about. Turns out they are related and there might be an important insight for the development for rights and roles:

I was under the impression that access to an entity in SORMAS is only governed by a set of _fixed_ rules like "a user can see every case in its responsible region" and that these rules only make statements about properties of one entity type (in our example Case::responsibleRegion).
Formally, this is text-book role-based access control (RBAC) as e.g., user A could then receive group "responsibleRegion:Berlin". There is a straight-forward mapping to the query and it's cheap to get all cases.

However, obviously my impression was wrong as e.g., cases become visible/accessible to a user if he has access to another entity type. For example, access to a sample _implies_ access to the associated case.

In fact, these implied access rights are responsible:
1. for the performance problems, as we need to figure out which of the user's relations to other entities causes e.g., cases to become visble besides the fixed RBAC assignments
2. for my confusion why the hell you would need a static lookup table for a thing that you could simply select out of the DB :D However, it makes sense now as you cannot describe these access rights through roles, so you either have to dynamically compute them, or create an access control list/table and attach the rights to the user ahead of time


I think this shows that this is not just a perfomance issue, but also causes trouble for access control as we are not a pure RBAC system anymore.

So you can scratch, what I wrote before but, I think I found a way to shrink the table even more :)

What I propose is to remove the parts from the lookup table that can be easily computed with a simple where clause on the entity itself (e.g., Case::responsibleRegion). In fact, this will just be duplicated from the case table if I'm not mistaken.

This should yield a case_access table which holds all the cases accessible to the user which result from access on other entities and not on cases directly.

The answer to the auditors question of "What cases can user A access" would everything which its role allows + the rights granted to him in case_access.

**Comment by MateStrysewske** [comment]
@JonasCir @MartinWahnschaffe and I also discussed this (i.e. only putting information about entities that are accessible via other entities in the _access tables), but decided that a) the redundancy in data is less hurtful than having the information about which user can access which entity in different places, and especially b) this does work with first-level data, but we also need contact access information in the case access table in order to not be forced to join other tables. Keeping this information in the root entity does not work anymore at this point.

**Comment by JonasCir** [comment]
OK I understand, thank you for the explanation. With this you have now a fully enumerated access control list which you can base your access control decision on  :) 
One issue I see here is a potential inconsistency with existing dynamic checks.  If only `getIndexList` would go through the access table but e.g., `getByUuid` would stick to the old dynamic access check, there could be cases where one access is granted while the other is denied.
So I think we should either use the table for all DB accesses or use the _same logic_ to populate the table and do the dynamic decision.

**Comment by MartinWahnschaffe** [comment]
Note: In the end you could probably to RBAC based on this calculated access table. Not sure where/if this would be helpful, just wanted to share the thought.

**Comment by MateStrysewske** [comment]
The access table concept implemented for cases unfortunately did not lead to a performance improvement when accessing 1000 cases via getAllActiveCasesAfter. The query itself actually performed worse:

**Current implementation:**
Attempt 1: 6473 ms
Attempt 2: 3619 ms
Attempt 3: 3719 ms

**Case access table:**
Attempt 1: 7231 ms
Attempt 2: 5430 ms
Attempt 3: 5636 ms

Apart from this duration of the backend query, the bigger performance issues were the conversion into DTO (=> toDto), which took around 15~20 seconds, and especially the pseudonymization logic, which could take over two minutes to complete.

@StefanKock I unfortunately pushed the POC to #7734 instead of this issue.
