### ISSUE TITLE
Deselecting the "Enter home address of the case person now" check box does not remove entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7824]
### Bug Description

When a user makes entries in the home address section during case creation while the checkbox "Enter home address of the case person now" is active, they're not removed when the user de-selects the checkbox again. Thus, saving the case also saves the de-selected home address data.
### Steps to Reproduce

1. Create a case and select the checkbox "Enter home address of the case person now"
2. Enter location data 
3. De-select the checkbox
4. Save the case
5. Check the case persons home address

### Expected Behavior

When the checkbox is deselected, the input should be removed so it is not saved regardless
### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Reopening issue because when selecting facility and facility category after deselecting the checkbox and trying to save the case an error message for facility is displayed as seen in screenshot 1. 
Selecting the checkbox one more time, the user can see that the Facility category was deleted but is still expected. 

![7824_1](https://user-images.githubusercontent.com/70562142/152685457-b0403482-6940-46ee-b9f0-b62854afb8da.jpg)

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of sormas 1.68.0-snapshot on test1402.sormas.netzlink.com
