### ISSUE TITLE
"Detailed Export" taking too long [2]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#811]
"Detailed Export" taking too long from https://sormas.org.ng/sormas-ui/#!cases. Might be a memory challenge. Please review.

**Comment by Chinedar** [comment]
It eventually exports empty.

**Comment by MateStrysewskeSym** [comment]
We will provide some kind of a hotfix for this that will at least (hopefully) make sure that the export is working, even though it will still take long. To really fix this issue, we will need to adjust the whole export logic.

**Comment by MartinWahnschaffeSymeda** [comment]
### Detail export:
- [ ] getExportList needs to directly select into CaseExportDto (see getIndexList)
- [ ] add first and max params to limit the number of queried entries
- [ ] change the list supplier to a BiFunction that returns 'max' entries starting with entry 'first'

### Basic export
- [ ] directly write into CSV instead of writing to a list of string lists first

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] FacilityHelper.buildToString -> buildFacilityString. Call this method from the other buildFacilityString method and then add details
- [ ] add comment to for block in CaseFacade.getExportList to mark which part can be sped up (e.g. symptoms could be persisted as string). Same for contacts
- [ ] increase step size of DownloadUtil.createCsvExportStreamResource to 200
