### ISSUE TITLE
Allow entering of home address for existing persons with empty home address [1]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#8213]
### Problem Description

When creating a case with a chosen existing person the checkbox "Enter home address of the case person now" is always disabled, even if the home address of the person is empty.

### Proposed Change

Enable the checkbox if the address of the person is empty because in that case, users might want to add it at this point rather than having to enter the person page and enter it there afterwards.

### Acceptance Criteria

- [x] When creating a new case for an existing person, the checkbox is disabled if the home address of the person has at least one field that is not empty
- [x] Otherwise, the checkbox is enabled and the user can create a home address for the existing person
- [x] `LocationDto.checkIsEmptyLocation` is used to check this, and its implementation has been extended according to the specifications below

### Implementation Details
Extend `LocationDto.checkIsEmptyLocation`:
- Use `StringUtils.isNotBlank` for String fields instead of a simple null check
- Add all missing fields that are currently not checked in this method

**Comment by adinaflorea9** [comment]
Also consider enabling the person related fields when creating entities with a chosen existing person, if the person related fields are empty (currently the fields become read only when the person search option is used, regardless of whether there is person related information in them or not).

![image](https://user-images.githubusercontent.com/96909231/157424894-def8087d-2816-4fa1-966e-3d4e5c7b536e.png)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following - the checkbox 'Enter home address of the case person now' is not editable in the for a person that previously has the country set in the 'Home address' section.

Steps to reproduce:
1. Create a new person (via any entity) and do not set any values in the 'Home address' section;
2. Check that when creating a new case for this person, the 'Enter home address of the case person now' is editable (expected that it is);
3. Set a country for the person in the 'Home address' section of the person page;
4. Check that when creating a new case for this person, the 'Enter home address of the case person now' is not editable (expected that it is not editable);
5. Go to the person page again and clear the value from the 'Country' field and make sure to save those changes (either via the regular 'Save' button or via the 'Save changes' button from the dirty check pop-up);
6. Check the form for creating a new case for that person.

Actual behavior: the checkbox for 'Enter home address of the case person now' is not editable even though the person does not have any home address related fields filled in.

Expected behavior: the checkbox should be editable as the person does not have any information in the 'Home address' fields

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(44bfee6).
