### ISSUE TITLE
Authorize generic facade api methods [2]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#8352]
### Feature Description

There are more and more generic methods implemented in the api and those methods should be authorized.
e.g. `AbstractCoreFacadeEjb::save, AbstractCoreFacadeEjb::delete, AbstractBaseEjb::archive, AbstractBaseEjb::dearchive`
This is a followup ticket of #5057. 

### Problem Description

Authorizing generic methods is not straightforward so a solution is needed that fits all the needs and can be used in all facades.

### Proposed Change

Implement option 1. of Possible Alternatives

- [x] Annotate *AbstractCoreFacadeEjb::archive* method **DenyAll**.
- [x] Add  *archive* method in subclasses of *AbstractCoreFacadeEjb* annotated with `@RolesAllowed` using the correspointding *_ARCHIVE user right and calling the private on the super class.
Like the following in CaseFacadeEjb
    ```
    @RolesAllowed(UserRight._CASE_ARCHIVE)
    public void archive(String entityUuid, Date endOfProcessingDate) {
	    super.archive(entityUuid, endOfProcessingDate);
    }
    ```

Similar 
- [x] Do it for *AbstractCoreFacadeEjb::dearchive*
- [x] Do it for *AbstractCoreFacadeEjb::save*
- [x] Do it for *AbstractCoreFacadeEjb::delete*
- [x] Do it for *AbstractSormasToSormasInterface::share*

### Possible Alternatives

1. AbstractCoreFacade only provides protected methods that have to be called from a correctly annotated method in the specfic facade, e.g. public CaseFacadeEjb.archive will call protected AbstractCoreFacade.archive.
2. The generic method does a check for the corresponding user right that is provided by the implementing Facade. E.g. AbstractCoreFacade.archive calls CaseFacadeEjb.getArchiveRights.
3. ~~Create an interceptor and custom annotations e.g. @CanEdit on the generic method and @AllowedUserRIghts(edit = UserRight._Case_EDIT) on the concrete facade implementation (similar to @AttributeOverride for entities)~~

**Comment by MartinWahnschaffe** [comment]
I have added two alternatives to the list, because I'm not eager to have another interceptor in the list (note that the interceptors will be called for every single ejb call). Also I'm not sure how well the annotations would work. It seems to be too easy to forget about those.

I'd prefer to pick option 1. I think the methods that need to be annotated are so important that it's preferable to have them in the source code of the spefic facade. Even if it just looks like 

```
@RolesAllowed(UserRight._CASE_ARCHIVE)
public void archive(String entityUuid, Date endOfProcessingDate) {
	super.archive(entityUuid, endOfProcessingDate);
}
```

**Comment by cazacmarin** [comment]
Small but very important comments: 

 - Were fixed 2 tests which failed due to novatec.beantest framework which is used(and outdated): PersonFacadeEjbTest.testGetPersonsAfter & CaseFacadeEjbTest.testMergeCase - in one of the tests save is called twice however entity is saved at creation.
  - Me and Levi did not get really the point about `save method` with @Denyall annotation why it is not working as expected. As for archive and other methods all is working fine. Error which is giving at creation of a case from vaadin (Sormas UI), it says `Corba exception - unauthorized` -> due to that, was used the workaround with method renaming.
  - Performed some manual test to be sure that save/archive for case/events/contacts are working.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup using the latest version of Sormas 1.71.0-snapshot
Verified the Archive + De-Archived with Admin user  + Case Sup + AdminSurveillance
