### ISSUE TITLE
Visits can be done for contacts coverted to cases

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#844]
New visit can be done for a contact that has been converted to case. this should not be possible except the contact is converted back to a contact which is also unlikely.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym @bernardsilenou  The reason why we should not disable contact follow up for converted case, is because when they become symptomatic, they are moved to the isolation ward. Even though its only headache. Then after blood tests and all are done, and the test turns out negative depending on the disease, the converted case reverts back to be a contact and is followed up for 21 days because the contact who was converted to case was exposed in the same room or building as the other suspected cases who might have become a confirmed case. This is not part of the incubation period but is a standard practice to ensure no Nosocomial Infections. However, i will agree with Bernard that as long as a contact remains converted to case, he should not be able to have any visits done. The system should allow the flexibility to convert to a case and revert decision and restore as a contact. In this case, disable automatic tasks and allow manual manipulations. Let me know if you have any other clarification needs

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Thanks for your suggestions, however, they don't tackle the problem with retrospective data entry I mentioned. Could you please elaborate on that as well?

**Comment by bernardsilenou** [comment]
General comment:
It is not good to have retrospective creation of visits in the system, this will magnify the visits statistics, for example the number of missed visits will be large. Although at the back end, contacts actually means "edges" linking two nodes(persons), in transferring this information to epidemiologist, when we say contacts, we should focus on contact persons not contacts in the design sense. In this regard, if a contact in converted to a case, we mean a contact person has become a case, at this instance the person is existing in the system as a case thus all attribute of a case applies to this person NOT attributes of contact person like visits. A person should only exist in the system in one instance as either case or contact not both as it currently is. For a contact person who had contact to two different cases,
if one of the contacts (not contact person) is converted to case, this contact person should be converted to a case and no visit should not be able to be done for for the other contact.  The system should allow contact to be converted to case and vise versa. When a contact is converted to case, visits should not be possible, is some one tries to do a visit , the system should tell  him that this contact is now a case and give  the possibility of the supervisor to convert the contact (case) back to a contact.

For retrospective data:
1 You cannot have a retrospective data with a contact converted to case and visits continue after the date of conversion which is usually the last date of follow-up visit.
2 if the contact became a case on visit 5, then the person entering the information in sormas will enter all the visits done in the past and on day 5 convert
the contact to a case and no visit will be enter further. 
3 Concerning automatic task generation by the system, if the date of last contact with case compared to current date is  >> incubation period of the disease, 
the system should not create automatic task to the users. this will just unnecessarily increase the number of pending task.

**Comment by bernardsilenou** [comment]
In addition to general comment: It can occure that a case and a contact are refered to the same person in the system for example in source tracing or a person who had contact to 2 different cases become a case as a result of one of the 2 contacts.  When this happen, visits should not also be possibe for the person but the contact (edge) should stay in the system.  If the disease is different, then visits should be possible even if the contact person is converted to case for another disease.

**Comment by MateStrysewskeSym** [comment]
Alright, thanks for the clarification. We'll disable the creation of visits for converted contacts then.
