### ISSUE TITLE
Permanently deleting samples associated to cases leads to errors

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8605]
### Bug Description

During the introduction of permanent case deletion, it was also introduced that samples are permanently deleted alongside their associated cases; however, permanent deletion is currently not properly implemented for samples, so the whole operation fails when there is a pathogen test or any other entity in the database that refers to this sample.

### Expected Behavior

- Only soft-delete samples associated to permanently deleted cases for now, instead of permanently deleting them
- Also remove the sample from its associated case in the `delete` method (because otherwise there will be a foreign key constraint violation error when trying to delete the case from the database)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment using the latest version of Sormas 1.70.1 hotfix branch.
Tested this by enabling the permanent deletion of cases older than 14 days and by manipulating the ChronJob to execute every 10 minutes. 
Added Samples to the targeted Cases and once the deletion occurred because of the ChronJob, I was able to validate that also the Samples were soft deleted.
