### ISSUE TITLE
Name Heading doesn't show ß correctly

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8649]
### Bug Description

If there is a name with "ß" in the name, it is shown as "ss" in the entity heading with the name.

### Steps to Reproduce

1. create a case/contact with "ß" in name
2. check the name heading 

### Expected Behavior

It should show the correct typed name.

### Screenshots

![ss und ß](https://user-images.githubusercontent.com/78568406/161040558-c1b8afb9-79b5-4731-ba9d-73c3ef753335.JPG)

### System Details

* Device:
* SORMAS version: 1.69.1 
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

- Link concerning big letter for ß: https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F
- `TitleLayoutHelper.buildPersonString` calls `PersonDto.buildCaption` that uses `DataHelper.toStringNullable(lastName).toUpperCase()`. Looks like this Java feature does not know about capital ß.

**Comment by dinua** [comment]
this bug is a common java problem when we do upperCase for ß  . The lastname is displayed in upper cases

**Comment by StefanKock** [comment]
Options: No uppercase, or try to replace with capital ? with risk of fonts not supporting that

**Comment by JaquM-HZI** [comment]
@dinua and @StefanKock Since 2017 there is the ß as upper case **ẞ** so is it just not available in java?

**Comment by StefanKock** [comment]
It's partly about Java, more about rules how to convert to uppercase and if the upper case ß = ẞ exists in fonts that are used in browsers.

**Comment by MateStrysewske** [comment]
@KristinaBorch @kwa20 @JaquM-HZI The font we're currently using probably does not support the capital ß and therefore falls back to a default browser font in order to display it. I don't think there's anything we can do about it other than changing the font we're using, but that would be way out of scope for this issue. I'll close it again therefore, and would ask you to open a separate change request if you decide that the font should be changed.
