### ISSUE TITLE
Clinicians cannot create samples for contacts

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8738]
### Bug Description

Creating a sample for a contact as a clinician results in an error. No samples can be created.
### Steps to Reproduce

1. Log in as a clinician
2. Open or create a contact
3. Create a sample for this contact
4. Enter compulsory fields and save

### Expected Behavior

Clinicians should be able to successfully create a sample for contacts
### Screenshots

![contactSampleCreateClinician](https://user-images.githubusercontent.com/70317594/162012069-134cef1d-b1f8-4992-a710-c0b72a73e56d.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Clinician

**Comment by MateStrysewske** [comment]
We had a talk about this and decided that onEntityChanged methods (e.g. onContactChanged, onCaseChanged) should be permitted to be used by all users (because they are never called directly by the user, but as a result of other operations, and should always succeed because they're executing internal logic that is necessary for data integrity).

**Comment by vidi42** [comment]
Follow-up ticket to implement a unit test which checks that the onEntityChanged methods are not called abusively https://github.com/hzi-braunschweig/SORMAS-Project/issues/8765

**Comment by adinaflorea9** [comment]
Tested ticket on the local machine, using SORMAS version 1.70.2-SNAPSHOT from the hotfix-1.70.2 branch.

I am re-opening the ticket due to the following behavior: adding a sample with a positive pathogen test result to a contact, generates a case that is not associate with either the sample or the contact.

Steps to reproduce:
1. Log in with a 'Clinician' user and open or create a contact;
2. Add a sample with a positive pathogen test result to the contact from step1;
=> 'Create case from contact with positive test result?' pop-up is triggered
3. Click 'Yes' in the pop-up;
=> 'Create new case' form is triggered
4. Fill in the mandatory fields with valid information and click 'Save';
=> A warning message is displayed:
![image](https://user-images.githubusercontent.com/96909231/162452854-6a9b25c4-0c34-47f0-98e1-4f92498fdf5e.png)
5. Refresh the page.

Actual behavior:
- on the contact page: the sample is saved;
- in the cases directory: new case was created (it has the person information of the contact from step 1; the sample created at step2 is not associated with the case);
- in the samples directory: the sample from step 2 is only associated with the contact from step1.

Additional information:
A 'Clinician' user does not have rights to: CONTACT_EDIT; CONTACT_CLASSIFY; CONTACT_CONVERT

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the hotfix 1.70.2 branch.
