### ISSUE TITLE
Persons cannot be registered in climedo

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8739]
### Bug Description

Persons cannot be registered in climedo independent of whether phone only or both, email and phone are used.
### Steps to Reproduce

1. Create a case or contact and enter respective person contact information
2. Register the person in the climedo diary

### Expected Behavior

Persons with valid person contact details should be successfully registered in climedo
### Screenshots

![climedoError2](https://user-images.githubusercontent.com/70317594/162013392-4bc6fe66-a2ea-440d-9f23-94df555f8c36.PNG)
![climedoError](https://user-images.githubusercontent.com/70317594/162013399-91ffa3a5-0cde-4752-9d50-5b85805d221b.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Attaching the Stack trace for this error :
[test1402_stack_trace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8440423/test1402_stack_trace.txt)

**Comment by FredrikSchaeferVitagroup** [comment]
This bug most probably relates to a wrong configuration of the https://test1402.sormas.netzlink.com/ instance.

We've had the same problem on https://ga1.sormas-oegd.de/, and solved it there.

The related netzlink Request ID :##RE-2022126425##. Current status is that netzlink needs to migrate the fix to other test and release instances.
For test1402, I happen to have database access, so I migrated the fix myself. After the next restart, the expected behaviour should show.

There's nothing to be changed in the SORMAS code, so I will discard this ticket.

**Comment by FredrikSchaeferVitagroup** [comment]
Btw, to later improve the behaviour of SORMAS to not show a generic error message here, there already exists a [ticket](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8640).

**Comment by FredrikSchaeferVitagroup** [comment]
Netzlink reported that https://test1402.sormas.netzlink.com/ was restarted. I quickly checked, and could now register a person in climedo.
