### ISSUE TITLE
Don't redirect the user when a form contains errors

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#8752]
### Bug Description

Mandatory field validation needs to be triggered upon trying to navigate before unsaved changes prompt gets triggered. Otherwise, all changes are discarded despite selecting save changes. 

### Steps to Reproduce

1. Click on different symptoms + Click on "Other Symptoms"
2. Do not save, click next tab (hospitalization)
3. Message comes: save changes?
4. Yes
5. Error message: Please check the input data: Specify Other Symptoms
6. Close message with X
7. Bug: The whole symptom page is not saved, entries are lost

### Expected Behavior

It must be ensured that user entries are saved.
Checking the mandatory fields and saving must not mutually hinder / exclude each other.
The logic must be installed in all areas where you can switch between different tabs.
It must be available for all user roles.

### Development Instructions
Depending on what is easier to implement:
- Validate the form before showing the navigation prompt and show the validation errors instead of navigating if there is one; I believe that this will be pretty hard to do.
- When the user clicks on "Save" in the navigation prompt and the form contains errors, suppress the navigation (and instead show the validation error).

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: Chrome
* Server URL:  https://test1401.sormas-oegd.de/ and https://release-international.sormas.netzlink.com/
* User Role: for example: admin, Clinician International, Contact Officer & Surveillance Officer Germany

**Comment by MateStrysewske** [comment]
@KernB Hey! Thanks for the bug report!

Manually doing the validation before bringing up the navigation prompt would probably be quite complicated. I'd suggest that we instead suppress the navigation if the form contains errors (at least if that's easier to implement).

**Comment by adinaflorea9** [comment]
Tested the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(9c0e90c).

I am reopening the ticket due to the following behavior that can be reproduced on a person page (travel entry; immunization), case page(immunization, link event), contact page (immunization, link event), event page (link subordinate event) or event participant page (contact; immunization):
**Steps to reproduce:**
- navigate to a person page;
- trigger the validation for a field;
- add new travel entry (when the card is on the respective page);

=> 1. user is no longer redirected to the new travel entry's page (this is the regular behavior) even after updating the data in the filed and clearing the validation; same applies for adding immunizations;

=> 2. the new travel entries and immunizations appear on the person page as linked in their respective cards only if the user refreshes the page;

GIF1:
![Link Event](https://user-images.githubusercontent.com/96909231/164000706-d09fce7a-8edd-41ea-85c2-6944f39ed1da.gif)

GIF2:
![Immunization](https://user-images.githubusercontent.com/96909231/164000795-648d0c0b-eb45-4708-932f-2d4067187e30.gif)

GIF3:
![link subordinate events](https://user-images.githubusercontent.com/96909231/164000827-98862890-512b-4db8-a3b4-db5ccb0b15d1.gif)

**Comment by adinaflorea9** [comment]
Tested ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(78596ba). 

I am reopening the the ticket due to the following behavior: on a contact page, after triggering an error in the 'Report Date' field, if the user clicks on 'Create a case for this contact person' and fills in & saves  the 'Create new case form', the case appears linked to the contact only after refreshing the page; the 'Confirm navigation' pop-up is triggered twice and it is displayed only after the 'Create new case' form is closed.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(d0b4148).
