### ISSUE TITLE
Sorting of the Directorys

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#8755]
### Bug Description

- Sorting numbers (e.g. house numbers) treats the data as strings instead of numbers.
- There are also empty entries at the beginning and end of the list (e.g. street)
- "Completeness" and "Number of Visits" cannot be sorted (Persons directory)

### Steps to Reproduce

1.
2.

### Expected Behavior

For all directories, the fields are sorted according to their data type. 
All empty fields are displayed together at the beginning or end of the list. 
All displayed fields are sortable.
All user roles get the new sorting.

### Screenshots

![Directory](https://user-images.githubusercontent.com/101708230/162215757-5055bbb2-e92b-4a61-8bef-725e36fd21e5.png)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/ and https://release-international.sormas.netzlink.com/
* User Role: for example: admin, Clinician International, Contact Officer & Surveillance Officer Germany

**Comment by MateStrysewske** [comment]
@KernB There are certain columns that we can't make sortable because we have to do the sorting in the database (due to the lists being lazily loaded), and some of these values are computed and not available at that point in time. Since the house number field is indeed a string field in the database because it can also contain non-numeric characters, I don't believe that we can do a proper integer sorting here. The "empty" entries in the street field that are sorted first are probably whitespaces; I agree that this is not desirable and have created a follow-up issue that we need to refine: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8760.

I'll close this issue, but feel free to respond again if you believe that we need to do more here.
