### ISSUE TITLE
[Audit] log REST login fail

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8815]
### Login failure for REST API

Split from #8790  as implementation is a little bit trickier than expected.

- [ ] Add method to `AuditLogger`
- [ ] Define log format
- [ ] audit placed in `MultiAuthenticationMechanism`

**Comment by JonasCir** [comment]
Ok this is significantly harder to implement than I anticipated. Problem here is that the `KeycloakHttpAuthenticationMechanism` used in `MultiAuthenticationMechanism` is invoked when sending wrong credentials along a REST request, however, it will return `httpMessageContext.doNothing()` and do not touch the request at all. The handling of the request continues to go through a quite an amount of JavaEE functions till it reaches the request filters. There, `KeycloakFilter` delegates to `KeycloakOIDCFilter` which will interact with Keycloak and validate the token. Problem is that this filter creates a response and terminates the request internally, such that the filters will never see the result of the operation, therefore, we cannot audit it.

What is strange is that in case the credentials are valid, the `KeycloakHttpAuthenticationMechanism` is invoked a second time where it now picks up the request as some context is now available. 

In case we use the legacy login, the `BasicAuthenticationMechanism` directly kicks before the filter chain.

Can we discuss this @MartinWahnschaffe @vidi42

**Comment by vidi42** [comment]
@JonasCir 
Keycloak has an event functionality that logs logins and login errors. We could consume those instead of relying on the MultiAuthenticationMechanism.

This is how it looks like on test-de2
![image](https://user-images.githubusercontent.com/3462897/164165723-466c9576-498f-4990-8513-34a46aebabb8.png)

And we can use the Keycloak API to get and log those.
See https://www.keycloak.org/docs-api/16.0/rest-api/index.html (Get events Returns all events, or filters them based on URL query parameters listed here)

Or we could just use those as audit logs instead of having them on our side.

**Comment by JonasCir** [comment]
Yeah I mean one part of the logging concept was concerned with Keycloak anyway, so it makes to gather an ship logs from the source directly instead of going through the application layer again.

Thanks for screenshot! I'm talking this through with Martin :)

**Comment by abrudanancuta** [comment]
validated on local env together with @JonasCir
