### ISSUE TITLE
Permanent deletion violates foreign key constraint "fk_contact_resultingcase_id" on table "contact"

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8847]
### Bug Description

An error/exception thrown stops the permanent deletion of entities.

### Steps to Reproduce

1. In the Data Base, in the 'deletionconfiguration' for 'CASE' set the 'deletionreference' to 'CREATION' and the 'deletionperiod' to 2 (or another amount of days);
2. Update the CronService.java - 'deleteExpiredEntities'  - to be executed every 5 minutes;
3. Observe the amount of entities in the UI and the DB that are within the time frame - i.e. created more than 2 days ago (cases, contacts, or any other entities associated with them);
4. Wait for the 'deleteExpiredEntities' to run;
5. Check the logs.

### Actual Behavior

An error is thrown and the entities are not deleted either from the UI or the DB.

### Expected Behavior

No server error is logged; permanent deletion of entities is successful.

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(9383bd6)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information

- Logs from the local machine are attached in the first comment.
- Looks like we have sibling ticket with #8851. Is there an overall pattern that should be fixed together?

**Comment by adinaflorea9** [comment]
[Logs.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/8506027/Logs.zip)

**Comment by MateStrysewske** [comment]
Relevant for 1.70.3. The problem is that the `ContactService.getAllByResultingCase` method excludes deleted contacts.

**Comment by MateStrysewske** [comment]
We seem to have the same problem for travel entries that have the deleted case as their resulting case.

**Comment by mario-kuehne** [comment]
**Reproduction**

Reproduction (locally) with branch 'development' Version: 1.71.0-SNAPSHOT (9383bd6) 
1) Create Contact A with all mandatory fields
2) Open Contact A
3) Set Contact Classification to "Confirmed Contact"
4) Save Contact A
4) Click 'Create a case for this contact person'
5) Fill all mandatory fields in modal dialog 'Create new Case' and save case C  => the column 'resultingcase_id' in database table 'contact' for Contact A now has a reference to the case C
6) Set 'deleted' column in database table 'contact' for Contact A to 'true' (or optional: manually trigger a soft-delete of the Contact A through UI)
7) Set 'deletionreference' == CREATION for entitytype 'CASE' and a custom deletionperiod (e.g. 20 days)
8) (Optional) Set 'CronService.deleteExpiredEntities' to a suitable schedule for test purposes (e.g. every minute)
9) Set 'creationdate' in database table 'cases' for case C to a value earlier than configured deletionperiod
10) Exeption occurs when automatic deletion of case C gets triggered: 
`Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "cases" violates foreign key constraint "fk_contact_resultingcase_id" on table "contact"
  Detail: Key (id)=(553) is still referenced from table "contact".`
