### ISSUE TITLE
External Lab Officer cannot edit samples because they can't be assigned to a laboratory

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8892]
### Bug Description
External Lab Officer cannot edit samples

### Steps to Reproduce
1. Have some samples create with "Purpose of the sample": External lab testing
2. Login as External Lab Officer
3. Open a sample in edit mode and try to change some data in it

### Actual Behavior
None of the fields are editable

### Expected Behavior
All fields should be editable - this can probably be fixed by allowing external lab officers to be assigned to a laboratory (and making that mandatory), i.e. same as for a normal lab officer.

### Screenshots

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/91872179/164216506-b30d39b3-34a9-4608-a3b2-0a17603ab9c9.png)

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@Chinedar What's the original idea about which samples external lab officers are allowed to edit and which not? Pretty sure there has been stuff happening in the meantime that changed this logic, but I can't recall how this was initially designed to be. Can you help us out here?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- Just as lab officers, external lab officers can edit samples  + pathogen tests of the samples assigned to their lab. The only addition contains that I think we thought of adding to the external lab officers is that they should not be able to edit all the attributes of the sample, eg final lab result, and date dispatch. To me I think this additional contains is not needed and we can give external lab officers full assess to sample,  as long as the sample is assigned to the lab of the user.

**Comment by vidi42** [comment]
The sample is not editable because the user most likely doesn't have the jurisdiction to do that.

**Comment by MateStrysewske** [comment]
@bernardsilenou Exactly as @vidi42 said, external lab officers can't be assigned to a laboratory. That might actually be the root problem here because this might've been an unintended change?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
You are right, I think we should give them the option to have an associated laboratory.
The only difference from a normal lab officer is that the country of the external lab would not be the country of the instance, so al sensitive data would be confidential but they would ba able to edit pathogen test, additional test + final lab results

**Comment by MateStrysewske** [comment]
@Chinedar @bernardsilenou I've put some more thought into this and am pretty sure that external lab officers were never assignable to a laboratory in the first place because we didn't even have the possibility to add jurisdictions outside the server country for a long time. Can you recall which ruleset we used to decide which samples external lab officers were allowed to see and edit and which they weren't?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
When we added external lab user role, we did not have the multi country point of view even though the user is based outside the server country. 
The rule is that external lab officers view sample assigned to their lab but do not see sensitive data of the associated person. In addition, they can not edit sample data but can add new pathogen test to sample

**Comment by bernardsilenou** [comment]
But authomatic classification for final lab result of sample should be possible for test created by ext lab user

**Comment by MateStrysewske** [comment]
@bernardsilenou Aaah, I just realised that laboratories don't need to be assigned a region, district, etc., so that makes sense. Alright, that means that the fix here is probably to simply allow to assign external lab officers to a laboratory again.

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because of the following findings:

- An error is thrown when the user adds a Pathogen Test:

![image](https://user-images.githubusercontent.com/89522688/176657053-649f68c5-cad0-47c4-b12c-7a51e933a9e5.png)

- An error is thrown when the user adds an Additional Test:
![image](https://user-images.githubusercontent.com/89522688/176657075-b71eb20b-a156-4bdf-8ff1-4816d091a995.png)

- 'Refer to another laboratory' is clickable and the user has SAMPLE_TRANSFER user rights, but when he clicks on it, nothing happens:
![refer to another lab](https://user-images.githubusercontent.com/89522688/176668945-09efc7ad-08e0-41c8-8314-f695be7d7457.gif)
