### ISSUE TITLE
Cannot register Sormas  patient user to Climedo 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8931]
### Bug Description
Cannot register Sormas  patient user to Climedo 

### Steps to Reproduce
1. As NatUser have a Contact with valid email address created that is not registered in Climedo
2. Try to register the Contact in Climedo

### Actual Behavior
An error message appears when clicking on "Register in Climedo Ediary"

### Expected Behavior
Contact should be registered in Climedo

### Screenshots

<img width="1440" alt="Screenshot 2022-04-22 at 11 50 10" src="https://user-images.githubusercontent.com/91872179/164682665-c0148f86-1f6e-4bd7-b7de-38a8d0352706.png">

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT (20b3763)
* Android version/Browser:
* Server URL: https://ga1.sormas-oegd.de/
* User Role: NatUser

### Additional Information

[ErrorClimedoRegister.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8539744/ErrorClimedoRegister.txt)

**Comment by FredrikSchaeferVitagroup** [comment]
It seems that calls to  `{{environmentUrl}}/sormas-rest/visits-external/person/` return a 403 now for users with REST_EXTERNAL_VISITS user right (and seemingly also with more rights). That's probably the underlying issue.

**Comment by FredrikSchaeferVitagroup** [comment]
There's messy behaviour showing.
When trying to fetch person data with the request `{{environmentUrl}}/sormas-rest/visits-external/person/{{personUuid}}`, I am getting a `403 Forbidden` on both test instances https://ga1.sormas-oegd.de/ (where the interface seems to be broken) and https://test1402.sormas.netzlink.com/ (where the interface seems to still work).
On my local system, all requests seem to work as expected. 
Maybe netzlink is now whitelisting IPs for requests to sormas-rest, and they didn't whitelist climedo for https://ga1.sormas-oegd.de/?

**Comment by FredrikSchaeferVitagroup** [comment]
I asked a netzlink employee.

**Comment by FredrikSchaeferVitagroup** [comment]
The bug ocurred because some wrong configuration reappeared on ga1.

There were 4 rights defined in the custom uerrolesconfig for the REST_EXTERNAL_VISITS user role. All of which are also default. But the default includes two more rights, SORMAS_REST and EXTERNAL_VISITS. The custom userrole lacks those two rights.
This was not noticed in versions before 1.70.0, because for some actions it was just checked for the role or the requesting user. In the new versions, it is checked for rights instead.

Previous related tickets are https://github.com/hzi-braunschweig/SORMAS-Project/issues/8739 and RE-2022126425 on netzlink side.

Netzlink states that the errorneous configuration is permanently removed now. I succeeded registering a person in climedo on ga1 a few minutes ago.

What remains a little weird is that I can not make external journal request to [test1402](https://test1402.sormas.netzlink.com/) (-> 403) , even though the external journal interface seems to work correctly there. But that is not subject of this issue

**Comment by FredrikSchaeferVitagroup** [comment]
It seems that this problem reappeared. The custom user roles config does not seem to be responsible this time, as it is not in the db.

**Comment by FredrikSchaeferVitagroup** [comment]
Yesterday's investigation indicated that the problem may have to do with some invalid user role configuration that remained in keycloak. After removing them with [this script](https://github.com/hzi-braunschweig/SORMAS-Project/issues/7820#issuecomment-1057038897), the interface worked again.

**Comment by vidi42** [comment]
So it seems this is not related to the Keycloak roles or other roles and rights in SORMAS, but a setup issue. 
@FredrikSchaeferVitagroup I would say we can close this again
