### ISSUE TITLE
Addition of age categories to aggregate module (mSERS) [5]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#8967]
### Situation Description

Aggregated reporting (mSERS) can be used as an alternative to case-based reporting. It currently allows to report number of reported cases, confirmed lab results and deaths for each mSERS-disease per epi week,

For certain disease it's necessary to report these numbers for different age groups (based on the age of the people). 

### Feature Description

* A technical admin should be able to define age groups for each disease using the database. Not all disease have the same age groups and some disease don't need them at all. The age group is not also the same for all instances and can change over time for an instance.
  An example would be 0-28 day, 0-11 months, 12-59 months, 1-4 years, 5-15 years, > 15 years
  This could be limited to a maximum of 8 per disease
* When creating a report using the mobile app and the web app the reporting user needs to be able to enter those numbers for each age group
* The aggregated reports view in the web application needs to display and export these age groups

Examples:

disease | age_group | Total New cases | Total lab confirmed | Total death
-- | -- | -- | -- | --
Covid-19 | 0-28 days |   |   |  
|| 0-11 months |   |  
|| 12-59   months |   |  
|| 1-4 years |   |   |  
|| 5-15 years |   |   |  
|| > 15 years |   |   |  
Meningitis | 0-28 days |   |   |  
|| 0-11 months |   |  
Cholera | 12-59 months |   |  
|| 1-4 years |   |   |  
|| 5-15 years |   |   |  
|| > 15 years |   |   |  
Anthrax | 0-28 days |   |   |  
|| 0-11 months |   |  
|| 12-59   months |   |  
|| 1-4 years |   |   |  
|| 5-15 years |   |   |  
|| > 15 years |   |   |  

#### Date Model

- [x] Add an agegroups field to the disease configuration that allows to define a comma separated list of age groups. Each age group is defined following a simple pattern:
  XA_YB, where X is the "from" age, Y is the "to" age (both inclusive) and A/B is the age type (D: days, M: months, Y: years).
  You can leave the _Y away to define an age group of X+.
  Examples:
  * 0D_28D: "0-28 days"
  * 1M_12M: "1-12 months"
  * 1Y_4Y: "1-4 years"
  * 5Y_15Y: "5-15 years"
  * 16Y: "16+ years"
- [x] Add an age group field (string) to the AggregateReport entities (backend & app) and dtos and the sync process
- [x] Create an utility method that checks whether an age group definition is valid and one that return the caption for it.

#### Report creation in UI

![grafik](https://user-images.githubusercontent.com/23217632/166430163-c9eaf197-fff4-4828-973e-565eecdbd3ae.png)

- [x] Make the disease name bold in the creation form
- [x] When the disease uses age groups, but the disease caption in a dedicated line and add one data entry line for each age group (see mockup)

#### Report creation in app

- [x] Same as in UI

#### Aggregated reports view in UI

- [x] Add a new age group column to the grid
- [x] Group the data by age groups. **Important**: To group don't use the age groups provided by the disease configuration. Instead use the age groups that are used in the actual reported data. Age groups for a disease may be changed over time and thisway we can also display old data without problems.
- [x] Make sure this also reflects in the export

### Additional Information

[aggregate_module (1).ods](https://github.com/hzi-braunschweig/SORMAS-Project/files/8570122/aggregate_module.1.ods)

### Out of scope

This will go into a separate issue:

As a surveillance officer (SO)

- I want to have the feature to document aggregate data on the mobile app and also on the web app. This feature exists already for national users. #9052
- Since SO are limited to districts, the region and districts should be preselected on the creation form and SO should not be able to create reports outside their jurisdiction. SO should be able to create a report for a facility in their district. #9052
- Add a reporting user on the edit form of each report
- There is no possibility to edit a report (either as SO, national user), if a user resubmits another report in the same week, system does not detect them as duplicates but considers them as independent + sum the counts. It would be good to have the option to edit a report. I have add another issue for duplicate detection #9039

**Comment by MartinWahnschaffe** [comment]
### UI Mockup
Left side is how mSERS currently works. Rights side is the proposal. This is a mockup of the web application, but the mobile app would look almost the same.

![mSERS](https://user-images.githubusercontent.com/23217632/166206539-bdf45e3f-1213-46da-a96d-4c8dbed14a8d.png)

When age groups are supposed to be entered for a disease, the name of the disease will go into a header line. The following lines each list the three date entry fields for one age group.

**Important**: From my point of view we should not include the sex here. It would lead to another multiplication of fields. E.g. for covid the user already has to enter 6*3 = 18 fields. If we include the sex as-well it would be 3-4 times more (54 or 72).
@KristinaBorch @bernardsilenou If you agree, please update the issue name and description accordingly.

### Surveillance Officer
We can give the default user role of the surveillance officer the right to create aggregate reports, but we should discuss the following points first:

1. The numbers reported in this report would be **added** to what is reported from other sources, e.g. by a hospital informant for a health facility in the same district. This may be un-intuitive for users. Please let me know whether this is clear to you and whether we should somehow address it (e.g. by writing a clear message when someone reports numbers for a district or maybe even a whole region).
2. The mobile app does not give surveillance officers (or other users) the ability to look into what has been reported by other users or to see the total numbers for their district. If we want to have this, we should create another issue for it and have to decide how it should work. 
3. The web app currently only comes with an aggregated view. From my point of view it misses the feature to list and edit the individual mSERS reports given by different users. E.g. it also means that I can add a new report here, but there is no way to edit it, so when I enter wrong numbers I can't fix it. If we want to have this, we should create another issue for it.

**Comment by MartinWahnschaffe** [comment]
### Implementation Notes
Add an agegroups field to the disease configuration that allows to define a comma separated list of age groups. Each age group is defined following a simple pattern:
X_YZ, where X is the "from" age, Y is the "to" age (both inclusive) and Z is the age type (D: days, M: months, Y: years).
You can leave the _Y away to define an age group of X+.

Examples:
0_28D: "0-28 days"
1_12M: "1-12 months" 
1_4Y: "1-4 years"
5_15Y: "5-15 years"
16Y: "16+ years"

When aggregated numbers are reported the related age group will be saved, so this aggregated report will always be specific to that age group. This way age groups are automatically "archived", because even when the age groups for a disease are changed, the existing entries will still use the old age group.
It also allows us to easily compare data across disease and SORMAS instances, given that the same age group is used.

@KristinaBorch @bernardsilenou Another question:
Do we really need an interface to define the age groups for the different diseases or would it also be an option to configure it in the database for now, given that the configuration itself is not too complicated?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe in response to this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/8967#issuecomment-1114639228
1. This is a very valid point. I think we should not **combine records reported by users with different user roles or jurisdiction limits.** This may lead to duplicate counts since the report submitted by SO should represent the sum of all reports from all informants in the districts and the similar for supervisors (representing the sum in a region).  In the current solution, the reports sent by National users or supervisors are added to those submitted by informants. This may lead to overcounting.
What about adding a user role as an entry to the aggregate report table + filter, this can be used to distinguish the reports. We must not validate if the reports submitted by SO is the sum of informants' report in the district of the SO. In practice, not all hospitals in a district may be using sormas, so the SO can get reports from some informants through sormas and others through paper or other means and compile a report for their district.
2. Yea, we would need to make this change. Unlike case-based reporting, even if there are many users in a region, district or facility, we should end up with only one report for a jurisdiction in a particular week. We would need all users in a jurisdiction to have full access to a report + option to edit a report + duplicate detection of reports. A first report created by a user is shared among all users in the same jurisdiction, others can only edit the report.
3. I found the same also and already mentioned it in point 2

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/8967#issuecomment-1114680955
I think we can go with the db configuration. The age group is not something that would change all the time so we may not even need to add an interface for it.

**Comment by MartinWahnschaffe** [comment]
The whole topic of allowing surveillance officers to create reports and changing the way reports are aggregated will have to go into separate issues, so I'll take if out of the description and title here.

**Comment by bernardsilenou** [comment]
@BarnaBartha  @AndyBakcsy-she 
Just want to remind what we discussed in the sprint today:
1. Mobile app: to map the jurisdiction of the reporting user as that of the report
2. Web app: to refill the default jurisdiction with that of the user
Please would it still be possible to add them before the release? Number 1 is the most important and urgent to have in this release

**Comment by MartinWahnschaffe** [comment]
Point 2 is covered by #9052
Point 1 used to be working before, so it looks like we need to look into this again and make sure it's working.

Remaining todo:

- [ ] Make sure aggregate reports created in the mobile app are automatically associated to the user's jurisdiction entities (facility, etc.)
- [ ] Make sure age group entries are also shown in the mobile app when there is already data for the disease for another or no age group.

PS: There was another issues in the review, that lead to the newly added age groups not showing up: The change date of the disease configuration was not updated.

**Comment by kwa20** [comment]
@MartinWahnschaffe @BarnaBartha We unfortunately don't have a wiki entry for diseaseconfigurations yet (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/7657).
I am a bit unsure about how to add the age groups in the form of a list into the database. Will this be similar to e.g. translations in customizableenumvalues? (cf. https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Customizable-Enumerations). If not, could you explain or give an example on how exactly this would need to be deposited in the db?

**Comment by MartinWahnschaffe** [comment]
@kwa20 Good point. I'll take care of creating this documentation. I have assigned #7657 to me.
