### ISSUE TITLE
Group aggregated reporting data (mSERS) by jurisdiction and epi week [5]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#8974]
### Situation Description

The aggregated reports view is currently only displaying (and exporting) the four columns disease, new cases, lab confirmations and deaths. The system always aggregates the numbers for the whole jurisdiction that is defined by filters, e.g. when filtering to a district, the numbers of all facilities are aggregated. This is not sufficient.

### Feature Description
The core requirement here is to group the data aggregation by jurisdiction and by epi week.

- [x] Add a grouping field for the jurisdiction. The field only allows to pick a jurisdiction level that is below or equal to the jurisdiction level used in the filters. E.g. when the data is filter to a specific district the available groupings would be district, facility and point of entry (see campaign statistics - there we have already implemented something similar).
- [x] Add a region column to the grid and depending on the grouping also columns for district and facility or point of entry. To do this extend the AggreagtedCaseCountDto and the backend logic that queries the data
- [x] Add an epi week column to the grid and dto. Always group the data by epi week, so when the date filter ranges across multiple epi weeks, each epi week will have entries in the resulting table
- [x] Add a disease filter (just single select)
- [x] The 0-rows, we are currently adding for disease that don't have reported numbers should stay and have to be extended to have one for every epi week. In terms of jurisdiction grouping and age groups don't add multiple 0-rows. Instead use the jurisdiction of the filter and no age group. 
- [x] Add checkbox "show 0-rows for groupings"
- [x] Make sure all of this reflects correctly in the export

![grafik](https://user-images.githubusercontent.com/23217632/169231720-25a3dfd4-8a2e-4ab2-890e-19c9f4ffae2b.png)

### Additional Information

[export_aggregate_module.ods](https://github.com/hzi-braunschweig/SORMAS-Project/files/8570715/export_aggregate_module.ods)

**Comment by KristinaBorch** [comment]
@bernardsilenou is this as intended?

**Comment by MartinWahnschaffe** [comment]
The current aggregate reporting view works as follows:

1. You pick optional regional filter(s) to drill down into the data as far as you please: region, district, facility/point of entry
2. You pick a date range based on epi weeks.

The system will aggregate the reported numbers based on these filters and then displays the following four columns:

* disease
* newCases
* labConfirmations
* deaths

@KristinaBorch @bernardsilenou Based on this I have a few questions.

1. There is currently no way to report numbers for a community. If we need to add this, please split it out into a separate issue. My guess is that you were mixing it up with point of entry?
2. I guess the region, district, facility and point of entry columns in the export should only be visible when the data is filtered to a certain region/district/facility, right? So when you look at the data for the whole district, the export will not have a facility column. Is this correct?
3. In the example you gave the data is grouped by epi week. So when I look at the data of three epi weeks it does not summarize them into one entry, but keeps them separate. I guess we should apply this change to the aggregation view in the web app, right?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
1. I think community is not needed for now.
2. Absolutely right. The same applies if we filter and end at region level
3. Yes please

**Comment by adinaflorea9** [comment]
As discussed with @sergiupacurariu  and @MateStrysewske, I am reopening the ticket due to the following:

- [ ] 1. Regarding the EPI weeks filters: if the user 'clears' the filters (sets them to the empty value from the dropdowns) and then click's 'Apply filters', a notification pops up letting the user know that 'The epiWeek filter is not filled correctly', and the reports are not filtered. 

 However, if afterwards the user closes that notification, navigates to any other directory, and then navigates back to the mSERS directory, the reports are now filtered with no epiWeek (all reports from all epiWeeks are shown in the list).
Expected behavior: when navigating out of the mSERS directory and back into it, the epiWeek related filters should be reset to their default values (both the ‘year’ and ‘Epi Week’ filter fields).

 - [ ] 2. If the user filters the reports based on region, district/ facility or point of entry, when they click 'Reset Filters' the values from the filters are reset, but the list of results is not (the reports remain filtered); this behaviour is not consistent with the behaviour from other directories, where if the users click reset, both the filter values and the lists or results are reset.

Expected behavior: both the filters and the list of results are reset.

 - [ ] 3. This is in regard to the 'Create new aggregate report form' - there are two flows that lead to some inconsistencies:

3.1. 
1. Click on 'new aggregate report';
2. In the 'Create new aggregated report' choose the option 'Specify';
3. Clear the ‘year’ and ‘epi week filters’;
4. Click 'Save'
-> the form just closes; no warning message or notification; no report is created -> the 'save' button basically does the same as the 'discard' button, because none of the fields are mandatory and the report is not created;

Expected: - at least the epi week related fields should be mandatory (this is based on the fact that a report with no date or no epi week would be pointless; and on the fact that when filtering the reports, it is required to have valid information selected in the epi week filter fields).

3.2. 
1. repeat the same steps as above until step 4;
2. add values to some of the diseases;
->general error message appears and the error is visible in the logs as well;
![image](https://user-images.githubusercontent.com/96909231/174035184-cf4494a7-def9-4f13-b76d-a1e0b130c8ba.png)
[logs mSERS error message.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8917409/logs.mSERS.error.message.txt)

=> this would be solved if the epi week related fields would be mandatory

3.3. The 'Region' and 'District' fields are not mandatory when creating a new report - if reports are saved without infrastructure data, then they can only be found when filtering by epi week, and disease; also, a report with no infrastructure data would not be valid? As the cases, lab confirmations or deaths for different diseases would have no 'jurisdiction'/ no place where they occurred.

- [ ] 4.The 'Facility' and 'Point of entry' filters allow the users to select 'Other facility' or 'Other airport/seaport/ground crossing' if there are no facilities or points of entry created in the jurisdiction.

However, in the 'Create new aggregate report form' the user is not given the option to select these values when creating new reports.

Expected: In the 'Create new aggregate report form':
- both for the ‘Facility’ and the ‘Point of entry’ the user should be able to select the values ‘Other facility’ / ‘Other airport/ seaport/ ground crossing’;

- additional fields should be visible if the users select the 'other' options - 'Facility Name & Description' and 'Point of Entry Name & Description'.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS  from the development branch - 1.74.0-SNAPSHOT(3316ffe).
