### ISSUE TITLE
Error appears when trying to delete a prescription linked to a treatment

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8978]
### Bug Description
Error appears when trying to delete a prescription linked to a treatment

### Steps to Reproduce

1. Login as one of the roles: NATIONAL_CLINICIAN,  CASE_SUPERVISOR, ADMIN
2. Edit/create a Case
3. Go to Therapy tab
4. Create a Prescription
5. Create Treatment from the Prescription created above
6. Open in edit mode the Treatment created 
7. Select Open prescription
8. Try to delete the prescription

### Actual Behavior
The prescription remains in edit mode without any effect and an error appear in the server logs

### Expected Behavior
When trying to delete a prescription linked to the treatment, a confirmation pop-up should appear asking if user wants to deleted also the linked treatment. If the answer is no, then the treatment will remain in the system as standalone. If the answer is yes, then the treatment will be deleted together with the prescription

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:
* User Role: NATIONAL_CLINICIAN,  CASE_SUPERVISOR

### Additional Information

[DeleteError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8572838/DeleteError.txt)
```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "prescription" violates foreign key constraint "fk_treatment_prescription_id" on table "treatment"
  Detail: Key (id)=(2298) is still referenced from table "treatment".
```

**Comment by FredrikSchaeferVitagroup** [comment]
@abrudanancuta Are you sure about the expected behaviour? Should the related treatment really be deleted without any additional warning?

**Comment by abrudanancuta** [comment]
> @abrudanancuta Are you sure about the expected behaviour? Should the related treatment really be deleted without any additional warning?

A confirmation pop-up could be a solution when trying to delete a prescription linked to a treatment

**Comment by FredrikSchaeferVitagroup** [comment]
There is another bug in the same functionality, btw: #8977. @abrudanancuta said one can currently just treatments and prescription as admin user.

**Comment by MateStrysewske** [comment]
@abrudanancuta @dinua @FredrikSchaeferVitagroup Ah, sorry, I didn't read the expected behavior properly. I agree that we need a pop-up there; if the user decides to not delete the treatments alongside the prescription, the treatments should remain in the system and we should instead remove the links to the prescription before deleting the prescription.

**Comment by abrudanancuta** [comment]
I updated the Expected behaviour

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because:
- The heading of the pop-up is cut off;
- The text contains grammatical errors;

![image](https://user-images.githubusercontent.com/89522688/168095338-0029fc1e-d265-4c07-bb1c-6210fa78df08.png)

Also, wouldn't it be a good idea if the pop-up would contain a 'x' (close pop-up) option? In case the user changes his mind about the deletion...Maybe @MateStrysewske or @kwa20 can decide if this would be desired or not.

**Comment by roxanamlendea** [comment]
The pop-up is too wide in the current form.
![image](https://user-images.githubusercontent.com/89522688/168998966-243ba9ed-fa1e-4463-893d-9a0cef569500.png)
