### ISSUE TITLE
Allow users to undo soft-deletion [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8990]
### Feature Description

Users can soft-delete core entities, samples and pathogen tests (see https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Manual-&-Automatic-Deletion#manual-soft-deletion), but it's currently not possible to undo this.

### Proposed Change

- [x] Add an undelete method to the AbstractDeletableAdoService. It should remove the deleted flag.
- [x] If #8162 is done, also clear the reason for deletion - otherwise move this todo over
- [x] For event: also undelete event participants
- [x] For case, contact and event participant: also undelete related samples
- [x] For sample: undelete related pathogen tests
- [x] When soft-deleting a sample don't remove the link to the lab message. Only remove this link when permanently deleting
- [x] Use the delete button in the UI to undelete entities. This should only be possible for users that are allowed to delete the entity in the first place. Replace the caption accordingly ("undo deletion").
- [x] Unit test this

### Acceptance Criteria

* An un-deleted case that was shared to an external surveillance tool is shown in the case directory when the onlyEntitiesChangedSinceLastSharedWithExternalSurvTool filter is applied

### Implementation Details

Related questions:

- Should an undeleted case automatically be sent to the external surveillance tool? 
  -> Undeleting the entity increments it's change date and thus should list is among the cases that have been changed since last shared.
- Can we automatically re-assign an undeleted sample to a lab message? Does this make sense? (seems unnecessary to me). What about the reference physician report to caseID?
 -> For the lab messages I have added a todo above. For the external message see bug ticket.

### Additional Information

Out of scope: **Important**: Undoing a soft-deletion will **not** recover links to previously related entities

**Comment by kwa20** [comment]
@MartinWahnschaffe I noticed that when opening manually deleted entities via the URL, the deletion configuration for other references is still displayed. We should probably display the period for the `MANUAL_DELETION` reference instead because that would be relevant when considering to undo the deletion.

<img width="209" alt="deletedCaseDeletionConfigDisplay" src="https://user-images.githubusercontent.com/70317594/168607773-a3b62a2d-1e80-4115-8265-9671af9821f7.PNG">

**Comment by MartinWahnschaffe** [comment]
> @MartinWahnschaffe I noticed that when opening manually deleted entities via the URL, the deletion configuration for other references is still displayed. We should probably display the period for the `MANUAL_DELETION` reference instead because that would be relevant when considering to undo the deletion.
> 
> <img alt="deletedCaseDeletionConfigDisplay" width="209" src="https://user-images.githubusercontent.com/70317594/168607773-a3b62a2d-1e80-4115-8265-9671af9821f7.PNG">
> 
> EDIT: @MateStrysewske I just saw this comment in the other issue [#8162 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8162#issuecomment-1092594143). Is this taken care of there?

Yes, it's taken care of in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8162

**Comment by MartinWahnschaffe** [comment]
> @MartinWahnschaffe @Jan-Boehme I further noticed that #8162 adds the following string: _You are about to mark this data for deletion. This action is irreversible._ However, it being irreversible is changed through this issue. We might also want to adjust the message accordingly.

Yes, good point. The correct message would be "You are about to mark this data for deletion. If referenced by other data in the system, those references will be removed, which cannot be automatically undone."

This referencing part is probably a bit vague. An example would be a sample that is shared between a contact and a resulting case. When the resulting case is deleted, but the contact is kept, the sample also has to be kept and thus is unreferenced from the deleted case.

I'm not sure how far we should go in this dialog: Not mention removal of references at all vs. generic mention vs. detailed explanation (which may be too much for this dialog).

**Comment by kwa20** [comment]
@MartinWahnschaffe If we can't undo manual deletions so that entities will be the same before the deletion, wouldn't this be a huge problem? This would mean that we always extensively change the entity that we undelete.

**Comment by MartinWahnschaffe** [comment]
I don't think this would be a huge problem:

1. Manual deletion should be something that rarely happens and mostly to data that is not highly referenced by other data
2. Undoing deletion should be something that is done even more rarely
3. The most important links are those between cases and contacts - those can manually be re-created

**Comment by kwa20** [comment]
@MartinWahnschaffe After describing the current implementation and future prospects with the data security team, they informed us about the necessity of a reason field for recovered entities (i.e. for un-doing deletions). Is this already mentioned somewhere?

**Comment by MartinWahnschaffe** [comment]
No, this is new. Does this mean that the previously defined deletionReason+otherDeletionReason should also not be cleared?
Should the reason field just be a text field?

**Comment by kwa20** [comment]
@MartinWahnschaffe I think we probably have to clarify the clearing of the deletion reason with the data security team but for the revovery reason, this can just be a free text field.

**Comment by roxanamlendea** [comment]
Started the testing for this ticket and I'm reopening the ticket because so far I've found the following issues:

1) The text in the deletion pop-ups still says that the action is irreversible. The text 'You are about to mark this data for deletion. If referenced by other data in the system, those references will be removed, which cannot be automatically undone.' only seems to be implemented for the Deletion of Contacts in Bulk. This needs to be applied for all the entities which can be undeleted.

![image](https://user-images.githubusercontent.com/89522688/198049963-38f5f1fb-6826-4912-a95e-49a108e0978b.png)

2) Undoing the deletion of Travel Entries results in an error message:
[logs for undo deletion of travel entries.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9870343/logs.for.undo.deletion.of.travel.entries.txt)

Steps to reproduce:
1.Open a Travel Entry;
2.Copy the URL;
3.Delete the Travel Entry;
4.Paste the URL to open the page of the deleted Travel Entry;
5.Click on 'Undo Deletion'
-> The error message is thrown and the Travel Entry doesn't get undeleted.

![image](https://user-images.githubusercontent.com/89522688/198050531-724a9198-6be4-4cd0-871d-52db17731f4b.png)

3) 'Undo Deletion' is not possible for Samples:

Steps to reproduce:
1.Open a Sample;
2.Copy the URL;
3.Delete the Sample;
4.Paste the URL to open the page of the deleted Sample;
-> there's no 'Undo Deletion' button:

![image](https://user-images.githubusercontent.com/89522688/198051106-eaea3e39-5e50-496a-82a4-7cacc707fd11.png)

4) Deleted entities are editable:

Steps to reproduce:
1.Open a Case;
2.Copy the URL;
3.Delete the Case;
4.Paste the URL to open the page of the deleted Case;
-> The Case tab is read-only, but the other tabs are editable.

**Comment by JaquM-HZI** [comment]
Just to be sure, the only way to use this feature till: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8465 is implemented, would be to know the URL of the deleted case?

**Comment by roxanamlendea** [comment]
@JaquM-HZI Yes.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT.
The Surveillance Tool part could not be tested because SurvNet is not testable on our testing instances.

While testing this ticket, I noticed that some relations are kept and some are broken when soft deleting an entity. Even though it was not in scope for this ticket (as it is noted in the ticket description, '_Out of scope: Important: Undoing a soft-deletion will not recover links to previously related entities_'), I documented them and at @MartinWahnschaffe 's suggestion, I'll leave them as a comment here:

1. Tasks

a) When a Case / Event / Travel Entry is deleted and then un-deleted, the Tasks are still displayed on the Case page;
b) When a Contact is deleted and then un-deleted, the Tasks are no longer displayed on the Contact page;


2. Samples

a) Sample associated with a single entity - delete and undelete the Sample -> the Sample is still linked to the entity
b) Case OR Contact OR Event Participant + Sample which was not used for a resulting Case - delete and undelete the Case/Contact/EP - the Sample is still linked to the entity
c) Contact + Sample + resulting Case - delete and undelete the Sample -> the Sample is still linked to both Contact and Case
d) Contact + Sample + resulting Case - delete and undelete the Case OR the Contact -> the Sample is unlinked from that entity;
e) Event Participant + Sample + resulting Case - delete and undelete the Sample -> the Sample is still linked to both Event Participant and Case
f) Event Participants + Sample + resulting Case - delete and undelete the Event Participant -> the Sample card is still displayed on the Event Participant page, the Case id is still displayed on the Event Participants tab and the Sample is still displayed on the Case page
g) Event Participants + Sample + resulting Case - delete and undelete the Case -> the Sample and the Event are no longer displayed on the Case page and Case id is no longer displayed on the Event Participants tab, so the link is lost


3. Events

a) The Superordinate Event link is still kept
b) The Subordinate Event link is not kept
c) In order to delete the Event, Event Participants have to be deleted first - when the Event is undeleted, the Event Participants are also restored
d) Case that is also an Event Participant - delete and undelete the Case -> the Event Card is no longer displayed on the Case page
e) Contact that is also an Event Participant - delete and undelete the Contact -> the Event Card is still displayed on the Case page


4) Travel Entries

a) Travel Entry + Case - delete and undelete the Case -> the link is lost
b) Travel Entry + Case - delete and undelete the Travel Entry -> the link is kept


5) Source Case of Contacts

a) Create a Contact + Source Case - delete and undelete the Contact -> the link is kept (the Source Case is still displayed on the Contact page and the Contact is still displayed on the Contacts tab of the Case)
b) Create a Contact + Source Case - delete and undelete the Case -> the link is lost (the Source Case is no longer displayed on the Contact page and the Contact is no longer displayed on the Contacts tab of the Case)


6) Contact with Source Case

a) Create a Case and create a Contact with Source Case from the Epi Data Tab - delete and undelete the Case -> the link is lost
b) Create a Case and create a Contact with Source Case from the Epi Data Tab - delete and undelete the Contact -> the link is kept


7) Immunizations

a) Case + Immunization (Recovery; the Case is linked as the Recovery Case) - delete and undelete the Case -> the Recovery link is lost
b) Case + Immunization (Recovery; a previous Case is linked as Recovery Case) - delete and undelete the Case -> the Recovery link is still kept
