### ISSUE TITLE
Follow-up is automatically canceled for a Contact when a Case for a different disease is created by adding a positive Pathogen Test

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8998]
### Bug Description
When a user adds a positive Pathogen Test with a Disease different than the Contact's Disease, the Follow-up is automatically canceled, the 'Contact Classification' = 'Confirmed' and the 'Contact Status' = 'Dropped'

### Steps to Reproduce

1. Create a Contact with 'COVID-19' selected as Disease;
2. Create a Sample and add a positive Pathogen Test Result for a different disease (eg. Anthrax) and Save;
3. In the following pop-up choose 'Yes';
![image](https://user-images.githubusercontent.com/89522688/165762432-a0f7a89d-cd52-4ba2-860d-aba4669eb0d6.png)
4. Fill in the mandatory fields in the 'Create new Case' form and Save;
5. Navigate to the Contacts Directory and open the Contact created in step 1;
6. Check the Follow-up section, the Contact Classification and the Contact Status 

### Actual Behavior
The Follow-up of the Contact is cancelled, the 'Contact Classification' = 'Confirmed' and the 'Contact Status' = 'Dropped'

### Expected Behavior
The Follow-up, the 'Contact Classification' and the 'Contact Status' should not get changed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/165762156-876f120d-900b-4a72-8953-fe0f6aae7285.png)

![image](https://user-images.githubusercontent.com/89522688/165762844-61091a88-35eb-4df8-b198-15a7bb6457c1.png)

![image](https://user-images.githubusercontent.com/89522688/165763245-7012ba0b-a20a-440e-a74e-7df3ae420c90.png)

![image](https://user-images.githubusercontent.com/89522688/165763267-dd19a387-a479-45a8-a0cb-0e3b3f9bb4c4.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (f883c3f)
* Android version/Browser: Chrome
* Server URL: local env
* User Role: Admin, Nat User

**Comment by adinaflorea9** [comment]
Verified ticket on the latest version of SORMAS from the development branch - 1.72.0-SNAPSHOT(2c2678f). I am reopening the ticket due to the following behaviors:

I:
Steps to reproduce:
1. Create a contact with the disease Covid-19;
2. Add to the contact a sample with a positive pathogen test of Ebola Virus Disease;
=> pop-up to create an EVD case is triggered;
3. Create the new EVD case;
4. Navigate back to the contact from step 1 and open the sample associated with it; 
5. Delete the sample;
6. Navigate back to the contact from step 1 and add a sample with a positive pathogen test result of Covid-19;
=> pop-up to create a resulting case for the contact is triggered;
7. Fill in the mandatory information and save the resulting Covid-19 case.
8. Observe the sample card from the case page and the 'Follow-up status comment'.

Actual behavior:
There are 2 samples linked to the Covid-19 case from step 7 - the Covid-19 sample and the deleted EVD sample.
The 'Follow-up status comment' from the case page does not contain the information regarding the follow-up status of the associated contact ([System] Follow-up automatically canceled because contact was converted to a case).

Expected behavior:
There is 1 sample linked to the Covid-19 case from step 7 - the Covid-19 samples.
The 'Follow-up status comment' from the case page does contain the information regarding the follow-up status of the associated contact ([System] Follow-up automatically canceled because contact was converted to a case).

II:
Steps to reproduce:
1. Create a contact with the disease Covid-19;
2. Create a resulting case for it (either manually via the 'Create a case for this contact person' button or via a sample with a positive Covid-19 pathogen test result);
3. Observe the 'Follow-up status comment' section from the resulting case's page.

Actual behavior:
The 'Follow-up status comment' from the case page does not contain the information regarding the follow-up status of the associated contact ([System] Follow-up automatically canceled because contact was converted to a case).

Expected behavior: The 'Follow-up status comment' from the case page does contain the information regarding the follow-up status of the associated contact ([System] Follow-up automatically canceled because contact was converted to a case).

III:
1. Create a contact with the disease Covid-19;
2. Add a Covid-19 sample with a positive pathogen test result to it;
3. Create the resulting Covid-19 case;
4. Navigate to the 'Samples' directory and open the sample created at step 2;
5. Add a new pathogen test result of Anthrax to the sample;
=> pop-up to create a new Anthrax case is triggered;
6. Fill in the mandatory information and save the case;
7. Observe the 'Follow-up status comment' of the case form step 6.

Actual behavior:
The follow-up status comment is filled in with the information form the 'Follow-up status comment' of the contact from step 1.

Expected behavior:
The follow-up status comment of the case from step 6 should not be filled with the information from the 'Follow-up status comment' of the contact from step 1, as this is not the resulting case of the contact (no the case into which the contact has been converted).

**Comment by adinaflorea9** [comment]
@MateStrysewske Would you please be able to take a look over the following scenario and provide us some feedback regarding the expected behavior?

1. Creating a case via a sample with positive pathogen test result (Anthrax) for a contact (covid-19) leads to the information from the 'Follow-up status comment' of the contact to be copied into the new case (case which is not the resulting case of the contact and therefore not the reason for the contact's follow-up being cancelled) - I discussed this with @dinua and for this scenario we thought that all the information from the comment could be copied into the new case, except the part: ([System] Follow-up automatically canceled because contact was converted to a case).

2. If a contact (covid-19) has a resulting covid case, and the user adds more information afterwards in the follow-up status comment section, when the user creates another case of another disease for this contact, all the information from the 'Follow-up status' comment of the contact is copied into the case that is of another disease - including the section ([System] Follow-up automatically canceled because contact was converted to a case) - in this scenario, should the section 'system - follow-up automatically cancelled...' be copied into this new case of another disease?
![image](https://user-images.githubusercontent.com/96909231/168548802-3c89291f-40a8-4de7-943c-2a9b1452b5f3.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS  from the development branch - 1.74.0-SNAPSHOT(3316ffe).
