### ISSUE TITLE
Bulk Edit Mode in Contacts directory not consistently present for an Admin Surveillance Supervisor

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9020]
### Bug Description

The 'Bulk edit mode' in the 'Contacts' directory is not displayed for an Admin Surveillance Supervisor consistently. 

Bulk edit mode in the 'Contacts' directory for this user is missing on my local machine (which is set with country.locale - DE) and on test.sormas.netzlink.com (which should be configured to have the country.locale - International), but it is present on @roxanamlendea's local machine and on test-de2.sormas.netzlink.com.

### Steps to Reproduce

1. Log in with a user that is Admin Surveillance Supervisor;
2. Navigate to the 'Contacts' directory and click on the button 'More'

### Actual Behavior

The 'Enter bulk edit mode' button is not consistently displayed for the Admin Surveillance Supervisor across testing environments.

### Expected Behavior

The 'Enter bulk edit mode' button should be consistently displayed for the Admin Surveillance Supervisor across testing environments.

### Screenshots

My local machine:
![image](https://user-images.githubusercontent.com/96909231/165962851-443e1173-c46c-42b2-bdb4-79e73e1bb299.png)

Test-de2:
![image](https://user-images.githubusercontent.com/96909231/165962966-4346161d-74cb-4c93-beb8-b8570ceb3deb.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(bfaf3d6) - my local machine; 1.71.0-SNAPSHOT(8e38a60) - test-de2
* Android version/Browser: Chrome
* Server URL: local machine; test-de2.sormas.netzlink.com
* User Role: Admin Surveillance Supervisor

**Comment by StefanKock** [comment]
@adinaflorea9 is this a defect on a released version also?

**Comment by adinaflorea9** [comment]
@StefanKock this is still reproducible on:

- my local machine (where I now have version 1.72.0-SNAPSHOT(e6f0ecd) and country locale - DE - and bulk edit mode is **not** present in the 'Contacts' directory for an Admin Surveillance Supervisor);

- test.sormas.netzlink.com (1.72.0-SNAPSHOT(0866879) - country locale - EN - and bulk edit mode is **not** present in the 'Contacts' directory for an Admin Surveillance Supervisor);

- test-de2.sormas.netzlink.com (1.72.0-SNAPSHOT(0866879) - country locale - DE - and bulk edit mode **is present** in the 'Contacts' directory for an Admin Surveillance Supervisor.

The version where I initially observed this is 1.71.0.

**Comment by carina29** [comment]
@adinaflorea9 I've investigated the bug. 
There is a method based on which is decided in ContactsView the display/hiding of the "Enter bulk edit mode" button.

	private boolean isBulkEditAllowed() {
		return **viewConfiguration.getViewType().isContactOverview()**
			&& **(UserProvider.getCurrent().hasUserRight(UserRight.PERFORM_BULK_OPERATIONS)**
				|| **FacadeProvider.getSormasToSormasFacade().isSharingCasesContactsAndSamplesEnabledForUser())**;
	}

An Admin Surveillance Supervisor **does not have** the right to perform PERFORM_BULK_OPERATIONS by default ( this right is necessary in order to display "Enter bulk edit mode" button.
(Based on the code and the User Roles Table only the Admin has this right)
![image](https://user-images.githubusercontent.com/47103965/168811458-44cf3c6c-999d-4bd0-a5ac-6a48e377c2bb.png)
![image](https://user-images.githubusercontent.com/47103965/168811735-a002c517-c6bf-4e08-a588-e403103298d9.png)

**If** for somebody else ( or if on other environment) **the button appears means** => 
 1) viewConfiguration.getViewType().isContactOverview()   = true  which means that the 
Contacts is clicked:
![image](https://user-images.githubusercontent.com/47103965/168814210-5a0afdde-e9b4-436a-afe1-e825c3f56b51.png)

2) UserProvider.getCurrent().hasUserRight(UserRight.PERFORM_BULK_OPERATIONS  will be false (The Admin Surveillance Supervisor does not have this right) 

3) FacadeProvider.getSormasToSormasFacade().isSharingCasesContactsAndSamplesEnabledForUser()  this have to be true in order to after the evaluation of the isBulkEditAllowed() method display the button.

      **isSharingCasesContactsAndSamplesEnabledForUser() is true if** 
       3.1) SORMAS_TO_SORMAS_SHARE_CASES_WITH_CONTACTS_AND_SAMPLES is set to true in the DB (featureconfiguration 
       table)
       ![image](https://user-images.githubusercontent.com/47103965/168815455-14d820ce-d0ec-4946-95de-eba56a33f6cb.png)
       **AND**
       3.2) isFeatureEnabledForUser() = true
                  **isFeatureEnabledForUser() is true if** 
                     3.2.1) The user has SORMAS_TO_SORMAS_SHARE  right  (Admin Surveillance Supervisor has this right)
                     3.2.2) isFeatureConfigured() = true ( this means that in S2S is configured - the path is given and is not empty)


If the button appears/does not appear because of the above described conditions, the behaviour is the correct one and is not a bug. 

@adinaflorea9  Could you retest please with the above conditions if the button appears? 
We can also have a call if you want. :)
Thank you :)

**Comment by adinaflorea9** [comment]
The conditions that need to be met for the 'Bulk Edit Mode' to be displayed for an Admin Surveillance Supervisor in the 'Contacts' directory, presented by @carina29 in the above comment, are not met on the local machine that I am using.

When these conditions are met, the 'Bulk Edit Mode' is displayed in the 'Contacts' directory for the Admin Surveillance Supervisor.

I am discarding the issue as this behavior is dependent on whether the conditions are met or not.
