### ISSUE TITLE
Don't summarize aggregated report numbers with those of sub jurisdictions in the aggregate report view [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9068]
### Problem Description
The numbers shown in the aggregate report view always aggregate anything that lies within the filtered/grouped jurisdiction. This means a reported created for a district would be summed up together with reports for facilities in that district.
This is borderline wrong and unintuitive for users. 

### Proposed Change

- [x] No longer combine reports of different jurisdiction levels in the report view of the UI. E.g. when data is aggregated on district level, the system will rely on the reports directly created for the district and only fall-back to aggregating facility-level reports, when there is no report for the district.
- [x] When there are duplicate entries for the exact same jursidiction (e.g. facility) pick the younger one (latest changeDate). A duplicate detection will be added in a separate issue.
- [x] Add a reporting user column to the grid (AggregateCaseCountDto). It should display the user for all rows that were directly reported and are not aggregated. So for facilities and poe it will always show a user, for district, region and whole instance only if there is a direct report for that jurisdiction.

### Implementation Suggestion

1. Query all reports that lie within the filter criteria AND have a jurisidiction below or equal to the grouping level. E.g. when data is filtered to one region and grouped by district, query all reports that are associated to the region AND have at least a district defined. This means reports created directly for the region itself would not be a part of this.
2. The results should be sorted by jurisidiction - starting with those that don't have a sub-jursidiction defined. E.g. A report for the district itself would be in the list before a report of a facility in the district.
3. Go through the reports to aggregate them based on the grouping. 
  * When a district is covered by a direct report for that district ignore all reports for sub-jurisdictions
  * When a district is not covered, summarize all reports for facilities and poes

If the grouping is done by region or even the whole instance, the same needs to happen: When no direct region report exists, summarize all direct district reports. If for one of those districts no direct report exists, summarize all facility and poe reports.

Note: All of this also has to take into account grouping by epic weeks. To achieve this I'd suggest to simply repeat this process for each epi week.

Alternative: Try to directly handle the aggregation with SQL queries or at least to filter our reports that are not needed because we already have a report for the parent jurisdiction.

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou "When there are duplicate entries for the exact same jurisdiction (e.g. facility) pick the younger one (latest changeDate). A duplicate detection will be added in a separate issue."
Is this ok for you? 
If you want we could introduce another column that flags when duplicates exists that were ignored for aggregation.

**Comment by bernardsilenou** [comment]
> @bernardsilenou See one of the todos above: "When there are duplicate entries for the exact same jurisdiction (e.g. facility) pick the younger one (latest changeDate). A duplicate detection will be added in a separate issue."

 :+1: 
> Is this ok for you? If you want we could introduce another column that flags when duplicates exists that were ignored for aggregation.

I think we can flag if there is a duplicate only when the user wants to create a new report, no need to add the flag in this aggregate view for now. Maybe we can later add some form of duplicate detection bulk action = flag + option to view the duplicate reports and choose one.

**Comment by StefanKock** [comment]
Finding concerning sync by @adinaflorea9 and @sergiupacurariu to be documented.

**Comment by adinaflorea9** [comment]
As discussed with @sergiupacurariu, I will move the ticket back into the testing lane without any other changes made to the current behavior, at this time.

The current behavior is the one that is descried below, in the flows presented:

I: 
1. Within the same epi week, create the following reports: Report1 with only the region set, Report2 with same region + district set, Report3 with same region + same district + facility set;
2. In the 'Aggregate reporting' tab - filter the reports based in the epi week from step 1 and then set the grouping to different values;
=> when grouping by 'Region' - Report1 is displayed;
=> when grouping by 'District' - Report2 is displayed;
=> when grouping by 'Facility' - Report3 is displayed.

II:
1. Within the same epi week, create the following reports: Report1 with only the region set, Report2 with the same region + district set, Report3 with the same region+ same district + facility set, Report4 with the same region + same district + another facility set;
2. In the 'Aggregate reporting' tab - filter the reports based in the epi week from step 1 and then set the grouping to different values;
=> when grouping by 'Region' - Report1 is displayed; + an aggregated report between Report3+Report4 is displayed;
=> when grouping by 'District' - Report2 is displayed; + an aggregated report between Report3+Report4 is displayed;
=> when grouping by 'Facility' - Report3 and Report4 are displayed.

III:
1. Within the same epi week, create the following reports: Report1 with only the region set, Report2 with the same region + district set, Report3 with the same region + another district set, Report4 with the same region+ same district + facility set, Report5 with the same region + same district + another facility set;
2. In the 'Aggregate reporting' tab - filter the reports based in the epi week from step 1 and then set the grouping to different values;
=> when grouping by 'Region' - Report1 is displayed; + an aggregated report between Report2+Report3 is displayed; + an aggregated report between Report4+Report5 is displayed;
=> when grouping by 'District' - Report2 and Report 3 are displayed; + an aggregated report between Report4+Report5 is displayed;
=> when grouping by 'Facility' - Report4 and Report5 are displayed.

In the ticket it is mentioned that: 
![image](https://user-images.githubusercontent.com/96909231/178699512-dfad150e-e7c5-40d1-bc4f-62d628a20c34.png)

The grouping for the 'whole instance' can be done by setting the 'Grouping' field to its empty value - however, by grouping based on this, the only report displayed is the latest report created within the set epi week.

For the expected behavior when grouping by the empty value/whole instance, as discussed with @sergiupacurariu we would like to have some input from @MartinWahnschaffe and/or @bernardsilenou.

**Comment by StefanKock** [comment]
@adinaflorea9 just close next time to move to Testing to not leave it open

**Comment by bernardsilenou** [comment]
@adinaflorea9 
Following https://github.com/hzi-braunschweig/SORMAS-Project/issues/9068#issuecomment-1182988376
I have not tested all the steps but one issue that I see is that an aggregate report can be created without a region or district by a national user for example.
1. Just as cases must have a region and a district, an aggregate report must also have both, no matter the user who created it. we can prevent users from creating such data.
2. We can also separate the creating and viewing/ grouping of the aggregate reports. Thus the issue that arises when filtering by region would not apply since all reports would have a region and district.
3. Since the main users who create such reports are SO (having no facility) and informant (having a facility), then we can make facility optional for a report. When grouping by facility, then report with Missing facility would not show up

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou I have create #9847 to take care of this. I think we should leave the user roles as-is, though. Why shouldn't a supervisor be allowed to create aggregated reports for the districts? Guess we can't fully rule out that this will be needed in the future and I don't see harm in it.
