### ISSUE TITLE
Allow mobile app users to view all mSERS reports related to their jurisdiction and to create new ones for sub-jurisdictions [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9084]
### Feature Description

Based on #9052 surveillance officers are able to create reports in the mobile and web app and to view reports of other users in their district in the web app. They currently have no way of viewing those reports in the mobile app.
In addition users in the mobile app are only able to edit their own reports. Not reports of other users in the same jurisdiction.

![grafik](https://user-images.githubusercontent.com/23217632/166877088-9acf5b38-1031-47f5-89f4-4c3e5b3fd0ff.png)

The general idea here is to allow users to allow viewing and editing in the same activity+fragment:

1. Users should have access to all reports of their jurisdiction and sub-jurisdictions
2. Users should be able to edit their own reports and to create new reports for sub-jurisdictions that don't have a report yet
3. Users should always be able to create a report for their own jurisdiction - even when another user has already created one. In this case there will later be a warning. See #9039

For facility and point of entry we would probably consider it a duplicate when another user has already submitted a report, but it might for example be the case that user A is responsible for one set of diseases and user B for another set of diseases.

We will achieve this by adding  a drop-down to the header of the aggregate report view in the mobile app that allows users to pick which report they want to view (or edit if they are allowed)

### Proposed Change

- [x] Create a method that provides the items for the drop-down. Each item is a combination of a jurisdiction entity (district, facility or poe) and optionally a user that has created an aggregate report for the selected epi week. The reason for this is that we (A) need to be able to select each jurisdiction entity, so we can view/edit the report for it and (B) there may be multiple entries for the same entity, provided by different users that we need to make accessible as-well
  The first item and default value for the drop-down should be district/facility/poe of the user himself
  Order should be: district, facility, poe and within each category alphabetically.
- [x] Add the drop-down below the epi week date selection. In the drop down display the name of the district/facility/PoE and if available the user (e.g. "Kamumba Hospital - John Doe").
  When the epi week changes the items in the list have to be refreshed. If the currently selected user is no longer in the list, fallback to the first item in the list
- [x] The aggregate report view should only be editable when either the reports of the current user are shown **or** no report was created for it yet. Simply make the fields read-only.

### Additional Information

Example for the drop-down as seen by a surveillance officer:

> "District A - You"
> "District A - John Doe" // other user in the same district has already created a report
> "Facility X - Jane Doe"
> "Facility X - Han Solo" // two hospital users have created a report for the same facility
> "Facility Y" // no user has created a report for the facility OR the report had only 0s

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou @KristinaBorch @Juliane-D

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(20f9576).

The duplicate detection pop-up that should be triggered when there already is an existing report within the same epi week and exact jurisdiction is not triggered in the mobile app - this is due to ticket #9039 not yet being implemented.

The users for testing were 'filtered' based on the following values:
- needed to be mobile app users (i.e. users that have the jurisdiction of district or below)
- user rights AGGREGATE_REPORT_VIEW and AGGREGATE_REPORT_EDIT = YES.

Behavior from ticket #9526 that is reproducible for Hospital Informant and Community Officer blocked me from testing the mSERS directory in the mobile app with these 2 users.

The users that were covered during testing were: Surveillance Officer, District Observer and POE Informant.
