### ISSUE TITLE
Surveillance Supervisors see the Buttons for deleting Pathogen tests while processing Lab Messages, but can not use them.

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#9198]
### Bug Description

Surveillance supervisors by default have the right to process lab messages (currently `LAB_MESSAGES`, [soon ](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8895)`EXTERNAL_MESSAGE_PROCESS`), but not the `PATHOGEN_TEST_DELETE`.

Still, when processing lab messages (in a certain way), they see buttons to remove new and already existing pathogen tests. Removing an existing pathongen test via such button throws an exception `User [user uuid]  is not allowed to delete pathogen tests.`

### Steps to Reproduce

1. As surveillance supervisor with default user rights, start processing a lab message.
2. Refer it to an existing person, case/contact/event-participant, and sample with at least one already saved pathogen test.
-> The `REMOVE THIS PATHOGEN TEST` buttons show.
3. Remove an already saved pathogen test via such button.
4. Try to save the case.
-> Above described exception gets thrown.

### Expected Behavior

`REMOVE THIS PATHOGEN TEST` buttons should be hidden for users without the `PATHOGEN_TEST_DELETE` right, but only for already saved pathogen tests. Unsaved pathogen tests should always be removable.

The default configuration for surveillance supervisors is a little weird then, regarding lab messages processing. But at least theoretically, they should still be able to process most lab messages. @kwa20 Do you agree?

### System Details

* Device: Windows
* SORMAS version: 1.72.0-SHAPSHOT
* Android version/Browser: Chrome
* Server URL: local dev system
* User Role: surveillance supervisor

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I generally agree. How about pathogen tests that did not exist previously but which the user adds? If they are not able to "cancel" he creation they might end up with more pathogen tests than intended or have to discard the process. If thats's the case. We might want to adjust this in a change request so that we differentiate between a new addition and editing of existing tests (similar to vaccinaitons mentioned in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8980)

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Good point, I adjusted the description.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.73.0-SNAPSHOT (a69d3d0)
