### ISSUE TITLE
Discard and save buttons overlap for point of entry cases in some languages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9224]
### Bug Description

On the case form of point of entry cases, the discard save buttons overlap for some user languages (e.g. german).
### Steps to Reproduce

1. Create a case with the origin point of entry but leave the place of stay empty
2. Scroll to the bottom of the page
3. Change the user language to e.g. german
4. Check the button display

### Expected Behavior

Buttons should not overlap
### Screenshots

<img width="395" alt="referPointOFEntryDisplay" src="https://user-images.githubusercontent.com/70317594/168803375-016258cb-68b4-4742-9a7b-57fb66e373b8.PNG">

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by dinua** [comment]
After a discussion with @MateStrysewske , it was decided to move a button in other place
![image](https://user-images.githubusercontent.com/4202109/171116942-8e0834fa-9f25-4585-b30e-568a270ec1cf.png)

**Comment by roxanamlendea** [comment]
The button is now moved and everything looks fine in German and English, but in French, the button is cut off.
![image](https://user-images.githubusercontent.com/89522688/172110548-6b0cc53a-2b1a-4912-8e89-9a4aef5202a1.png)
In Spanish it hasn't been translated yet.

**Comment by roxanamlendea** [comment]
I have found an issue that is probably related to the fix for this ticket. Since the 'Refer Case from Point of Entry' has been moved, the button is visible also for users that don't have the CASE_REFER_FROM_POE user right (eg. Community Informant, Contact Supervisor, Contact Officer etc.). When the user clicks on the button, nothing happens. However, the button should not be visible for them in the first place.

**Comment by roxanamlendea** [comment]
I have to reopen the ticket again because I have found another scenario in which the 'Refer Case from Point of Entry' should not be visible anymore.
After the user successfully refers case from point of entry, the button should disappear, but it doesn't. When the user clicks on the button, nothing happens.

![Refer from POE 2](https://user-images.githubusercontent.com/89522688/173371976-a77290f1-c841-4fa2-80e9-ba6b3b7b7072.gif)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.73.0-SNAPSHOT from the development branch (0fc81d1)
