### ISSUE TITLE
Samples aren't validated in the backend when they're saved

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#9276]
### Bug Description

We have a `validate` method in SampleFacadeEjb which is however not called in `saveSample`. This makes it possible to push samples to the system via ReST that are not associated to any case, contact, or event participant.

### Expected Behavior

`validate` should be called in `saveSample` to prevent this.

**Comment by kwa20** [comment]
@MateStrysewske We also noticed that samples can be created without a laboratory
<img width="597" alt="samplesNoAssociation" src="https://user-images.githubusercontent.com/70317594/169486684-e26e7bd3-3dff-4643-b89f-f68b38ff5eac.PNG">

Not sure if this is also covered by the validation.

**Comment by MateStrysewske** [comment]
Likely, but we'll definitely double check.

**Comment by roxanamlendea** [comment]
I tried creating a Sample via API calls in Postman and I found out that the validation only checks if the mandatory values have been filled in, it doesn't check if they exist.
For example, I can create a Sample via Postman with an inexistent associatedCase uuid.
@MateStrysewske Should this be fixed in this ticket or should I open a different one?

**Comment by MateStrysewske** [comment]
@roxanamlendea Open a new bug issue for that please :)

**Comment by MateStrysewske** [comment]
@richardbartha I suppose that's the issue you talked about?

**Comment by richardbartha** [comment]
I would say yes!

**Comment by roxanamlendea** [comment]
@MateStrysewske @richardbartha Ok, I'll open a new ticket for this.
I cannot create a Sample with associatedCase being empty, but I can create a Sample with an inexistent uuid for associatedCase.

**Comment by richardbartha** [comment]
Validate dto gets called when creating sample with api calls but that does not solve the underlying issue since creation of samples that are not associated to any case, contact, or event participant is still possible but this will be fixed with #9541. Issue of internal sample creation for #9517 is fixed.
