### ISSUE TITLE
Person name filter on sample directory should work with event participants and cotacts

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#9291]
### Bug Description

The sample directory has a filer called "sample id/name, case," to search samples linked to a person by providing the name of the person. The filter does not work for an event participant or contact person name but does for case person.
### Steps to Reproduce

1. create a sample of an ep of contact, make sure that the sample is not lined to a case.
2. go to sample search and search  for the  sample using the name of the person

### Expected Behavior

filter should consider names of person no matter their linked entity type
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/169569143-ed12ab37-6a1a-4af1-b083-4715a84e8ded.png)

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser: web
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: national user + admin

**Comment by kwa20** [comment]
@bernardsilenou @JaquM-HZI This issue is similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/2705, https://github.com/hzi-braunschweig/SORMAS-Project/issues/3104 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/8480. I suggest we check which parts might have been done already, which are still open, aggregate them in one issue and close the other ones.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.73.0-SNAPSHOT(c141ca3).
