### ISSUE TITLE
Adding vaccines to a contact in the mobile app leads to an error

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9332]
### Bug Description

In the mobile app, when a user tires to add a vaccine to a contact that has no jurisdiction, an error is triggered.

Contacts are synced to the mobile app with no jurisdiction if the contact has a source case that is classified as 'Not a case' (#7304), and the contact is created in the vaadin-app by the same user that is logged in the mobile app.

### Steps to Reproduce

1. In the vaadin-app, logged in with a Surveillance Officer, create a case that is classified as ''Not a case'; 
2. In the vaadin-app, logged in with a Surveillance Officer, create a contact and set as source case the case from step 1;
3. In the mobile app, logged in with a Surveillance Officer, trigger a synchronization with the server;
-> the contact from step 2 is synchronized; the case from step 1 is not synchronized;
4. Navigate to the 'Vaccinations' tab of the contact in the mobile app;
5. Click to create a new vaccine, fill in the mandatory fields and click 'Save'.

### Actual Behavior

An error appears and the new vaccine is not saved.

### Expected Behavior

Exclude contacts with source cases that are excluded from being synchronised to the mobile device (according to CaseService#createUserFilter) from calls to ContactService#createUserFilterWithoutCase if a mobile sync is done.

### Screenshots

Error message in the android-app:
![image](https://user-images.githubusercontent.com/96909231/170265390-54333ed8-7760-44ed-9384-8712411fc8cf.png)

Logs:
![image](https://user-images.githubusercontent.com/96909231/170265442-dbcc02fc-0e61-4d74-9222-443f4225697e.png)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(7810826)
* Android version/Browser: Chrome (vaadin-app); Android 11 (android-app)
* Server URL: local machine
* User Role: Surveillance Officer

**Comment by MateStrysewske** [comment]
@kwa20 @adinaflorea9 @bernardsilenou This is caused by the case no longer being synchronised to the mobile app (which is of course correct) and the vaccination trying to look into the responsible region of the source case when building the immunization as the contact itself has no jurisdiction.

I would suggest to exclude contacts with source cases that are excluded from being synchronised to the mobile device (according to CaseService#createUserFilter) from calls to ContactService#createUserFilterWithoutCase if a mobile sync is done. I believe that's reasonable because those contacts would likely not really be managed anymore anyway (since their case is not relevant). 

Does this sound fine?

HOWEVER, this might theoretically have a performance impact; it SHOULD not because we can reuse existing joins, but I'm not exactly sure. Whoever picks this issue should verify that it's not the case, and @StefanKock should probably have a quick look over the code and give his opinion.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.73.0-SNAPSHOT(0fc81d1).
