### ISSUE TITLE
Task - The task created from Event page by combination of the roles Surveillance Officer+Contact Officer is not visible in the Event form

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#9334]
### Bug Description
Task - The task created from Event page by combination of the roles Surveillance Officer+Contact Officer is not visible in the Event form

### Steps to Reproduce
1. As user having the roles Surveillance Officer+Contact Officer in combination open in edit mode an event
2. Create a task for the opened event
3. Look in the event form for the task created
4. Go to Task page and make a filter for the event context task

### Actual Behavior
Event task are not visible for this combination of role

### Expected Behavior
The task created should be visible at step 3
The task belongig to the context event should be visible at step 4

### System Details

* Device:
* SORMAS version: 1.73.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
The same issue appears if task is created from Travel Entry

**Comment by dinua** [comment]
@MateStrysewske will need more time to investigate this isuee

**Comment by MateStrysewske** [comment]
@dinua I've done some testing because the user filter was kind of messed up, and believe I've fixed the issue while doing so. Assigned you as the reviewer of the PR because you already had a look into this issue.

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because the combination of Surveillance Officer + Contact Officer user can only see the tasks that he created if they are assigned to certain users (like Admin, National User, National Observer etc). If he assigns the tasks to users like Admin Surveillance Supervisor, Event Officer, Surveillance Supervisor, Contact Supervisor, etc, the tasks are not displayed on the Event / Travel Entry page and in the Tasks Directory.
