### ISSUE TITLE
Contact Officer can not create a resulting case for an Event Participant and an error is triggered

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9345]
### Bug Description

An error is triggered when a Contact Officer tries to create a case for an Event Participant, if the Event Participant already has a case of a different disease than the disease of the event.

The Contact Officer does not have rights to edit event participants (EVENTPARTICIPANT_EDIT = NO), but the 'Create' button is clickable on the 'Event Participants' tab. 

### Steps to Reproduce

1. Log in with an Admin+NatUser and navigate to the page of an event participant associated with an event that has the disease set (Covid-19);
2. Add a sample with a positive pathogen test result for another disease (Anthrax);
3. Click yes in the pop-up 'Create case from event participant with positive test result?'; fill in the mandatory information in the 'Create new case form' that is triggered afterwards, and save the case;
4. Log in with a Contact Officer and navigate to the 'Event Participants' tab of the event from step 1;
5. Find the event participant from step 1 and click the 'Create' button from the 'Case ID' column;
6. Fill in the mandatory information in the 'Create new case' form and click 'Save'.

### Actual Behavior

An error message is displayed and the case is not saved.

### Expected Behavior

No error message should be displayed and the case should be successfully saved.

 
### Screenshots

![Screenshot 2022-05-25 171234](https://user-images.githubusercontent.com/96909231/170463790-c9719764-b23b-41b2-ad77-572742caa17a.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.73.0-SNAPSHOT(ac18965) 
* Android version/Browser: Chrome
* Server URL: local machine and release-international.sormas.netzlink.com
* User Role: Contact Officer

### Additional Information

This is also reproducible on release-international.sormas.netzlink.com where SORMAS version is **1.72.1.**

Logs from the local machine:
[stacktrace 26.05.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8778068/stacktrace.26.05.txt)

**Comment by MateStrysewske** [comment]
@adinaflorea9 @carina29 Discusses with @kwa20 that users with the CASE_CREATE and without the EVENTPARTICIPANT_EDIT user right should indeed be allowed to create a resulting case for event participants.

**Comment by carina29** [comment]
@MateStrysewske @adinaflorea9 I've investigated the bug and the problem is that cloneSampleForCase method is called which has SAMPLE_CREATE annotation on it. CONTACT_OFFICER does not have this right.
![image](https://user-images.githubusercontent.com/47103965/170975468-c6520af5-85c9-41e6-bc94-713c8cde08ee.png)
![image](https://user-images.githubusercontent.com/47103965/170975571-9a0ad8eb-8059-4aa5-8ef4-694a04dfb2ed.png)

The possible solutions would be the following:
1) add SAMPLE_CREATE right to CONTACT_OFFICERs
2) add a check and do the cloneSampleForCase only if the user has the SAMPLE_CREATE right ( the clone in this case will not be done for CONTACT_OFFICERs)
3) Add other annotation rights too on the cloneSampleForCase method

@MateStrysewske what do you think which option would be the best in this case? :)
Thank you very much!

**Comment by carina29** [comment]
I've talked with @MateStrysewske about the above mentioned problem and solutions. 
The outcome of the discussion was to add CASE_CREATE right too (besides the already existing SAMPLE_CREATE right) to the 
cloneSampleForCase method.
