### ISSUE TITLE
Add requested pathogen tests and additional tests [13]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#937]
- [ ] ~Move the samples list from case to this tab~
- [x] Add field: "Did patient test positive for any other infection?" and a "Specify" text field
- [x] Add a formular with the fields from section IV from the document referenced in #934 (specific tests associated with the case management process)

**Comment by MateStrysewskeSym** [comment]
![grafik](https://user-images.githubusercontent.com/23701005/51842661-b9322c00-2311-11e9-8088-8a81a3ada10c.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Ideas:

* Sample could have two chechkbox lists of sample tests and sample values to be tested
* SampleValues could hold all tested sample values and be shown below the sample tests. Add button to open an edit popup

- [ ] create mockup for extended sample creation/editing
- [ ] create mockup for sample values form
- [ ] create mockup for sample list in case view. Needs to display some info on tested sample values

**Comment by MartinWahnschaffeSymeda** [comment]
### Backend

- [ ] Rename SampleTestType to PathogenTestType
- [ ] Add AdditionalTestType with types from above
- [ ] Add field with list of requested pathogen tests. Serialize in single field (not in a separate table)
- [ ] Copy values from old suggested test type and remove that field
- [ ] Add field with list of requested additional tests. Serialize ...
- [ ] Add requiered yes/no fields (Boolean) "Request pathogen test" and "Request additional test"
- [ ] Rename SampleTest to PathogenTest
- [ ] Add AdditionalTest, containing fields for all addtional tests
- [ ] Add user right for additional tests

### UI

- [ ] Add UI fields for new data fields
- [ ] Only show requested additional tests field and yes/no fields when user has right. Otherwise set pathogen tests to yes and additional to no
- [ ] Hide pathogen tests when not requested
- [ ] Add list for additional tests. Hide when not requested
- [ ] Add form to create/edit additional test
- [ ] in case samples list give hint to user that additional tests exist

**Comment by MartinWahnschaffeSymeda** [comment]
Addition based on feedback:

- [ ] For test types don't use "Haemoglobinurea", but "Haemoglobin in urine", etc.
- [ ] limit test types to those that match the sample material

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] don't show "other" in requested list for now. In the long-term we may need a text field to allow requesting other types. For now users can use the comments form.
