### ISSUE TITLE
Follow-up until date does not get initially updated when entering a positive sample for cases or contacts

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9447]
### Bug Description

When a positive sample is added with a collection date before the report date of cases/contacts, the expected follow-up until date is updated but not the follow-up until date itself. However, if the sample is opened again and simply saved without having made changes, the follow-up until date is updated. This happens when either creating samples and pathogen tests step by step or if they are created in the same creation form.
### Steps to Reproduce

1.  Create a case/contact and set the report date to today
2. Check the expected follow-up until date and follow-up until date
3. Create a positive sample (+ positive pathogen test) and set the collection date to a date before the report date
4. Check the expected follow-up until date and follow-up until date again
5. Open the created sample and simply save the sample form without making any changes
6. Check the expected follow-up until date and follow-up until date another time

### Expected Behavior

The follow-up until date should get updated initially

### Screenshots

![sampleFollowUpUntil](https://user-images.githubusercontent.com/70317594/172667021-10d95758-e2a2-41cd-a18f-dd55f1b62b73.gif)

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Tested this ticket on Sormas 1.74.0-SNAPSHOT (88035d1) and I'm reopening it because the follow-up until date of the Contact does not get initially updated.

Steps to reproduce:
1. Create a Contact and set the Report Date to the current date.
2. Create a positive Sample and set the Collection Date to a date prior to the Report Date.
3. Check the Follow up dates of the Contact.
-> 'Expected Follow-up until' date gets updated, but the 'Follow-up until' date doesn't.

![image](https://user-images.githubusercontent.com/89522688/175935558-e1f472ab-96c3-4f6a-978d-6405848bc69b.png)

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because of a bug in the following scenario:

1. Create a Contact and set the Report Date to the current date.
2. Create a pending Sample with the Collection Date to a date prior to the Report Date + a positive Pathogen Test result.
3. In the 'Create case from contact' pop-up, click on 'Yes';
4. In the 'Create new case' form, click on 'Discard'.

-> The Follow-up Dates of the Contact don't get updated, even though the Sample's Final Lab Result is set to positive.

**Comment by syntakker** [comment]
This is in accordance with #3424: If a contact is converted to a case, the follow-up is canceled. No further update of follow-up dates is undertaken.
