### ISSUE TITLE
Add "Other health conditions" to clinical course [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#952]
After #938. See #934 

- [x] add entity to contain all conditions mentioned in the Lassa form
- [x] display on clinical course view of case (web)
- [x] ~also list pregnancy~

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig 
We have decided to leave pregnancy out of this form due to both technical and semantical reasons. We can't easily duplicate the pregnancy field from the case and simply also display it in the Other Health Conditions; we would have to actually create a whole new pregnancy field for Other Health Conditions and synchronize the data changes, which could be problematic. In the long-term, we'll find a way to display vital information such as pregnancy in a place that's always visible in each sub-sections of the case, but to actually edit the pregnancy status, the user would need to go to the case data tab and do it there.

Is this okay for you?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] move ClinicalCourseController.getClinicalCourseView to CaseController.getClinicalCourseComponent
- [ ] remove the Case prefix from the other case forms and views
