### ISSUE TITLE
[S2S] Remove decision between "personal data" and "sensitive data" [1]

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#9521]
### Problem Description

When sharing an entity the user currently is able to select two checkboxes "Exclude personal data" and "Exclude sensitive data".
Through the lens of privacy there is no difference between the two. All sensitive data is personal data as well.
For the users it is also difficult to know which fields are affected by which checkbox.

### Proposed Change

Remove the checkbox for "Exclude sensitive data".
If the box "Exclude personal data" is checked, it should have the same impact on the transferred data as if both boxes are checked in the current implementation.

### Acceptance Criteria

The checkbox is no longer visible in any of the "Share" popups.
When checking the box "Exclude personal data", all fields that have formerly only been excluded when checking "Exclude sensitive data" are not transferred to the other system.
When checking the box "Exclude" personal data, all fields that are not transferred right now are still not being transferred.

### Additional Information

@markusmann-vg Migration is out of scope

**Comment by Jan-Boehme** [comment]
@markusmann-vg FYI, as discussed yesterday in the weekly meeting with the privacy team.

**Comment by kwa20** [comment]
@Jan-Boehme @leventegal-she In the data dictionary, we distinguish between personal and sensitive data in the column called "Data protection". If we now only have the checkbox for excluding personal data which also include sensitive data, does that mean that personal and sensitive data are treated the same?
- If yes, we should probably also adjust the data dictionary accordingly
- If not, we could rename the checkbox caption as "Exclude personal and sensitive data"

**Comment by Jan-Boehme** [comment]
@kwa20 Yes, that's correct. In theory there is no need to differentiate between the two from a data protection perspective.
All data we marked as "sensitive" is also personal data. So it doesn't really make sense to handle them differently.

The data dictionary needs to be adjusted to reflect his change.

**Comment by kwa20** [comment]
@Jan-Boehme Judging by this pull request https://github.com/hzi-braunschweig/SORMAS-Project/pull/9913, the backend still contains the differentiation between personal and sensitive data. Since it is used for pseudonymization we might want to either adjust it in the backend in the long run and only then update the data dictionary accordingly. Since both types still exist, should we still mention them both in the check box caption?

**Comment by Jan-Boehme** [comment]
@kwa20 Yes, the backend still contains differentiation between personal and sensitive and it should be removed in the long run but for now I think it is enough to remove the difference from the UI and just keeping it in the background. Having personal and sensitive data mentioned in the UI always was a point of confusion for the users as they were not able to judge which one they need so they either checked both or none.

But I can see your point for not removing it from the data dictionary as long as it still exists in the backend.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on a peer testing session with Levi

**Comment by SahaLinaPrueger** [comment]
Because i have no possibility to test this on the nightlies: pls take care of things like:  
latitude ; longitude ; facility ; facility type ; postal code and check if this fields have to be included.
In the current testing the behaviour is not correct but i will not write a bug report because this issue is implemented and it could also be that my data protection dictionary (downloaded with an old SORMAS version) is not up to date.
Thanks in advance.
