### ISSUE TITLE
Hovering over the drop down "Type of Contact" in Line Listing for contacts does not show full text

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#9530]
### Bug Description

The drop down "Type of Contact" in Line Listing for contacts does not display the full text, so for the user it is more than difficult to choose an option. Regarding the comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/1521#issuecomment-867055893, hovering over the options should display the full text but when testing no text is shown. 

### Steps to Reproduce

1. Go to Contacts
2. Open Line Listing
3. Open drop down Type of Contact
4. Hover over the options

### Expected Behavior

Hovering over the drop down options should display the full text.  

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser: 
* Server URL:
* User Role:

**Comment by syntakker** [comment]
The tooltip feature for hovering over combo box items is not available for Vaadin 8.:
https://vaadin.com/forum/thread/17044583/mouseover-tooltip-for-combobox-items

Due to the end of the sprint and the planned release, PR #10105 provides a preliminary fix which increases readability of the combo box texts by increasing the width of the affected input fields.
Possibilities to provide the tooltip-on-hover feature within Vaadin 8 will be further investigated.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(56663e12).

The 'Type of Contact' field has been extended, as @syntakker specified in his comment. The entries from the dropdown are extended so the information is a bit more clear:

'Type of Contact' before:
![image](https://user-images.githubusercontent.com/96909231/185111342-4e72fd1d-c093-47df-9e0d-ffbe35cfba08.png)

'Type of Contact' after #10105
![image](https://user-images.githubusercontent.com/96909231/185110827-6d780b0b-6c86-4d43-9942-b791d66e5e73.png)
