### ISSUE TITLE
Physician's Report is called lab message in the messageDiseaseNotSpecifiedInLabMessage

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#9590]
### Bug Description

The messages says: `The tested disease of the lab message could not automatically be determined. Please manually verify that this lab message is about a disease to be dealt with in SORMAS.` This is confusing, as this also shows for physician's reports that are no lab messages.

### Steps to Reproduce

1. Start processing a physician's report without disease
-> A popup with the message shows

### Expected Behavior

The Messages string should be
`The tested disease of the external message could not automatically be determined. Please manually verify that this message is about a disease to be dealt with in SORMAS.`

### System Details

* SORMAS version: 1.74.0-SNAPSHOT (and probably 1.73.X)

**Comment by FredrikSchaeferVitagroup** [comment]
This can be verified on test-de2 and locally.
It may be a good idea to also check the german language string, as that one is the one mostly used for external messages. Please be aware that the fixed message string first has to be translated via crowdin for that.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch - 1.74.0-SNAPSHOT(c91f2a7).

I am reopening the ticket due to the following: in the vaadin-app the 'lab message' is still the term used for external messages. The places are the following:
    1. main list of messages in the directory -> 'Type' column -> 'Lab message' (is it expected that they are still called lab messages here? Or should it say simply 'message' or 'external message'?):
    
![Screenshot 2022-06-24 142212](https://user-images.githubusercontent.com/96909231/175544503-fd644b49-ecd5-4082-8146-66bbe4dafe39.png)

    2. 'Pick or create entry' form triggered when processing a message:
    
![Screenshot 2022-06-24 142159](https://user-images.githubusercontent.com/96909231/175544566-ccb59c39-701d-43dc-a44d-5f39c007e050.png)

    3. 'Pick or create person' form triggered when duplicate detection for persons is triggered when processing a message:
    
![Screenshot 2022-06-24 142148](https://user-images.githubusercontent.com/96909231/175544605-d4faffd6-52a6-4fae-86be-d124b9dfe3d5.png)

    4. On 'Case page'/ 'Contact page'/ 'Event Participant page' -> 'Samples' card of entities created via processing a message -> hover over the 'Message' icon:
    
![Screenshot 2022-06-24 142206](https://user-images.githubusercontent.com/96909231/175544640-1f45fd09-bcd8-45f3-8251-eccc30cf9a9f.png)

   Note - this is reproducible when the language is set to German as well.

**Comment by adinaflorea9** [comment]
After a call with @FredrikSchaeferVitagroup where he has explained the places in which the 'lab message' value should still appear, it has been decided that only point 3 from my comment should still be fixed:

![image](https://user-images.githubusercontent.com/96909231/176118626-b919eed5-9c04-4bfe-abc0-be6f7beee61d.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(c92114e). 

When processing a lab message or physician's report that has no disease, the message string now states 'external message', as discussed with @FredrikSchaeferVitagroup.

In the forms/pop-ups triggered when processing messages, depending on whether a lab message or a physician's report is processed the message strings refer specifically to lab messages/messages or external messages. 

Verified on a DE server, with the languages English and German.
