### ISSUE TITLE
User roles should have optional link to default user role [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9645]
### Problem Description
Default user roles are changed over time when new user rights are added, existing rights removed or user right configurations changed/fixed.
So far we have tried to migrate these changes by automatically applying new user rights to existing user roles based on their existing user rights. Most often this works fine, but sometimes it doesn't work,. An example for this is #8892: External lab users need to receive the right to see sensitive data, but there is no way to generically decide about this based on other user rights of a user role.

### Proposed Change

- [x] Give the user role entity a new field `linkedDefaultUserRole` that maintains a link to the default user role that was used to create this user role.
  For future migrations, when a change is made to the default user role, all user roles that are linked to it are changed accordingly.
- [x] The default user role + default user logic that is currently relying on the user captions needs to be changed to use this new fields instead, to make it more resilient. See implementation details.
- [x] Edit form: The user can either remove the link to the default user role or even set it for a user role that was manually created.
- [x] "Apply user role template" is visible in both the main and notifications edit view and opens a popup with a drop-down to select the user role, including the description we use in the creation form. When a "linked default user role" is selected in the edit form, it is used as the default value for the drop-down in the popup.
- [x] Creation form: Move the user role template info to the right side of the template selection drop-down.
- [x] Creating a user role based on a template or applying a template should also fill the "linked default user role" field. Either to the used default user role or to the linked default user role of the template.

#### Edit Form
![grafik](https://user-images.githubusercontent.com/23217632/181022423-f5933fd8-a7f8-48cf-997a-ea10f6465ff7.png)

#### Creation Form
![grafik](https://user-images.githubusercontent.com/23217632/181023384-baabb74a-3ab2-411b-932c-3e3696c395b9.png)

### Acceptance Criteria
* The automatically created user roles on existing systems and on newly setup systems are correctly linked to the default user roles.

### Implementation Details

- [x] The INSERT statement in the 460 schema update should set the correct linked default user roles
- [x] StartupShutdownService.fillDefaultUserRoles should use the linked default user role instead of the caption
- [x] Same for StartupShutdownService.upgrade to 469 and 471
- [x] Same for the calls to StartupShutdownService.createOrUpdateDefaultUser and createAndPersistDefaultUser - which should probably be unified.
- [x] Add a new schema version update that set's the linkedDefaultUserRole based on the caption for those user roles that don't have it yet. This is only relevant for systems that have already rolled-out schema version 460+

**Comment by adinaflorea9** [comment]
As discussed with @BarnaBartha I am reopening the ticket due to: 

- [ ] When a "linked default user role" is selected in the edit form, it is used as the default value for the drop-down in the popup from "Apply user role template'', which currently is not populated.

- [ ] Creating a user role based on a template or applying a template should also fill the "linked default user role" field. **Either to the used default user role** or to the linked default user role of the template (the highlighted part currently does not happen).

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:

When a "linked default user role" is selected in the edit form, it is used as the default value for the drop-down in the popup from "Apply user role template''. However, if the user then changes the selection in the 'Apply user role template' the changes are applied but the selection in the dropdown is not saved.

GIF of the behavior:
![Apply template](https://user-images.githubusercontent.com/96909231/188153051-3813cf4b-6233-4013-833f-cd272a455a85.gif)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(b4777e7).

**Comment by kwa20** [comment]
@MartinWahnschaffe When I apply a user role template via the new pop-up, an already set linked default user role does not get updated. Let's say I've created a new user role with the National User template, then the `linkedDefaultUserRole `field will be pre-filled with National User. If I then apply a different template to it via the new pop-up (e.g. Surveillance Officer), the linked default user role stays the same but the pre-selected rights were updated according to the selected template. Wouldn't this then mean that if the National User (Default) role gets adjusted via an update that the new user role which was then based on the Surveillance Officer may suddenly then have a lot more rights than before?

I'm not quite sure what the expected behaviour should be here.

![LinkDefaultUserroleTest](https://user-images.githubusercontent.com/70317594/189940023-57164849-864a-4e32-bf69-7aa791500845.gif)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to another scenario the following:

![image](https://user-images.githubusercontent.com/96909231/190076835-58c1fad5-9e9e-4544-9e40-1f59486ee83e.png)

The expected behavior that is described in the above point is no longer reproducible (setting a user role template that has an associated linked default user role, no longer fills the 'Linked default user role' field both when the field is empty or pre-filled).

Steps to reproduce:
1. Create a new user role that does not have a linked default user role;
2. Create a second user role that uses the template of the user role created at step 1;
-> the second user role will have the 'Linked default user role' field empty - ok
3. From the 'Apply user role template' button select a user role that has an associated linked default user role;
4. Save
=> the 'Linked default user role' filed on the page of the user role created at step 2 should be filled with the user role linked to the user role template selected at step 3.

![User roles linked](https://user-images.githubusercontent.com/96909231/190077697-e2e68a59-9f90-4b57-a5a2-befbd25a7d1e.gif)

**Comment by MateStrysewske** [comment]
@kwa20 That was tackled with my latest commit, the dropdown is no longer pre-filled with the linked default user role now, because that was misleading.

@adinaflorea9 Exactly, I removed this behaviour because of your last reopen. It's not possible to populate that dropdown with the value that was selected previously there, because we don't store it anywhere. So far, it has been pre-filled with the selected linked user role, but that leads to confusions because if you select and apply another template, having this pre-filling logic looks like this template was applied before, when it wasn't. Removing this behaviour removes a bit of convenience, but also removes this confusion.

**Comment by adinaflorea9** [comment]
@MateStrysewske Thank you for explaining this!

**Comment by AliciaRaber** [comment]
Tested on
