### ISSUE TITLE
Confirmed case classifications don't add up on dashboard for non-German instances

### ISSUE THREAD

**Issue by hschanze** [hzi-braunschweig/SORMAS-Project#9659]
### Bug Description
The number cases shown in the overview doesn't fit the sum of the cases down where the cases classes are listed. E.g. the overview shows 19 cases of measles but in the measles slide there are 17 "not yet classified" and 1 confirmed case.

### System Details

* Device: Windows 10
* SORMAS version: 1.72.1
* Android version/Browser: Firefox
* Server URL:https://test-fr-perf-02.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE

* User Role:Admin, National User

### Additional Information
Maybe the "Confirmed cases with no symptoms" are missing, because it seems that with them the numbers add up.
@bernardsilenou

**Comment by bernardsilenou** [comment]
- The computation of indicators on the dashboard should group the three categories (confirm, confirm with symptoms, confirmed with unknown symptoms) of confirmed cases as confirmed cases on non-DE instances.
-

**Comment by MateStrysewske** [comment]
Info for QA: This only happens when creating a case with one of the Germany-exclusive confirmed classifications on an instance configured with locale de-DE, then switching to another locale (e.g. en) and observing the counts on the dashboard.

**Comment by roxanamlendea** [comment]
Tested ticket on my local machine using the the latest version of Sormas 1.74.0-SNAPSHOT (57c7fde) from the development branch. I tested on the following country locales: DE, EN and FR, but I couldn't compare the numbers on the Dashboard to check if they add up because the following issue occurs: #9839. Due to the fact that the release has been done, I'm opening a ticket ticket for this issue.
