### ISSUE TITLE
POE Users should only see POE specific aggregated reports [2]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9703]
### Problem Description

The line from the below screenshot, from the AggregateReportService.java renders that if a user has national level jurisdiction, but is not a port health user as well, then it should return null and the user should be able to see all results/entities on a national level.
![image](https://user-images.githubusercontent.com/96909231/176871178-87fd5767-ee45-43ae-9898-af6a3dedeb70.png)

This is preventing the POE National User from seeing any aggregated reports, if they were not created by them, as this user has the 'jurisdictionlevel' = NATION, and also the 'porthealthuser' = true.

POE National User has the user rights AGGREGATE_REPORT_VIEW and AGGREGATE_REPORT_EDIT = yes.

#### Steps to Reproduce

1. Make sure that there are aggregated reports created (log in with an Admin+NatUser and create a couple of aggregated reports in various jurisdictions);
2. Log into the app with a POE National User and navigate to the 'mSERS' directory;
3. In the 'Aggregate reporting' or the 'Report data' tab, try to filter the reports.

#### System Details

* Device: Windows 10
* SORMAS version: 1.74.0SNAPSHOT(5e5b8ae)
* Android version/Browser: Chrome
* Server URL: local machine

#### Actual Behavior

POE National User can not see any aggregated reports if they were not created by them.

#### Expected Behavior

POE National User should be able to see aggregated reports on a national level.

### Proposed Change

- [x] port health users (based on UserRole.isPortHealthUser) should only be able to create aggregate reports for a specific point of entry, not for the district or region in general
- [x] port health users should only be able to list aggregate report data associated to a point of entry in their jurisdiction
- [x] same when further aggregating the data (e.g. on district or region level) - only consider data associated to a point of entry in their jurisdiction

**Comment by MateStrysewske** [comment]
@JaquM-HZI @kwa20 I guess the current behaviour is more or less "correct" because I can't recall there ever being a specification of which data the POE national user should see, so limiting them to the data they've created themselves made sense in this regard, even though it's definitely not the desired behaviour.

I would suggest to allow POE national users to see aggregate reports from all points of entry in the country, but not from any other jurisdictions (so, no reports from facilities and also no reports from regions or districts without a POE selected). It's possible that we would also need to change POE supervisors to only see data from points of entry, I'm not sure how they're implemented right now.

What's your take on this?

**Comment by adinaflorea9** [comment]
For POE Supervisor this is the current behavior: 

- the user is restricted based on jurisdiction that depends on region + district + point of entry;

- in the mSERS directory they can see reports from that jurisdiction (namely that region + district + all points of entry that are set in that region+district) but also reports that are from that region + district + facilities from that jurisdiction.

**Comment by bernardsilenou** [comment]
POE users can have full access to data related to POE in their associated jurisdiction only.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.77.0-snapshot on local setup
