### ISSUE TITLE
OHAOZARA_SO user not able to log in

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#971]

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Details please: 
1. What exactly is happening? The user enters name and password. What kind of error/problem is the android app reporting?
2. What version of the app is the user using?
3. Have you tried to give the user a new password?
4. Is this a new user account? If not: Did it work before?

**Comment by Chinedar** [comment]
1. The error "could not authenticate. Check username and password"  
2. version 1.11.1
3. Yes, a new password has been created. 
4. It is not a new user account. Worked well until last week. When the user adds a new case and tries to synchronize, the app goes back to authentication page. The already entered case disappears. 
5. We logged out and tried to log back in hence the login challenge.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Thanks for the details. 
Some ideas on what else you can try:

1. Make sure the server url is correct - should be https://sormas.org.ng/sormas-rest
2. Try to access https://sormas.org.ng/sormas-rest/info/version from a web browser. You should be able to login if user name and password are correct. Otherwise reset the password again.
3. If the app still doesn't work you can delete the app's data on the device using the app info screen from the android system (not from within sormas).

**Comment by MateStrysewskeSym** [comment]
@Chinedar Any news?

**Comment by Chinedar** [comment]
@MateStrysewskeSym yes this has been resolved. Cleared cache and we are in. Thanks.

**Comment by Chinedar** [comment]
@MateStrysewskeSym Yes this works now
