### ISSUE TITLE
Need to have date filter in contact directory [0.5]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#972]

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar @hzi-braunschweig 
By which date field should contacts be filtered? The date of report?
The date of last contact may also be interesting, but it's not a required field, so not every contact does have it.

**Comment by Chinedar** [comment]
Yes Martin, let's bring in the two; 1. Date of report, 2. Date of last contact (even though not required, this is helpful for review). Thanks!

**Comment by Chinedar** [comment]
@Martin sorry to bring this in here. Please throw more light on "reception date" among the date options.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar What do you mean by "throw more light on..."?

**Comment by Chinedar** [comment]
Please explain the rationale behind "reception date" again. conflicting opinions down here and we need to resolve it for everyone to be clear what exactly reception date means. Thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
Implementation:

- [ ] as in case: date and epi-week filters "from", "to" and a drop down to pick report or last contact date. Default: report date

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Kind of funny, because my expectation would be that you know better than us what this field is about. My understanding is that the date of reception is the point in time when the case form has been received by the surveillance supervisor (this originates from the paper form). This will makes less sense with SORMAS, since the supervisor is immediatly able to access the case.

@hzi-braunschweig What is your point of view on this? We plan to remove this as an option from the date filters. Do we need the field at all?

**Comment by MateStrysewskeSym** [comment]
- [ ] change info text
