### ISSUE TITLE
[Merging] When merging Cases with multiple Vaccinations, in some scenarios, some information gets lost

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9769]
### Bug Description
When merging 2 Cases that have multiple Vaccinations, some information of the 'Vaccination Info Source' gets lost:

As far as I can tell, the problem occurs ONLY WHEN ALL of the following conditions are met:
- both Case 1 and Case 2 have multiple vaccinations (>1 vaccination each);
- all of them have the same Vaccination Date and Vaccination Name;
- the Vaccinations of the leading case have the 'Vaccination Info Source' set to null and the non-leading case has values set for the 'Vaccination Info Source';
- the Vaccinations are added in EXACTLY the specified order.

### Steps to Reproduce

Scenario 1:
1. Create 2 duplicate Cases;
2. For Case 1, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name):
       - Vaccination no. 1: 'Vaccination Info Source' is empty;
       - Vaccination no. 2: 'Vaccination Info Source' is filled in with the 'Vaccination Card' value;
       - Vaccination no. 3: 'Vaccination Info Source' is empty;
3. For Case 2, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name as Case 1):
       - Vaccination no. 1: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
       - Vaccination no. 2: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
       - Vaccination no. 3: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
4. Navigate to the Case Directory and click on 'Merge Duplicates';
5. Merge the Cases; Case 1 is the leading one.

-> Actual Behavior:
- 'A problem has occurred. The data could not be saved because it has been changed in the meantime' error message is displayed.
- The Vaccinations get merged, but the 'Vaccination Info Source' doesn't get filled in as it should. One is 'Vaccination Card', One is 'Oral Communication', and one is empty.

[stacktrace for merging.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9063701/stacktrace.for.merging.txt)

Scenario 2:
1. Create 2 duplicate Cases;
2. For Case 1, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name):
       - Vaccination no. 1: 'Vaccination Info Source' is empty;
       - Vaccination no. 2: 'Vaccination Info Source' is empty;
       - Vaccination no. 3: 'Vaccination Info Source' is filled in with the 'Vaccination Card' value;
3. For Case 2, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name as Case 1):
       - Vaccination no. 1: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
       - Vaccination no. 2: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
       - Vaccination no. 3: 'Vaccination Info Source' is filled in with the 'Oral Communication' value;
4. Navigate to the Case Directory and click on 'Merge Duplicates';
5. Merge the Cases; Case 1 is the leading one.

-> Actual Behavior:
- 'A problem has occurred. The data could not be saved because it has been changed in the meantime' error message is displayed.
- The Vaccinations get merged and the 'Vaccination Info Source' gets updated correctly: one ; Vaccination Card' and 2 'Oral Communication'

[stacktrace for merging cases 2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9063743/stacktrace.for.merging.cases.2.txt)

Scenario 3:
1. Create 2 duplicate Cases;
2. For Case 1, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name):
       - Vaccination no. 1: 'Vaccination Info Source' is empty; the rest of the fields are empty;
       - Vaccination no. 2: 'Vaccination Info Source' is filled in with the 'Vaccination Card' value; the rest of the fields are empty;
       - Vaccination no. 3: 'Vaccination Info Source' is empty; the rest of the fields are empty;
3. For Case 2, create 3 vaccinations (all of them need to have identical Vaccination Date and Vaccine Name as Case 1):
       - Vaccination no. 1: 'Vaccination Info Source' is filled in with the 'Oral Communication' value; also fill in the other fields ("Vaccine Type', 'Vaccine Dose', 'INN', etc;
       - Vaccination no. 2: 'Vaccination Info Source' is filled in with the 'Oral Communication' value; also fill in the other fields identical to Vaccination no. 1
       - Vaccination no. 3: 'Vaccination Info Source' is filled in with the 'Oral Communication' value; also fill in the other fields identical to Vaccination no. 1;
4. Navigate to the Case Directory and click on 'Merge Duplicates';
5. Merge the Cases; Case 1 is the leading one.

-> Actual Behavior:
- 'A problem has occurred. The data could not be saved because it has been changed in the meantime' error message is displayed.
- - The Vaccinations get merged and the 'Vaccination Info Source' gets updated correctly: one ; Vaccination Card' and 2 'Oral Communication'; also the other fields get updated correctly;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/177766071-5ae7fc17-1468-41cd-b89e-5e7a0a5bb847.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.74.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: admin, national user

### Additional Information
See @SahaLinaPrueger's comment in issue #9299

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by dinua** [comment]
@MartinWahnschaffe 
This bug happen because in the follow case there are more vaccines same as the one in the leading case. This will cause to make multiple saves to the same vaccine (the one in he leading case) and this is what will throw the error that the dto was saved meantime.
Right now we search in the follow case if there is a duplicate vaccine in lead case , if we switch the search we could avoid this problem (search in lead case vaccines if there is a duplicate vaccine) , but there is still a problem 

If we have a example like this

lead case : COVID 
   - vaccines : - date "7/1/2022" name "Pfizer" vaccination info source "empty"

follow case : COVID
   - vaccines : - date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card"
                      - date "7/1/2022" name "Pfizer" vaccination info source "Oral Communication"
				... (can be more with same date and name)
				
How the vaccines should be merge in this case ?
From witch vaccine we should take data or should we duplicate the vaccine ?

**Comment by dinua** [comment]
We discuss for this corner case when the vaccines have the same name and date and we came up with a solution to do multiple steps of merging vaccines. In the first step we merge all duplicates vaccines for the lead case, in the second step we merge all vaccines for the follow-up case and third step we merge the vaccines between cases. In the merge of vaccine in a case we will consider the latest changed/added vaccine as the lead vaccine (the one that will give the information if there are not null)
 Let's assume we have this extreme corner case :

Case 1 Lead Case COVID
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "empty" vaccine type "type1" vaccine dose "dose1" changed date "7/22/2022 12:00"
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" vaccine type "type1" inn "inn1" changed date "7/22/2022 13:00"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "Vaccination card" vaccine type "type1" vaccine dose "dose1" changed date "7/22/2022 12:00"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "empty" vaccine type "type1" vaccine batch number "123" changed date "7/22/2022 11:00"

Case 2 Follow Case COVID
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Oral Communication" vaccine type "type1" vaccine dose "dose1"  inn "inn2" unii code "987" changed date "7/22/2022 12:30"
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Oral Communication" vaccine type "type1" vaccine dose "dose1" changed date "7/22/2022 13:30"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "Vaccination card" vaccine type "type3" vaccine dose "dose1" changed date "7/22/2022 12:30"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "Oral Communication" vaccine type "type2" vaccine batch number "123" changed date "7/22/2022 11:30"

In the first step we are going to merge all duplicates for lead case , so it will looks like this :

Case 1 Lead Case COVID
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" vaccine type "type1" inn "inn1" vaccine dose "dose1" changed date "7/22/2022 13:00"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "Vaccination card" vaccine type "type1" vaccine dose "dose1" vaccine batch number "123" changed date "7/22/2022 12:00"

In the second step we are going to merge all duplicates for follow case , so it will looks like this :

Case 2 Follow Case COVID

- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Oral Communication" vaccine type "type1" vaccine dose "dose1" inn "inn2" unii code "987" changed date "7/22/2022 13:30"
- vaccine : date "7/5/2022" name "Moderna" vaccination info source "Vaccination card" vaccine type "type3" vaccine dose "dose1" vaccine batch number "123" changed date "7/22/2022 12:30"

In the third step we are going to merge vaccine between cases so the result case will look like this 

Case COVID
 - vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" vaccine type "type1" inn "inn1" vaccine dose "dose1" unii code "987" changed date "7/22/2022 13:00"
 - vaccine : date "7/5/2022" name "Moderna" vaccination info source "Vaccination card" vaccine type "type1" vaccine dose "dose1" vaccine batch number "123" changed date "7/22/2022 12:00"
 
Vaccinations duplicates merging rule
- when they are in the same case , the lead vaccine will be consider the latest one
- where they are in different cases , the lead vaccine will be consider the one in the lead case

The n-user is not going to see all of this steps , only the resulting case

**Comment by SahaLinaPrueger** [comment]
Thank you for this solution. My spontaneous thoughts about this:

If we take this solution please make sure, that this procedure only works for COVID-19 vaccines. For other infections it might be possible that it is correct that there exist multiple vaccinations on the same date with the same vaccine name. If we take this solution, we also have to implement a warning bevor merging: 'Please notice: If there exist multiple vaccines for COVID-19 on the same date with the same vaccine name in your leading case, there will be just one vaccination on this date with the same vaccine name after the merge. If you are sure that it is correct that there exist multiple vaccinations on the same date with the same vaccination name you have to write them down bevor merging and you have to edit them afterwards to the case manually.' 
I have to discuss this solution with @JaquM-HZI , because with this solution we correct errors for which the health departments are responsible and may not be errors. 
And one question according to step 1 and 2: Is there no possibility to make the vaccine with the most filled in entries as leading vaccine? 

alternative could be:
step 1: count number of vaccines with same date and same vaccine name of leading case
step 2: sort multiple vaccines with same date and vaccine name by latest change/added of leading case and get them in an order
step 3: count number of vaccines with same date and same vaccine name of follow up case
step 4: sort multiple vaccines with same date and vaccine name by latest change/added of follow up case and get them in an order
step 5: substract: number step 3 - number step 1
step 6: result 0 or less = perfect result -> follow step 7. result more than 0 -> follow step 6.1
step 6.1: if difference is 1 the last two vaccines in the order from step 3 in the follow up-case have to be merged. leading vaccine is the last one of the order. if difference is 2 the last three vaccines in the order from step 3 have to be merged. leading vaccine is the last one of the order. if difference is 3 the last four vaccines in the order from step 3 have to be merged and so on. After this follow step 7. 
step 7: merge vaccines from leading case and follow-up case in the order you sorted them in step 2 and 4. vaccine from leading case is always the leading vaccine. so the first vaccine from step 2 will be merged with the first vaccine from step 4. (if there exist less vaccines in follow-up case than in leading case some vaccines will not be merged)

But this are just my spontaneous thoughts. I will discuss them and give you feedback then.

**Comment by dinua** [comment]
Hello @SahaLinaPrueger 

Sorry to keep changing the details here ,but what I said before is no longer valid , that approach is way to complicated , it would involve to refactor the whole immunization merging and still could not respect all the new hints form your last comment. So I going to have a new approach that is easier and it is like this . 
If in the lead case we have duplicates vaccination (same name and date) we are going to leave them be , maybe there is a reason why it is like this . In the follow case if we find multiple duplicate vaccine we are going to merge only with the latest changed one . So here is an example of how this works : 
 
Case 1 Lead Case COVID

- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "empty" vaccine type "type1" changed date "7/22/2022 12:00"
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "empty" inn "inn1" changed date "7/22/2022 13:00"

Case 2 Follow Case COVID

- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Oral Communication" changed date "7/22/2022 12:30"
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" changed date "7/22/2022 13:30"

Result Case :
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" vaccine type "type1" changed date "7/22/2022 12:00"
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "Vaccination card" inn "inn1" changed date "7/22/2022 13:00"

In the merging process for all vaccines for lead case with date "7/1/2022" and name "Pfizer" we are going to merge with the vaccine from follow case with  vaccination info source "Vaccination card" (latest changed) and from here vaccine with vaccination info source "Oral Communication" will be ignored

**Comment by MateStrysewske** [comment]
@SahaLinaPrueger We'll go with the "latest change date" approach first; using the vaccination that has the most details filled in makes sense, but should be handled in a change request because it's a new functionality that's not yet implemented.

**Comment by SahaLinaPrueger** [comment]
@dinua shortly before you wrote this i spoke with @JaquM-HZI and we thought the following solution would be nice:
According to your comment yesterday: delete step one but step 2 and step 3 can be done. 

So: Vaccinations duplicates merging rules:

when they are in the same case (step 2), the lead vaccine will be consider the latest one
where they are in different cases (step 3), the lead vaccine will be consider the latest one in the lead case (without step 1 there could be multiple vaccines with same date and name in leading case, only the latest one will be merged with the vaccine from step 2).

Is this a possible solution?

Because of step one: The idea is very nice and we would like to define a feature request. In this feauture request we will create a  layout where the user can choose which vaccination they want to merge and which not. Then we do not need a warning message and we can implement this for all diseases. And this can be a preparation for person merge layout. So we will work on this and we are grateful for the nice idea.

**Comment by SahaLinaPrueger** [comment]
@MateStrysewske so we can open a change request and have to mention, that this change request refers to this issue. Probably the change request will be implemented after this issue is closed, so by implementing the new change request the merging for vaccination has to be changed in retrospect. That would be the correct procedure, am i right?

**Comment by dinua** [comment]
Hello @SahaLinaPrueger 

I have already created a version of fix as I said yesterday (27.07.2022) as describe there
(to make easier to understand , let's assume all vaccines in both cases are duplicated , all of them have same name and date)
- if there are duplicates in lead case we leave them 
- from the follow case we take the latest changed vaccine
- in all vaccines from lead case we merge the latest vaccine from follow case. So the latest change vaccine from follow case is merged in all of his vaccine correspondents from lead case 

I hope this is ok

**Comment by SahaLinaPrueger** [comment]
To be honest the solution you described yesterday makes no sense to me in terms of content.
If we take the solution you described we are ignoring the other vaccinations in the follow-up case completely and it also makes no sense to merge the latest changed vaccine from the follow case with _all_ vaccines from the leading case. 

Is it possible to implement the solution i described yesterday? 
So first merge all vaccines from the follow up case (which have same date and name) and then only merge this vaccination with the latest changed vaccine from the leading case?

**Comment by MateStrysewske** [comment]
@SahaLinaPrueger Just to clarify: We don't merge the latest changed vaccinations from the follow case with ALL vaccinations from the leading case; instead, for EACH vaccination of the leading case, we check whether there is at least one duplicate vaccinations in the follow case, and if so, we use the latest changed vaccination among those duplicates for the merging.

**Comment by SahaLinaPrueger** [comment]
Yes and that is the problem. If you only use the latest changed vaccination among those duplicates for the merging you 1. ignore the other ones in the follow-up case (with same date and name) and 2. you use the information from one vaccine (last changed vaccination of follow-up case) a lot of times (for each vaccination of leading case with same date and name).

It would be nice if you can check if the solution i mentioned is possible to implement.

**Comment by dinua** [comment]
@SahaLinaPrueger 
Just to be sure , this is the behaviour desired ? Please correct me if I'm wrong

Case 1 Lead Case COVID
- _vaccine1_ : date "7/1/2022" name "Pfizer" vaccination info source "empty" dose "dose1" changed date "7/22/2022 12:00"
- _vaccine2_ : date "7/1/2022" name "Pfizer" vaccination info source "empty" dose "dose2" changed date "7/22/2022 13:00"

Case 2 Follow Case COVID
- _vaccine3_ : date "7/1/2022" name "Pfizer" **vaccination info source "Oral Communication" inn "inn1"** changed date "7/22/2022 12:30"
- _vaccine4_ : date "7/1/2022" name "Pfizer" **vaccination info source "Vaccination card" batch number "123" dose "dose99" ** changed date "7/22/2022 13:30"

Result Case :
- vaccine : date "7/1/2022" name "Pfizer" vaccination info source "empty" dose "dose1" changed date "7/22/2022 12:00"
- vaccine : date "7/1/2022" name "Pfizer" **vaccination info source "Vaccination card" dose "dose2" inn "inn1" batch number "123"** changed date "7/22/2022 13:00"

In the result case 
1) the vaccine from "12:00" will remain unchanged because there is an other duplicated vaccine (in the same case as it) that is newer as it
2) the vaccine from "13:00" will me merge with the infos from follow up case as that :
- it will take  vaccination info source "Vaccination card" from vaccine4 and Not "Oral Communication", vaccine3 is older as vaccine4
- it will take  batch number "123" from vaccine4
- it will take inn "inn1" from vaccine3
- it will Not change the value for dose because it is already set

Thank you

**Comment by SahaLinaPrueger** [comment]
Yes, but to be honest i also do not like this solution because of several reasons of content. 
I will discuss my doubts with my team, and then i will give you feedback. 
I am sorry that this issue is holding us up so much. There are decisions to be made here that, when we make them, we will follow up consistently on other issues. That's why i think it's good, in spite of everything, if we take longer once, but are all the quicker the next time.

**Comment by SahaLinaPrueger** [comment]
Result: we stay with the desired solution, which you have summarised correctly. It is possible to implement this @dinua ?

**Comment by dinua** [comment]
Yes , We stay with the last solution discuss here

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.75.0-SNAPSHOT (05a2661).
