### ISSUE TITLE
Hide disease variant on mobile app when there is none

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#9893]
### Bug Description

When the disease variant entry is empty in the DB, the UI element for "disease variant" on the web app is not shown. Disease variants appeared on the mobile app even for diseases that do not have a variant.

### Steps to Reproduce

1. Create a measles case on https://release-international.sormas.netzlink.com/ using the mobile app
2. Open the edit form and the system ask for disease variant

### Expected Behavior

Disease variants should appear only for diseases that have categories for variants in the db.
### System Details

* Device:
* SORMAS version: 1.73.2
* Android version/Browser:  A 11
* Server URL:  https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: surveillance + contact officer

### Additional Information

This may be an old issue before 1.73.2.  The web app works as expected, only the mobile app needs adjustment.

**Comment by roxanamlendea** [comment]
Reopening the ticket because of the following issue:

Note: Disease Variants are configured on my local machine;
In the mobile app, in Edit Mode, for Cases that only have a Disease selected, without a Disease Variant, it is displayed as if it had also a Disease Variant.

![image](https://user-images.githubusercontent.com/89522688/195368140-ec21b1fe-7ceb-4757-95d3-f7b39640af33.png)

I checked the Vaadin app and the DB, and the disease variant does not appear, which is correct, but in the mobile app it somehow appears preselected.

![image](https://user-images.githubusercontent.com/89522688/195368363-7c583a60-9144-49ba-a7ac-a0644e60a7a4.png)
![image](https://user-images.githubusercontent.com/89522688/195368384-122d38bc-4872-4866-b1f3-0052db68ced7.png)

**Comment by roxanamlendea** [comment]
Also, when the Disease Variants are not configured on my local machine at all, the 'Tested Disease Variant' dropdown (it is an empty dropdown) is displayed on the Pathogen Test page.

![image](https://user-images.githubusercontent.com/89522688/195384105-d0b0d580-f3b0-47b3-b628-10c38afc82af.png)

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 tablet connected to the local server on the latest version of Sormas 1.77.0-SNAPSHOT (8c31891)
