### ISSUE TITLE
Epi curve update on sormas dashboard

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#999]
The colour orde of the  the epi curve bars from below to top should be confirmed, probable, suspected and not yet calssified for all the bars.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Have you discussed this in the team? I feel like the most severe (i.e. confirmed) cases should be shown at the top because the users are reading from top to bottom and the topmost part of the bars naturally catches their attention before the others. 

@dta16 What's your take on this?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym No I agree with you Mate, It is ok the way it is. The not yet classified is not really part of the surveillance system and should not be the first item that is seen. Confirmed is prioritized on top and so on... @bernardsilenou We cant change this Bernard
